# Generated by Django 5.2.12 on 2026-08-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fixed_income", "0002_seal_research_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedIncomeR5InputReceiptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_id", models.CharField(max_length=192)),
                ("receipt_version", models.CharField(max_length=96)),
                (
                    "owner",
                    models.CharField(default="fixed_income", max_length=32),
                ),
                ("command_hash", models.CharField(max_length=64)),
                (
                    "assessment_id",
                    models.CharField(max_length=160, unique=True),
                ),
                ("input_set_id", models.CharField(max_length=160)),
                ("input_set_version", models.CharField(max_length=160)),
                ("input_set_hash", models.CharField(max_length=64)),
                ("policy_set_id", models.CharField(max_length=160)),
                ("policy_set_version", models.CharField(max_length=160)),
                ("policy_set_hash", models.CharField(max_length=64)),
                ("evaluated_at", models.DateTimeField(db_index=True)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("evidence_clock_graph_hash", models.CharField(max_length=64)),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fixed_income_r5_input_receipt",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("receipt_id", "receipt_version"),
                        name="fi_r5_receipt_identity_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("evaluated_at__lte", models.F("recorded_at"))),
                        name="fi_r5_receipt_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_use_for_decision", True),
                            ("owner", "fixed_income"),
                            ("research_only", True),
                        ),
                        name="fi_r5_receipt_safety_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FixedIncomeR5ResultModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_id", models.CharField(max_length=192)),
                ("result_version", models.CharField(max_length=96)),
                (
                    "owner",
                    models.CharField(default="fixed_income", max_length=32),
                ),
                ("command_hash", models.CharField(max_length=64)),
                (
                    "assessment_id",
                    models.CharField(max_length=160, unique=True),
                ),
                ("input_set_hash", models.CharField(max_length=64)),
                ("policy_set_hash", models.CharField(max_length=64)),
                ("input_hash", models.CharField(max_length=64)),
                ("output_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "available"),
                            ("blocked", "blocked"),
                        ],
                        max_length=16,
                    ),
                ),
                ("evaluated_at", models.DateTimeField(db_index=True)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("evidence_clock_graph_hash", models.CharField(max_length=64)),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relative_value_results",
                        to="fixed_income.fixedincomer5inputreceiptmodel",
                    ),
                ),
            ],
            options={
                "db_table": "fixed_income_r5_result",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("result_id", "result_version"),
                        name="fi_r5_result_identity_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("receipt",),
                        name="fi_r5_result_receipt_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("evaluated_at__lte", models.F("recorded_at"))),
                        name="fi_r5_result_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_use_for_decision", True),
                            ("owner", "fixed_income"),
                            ("research_only", True),
                        ),
                        name="fi_r5_result_safety_ck",
                    ),
                ],
            },
        ),
    ]
