# Generated by Django 5.2.10 on 2026-03-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("macro", "0010_exchangeratemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangeratemodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
