# Generated by Django 5.2.12 on 2026-08-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MacroFactorResearchResultModel",
            fields=[
                ("result_id", models.CharField(max_length=160, primary_key=True, serialize=False)),
                ("factor_version", models.CharField(max_length=160, unique=True)),
                ("target_code", models.CharField(db_index=True, max_length=160)),
                ("evidence_produced_at", models.DateTimeField(db_index=True)),
                ("pit_manifest_id", models.CharField(db_index=True, max_length=160)),
                ("pit_manifest_hash", models.CharField(max_length=64)),
                ("code_version", models.CharField(max_length=160)),
                ("parameter_version", models.CharField(max_length=160)),
                ("external_evidence_id", models.CharField(db_index=True, max_length=160)),
                (
                    "lifecycle_status",
                    models.CharField(
                        choices=[("research_only", "research_only"), ("retired", "retired")],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField()),
                ("research_only", models.BooleanField(default=True, editable=False)),
                ("must_not_use_for_decision", models.BooleanField(default=True, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "macro_factor_research_result",
                "indexes": [
                    models.Index(
                        fields=["target_code", "-evidence_produced_at"],
                        name="macro_factor_target_time_idx",
                    ),
                    models.Index(
                        fields=["pit_manifest_id", "lifecycle_status"],
                        name="macro_factor_manifest_life_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("research_only", True)),
                        name="macro_factor_result_research_only",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("must_not_use_for_decision", True)),
                        name="macro_factor_result_decision_blocked",
                    ),
                ],
            },
        ),
    ]
