# Generated by Django 5.2.12 on 2026-08-05 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("macro_factor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="macrofactorresearchresultmodel",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.CreateModel(
            name="MacroFactorRunArtifactModel",
            fields=[
                ("artifact_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("run_key", models.CharField(db_index=True, max_length=160)),
                ("run_version", models.PositiveIntegerField()),
                ("factor_version", models.CharField(db_index=True, max_length=160)),
                ("target_code", models.CharField(db_index=True, max_length=160)),
                (
                    "output_role",
                    models.CharField(
                        choices=[
                            ("current_state", "current_state"),
                            ("forward_expectation", "forward_expectation"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("produced_at", models.DateTimeField(db_index=True)),
                ("source_result_hash", models.CharField(max_length=64)),
                ("external_evidence_id", models.CharField(db_index=True, max_length=160)),
                ("external_producer_ref", models.CharField(max_length=500)),
                ("external_artifact_hash", models.CharField(max_length=64)),
                ("external_artifact_media_type", models.CharField(max_length=100)),
                ("external_artifact_content_length", models.PositiveBigIntegerField()),
                ("external_artifact_bytes", models.BinaryField()),
                ("request_hash", models.CharField(max_length=64, unique=True)),
                ("pit_manifest_id", models.CharField(db_index=True, max_length=160)),
                ("pit_manifest_hash", models.CharField(max_length=64)),
                ("dataset_hash", models.CharField(max_length=64)),
                ("benchmark_version", models.CharField(max_length=160)),
                ("benchmark_hash", models.CharField(max_length=64)),
                ("fixed_fmp_version", models.CharField(max_length=160)),
                ("fixed_fmp_hash", models.CharField(max_length=64)),
                ("cost_model_version", models.CharField(max_length=160)),
                ("cost_model_hash", models.CharField(max_length=64)),
                ("split_contract_version", models.CharField(max_length=160)),
                ("split_contract_hash", models.CharField(max_length=64)),
                ("plan_hash", models.CharField(max_length=64)),
                ("selection_protocol_version", models.CharField(max_length=160)),
                ("selection_protocol_hash", models.CharField(max_length=64)),
                ("metrics_protocol_version", models.CharField(max_length=160)),
                ("metrics_protocol_hash", models.CharField(max_length=64)),
                ("timing_policy_version", models.CharField(max_length=160)),
                ("timing_policy_hash", models.CharField(max_length=64)),
                ("code_version", models.CharField(max_length=160)),
                ("dependency_lock_hash", models.CharField(max_length=64)),
                ("parameter_version", models.CharField(max_length=160)),
                ("parameter_hash", models.CharField(max_length=64)),
                ("random_seed", models.PositiveBigIntegerField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField()),
                ("research_only", models.BooleanField(default=True, editable=False)),
                ("must_not_use_for_decision", models.BooleanField(default=True, editable=False)),
                ("must_not_execute", models.BooleanField(default=True, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="run_artifacts",
                        to="macro_factor.macrofactorresearchresultmodel",
                    ),
                ),
            ],
            options={
                "db_table": "macro_factor_run_artifact",
                "ordering": ["run_key", "run_version"],
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="MacroFactorLifecycleEventModel",
            fields=[
                ("event_id", models.CharField(max_length=160, primary_key=True, serialize=False)),
                ("artifact_hash", models.CharField(max_length=64)),
                ("factor_version", models.CharField(db_index=True, max_length=160)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("recorded", "recorded"), ("retired", "retired")],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("recorded_at", models.DateTimeField()),
                ("policy_version", models.CharField(max_length=160)),
                ("policy_hash", models.CharField(max_length=64)),
                ("reason_codes", models.JSONField()),
                ("evidence_hash", models.CharField(max_length=64)),
                ("previous_event_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("owner_attestation_id", models.CharField(blank=True, max_length=160, null=True)),
                ("owner_attestation_hash", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "owner_attestation_owner_ref",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "owner_attestation_media_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "owner_attestation_content_length",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "owner_attestation_issued_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("owner_attestation_bytes", models.BinaryField(blank=True, null=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField()),
                ("research_only", models.BooleanField(default=True, editable=False)),
                ("must_not_use_for_decision", models.BooleanField(default=True, editable=False)),
                ("must_not_execute", models.BooleanField(default=True, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_events",
                        to="macro_factor.macrofactorrunartifactmodel",
                    ),
                ),
            ],
            options={
                "db_table": "macro_factor_lifecycle_event",
                "ordering": ["artifact_id", "sequence"],
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="MacroFactorDatedOutputModel",
            fields=[
                ("output_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("artifact_hash", models.CharField(max_length=64)),
                ("factor_version", models.CharField(db_index=True, max_length=160)),
                ("target_code", models.CharField(db_index=True, max_length=160)),
                (
                    "output_role",
                    models.CharField(
                        choices=[
                            ("current_state", "current_state"),
                            ("forward_expectation", "forward_expectation"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("observation_date", models.DateField(db_index=True)),
                ("target_period_start", models.DateField()),
                ("target_period_end", models.DateField()),
                ("horizon_periods", models.PositiveIntegerField()),
                ("horizon_unit", models.CharField(max_length=160)),
                ("knowledge_as_of", models.DateTimeField(db_index=True)),
                ("produced_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("value", models.DecimalField(decimal_places=18, max_digits=38)),
                ("unit", models.CharField(max_length=160)),
                ("pit_manifest_id", models.CharField(db_index=True, max_length=160)),
                ("pit_manifest_hash", models.CharField(max_length=64)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField()),
                ("research_only", models.BooleanField(default=True, editable=False)),
                ("must_not_use_for_decision", models.BooleanField(default=True, editable=False)),
                ("must_not_execute", models.BooleanField(default=True, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dated_outputs",
                        to="macro_factor.macrofactorrunartifactmodel",
                    ),
                ),
            ],
            options={
                "db_table": "macro_factor_dated_output",
                "ordering": ["artifact_id", "output_role", "observation_date"],
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AddIndex(
            model_name="macrofactorrunartifactmodel",
            index=models.Index(
                fields=["target_code", "output_role", "-produced_at"], name="mf_run_target_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="macrofactorrunartifactmodel",
            index=models.Index(
                fields=["factor_version", "-produced_at"], name="mf_run_factor_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="macrofactorrunartifactmodel",
            constraint=models.UniqueConstraint(
                fields=("run_key", "run_version"), name="macro_factor_run_key_version_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="macrofactorrunartifactmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("must_not_execute", True),
                    ("must_not_use_for_decision", True),
                    ("research_only", True),
                ),
                name="macro_factor_run_research_blocked_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="macrofactorlifecycleeventmodel",
            index=models.Index(fields=["artifact", "occurred_at"], name="mf_lifecycle_time_idx"),
        ),
        migrations.AddConstraint(
            model_name="macrofactorlifecycleeventmodel",
            constraint=models.UniqueConstraint(
                fields=("artifact", "sequence"), name="macro_factor_lifecycle_sequence_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="macrofactorlifecycleeventmodel",
            constraint=models.UniqueConstraint(
                fields=("artifact", "event_type"), name="macro_factor_lifecycle_type_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="macrofactorlifecycleeventmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("event_type", "recorded"),
                        ("owner_attestation_bytes__isnull", True),
                        ("owner_attestation_content_length__isnull", True),
                        ("owner_attestation_hash__isnull", True),
                        ("owner_attestation_id__isnull", True),
                        ("owner_attestation_issued_at__isnull", True),
                        ("owner_attestation_media_type__isnull", True),
                        ("owner_attestation_owner_ref__isnull", True),
                        ("previous_event_hash__isnull", True),
                        ("sequence", 1),
                    ),
                    models.Q(
                        ("event_type", "retired"),
                        ("owner_attestation_bytes__isnull", False),
                        ("owner_attestation_content_length__isnull", False),
                        ("owner_attestation_hash__isnull", False),
                        ("owner_attestation_id__isnull", False),
                        ("owner_attestation_issued_at__isnull", False),
                        ("owner_attestation_media_type__isnull", False),
                        ("owner_attestation_owner_ref__isnull", False),
                        ("previous_event_hash__isnull", False),
                        ("sequence__gt", 1),
                    ),
                    _connector="OR",
                ),
                name="macro_factor_lifecycle_chain_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="macrofactorlifecycleeventmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("recorded_at__gte", models.F("occurred_at"))),
                name="macro_factor_lifecycle_recorded_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="macrofactorlifecycleeventmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("event_type", "recorded"),
                        ("owner_attestation_issued_at__isnull", True),
                    ),
                    models.Q(
                        ("event_type", "retired"),
                        ("owner_attestation_issued_at__gte", models.F("occurred_at")),
                        ("owner_attestation_issued_at__lte", models.F("recorded_at")),
                    ),
                    _connector="OR",
                ),
                name="macro_factor_lifecycle_attested_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="macrofactorlifecycleeventmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("must_not_execute", True),
                    ("must_not_use_for_decision", True),
                    ("research_only", True),
                ),
                name="macro_factor_lifecycle_research_blocked_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="macrofactordatedoutputmodel",
            index=models.Index(
                fields=["target_code", "output_role", "-observation_date"],
                name="macro_factor_output_target_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="macrofactordatedoutputmodel",
            index=models.Index(
                fields=["valid_until", "output_role"], name="macro_factor_output_valid_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="macrofactordatedoutputmodel",
            constraint=models.UniqueConstraint(
                fields=(
                    "artifact",
                    "output_role",
                    "observation_date",
                    "target_period_start",
                    "target_period_end",
                ),
                name="macro_factor_output_identity_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="macrofactordatedoutputmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_period_end__gte", models.F("target_period_start"))),
                name="macro_factor_output_period_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="macrofactordatedoutputmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("produced_at__gte", models.F("knowledge_as_of"))),
                name="macro_factor_output_knowledge_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="macrofactordatedoutputmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("valid_until__gt", models.F("produced_at"))),
                name="macro_factor_output_validity_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="macrofactordatedoutputmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("horizon_periods", 0), ("output_role", "current_state")),
                    models.Q(("horizon_periods__gt", 0), ("output_role", "forward_expectation")),
                    _connector="OR",
                ),
                name="macro_factor_output_horizon_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="macrofactordatedoutputmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("must_not_execute", True),
                    ("must_not_use_for_decision", True),
                    ("research_only", True),
                ),
                name="macro_factor_output_research_blocked_ck",
            ),
        ),
    ]
