# Generated by Django 5.2.12 on 2026-08-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("macro_factor", "0002_reproducible_run_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="MacroFactorLifecycleStreamCommitModel",
            fields=[
                (
                    "commit_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("artifact_hash", models.CharField(max_length=64)),
                ("event_hash", models.CharField(max_length=64)),
                ("sequence", models.PositiveIntegerField()),
                ("event_count", models.PositiveIntegerField()),
                ("head_event_hash", models.CharField(max_length=64)),
                (
                    "previous_commit_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("stream_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField()),
                ("research_only", models.BooleanField(default=True, editable=False)),
                (
                    "must_not_use_for_decision",
                    models.BooleanField(default=True, editable=False),
                ),
                ("must_not_execute", models.BooleanField(default=True, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_stream_commits",
                        to="macro_factor.macrofactorrunartifactmodel",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_stream_commit",
                        to="macro_factor.macrofactorlifecycleeventmodel",
                    ),
                ),
            ],
            options={
                "db_table": "macro_factor_lifecycle_stream_commit",
                "ordering": ["artifact_id", "sequence"],
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("artifact", "sequence"),
                        name="mf_lifecycle_commit_seq_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("event_count", models.F("sequence"))),
                        name="mf_lifecycle_commit_count_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("head_event_hash", models.F("event_hash"))),
                        name="mf_lifecycle_commit_head_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("previous_commit_hash__isnull", True), ("sequence", 1)),
                            models.Q(
                                ("previous_commit_hash__isnull", False),
                                ("sequence__gt", 1),
                            ),
                            _connector="OR",
                        ),
                        name="mf_lifecycle_commit_prev_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="mf_lifecycle_commit_blocked_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MacroFactorLifecycleStreamHeadModel",
            fields=[
                ("artifact_hash", models.CharField(max_length=64)),
                ("latest_sequence", models.PositiveIntegerField()),
                ("event_count", models.PositiveIntegerField()),
                ("latest_event_hash", models.CharField(max_length=64)),
                ("latest_commit_hash", models.CharField(max_length=64)),
                ("stream_hash", models.CharField(max_length=64)),
                ("content_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("research_only", models.BooleanField(default=True, editable=False)),
                (
                    "must_not_use_for_decision",
                    models.BooleanField(default=True, editable=False),
                ),
                ("must_not_execute", models.BooleanField(default=True, editable=False)),
                (
                    "artifact",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="lifecycle_stream_head",
                        serialize=False,
                        to="macro_factor.macrofactorrunartifactmodel",
                    ),
                ),
            ],
            options={
                "db_table": "macro_factor_lifecycle_stream_head",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("event_count", models.F("latest_sequence"))),
                        name="mf_lifecycle_head_count_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="mf_lifecycle_head_blocked_ck",
                    ),
                ],
            },
        ),
    ]
