"""Account-level auto-advisor decision sheet services."""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from datetime import datetime
from decimal import ROUND_FLOOR, Decimal, InvalidOperation
from typing import Any, Protocol

from apps.account.application.portfolio_api_services import (
    PortfolioAccessDeniedError,
    PortfolioNotFoundError,
    get_portfolio_positions_payload,
)
from apps.asset_analysis.application.asset_name_service import resolve_asset_names
from apps.simulated_trading.application.interface_services import get_account_access
from core.integration.manual_trade_sync import get_manual_trade_portfolio_id_for_account
from core.integration.simulated_positions import get_position_snapshots

from .workspace_services import list_workspace_recommendations

ACTIONABLE_SIDES = {"BUY", "ADD", "REDUCE", "EXIT"}
BUY_SIDES = {"BUY", "ADD"}
SELL_SIDES = {"SELL", "REDUCE", "EXIT"}


class AdvisorAccessError(PermissionError):
    """Raised when the current user cannot access the account-level sheet."""

    def __init__(self, message: str, status_code: int = 403) -> None:
        super().__init__(message)
        self.status_code = status_code


@dataclass(frozen=True)
class AdvisorHoldingSnapshot:
    """Unified holding snapshot used by the advisor chain."""

    asset_code: str
    asset_name: str
    asset_class: str
    quantity: Decimal
    market_value: Decimal
    current_weight: Decimal
    avg_cost: Decimal
    current_price: Decimal | None
    unrealized_pnl: Decimal
    unrealized_pnl_pct: Decimal
    data_source: str
    price_time: str

    def to_dict(self) -> dict[str, Any]:
        """Return API-safe holding payload."""

        return {
            "asset_code": self.asset_code,
            "asset_name": self.asset_name or self.asset_code,
            "asset_class": self.asset_class,
            "quantity": _decimal_to_number(self.quantity),
            "market_value": _decimal_to_number(self.market_value),
            "current_weight": _decimal_to_number(self.current_weight),
            "avg_cost": _decimal_to_number(self.avg_cost),
            "current_price": _decimal_to_number(self.current_price),
            "unrealized_pnl": _decimal_to_number(self.unrealized_pnl),
            "unrealized_pnl_pct": _decimal_to_number(self.unrealized_pnl_pct),
            "data_source": self.data_source,
            "price_time": self.price_time,
        }


@dataclass(frozen=True)
class AdvisorAccountSnapshot:
    """Account summary plus normalized holdings."""

    account_summary: dict[str, Any]
    holdings: list[AdvisorHoldingSnapshot]
    baseline: str
    warnings: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class AdvisorOrderIntent:
    """Read-only order intent generated by the auto-advisor."""

    order_intent_id: str
    account_id: str
    asset_code: str
    asset_name: str
    side: str
    current_quantity: Decimal
    target_quantity: Decimal
    delta_quantity: Decimal
    estimated_price: Decimal | None
    estimated_amount: Decimal
    current_weight: Decimal
    target_weight: Decimal
    priority: int
    price_band: dict[str, Any]
    reason: str
    risk_notes: list[str]
    invalidation_rule: str
    execution_hint: str
    source_recommendation_id: str
    blocking_status: str

    def to_dict(self) -> dict[str, Any]:
        """Return API-safe order intent payload."""

        return {
            "order_intent_id": self.order_intent_id,
            "account_id": self.account_id,
            "asset_code": self.asset_code,
            "asset_name": self.asset_name or self.asset_code,
            "side": self.side,
            "current_quantity": _decimal_to_number(self.current_quantity),
            "target_quantity": _decimal_to_number(self.target_quantity),
            "delta_quantity": _decimal_to_number(self.delta_quantity),
            "estimated_price": _decimal_to_number(self.estimated_price),
            "estimated_amount": _decimal_to_number(self.estimated_amount),
            "current_weight": _decimal_to_number(self.current_weight),
            "target_weight": _decimal_to_number(self.target_weight),
            "priority": self.priority,
            "price_band": self.price_band,
            "reason": self.reason,
            "risk_notes": self.risk_notes,
            "invalidation_rule": self.invalidation_rule,
            "execution_hint": self.execution_hint,
            "source_recommendation_id": self.source_recommendation_id,
            "blocking_status": self.blocking_status,
        }


class HoldingSnapshotProviderProtocol(Protocol):
    """Read account summary and normalized holdings."""

    def get_snapshot(self, *, account_id: str, user: Any) -> AdvisorAccountSnapshot:
        """Return the account holding snapshot for the current user."""


class RecommendationProviderProtocol(Protocol):
    """Read workspace recommendations for an account."""

    def list_recommendations(self, *, account_id: str) -> list[Any]:
        """Return candidate recommendation DTOs."""


class WorkspaceRecommendationProvider:
    """Recommendation provider backed by the Decision Workspace list service."""

    def list_recommendations(self, *, account_id: str) -> list[Any]:
        """Return up to 50 non-ignored workspace recommendations."""

        recommendations, _ = list_workspace_recommendations(
            account_id=account_id,
            status=None,
            user_action=None,
            security_code=None,
            include_ignored=False,
            recommendation_id=None,
            page=1,
            page_size=50,
        )
        return recommendations


class AccountHoldingSnapshotProvider:
    """Build a unified holding snapshot for one user-facing account id."""

    def get_snapshot(self, *, account_id: str, user: Any) -> AdvisorAccountSnapshot:
        """Validate account access and return normalized simulated/manual holdings."""

        normalized_account_id = _parse_account_id(account_id)
        access = get_account_access(user, normalized_account_id, action="查看自动投顾建议")
        if not access.allowed:
            raise AdvisorAccessError(access.error or "无权查看该账户", access.status_code or 403)

        account = access.account
        warnings: list[str] = []
        raw_holdings: list[dict[str, Any]] = []

        try:
            raw_holdings.extend(
                {
                    **item,
                    "data_source": "simulated",
                }
                for item in get_position_snapshots(account_id=normalized_account_id)
            )
        except Exception as exc:
            warnings.append(f"simulated_positions_unavailable:{exc}")

        portfolio_id = get_manual_trade_portfolio_id_for_account(normalized_account_id)
        if portfolio_id is not None:
            try:
                _, payload = get_portfolio_positions_payload(
                    user_id=int(user.id),
                    portfolio_id=portfolio_id,
                )
                raw_holdings.extend(
                    {
                        **item,
                        "data_source": "manual_portfolio",
                    }
                    for item in payload
                )
            except (PortfolioAccessDeniedError, PortfolioNotFoundError) as exc:
                warnings.append(f"manual_portfolio_unavailable:{exc}")

        cash = _to_decimal(getattr(account, "current_cash", 0))
        total_asset = _to_decimal(getattr(account, "total_value", 0))
        market_value = _to_decimal(getattr(account, "current_market_value", 0))
        if total_asset <= 0:
            total_asset = cash + market_value
        if total_asset <= 0:
            total_asset = sum(_to_decimal(item.get("market_value")) for item in raw_holdings) + cash

        holdings = _merge_holdings(raw_holdings, total_asset=total_asset)
        baseline = "empty_positions" if not holdings else "existing_positions"
        account_type = str(getattr(account, "account_type", "") or "unknown")

        return AdvisorAccountSnapshot(
            account_summary={
                "account_id": str(normalized_account_id),
                "account_name": getattr(account, "account_name", "") or f"账户 {normalized_account_id}",
                "account_type": account_type,
                "account_type_label": _account_type_label(account_type),
                "account_status": "active" if getattr(account, "is_active", False) else "inactive",
                "total_asset": _decimal_to_number(total_asset),
                "cash": _decimal_to_number(cash),
                "available_cash": _decimal_to_number(cash),
                "market_value": _decimal_to_number(market_value),
                "holding_count": len(holdings),
                "baseline": baseline,
            },
            holdings=holdings,
            baseline=baseline,
            warnings=warnings,
        )


class GenerateAdvisorDecisionSheetUseCase:
    """Generate a read-only account-level advisor decision sheet."""

    def __init__(
        self,
        *,
        holding_provider: HoldingSnapshotProviderProtocol | None = None,
        recommendation_provider: RecommendationProviderProtocol | None = None,
    ) -> None:
        self.holding_provider = holding_provider or AccountHoldingSnapshotProvider()
        self.recommendation_provider = recommendation_provider or WorkspaceRecommendationProvider()

    def execute(self, *, account_id: str, user: Any) -> dict[str, Any]:
        """Generate holdings, allocation drift, order intents, blockers, and actions."""

        snapshot = self.holding_provider.get_snapshot(account_id=account_id, user=user)
        account = snapshot.account_summary
        total_asset = _to_decimal(account.get("total_asset"))
        cash = _to_decimal(account.get("available_cash"))
        holdings = sorted(snapshot.holdings, key=lambda item: item.current_weight, reverse=True)
        holdings_by_code = {item.asset_code: item for item in holdings}

        recommendations = self.recommendation_provider.list_recommendations(
            account_id=str(account["account_id"])
        )
        security_names = _resolve_missing_names(holdings, recommendations)

        blockers: list[dict[str, Any]] = []
        warnings = list(snapshot.warnings)
        order_intents: list[AdvisorOrderIntent] = []

        for holding in holdings:
            rec = _find_recommendation_for_asset(recommendations, holding.asset_code)
            intent = self._build_existing_holding_intent(
                account_id=str(account["account_id"]),
                holding=holding,
                total_asset=total_asset,
                recommendation=rec,
            )
            if intent is not None:
                order_intents.append(intent)

        remaining_cash = cash
        for recommendation in recommendations:
            asset_code = _recommendation_asset_code(recommendation)
            if not asset_code:
                continue
            side = _normalize_recommendation_side(recommendation)
            if side not in BUY_SIDES:
                continue
            if asset_code in holdings_by_code and any(
                item.asset_code == asset_code and item.side in {"ADD", "BUY"}
                for item in order_intents
            ):
                continue
            if _to_decimal(getattr(recommendation, "suggested_quantity", 0)) == 0:
                warnings.append(f"{asset_code}:recommendation_quantity_zero_recomputed")

            current_holding = holdings_by_code.get(asset_code)
            intent = self._build_buy_intent(
                account_id=str(account["account_id"]),
                recommendation=recommendation,
                holding=current_holding,
                total_asset=total_asset,
                available_cash=remaining_cash,
                asset_name=security_names.get(asset_code, asset_code),
                baseline=snapshot.baseline,
            )
            if intent is None:
                continue
            order_intents.append(intent)
            if intent.blocking_status == "OK":
                remaining_cash -= intent.estimated_amount

        order_intents = sorted(order_intents, key=lambda item: (item.priority, item.asset_code))
        for intent in order_intents:
            if intent.blocking_status != "OK":
                blockers.append(
                    {
                        "type": intent.blocking_status,
                        "asset_code": intent.asset_code,
                        "message": "；".join(intent.risk_notes) or "订单意图存在阻断项",
                    }
                )

        allocation = _build_allocation_payload(holdings, total_asset=total_asset)
        verdict = _resolve_verdict(order_intents=order_intents, blockers=blockers, warnings=warnings)
        next_actions = _build_next_actions(verdict=verdict, has_orders=bool(order_intents))

        return {
            "account": account,
            "baseline": snapshot.baseline,
            "generated_at": _now_iso(),
            "today_conclusion": verdict,
            "risk_summary": _build_risk_summary(holdings, blockers, warnings),
            "holdings": [holding.to_dict() for holding in holdings],
            "allocation": allocation,
            "order_summary": _build_order_summary(order_intents),
            "order_intents": [intent.to_dict() for intent in order_intents],
            "blockers": blockers,
            "warnings": warnings,
            "next_actions": next_actions,
        }

    def _build_existing_holding_intent(
        self,
        *,
        account_id: str,
        holding: AdvisorHoldingSnapshot,
        total_asset: Decimal,
        recommendation: Any | None,
    ) -> AdvisorOrderIntent | None:
        rec_side = _normalize_recommendation_side(recommendation)
        reason_parts: list[str] = []
        target_weight = holding.current_weight
        side = "HOLD"
        priority = 90

        if rec_side in {"SELL", "EXIT"}:
            side = "EXIT"
            target_weight = Decimal("0")
            priority = 10
            reason_parts.append("已有退出/卖出推荐")
        elif rec_side == "REDUCE":
            side = "REDUCE"
            target_weight = min(holding.current_weight, Decimal("0.15"))
            priority = 20
            reason_parts.append("已有减仓推荐")
        elif holding.unrealized_pnl_pct <= Decimal("-10"):
            side = "EXIT"
            target_weight = Decimal("0")
            priority = 12
            reason_parts.append("浮亏超过 10%，优先退出复核")
        elif holding.current_weight > Decimal("0.25"):
            side = "REDUCE"
            target_weight = Decimal("0.20")
            priority = 25
            reason_parts.append("单一持仓权重超过 25%，先降到 20% 以内")
        elif rec_side == "BUY":
            side = "ADD"
            target_weight = max(holding.current_weight, min(holding.current_weight + Decimal("0.03"), Decimal("0.20")))
            priority = 50
            reason_parts.append("已有买入推荐，当前账户已持有，转换为加仓意图")
        else:
            reason_parts.append("当前持仓未触发调仓条件")

        if side == "HOLD":
            return self._intent_from_values(
                account_id=account_id,
                asset_code=holding.asset_code,
                asset_name=holding.asset_name,
                side="HOLD",
                current_quantity=holding.quantity,
                target_quantity=holding.quantity,
                current_weight=holding.current_weight,
                target_weight=target_weight,
                estimated_price=holding.current_price,
                priority=priority,
                reason="；".join(reason_parts),
                risk_notes=[],
                invalidation_rule=_invalidation_rule(recommendation),
                execution_hint="无需下单，继续观察持仓和失效条件。",
                source_recommendation_id=_recommendation_id(recommendation),
                blocking_status="OK",
            )

        risk_notes: list[str] = []
        blocking_status = "OK"
        if holding.current_price is None or holding.current_price <= 0:
            blocking_status = "BLOCKED_PRICE_MISSING"
            risk_notes.append("缺少有效现价，不能计算真实订单金额。")

        return self._intent_from_values(
            account_id=account_id,
            asset_code=holding.asset_code,
            asset_name=holding.asset_name,
            side=side,
            current_quantity=holding.quantity,
            target_quantity=_target_quantity(
                total_asset=total_asset,
                target_weight=target_weight,
                price=holding.current_price,
            ),
            current_weight=holding.current_weight,
            target_weight=target_weight,
            estimated_price=holding.current_price,
            priority=priority,
            reason="；".join(reason_parts),
            risk_notes=risk_notes,
            invalidation_rule=_invalidation_rule(recommendation),
            execution_hint=_execution_hint(side),
            source_recommendation_id=_recommendation_id(recommendation),
            blocking_status=blocking_status,
        )

    def _build_buy_intent(
        self,
        *,
        account_id: str,
        recommendation: Any,
        holding: AdvisorHoldingSnapshot | None,
        total_asset: Decimal,
        available_cash: Decimal,
        asset_name: str,
        baseline: str,
    ) -> AdvisorOrderIntent | None:
        asset_code = _recommendation_asset_code(recommendation)
        price = _recommendation_price(recommendation)
        risk_notes: list[str] = []
        blocking_status = "OK"
        if price is None or price <= 0:
            blocking_status = "BLOCKED_PRICE_MISSING"
            risk_notes.append("缺少有效现价，不能计算真实下单数量。")

        if available_cash <= 0:
            blocking_status = "BLOCKED_NO_CASH"
            risk_notes.append("账户可用资金不足，不能新增买入。")

        target_weight = _recommended_target_weight(recommendation, baseline=baseline)
        budget = min(available_cash, total_asset * target_weight)
        current_quantity = holding.quantity if holding else Decimal("0")
        current_weight = holding.current_weight if holding else Decimal("0")
        target_quantity = current_quantity
        if blocking_status == "OK":
            target_quantity = current_quantity + _floor_quantity(budget / price)
            if target_quantity <= current_quantity:
                blocking_status = "BLOCKED_MIN_SIZE"
                risk_notes.append("按目标权重和价格计算后不足 1 单位。")

        side = "ADD" if holding else "BUY"
        reason = _recommendation_reason(recommendation)
        if baseline == "empty_positions":
            reason = f"空仓账户建仓建议；{reason}"

        return self._intent_from_values(
            account_id=account_id,
            asset_code=asset_code,
            asset_name=asset_name,
            side=side,
            current_quantity=current_quantity,
            target_quantity=target_quantity,
            current_weight=current_weight,
            target_weight=max(current_weight, target_weight),
            estimated_price=price,
            priority=40 if holding else 60,
            reason=reason,
            risk_notes=risk_notes,
            invalidation_rule=_invalidation_rule(recommendation),
            execution_hint=_execution_hint(side),
            source_recommendation_id=_recommendation_id(recommendation),
            blocking_status=blocking_status,
        )

    def _intent_from_values(
        self,
        *,
        account_id: str,
        asset_code: str,
        asset_name: str,
        side: str,
        current_quantity: Decimal,
        target_quantity: Decimal,
        current_weight: Decimal,
        target_weight: Decimal,
        estimated_price: Decimal | None,
        priority: int,
        reason: str,
        risk_notes: list[str],
        invalidation_rule: str,
        execution_hint: str,
        source_recommendation_id: str,
        blocking_status: str,
    ) -> AdvisorOrderIntent:
        delta_quantity = target_quantity - current_quantity
        amount = abs(delta_quantity) * (estimated_price or Decimal("0"))
        return AdvisorOrderIntent(
            order_intent_id=_stable_order_intent_id(account_id, asset_code, side, source_recommendation_id),
            account_id=account_id,
            asset_code=asset_code,
            asset_name=asset_name,
            side=side,
            current_quantity=current_quantity,
            target_quantity=target_quantity,
            delta_quantity=delta_quantity,
            estimated_price=estimated_price,
            estimated_amount=amount,
            current_weight=current_weight,
            target_weight=target_weight,
            priority=priority,
            price_band=_price_band(estimated_price),
            reason=reason,
            risk_notes=risk_notes,
            invalidation_rule=invalidation_rule,
            execution_hint=execution_hint,
            source_recommendation_id=source_recommendation_id,
            blocking_status=blocking_status,
        )


def _parse_account_id(account_id: str) -> int:
    try:
        parsed = int(str(account_id).strip())
    except (TypeError, ValueError):
        raise AdvisorAccessError("account_id must be a valid account id", 400) from None
    if parsed <= 0:
        raise AdvisorAccessError("account_id must be a valid account id", 400)
    return parsed


def _merge_holdings(
    raw_holdings: list[dict[str, Any]],
    *,
    total_asset: Decimal,
) -> list[AdvisorHoldingSnapshot]:
    grouped: dict[str, dict[str, Any]] = {}
    for raw in raw_holdings:
        code = str(raw.get("asset_code") or raw.get("security_code") or "").strip().upper()
        if not code:
            continue
        quantity = _to_decimal(raw.get("quantity", raw.get("shares", 0)))
        market_value = _to_decimal(raw.get("market_value", 0))
        avg_cost = _to_decimal(raw.get("avg_cost", raw.get("cost", 0)))
        current_price = _optional_decimal(raw.get("current_price", raw.get("estimated_price")))
        pnl = _to_decimal(raw.get("unrealized_pnl", 0))
        pnl_pct = _normalize_percent(raw.get("unrealized_pnl_pct", 0))
        existing = grouped.setdefault(
            code,
            {
                "asset_code": code,
                "asset_name": raw.get("asset_name") or code,
                "asset_class": raw.get("asset_class") or raw.get("asset_type") or "equity",
                "quantity": Decimal("0"),
                "market_value": Decimal("0"),
                "cost_value": Decimal("0"),
                "current_price": current_price,
                "unrealized_pnl": Decimal("0"),
                "unrealized_pnl_pct": pnl_pct,
                "data_sources": set(),
                "price_time": raw.get("price_time") or raw.get("updated_at") or "",
            },
        )
        existing["quantity"] += quantity
        existing["market_value"] += market_value
        existing["cost_value"] += avg_cost * quantity
        existing["unrealized_pnl"] += pnl
        existing["data_sources"].add(str(raw.get("data_source") or raw.get("source") or "unknown"))
        if current_price and current_price > 0:
            existing["current_price"] = current_price
        if not existing["price_time"]:
            existing["price_time"] = raw.get("price_time") or raw.get("updated_at") or ""

    holdings: list[AdvisorHoldingSnapshot] = []
    for item in grouped.values():
        quantity = item["quantity"]
        market_value = item["market_value"]
        avg_cost = item["cost_value"] / quantity if quantity else Decimal("0")
        current_weight = market_value / total_asset if total_asset > 0 else Decimal("0")
        holdings.append(
            AdvisorHoldingSnapshot(
                asset_code=item["asset_code"],
                asset_name=str(item["asset_name"] or item["asset_code"]),
                asset_class=str(item["asset_class"] or "equity"),
                quantity=quantity,
                market_value=market_value,
                current_weight=current_weight,
                avg_cost=avg_cost,
                current_price=item["current_price"],
                unrealized_pnl=item["unrealized_pnl"],
                unrealized_pnl_pct=item["unrealized_pnl_pct"],
                data_source="unified",
                price_time=_serialize_time(item["price_time"]),
            )
        )
    return holdings


def _build_allocation_payload(
    holdings: list[AdvisorHoldingSnapshot],
    *,
    total_asset: Decimal,
) -> list[dict[str, Any]]:
    by_class: dict[str, Decimal] = {}
    for holding in holdings:
        by_class[holding.asset_class] = by_class.get(holding.asset_class, Decimal("0")) + holding.market_value
    if not by_class:
        by_class["equity"] = Decimal("0")
    payload: list[dict[str, Any]] = []
    for asset_class, current_amount in sorted(by_class.items()):
        target_weight = Decimal("0.60") if asset_class == "equity" else Decimal("0.10")
        current_weight = current_amount / total_asset if total_asset > 0 else Decimal("0")
        payload.append(
            {
                "asset_class": asset_class,
                "target_weight": _decimal_to_number(target_weight),
                "current_weight": _decimal_to_number(current_weight),
                "deviation_amount": _decimal_to_number((target_weight - current_weight) * total_asset),
            }
        )
    return payload


def _build_order_summary(order_intents: list[AdvisorOrderIntent]) -> dict[str, Any]:
    counts = dict.fromkeys(["BUY", "ADD", "REDUCE", "EXIT", "HOLD", "WATCH"], 0)
    actionable_count = 0
    blocked_count = 0
    for intent in order_intents:
        counts[intent.side] = counts.get(intent.side, 0) + 1
        if intent.side in ACTIONABLE_SIDES:
            actionable_count += 1
        if intent.blocking_status != "OK":
            blocked_count += 1
    return {
        "total": len(order_intents),
        "actionable": actionable_count,
        "blocked": blocked_count,
        "buy": counts["BUY"],
        "add": counts["ADD"],
        "reduce": counts["REDUCE"],
        "exit": counts["EXIT"],
        "hold": counts["HOLD"],
        "watch": counts["WATCH"],
    }


def _build_risk_summary(
    holdings: list[AdvisorHoldingSnapshot],
    blockers: list[dict[str, Any]],
    warnings: list[str],
) -> dict[str, Any]:
    top_weight = max((holding.current_weight for holding in holdings), default=Decimal("0"))
    over_weight = [holding.asset_code for holding in holdings if holding.current_weight > Decimal("0.25")]
    return {
        "top_position_weight": _decimal_to_number(top_weight),
        "overweight_positions": over_weight,
        "blocker_count": len(blockers),
        "warning_count": len(warnings),
    }


def _build_next_actions(*, verdict: str, has_orders: bool) -> list[dict[str, str]]:
    actions = [
        {"key": "refresh_recommendations", "label": "刷新推荐", "hint": "重新生成账户推荐输入。"},
        {"key": "view_conflicts", "label": "查看冲突/阻断", "hint": "核对 Beta Gate、冷却期、配额和价格缺失。"},
    ]
    if has_orders and verdict in {"ACT", "REVIEW"}:
        actions.extend(
            [
                {"key": "generate_plan", "label": "生成 Workspace 计划", "hint": "把已采纳建议转入计划预览。"},
                {"key": "copy_manual_list", "label": "复制手工执行清单", "hint": "用于人工下单或记录成交。"},
            ]
        )
    actions.append({"key": "record_manual_fill", "label": "手工记录成交", "hint": "执行后在账户中补录成交。"})
    return actions


def _resolve_verdict(
    *,
    order_intents: list[AdvisorOrderIntent],
    blockers: list[dict[str, Any]],
    warnings: list[str],
) -> str:
    actionable = [item for item in order_intents if item.side in ACTIONABLE_SIDES]
    executable = [item for item in actionable if item.blocking_status == "OK"]
    if actionable and not executable:
        return "BLOCKED"
    if executable:
        return "ACT"
    if blockers or warnings:
        return "REVIEW"
    return "WAIT"


def _resolve_missing_names(holdings: list[AdvisorHoldingSnapshot], recommendations: list[Any]) -> dict[str, str]:
    names = {holding.asset_code: holding.asset_name for holding in holdings if holding.asset_name}
    codes = [_recommendation_asset_code(item) for item in recommendations]
    missing = [code for code in codes if code and code not in names]
    if missing:
        names.update(resolve_asset_names(missing))
    return names


def _find_recommendation_for_asset(recommendations: list[Any], asset_code: str) -> Any | None:
    normalized = asset_code.upper()
    for side in ["EXIT", "SELL", "REDUCE", "BUY", "ADD", "HOLD"]:
        for recommendation in recommendations:
            if _recommendation_asset_code(recommendation) == normalized and _normalize_recommendation_side(recommendation) == side:
                return recommendation
    return None


def _recommendation_asset_code(recommendation: Any | None) -> str:
    if recommendation is None:
        return ""
    return str(
        getattr(recommendation, "security_code", "")
        or getattr(recommendation, "asset_code", "")
        or ""
    ).strip().upper()


def _normalize_recommendation_side(recommendation: Any | None) -> str:
    if recommendation is None:
        return ""
    side = str(getattr(recommendation, "side", "") or "").strip().upper()
    if side == "SELL":
        return "EXIT"
    return side


def _recommendation_id(recommendation: Any | None) -> str:
    if recommendation is None:
        return ""
    return str(getattr(recommendation, "recommendation_id", "") or "")


def _recommendation_reason(recommendation: Any | None) -> str:
    if recommendation is None:
        return "账户规则生成。"
    return str(
        getattr(recommendation, "human_rationale", "")
        or getattr(recommendation, "reason", "")
        or "来自工作台统一推荐。"
    )


def _invalidation_rule(recommendation: Any | None) -> str:
    if recommendation is None:
        return "若宏观环境、Beta Gate 或标的基本面发生反向变化，重新评估。"
    stop_loss = _optional_decimal(getattr(recommendation, "stop_loss_price", None))
    if stop_loss and stop_loss > 0:
        return f"跌破止损价 {stop_loss} 或推荐失效时重新评估。"
    return "若推荐信号失效、Beta Gate 不通过或价格偏离入场区间，暂停执行。"


def _recommendation_price(recommendation: Any) -> Decimal | None:
    for attr in ("current_price", "entry_price_high", "fair_value", "entry_price_low"):
        value = _optional_decimal(getattr(recommendation, attr, None))
        if value is not None and value > 0:
            return value
    return None


def _recommended_target_weight(recommendation: Any, *, baseline: str) -> Decimal:
    raw_pct = _to_decimal(getattr(recommendation, "position_pct", 0))
    if raw_pct > 1:
        raw_pct = raw_pct / Decimal("100")
    default_weight = Decimal("0.08") if baseline == "empty_positions" else Decimal("0.05")
    weight = raw_pct if raw_pct > 0 else default_weight
    return min(max(weight, Decimal("0.02")), Decimal("0.15"))


def _target_quantity(*, total_asset: Decimal, target_weight: Decimal, price: Decimal | None) -> Decimal:
    if price is None or price <= 0:
        return Decimal("0")
    return _floor_quantity((total_asset * target_weight) / price)


def _floor_quantity(value: Decimal) -> Decimal:
    if value <= 0:
        return Decimal("0")
    return value.quantize(Decimal("1"), rounding=ROUND_FLOOR)


def _price_band(price: Decimal | None) -> dict[str, Any]:
    if price is None or price <= 0:
        return {"low": None, "high": None, "label": "价格缺失"}
    low = price * Decimal("0.99")
    high = price * Decimal("1.01")
    return {
        "low": _decimal_to_number(low),
        "high": _decimal_to_number(high),
        "label": f"{low:.2f} - {high:.2f}",
    }


def _execution_hint(side: str) -> str:
    return {
        "BUY": "按价格区间分批买入，成交后手工记录到账户。",
        "ADD": "仅补足目标仓位，不追高突破价格上沿。",
        "REDUCE": "优先卖出超配部分，保留目标仓位。",
        "EXIT": "按风控优先级处理，可分批清仓并记录理由。",
        "HOLD": "无需下单，继续跟踪失效条件。",
        "WATCH": "加入观察，不形成订单。",
    }.get(side, "人工复核后处理。")


def _stable_order_intent_id(account_id: str, asset_code: str, side: str, source_id: str) -> str:
    raw = f"{account_id}|{asset_code}|{side}|{source_id}".encode()
    return f"oi_{hashlib.sha1(raw).hexdigest()[:16]}"


def _account_type_label(account_type: str) -> str:
    return {
        "real": "实盘账户",
        "simulated": "模拟盘账户",
        "paper": "模拟盘账户",
        "manual": "手工账户",
    }.get(account_type, account_type or "账户")


def _normalize_percent(value: Any) -> Decimal:
    pct = _to_decimal(value)
    if abs(pct) <= Decimal("1"):
        return pct * Decimal("100")
    return pct


def _to_decimal(value: Any) -> Decimal:
    if value in (None, ""):
        return Decimal("0")
    if isinstance(value, Decimal):
        return value
    try:
        return Decimal(str(value))
    except (InvalidOperation, ValueError, TypeError):
        return Decimal("0")


def _optional_decimal(value: Any) -> Decimal | None:
    if value in (None, ""):
        return None
    decimal_value = _to_decimal(value)
    return decimal_value


def _decimal_to_number(value: Decimal | None) -> float | None:
    if value is None:
        return None
    return float(value)


def _serialize_time(value: Any) -> str:
    if isinstance(value, datetime):
        return value.isoformat()
    return str(value or "")


def _now_iso() -> str:
    from datetime import UTC

    return datetime.now(UTC).isoformat()
