"""Auto-advisor data contracts, protocols, statuses, and shared constants."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from decimal import Decimal
from typing import Any, Protocol, cast

from apps.account.application.portfolio_api_contracts import PortfolioApiRepository
from apps.decision_rhythm.application.advisor_serialization import (
    _build_decision_card_payload,
    _decimal_to_number,
)

ACTIONABLE_SIDES = {"BUY", "ADD", "REDUCE", "EXIT"}


BUY_SIDES = {"BUY", "ADD"}


SELL_SIDES = {"SELL", "REDUCE", "EXIT"}


RISK_GATE_BLOCKING_STATUS = "BLOCKED_RISK_GATE"


RISK_POLICY_UNAVAILABLE_STATUS = "BLOCKED_RISK_POLICY_UNAVAILABLE"


EXECUTION_GUARD_BLOCKING_STATUS = "BLOCKED_EXECUTION_GUARD"


EXPOSURE_LIMIT_BLOCKING_STATUS = "BLOCKED_EXPOSURE_LIMIT"


def get_manual_trade_portfolio_id_for_account(account_id: int) -> int | None:
    """Return the legacy portfolio id used by manual trade import for one account."""

    from apps.account.application.repository_provider import get_portfolio_api_repository

    repository = cast(PortfolioApiRepository, get_portfolio_api_repository())
    portfolio = repository.get_portfolio_for_account(account_id)
    if portfolio is None:
        return None
    return int(portfolio.id)


class AdvisorAccessError(PermissionError):
    """Raised when the current user cannot access the account-level sheet."""

    def __init__(self, message: str, status_code: int = 403) -> None:
        super().__init__(message)
        self.status_code = status_code


@dataclass(frozen=True)
class AdvisorHoldingSnapshot:
    """Unified holding snapshot used by the advisor chain."""

    asset_code: str
    asset_name: str
    asset_class: str
    quantity: Decimal
    market_value: Decimal
    current_weight: Decimal
    avg_cost: Decimal
    current_price: Decimal | None
    unrealized_pnl: Decimal
    unrealized_pnl_pct: Decimal
    data_source: str
    price_time: str

    def to_dict(self) -> dict[str, Any]:
        """Return API-safe holding payload."""

        return {
            "asset_code": self.asset_code,
            "asset_name": self.asset_name or self.asset_code,
            "asset_class": self.asset_class,
            "quantity": _decimal_to_number(self.quantity),
            "market_value": _decimal_to_number(self.market_value),
            "current_weight": _decimal_to_number(self.current_weight),
            "avg_cost": _decimal_to_number(self.avg_cost),
            "current_price": _decimal_to_number(self.current_price),
            "unrealized_pnl": _decimal_to_number(self.unrealized_pnl),
            "unrealized_pnl_pct": _decimal_to_number(self.unrealized_pnl_pct),
            "data_source": self.data_source,
            "price_time": self.price_time,
        }


@dataclass(frozen=True)
class AdvisorAccountSnapshot:
    """Account summary plus normalized holdings."""

    account_summary: dict[str, Any]
    holdings: list[AdvisorHoldingSnapshot]
    baseline: str
    warnings: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class AdvisorOrderIntent:
    """Read-only order intent generated by the auto-advisor."""

    order_intent_id: str
    account_id: str
    asset_code: str
    asset_name: str
    side: str
    current_quantity: Decimal
    target_quantity: Decimal
    delta_quantity: Decimal
    estimated_price: Decimal | None
    estimated_amount: Decimal
    current_weight: Decimal
    target_weight: Decimal
    priority: int
    price_band: dict[str, Any]
    reason: str
    risk_notes: list[str]
    invalidation_rule: str
    execution_hint: str
    source_recommendation_id: str
    blocking_status: str
    source_recommendation_ids: list[str] = field(default_factory=list)
    conflict_resolution: dict[str, Any] = field(default_factory=dict)
    risk_gate_status: str = "NOT_CHECKED"
    risk_gate: dict[str, Any] = field(default_factory=dict)
    data_asof: dict[str, Any] = field(default_factory=dict)
    decision_card: dict[str, Any] = field(default_factory=dict)
    tracking: dict[str, Any] = field(default_factory=dict)
    confirmation: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Return API-safe order intent payload."""

        payload = {
            "order_intent_id": self.order_intent_id,
            "account_id": self.account_id,
            "asset_code": self.asset_code,
            "asset_name": self.asset_name or self.asset_code,
            "side": self.side,
            "current_quantity": _decimal_to_number(self.current_quantity),
            "target_quantity": _decimal_to_number(self.target_quantity),
            "delta_quantity": _decimal_to_number(self.delta_quantity),
            "estimated_price": _decimal_to_number(self.estimated_price),
            "estimated_amount": _decimal_to_number(self.estimated_amount),
            "current_weight": _decimal_to_number(self.current_weight),
            "target_weight": _decimal_to_number(self.target_weight),
            "priority": self.priority,
            "price_band": self.price_band,
            "reason": self.reason,
            "risk_notes": self.risk_notes,
            "invalidation_rule": self.invalidation_rule,
            "execution_hint": self.execution_hint,
            "source_recommendation_id": self.source_recommendation_id,
            "blocking_status": self.blocking_status,
            "source_recommendation_ids": self.source_recommendation_ids
            or ([self.source_recommendation_id] if self.source_recommendation_id else []),
            "conflict_resolution": self.conflict_resolution,
            "risk_gate_status": self.risk_gate_status,
            "risk_gate": self.risk_gate,
            "data_asof": self.data_asof,
            "tracking": self.tracking,
            "confirmation": self.confirmation,
        }
        payload["decision_card"] = self.decision_card or _build_decision_card_payload(payload)
        return payload


class HoldingSnapshotProviderProtocol(Protocol):
    """Read account summary and normalized holdings."""

    def get_snapshot(self, *, account_id: str, user: Any) -> AdvisorAccountSnapshot:
        """Return the account holding snapshot for the current user."""


class RecommendationProviderProtocol(Protocol):
    """Read workspace recommendations for an account."""

    def list_recommendations(self, *, account_id: str) -> list[Any]:
        """Return candidate recommendation DTOs."""


class RiskGateProviderProtocol(Protocol):
    """Read risk policy context and evaluate proposed advisor orders."""

    def get_policy_context(self, *, account_id: str) -> dict[str, Any]:
        """Return the effective personal risk policy for the account."""

    def evaluate_order(
        self,
        *,
        account: dict[str, Any],
        intent: AdvisorOrderIntent,
        holdings: list[AdvisorHoldingSnapshot],
        policy_context: dict[str, Any],
    ) -> dict[str, Any]:
        """Return risk gate status for one order intent."""


class DataHealthProviderProtocol(Protocol):
    """Read decision data health for the advisor sheet."""

    def get_health(self, *, asset_codes: list[str]) -> dict[str, Any]:
        """Return a unified decision data health payload."""


class ExecutionGuardProviderProtocol(Protocol):
    """Evaluate decision-rhythm execution checks before an advisor order is shown."""

    def evaluate(
        self,
        *,
        recommendation: Any | None,
        intent: AdvisorOrderIntent,
        resolution: dict[str, Any] | None,
    ) -> dict[str, Any]:
        """Return Beta Gate, quota, cooldown, and invalidation checks for one intent."""


class ExposureProviderProtocol(Protocol):
    """Resolve asset sector, industry, and strategy exposure metadata."""

    def get_asset_exposures(self, *, asset_codes: list[str]) -> dict[str, dict[str, Any]]:
        """Return exposure metadata keyed by normalized asset code."""


class RecommendationTrackingProviderProtocol(Protocol):
    """Read execution links and review evidence for advisor recommendations."""

    def get_execution_links(
        self,
        *,
        account_id: str,
        recommendation_ids: list[str],
        user: Any,
    ) -> dict[str, list[dict[str, Any]]]:
        """Return execution links keyed by recommendation id."""


class RecommendationPerformanceProviderProtocol(Protocol):
    """Read historical prices used for recommendation performance windows."""

    def get_close_price_series(
        self,
        *,
        asset_code: str,
        start_date: date,
        end_date: date,
    ) -> list[tuple[date, float]]:
        """Return close prices oldest to newest."""


class AttributionContextProviderProtocol(Protocol):
    """Read Regime and Policy context for post-recommendation attribution."""

    def get_context(
        self,
        *,
        recommendation_date: date | None,
        outcome_date: date | None,
    ) -> dict[str, Any]:
        """Return recommendation-time and outcome-time Regime/Policy context."""


__all__ = [
    "ACTIONABLE_SIDES",
    "BUY_SIDES",
    "SELL_SIDES",
    "RISK_GATE_BLOCKING_STATUS",
    "RISK_POLICY_UNAVAILABLE_STATUS",
    "EXECUTION_GUARD_BLOCKING_STATUS",
    "EXPOSURE_LIMIT_BLOCKING_STATUS",
    "get_manual_trade_portfolio_id_for_account",
    "AdvisorAccessError",
    "AdvisorHoldingSnapshot",
    "AdvisorAccountSnapshot",
    "AdvisorOrderIntent",
    "HoldingSnapshotProviderProtocol",
    "RecommendationProviderProtocol",
    "RiskGateProviderProtocol",
    "DataHealthProviderProtocol",
    "ExecutionGuardProviderProtocol",
    "ExposureProviderProtocol",
    "RecommendationTrackingProviderProtocol",
    "RecommendationPerformanceProviderProtocol",
    "AttributionContextProviderProtocol",
]
