# Generated by Django 5.2.9 on 2026-01-04 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sentiment", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SentimentAnalysisLog",
        ),
        migrations.DeleteModel(
            name="SentimentCache",
        ),
        migrations.DeleteModel(
            name="SentimentIndexModel",
        ),
    ]
