# Generated by Django 5.2.10 on 2026-03-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_capability", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="capabilitycatalogmodel",
            new_name="ai_capabili_source__f3ec7e_idx",
            old_name="ai_cap_src_en_idx",
        ),
        migrations.RenameIndex(
            model_name="capabilitycatalogmodel",
            new_name="ai_capabili_route_g_81ac73_idx",
            old_name="ai_cap_grp_en_idx",
        ),
        migrations.RenameIndex(
            model_name="capabilitycatalogmodel",
            new_name="ai_capabili_categor_9b2109_idx",
            old_name="ai_cap_cat_en_idx",
        ),
        migrations.RenameIndex(
            model_name="capabilitycatalogmodel",
            new_name="ai_capabili_risk_le_a1aff8_idx",
            old_name="ai_cap_risk_en_idx",
        ),
        migrations.RenameIndex(
            model_name="capabilitycatalogmodel",
            new_name="ai_capabili_review__6f6476_idx",
            old_name="ai_cap_review_idx",
        ),
    ]
