# Generated by Django 5.2.9 on 2026-01-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulated_trading", "0005_add_position_invalidation_tracking"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="positionmodel",
            new_name="simulated_p_account_db88fb_idx",
            old_name="simulated_posi_account_id_idx",
        ),
        migrations.RenameIndex(
            model_name="positionmodel",
            new_name="simulated_p_is_inva_6793c1_idx",
            old_name="simulated_posi_is_invalid_idx",
        ),
    ]
