# Generated by Django 5.2.9 on 2026-02-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulated_trading", "0008_dailyinspectionnotificationconfigmodel"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dailyinspectionreportmodel",
            new_name="simulated_d_account_15d21a_idx",
            old_name="simulated_d_account_a973a7_idx",
        ),
        migrations.RenameIndex(
            model_name="dailyinspectionreportmodel",
            new_name="simulated_d_inspect_d1929f_idx",
            old_name="simulated_d_inspect_3ad5f2_idx",
        ),
    ]
