# Generated by Django 5.2.10 on 2026-03-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulated_trading", "0010_rebalanceproposalmodel_notificationhistorymodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positionmodel",
            name="unrealized_pnl",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="浮动盈亏(元)"
            ),
        ),
        migrations.AlterField(
            model_name="positionmodel",
            name="unrealized_pnl_pct",
            field=models.FloatField(default=0.0, verbose_name="浮动盈亏率(%)"),
        ),
    ]
