# Generated by Django 5.2.10 on 2026-03-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulated_trading", "0015_add_ledger_migration_map"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positionmodel",
            name="available_quantity",
            field=models.DecimalField(decimal_places=6, max_digits=20, verbose_name="可卖数量"),
        ),
        migrations.AlterField(
            model_name="positionmodel",
            name="quantity",
            field=models.DecimalField(decimal_places=6, max_digits=20, verbose_name="持仓数量"),
        ),
        migrations.AlterField(
            model_name="simulatedtrademodel",
            name="quantity",
            field=models.DecimalField(decimal_places=6, max_digits=20, verbose_name="交易数量"),
        ),
    ]
