# Generated by Django 5.2.12 on 2026-04-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulated_trading", "0017_add_performance_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="accountbenchmarkcomponentmodel",
            new_name="account_ben_account_855253_idx",
            old_name="acct_bm_account_active_idx",
        ),
        migrations.RenameIndex(
            model_name="accountbenchmarkcomponentmodel",
            new_name="account_ben_account_23da74_idx",
            old_name="acct_bm_account_sort_idx",
        ),
        migrations.RenameIndex(
            model_name="accountpositionvaluationsnapshotmodel",
            new_name="account_pos_account_9c2a2c_idx",
            old_name="apvs_account_date_idx",
        ),
        migrations.RenameIndex(
            model_name="accountpositionvaluationsnapshotmodel",
            new_name="account_pos_account_f11ca8_idx",
            old_name="apvs_account_date_code_idx",
        ),
        migrations.RenameIndex(
            model_name="accountpositionvaluationsnapshotmodel",
            new_name="account_pos_asset_c_abd568_idx",
            old_name="apvs_code_date_idx",
        ),
        migrations.RenameIndex(
            model_name="unifiedaccountcashflowmodel",
            new_name="unified_acc_account_65c519_idx",
            old_name="ucf_account_date_idx",
        ),
        migrations.RenameIndex(
            model_name="unifiedaccountcashflowmodel",
            new_name="unified_acc_account_208b6a_idx",
            old_name="ucf_account_type_idx",
        ),
        migrations.RenameIndex(
            model_name="unifiedaccountcashflowmodel",
            new_name="unified_acc_source__ae0486_idx",
            old_name="ucf_source_idx",
        ),
        migrations.AlterField(
            model_name="accountbenchmarkcomponentmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="accountpositionvaluationsnapshotmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="unifiedaccountcashflowmodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
