# Generated by Django 5.2.12 on 2026-07-24 19:19

from django.db import migrations, models


def collapse_duplicate_default_fee_configs(apps, schema_editor):
    """Keep one deterministic default per asset type before adding the constraint."""

    fee_config_model = apps.get_model("simulated_trading", "FeeConfigModel")
    asset_types = (
        fee_config_model._default_manager.filter(is_default=True)
        .values_list("asset_type", flat=True)
        .distinct()
    )
    for asset_type in asset_types:
        defaults = fee_config_model._default_manager.filter(
            asset_type=asset_type,
            is_default=True,
        ).order_by("-is_active", "-updated_at", "-pk")
        keep = defaults.first()
        if keep is not None:
            defaults.exclude(pk=keep.pk).update(is_default=False)


class Migration(migrations.Migration):

    dependencies = [
        ("simulated_trading", "0019_require_explicit_min_commission"),
    ]

    operations = [
        migrations.RunPython(
            collapse_duplicate_default_fee_configs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="feeconfigmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("asset_type",),
                name="uniq_default_fee_config_per_asset_type",
            ),
        ),
    ]
