# Generated by Django 5.2 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("simulated_trading", "0020_enforce_fee_config_invariants")]

    operations = [
        migrations.CreateModel(
            name="SimulatedAccountRowSourceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("source_id", models.CharField(max_length=192)),
                ("source_version", models.CharField(max_length=192)),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                ("underlying_unified_account_namespace", models.CharField(max_length=192)),
                ("underlying_unified_account_id", models.PositiveBigIntegerField()),
                ("row_user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("raw_account_type", models.CharField(max_length=192)),
                ("is_active", models.BooleanField()),
                ("row_created_at", models.DateTimeField()),
                ("row_updated_at", models.DateTimeField()),
                ("is_present", models.BooleanField()),
                ("is_tombstone", models.BooleanField()),
                ("observed_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("source_valid_until", models.DateTimeField()),
                ("ttl_valid_until", models.DateTimeField()),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("owner_assignment_state", models.CharField(max_length=32)),
                ("supersedes_content_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("root_claim_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("captured_actor_id", models.CharField(max_length=192)),
                ("captured_actor_user_id", models.PositiveBigIntegerField()),
                ("captured_actor_role", models.CharField(max_length=192)),
                ("captured_actor_kind", models.CharField(max_length=16)),
                ("captured_actor_is_staff", models.BooleanField()),
                ("canonical_payload", models.JSONField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("row_fact_hash", models.CharField(max_length=64)),
                ("logical_binding_hash", models.CharField(max_length=64)),
                ("actor_binding_hash", models.CharField(max_length=64, unique=True)),
                ("record_header_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "simulated_account_row_source_ledger",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["source_id", "account_namespace", "account_id", "recorded_at"],
                        name="sim_row_src_chain_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_id", "source_version"), name="sim_row_src_identity_uq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("root_claim_hash__isnull", False)),
                        fields=("root_claim_hash",),
                        name="sim_row_src_root_uq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("supersedes_content_hash__isnull", False)),
                        fields=("supersedes_content_hash",),
                        name="sim_row_src_next_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("artifact_type", "simulated_account_row"),
                            ("captured_actor_is_staff", True),
                            ("captured_actor_kind", "human"),
                            ("owner", "simulated_trading"),
                            ("owner_assignment_state", "unknown"),
                            ("permission", "evidence_only"),
                            ("schema", "simulated-account-row.v1"),
                            ("status", "inactive"),
                        ),
                        name="sim_row_src_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("observed_at__lte", models.F("recorded_at")),
                            ("persisted_at", models.F("recorded_at")),
                            ("recorded_at__lt", models.F("valid_until")),
                            ("row_created_at__lte", models.F("row_updated_at")),
                            ("row_updated_at__lte", models.F("observed_at")),
                            ("valid_until__lte", models.F("source_valid_until")),
                            ("valid_until__lte", models.F("ttl_valid_until")),
                        ),
                        name="sim_row_src_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("is_present", True), ("is_tombstone", False)),
                            models.Q(("is_present", False), ("is_tombstone", True)),
                            _connector="OR",
                        ),
                        name="sim_row_src_presence_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("root_claim_hash__isnull", False),
                                ("supersedes_content_hash__isnull", True),
                            ),
                            models.Q(
                                ("root_claim_hash__isnull", True),
                                ("supersedes_content_hash__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="sim_row_src_link_ck",
                    ),
                ],
            },
        )
    ]
