# Generated by Django 5.2 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulated_trading", "0021_simulated_account_row_source_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulatedAccountRawObservationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("observation_id", models.CharField(max_length=192)),
                ("observation_version", models.CharField(max_length=192)),
                ("row_pk", models.PositiveBigIntegerField()),
                ("row_user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("raw_account_type", models.CharField(max_length=192)),
                ("is_active", models.BooleanField()),
                ("row_created_at", models.DateTimeField()),
                ("row_updated_at", models.DateTimeField()),
                ("is_present", models.BooleanField()),
                ("is_tombstone", models.BooleanField()),
                ("observed_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField(db_index=True)),
                (
                    "supersedes_content_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "root_claim_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("canonical_payload", models.JSONField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("authority_seal", models.CharField(max_length=64)),
                ("row_seal", models.CharField(max_length=64)),
                ("clock_seal", models.CharField(max_length=64)),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("persisted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "simulated_account_raw_observation_ledger",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["observation_id", "row_pk", "recorded_at"],
                        name="sim_raw_obs_chain_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("observation_id", "observation_version"),
                        name="sim_raw_obs_identity_uq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(root_claim_hash__isnull=False),
                        fields=("root_claim_hash",),
                        name="sim_raw_obs_root_uq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(supersedes_content_hash__isnull=False),
                        fields=("supersedes_content_hash",),
                        name="sim_raw_obs_next_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            owner="simulated_trading",
                            artifact_type="simulated_account_raw_observation",
                            schema="simulated-account-raw-observation.v1",
                            permission="evidence_only",
                            status="inactive",
                        ),
                        name="sim_raw_obs_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            row_created_at__lte=models.F("row_updated_at"),
                            row_updated_at__lte=models.F("observed_at"),
                            observed_at__lte=models.F("recorded_at"),
                            recorded_at__lt=models.F("valid_until"),
                            persisted_at=models.F("recorded_at"),
                        ),
                        name="sim_raw_obs_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(is_present=True, is_tombstone=False)
                            | models.Q(is_present=False, is_tombstone=True)
                        ),
                        name="sim_raw_obs_presence_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                supersedes_content_hash__isnull=True,
                                root_claim_hash__isnull=False,
                            )
                            | models.Q(
                                supersedes_content_hash__isnull=False,
                                root_claim_hash__isnull=True,
                            )
                        ),
                        name="sim_raw_obs_link_ck",
                    ),
                ],
            },
        )
    ]
