# Generated by Django 5.2 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("simulated_trading", "0022_simulated_account_raw_observation_ledger")]

    operations = [
        migrations.CreateModel(
            name="SimulatedAccountRowSourceV2Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("source_id", models.CharField(max_length=192)),
                ("source_version", models.CharField(max_length=192)),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                ("underlying_unified_account_namespace", models.CharField(max_length=192)),
                ("underlying_unified_account_id", models.PositiveBigIntegerField()),
                ("row_user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("raw_account_type", models.CharField(max_length=192)),
                ("is_active", models.BooleanField()),
                ("row_created_at", models.DateTimeField()),
                ("row_updated_at", models.DateTimeField()),
                ("is_present", models.BooleanField()),
                ("is_tombstone", models.BooleanField()),
                ("observed_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("source_valid_until", models.DateTimeField()),
                ("ttl_valid_until", models.DateTimeField()),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("raw_observation_id", models.CharField(max_length=192)),
                ("raw_observation_version", models.CharField(max_length=192)),
                ("raw_observation_identity_hash", models.CharField(max_length=64)),
                ("raw_observation_content_hash", models.CharField(max_length=64)),
                ("raw_observation_observed_at", models.DateTimeField()),
                ("raw_observation_valid_until", models.DateTimeField()),
                (
                    "raw_observation_supersedes_content_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("owner_assignment_state", models.CharField(max_length=32)),
                ("raw_observation_owner", models.CharField(max_length=32)),
                ("raw_observation_artifact_type", models.CharField(max_length=64)),
                ("raw_observation_schema", models.CharField(max_length=64)),
                ("supersedes_content_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("root_claim_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("canonical_payload", models.JSONField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("raw_binding_seal", models.CharField(max_length=64, unique=True)),
                ("row_seal", models.CharField(max_length=64)),
                ("logical_seal", models.CharField(max_length=64)),
                ("clock_seal", models.CharField(max_length=64)),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "simulated_account_row_source_v2_ledger",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["source_id", "account_namespace", "account_id", "recorded_at"],
                        name="sim_row_v2_chain_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_id", "source_version"), name="sim_row_v2_identity_uq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(root_claim_hash__isnull=False),
                        fields=("root_claim_hash",),
                        name="sim_row_v2_root_uq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(supersedes_content_hash__isnull=False),
                        fields=("supersedes_content_hash",),
                        name="sim_row_v2_next_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            owner="simulated_trading",
                            artifact_type="simulated_account_row_v2",
                            schema="simulated-account-row.v2",
                            owner_assignment_state="unknown",
                            raw_observation_owner="simulated_trading",
                            raw_observation_artifact_type="simulated_account_raw_observation",
                            raw_observation_schema="simulated-account-raw-observation.v1",
                            permission="evidence_only",
                            status="inactive",
                        ),
                        name="sim_row_v2_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            row_created_at__lte=models.F("row_updated_at"),
                            row_updated_at__lte=models.F("observed_at"),
                            observed_at__lte=models.F("recorded_at"),
                            recorded_at__lt=models.F("valid_until"),
                            observed_at=models.F("raw_observation_observed_at"),
                            source_valid_until=models.F("raw_observation_valid_until"),
                            valid_until__lte=models.F("source_valid_until"),
                            persisted_at=models.F("recorded_at"),
                        )
                        & models.Q(valid_until__lte=models.F("ttl_valid_until")),
                        name="sim_row_v2_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            source_id=models.F("raw_observation_id"),
                            source_version=models.F("raw_observation_version"),
                        ),
                        name="sim_row_v2_raw_id_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(is_present=True, is_tombstone=False)
                        | models.Q(is_present=False, is_tombstone=True),
                        name="sim_row_v2_presence_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            supersedes_content_hash__isnull=True,
                            root_claim_hash__isnull=False,
                            raw_observation_supersedes_content_hash__isnull=True,
                        )
                        | models.Q(
                            supersedes_content_hash__isnull=False,
                            root_claim_hash__isnull=True,
                            raw_observation_supersedes_content_hash__isnull=False,
                        ),
                        name="sim_row_v2_link_ck",
                    ),
                ],
            },
        )
    ]
