# Generated by Django 5.2.10 on 2026-02-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_monitor", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="taskalertmodel",
            new_name="task_monito_level_af3646_idx",
            old_name="task_monit_level__trig_idx",
        ),
        migrations.RenameIndex(
            model_name="taskalertmodel",
            new_name="task_monito_task_na_a1688a_idx",
            old_name="task_monit_tname__trig_idx",
        ),
        migrations.RenameIndex(
            model_name="taskexecutionmodel",
            new_name="task_monito_task_na_98a9f9_idx",
            old_name="task_monit_task_name__id_idx",
        ),
        migrations.RenameIndex(
            model_name="taskexecutionmodel",
            new_name="task_monito_status_3521ef_idx",
            old_name="task_monit_status__id_idx",
        ),
        migrations.AlterField(
            model_name="taskalertmodel",
            name="exception",
            field=models.TextField(blank=True, null=True, verbose_name="异常信息"),
        ),
        migrations.AlterField(
            model_name="taskalertmodel",
            name="send_error",
            field=models.TextField(blank=True, null=True, verbose_name="发送错误"),
        ),
        migrations.AlterField(
            model_name="taskalertmodel",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="发送时间"),
        ),
        migrations.AlterField(
            model_name="taskalertmodel",
            name="traceback",
            field=models.TextField(blank=True, null=True, verbose_name="堆栈跟踪"),
        ),
        migrations.AlterField(
            model_name="taskexecutionmodel",
            name="exception",
            field=models.TextField(blank=True, null=True, verbose_name="异常信息"),
        ),
        migrations.AlterField(
            model_name="taskexecutionmodel",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
        ),
        migrations.AlterField(
            model_name="taskexecutionmodel",
            name="queue",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="队列名称"),
        ),
        migrations.AlterField(
            model_name="taskexecutionmodel",
            name="result",
            field=models.TextField(blank=True, null=True, verbose_name="执行结果"),
        ),
        migrations.AlterField(
            model_name="taskexecutionmodel",
            name="runtime_seconds",
            field=models.FloatField(blank=True, null=True, verbose_name="运行时长(秒)"),
        ),
        migrations.AlterField(
            model_name="taskexecutionmodel",
            name="started_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="开始时间"
            ),
        ),
        migrations.AlterField(
            model_name="taskexecutionmodel",
            name="traceback",
            field=models.TextField(blank=True, null=True, verbose_name="堆栈跟踪"),
        ),
        migrations.AlterField(
            model_name="taskexecutionmodel",
            name="worker",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Worker 名称"
            ),
        ),
    ]
