# Generated by Django 5.2.10 on 2026-03-18 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hedge", "0002_rename_holding_to_snapshot"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="hedgeportfoliosnapshotmodel",
            new_name="hedge_portf_pair_id_6d9fd6_idx",
            old_name="hedge_portf_pair_id_e7f44b_idx",
        ),
        migrations.RenameIndex(
            model_name="hedgeportfoliosnapshotmodel",
            new_name="hedge_portf_trade_d_2fce66_idx",
            old_name="hedge_portf_trade_d_d448c9_idx",
        ),
        migrations.AlterField(
            model_name="hedgeportfoliosnapshotmodel",
            name="pair",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="hedge.hedgepairmodel",
                verbose_name="对冲对",
            ),
        ),
    ]
