# Generated by Django 5.2.9 on 2025-12-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InvestmentSignalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("asset_code", models.CharField(db_index=True, max_length=20)),
                ("asset_class", models.CharField(max_length=50)),
                (
                    "direction",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short"), ("NEUTRAL", "Neutral")],
                        max_length=10,
                    ),
                ),
                ("logic_desc", models.TextField()),
                ("invalidation_logic", models.TextField()),
                ("invalidation_threshold", models.FloatField(blank=True, null=True)),
                ("target_regime", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("invalidated", "Invalidated"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "investment_signal",
                "ordering": ["-created_at"],
            },
        ),
    ]
