# Generated by Django 5.2.9 on 2025-12-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentsignalmodel",
            name="invalidated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="investmentsignalmodel",
            name="invalidation_details",
            field=models.JSONField(blank=True, help_text="证伪时的详细数据", null=True),
        ),
        migrations.AddField(
            model_name="investmentsignalmodel",
            name="invalidation_rules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="结构化证伪规则，格式: {conditions: [...], logic: 'AND/OR'}",
                null=True,
            ),
        ),
    ]
