# Generated by Django 5.2.9 on 2026-01-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signal", "0003_investmentsignalmodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentsignalmodel",
            name="avg_backtest_return",
            field=models.FloatField(
                blank=True,
                help_text="该信号在所有回测中的平均收益率",
                null=True,
                verbose_name="平均回测收益率",
            ),
        ),
        migrations.AddField(
            model_name="investmentsignalmodel",
            name="backtest_count",
            field=models.IntegerField(
                default=0, help_text="该信号参与回测的次数", verbose_name="回测次数"
            ),
        ),
        migrations.AddField(
            model_name="investmentsignalmodel",
            name="backtest_performance_score",
            field=models.FloatField(
                blank=True,
                help_text="基于历史回测的信号表现评分 (0-100)",
                null=True,
                verbose_name="回测表现评分",
            ),
        ),
    ]
