# Generated by Django 5.2.9 on 2026-01-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signal", "0005_refactor_invalidation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentsignalmodel",
            name="invalidation_logic",
            field=models.TextField(
                blank=True, help_text="[DEPRECATED] 请使用 invalidation_description"
            ),
        ),
        migrations.AlterField(
            model_name="investmentsignalmodel",
            name="invalidation_rules",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="[DEPRECATED] 请使用 invalidation_rule_json",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="investmentsignalmodel",
            name="invalidation_threshold",
            field=models.FloatField(
                blank=True, help_text="[DEPRECATED] 请使用 invalidation_rule_json", null=True
            ),
        ),
    ]
