# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signal', '0007_add_unified_signal_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiedsignalmodel',
            name='signal_source',
            field=models.CharField(
                choices=[
                    ('regime', '宏观象限'),
                    ('factor', '因子选股'),
                    ('rotation', '资产轮动'),
                    ('hedge', '对冲组合'),
                    ('alpha', 'AI选股'),
                    ('manual', '手动'),
                ],
                db_index=True,
                max_length=20,
                verbose_name='信号来源'
            ),
        ),
    ]
