# Generated by Django 5.2.12 on 2026-08-05 02:09

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signal", "0009_forecast_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastledgerentry",
            name="model_probability",
            field=models.DecimalField(
                blank=True,
                decimal_places=12,
                max_digits=18,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="forecastledgerentry",
            name="model_probability_source_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="forecastledgerentry",
            name="model_promotion_decision_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="forecastledgerentry",
            name="scenario_revision_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forecastledgerentry",
            name="scenario_set_revision_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forecastledgerentry",
            name="subjective_probability",
            field=models.DecimalField(
                blank=True,
                decimal_places=12,
                max_digits=18,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="forecastledgerentry",
            name="subjective_probability_source_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="forecastoutcome",
            name="model_brier_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forecastoutcome",
            name="scenario_realized",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forecastoutcome",
            name="subjective_brier_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="forecastledgerentry",
            index=models.Index(
                fields=["scenario_revision_id", "published_at"], name="signal_scn_rev_pub_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forecastledgerentry",
            index=models.Index(
                fields=["scenario_set_revision_id", "published_at"], name="signal_scn_set_pub_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("model_probability__isnull", True),
                        ("model_probability_source_version", ""),
                        ("model_promotion_decision_id", ""),
                        ("scenario_revision_id__isnull", True),
                        ("scenario_set_revision_id__isnull", True),
                        ("subjective_probability__isnull", True),
                        ("subjective_probability_source_version", ""),
                    ),
                    models.Q(
                        ("scenario_revision_id__isnull", False),
                        ("subjective_probability__isnull", False),
                        models.Q(("subjective_probability_source_version", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="signal_scn_binding_complete_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("model_probability__isnull", True),
                        ("model_probability_source_version", ""),
                        ("model_promotion_decision_id", ""),
                    ),
                    models.Q(
                        ("model_probability__isnull", False),
                        models.Q(("model_probability_source_version", ""), _negated=True),
                        models.Q(("model_promotion_decision_id", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="signal_scn_model_complete_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subjective_probability__isnull", True),
                    models.Q(
                        ("subjective_probability__gte", 0), ("subjective_probability__lte", 1)
                    ),
                    _connector="OR",
                ),
                name="signal_scn_subjective_range_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("model_probability__isnull", True),
                    models.Q(("model_probability__gte", 0), ("model_probability__lte", 1)),
                    _connector="OR",
                ),
                name="signal_scn_model_range_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastoutcome",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subjective_brier_score__isnull", True),
                    models.Q(
                        ("subjective_brier_score__gte", 0), ("subjective_brier_score__lte", 1)
                    ),
                    _connector="OR",
                ),
                name="signal_scn_subjective_brier_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastoutcome",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("model_brier_score__isnull", True),
                    models.Q(("model_brier_score__gte", 0), ("model_brier_score__lte", 1)),
                    _connector="OR",
                ),
                name="signal_scn_model_brier_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastoutcome",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("model_brier_score__isnull", True),
                        ("scenario_realized__isnull", True),
                        ("subjective_brier_score__isnull", True),
                    ),
                    models.Q(
                        ("scenario_realized__isnull", False),
                        ("subjective_brier_score__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="signal_scn_outcome_score_ck",
            ),
        ),
    ]
