"""Runtime TUI metadata for the daily decision workspace."""

from __future__ import annotations

from typing import Any

_SCREEN = "command-center.decision-flow"
_MODULE = "daily-decisions"
_SOURCE = "approved:runtime-decision-workspace"

_DECISION_SIDE_FIELD: dict[str, Any] = {
    "key": "side",
    "label": "交易方向",
    "binding": "body",
    "input_type": "select",
    "value_type": "string",
    "required": True,
    "default": "BUY",
    "options": ["BUY", "SELL"],
}

RUNTIME_DECISION_WORKSPACE_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "decision.workspace.recommendations_refresh",
        "label": "刷新账户推荐",
        "endpoint": "/api/decision/workspace/recommendations/refresh/",
        "method": "POST",
        "intent": "refresh_workspace_recommendations",
        "risk": "write",
        "audience": "authenticated",
        "effect": "execute",
        "confirmation_required": True,
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "按账户重新计算推荐；可选择强制绕过缓存并同步等待结果。",
        "source": _SOURCE,
        "task_group": "02 决策工作台",
        "sequence": 245,
        "task_tier": "operation",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "binding": "body",
                "input_type": "text",
                "value_type": "string",
                "required": False,
                "default": "default",
            },
            {
                "key": "force",
                "label": "强制刷新",
                "binding": "body",
                "input_type": "checkbox",
                "value_type": "boolean",
                "required": False,
                "default": True,
            },
            {
                "key": "async_mode",
                "label": "后台执行",
                "binding": "body",
                "input_type": "checkbox",
                "value_type": "boolean",
                "required": False,
                "default": True,
            },
        ],
        "view_model": {
            "kind": "detail",
            "title_path": "data.status",
            "status_path": "success",
        },
    },
    {
        "key": "decision.workspace.invalidation_template",
        "label": "生成证伪模板",
        "endpoint": "/api/decision/workspace/invalidation/template/",
        "method": "POST",
        "intent": "generate_invalidation_template",
        "risk": "write",
        "audience": "authenticated",
        "effect": "execute",
        "confirmation_required": True,
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "结合当前脉搏与宏观象限上下文生成系统证伪模板。",
        "source": _SOURCE,
        "task_group": "02 决策工作台",
        "sequence": 246,
        "task_tier": "operation",
        "fields": [
            {
                "key": "security_code",
                "label": "证券代码",
                "binding": "body",
                "input_type": "text",
                "value_type": "string",
                "required": True,
            },
            _DECISION_SIDE_FIELD,
            {
                "key": "rationale",
                "label": "推荐理由",
                "binding": "body",
                "input_type": "textarea",
                "value_type": "string",
                "required": False,
                "max": 2000,
            },
        ],
        "view_model": {
            "kind": "detail",
            "title_path": "data.template.description",
            "status_path": "success",
        },
    },
    {
        "key": "decision.workspace.invalidation_ai_draft",
        "label": "生成 AI 证伪草稿",
        "endpoint": "/api/decision/workspace/invalidation/ai-draft/",
        "method": "POST",
        "intent": "generate_ai_invalidation_draft",
        "risk": "write",
        "audience": "authenticated",
        "effect": "execute",
        "confirmation_required": True,
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "基于证券、方向、推荐理由和用户补充要求生成可复核的证伪草稿。",
        "source": _SOURCE,
        "task_group": "02 决策工作台",
        "sequence": 247,
        "task_tier": "operation",
        "fields": [
            {
                "key": "security_code",
                "label": "证券代码",
                "binding": "body",
                "input_type": "text",
                "value_type": "string",
                "required": True,
            },
            _DECISION_SIDE_FIELD,
            {
                "key": "rationale",
                "label": "推荐理由",
                "binding": "body",
                "input_type": "textarea",
                "value_type": "string",
                "required": False,
                "max": 2000,
            },
            {
                "key": "user_prompt",
                "label": "补充要求",
                "binding": "body",
                "input_type": "textarea",
                "value_type": "string",
                "required": False,
                "max": 2000,
            },
        ],
        "view_model": {
            "kind": "detail",
            "title_path": "data.draft.description",
            "status_path": "success",
        },
    },
)
