"""Runtime TUI metadata for current-user AI provider access."""

from __future__ import annotations

from typing import Any

RUNTIME_AI_OPS_MODULE: dict[str, Any] = {
    "key": "ai-ops",
    "label": "AI 助手",
    "group": "ops",
    "summary": "查看 AI 服务商、提示词模板、智能任务运行时与相关治理任务。",
}


RUNTIME_AI_MY_PROVIDERS_SCREEN: dict[str, Any] = {
    "key": "ai-ops.my-providers",
    "label": "我的 AI 服务商",
    "module_key": "ai-ops",
    "group": "ops",
    "summary": "管理个人 AI 服务商、查看自己的兜底配额和调用日志。",
    "view_type": "detail",
    "default_action_key": "ai-ops.list-my-providers",
    "user_experience": {
        "journey": "dashboard",
        "primary_task": "先确认个人 AI 服务商是否可用，再决定是否调整额度、密钥或排查最近调用日志。",
        "primary_outcome": "明确当前个人服务商状态、剩余额度，以及是否需要更新配置或处理失败日志。",
        "empty_state_hint": "先看个人服务商列表，再查看额度状态和最近调用日志。",
        "next_step_hint": "若服务商不可用或额度不足，继续在本屏执行创建、更新或切换动作。",
    },
    "workflow": {
        "name": "AI 管理流程",
        "step": 1,
        "total": 3,
        "label": "个人服务商",
        "role": "先看个人服务商是否可用，再检查自己配额与最近调用日志。",
        "previous": {"key": "ai-ops.providers", "label": "AI 服务商与用量"},
        "next": {},
    },
    "business_context": {
        "objective": "普通用户在 TUI 内完成个人 AI 接入与自查。",
        "decision_output": "当前个人服务商列表、启用状态、剩余额度以及最近失败日志。",
        "checkpoints": [
            "先看个人服务商列表与启用状态。",
            "需要新增密钥时在 TUI 直接创建或更新个人服务商。",
            "调用异常时对照 quota 与 logs 定位是否是额度或上游故障。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "my-provider-list",
            "title": "一、我的服务商",
            "kind": "datagrid",
            "action_key": "ai-ops.list-my-providers",
            "max_rows": 8,
            "layout_area": "providers",
            "target_screen": "ai-ops.my-providers",
            "columns": [
                {"key": "name", "label": "名称"},
                {"key": "provider_type_label", "label": "类型"},
                {"key": "default_model", "label": "默认模型"},
                {"key": "is_active", "label": "启用"},
                {"key": "priority", "label": "优先级"},
            ],
            "user_priority": "p0",
            "presentation_semantic": "primary_list",
        },
        {
            "key": "my-provider-quota",
            "title": "二、我的兜底配额",
            "kind": "detail",
            "action_key": "ai-ops.my-quota-current",
            "layout_area": "quota",
            "target_screen": "ai-ops.my-providers",
            "user_priority": "p1",
            "presentation_semantic": "primary_status",
        },
        {
            "key": "my-provider-logs",
            "title": "三、最近调用日志",
            "kind": "datagrid",
            "action_key": "ai-ops.my-ai-logs",
            "max_rows": 8,
            "layout_area": "logs",
            "target_screen": "ai-ops.my-providers",
            "columns": [
                {"key": "provider_name", "label": "服务商"},
                {"key": "model", "label": "模型"},
                {"key": "status", "label": "状态"},
                {"key": "estimated_cost", "label": "成本"},
                {"key": "created_at", "label": "时间"},
            ],
            "user_priority": "p2",
            "presentation_semantic": "supporting_list",
        },
    ],
}


RUNTIME_AI_USER_PROVIDER_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "ai-ops.list-my-providers",
        "label": "读取我的 AI 服务商",
        "endpoint": "/api/ai/me/providers/",
        "method": "GET",
        "intent": "list_current_user_ai_providers",
        "risk": "read",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "datagrid",
        "description": "读取当前用户自己的 AI 服务商列表。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 300,
        "task_tier": "primary",
        "fields": [],
        "view_model": {"kind": "datagrid"},
    },
    {
        "key": "ai-ops.my-provider-detail",
        "label": "读取我的服务商详情",
        "endpoint": "/api/ai/me/providers/<int:provider_id>/",
        "method": "GET",
        "intent": "read_current_user_ai_provider_detail",
        "risk": "read",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取一个个人 AI 服务商的配置详情。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 310,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.create-my-provider",
        "label": "创建我的服务商",
        "endpoint": "/api/ai/me/providers/",
        "method": "POST",
        "intent": "create_current_user_ai_provider",
        "risk": "write",
        "effect": "create",
        "confirmation_required": True,
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "为当前用户创建一个新的个人 AI 服务商。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 320,
        "task_tier": "operation",
        "fields": [
            {
                "key": "name",
                "label": "名称",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "provider_type",
                "label": "类型",
                "input_type": "select",
                "required": True,
                "default": "openai",
                "binding": "body",
                "value_type": "string",
                "options": ["openai", "deepseek", "qwen", "moonshot", "custom"],
            },
            {
                "key": "base_url",
                "label": "基础地址",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_key",
                "label": "API Key",
                "input_type": "password",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "default_model",
                "label": "默认模型",
                "input_type": "text",
                "required": False,
                "default": "gpt-3.5-turbo",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_mode",
                "label": "API 模式",
                "input_type": "select",
                "required": False,
                "default": "dual",
                "binding": "body",
                "value_type": "string",
                "options": ["dual", "responses_only", "chat_only"],
            },
            {
                "key": "priority",
                "label": "优先级",
                "input_type": "number",
                "required": False,
                "default": "10",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "select",
                "required": False,
                "default": "true",
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
            {
                "key": "fallback_enabled",
                "label": "允许故障切换",
                "input_type": "select",
                "required": False,
                "default": "true",
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
            {
                "key": "description",
                "label": "说明",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "extra_config",
                "label": "扩展配置",
                "input_type": "textarea",
                "required": False,
                "default": {},
                "binding": "body",
                "value_type": "object",
            },
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.update-my-provider",
        "label": "更新我的服务商",
        "endpoint": "/api/ai/me/providers/<int:provider_id>/",
        "method": "PATCH",
        "intent": "update_current_user_ai_provider",
        "risk": "write",
        "effect": "update",
        "confirmation_required": True,
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "更新一个已有的个人 AI 服务商。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 330,
        "task_tier": "operation",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "name",
                "label": "名称",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "provider_type",
                "label": "类型",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "string",
                "options": ["openai", "deepseek", "qwen", "moonshot", "custom"],
            },
            {
                "key": "base_url",
                "label": "基础地址",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_key",
                "label": "API Key",
                "input_type": "password",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "default_model",
                "label": "默认模型",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_mode",
                "label": "API 模式",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "string",
                "options": ["dual", "responses_only", "chat_only"],
            },
            {
                "key": "priority",
                "label": "优先级",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
            {
                "key": "fallback_enabled",
                "label": "允许故障切换",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
            {
                "key": "description",
                "label": "说明",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "extra_config",
                "label": "扩展配置",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "value_type": "object",
            },
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.toggle-my-provider",
        "label": "切换我的服务商启用",
        "endpoint": "/api/ai/me/providers/<int:provider_id>/toggle_active/",
        "method": "POST",
        "intent": "toggle_current_user_ai_provider",
        "risk": "write",
        "effect": "toggle",
        "confirmation_required": True,
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "切换个人 AI 服务商的启用状态。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 340,
        "task_tier": "operation",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.delete-my-provider",
        "label": "删除我的服务商",
        "endpoint": "/api/ai/me/providers/<int:provider_id>/",
        "method": "DELETE",
        "intent": "delete_current_user_ai_provider",
        "risk": "write",
        "effect": "delete",
        "confirmation_required": True,
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "message",
        "description": "删除一个个人 AI 服务商。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 350,
        "task_tier": "operation",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "message"},
    },
    {
        "key": "ai-ops.my-quota-current",
        "label": "读取我的 Quota",
        "endpoint": "/api/ai/me/quota/current/",
        "method": "GET",
        "intent": "read_current_user_ai_quota",
        "risk": "read",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取当前用户自己的兜底配额使用状态。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 360,
        "task_tier": "support",
        "fields": [],
        "view_model": {"kind": "detail", "title_path": "username", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.my-ai-logs",
        "label": "读取我的 AI 日志",
        "endpoint": "/api/ai/me/logs/",
        "method": "GET",
        "intent": "list_current_user_ai_logs",
        "risk": "read",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "datagrid",
        "description": "读取当前用户自己的 AI 调用日志。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 370,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider",
                "label": "服务商 ID",
                "input_type": "number",
                "required": False,
                "binding": "query",
                "value_type": "integer",
            },
            {
                "key": "status",
                "label": "状态",
                "input_type": "select",
                "required": False,
                "default": "",
                "binding": "query",
                "value_type": "string",
                "options": ["", "success", "error", "timeout", "rate_limited"],
            },
            {
                "key": "provider_scope",
                "label": "服务商范围",
                "input_type": "select",
                "required": False,
                "default": "",
                "binding": "query",
                "value_type": "string",
                "options": ["", "system_global", "system_fallback", "personal"],
            },
            {
                "key": "limit",
                "label": "返回行数",
                "input_type": "hidden",
                "required": False,
                "default": "50",
                "binding": "query",
                "value_type": "integer",
            },
        ],
        "view_model": {"kind": "datagrid"},
    },
)
