"""Runtime TUI metadata actions for administrator AI quota workflows."""

from __future__ import annotations

from typing import Any

RUNTIME_AI_QUOTA_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "ai-ops.list-user-quotas",
        "label": "读取用户 AI 配额",
        "endpoint": "/api/ai/admin/quotas/",
        "method": "GET",
        "intent": "list_admin_user_ai_quotas",
        "risk": "admin",
        "screen_key": "ai-ops.user-quotas",
        "module_key": "ai-ops",
        "view_type": "datagrid",
        "description": "读取所有用户的兜底配额列表。",
        "source": "approved:runtime-identity-access",
        "task_group": "05 配额治理",
        "sequence": 500,
        "task_tier": "primary",
        "fields": [],
        "view_model": {"kind": "datagrid"},
    },
    {
        "key": "ai-ops.user-quota-detail",
        "label": "读取用户 AI 配额详情",
        "endpoint": "/api/ai/admin/quotas/<int:user_id>/",
        "method": "GET",
        "intent": "read_admin_user_ai_quota_detail",
        "risk": "admin",
        "screen_key": "ai-ops.user-quotas",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取单个用户的兜底配额详情。",
        "source": "approved:runtime-identity-access",
        "task_group": "05 配额治理",
        "sequence": 510,
        "task_tier": "support",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "username", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.update-user-quota",
        "label": "更新用户 AI 配额",
        "endpoint": "/api/ai/admin/quotas/<int:user_id>/",
        "method": "PATCH",
        "intent": "update_admin_user_ai_quota",
        "risk": "admin",
        "screen_key": "ai-ops.user-quotas",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "更新单个用户的日度/月度兜底配额。",
        "source": "approved:runtime-identity-access",
        "task_group": "05 配额治理",
        "sequence": 520,
        "task_tier": "primary",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "daily_limit",
                "label": "日额度",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "monthly_limit",
                "label": "月额度",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
            {
                "key": "admin_note",
                "label": "管理员备注",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "detail", "title_path": "username", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.batch-apply-user-quotas",
        "label": "批量下发用户 AI 配额",
        "endpoint": "/api/ai/admin/quotas/batch_apply/",
        "method": "POST",
        "intent": "batch_apply_admin_user_ai_quota",
        "risk": "admin",
        "screen_key": "ai-ops.user-quotas",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "批量下发一套兜底配额到用户集合。",
        "source": "approved:runtime-identity-access",
        "task_group": "05 配额治理",
        "sequence": 530,
        "task_tier": "primary",
        "fields": [
            {
                "key": "daily_limit",
                "label": "日额度",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "monthly_limit",
                "label": "月额度",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "overwrite_existing",
                "label": "覆盖既有配置",
                "input_type": "select",
                "required": False,
                "default": "false",
                "binding": "body",
                "value_type": "boolean",
                "options": ["false", "true"],
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "select",
                "required": False,
                "default": "true",
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
            {
                "key": "admin_note",
                "label": "管理员备注",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "detail"},
    },
)
