"""Runtime TUI metadata for owner-scoped realtime alert management."""

from __future__ import annotations

from typing import Any

RUNTIME_REALTIME_GROUP: dict[str, Any] = {
    "key": "ops",
    "label": "运行管理",
}

RUNTIME_REALTIME_MODULE: dict[str, Any] = {
    "key": "realtime-monitor",
    "label": "实时提醒",
    "group": "ops",
    "summary": "集中管理自己的价格提醒和实时订阅。",
}

RUNTIME_REALTIME_SCREEN: dict[str, Any] = {
    "key": "realtime-monitor.alerts",
    "label": "价格提醒与订阅",
    "module_key": "realtime-monitor",
    "group": "ops",
    "summary": "查看触发条件，维护提醒，并选择需要持续接收价格更新的资产。",
    "view_type": "detail",
    "audience": "authenticated",
    "default_action_key": "realtime-monitor.list-alerts",
    "user_experience": {
        "journey": "workspace",
        "primary_task": "在一个屏内查看并维护自己的价格提醒和实时订阅。",
        "primary_outcome": "确认当前生效的提醒条件和订阅资产，并完成所需的新增、调整或停用。",
        "empty_state_hint": "先查看价格提醒；如果还没有提醒，可按资产、条件和阈值新建一条。",
        "next_step_hint": "维护完成后保持所需资产处于订阅状态，价格更新和提醒触发会自动送达。",
    },
    "business_context": {
        "objective": "避免错过关注资产的关键价格变化。",
        "decision_output": "生效提醒、已触发状态和持续接收价格更新的资产清单。",
        "checkpoints": [
            "确认资产代码和触发方向。",
            "核对阈值与提醒状态。",
            "只保留仍需持续跟踪的订阅。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "active-alerts",
            "title": "我的价格提醒",
            "kind": "datagrid",
            "action_key": "realtime-monitor.list-alerts",
            "max_rows": 20,
            "layout_area": "alerts",
            "target_screen": "realtime-monitor.alerts",
            "note": "优先核对仍在生效的提醒及其阈值。",
            "user_priority": "p0",
            "presentation_semantic": "primary_list",
            "columns": [
                {"key": "asset_code", "label": "资产"},
                {"key": "condition", "label": "条件"},
                {"key": "threshold", "label": "阈值"},
                {"key": "status", "label": "状态"},
            ],
        },
        {
            "key": "price-subscriptions",
            "title": "实时订阅资产",
            "kind": "datagrid",
            "action_key": "realtime-monitor.list-subscriptions",
            "max_rows": 20,
            "layout_area": "subscriptions",
            "target_screen": "realtime-monitor.alerts",
            "note": "这里的资产会持续接收最新价格更新。",
            "user_priority": "p1",
            "presentation_semantic": "supporting_list",
            "columns": [
                {"key": "asset_code", "label": "资产"},
                {"key": "created_at", "label": "订阅时间"},
            ],
        },
    ],
}

_ASSET_FIELD = {
    "key": "asset_code",
    "label": "资产代码",
    "input_type": "text",
    "required": True,
    "default": "",
    "placeholder": "510300.SH",
    "binding": "body",
    "value_type": "string",
    "presentation_semantic": "identifier",
}

RUNTIME_REALTIME_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "realtime-monitor.list-alerts",
        "label": "查看价格提醒",
        "endpoint": "/api/realtime/alerts/",
        "method": "GET",
        "intent": "list_owner_price_alerts",
        "risk": "read",
        "screen_key": "realtime-monitor.alerts",
        "module_key": "realtime-monitor",
        "view_type": "datagrid",
        "description": "列出当前账户的价格提醒及触发状态。",
        "source": "approved:runtime-realtime",
        "task_group": "01 提醒查看",
        "task_tier": "primary",
        "sequence": 100,
        "view_model": {"kind": "datagrid", "rows_path": "results"},
    },
    {
        "key": "realtime-monitor.create-alert",
        "label": "新建价格提醒",
        "endpoint": "/api/realtime/alerts/",
        "method": "POST",
        "intent": "create_owner_price_alert",
        "risk": "write",
        "screen_key": "realtime-monitor.alerts",
        "module_key": "realtime-monitor",
        "view_type": "detail",
        "description": "确认资产、方向和阈值后创建提醒。",
        "source": "approved:runtime-realtime",
        "task_group": "02 提醒维护",
        "task_tier": "primary",
        "sequence": 200,
        "confirmation_required": True,
        "audit_required": True,
        "fields": [
            dict(_ASSET_FIELD),
            {
                "key": "condition",
                "label": "触发条件",
                "input_type": "select",
                "required": True,
                "default": "cross_up",
                "placeholder": "",
                "binding": "body",
                "value_type": "string",
                "options": ["above", "below", "cross_up", "cross_down"],
            },
            {
                "key": "threshold",
                "label": "触发阈值",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "3.50",
                "binding": "body",
                "value_type": "decimal",
            },
            {
                "key": "message",
                "label": "提醒说明",
                "input_type": "text",
                "required": False,
                "default": "",
                "placeholder": "可选",
                "binding": "body",
                "value_type": "string",
            },
        ],
    },
    {
        "key": "realtime-monitor.update-alert",
        "label": "调整价格提醒",
        "endpoint": "/api/realtime/alerts/<int:alert_id>/",
        "method": "PATCH",
        "intent": "update_owner_price_alert",
        "risk": "write",
        "screen_key": "realtime-monitor.alerts",
        "module_key": "realtime-monitor",
        "view_type": "detail",
        "description": "选择一条提醒，确认后调整状态或阈值。",
        "source": "approved:runtime-realtime",
        "task_group": "02 提醒维护",
        "task_tier": "primary",
        "sequence": 210,
        "confirmation_required": True,
        "audit_required": True,
        "fields": [
            {
                "key": "alert_id",
                "label": "提醒编号",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "从提醒列表选择",
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "status",
                "label": "提醒状态",
                "input_type": "select",
                "required": False,
                "default": "",
                "placeholder": "保持不变",
                "binding": "body",
                "value_type": "string",
                "options": ["active", "inactive"],
            },
            {
                "key": "threshold",
                "label": "触发阈值",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "保持不变",
                "binding": "body",
                "value_type": "decimal",
            },
        ],
    },
    {
        "key": "realtime-monitor.delete-alert",
        "label": "删除价格提醒",
        "endpoint": "/api/realtime/alerts/<int:alert_id>/",
        "method": "DELETE",
        "intent": "delete_owner_price_alert",
        "risk": "write",
        "screen_key": "realtime-monitor.alerts",
        "module_key": "realtime-monitor",
        "view_type": "message",
        "description": "选择一条不再需要的提醒并确认删除。",
        "source": "approved:runtime-realtime",
        "task_group": "02 提醒维护",
        "task_tier": "advanced",
        "sequence": 220,
        "confirmation_required": True,
        "audit_required": True,
        "fields": [
            {
                "key": "alert_id",
                "label": "提醒编号",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "从提醒列表选择",
                "binding": "path",
                "value_type": "integer",
            }
        ],
    },
    {
        "key": "realtime-monitor.list-subscriptions",
        "label": "查看实时订阅",
        "endpoint": "/api/realtime/subscriptions/",
        "method": "GET",
        "intent": "list_owner_price_subscriptions",
        "risk": "read",
        "screen_key": "realtime-monitor.alerts",
        "module_key": "realtime-monitor",
        "view_type": "datagrid",
        "description": "列出当前账户持续接收价格更新的资产。",
        "source": "approved:runtime-realtime",
        "task_group": "03 实时订阅",
        "task_tier": "support",
        "sequence": 300,
        "view_model": {"kind": "datagrid", "rows_path": "results"},
    },
    {
        "key": "realtime-monitor.subscribe",
        "label": "添加实时订阅",
        "endpoint": "/api/realtime/subscriptions/",
        "method": "POST",
        "intent": "create_owner_price_subscription",
        "risk": "write",
        "screen_key": "realtime-monitor.alerts",
        "module_key": "realtime-monitor",
        "view_type": "detail",
        "description": "确认资产代码后开始持续接收价格更新。",
        "source": "approved:runtime-realtime",
        "task_group": "03 实时订阅",
        "task_tier": "support",
        "sequence": 310,
        "confirmation_required": True,
        "audit_required": True,
        "fields": [dict(_ASSET_FIELD)],
    },
    {
        "key": "realtime-monitor.unsubscribe",
        "label": "移除实时订阅",
        "endpoint": "/api/realtime/subscriptions/<str:asset_code>/",
        "method": "DELETE",
        "intent": "delete_owner_price_subscription",
        "risk": "write",
        "screen_key": "realtime-monitor.alerts",
        "module_key": "realtime-monitor",
        "view_type": "message",
        "description": "选择不再持续跟踪的资产并确认移除。",
        "source": "approved:runtime-realtime",
        "task_group": "03 实时订阅",
        "task_tier": "support",
        "sequence": 320,
        "confirmation_required": True,
        "audit_required": True,
        "fields": [
            {
                **_ASSET_FIELD,
                "placeholder": "从订阅列表选择",
                "binding": "path",
            }
        ],
    },
)
