"""Runtime TUI metadata for investment signal management tasks."""

from __future__ import annotations

from typing import Any

from apps.regime.domain.services_v2 import RegimeType

_DIRECTION_OPTIONS = ["LONG", "SHORT", "NEUTRAL"]
_REGIME_OPTIONS = [regime.value for regime in RegimeType]
_STATUS_OPTIONS = ["", "pending", "approved", "rejected", "invalidated", "expired"]

_SIGNAL_EDIT_FIELDS: tuple[dict[str, Any], ...] = (
    {
        "key": "asset_code",
        "label": "资产代码",
        "input_type": "text",
        "required": False,
        "binding": "body",
        "value_type": "string",
    },
    {
        "key": "asset_class",
        "label": "资产类别",
        "input_type": "text",
        "required": False,
        "binding": "body",
        "value_type": "string",
    },
    {
        "key": "direction",
        "label": "方向",
        "input_type": "select",
        "required": False,
        "binding": "body",
        "value_type": "string",
        "options": _DIRECTION_OPTIONS,
    },
    {
        "key": "logic_desc",
        "label": "投资逻辑",
        "input_type": "textarea",
        "required": False,
        "binding": "body",
        "value_type": "string",
    },
    {
        "key": "invalidation_logic",
        "label": "证伪逻辑",
        "input_type": "textarea",
        "required": False,
        "binding": "body",
        "value_type": "string",
    },
    {
        "key": "target_regime",
        "label": "目标环境",
        "input_type": "select",
        "required": False,
        "binding": "body",
        "value_type": "string",
        "options": _REGIME_OPTIONS,
    },
)


def _signal_id_field() -> dict[str, Any]:
    """Return an isolated path-field definition for one signal."""

    return {
        "key": "signal_id",
        "label": "信号 ID",
        "input_type": "number",
        "required": True,
        "binding": "path",
        "value_type": "integer",
    }


RUNTIME_SIGNAL_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "signal.list",
        "label": "筛选投资信号",
        "endpoint": "/api/signal/",
        "method": "GET",
        "intent": "list_investment_signals",
        "risk": "read",
        "screen_key": "research.signals",
        "module_key": "daily-decisions",
        "view_type": "datagrid",
        "description": "按状态、资产类别、方向或关键词筛选投资信号。",
        "source": "approved:runtime-signal-management",
        "task_group": "01 有效信号",
        "sequence": 115,
        "task_tier": "primary",
        "fields": [
            {
                "key": "status",
                "label": "状态",
                "input_type": "select",
                "required": False,
                "binding": "query",
                "value_type": "string",
                "options": _STATUS_OPTIONS,
            },
            {
                "key": "asset_class",
                "label": "资产类别",
                "input_type": "text",
                "required": False,
                "binding": "query",
                "value_type": "string",
            },
            {
                "key": "direction",
                "label": "方向",
                "input_type": "select",
                "required": False,
                "binding": "query",
                "value_type": "string",
                "options": ["", *_DIRECTION_OPTIONS],
            },
            {
                "key": "search",
                "label": "关键词",
                "input_type": "text",
                "required": False,
                "binding": "query",
                "value_type": "string",
            },
            {
                "key": "limit",
                "label": "返回行数",
                "input_type": "hidden",
                "required": False,
                "default": "50",
                "binding": "query",
                "value_type": "integer",
            },
        ],
        "view_model": {"kind": "datagrid"},
    },
    {
        "key": "signal.create",
        "label": "创建投资信号",
        "endpoint": "/api/signal/",
        "method": "POST",
        "intent": "create_investment_signal",
        "risk": "admin",
        "audience": "admin",
        "effect": "create",
        "confirmation_required": True,
        "screen_key": "research.signals",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "创建带有量化证伪逻辑的投资信号。",
        "source": "approved:runtime-signal-management",
        "task_group": "02 信号治理",
        "sequence": 160,
        "task_tier": "primary",
        "fields": [
            {
                **field,
                "required": field["key"]
                in {
                    "asset_code",
                    "asset_class",
                    "direction",
                    "logic_desc",
                    "invalidation_logic",
                    "target_regime",
                },
            }
            for field in _SIGNAL_EDIT_FIELDS
        ],
        "view_model": {"kind": "detail", "title_path": "asset_code", "status_path": "status"},
    },
    {
        "key": "signal.update",
        "label": "更新投资信号",
        "endpoint": "/api/signal/<int:signal_id>/",
        "method": "PATCH",
        "intent": "update_investment_signal",
        "risk": "admin",
        "audience": "admin",
        "effect": "update",
        "confirmation_required": True,
        "screen_key": "research.signals",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "更新一个投资信号及其证伪逻辑。",
        "source": "approved:runtime-signal-management",
        "task_group": "02 信号治理",
        "sequence": 170,
        "task_tier": "support",
        "fields": [_signal_id_field(), *[dict(field) for field in _SIGNAL_EDIT_FIELDS]],
        "view_model": {"kind": "detail", "title_path": "asset_code", "status_path": "status"},
    },
    {
        "key": "signal.approve",
        "label": "批准投资信号",
        "endpoint": "/api/signal/<int:signal_id>/approve/",
        "method": "POST",
        "intent": "approve_investment_signal",
        "risk": "admin",
        "audience": "admin",
        "effect": "update",
        "confirmation_required": True,
        "screen_key": "research.signals",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "将待处理信号批准为有效信号。",
        "source": "approved:runtime-signal-management",
        "task_group": "02 信号治理",
        "sequence": 180,
        "task_tier": "support",
        "fields": [_signal_id_field()],
        "view_model": {"kind": "detail", "title_path": "asset_code", "status_path": "status"},
    },
    {
        "key": "signal.reject",
        "label": "拒绝投资信号",
        "endpoint": "/api/signal/<int:signal_id>/reject/",
        "method": "POST",
        "intent": "reject_investment_signal",
        "risk": "admin",
        "audience": "admin",
        "effect": "update",
        "confirmation_required": True,
        "screen_key": "research.signals",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "记录原因并拒绝一个待处理信号。",
        "source": "approved:runtime-signal-management",
        "task_group": "02 信号治理",
        "sequence": 190,
        "task_tier": "support",
        "fields": [
            _signal_id_field(),
            {
                "key": "reason",
                "label": "拒绝原因",
                "input_type": "textarea",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "detail", "title_path": "asset_code", "status_path": "status"},
    },
    {
        "key": "signal.invalidate",
        "label": "证伪投资信号",
        "endpoint": "/api/signal/<int:signal_id>/invalidate/",
        "method": "POST",
        "intent": "invalidate_investment_signal",
        "risk": "admin",
        "audience": "admin",
        "effect": "update",
        "confirmation_required": True,
        "screen_key": "research.signals",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "记录证据并把已批准信号标为已证伪。",
        "source": "approved:runtime-signal-management",
        "task_group": "02 信号治理",
        "sequence": 200,
        "task_tier": "primary",
        "fields": [
            _signal_id_field(),
            {
                "key": "reason",
                "label": "证伪原因",
                "input_type": "textarea",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "detail", "title_path": "asset_code", "status_path": "status"},
    },
    {
        "key": "signal.delete",
        "label": "删除投资信号",
        "endpoint": "/api/signal/<int:signal_id>/",
        "method": "DELETE",
        "intent": "delete_investment_signal",
        "risk": "admin",
        "audience": "admin",
        "effect": "delete",
        "confirmation_required": True,
        "screen_key": "research.signals",
        "module_key": "daily-decisions",
        "view_type": "message",
        "description": "永久删除一个投资信号。",
        "source": "approved:runtime-signal-management",
        "task_group": "02 信号治理",
        "sequence": 210,
        "task_tier": "support",
        "fields": [_signal_id_field()],
        "view_model": {"kind": "message"},
    },
    {
        "key": "signal.batch-check",
        "label": "检查全部信号证伪条件",
        "endpoint": "/api/signal/batch-check/",
        "method": "POST",
        "intent": "batch_check_signal_invalidation",
        "risk": "admin",
        "audience": "admin",
        "effect": "execute",
        "confirmation_required": True,
        "screen_key": "research.signals",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "检查全部待处理和已批准信号，并按证伪规则更新状态。",
        "source": "approved:runtime-signal-management",
        "task_group": "02 信号治理",
        "sequence": 220,
        "task_tier": "primary",
        "fields": [],
        "view_model": {"kind": "detail"},
    },
)
