"""Runtime TUI metadata for MCP self-service and administration."""

from __future__ import annotations

from typing import Any

RUNTIME_MCP_ACCESS_MODULE: dict[str, Any] = {
    "key": "mcp-access",
    "label": "我的 MCP 接入",
    "group": "ops",
    "summary": "获取、复制和验证当前账号的 MCP 接入材料。",
}

RUNTIME_MCP_SELF_SERVICE_SCREEN: dict[str, Any] = {
    "key": "capability-router.self-service",
    "label": "我的 MCP 接入",
    "module_key": "mcp-access",
    "group": "ops",
    "summary": "管理自己的 MCP 接入令牌、读写级别，以及一键复制给 AI 代理的接入提示词。",
    "view_type": "detail",
    "audience": "authenticated",
    "default_action_key": "capability-router.mcp-self-status",
    "user_experience": {
        "journey": "self_service",
        "primary_task": "在一个屏内完成 MCP 状态确认、令牌管理、连接地址复制和代理接入提示词获取。",
        "primary_outcome": "拿到完整可复制的接入令牌、路由地址、能力目录和接入提示词，并明确下一步是否创建或撤销令牌。",
        "empty_state_hint": "先读取我的 MCP 状态；如果未开通，回到上一屏完成接入，再返回这里生成或管理令牌。",
        "next_step_hint": "完成复制后，把接入提示词和路由地址粘贴给外部代理；旧令牌不再使用时立即撤销。",
    },
    "workflow": {
        "name": "能力接入流程",
        "label": "个人接入",
        "role": "先确认自己是否已开通 MCP，再生成令牌并复制代理接入提示词。",
        "previous": {},
        "next": {},
    },
    "business_context": {
        "objective": "在 TUI 内完成个人 MCP 接入，不再依赖网页表单。",
        "decision_output": "当前权限状态、可用令牌、推荐接入提示词，以及是否需要新建或撤销令牌。",
        "checkpoints": [
            "先读个人 MCP 状态，确认 mcp_enabled、默认账户和可复制提示词。",
            "需要新令牌时明确读写级别，再执行创建。",
            "旧令牌不再使用时立即撤销，避免凭证扩散。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "mcp-access-package",
            "title": "一、完整接入包",
            "kind": "detail",
            "action_key": "capability-router.mcp-self-status",
            "max_rows": 8,
            "layout_area": "summary",
            "target_screen": "capability-router.self-service",
            "note": "令牌、智能路由地址、能力目录、接入提示词和环境说明集中在这里。",
            "user_priority": "p0",
            "presentation_semantic": "copyable_secret",
        },
        {
            "key": "mcp-access-verification",
            "title": "二、验证接入状态",
            "kind": "detail",
            "action_key": "capability-router.verify-my-mcp-access",
            "max_rows": 6,
            "layout_area": "verification",
            "target_screen": "capability-router.self-service",
            "note": "只读检查当前凭证、智能路由和能力目录，不会调用模型或修改配置。",
            "user_priority": "p1",
            "presentation_semantic": "primary_status",
        },
        {
            "key": "mcp-self-tokens",
            "title": "三、令牌历史",
            "kind": "datagrid",
            "action_key": "capability-router.list-my-mcp-tokens",
            "max_rows": 8,
            "layout_area": "tokens",
            "target_screen": "capability-router.self-service",
            "columns": [
                {"key": "name", "label": "名称"},
                {"key": "preview", "label": "预览"},
                {"key": "access_level_label", "label": "级别"},
                {"key": "last_used_at", "label": "最后使用"},
            ],
            "user_priority": "p2",
            "presentation_semantic": "supporting_list",
        },
    ],
}

RUNTIME_MCP_ADMIN_ACCESS_SCREEN: dict[str, Any] = {
    "key": "capability-router.admin-access",
    "label": "MCP 用户治理",
    "module_key": "mcp-governance",
    "group": "ops",
    "summary": "管理员在 TUI 内管理用户 MCP 开关、令牌发放与撤销。",
    "view_type": "detail",
    "audience": "admin",
    "default_action_key": "capability-router.mcp-admin-users",
    "user_experience": {
        "journey": "admin",
        "primary_task": "筛出需要开通、收紧或回收凭证的用户，并在同屏完成 MCP 用户治理。",
        "primary_outcome": "明确哪些用户缺令牌、哪些凭证仍在使用、哪些用户的读写权限需要调整。",
        "empty_state_hint": "先读取用户与令牌分布，再按“仅无令牌”“仅已启用”等筛选条件定位目标用户。",
        "next_step_hint": "确认用户状态后再执行发放、开关或撤销操作，并复核令牌是否已收紧。",
    },
    "workflow": {
        "name": "能力接入流程",
        "label": "管理员治理",
        "role": "先筛用户，再发令牌、控读写权限并回收凭证。",
        "previous": {},
        "next": {},
    },
    "business_context": {
        "objective": "让管理员在 TUI 内闭环管理普通用户与管理员自己的 MCP 凭证策略。",
        "decision_output": "哪些用户未开通 MCP、哪些令牌仍在使用、哪些读写凭证需要收紧。",
        "checkpoints": [
            "先看用户列表和“仅无令牌”筛选，定位待发放用户。",
            "发放令牌时明确访问级别，不默认给读写。",
            "关闭用户 MCP 时同步回收其有效令牌。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "mcp-admin-users",
            "title": "一、用户与令牌分布",
            "kind": "datagrid",
            "action_key": "capability-router.mcp-admin-users",
            "max_rows": 10,
            "layout_area": "users",
            "target_screen": "capability-router.admin-access",
            "columns": [
                {"key": "user_id", "label": "用户 ID"},
                {"key": "username", "label": "用户"},
                {"key": "rbac_role", "label": "角色"},
                {"key": "mcp_enabled", "label": "MCP"},
                {"key": "token_count", "label": "令牌数"},
                {"key": "read_only_token_count", "label": "只读数"},
            ],
            "row_actions": [
                {
                    "action_key": "capability-router.mcp-admin-user-detail",
                    "label_template": "查看 {username} 的 MCP 详情",
                    "param_map": {"user_id": "user_id"},
                },
                {
                    "action_key": "capability-router.admin-create-mcp-token",
                    "label_template": "为 {username} 发放只读令牌",
                    "param_map": {"user_id": "user_id"},
                },
                {
                    "action_key": "capability-router.admin-toggle-user-mcp",
                    "label_template": "切换 {username} 的 MCP 开关",
                    "param_map": {"user_id": "user_id"},
                },
                {
                    "action_key": "capability-router.admin-revoke-user-mcp-tokens",
                    "label_template": "回收 {username} 的全部 MCP 令牌",
                    "param_map": {"user_id": "user_id"},
                },
            ],
            "user_priority": "p0",
            "presentation_semantic": "primary_list",
        }
    ],
}


RUNTIME_MCP_ACCESS_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "capability-router.mcp-self-status",
        "label": "读取我的 MCP 状态",
        "endpoint": "/api/account/mcp/self/",
        "method": "GET",
        "intent": "read_current_user_mcp_self_service",
        "risk": "read",
        "screen_key": "capability-router.self-service",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "读取当前用户的 MCP 开通状态、默认账户、令牌与代理接入提示词。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 100,
        "task_tier": "primary",
        "fields": [],
        "view_model": {
            "kind": "detail",
            "title_path": "username",
            "status_path": "mcp_enabled",
            "field_presentations": {
                "access_token": "secret",
                "route_endpoint": "copyable",
                "capability_catalog_endpoint": "copyable",
                "access_package": "multiline",
                "environment_statement": "metadata",
            },
        },
        "result_semantics": ["primary_status", "copyable_secret"],
    },
    {
        "key": "capability-router.verify-my-mcp-access",
        "label": "验证我的 MCP 接入",
        "endpoint": "/api/ai-capability/mcp-access/verify/",
        "method": "GET",
        "intent": "verify_current_user_mcp_access",
        "risk": "read",
        "screen_key": "capability-router.self-service",
        "module_key": "mcp-access",
        "view_type": "detail",
        "description": "只读检查当前凭证、智能路由与能力目录是否可用。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 105,
        "task_tier": "primary",
        "fields": [],
        "view_model": {"kind": "detail", "status_path": "state"},
        "result_semantics": ["primary_status"],
    },
    {
        "key": "capability-router.list-my-mcp-tokens",
        "label": "读取我的令牌列表",
        "endpoint": "/api/account/mcp/self/",
        "method": "GET",
        "intent": "list_current_user_mcp_tokens",
        "risk": "read",
        "screen_key": "capability-router.self-service",
        "module_key": "capability-router",
        "view_type": "datagrid",
        "description": "从个人 MCP 状态接口中提取自己的有效令牌列表。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 110,
        "task_tier": "support",
        "fields": [],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "access_tokens",
            "total_path": "active_token_count",
        },
        "result_semantics": ["supporting_list"],
    },
    {
        "key": "capability-router.mcp-self-endpoints",
        "label": "读取我的接入地址",
        "endpoint": "/api/account/mcp/self/",
        "method": "GET",
        "intent": "read_current_user_mcp_endpoints",
        "risk": "read",
        "screen_key": "capability-router.self-service",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "读取当前用户接入 AgomTradePro 所需的基础地址、路由地址、网页对话地址与能力目录。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 115,
        "task_tier": "support",
        "fields": [],
        "view_model": {"kind": "detail", "title_path": "username", "status_path": "mcp_enabled"},
        "result_semantics": ["endpoint_list"],
    },
    {
        "key": "capability-router.mcp-self-prompt-guide",
        "label": "读取我的接入提示词",
        "endpoint": "/api/account/mcp/self/",
        "method": "GET",
        "intent": "read_current_user_mcp_prompt_guide",
        "risk": "read",
        "screen_key": "capability-router.self-service",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "读取当前用户可直接发给外部代理的 MCP/SDK 接入提示词。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 117,
        "task_tier": "support",
        "fields": [],
        "view_model": {
            "kind": "detail",
            "title_path": "username",
            "status_path": "agent_bootstrap_token_ready",
        },
        "result_semantics": ["multiline_prompt"],
    },
    {
        "key": "capability-router.create-my-mcp-token",
        "label": "创建我的 MCP 令牌",
        "endpoint": "/api/account/mcp/tokens/",
        "method": "POST",
        "intent": "create_current_user_mcp_token",
        "risk": "write",
        "screen_key": "capability-router.self-service",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "为当前用户创建一个新的 MCP 令牌，并返回可直接粘贴给外部代理的接入提示词。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 120,
        "task_tier": "operation",
        "fields": [
            {
                "key": "token_name",
                "label": "令牌名称",
                "input_type": "text",
                "required": False,
                "placeholder": "留空则自动生成",
                "binding": "body",
                "value_type": "string",
                "presentation_semantic": "identifier",
            },
            {
                "key": "access_level",
                "label": "访问级别",
                "input_type": "select",
                "required": True,
                "default": "read_only",
                "binding": "body",
                "value_type": "string",
                "options": ["read_only", "read_write"],
                "presentation_semantic": "identifier",
            },
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
        "result_semantics": ["copyable_secret", "multiline_prompt"],
    },
    {
        "key": "capability-router.revoke-my-mcp-token",
        "label": "撤销我的 MCP 令牌",
        "endpoint": "/api/account/mcp/tokens/<int:token_id>/revoke/",
        "method": "POST",
        "intent": "revoke_current_user_mcp_token",
        "risk": "write",
        "screen_key": "capability-router.self-service",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "撤销当前用户自己名下的一个有效 MCP 令牌。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 130,
        "task_tier": "operation",
        "fields": [
            {
                "key": "token_id",
                "label": "令牌 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
                "presentation_semantic": "primary_selector",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "capability-router.mcp-admin-users",
        "label": "读取 MCP 用户列表",
        "endpoint": "/api/account/admin/mcp/users/",
        "method": "GET",
        "intent": "list_admin_mcp_user_governance_rows",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "datagrid",
        "description": "读取管理员视角下的 MCP 用户、令牌与开关分布。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 200,
        "task_tier": "primary",
        "fields": [
            {
                "key": "q",
                "label": "关键词",
                "input_type": "text",
                "required": False,
                "default": "",
                "placeholder": "搜索用户名或邮箱",
                "binding": "query",
                "value_type": "string",
            },
            {
                "key": "without_token",
                "label": "仅无令牌",
                "input_type": "select",
                "required": False,
                "default": "false",
                "binding": "query",
                "value_type": "boolean",
                "options": ["false", "true"],
            },
        ],
        "view_model": {"kind": "datagrid", "rows_path": "rows", "total_path": "total_users"},
    },
    {
        "key": "capability-router.mcp-admin-user-detail",
        "label": "读取用户 MCP 详情",
        "endpoint": "/api/account/admin/mcp/users/<int:user_id>/",
        "method": "GET",
        "intent": "read_admin_mcp_user_detail",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "查看单个用户的 MCP 状态、令牌以及可复制接入提示词。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 210,
        "task_tier": "support",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "username", "status_path": "mcp_enabled"},
    },
    {
        "key": "capability-router.admin-create-mcp-token",
        "label": "为用户创建 MCP 令牌",
        "endpoint": "/api/account/admin/mcp/users/<int:user_id>/tokens/",
        "method": "POST",
        "intent": "create_admin_managed_mcp_token",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "管理员为指定用户创建一个新令牌，并返回可转发给外部代理的接入提示词。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 220,
        "task_tier": "primary",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "token_name",
                "label": "令牌名称",
                "input_type": "text",
                "required": False,
                "placeholder": "留空则自动生成",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "access_level",
                "label": "访问级别",
                "input_type": "select",
                "required": True,
                "default": "read_only",
                "binding": "body",
                "value_type": "string",
                "options": ["read_only", "read_write"],
            },
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "capability-router.admin-toggle-user-mcp",
        "label": "切换用户 MCP 开关",
        "endpoint": "/api/account/admin/mcp/users/<int:user_id>/toggle/",
        "method": "POST",
        "intent": "toggle_admin_managed_user_mcp",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "管理员直接开启或关闭用户 MCP 权限。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 230,
        "task_tier": "primary",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "capability-router.admin-revoke-user-mcp-tokens",
        "label": "撤销用户全部令牌",
        "endpoint": "/api/account/admin/mcp/users/<int:user_id>/tokens/revoke/",
        "method": "POST",
        "intent": "revoke_admin_managed_user_mcp_tokens",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "管理员一次性回收指定用户的全部 MCP 令牌。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 240,
        "task_tier": "support",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "capability-router.admin-revoke-mcp-token",
        "label": "撤销单个用户令牌",
        "endpoint": "/api/account/admin/mcp/tokens/<int:token_id>/revoke/",
        "method": "POST",
        "intent": "revoke_admin_managed_single_mcp_token",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "管理员按 token_id 回收单个 MCP 令牌。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 250,
        "task_tier": "support",
        "fields": [
            {
                "key": "token_id",
                "label": "令牌 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
)
