"""Runtime TUI metadata injection constants for risk-center surfaces."""

from __future__ import annotations

from typing import Any

RUNTIME_RISK_CENTER_MODULE: dict[str, Any] = {
    "key": "risk-center",
    "label": "风控中心",
    "group": "workflow",
    "summary": "集中查看全局底线、账户策略、有效策略和管理员例外。",
}

RUNTIME_RISK_CENTER_SCREEN: dict[str, Any] = {
    "key": "risk-center.overview",
    "label": "集中风控中心",
    "module_key": "risk-center",
    "group": "workflow",
    "summary": "查看当前情景、数据健康和组合影响，并通过预览与人工确认治理情景版本。",
    "view_type": "detail",
    "dashboard_layout": "task_flow",
    "default_action_key": "risk-center.active-scenario-set",
    "entry_mode": "direct",
    "entry_empty_copy": "当前没有已激活的情景集；管理员可先创建草稿并完成预览和审批。",
    "entry_help_steps": [
        "先查看当前生效情景集和五维市场证据。",
        "选择组合快照并预览各情景影响。",
        "需要调整时先生成差异预览，再交由有权限的人类确认。",
    ],
    "business_context": {
        "objective": "查看并调整未来情景，预览对组合的影响。",
        "decision_output": "情景版本、主情景概率、证据新鲜度、组合影响和明确阻断原因。",
        "checkpoints": [
            "先确认情景版本、证据时间和数据健康。",
            "组合影响必须引用不可变快照和 Allocation Policy 版本。",
            "激活和回滚只允许人类管理员在持久审批后执行。",
        ],
    },
    "user_experience": {
        "journey": "workspace",
        "primary_task": "查看并调整未来情景，预览对组合的影响。",
        "primary_outcome": "形成引用确定情景版本、组合快照和数据证据的可复核预览。",
        "empty_state_hint": "尚无已激活情景集时，先创建草稿并完成影响预览。",
        "next_step_hint": "确认数据健康和组合影响后，再由有权限的人类审批并激活。",
    },
    "dashboard_panels": [
        {
            "key": "active-scenario-set",
            "title": "当前生效情景集",
            "kind": "detail",
            "action_key": "risk-center.active-scenario-set",
            "layout_area": "active_scenarios",
            "target_screen": "risk-center.overview",
            "empty_message": "当前没有已激活情景集，决策入口保持阻断。",
            "error_message": "情景集读取失败，不能用于决策。",
            "stale_message": "情景证据已过期，请复核后再使用。",
            "user_priority": "p0",
            "presentation_semantic": "primary_status",
        },
        {
            "key": "scenario-impact",
            "title": "组合影响预览",
            "kind": "detail",
            "action_key": "risk-center.scenario-impact-preview",
            "layout_area": "portfolio_impact",
            "target_screen": "risk-center.overview",
            "empty_message": "选择情景集版本和组合快照后生成影响预览。",
            "error_message": "组合影响预览失败，不能用于决策。",
            "stale_message": "组合或数据证据已变化，请重新预览。",
            "user_priority": "p0",
            "presentation_semantic": "primary_status",
        },
        {
            "key": "market-state-evidence",
            "title": "五维市场状态与数据健康",
            "kind": "detail",
            "action_key": "risk-center.market-state",
            "layout_area": "market_evidence",
            "target_screen": "risk-center.overview",
            "empty_message": "暂无完整五维证据；缺失项不会按中性值处理。",
            "error_message": "市场证据读取失败，情景调整入口保持阻断。",
            "stale_message": "部分市场证据已过期，请先刷新数据。",
            "user_priority": "p0",
            "presentation_semantic": "primary_status",
        },
        {
            "key": "scenario-catalog",
            "title": "情景版本目录",
            "kind": "datagrid",
            "action_key": "risk-center.scenario-list",
            "layout_area": "scenario_catalog",
            "target_screen": "risk-center.overview",
            "empty_message": "暂无情景定义。",
            "user_priority": "p1",
            "presentation_semantic": "supporting_list",
        },
    ],
}

RUNTIME_RISK_CENTER_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "risk-center.floor",
        "label": "全局底线",
        "endpoint": "/api/risk-center/floor/",
        "method": "GET",
        "intent": "read_global_risk_floor",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "读取当前启用的全局风控底线。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 100,
        "task_tier": "primary",
        "view_model": {"kind": "detail", "title_path": "data.name", "status_path": "success"},
    },
    {
        "key": "risk-center.templates",
        "label": "风险模板",
        "endpoint": "/api/risk-center/templates/",
        "method": "GET",
        "intent": "list_risk_templates",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "datagrid",
        "description": "列出全局风险模板。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 110,
        "task_tier": "support",
        "view_model": {"kind": "datagrid", "rows_path": "data"},
    },
    {
        "key": "risk-center.account-policies",
        "label": "账户策略",
        "endpoint": "/api/risk-center/account-policies/",
        "method": "GET",
        "intent": "list_account_risk_policies",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "datagrid",
        "description": "列出当前用户可访问的账户级风控策略。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 120,
        "task_tier": "primary",
        "view_model": {"kind": "datagrid", "rows_path": "data"},
    },
    {
        "key": "risk-center.effective-policy",
        "label": "账户有效策略",
        "endpoint": "/api/risk-center/effective-policy/",
        "method": "GET",
        "intent": "resolve_effective_risk_policy",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "按账户 ID 解析最终生效策略、继承来源、底线和例外说明。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 130,
        "task_tier": "primary",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "输入账户 ID",
                "binding": "query",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "data.account_id", "status_path": "success"},
    },
    {
        "key": "risk-center.exceptions",
        "label": "风控例外",
        "endpoint": "/api/risk-center/exceptions/",
        "method": "GET",
        "intent": "list_risk_exceptions",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "datagrid",
        "description": "列出管理员风控例外，可按账户过滤。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 140,
        "task_tier": "support",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "可选",
                "binding": "query",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "datagrid", "rows_path": "data"},
    },
    {
        "key": "risk-center.pre-trade-check",
        "label": "交易前风控预览",
        "endpoint": "/api/risk-center/pre-trade-check/",
        "method": "POST",
        "intent": "preview_pre_trade_risk",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "输入一笔拟交易，预览集中风控中心是否会拒绝。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 150,
        "task_tier": "primary",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "输入账户 ID",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "symbol",
                "label": "证券代码",
                "input_type": "text",
                "required": True,
                "default": "",
                "placeholder": "000001.SZ",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "side",
                "label": "方向",
                "input_type": "select",
                "required": True,
                "default": "buy",
                "placeholder": "",
                "binding": "body",
                "value_type": "string",
                "options": ["buy", "sell"],
            },
            {
                "key": "quantity",
                "label": "数量",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "100",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "price",
                "label": "价格",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "10.00",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "account_equity",
                "label": "账户权益",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "100000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "total_position_value",
                "label": "当前总持仓",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "50000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "cash_balance",
                "label": "现金余额",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "50000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "current_symbol_position_value",
                "label": "当前单标的市值",
                "input_type": "number",
                "required": False,
                "default": 0,
                "placeholder": "0",
                "binding": "body",
                "value_type": "float",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.passed"},
    },
    {
        "key": "risk-center.post-investment-check",
        "label": "投后风控巡检",
        "endpoint": "/api/risk-center/post-investment-check/",
        "method": "POST",
        "intent": "track_post_investment_risk",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "输入账户权益、现金和持仓快照，巡检集中风控是否已触碰。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 160,
        "task_tier": "primary",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "输入账户 ID",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "account_equity",
                "label": "账户权益",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "100000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "cash_balance",
                "label": "现金余额",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "20000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "total_position_value",
                "label": "持仓总市值",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "80000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "daily_pnl_pct",
                "label": "当日盈亏比例",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "-0.03",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "drawdown_pct",
                "label": "当前回撤比例",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "0.08",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "positions",
                "label": "持仓快照",
                "input_type": "textarea",
                "required": False,
                "default": "[]",
                "placeholder": '[{"symbol":"000001.SZ","market_value":30000,"unrealized_pnl_pct":-0.08}]',
                "binding": "body",
                "value_type": "list",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.status"},
    },
    {
        "key": "risk-center.daily-report",
        "label": "风控/持仓日报",
        "endpoint": "/api/risk-center/daily-report/",
        "method": "POST",
        "intent": "generate_risk_and_position_daily_report",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "输入账户日终快照，生成风控日报和持仓日报。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 170,
        "task_tier": "primary",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "输入账户 ID",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "report_date",
                "label": "报告日期",
                "input_type": "date",
                "required": False,
                "default": "",
                "placeholder": "YYYY-MM-DD",
                "binding": "body",
                "value_type": "date",
            },
            {
                "key": "account_equity",
                "label": "账户权益",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "100000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "cash_balance",
                "label": "现金余额",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "20000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "total_position_value",
                "label": "持仓总市值",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "80000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "daily_pnl_pct",
                "label": "当日盈亏比例",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "-0.03",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "drawdown_pct",
                "label": "当前回撤比例",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "0.08",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "positions",
                "label": "持仓快照",
                "input_type": "textarea",
                "required": False,
                "default": "[]",
                "placeholder": '[{"symbol":"000001.SZ","market_value":30000,"unrealized_pnl_pct":-0.08}]',
                "binding": "body",
                "value_type": "list",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.risk_daily_report.status"},
    },
    {
        "key": "risk-center.daily-report-history",
        "label": "查询历史日报",
        "endpoint": "/api/risk-center/daily-report/",
        "method": "GET",
        "intent": "query_risk_and_position_daily_report_history",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "datagrid",
        "description": "按账户、单日或日期区间查询已归档的风控日报和持仓日报。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 175,
        "task_tier": "primary",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "留空则查询有权限账户",
                "binding": "query",
                "value_type": "integer",
            },
            {
                "key": "report_date",
                "label": "报告日期",
                "input_type": "date",
                "required": False,
                "default": "",
                "placeholder": "YYYY-MM-DD",
                "binding": "query",
                "value_type": "date",
            },
            {
                "key": "start_date",
                "label": "开始日期",
                "input_type": "date",
                "required": False,
                "default": "",
                "placeholder": "YYYY-MM-DD",
                "binding": "query",
                "value_type": "date",
            },
            {
                "key": "end_date",
                "label": "结束日期",
                "input_type": "date",
                "required": False,
                "default": "",
                "placeholder": "YYYY-MM-DD",
                "binding": "query",
                "value_type": "date",
            },
            {
                "key": "limit",
                "label": "返回数量",
                "input_type": "number",
                "required": False,
                "default": "30",
                "placeholder": "30",
                "binding": "query",
                "value_type": "integer",
            },
        ],
        "view_model": {"kind": "datagrid", "rows_path": "data"},
    },
    {
        "key": "risk-center.update-floor",
        "label": "更新全局底线",
        "endpoint": "/api/risk-center/floor/",
        "method": "PUT",
        "intent": "update_global_risk_floor",
        "risk": "write",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "经过确认后更新全局风控底线。",
        "source": "approved:runtime-risk-center",
        "task_group": "02 风控写入",
        "sequence": 200,
        "task_tier": "advanced",
        "fields": [
            {
                "key": "max_total_position_pct",
                "label": "总仓位上限",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "0.8",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "max_single_position_pct",
                "label": "单标的上限",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "0.18",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "min_cash_pct",
                "label": "最低现金比例",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "0.15",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "reason",
                "label": "变更理由",
                "input_type": "text",
                "required": True,
                "default": "",
                "placeholder": "说明本次全局底线调整原因",
                "binding": "body",
                "value_type": "string",
            },
        ],
    },
    {
        "key": "risk-center.upsert-policy",
        "label": "保存账户策略",
        "endpoint": "/api/risk-center/account-policies/",
        "method": "POST",
        "intent": "upsert_account_risk_policy",
        "risk": "write",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "经过确认后创建或更新账户级风控策略。",
        "source": "approved:runtime-risk-center",
        "task_group": "02 风控写入",
        "sequence": 210,
        "task_tier": "primary",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "输入账户 ID",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "risk_profile",
                "label": "风险偏好",
                "input_type": "select",
                "required": False,
                "default": "moderate",
                "placeholder": "",
                "binding": "body",
                "value_type": "string",
                "options": ["conservative", "moderate", "aggressive", "custom"],
            },
            {
                "key": "max_total_position_pct",
                "label": "总仓位上限",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "0.75",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "max_single_position_pct",
                "label": "单标的上限",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "0.18",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "reason",
                "label": "变更理由",
                "input_type": "text",
                "required": False,
                "default": "TUI account risk policy update",
                "placeholder": "说明本次账户策略调整原因",
                "binding": "body",
                "value_type": "string",
            },
        ],
    },
    {
        "key": "risk-center.create-exception",
        "label": "创建风控例外",
        "endpoint": "/api/risk-center/exceptions/",
        "method": "POST",
        "intent": "create_risk_exception",
        "risk": "write",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "经过确认后创建有理由和过期时间的管理员风控例外。",
        "source": "approved:runtime-risk-center",
        "task_group": "02 风控写入",
        "sequence": 220,
        "task_tier": "advanced",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "可选",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "field_name",
                "label": "突破字段",
                "input_type": "select",
                "required": True,
                "default": "max_total_position_pct",
                "placeholder": "",
                "binding": "body",
                "value_type": "string",
                "options": ["max_total_position_pct", "max_single_position_pct", "min_cash_pct"],
            },
            {
                "key": "allowed_value",
                "label": "允许值",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "0.9",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "expires_at",
                "label": "过期时间",
                "input_type": "text",
                "required": True,
                "default": "",
                "placeholder": "2026-06-28T00:00:00Z",
                "binding": "body",
                "value_type": "datetime",
            },
            {
                "key": "reason",
                "label": "例外理由",
                "input_type": "textarea",
                "required": True,
                "default": "",
                "placeholder": "说明临时突破底线的业务原因",
                "binding": "body",
                "value_type": "string",
            },
        ],
    },
)

RUNTIME_RISK_CENTER_ACTIONS += (
    {
        "key": "risk-center.active-scenario-set",
        "label": "当前生效情景集",
        "endpoint": "/api/risk-center/stress-scenario-sets/active/",
        "method": "GET",
        "intent": "read_active_scenario_set",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "查看当前生效情景、主情景概率、最近修改、证据时间和阻断状态。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "00 情景总览",
        "sequence": 10,
        "task_tier": "primary",
        "fields": [
            {
                "key": "environment",
                "label": "运行环境",
                "input_type": "select",
                "required": True,
                "default": "production",
                "binding": "query",
                "value_type": "string",
                "options": ["production", "shadow"],
            },
            {
                "key": "purpose",
                "label": "用途",
                "input_type": "select",
                "required": True,
                "default": "portfolio_stress",
                "binding": "query",
                "value_type": "string",
                "options": ["portfolio_stress", "strategy_research"],
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.status"},
    },
    {
        "key": "risk-center.scenario-list",
        "label": "情景版本目录",
        "endpoint": "/api/risk-center/stress-scenarios/",
        "method": "GET",
        "intent": "list_governed_stress_scenarios",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "datagrid",
        "description": "查看可见情景定义、当前版本、类型、状态和证据更新时间。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "00 情景总览",
        "sequence": 20,
        "task_tier": "primary",
        "view_model": {"kind": "datagrid", "rows_path": "data"},
    },
    {
        "key": "risk-center.market-state",
        "label": "五维市场状态",
        "endpoint": "/api/risk-center/research/market-state/",
        "method": "GET",
        "intent": "read_five_dimension_market_state",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "聚合宏观、产业、盈利、资金和估值证据，并保留缺失与冲突。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "00 情景总览",
        "sequence": 30,
        "task_tier": "primary",
        "view_model": {"kind": "detail", "status_path": "data.must_not_use_for_decision"},
    },
    {
        "key": "risk-center.scenario-impact-preview",
        "label": "预览组合情景影响",
        "endpoint": "/api/risk-center/stress-scenario-sets/impact-preview/",
        "method": "POST",
        "intent": "preview_scenario_portfolio_impact",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "基于不可变组合快照预览各情景和概率加权影响，不执行交易。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "01 情景预览",
        "sequence": 40,
        "task_tier": "primary",
        "fields": [
            {
                "key": "scenario_set_revision_id",
                "label": "情景集版本",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "portfolio_snapshot_id",
                "label": "组合快照",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "allocation_policy_version",
                "label": "配置政策版本",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {
            "kind": "detail",
            "status_path": "data.must_not_use_for_decision",
        },
    },
    {
        "key": "risk-center.scenario-revision-preview",
        "label": "预览情景修订",
        "endpoint": "/api/risk-center/stress-scenarios/preview-revision/",
        "method": "POST",
        "intent": "preview_stress_scenario_revision",
        "risk": "read",
        "audience": "admin",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "先校验修订并查看版本差异、数据依赖和组合影响，全程不改变生效状态。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "01 情景预览",
        "sequence": 50,
        "task_tier": "primary",
        "fields": [
            {
                "key": "scenario_key",
                "label": "情景标识",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "scenario_type",
                "label": "情景类型",
                "input_type": "select",
                "required": True,
                "default": "historical_window",
                "binding": "body",
                "value_type": "string",
                "options": [
                    "historical_window",
                    "rolling_extreme",
                    "parametric_shock",
                    "macro_path",
                ],
            },
            {
                "key": "based_on_version",
                "label": "基于版本",
                "input_type": "number",
                "required": False,
                "default": "",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "invalidation_logic",
                "label": "证伪条件",
                "input_type": "textarea",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "review_date",
                "label": "下次复核日期",
                "input_type": "date",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "date",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.status"},
    },
    {
        "key": "risk-center.scenario-propose",
        "label": "提交情景修订提案",
        "endpoint": "/api/risk-center/stress-scenarios/propose-revision/",
        "method": "POST",
        "intent": "propose_stress_scenario_revision",
        "risk": "write",
        "effect": "create",
        "confirmation_required": True,
        "audit_required": True,
        "audience": "admin",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "确认后只创建不可变修订提案，不会自动激活生产情景。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "02 情景治理",
        "sequence": 60,
        "task_tier": "primary",
        "fields": [
            {
                "key": "preview_id",
                "label": "预览凭据",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "change_reason",
                "label": "修订理由",
                "input_type": "textarea",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "idempotency_key",
                "label": "操作流水号",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.status"},
    },
    {
        "key": "risk-center.scenario-activate",
        "label": "激活已批准情景版本",
        "endpoint": "/api/risk-center/stress-scenario-sets/activate/",
        "method": "POST",
        "intent": "activate_approved_stress_scenario_revision",
        "risk": "admin",
        "effect": "update",
        "confirmation_required": True,
        "audit_required": True,
        "audience": "admin",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "仅人类管理员可在持久审批通过后激活；AI 提案人不能自批。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "02 情景治理",
        "sequence": 70,
        "task_tier": "advanced",
        "fields": [
            {
                "key": "proposal_id",
                "label": "已批准提案",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "scenario_set_revision_id",
                "label": "待激活情景集版本",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "environment",
                "label": "运行环境",
                "input_type": "select",
                "required": True,
                "default": "production",
                "binding": "body",
                "value_type": "string",
                "options": ["production", "shadow"],
            },
            {
                "key": "purpose",
                "label": "使用目的",
                "input_type": "text",
                "required": True,
                "default": "portfolio_stress",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "preview_id",
                "label": "预览凭据",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "expected_active_version",
                "label": "当前版本",
                "input_type": "number",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "expected_active_hash",
                "label": "当前内容校验值",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "change_reason",
                "label": "激活理由",
                "input_type": "textarea",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "correlation_id",
                "label": "操作流水号",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "idempotency_key",
                "label": "操作流水号",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.status"},
    },
    {
        "key": "risk-center.scenario-proposal-approve",
        "label": "人工复核情景提案",
        "endpoint": "/api/risk-center/stress-scenario-proposals/{proposal_id}/approve/",
        "method": "POST",
        "intent": "approve_stress_scenario_proposal",
        "risk": "admin",
        "effect": "update",
        "confirmation_required": True,
        "audit_required": True,
        "audience": "admin",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "由非提案人的人类管理员复核证据后批准；批准本身不会自动激活。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "02 情景治理",
        "sequence": 75,
        "task_tier": "advanced",
        "fields": [
            {
                "key": "proposal_id",
                "label": "待复核提案",
                "input_type": "number",
                "required": True,
                "default": "",
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "reason",
                "label": "复核意见",
                "input_type": "textarea",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "correlation_id",
                "label": "操作流水号",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.status"},
    },
    {
        "key": "risk-center.scenario-rollback",
        "label": "回滚到已验证版本",
        "endpoint": "/api/risk-center/stress-scenario-sets/rollback/",
        "method": "POST",
        "intent": "rollback_approved_stress_scenario_revision",
        "risk": "admin",
        "effect": "update",
        "confirmation_required": True,
        "audit_required": True,
        "audience": "admin",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "复制旧内容为新版本并激活，历史版本保持不可变。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "02 情景治理",
        "sequence": 80,
        "task_tier": "advanced",
        "fields": [
            {
                "key": "proposal_id",
                "label": "已批准提案",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "target_version",
                "label": "目标历史版本",
                "input_type": "number",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "scenario_key",
                "label": "情景集标识",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "environment",
                "label": "运行环境",
                "input_type": "select",
                "required": True,
                "default": "production",
                "binding": "body",
                "value_type": "string",
                "options": ["production", "shadow"],
            },
            {
                "key": "purpose",
                "label": "使用目的",
                "input_type": "text",
                "required": True,
                "default": "portfolio_stress",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "preview_id",
                "label": "预览凭据",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "expected_active_version",
                "label": "当前版本",
                "input_type": "number",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "expected_active_hash",
                "label": "当前内容校验值",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "change_reason",
                "label": "回滚理由",
                "input_type": "textarea",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "correlation_id",
                "label": "操作流水号",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "idempotency_key",
                "label": "操作流水号",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.status"},
    },
)
