"""Runtime TUI metadata injections for unified operator home and governance flow."""

from __future__ import annotations

from typing import Any

RUNTIME_OPERATOR_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "operator.home.continue_decision_flow",
        "label": "继续今日决策流程",
        "method": "GET",
        "endpoint": "/api/tui/operator/home/",
        "intent": "open_daily_decision_lane_from_home",
        "screen_key": "command-center.overview",
        "module_key": "command-center",
        "view_type": "detail",
        "risk": "read",
        "fields": [],
        "description": "从统一首页继续进入每日投研 workflow。",
        "source": "approved:runtime-operator-home",
        "task_group": "00 首页主动作",
        "sequence": 10,
        "task_tier": "primary",
    },
    {
        "key": "operator.home.enter_governance_flow",
        "label": "进入系统治理流",
        "method": "GET",
        "endpoint": "/api/tui/operator/home/",
        "intent": "open_governance_lane_from_home",
        "screen_key": "command-center.overview",
        "module_key": "command-center",
        "view_type": "detail",
        "risk": "read",
        "fields": [],
        "description": "从统一首页进入系统治理 workflow。",
        "source": "approved:runtime-operator-home",
        "task_group": "00 首页主动作",
        "sequence": 11,
        "task_tier": "primary",
    },
    {
        "key": "operator.home.resume_last_workspace",
        "label": "恢复上次工作区",
        "method": "GET",
        "endpoint": "/api/tui/operator/home/",
        "intent": "resume_last_non_home_workspace",
        "screen_key": "command-center.overview",
        "module_key": "command-center",
        "view_type": "detail",
        "risk": "read",
        "fields": [],
        "description": "恢复最近一次非首页工作区。",
        "source": "approved:runtime-operator-home",
        "task_group": "00 首页主动作",
        "sequence": 12,
        "task_tier": "support",
    },
    {
        "key": "operator.home.open_cli",
        "label": "打开 CLI",
        "method": "GET",
        "endpoint": "/api/tui/operator/home/",
        "intent": "open_parallel_cli_surface",
        "screen_key": "command-center.overview",
        "module_key": "command-center",
        "view_type": "detail",
        "risk": "read",
        "fields": [],
        "description": "在独立入口打开 CLI，不中断 TUI 主流程。",
        "source": "approved:runtime-operator-home",
        "task_group": "00 首页主动作",
        "sequence": 13,
        "task_tier": "support",
    },
    {
        "key": "operator.home.decision_queue",
        "label": "今日待办队列",
        "method": "GET",
        "endpoint": "/api/tui/operator/home/decision_queue/",
        "intent": "read_operator_home_decision_queue",
        "screen_key": "command-center.overview",
        "module_key": "command-center",
        "view_type": "datagrid",
        "risk": "read",
        "fields": [],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "rows",
            "total_path": "total",
        },
        "description": "读取统一首页的今日待办队列。",
        "source": "approved:runtime-operator-home",
        "task_group": "01 首页摘要",
        "sequence": 20,
        "task_tier": "support",
    },
    {
        "key": "operator.home.market_context",
        "label": "环境与脉搏摘要",
        "method": "GET",
        "endpoint": "/api/tui/operator/home/market_context/",
        "intent": "read_operator_home_market_context",
        "screen_key": "command-center.overview",
        "module_key": "command-center",
        "view_type": "datagrid",
        "risk": "read",
        "fields": [],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "rows",
            "total_path": "total",
        },
        "description": "读取统一首页的环境、Policy、Pulse 与数据就绪摘要。",
        "source": "approved:runtime-operator-home",
        "task_group": "01 首页摘要",
        "sequence": 21,
        "task_tier": "support",
    },
    {
        "key": "operator.home.account_signal_summary",
        "label": "账户与信号摘要",
        "method": "GET",
        "endpoint": "/api/tui/operator/home/account_signal_summary/",
        "intent": "read_operator_home_account_signal_summary",
        "screen_key": "command-center.overview",
        "module_key": "command-center",
        "view_type": "datagrid",
        "risk": "read",
        "fields": [],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "rows",
            "total_path": "total",
        },
        "description": "读取统一首页的账户与信号摘要。",
        "source": "approved:runtime-operator-home",
        "task_group": "01 首页摘要",
        "sequence": 22,
        "task_tier": "support",
    },
    {
        "key": "operator.home.system_exception_summary",
        "label": "系统异常总览",
        "method": "GET",
        "endpoint": "/api/tui/operator/home/system_exception_summary/",
        "intent": "read_operator_home_system_exception_summary",
        "screen_key": "command-center.overview",
        "module_key": "command-center",
        "view_type": "datagrid",
        "risk": "read",
        "fields": [],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "rows",
            "total_path": "total",
        },
        "description": "读取统一首页的系统治理异常摘要。",
        "source": "approved:runtime-operator-home",
        "task_group": "01 首页摘要",
        "sequence": 23,
        "task_tier": "support",
    },
    {
        "key": "operator.home.data_task_summary",
        "label": "数据与任务异常",
        "method": "GET",
        "endpoint": "/api/tui/operator/home/data_task_summary/",
        "intent": "read_operator_home_data_task_summary",
        "screen_key": "command-center.overview",
        "module_key": "command-center",
        "view_type": "datagrid",
        "risk": "read",
        "fields": [],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "rows",
            "total_path": "total",
        },
        "description": "读取统一首页的数据、任务与运行时异常摘要。",
        "source": "approved:runtime-operator-home",
        "task_group": "01 首页摘要",
        "sequence": 24,
        "task_tier": "support",
    },
    {
        "key": "operator.home.ai_config_summary",
        "label": "AI / 配置异常",
        "method": "GET",
        "endpoint": "/api/tui/operator/home/ai_config_summary/",
        "intent": "read_operator_home_ai_config_summary",
        "screen_key": "command-center.overview",
        "module_key": "command-center",
        "view_type": "datagrid",
        "risk": "read",
        "fields": [],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "rows",
            "total_path": "total",
        },
        "description": "读取统一首页的 AI、MCP 与关键配置异常摘要。",
        "source": "approved:runtime-operator-home",
        "task_group": "01 首页摘要",
        "sequence": 25,
        "task_tier": "support",
    },
    {
        "key": "operator.governance.runtime_summary",
        "label": "运行时治理摘要",
        "method": "GET",
        "endpoint": "/api/tui/operator/governance-queue/",
        "intent": "read_runtime_governance_summary",
        "screen_key": "api-library.runtime",
        "module_key": "api-library",
        "view_type": "datagrid",
        "risk": "read",
        "fields": [
            {
                "key": "domain",
                "label": "治理域",
                "input_type": "hidden",
                "default": "runtime",
            }
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "items",
            "total_path": "total",
        },
        "description": "优先读取 runtime、readiness 与 operator surface 异常。",
        "source": "approved:runtime-governance",
        "task_group": "01 治理主线",
        "sequence": 10,
        "task_tier": "primary",
    },
    {
        "key": "operator.governance.data_center_summary",
        "label": "数据中心治理摘要",
        "method": "GET",
        "endpoint": "/api/tui/operator/governance-queue/",
        "intent": "read_data_center_governance_summary",
        "screen_key": "api-library.data-center",
        "module_key": "api-library",
        "view_type": "datagrid",
        "risk": "read",
        "fields": [
            {
                "key": "domain",
                "label": "治理域",
                "input_type": "hidden",
                "default": "data-center",
            }
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "items",
            "total_path": "total",
        },
        "description": "优先读取 freshness、服务商与 market thermometer 异常。",
        "source": "approved:runtime-governance",
        "task_group": "01 治理主线",
        "sequence": 20,
        "task_tier": "primary",
    },
    {
        "key": "operator.governance.ai_provider_summary",
        "label": "AI 服务商治理摘要",
        "method": "GET",
        "endpoint": "/api/tui/operator/governance-queue/",
        "intent": "read_ai_provider_governance_summary",
        "screen_key": "ai-ops.providers",
        "module_key": "ai-ops",
        "view_type": "datagrid",
        "risk": "read",
        "fields": [
            {
                "key": "domain",
                "label": "治理域",
                "input_type": "hidden",
                "default": "ai-provider",
            }
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "items",
            "total_path": "total",
        },
        "description": "优先读取服务商可用性、失败日志与 quota 异常。",
        "source": "approved:runtime-governance",
        "task_group": "01 治理主线",
        "sequence": 30,
        "task_tier": "primary",
    },
    {
        "key": "operator.governance.agent_runtime_summary",
        "label": "Agent 运行时治理摘要",
        "method": "GET",
        "endpoint": "/api/tui/operator/governance-queue/",
        "intent": "read_agent_runtime_governance_summary",
        "screen_key": "ai-ops.agent-runtime",
        "module_key": "ai-ops",
        "view_type": "datagrid",
        "risk": "read",
        "fields": [
            {
                "key": "domain",
                "label": "治理域",
                "input_type": "hidden",
                "default": "agent-runtime",
            }
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "items",
            "total_path": "total",
        },
        "description": "优先读取待处理任务、失败任务与 runtime blockage。",
        "source": "approved:runtime-governance",
        "task_group": "01 治理主线",
        "sequence": 40,
        "task_tier": "primary",
    },
    {
        "key": "operator.governance.account_settings_summary",
        "label": "执行参数治理摘要",
        "method": "GET",
        "endpoint": "/api/tui/operator/governance-queue/",
        "intent": "read_account_settings_governance_summary",
        "screen_key": "execution.account-settings",
        "module_key": "execution",
        "view_type": "datagrid",
        "risk": "read",
        "fields": [
            {
                "key": "domain",
                "label": "治理域",
                "input_type": "hidden",
                "default": "account-settings",
            }
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "items",
            "total_path": "total",
        },
        "description": "优先读取会阻断执行的账户参数与前置配置异常。",
        "source": "approved:runtime-governance",
        "task_group": "01 治理主线",
        "sequence": 50,
        "task_tier": "primary",
    },
    {
        "key": "operator.governance.config_center_summary",
        "label": "配置中心治理摘要",
        "method": "GET",
        "endpoint": "/api/tui/operator/governance-queue/",
        "intent": "read_config_center_governance_summary",
        "screen_key": "api-library.config-center",
        "module_key": "api-library",
        "view_type": "datagrid",
        "risk": "admin",
        "fields": [
            {
                "key": "domain",
                "label": "治理域",
                "input_type": "hidden",
                "default": "config-center",
            }
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "items",
            "total_path": "total",
        },
        "description": "优先读取训练、runtime 与本地 Qlib 数据异常。",
        "source": "approved:runtime-governance",
        "task_group": "01 治理主线",
        "sequence": 60,
        "task_tier": "primary",
    },
)
