"""Runtime screen patches for macro, regime, and data-center TUI surfaces."""

from __future__ import annotations

from typing import Any


RUNTIME_SCREEN_PATCHES_MACRO_DATA: dict[str, dict[str, Any]] = {
    "macro-regime.beta-gate": {
        "default_action_key": "auto.api.get.api.beta-gate.decisions",
        "user_experience": {
            "journey": "dashboard",
            "primary_task": "先判断当前市场暴露是否被放行，再决定是否继续查看配置和标的池版本差异。",
            "primary_outcome": "明确最近放行结论、当前配置是否匹配风险画像，以及是否需要做版本复核。",
            "empty_state_hint": "先看最近闸门决策，再看配置版本和标的池快照。",
            "next_step_hint": "如果放行结论与预期不一致，继续比较配置版本并复核规则差异。",
        },
        "business_context": {
            "objective": "先看最近闸门决策，再核对配置、标的池和版本差异，判断当前市场暴露是否允许放行。",
            "decision_output": "Beta 闸门结论：放行、限制、禁止或需要版本复核。",
            "checkpoints": [
                "先看最近决策，确认哪些标的被放行、限制或拦截。",
                "再看配置和标的池，确认当前约束是否符合目标风险画像。",
                "需要核对规则变动时再进入版本对比，不直接执行。",
            ],
        },
        "dashboard_panels": [
            {
                "key": "beta-gate-decisions",
                "title": "一、最近闸门决策",
                "kind": "datagrid",
                "action_key": "auto.api.get.api.beta-gate.decisions",
                "max_rows": 8,
                "layout_area": "decisions",
                "target_screen": "macro-regime.beta-gate",
                "user_priority": "p0",
                "presentation_semantic": "primary_list",
                "columns": [
                    {"key": "asset_code", "label": "标的"},
                    {"key": "status", "label": "结论"},
                    {"key": "current_regime", "label": "环境"},
                    {"key": "policy_level", "label": "政策档位"},
                    {"key": "evaluated_at", "label": "评估时间"},
                ],
            },
            {
                "key": "beta-gate-configs",
                "title": "二、当前配置版本",
                "kind": "datagrid",
                "action_key": "auto.api.get.api.beta-gate.configs",
                "max_rows": 6,
                "layout_area": "configs",
                "target_screen": "macro-regime.beta-gate",
                "user_priority": "p1",
                "presentation_semantic": "supporting_list",
                "columns": [
                    {"key": "config_id", "label": "配置ID"},
                    {"key": "risk_profile", "label": "风险画像"},
                    {"key": "version", "label": "版本"},
                    {"key": "is_active", "label": "启用"},
                    {"key": "effective_date", "label": "生效日期"},
                ],
            },
            {
                "key": "beta-gate-universe",
                "title": "三、最近标的池快照",
                "kind": "datagrid",
                "action_key": "auto.api.get.api.beta-gate.universe",
                "max_rows": 6,
                "layout_area": "universe",
                "target_screen": "macro-regime.beta-gate",
                "user_priority": "p2",
                "presentation_semantic": "supporting_list",
                "columns": [
                    {"key": "snapshot_id", "label": "快照ID"},
                    {"key": "current_regime", "label": "环境"},
                    {"key": "policy_level", "label": "政策档位"},
                    {"key": "risk_profile", "label": "风险画像"},
                    {"key": "created_at", "label": "生成时间"},
                ],
            },
            {
                "key": "beta-gate-version-compare",
                "title": "四、最近配置版本",
                "kind": "datagrid",
                "action_key": "auto.api.get.api.beta-gate.version.compare",
                "max_rows": 6,
                "layout_area": "versions",
                "target_screen": "macro-regime.beta-gate",
                "user_priority": "p2",
                "presentation_semantic": "supporting_list",
                "columns": [
                    {"key": "config_id", "label": "配置ID"},
                    {"key": "risk_profile", "label": "风险画像"},
                    {"key": "version", "label": "版本"},
                    {"key": "is_active", "label": "启用"},
                    {"key": "created_at", "label": "创建时间"},
                ],
            },
        ],
    },
    "api-library.data-center": {
        "default_action_key": "operator.governance.data_center_summary",
        "user_experience": {
            "journey": "dashboard",
            "primary_task": "先确认 freshness、来源链路和温度异常，再决定是否继续进入目录或同步动作。",
            "primary_outcome": "明确当前数据中心是否存在 freshness 缺口、服务商异常或覆盖不足。",
            "empty_state_hint": "先看治理摘要，再看服务商列表和指标目录。",
            "next_step_hint": "如果存在 freshness 或来源异常，继续进入对应目录或同步动作排查。",
        },
        "workflow": {
            "name": "系统治理流程",
            "lane": "governance",
            "step": 2,
            "total": 6,
            "label": "数据治理",
            "role": "先看 freshness、覆盖和服务商异常，再继续下钻具体目录。",
            "previous": {"key": "api-library.runtime", "label": "运行时治理"},
            "next": {"key": "ai-ops.providers", "label": "AI 服务商治理"},
        },
        "business_context": {
            "objective": "先看 freshness、服务商和市场温度异常，再决定是否进入指标目录或同步动作。",
            "decision_output": "数据中心治理结论：是否存在 freshness 缺口、覆盖不足、服务商异常或需补同步。",
            "checkpoints": [
                "先看治理摘要，确认当前阻断是否来自 freshness、覆盖或温度计。",
                "再看服务商列表和发布机构，确认来源链路是否可用。",
                "最后再进入指标目录或具体查询，不从目录浏览开始。",
            ],
        },
        "dashboard_panels": [
            {
                "key": "data-center-governance-summary",
                "title": "一、Freshness / 服务商 / 温度异常",
                "kind": "datagrid",
                "action_key": "operator.governance.data_center_summary",
                "max_rows": 8,
                "layout_area": "governance_summary",
                "target_screen": "api-library.data-center",
                "user_priority": "p0",
                "presentation_semantic": "primary_list",
                "columns": [
                    {"key": "severity", "label": "级别"},
                    {"key": "title", "label": "异常项"},
                    {"key": "status", "label": "状态"},
                    {"key": "blocking_reason", "label": "原因"},
                    {"key": "next_action", "label": "下一步"},
                ],
            },
            {
                "key": "data-center-providers",
                "title": "二、服务商列表",
                "kind": "datagrid",
                "action_key": "auto.api.get.api.data-center.providers",
                "max_rows": 6,
                "layout_area": "providers",
                "target_screen": "api-library.data-center",
                "user_priority": "p1",
                "presentation_semantic": "supporting_list",
            },
            {
                "key": "data-center-indicators",
                "title": "三、指标目录",
                "kind": "datagrid",
                "action_key": "auto.api.get.api.data-center.indicators",
                "max_rows": 8,
                "layout_area": "indicators",
                "target_screen": "api-library.data-center",
                "user_priority": "p1",
                "presentation_semantic": "supporting_list",
            },
        ],
    },
    "macro-regime.hedge": {
        "default_action_key": "auto.api.get.api.hedge.snapshots",
        "user_experience": {
            "journey": "dashboard",
            "primary_task": "先判断当前是否存在需要处理的对冲变化或主动预警，再决定是否继续看有效性。",
            "primary_outcome": "明确最新对冲快照、当前预警状态，以及是否需要继续复核对冲有效性。",
            "empty_state_hint": "先看最新对冲快照和当前预警，再查看对冲有效性。",
            "next_step_hint": "若快照或预警显示风险上升，继续进入有效性和相关性检查。",
        },
        "dashboard_panels": [
            {
                "key": "hedge-latest-snapshots",
                "title": "一、最新对冲快照",
                "kind": "datagrid",
                "action_key": "auto.api.get.api.hedge.snapshots.latest",
                "max_rows": 8,
                "layout_area": "snapshots",
                "target_screen": "macro-regime.hedge",
                "user_priority": "p0",
                "presentation_semantic": "primary_list",
            },
            {
                "key": "hedge-active-alerts",
                "title": "二、当前对冲预警",
                "kind": "datagrid",
                "action_key": "auto.api.get.api.hedge.alerts.active",
                "max_rows": 6,
                "layout_area": "alerts",
                "target_screen": "macro-regime.hedge",
                "user_priority": "p1",
                "presentation_semantic": "supporting_list",
            },
            {
                "key": "hedge-effectiveness",
                "title": "三、对冲有效性",
                "kind": "datagrid",
                "action_key": "auto.api.get.api.hedge.pairs.all_effectiveness",
                "max_rows": 6,
                "layout_area": "effectiveness",
                "target_screen": "macro-regime.hedge",
                "user_priority": "p2",
                "presentation_semantic": "supporting_list",
            },
        ],
    },
    "macro-regime.pulse": {
        "default_action_key": "pulse.current",
        "user_experience": {
            "journey": "dashboard",
            "primary_task": "先确认当前脉搏指标是否出现转折，再决定是否继续查看历史变化。",
            "primary_outcome": "明确当前脉搏状态、是否有异常变化，以及是否需要用历史数据复核趋势。",
            "empty_state_hint": "先看当前脉搏指标，再进入历史观察变化方向。",
            "next_step_hint": "如果当前脉搏出现异常或转折，继续查看历史并回到环境行动建议。",
        },
        "dashboard_panels": [
            {
                "key": "pulse-current",
                "title": "一、当前脉搏指标",
                "kind": "datagrid",
                "action_key": "pulse.current",
                "max_rows": 8,
                "layout_area": "current",
                "target_screen": "macro-regime.pulse",
                "user_priority": "p0",
                "presentation_semantic": "primary_list",
            },
            {
                "key": "pulse-history",
                "title": "二、脉搏历史",
                "kind": "datagrid",
                "action_key": "pulse.history",
                "max_rows": 8,
                "layout_area": "history",
                "target_screen": "macro-regime.pulse",
                "user_priority": "p2",
                "presentation_semantic": "supporting_list",
            },
        ],
    },
}

RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_MACRO_DATA: dict[str, set[str]] = {
    "api-library.data-center": {"auto.api.get.api.data-center"},
    "macro-regime.beta-gate": {
        "auto.api.get.api.beta-gate",
        "auto.api.get.api.beta-gate.health",
    },
}
