"""Runtime TUI metadata for governed QMT live execution tasks."""

from __future__ import annotations

from typing import Any

RUNTIME_BROKER_EXECUTION_SCREENS: tuple[dict[str, Any], ...] = (
    {
        "key": "broker-execution.overview",
        "label": "实盘执行与账户",
        "module_key": "daily-decisions",
        "group": "daily",
        "summary": "判断今天能否安全实盘，并复核订单、连接和停止状态。",
        "view_type": "status",
        "default_action_key": "broker-execution.overview",
        "user_experience": {
            "journey": "dashboard",
            "primary_task": "先确认本地连接和实盘门禁，再处理待确认订单。",
            "primary_outcome": "得到可交易、需复核、已停止或离线的明确结论。",
            "empty_state_hint": "若本地连接为空，请先完成 Windows Agent 和账户绑定。",
            "next_step_hint": "连接正常后复核待确认订单；出现异常时先停止并对账。",
        },
        "dashboard_panels": [
            {
                "key": "broker-execution-readiness",
                "title": "实盘就绪结论",
                "kind": "detail",
                "action_key": "broker-execution.overview",
                "layout_area": "broker_readiness",
                "target_screen": "broker-execution.overview",
                "user_priority": "p0",
                "presentation_semantic": "primary_status",
            },
            {
                "key": "broker-execution-orders",
                "title": "待确认与执行中订单",
                "kind": "datagrid",
                "action_key": "broker-execution.order-list",
                "max_rows": 8,
                "layout_area": "broker_orders",
                "target_screen": "broker-execution.overview",
                "user_priority": "p0",
                "presentation_semantic": "primary_list",
            },
            {
                "key": "broker-execution-connections",
                "title": "本地连接",
                "kind": "datagrid",
                "action_key": "broker-execution.connection-status",
                "max_rows": 6,
                "layout_area": "broker_connections",
                "target_screen": "broker-execution.overview",
                "user_priority": "p1",
                "presentation_semantic": "supporting_list",
            },
        ],
    },
    {
        "key": "broker-execution.audit",
        "label": "实盘对账与审计",
        "module_key": "daily-decisions",
        "group": "daily",
        "summary": "处理委托、成交、资金和持仓差异，并核对实盘操作证据。",
        "view_type": "status",
        "default_action_key": "broker-execution.reconciliation-list",
        "user_experience": {
            "journey": "dashboard",
            "primary_task": "先处理未处置对账差异，再检查实盘操作审计。",
            "primary_outcome": "所有差异都有明确处置状态，关键操作可追溯。",
            "empty_state_hint": "尚无差异时继续查看最近实盘审计事件。",
            "next_step_hint": "未知订单不得补单，先接受券商事实或升级复核。",
        },
        "dashboard_panels": [
            {
                "key": "broker-execution-reconciliation",
                "title": "实盘对账差异",
                "kind": "datagrid",
                "action_key": "broker-execution.reconciliation-list",
                "max_rows": 8,
                "layout_area": "broker_reconciliation",
                "target_screen": "broker-execution.audit",
                "user_priority": "p0",
                "presentation_semantic": "primary_list",
            },
            {
                "key": "broker-execution-audit",
                "title": "实盘操作审计",
                "kind": "datagrid",
                "action_key": "broker-execution.audit-list",
                "max_rows": 8,
                "layout_area": "broker_audit",
                "target_screen": "broker-execution.audit",
                "user_priority": "p1",
                "presentation_semantic": "supporting_list",
            },
        ],
    },
)


_ORDER_ID_FIELD = {
    "key": "client_order_id",
    "label": "订单编号",
    "input_type": "text",
    "required": True,
    "default": "",
    "placeholder": "从订单列表选择",
    "binding": "path",
    "value_type": "string",
}
_REASON_FIELD = {
    "key": "reason",
    "label": "操作原因",
    "input_type": "textarea",
    "required": True,
    "default": "",
    "placeholder": "说明复核结论或处置原因",
    "binding": "body",
    "value_type": "string",
}


def _order_action(
    key: str, label: str, action: str, *, preview: bool, sequence: int
) -> dict[str, Any]:
    return {
        "key": key,
        "label": label,
        "endpoint": f"/api/broker-execution/orders/<uuid:client_order_id>/{action}/",
        "method": "POST",
        "intent": key.replace("-", "_"),
        "risk": "write" if not preview else "read",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": f"{'预览' if preview else '确认'}{label}，并保留权限与审计证据。",
        "source": "approved:runtime-broker-execution",
        "task_group": "02 实盘订单处置",
        "task_tier": "primary",
        "sequence": sequence,
        "confirmation_required": not preview,
        "audit_required": not preview,
        "fields": [
            dict(_ORDER_ID_FIELD),
            dict(_REASON_FIELD),
            {
                "key": "preview_only",
                "label": "仅预览",
                "input_type": "hidden",
                "required": True,
                "default": preview,
                "binding": "body",
                "value_type": "boolean",
            },
            *(
                []
                if preview
                else [
                    {
                        "key": "expected_version",
                        "label": "预览中的订单版本",
                        "input_type": "number",
                        "required": True,
                        "default": 0,
                        "placeholder": "填写刚才预览返回的版本",
                        "binding": "body",
                        "value_type": "integer",
                    },
                    {
                        "key": "idempotency_key",
                        "label": "请求幂等键",
                        "input_type": "text",
                        "required": True,
                        "default": "",
                        "placeholder": "每次确认使用唯一值",
                        "binding": "body",
                        "value_type": "string",
                    }
                ]
            ),
        ],
    }


RUNTIME_BROKER_EXECUTION_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "broker-execution.overview",
        "label": "实盘就绪总览",
        "endpoint": "/api/broker-execution/",
        "method": "GET",
        "intent": "read_live_execution_readiness",
        "risk": "read",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "读取持久化的连接、停止开关、待确认订单和对账结论。",
        "source": "approved:runtime-broker-execution",
        "task_group": "01 实盘状态",
        "task_tier": "primary",
        "sequence": 100,
        "view_model": {"kind": "detail", "status_path": "data.today_readiness"},
    },
    {
        "key": "broker-execution.order-list",
        "label": "实盘订单",
        "endpoint": "/api/broker-execution/orders/",
        "method": "GET",
        "intent": "list_live_orders",
        "risk": "read",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "datagrid",
        "description": "列出当前身份有权查看的实盘订单。",
        "source": "approved:runtime-broker-execution",
        "task_group": "01 实盘状态",
        "task_tier": "primary",
        "sequence": 110,
        "view_model": {"kind": "datagrid", "rows_path": "data.orders"},
    },
    {
        "key": "broker-execution.order-detail",
        "label": "实盘订单详情",
        "endpoint": "/api/broker-execution/orders/<uuid:client_order_id>/",
        "method": "GET",
        "intent": "read_live_order_evidence",
        "risk": "read",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "查看订单风险快照、审批摘要、券商事件和成交。",
        "source": "approved:runtime-broker-execution",
        "task_group": "01 实盘状态",
        "task_tier": "primary",
        "sequence": 120,
        "fields": [dict(_ORDER_ID_FIELD)],
        "view_model": {"kind": "detail", "title_path": "data.asset_code", "status_path": "data.status"},
    },
    {
        "key": "broker-execution.connection-status",
        "label": "本地连接状态",
        "endpoint": "/api/broker-execution/connections/",
        "method": "GET",
        "intent": "read_qmt_connection_status",
        "risk": "read",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "datagrid",
        "description": "读取 Agent、QMT 和绑定账户最近一次持久化健康状态。",
        "source": "approved:runtime-broker-execution",
        "task_group": "01 实盘状态",
        "task_tier": "support",
        "sequence": 130,
        "view_model": {"kind": "datagrid", "rows_path": "data.connections"},
    },
    _order_action("broker-execution.approval-preview", "批准订单", "approve", preview=True, sequence=200),
    _order_action("broker-execution.approve-order", "批准订单", "approve", preview=False, sequence=210),
    _order_action("broker-execution.reject-preview", "拒绝订单", "reject", preview=True, sequence=220),
    _order_action("broker-execution.reject-order", "拒绝订单", "reject", preview=False, sequence=230),
    _order_action("broker-execution.cancel-preview", "请求撤单", "cancel", preview=True, sequence=240),
    _order_action("broker-execution.request-cancel", "请求撤单", "cancel", preview=False, sequence=250),
    {
        "key": "broker-execution.reconciliation-list",
        "label": "实盘对账批次",
        "endpoint": "/api/broker-execution/reconciliations/",
        "method": "GET",
        "intent": "list_live_reconciliation_runs",
        "risk": "read",
        "screen_key": "broker-execution.audit",
        "module_key": "daily-decisions",
        "view_type": "datagrid",
        "description": "列出委托、成交、资金和持仓差异批次。",
        "source": "approved:runtime-broker-execution",
        "task_group": "03 对账与审计",
        "task_tier": "primary",
        "sequence": 300,
        "view_model": {"kind": "datagrid", "rows_path": "data.runs"},
    },
    {
        "key": "broker-execution.audit-list",
        "label": "实盘操作审计",
        "endpoint": "/api/broker-execution/audit/",
        "method": "GET",
        "intent": "list_live_execution_audit",
        "risk": "read",
        "screen_key": "broker-execution.audit",
        "module_key": "daily-decisions",
        "view_type": "datagrid",
        "description": "查看批准、撤单、启停、凭证和差异处置证据。",
        "source": "approved:runtime-broker-execution",
        "task_group": "03 对账与审计",
        "task_tier": "support",
        "sequence": 310,
        "view_model": {"kind": "datagrid", "rows_path": "data.events"},
    },
    {
        "key": "broker-execution.resolve-reconciliation-preview",
        "label": "预览对账处置",
        "endpoint": "/api/broker-execution/reconciliations/<int:run_id>/resolve/",
        "method": "POST",
        "intent": "preview_live_reconciliation_resolution",
        "risk": "read",
        "screen_key": "broker-execution.audit",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "预览委托、成交、资金和持仓差异的处置结果。",
        "source": "approved:runtime-broker-execution",
        "task_group": "03 对账与审计",
        "task_tier": "primary",
        "sequence": 320,
        "fields": [
            {"key": "run_id", "label": "对账批次", "input_type": "number", "required": True, "default": 0, "placeholder": "从对账列表选择", "binding": "path", "value_type": "integer"},
            {"key": "resolution", "label": "处置方式", "input_type": "select", "required": True, "default": "verified_no_change", "binding": "body", "value_type": "string", "options": ["accept_broker_fact", "manual_adjustment", "verified_no_change", "escalate"]},
            dict(_REASON_FIELD),
            {"key": "preview_only", "label": "仅预览", "input_type": "hidden", "required": True, "default": True, "binding": "body", "value_type": "boolean"},
        ],
    },
    {
        "key": "broker-execution.resolve-reconciliation",
        "label": "确认对账处置",
        "endpoint": "/api/broker-execution/reconciliations/<int:run_id>/resolve/",
        "method": "POST",
        "intent": "resolve_live_reconciliation",
        "risk": "write",
        "screen_key": "broker-execution.audit",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "确认差异处置并保留幂等、权限和审计证据。",
        "source": "approved:runtime-broker-execution",
        "task_group": "03 对账与审计",
        "task_tier": "primary",
        "sequence": 330,
        "confirmation_required": True,
        "audit_required": True,
        "fields": [
            {"key": "run_id", "label": "对账批次", "input_type": "number", "required": True, "default": 0, "placeholder": "从对账列表选择", "binding": "path", "value_type": "integer"},
            {"key": "resolution", "label": "处置方式", "input_type": "select", "required": True, "default": "verified_no_change", "binding": "body", "value_type": "string", "options": ["accept_broker_fact", "manual_adjustment", "verified_no_change", "escalate"]},
            dict(_REASON_FIELD),
            {"key": "preview_only", "label": "仅预览", "input_type": "hidden", "required": True, "default": False, "binding": "body", "value_type": "boolean"},
            {"key": "idempotency_key", "label": "请求幂等键", "input_type": "text", "required": True, "default": "", "placeholder": "每次确认使用唯一值", "binding": "body", "value_type": "string"},
        ],
    },
    {
        "key": "broker-execution.kill-switch-preview",
        "label": "预览紧急停止",
        "endpoint": "/api/broker-execution/kill-switch/",
        "method": "POST",
        "intent": "preview_live_trading_stop",
        "risk": "read",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "预览停止范围和当前实盘状态，不产生状态变化。",
        "source": "approved:runtime-broker-execution",
        "task_group": "04 紧急控制",
        "task_tier": "primary",
        "sequence": 400,
        "fields": [
            {"key": "account_id", "label": "账户范围", "input_type": "number", "required": True, "default": 0, "placeholder": "0 表示全部可管理账户", "binding": "body", "value_type": "integer"},
            dict(_REASON_FIELD),
            {"key": "active", "label": "触发停止", "input_type": "hidden", "required": True, "default": True, "binding": "body", "value_type": "boolean"},
            {"key": "preview_only", "label": "仅预览", "input_type": "hidden", "required": True, "default": True, "binding": "body", "value_type": "boolean"},
        ],
    },
    {
        "key": "broker-execution.trigger-kill-switch",
        "label": "确认紧急停止",
        "endpoint": "/api/broker-execution/kill-switch/",
        "method": "POST",
        "intent": "trigger_live_trading_stop",
        "risk": "write",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "确认后停止新订单领取和提交，撤单与对账仍可继续。",
        "source": "approved:runtime-broker-execution",
        "task_group": "04 紧急控制",
        "task_tier": "primary",
        "sequence": 410,
        "confirmation_required": True,
        "audit_required": True,
        "fields": [
            {"key": "account_id", "label": "账户范围", "input_type": "number", "required": True, "default": 0, "placeholder": "0 表示全部可管理账户", "binding": "body", "value_type": "integer"},
            dict(_REASON_FIELD),
            {"key": "active", "label": "触发停止", "input_type": "hidden", "required": True, "default": True, "binding": "body", "value_type": "boolean"},
            {"key": "preview_only", "label": "仅预览", "input_type": "hidden", "required": True, "default": False, "binding": "body", "value_type": "boolean"},
            {"key": "idempotency_key", "label": "请求幂等键", "input_type": "text", "required": True, "default": "", "placeholder": "每次确认使用唯一值", "binding": "body", "value_type": "string"},
        ],
    },
    {
        "key": "broker-execution.resume-preview",
        "label": "预览恢复实盘",
        "endpoint": "/api/broker-execution/kill-switch/",
        "method": "POST",
        "intent": "preview_live_trading_resume",
        "risk": "read",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "复核连接、执行异常和对账差异是否允许恢复。",
        "source": "approved:runtime-broker-execution",
        "task_group": "04 紧急控制",
        "task_tier": "primary",
        "sequence": 420,
        "fields": [
            {"key": "account_id", "label": "账户范围", "input_type": "number", "required": True, "default": 0, "placeholder": "0 表示全部可管理账户", "binding": "body", "value_type": "integer"},
            dict(_REASON_FIELD),
            {"key": "active", "label": "恢复实盘", "input_type": "hidden", "required": True, "default": False, "binding": "body", "value_type": "boolean"},
            {"key": "preview_only", "label": "仅预览", "input_type": "hidden", "required": True, "default": True, "binding": "body", "value_type": "boolean"},
        ],
    },
    {
        "key": "broker-execution.resume-trading",
        "label": "确认恢复实盘",
        "endpoint": "/api/broker-execution/kill-switch/",
        "method": "POST",
        "intent": "resume_live_trading",
        "risk": "write",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "仅管理员在所有阻断项清除后确认恢复，并写入审计。",
        "source": "approved:runtime-broker-execution",
        "task_group": "04 紧急控制",
        "task_tier": "primary",
        "sequence": 430,
        "confirmation_required": True,
        "requires_password": True,
        "audit_required": True,
        "fields": [
            {"key": "account_id", "label": "账户范围", "input_type": "number", "required": True, "default": 0, "placeholder": "0 表示全部可管理账户", "binding": "body", "value_type": "integer"},
            dict(_REASON_FIELD),
            {"key": "active", "label": "恢复实盘", "input_type": "hidden", "required": True, "default": False, "binding": "body", "value_type": "boolean"},
            {"key": "preview_only", "label": "仅预览", "input_type": "hidden", "required": True, "default": False, "binding": "body", "value_type": "boolean"},
            {"key": "idempotency_key", "label": "请求幂等键", "input_type": "text", "required": True, "default": "", "placeholder": "每次确认使用唯一值", "binding": "body", "value_type": "string"},
        ],
    },
)
