"""Runtime TUI metadata injections for AI/MCP identity and access workflows."""

from __future__ import annotations

from typing import Any

from .tui_metadata_runtime_injection_ai_quotas import RUNTIME_AI_QUOTA_ACTIONS

RUNTIME_AI_OPS_MODULE: dict[str, Any] = {
    "key": "ai-ops",
    "label": "AI 助手",
    "group": "ops",
    "summary": "查看 AI 服务商、提示词模板、智能任务运行时与相关治理任务。",
}

RUNTIME_MCP_SELF_SERVICE_SCREEN: dict[str, Any] = {
    "key": "capability-router.self-service",
    "label": "我的 MCP 接入",
    "module_key": "capability-router",
    "group": "ops",
    "summary": "管理自己的 MCP 接入令牌、读写级别，以及一键复制给 AI 代理的接入提示词。",
    "view_type": "detail",
    "default_action_key": "capability-router.mcp-self-status",
    "user_experience": {
        "journey": "self_service",
        "primary_task": "在一个屏内完成 MCP 状态确认、令牌管理、连接地址复制和代理接入提示词获取。",
        "primary_outcome": "拿到完整可复制的接入令牌、路由地址、能力目录和接入提示词，并明确下一步是否创建或撤销令牌。",
        "empty_state_hint": "先读取我的 MCP 状态；如果未开通，回到上一屏完成接入，再返回这里生成或管理令牌。",
        "next_step_hint": "完成复制后，把接入提示词和路由地址粘贴给外部代理；旧令牌不再使用时立即撤销。",
    },
    "workflow": {
        "name": "能力接入流程",
        "step": 2,
        "total": 3,
        "label": "个人接入",
        "role": "先确认自己是否已开通 MCP，再生成令牌并复制代理接入提示词。",
        "previous": {"key": "capability-router.gateway", "label": "能力路由接入"},
        "next": {},
    },
    "business_context": {
        "objective": "在 TUI 内完成个人 MCP 接入，不再依赖网页表单。",
        "decision_output": "当前权限状态、可用令牌、推荐接入提示词，以及是否需要新建或撤销令牌。",
        "checkpoints": [
            "先读个人 MCP 状态，确认 mcp_enabled、默认账户和可复制提示词。",
            "需要新令牌时明确读写级别，再执行创建。",
            "旧令牌不再使用时立即撤销，避免凭证扩散。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "mcp-self-status",
            "title": "一、我的 MCP 状态",
            "kind": "detail",
            "action_key": "capability-router.mcp-self-status",
            "max_rows": 8,
            "layout_area": "summary",
            "target_screen": "capability-router.self-service",
            "note": "这里直接显示当前令牌、默认账户和基础连接地址。",
            "user_priority": "p0",
            "presentation_semantic": "copyable_secret",
        },
        {
            "key": "mcp-self-endpoints",
            "title": "二、接入地址",
            "kind": "detail",
            "action_key": "capability-router.mcp-self-endpoints",
            "max_rows": 6,
            "layout_area": "endpoints",
            "target_screen": "capability-router.self-service",
            "note": "代理优先接路由地址；网页对话和目录地址只用于兼容或排障。",
            "user_priority": "p0",
            "presentation_semantic": "endpoint_list",
        },
        {
            "key": "mcp-self-prompt-guide",
            "title": "三、接入提示词",
            "kind": "detail",
            "action_key": "capability-router.mcp-self-prompt-guide",
            "max_rows": 5,
            "layout_area": "prompt",
            "target_screen": "capability-router.self-service",
            "note": "完整提示词可在本屏执行“读取我的 MCP 状态”后查看。",
            "user_priority": "p1",
            "presentation_semantic": "multiline_prompt",
        },
        {
            "key": "mcp-self-tokens",
            "title": "四、我的令牌",
            "kind": "datagrid",
            "action_key": "capability-router.list-my-mcp-tokens",
            "max_rows": 8,
            "layout_area": "tokens",
            "target_screen": "capability-router.self-service",
            "columns": [
                {"key": "name", "label": "名称"},
                {"key": "display_token", "label": "令牌"},
                {"key": "access_level_label", "label": "级别"},
                {"key": "last_used_at", "label": "最后使用"},
            ],
            "user_priority": "p2",
            "presentation_semantic": "supporting_list",
        },
    ],
}

RUNTIME_MCP_ADMIN_ACCESS_SCREEN: dict[str, Any] = {
    "key": "capability-router.admin-access",
    "label": "MCP 用户治理",
    "module_key": "capability-router",
    "group": "ops",
    "summary": "管理员在 TUI 内管理用户 MCP 开关、令牌发放与撤销。",
    "view_type": "detail",
    "default_action_key": "capability-router.mcp-admin-users",
    "user_experience": {
        "journey": "admin",
        "primary_task": "筛出需要开通、收紧或回收凭证的用户，并在同屏完成 MCP 用户治理。",
        "primary_outcome": "明确哪些用户缺令牌、哪些凭证仍在使用、哪些用户的读写权限需要调整。",
        "empty_state_hint": "先读取用户与令牌分布，再按“仅无令牌”“仅已启用”等筛选条件定位目标用户。",
        "next_step_hint": "确认用户状态后再执行发放、开关或撤销操作，并复核令牌是否已收紧。",
    },
    "workflow": {
        "name": "能力接入流程",
        "step": 3,
        "total": 3,
        "label": "管理员治理",
        "role": "先筛用户，再发令牌、控读写权限并回收凭证。",
        "previous": {"key": "capability-router.mcp-center", "label": "MCP 接入中心"},
        "next": {},
    },
    "business_context": {
        "objective": "让管理员在 TUI 内闭环管理普通用户与管理员自己的 MCP 凭证策略。",
        "decision_output": "哪些用户未开通 MCP、哪些令牌仍在使用、哪些读写凭证需要收紧。",
        "checkpoints": [
            "先看用户列表和“仅无令牌”筛选，定位待发放用户。",
            "发放令牌时明确访问级别，不默认给读写。",
            "关闭用户 MCP 时同步回收其有效令牌。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "mcp-admin-users",
            "title": "一、用户与令牌分布",
            "kind": "datagrid",
            "action_key": "capability-router.mcp-admin-users",
            "max_rows": 10,
            "layout_area": "users",
            "target_screen": "capability-router.admin-access",
            "columns": [
                {"key": "username", "label": "用户"},
                {"key": "rbac_role", "label": "角色"},
                {"key": "mcp_enabled", "label": "MCP"},
                {"key": "token_count", "label": "令牌数"},
                {"key": "read_only_token_count", "label": "只读数"},
            ],
            "user_priority": "p0",
            "presentation_semantic": "primary_list",
        }
    ],
}

RUNTIME_AI_MY_PROVIDERS_SCREEN: dict[str, Any] = {
    "key": "ai-ops.my-providers",
    "label": "我的 AI 服务商",
    "module_key": "ai-ops",
    "group": "ops",
    "summary": "管理个人 AI 服务商、查看自己的兜底配额和调用日志。",
    "view_type": "detail",
    "default_action_key": "ai-ops.list-my-providers",
    "user_experience": {
        "journey": "dashboard",
        "primary_task": "先确认个人 AI 服务商是否可用，再决定是否调整额度、密钥或排查最近调用日志。",
        "primary_outcome": "明确当前个人服务商状态、剩余额度，以及是否需要更新配置或处理失败日志。",
        "empty_state_hint": "先看个人服务商列表，再查看额度状态和最近调用日志。",
        "next_step_hint": "若服务商不可用或额度不足，继续在本屏执行创建、更新或切换动作。",
    },
    "workflow": {
        "name": "AI 管理流程",
        "step": 1,
        "total": 3,
        "label": "个人服务商",
        "role": "先看个人服务商是否可用，再检查自己配额与最近调用日志。",
        "previous": {"key": "ai-ops.providers", "label": "AI 服务商与用量"},
        "next": {},
    },
    "business_context": {
        "objective": "普通用户在 TUI 内完成个人 AI 接入与自查。",
        "decision_output": "当前个人服务商列表、启用状态、剩余额度以及最近失败日志。",
        "checkpoints": [
            "先看个人服务商列表与启用状态。",
            "需要新增密钥时在 TUI 直接创建或更新个人服务商。",
            "调用异常时对照 quota 与 logs 定位是否是额度或上游故障。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "my-provider-list",
            "title": "一、我的服务商",
            "kind": "datagrid",
            "action_key": "ai-ops.list-my-providers",
            "max_rows": 8,
            "layout_area": "providers",
            "target_screen": "ai-ops.my-providers",
            "columns": [
                {"key": "name", "label": "名称"},
                {"key": "provider_type_label", "label": "类型"},
                {"key": "default_model", "label": "默认模型"},
                {"key": "is_active", "label": "启用"},
                {"key": "priority", "label": "优先级"},
            ],
            "user_priority": "p0",
            "presentation_semantic": "primary_list",
        },
        {
            "key": "my-provider-quota",
            "title": "二、我的兜底配额",
            "kind": "detail",
            "action_key": "ai-ops.my-quota-current",
            "layout_area": "quota",
            "target_screen": "ai-ops.my-providers",
            "user_priority": "p1",
            "presentation_semantic": "primary_status",
        },
        {
            "key": "my-provider-logs",
            "title": "三、最近调用日志",
            "kind": "datagrid",
            "action_key": "ai-ops.my-ai-logs",
            "max_rows": 8,
            "layout_area": "logs",
            "target_screen": "ai-ops.my-providers",
            "columns": [
                {"key": "provider_name", "label": "服务商"},
                {"key": "model", "label": "模型"},
                {"key": "status", "label": "状态"},
                {"key": "estimated_cost", "label": "成本"},
                {"key": "created_at", "label": "时间"},
            ],
            "user_priority": "p2",
            "presentation_semantic": "supporting_list",
        },
    ],
}

RUNTIME_AI_SYSTEM_PROVIDERS_SCREEN: dict[str, Any] = {
    "key": "ai-ops.system-providers",
    "label": "系统 AI 服务商",
    "module_key": "ai-ops",
    "group": "ops",
    "summary": "管理员在 TUI 内管理系统级 AI 服务商、连通性与使用统计。",
    "view_type": "detail",
    "default_action_key": "ai-ops.system-provider-overall-stats",
    "user_experience": {
        "journey": "admin",
        "primary_task": "先判断系统级 AI 服务商是否可支撑当前业务，再决定是否新增、切换或测试连通性。",
        "primary_outcome": "明确系统服务商总体可用性、启用状态，以及是否需要调整默认路由。",
        "empty_state_hint": "先看系统服务商概览，再查看系统服务商列表。",
        "next_step_hint": "若可用性不足或默认路由异常，继续在本屏执行创建、切换和连通性测试。",
    },
    "workflow": {
        "name": "AI 管理流程",
        "step": 2,
        "total": 3,
        "label": "系统服务商",
        "role": "先看系统服务商总体可用性，再处理创建、切换和连通性测试。",
        "previous": {"key": "ai-ops.my-providers", "label": "我的 AI 服务商"},
        "next": {"key": "ai-ops.user-quotas", "label": "用户 AI 配额"},
    },
    "business_context": {
        "objective": "把系统服务商的 CRUD、启停和测试能力拉进 TUI。",
        "decision_output": "系统服务商总量、启用状态、最近用量以及是否需要切换默认路由。",
        "checkpoints": [
            "先看整体统计，确认系统可用服务商数量。",
            "新增或修改时保持 base_url、api_mode 与默认模型一致。",
            "变更后立即跑 test-connection，不把未验证配置直接交给业务流量。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "system-provider-overall-stats",
            "title": "一、系统服务商概览",
            "kind": "detail",
            "action_key": "ai-ops.system-provider-overall-stats",
            "layout_area": "summary",
            "target_screen": "ai-ops.system-providers",
            "user_priority": "p0",
            "presentation_semantic": "primary_status",
        },
        {
            "key": "system-provider-list",
            "title": "二、系统服务商列表",
            "kind": "datagrid",
            "action_key": "ai-ops.list-system-providers",
            "max_rows": 10,
            "layout_area": "providers",
            "target_screen": "ai-ops.system-providers",
            "columns": [
                {"key": "name", "label": "名称"},
                {"key": "provider_type_label", "label": "类型"},
                {"key": "default_model", "label": "默认模型"},
                {"key": "is_active", "label": "启用"},
                {"key": "priority", "label": "优先级"},
            ],
            "user_priority": "p1",
            "presentation_semantic": "supporting_list",
        },
    ],
}

RUNTIME_AI_USER_QUOTAS_SCREEN: dict[str, Any] = {
    "key": "ai-ops.user-quotas",
    "label": "用户 AI 配额",
    "module_key": "ai-ops",
    "group": "ops",
    "summary": "管理员在 TUI 内查看和调整用户兜底配额。",
    "view_type": "detail",
    "default_action_key": "ai-ops.list-user-quotas",
    "user_experience": {
        "journey": "admin",
        "primary_task": "先判断哪些用户配额异常，再决定是否做单用户修正或批量下发。",
        "primary_outcome": "明确哪些用户已超预算、未配置或需要调整配额策略。",
        "empty_state_hint": "先看用户配额列表，再决定是否继续修正单用户或批量策略。",
        "next_step_hint": "确认异常用户后，再执行单用户修正或批量配额调整。",
    },
    "workflow": {
        "name": "AI 管理流程",
        "step": 3,
        "total": 3,
        "label": "配额治理",
        "role": "先看用户配额列表，再做单用户修正或批量下发。",
        "previous": {"key": "ai-ops.system-providers", "label": "系统 AI 服务商"},
        "next": {},
    },
    "business_context": {
        "objective": "把管理员对普通用户 AI 兜底配额的治理能力拉进 TUI。",
        "decision_output": "哪些用户已超预算、哪些用户未配置、哪些批量策略需要更新。",
        "checkpoints": [
            "先看列表确认 daily/monthly spent 与 is_active。",
            "单用户修正优先用 PATCH，批量策略再用 batch apply。",
            "批量覆盖前确认 overwrite_existing，避免误伤已定制配额。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "user-quota-list",
            "title": "一、用户配额列表",
            "kind": "datagrid",
            "action_key": "ai-ops.list-user-quotas",
            "max_rows": 12,
            "layout_area": "quotas",
            "target_screen": "ai-ops.user-quotas",
            "columns": [
                {"key": "username", "label": "用户"},
                {"key": "daily_limit", "label": "日额度"},
                {"key": "monthly_limit", "label": "月额度"},
                {"key": "daily_spent", "label": "今日已用"},
                {"key": "monthly_spent", "label": "本月已用"},
                {"key": "is_active", "label": "启用"},
            ],
            "user_priority": "p0",
            "presentation_semantic": "primary_list",
        }
    ],
}

RUNTIME_IDENTITY_ACCESS_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "capability-router.mcp-self-status",
        "label": "读取我的 MCP 状态",
        "endpoint": "/api/account/mcp/self/",
        "method": "GET",
        "intent": "read_current_user_mcp_self_service",
        "risk": "read",
        "screen_key": "capability-router.self-service",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "读取当前用户的 MCP 开通状态、默认账户、令牌与代理接入提示词。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 100,
        "task_tier": "primary",
        "fields": [],
        "view_model": {"kind": "detail", "title_path": "username", "status_path": "mcp_enabled"},
        "result_semantics": ["primary_status", "copyable_secret"],
    },
    {
        "key": "capability-router.list-my-mcp-tokens",
        "label": "读取我的令牌列表",
        "endpoint": "/api/account/mcp/self/",
        "method": "GET",
        "intent": "list_current_user_mcp_tokens",
        "risk": "read",
        "screen_key": "capability-router.self-service",
        "module_key": "capability-router",
        "view_type": "datagrid",
        "description": "从个人 MCP 状态接口中提取自己的有效令牌列表。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 110,
        "task_tier": "support",
        "fields": [],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "access_tokens",
            "total_path": "active_token_count",
        },
        "result_semantics": ["supporting_list"],
    },
    {
        "key": "capability-router.mcp-self-endpoints",
        "label": "读取我的接入地址",
        "endpoint": "/api/account/mcp/self/",
        "method": "GET",
        "intent": "read_current_user_mcp_endpoints",
        "risk": "read",
        "screen_key": "capability-router.self-service",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "读取当前用户接入 AgomTradePro 所需的基础地址、路由地址、网页对话地址与能力目录。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 115,
        "task_tier": "support",
        "fields": [],
        "view_model": {"kind": "detail", "title_path": "username", "status_path": "mcp_enabled"},
        "result_semantics": ["endpoint_list"],
    },
    {
        "key": "capability-router.mcp-self-prompt-guide",
        "label": "读取我的接入提示词",
        "endpoint": "/api/account/mcp/self/",
        "method": "GET",
        "intent": "read_current_user_mcp_prompt_guide",
        "risk": "read",
        "screen_key": "capability-router.self-service",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "读取当前用户可直接发给外部代理的 MCP/SDK 接入提示词。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 117,
        "task_tier": "support",
        "fields": [],
        "view_model": {"kind": "detail", "title_path": "username", "status_path": "agent_bootstrap_token_ready"},
        "result_semantics": ["multiline_prompt"],
    },
    {
        "key": "capability-router.create-my-mcp-token",
        "label": "创建我的 MCP 令牌",
        "endpoint": "/api/account/mcp/tokens/",
        "method": "POST",
        "intent": "create_current_user_mcp_token",
        "risk": "write",
        "screen_key": "capability-router.self-service",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "为当前用户创建一个新的 MCP 令牌，并返回可直接粘贴给外部代理的接入提示词。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 120,
        "task_tier": "operation",
        "fields": [
            {
                "key": "token_name",
                "label": "令牌名称",
                "input_type": "text",
                "required": False,
                "placeholder": "留空则自动生成",
                "binding": "body",
                "value_type": "string",
                "presentation_semantic": "identifier",
            },
            {
                "key": "access_level",
                "label": "访问级别",
                "input_type": "select",
                "required": True,
                "default": "read_only",
                "binding": "body",
                "value_type": "string",
                "options": ["read_only", "read_write"],
                "presentation_semantic": "identifier",
            },
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
        "result_semantics": ["copyable_secret", "multiline_prompt"],
    },
    {
        "key": "capability-router.revoke-my-mcp-token",
        "label": "撤销我的 MCP 令牌",
        "endpoint": "/api/account/mcp/tokens/<int:token_id>/revoke/",
        "method": "POST",
        "intent": "revoke_current_user_mcp_token",
        "risk": "write",
        "screen_key": "capability-router.self-service",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "撤销当前用户自己名下的一个有效 MCP 令牌。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 130,
        "task_tier": "operation",
        "fields": [
            {
                "key": "token_id",
                "label": "令牌 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
                "presentation_semantic": "primary_selector",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "capability-router.mcp-admin-users",
        "label": "读取 MCP 用户列表",
        "endpoint": "/api/account/admin/mcp/users/",
        "method": "GET",
        "intent": "list_admin_mcp_user_governance_rows",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "datagrid",
        "description": "读取管理员视角下的 MCP 用户、令牌与开关分布。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 200,
        "task_tier": "primary",
        "fields": [
            {
                "key": "q",
                "label": "关键词",
                "input_type": "text",
                "required": False,
                "default": "",
                "placeholder": "搜索用户名或邮箱",
                "binding": "query",
                "value_type": "string",
            },
            {
                "key": "without_token",
                "label": "仅无令牌",
                "input_type": "select",
                "required": False,
                "default": "false",
                "binding": "query",
                "value_type": "boolean",
                "options": ["false", "true"],
            },
        ],
        "view_model": {"kind": "datagrid", "rows_path": "rows", "total_path": "total_users"},
    },
    {
        "key": "capability-router.mcp-admin-user-detail",
        "label": "读取用户 MCP 详情",
        "endpoint": "/api/account/admin/mcp/users/<int:user_id>/",
        "method": "GET",
        "intent": "read_admin_mcp_user_detail",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "查看单个用户的 MCP 状态、令牌以及可复制接入提示词。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 210,
        "task_tier": "support",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "username", "status_path": "mcp_enabled"},
    },
    {
        "key": "capability-router.admin-create-mcp-token",
        "label": "为用户创建 MCP 令牌",
        "endpoint": "/api/account/admin/mcp/users/<int:user_id>/tokens/",
        "method": "POST",
        "intent": "create_admin_managed_mcp_token",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "管理员为指定用户创建一个新令牌，并返回可转发给外部代理的接入提示词。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 220,
        "task_tier": "primary",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "token_name",
                "label": "令牌名称",
                "input_type": "text",
                "required": False,
                "placeholder": "留空则自动生成",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "access_level",
                "label": "访问级别",
                "input_type": "select",
                "required": True,
                "default": "read_only",
                "binding": "body",
                "value_type": "string",
                "options": ["read_only", "read_write"],
            },
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "capability-router.admin-toggle-user-mcp",
        "label": "切换用户 MCP 开关",
        "endpoint": "/api/account/admin/mcp/users/<int:user_id>/toggle/",
        "method": "POST",
        "intent": "toggle_admin_managed_user_mcp",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "管理员直接开启或关闭用户 MCP 权限。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 230,
        "task_tier": "primary",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "capability-router.admin-revoke-user-mcp-tokens",
        "label": "撤销用户全部令牌",
        "endpoint": "/api/account/admin/mcp/users/<int:user_id>/tokens/revoke/",
        "method": "POST",
        "intent": "revoke_admin_managed_user_mcp_tokens",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "管理员一次性回收指定用户的全部 MCP 令牌。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 240,
        "task_tier": "support",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "capability-router.admin-revoke-mcp-token",
        "label": "撤销单个用户令牌",
        "endpoint": "/api/account/admin/mcp/tokens/<int:token_id>/revoke/",
        "method": "POST",
        "intent": "revoke_admin_managed_single_mcp_token",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "管理员按 token_id 回收单个 MCP 令牌。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 250,
        "task_tier": "support",
        "fields": [
            {
                "key": "token_id",
                "label": "令牌 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "ai-ops.list-my-providers",
        "label": "读取我的 AI 服务商",
        "endpoint": "/api/ai/me/providers/",
        "method": "GET",
        "intent": "list_current_user_ai_providers",
        "risk": "read",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "datagrid",
        "description": "读取当前用户自己的 AI 服务商列表。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 300,
        "task_tier": "primary",
        "fields": [],
        "view_model": {"kind": "datagrid"},
    },
    {
        "key": "ai-ops.my-provider-detail",
        "label": "读取我的服务商详情",
        "endpoint": "/api/ai/me/providers/<int:provider_id>/",
        "method": "GET",
        "intent": "read_current_user_ai_provider_detail",
        "risk": "read",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取一个个人 AI 服务商的配置详情。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 310,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.create-my-provider",
        "label": "创建我的服务商",
        "endpoint": "/api/ai/me/providers/",
        "method": "POST",
        "intent": "create_current_user_ai_provider",
        "risk": "write",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "为当前用户创建一个新的个人 AI 服务商。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 320,
        "task_tier": "primary",
        "fields": [
            {
                "key": "name",
                "label": "名称",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "provider_type",
                "label": "类型",
                "input_type": "select",
                "required": True,
                "default": "openai",
                "binding": "body",
                "value_type": "string",
                "options": ["openai", "deepseek", "qwen", "moonshot", "custom"],
            },
            {
                "key": "base_url",
                "label": "基础地址",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_key",
                "label": "API Key",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "default_model",
                "label": "默认模型",
                "input_type": "text",
                "required": False,
                "default": "gpt-3.5-turbo",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_mode",
                "label": "API 模式",
                "input_type": "select",
                "required": False,
                "default": "dual",
                "binding": "body",
                "value_type": "string",
                "options": ["dual", "responses_only", "chat_only"],
            },
            {
                "key": "priority",
                "label": "优先级",
                "input_type": "number",
                "required": False,
                "default": "10",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "select",
                "required": False,
                "default": "true",
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.update-my-provider",
        "label": "更新我的服务商",
        "endpoint": "/api/ai/me/providers/<int:provider_id>/",
        "method": "PATCH",
        "intent": "update_current_user_ai_provider",
        "risk": "write",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "更新一个已有的个人 AI 服务商。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 330,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "name",
                "label": "名称",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "provider_type",
                "label": "类型",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "string",
                "options": ["openai", "deepseek", "qwen", "moonshot", "custom"],
            },
            {
                "key": "base_url",
                "label": "基础地址",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_key",
                "label": "API Key",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "default_model",
                "label": "默认模型",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_mode",
                "label": "API 模式",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "string",
                "options": ["dual", "responses_only", "chat_only"],
            },
            {
                "key": "priority",
                "label": "优先级",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.toggle-my-provider",
        "label": "切换我的服务商启用",
        "endpoint": "/api/ai/me/providers/<int:provider_id>/toggle_active/",
        "method": "POST",
        "intent": "toggle_current_user_ai_provider",
        "risk": "write",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "切换个人 AI 服务商的启用状态。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 340,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.delete-my-provider",
        "label": "删除我的服务商",
        "endpoint": "/api/ai/me/providers/<int:provider_id>/",
        "method": "DELETE",
        "intent": "delete_current_user_ai_provider",
        "risk": "write",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "message",
        "description": "删除一个个人 AI 服务商。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 350,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "message"},
    },
    {
        "key": "ai-ops.my-quota-current",
        "label": "读取我的 Quota",
        "endpoint": "/api/ai/me/quota/current/",
        "method": "GET",
        "intent": "read_current_user_ai_quota",
        "risk": "read",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取当前用户自己的兜底配额使用状态。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 360,
        "task_tier": "support",
        "fields": [],
        "view_model": {"kind": "detail", "title_path": "username", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.my-ai-logs",
        "label": "读取我的 AI 日志",
        "endpoint": "/api/ai/me/logs/",
        "method": "GET",
        "intent": "list_current_user_ai_logs",
        "risk": "read",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "datagrid",
        "description": "读取当前用户自己的 AI 调用日志。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 370,
        "task_tier": "support",
        "fields": [
            {
                "key": "status",
                "label": "状态",
                "input_type": "text",
                "required": False,
                "default": "",
                "binding": "query",
                "value_type": "string",
            },
            {
                "key": "provider_scope",
                "label": "服务商范围",
                "input_type": "text",
                "required": False,
                "default": "",
                "binding": "query",
                "value_type": "string",
            },
            {
                "key": "limit",
                "label": "返回行数",
                "input_type": "hidden",
                "required": False,
                "default": "50",
                "binding": "query",
                "value_type": "integer",
            },
        ],
        "view_model": {"kind": "datagrid"},
    },
    {
        "key": "ai-ops.system-provider-overall-stats",
        "label": "读取系统服务商概览",
        "endpoint": "/api/ai/providers/overall_stats/",
        "method": "GET",
        "intent": "read_admin_ai_provider_overall_stats",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取管理员视角下的系统服务商总体统计。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 400,
        "task_tier": "primary",
        "fields": [],
        "view_model": {"kind": "detail"},
    },
    {
        "key": "ai-ops.list-system-providers",
        "label": "读取系统服务商列表",
        "endpoint": "/api/ai/providers/",
        "method": "GET",
        "intent": "list_admin_ai_system_providers",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "datagrid",
        "description": "读取系统级 AI 服务商列表。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 410,
        "task_tier": "primary",
        "fields": [],
        "view_model": {"kind": "datagrid"},
    },
    {
        "key": "ai-ops.system-provider-detail",
        "label": "读取系统服务商详情",
        "endpoint": "/api/ai/providers/<int:provider_id>/",
        "method": "GET",
        "intent": "read_admin_ai_system_provider_detail",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取一个系统级 AI 服务商的配置详情。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 420,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.create-system-provider",
        "label": "创建系统服务商",
        "endpoint": "/api/ai/providers/",
        "method": "POST",
        "intent": "create_admin_ai_system_provider",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "创建一个系统级 AI 服务商。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 430,
        "task_tier": "primary",
        "fields": [
            {
                "key": "name",
                "label": "名称",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "provider_type",
                "label": "类型",
                "input_type": "select",
                "required": True,
                "default": "openai",
                "binding": "body",
                "value_type": "string",
                "options": ["openai", "deepseek", "qwen", "moonshot", "custom"],
            },
            {
                "key": "base_url",
                "label": "基础地址",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_key",
                "label": "API Key",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "default_model",
                "label": "默认模型",
                "input_type": "text",
                "required": False,
                "default": "gpt-3.5-turbo",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_mode",
                "label": "API 模式",
                "input_type": "select",
                "required": False,
                "default": "dual",
                "binding": "body",
                "value_type": "string",
                "options": ["dual", "responses_only", "chat_only"],
            },
            {
                "key": "priority",
                "label": "优先级",
                "input_type": "number",
                "required": False,
                "default": "10",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "select",
                "required": False,
                "default": "true",
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.update-system-provider",
        "label": "更新系统服务商",
        "endpoint": "/api/ai/providers/<int:provider_id>/",
        "method": "PATCH",
        "intent": "update_admin_ai_system_provider",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "更新一个系统级 AI 服务商。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 440,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "name",
                "label": "名称",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "provider_type",
                "label": "类型",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "string",
                "options": ["openai", "deepseek", "qwen", "moonshot", "custom"],
            },
            {
                "key": "base_url",
                "label": "基础地址",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_key",
                "label": "API Key",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "default_model",
                "label": "默认模型",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_mode",
                "label": "API 模式",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "string",
                "options": ["dual", "responses_only", "chat_only"],
            },
            {
                "key": "priority",
                "label": "优先级",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.toggle-system-provider",
        "label": "切换系统服务商启用",
        "endpoint": "/api/ai/providers/<int:provider_id>/toggle_active/",
        "method": "POST",
        "intent": "toggle_admin_ai_system_provider",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "切换系统级 AI 服务商的启用状态。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 450,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.test-system-provider",
        "label": "测试系统服务商连通性",
        "endpoint": "/api/ai/providers/<int:provider_id>/test-connection/",
        "method": "POST",
        "intent": "test_admin_ai_system_provider_connection",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "测试一个系统级 AI 服务商的连通性。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 460,
        "task_tier": "primary",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail"},
    },
    {
        "key": "ai-ops.system-provider-usage-stats",
        "label": "读取系统服务商用量",
        "endpoint": "/api/ai/providers/<int:provider_id>/usage_stats/",
        "method": "GET",
        "intent": "read_admin_ai_system_provider_usage_stats",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取一个系统级 AI 服务商的今日、本月用量与预算状态。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 470,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "provider_name"},
    },
    {
        "key": "ai-ops.delete-system-provider",
        "label": "删除系统服务商",
        "endpoint": "/api/ai/providers/<int:provider_id>/",
        "method": "DELETE",
        "intent": "delete_admin_ai_system_provider",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "message",
        "description": "删除一个系统级 AI 服务商。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 480,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "message"},
    },
    *RUNTIME_AI_QUOTA_ACTIONS,
)
