"""Runtime TUI metadata for fund research workflows."""

from __future__ import annotations

from typing import Any

from apps.regime.domain.services_v2 import RegimeType

_SCREEN = "research.asset-lab"
_MODULE = "research"
_SOURCE = "approved:runtime-fund"
_REGIME_CHOICES = tuple(regime.value for regime in RegimeType)


def _fund_code(*, binding: str = "path") -> dict[str, Any]:
    """Build one fund-code field."""

    return {
        "key": "fund_code",
        "label": "基金代码",
        "binding": binding,
        "input_type": "text",
        "value_type": "string",
        "required": True,
        "max": 10,
    }


def _regime(*, binding: str, required: bool = False) -> dict[str, Any]:
    """Build one governed regime selector."""

    return {
        "key": "regime",
        "label": "宏观环境",
        "binding": binding,
        "input_type": "select",
        "value_type": "string",
        "required": required,
        "default": "Recovery",
        "options": list(_REGIME_CHOICES),
    }


RUNTIME_FUND_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "fund.multidim-screen",
        "label": "多维筛选基金",
        "endpoint": "/api/fund/tui-multidim-screen/",
        "method": "POST",
        "intent": "screen_funds_multidimensionally",
        "risk": "write",
        "audience": "authenticated",
        "effect": "execute",
        "confirmation_required": True,
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "datagrid",
        "description": "按基金类型、风格、规模与宏观上下文进行多维评分筛选。",
        "source": _SOURCE,
        "task_group": "09 基金研究",
        "sequence": 1030,
        "task_tier": "operation",
        "fields": [
            {
                "key": "fund_type",
                "label": "基金类型",
                "binding": "body",
                "input_type": "text",
                "value_type": "string",
                "required": False,
            },
            {
                "key": "investment_style",
                "label": "投资风格",
                "binding": "body",
                "input_type": "text",
                "value_type": "string",
                "required": False,
            },
            {
                "key": "min_scale",
                "label": "最小规模",
                "binding": "body",
                "input_type": "number",
                "value_type": "float",
                "required": False,
                "min": 0,
            },
            _regime(binding="body", required=True),
            {
                "key": "policy_level",
                "label": "政策档位",
                "binding": "body",
                "input_type": "select",
                "value_type": "string",
                "required": True,
                "default": "P1",
                "options": ["P0", "P1", "P2", "P3"],
            },
            {
                "key": "sentiment_index",
                "label": "情绪指数",
                "binding": "body",
                "input_type": "number",
                "value_type": "float",
                "required": True,
                "default": 0.0,
                "min": -1,
                "max": 1,
            },
            {
                "key": "max_count",
                "label": "最多返回",
                "binding": "body",
                "input_type": "number",
                "value_type": "integer",
                "required": False,
                "default": 30,
                "min": 1,
                "max": 100,
            },
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "funds",
            "columns": [
                {"key": "fund_code", "label": "基金代码"},
                {"key": "fund_name", "label": "基金名称"},
                {"key": "fund_type", "label": "类型"},
                {"key": "investment_style", "label": "风格"},
                {"key": "total_score", "label": "综合分"},
                {"key": "recommendation", "label": "建议"},
            ],
        },
    },
    {
        "key": "fund.rank",
        "label": "查看基金排名",
        "endpoint": "/api/fund/rank/",
        "method": "GET",
        "intent": "rank_funds",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "datagrid",
        "description": "按宏观环境和返回数量查看基金评分排名。",
        "source": _SOURCE,
        "task_group": "09 基金研究",
        "sequence": 1040,
        "task_tier": "operation",
        "fields": [
            _regime(binding="query"),
            {
                "key": "max_count",
                "label": "最多返回",
                "binding": "query",
                "input_type": "number",
                "value_type": "integer",
                "required": False,
                "default": 50,
                "min": 1,
                "max": 200,
            },
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "funds",
            "columns": [
                {"key": "rank", "label": "排名"},
                {"key": "fund_code", "label": "基金代码"},
                {"key": "fund_name", "label": "基金名称"},
                {"key": "total_score", "label": "总分"},
                {"key": "performance_score", "label": "业绩分"},
                {"key": "regime_fit_score", "label": "环境适配"},
                {"key": "risk_score", "label": "风险分"},
            ],
        },
    },
    {
        "key": "fund.score",
        "label": "查看单只基金评分",
        "endpoint": "/api/fund/score/<str:fund_code>/",
        "method": "GET",
        "intent": "read_fund_score",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "查看指定基金在给定宏观环境和日期下的评分。",
        "source": _SOURCE,
        "task_group": "09 基金研究",
        "sequence": 1050,
        "task_tier": "operation",
        "fields": [
            _fund_code(),
            _regime(binding="query"),
            {
                "key": "as_of_date",
                "label": "评分日期",
                "binding": "query",
                "input_type": "date",
                "value_type": "date",
                "required": False,
            },
        ],
        "view_model": {"kind": "detail", "title_path": "score.fund_name"},
    },
    {
        "key": "fund.style",
        "label": "分析基金风格",
        "endpoint": "/api/fund/style/<str:fund_code>/",
        "method": "GET",
        "intent": "analyze_fund_style",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "查看基金风格权重和行业集中度。",
        "source": _SOURCE,
        "task_group": "09 基金研究",
        "sequence": 1060,
        "task_tier": "operation",
        "fields": [
            _fund_code(),
            {
                "key": "report_date",
                "label": "报告日",
                "binding": "query",
                "input_type": "date",
                "value_type": "date",
                "required": False,
            },
        ],
        "view_model": {"kind": "detail", "title_path": "fund_name"},
    },
    {
        "key": "fund.performance",
        "label": "计算基金业绩",
        "endpoint": "/api/fund/performance/calculate/",
        "method": "POST",
        "intent": "calculate_fund_performance",
        "risk": "write",
        "audience": "authenticated",
        "effect": "execute",
        "confirmation_required": True,
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "计算指定起止日期内的收益、波动、夏普、回撤、Beta 与 Alpha。",
        "source": _SOURCE,
        "task_group": "09 基金研究",
        "sequence": 1070,
        "task_tier": "operation",
        "fields": [
            _fund_code(binding="body"),
            {
                "key": "start_date",
                "label": "开始日期",
                "binding": "body",
                "input_type": "date",
                "value_type": "date",
                "required": True,
            },
            {
                "key": "end_date",
                "label": "结束日期",
                "binding": "body",
                "input_type": "date",
                "value_type": "date",
                "required": True,
            },
        ],
        "view_model": {"kind": "detail", "title_path": "fund_name"},
    },
    {
        "key": "fund.info",
        "label": "查看基金资料",
        "endpoint": "/api/fund/info/<str:fund_code>/",
        "method": "GET",
        "intent": "read_fund_info",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "查看基金类型、风格、成立日、管理人、托管人和规模。",
        "source": _SOURCE,
        "task_group": "09 基金研究",
        "sequence": 1080,
        "task_tier": "operation",
        "fields": [_fund_code()],
        "view_model": {"kind": "detail", "title_path": "fund.fund_name"},
    },
    {
        "key": "fund.nav",
        "label": "查看基金净值",
        "endpoint": "/api/fund/nav/<str:fund_code>/",
        "method": "GET",
        "intent": "read_fund_nav",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "datagrid",
        "description": "按起止日期查看单位净值、累计净值和日收益。",
        "source": _SOURCE,
        "task_group": "09 基金研究",
        "sequence": 1090,
        "task_tier": "operation",
        "fields": [
            _fund_code(),
            {
                "key": "start_date",
                "label": "开始日期",
                "binding": "query",
                "input_type": "date",
                "value_type": "date",
                "required": False,
            },
            {
                "key": "end_date",
                "label": "结束日期",
                "binding": "query",
                "input_type": "date",
                "value_type": "date",
                "required": False,
            },
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "nav_data",
            "columns": [
                {"key": "nav_date", "label": "日期"},
                {"key": "unit_nav", "label": "单位净值"},
                {"key": "accum_nav", "label": "累计净值"},
                {"key": "daily_return", "label": "日收益"},
            ],
        },
    },
    {
        "key": "fund.holdings",
        "label": "查看基金持仓",
        "endpoint": "/api/fund/holding/<str:fund_code>/",
        "method": "GET",
        "intent": "read_fund_holdings",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "datagrid",
        "description": "按报告日查看基金股票持仓、金额和占比。",
        "source": _SOURCE,
        "task_group": "09 基金研究",
        "sequence": 1100,
        "task_tier": "operation",
        "fields": [
            _fund_code(),
            {
                "key": "report_date",
                "label": "报告日",
                "binding": "query",
                "input_type": "date",
                "value_type": "date",
                "required": False,
            },
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "holdings",
            "columns": [
                {"key": "stock_code", "label": "证券代码"},
                {"key": "stock_name", "label": "证券名称"},
                {"key": "holding_amount", "label": "持有数量"},
                {"key": "holding_value", "label": "持有市值"},
                {"key": "holding_ratio", "label": "持仓占比"},
            ],
        },
    },
)
