"""Core runtime TUI actions for risk-center surfaces."""

from __future__ import annotations

from typing import Any

RUNTIME_RISK_CENTER_CORE_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "risk-center.floor",
        "label": "全局底线",
        "endpoint": "/api/risk-center/floor/",
        "method": "GET",
        "intent": "read_global_risk_floor",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "读取当前启用的全局风控底线。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 100,
        "task_tier": "primary",
        "view_model": {"kind": "detail", "title_path": "data.name", "status_path": "success"},
    },
    {
        "key": "risk-center.templates",
        "label": "风险模板",
        "endpoint": "/api/risk-center/templates/",
        "method": "GET",
        "intent": "list_risk_templates",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "datagrid",
        "description": "列出全局风险模板。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 110,
        "task_tier": "support",
        "view_model": {"kind": "datagrid", "rows_path": "data"},
    },
    {
        "key": "risk-center.account-policies",
        "label": "账户策略",
        "endpoint": "/api/risk-center/account-policies/",
        "method": "GET",
        "intent": "list_account_risk_policies",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "datagrid",
        "description": "列出当前用户可访问的账户级风控策略。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 120,
        "task_tier": "primary",
        "view_model": {"kind": "datagrid", "rows_path": "data"},
    },
    {
        "key": "risk-center.effective-policy",
        "label": "账户有效策略",
        "endpoint": "/api/risk-center/effective-policy/",
        "method": "GET",
        "intent": "resolve_effective_risk_policy",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "按账户 ID 解析最终生效策略、继承来源、底线和例外说明。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 130,
        "task_tier": "primary",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "输入账户 ID",
                "binding": "query",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "data.account_id", "status_path": "success"},
    },
    {
        "key": "risk-center.exceptions",
        "label": "风控例外",
        "endpoint": "/api/risk-center/exceptions/",
        "method": "GET",
        "intent": "list_risk_exceptions",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "datagrid",
        "description": "列出管理员风控例外，可按账户过滤。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 140,
        "task_tier": "support",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "可选",
                "binding": "query",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "datagrid", "rows_path": "data"},
    },
    {
        "key": "risk-center.pre-trade-check",
        "label": "交易前风控预览",
        "endpoint": "/api/risk-center/pre-trade-check/",
        "method": "POST",
        "intent": "preview_pre_trade_risk",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "输入一笔拟交易，预览集中风控中心是否会拒绝。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 150,
        "task_tier": "primary",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "输入账户 ID",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "symbol",
                "label": "证券代码",
                "input_type": "text",
                "required": True,
                "default": "",
                "placeholder": "000001.SZ",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "side",
                "label": "方向",
                "input_type": "select",
                "required": True,
                "default": "buy",
                "placeholder": "",
                "binding": "body",
                "value_type": "string",
                "options": ["buy", "sell"],
            },
            {
                "key": "quantity",
                "label": "数量",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "100",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "price",
                "label": "价格",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "10.00",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "account_equity",
                "label": "账户权益",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "100000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "total_position_value",
                "label": "当前总持仓",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "50000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "cash_balance",
                "label": "现金余额",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "50000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "current_symbol_position_value",
                "label": "当前单标的市值",
                "input_type": "number",
                "required": False,
                "default": 0,
                "placeholder": "0",
                "binding": "body",
                "value_type": "float",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.passed"},
    },
    {
        "key": "risk-center.post-investment-check",
        "label": "投后风控巡检",
        "endpoint": "/api/risk-center/post-investment-check/",
        "method": "POST",
        "intent": "track_post_investment_risk",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "输入账户权益、现金和持仓快照，巡检集中风控是否已触碰。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 160,
        "task_tier": "primary",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "输入账户 ID",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "account_equity",
                "label": "账户权益",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "100000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "cash_balance",
                "label": "现金余额",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "20000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "total_position_value",
                "label": "持仓总市值",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "80000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "daily_pnl_pct",
                "label": "当日盈亏比例",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "-0.03",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "drawdown_pct",
                "label": "当前回撤比例",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "0.08",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "positions",
                "label": "持仓快照",
                "input_type": "textarea",
                "required": False,
                "default": "[]",
                "placeholder": '[{"symbol":"000001.SZ","market_value":30000,"unrealized_pnl_pct":-0.08}]',
                "binding": "body",
                "value_type": "list",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.status"},
    },
    {
        "key": "risk-center.daily-report",
        "label": "风控/持仓日报",
        "endpoint": "/api/risk-center/daily-report/",
        "method": "POST",
        "intent": "generate_risk_and_position_daily_report",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "输入账户日终快照，生成风控日报和持仓日报。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 170,
        "task_tier": "primary",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "输入账户 ID",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "report_date",
                "label": "报告日期",
                "input_type": "date",
                "required": False,
                "default": "",
                "placeholder": "YYYY-MM-DD",
                "binding": "body",
                "value_type": "date",
            },
            {
                "key": "account_equity",
                "label": "账户权益",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "100000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "cash_balance",
                "label": "现金余额",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "20000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "total_position_value",
                "label": "持仓总市值",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "80000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "daily_pnl_pct",
                "label": "当日盈亏比例",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "-0.03",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "drawdown_pct",
                "label": "当前回撤比例",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "0.08",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "positions",
                "label": "持仓快照",
                "input_type": "textarea",
                "required": False,
                "default": "[]",
                "placeholder": '[{"symbol":"000001.SZ","market_value":30000,"unrealized_pnl_pct":-0.08}]',
                "binding": "body",
                "value_type": "list",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.risk_daily_report.status"},
    },
    {
        "key": "risk-center.daily-report-history",
        "label": "查询历史日报",
        "endpoint": "/api/risk-center/daily-report/",
        "method": "GET",
        "intent": "query_risk_and_position_daily_report_history",
        "risk": "read",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "datagrid",
        "description": "按账户、单日或日期区间查询已归档的风控日报和持仓日报。",
        "source": "approved:runtime-risk-center",
        "task_group": "01 风控查看",
        "sequence": 175,
        "task_tier": "primary",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "留空则查询有权限账户",
                "binding": "query",
                "value_type": "integer",
            },
            {
                "key": "report_date",
                "label": "报告日期",
                "input_type": "date",
                "required": False,
                "default": "",
                "placeholder": "YYYY-MM-DD",
                "binding": "query",
                "value_type": "date",
            },
            {
                "key": "start_date",
                "label": "开始日期",
                "input_type": "date",
                "required": False,
                "default": "",
                "placeholder": "YYYY-MM-DD",
                "binding": "query",
                "value_type": "date",
            },
            {
                "key": "end_date",
                "label": "结束日期",
                "input_type": "date",
                "required": False,
                "default": "",
                "placeholder": "YYYY-MM-DD",
                "binding": "query",
                "value_type": "date",
            },
            {
                "key": "limit",
                "label": "返回数量",
                "input_type": "number",
                "required": False,
                "default": "30",
                "placeholder": "30",
                "binding": "query",
                "value_type": "integer",
            },
        ],
        "view_model": {"kind": "datagrid", "rows_path": "data"},
    },
    {
        "key": "risk-center.update-floor",
        "label": "更新全局底线",
        "endpoint": "/api/risk-center/floor/",
        "method": "PUT",
        "intent": "update_global_risk_floor",
        "risk": "write",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "经过确认后更新全局风控底线。",
        "source": "approved:runtime-risk-center",
        "task_group": "02 风控写入",
        "sequence": 200,
        "task_tier": "advanced",
        "fields": [
            {
                "key": "max_total_position_pct",
                "label": "总仓位上限",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "0.8",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "max_single_position_pct",
                "label": "单标的上限",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "0.18",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "min_cash_pct",
                "label": "最低现金比例",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "0.15",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "reason",
                "label": "变更理由",
                "input_type": "text",
                "required": True,
                "default": "",
                "placeholder": "说明本次全局底线调整原因",
                "binding": "body",
                "value_type": "string",
            },
        ],
    },
    {
        "key": "risk-center.upsert-policy",
        "label": "保存账户策略",
        "endpoint": "/api/risk-center/account-policies/",
        "method": "POST",
        "intent": "upsert_account_risk_policy",
        "risk": "write",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "经过确认后创建或更新账户级风控策略。",
        "source": "approved:runtime-risk-center",
        "task_group": "02 风控写入",
        "sequence": 210,
        "task_tier": "primary",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "输入账户 ID",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "risk_profile",
                "label": "风险偏好",
                "input_type": "select",
                "required": False,
                "default": "moderate",
                "placeholder": "",
                "binding": "body",
                "value_type": "string",
                "options": ["conservative", "moderate", "aggressive", "custom"],
            },
            {
                "key": "max_total_position_pct",
                "label": "总仓位上限",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "0.75",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "max_single_position_pct",
                "label": "单标的上限",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "0.18",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "reason",
                "label": "变更理由",
                "input_type": "text",
                "required": False,
                "default": "TUI account risk policy update",
                "placeholder": "说明本次账户策略调整原因",
                "binding": "body",
                "value_type": "string",
            },
        ],
    },
)
