"""Runtime TUI metadata injection constants for capability routing."""

from __future__ import annotations

from typing import Any


RUNTIME_CAPABILITY_ROUTER_MODULE: dict[str, Any] = {
    "key": "capability-router",
    "label": "能力路由",
    "group": "ops",
    "summary": "统一接入能力目录、智能路由、MCP 工具和内部能力。",
}

RUNTIME_CAPABILITY_ROUTER_SCREEN: dict[str, Any] = {
    "key": "capability-router.gateway",
    "label": "能力路由接入",
    "module_key": "capability-router",
    "group": "ops",
    "summary": "验证自然语言请求如何通过统一路由层选择能力，并检查目录覆盖状态。",
    "view_type": "detail",
    "default_action_key": "capability-router.route-message",
    "workflow": {
        "name": "能力接入流程",
        "step": 1,
        "total": 2,
        "label": "统一路由",
        "role": "先验证统一路由与目录覆盖，再进入 MCP 接入中心处理开关与同步。",
        "previous": {},
        "next": {"key": "capability-router.mcp-center", "label": "MCP 接入中心"},
    },
    "business_context": {
        "objective": "把 AI/TUI/Terminal 请求先送入统一路由层，再由后端选择 MCP、Terminal、内置能力或内部 API。",
        "decision_output": "路由结果、候选能力、是否需要确认、缺失参数和回答链摘要。",
        "checkpoints": [
            "先运行目录统计，确认 MCP、Terminal、API 能力已同步。",
            "再用路由测试输入自然语言问题，观察 selected_capability_key 和 requires_confirmation。",
            "若能力未命中，回到 MCP 工具治理页打开 enabled_for_routing 或补充能力描述。",
        ],
    },
}

RUNTIME_CAPABILITY_ROUTER_MCP_SCREEN: dict[str, Any] = {
    "key": "capability-router.mcp-center",
    "label": "MCP 接入中心",
    "module_key": "capability-router",
    "group": "ops",
    "summary": "在 TUI 内查看已同步 MCP server/tool 目录，处理同步、路由开关和终端开关。",
    "view_type": "detail",
    "default_action_key": "capability-router.mcp-tools-stats",
    "workflow": {
        "name": "能力接入流程",
        "step": 2,
        "total": 2,
        "label": "MCP 治理",
        "role": "先看同步与开关统计，再处理未放行工具并回查工具详情。",
        "previous": {"key": "capability-router.gateway", "label": "能力路由接入"},
        "next": {},
    },
    "business_context": {
        "objective": "在不离开 TUI 的情况下完成 MCP 目录同步、筛查和路由放行。",
        "decision_output": "哪些 MCP 工具已同步、哪些已进入 Routing/Terminal，以及哪些仍需人工治理。",
        "checkpoints": [
            "先看 MCP 统计，确认最近同步时间、路由启用数和终端启用数。",
            "再看全部工具或 routing_off 列表，定位仍未放行的能力。",
            "需要变更时，先查工具详情和 schema，再切换 routing 或 terminal 开关。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "mcp-tools-stats",
            "title": "一、MCP 同步与治理概览",
            "kind": "detail",
            "action_key": "capability-router.mcp-tools-stats",
            "layout_area": "summary",
            "target_screen": "capability-router.mcp-center",
        },
        {
            "key": "mcp-tools-list",
            "title": "二、已同步 MCP 工具",
            "kind": "datagrid",
            "action_key": "capability-router.list-mcp-tools",
            "max_rows": 8,
            "layout_area": "tools",
            "target_screen": "capability-router.mcp-center",
            "columns": [
                {"key": "capability_key", "label": "Capability"},
                {"key": "module_name", "label": "模块"},
                {"key": "risk_level", "label": "风险"},
                {"key": "enabled_for_routing", "label": "Routing"},
                {"key": "enabled_for_terminal", "label": "Terminal"},
            ],
        },
        {
            "key": "mcp-tools-routing-off",
            "title": "三、待放行 Routing 工具",
            "kind": "datagrid",
            "action_key": "capability-router.list-mcp-routing-off",
            "max_rows": 6,
            "layout_area": "routing_off",
            "target_screen": "capability-router.mcp-center",
            "columns": [
                {"key": "capability_key", "label": "Capability"},
                {"key": "review_status", "label": "审核"},
                {"key": "risk_level", "label": "风险"},
                {"key": "summary", "label": "说明"},
            ],
        },
    ],
}

RUNTIME_CAPABILITY_ROUTER_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "capability-router.route-message",
        "label": "测试统一路由",
        "endpoint": "/api/ai-capability/route/",
        "method": "POST",
        "intent": "test_capability_router_entrypoint",
        "risk": "ai",
        "screen_key": "capability-router.gateway",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "输入自然语言，由 Capability Router 返回候选能力、选中能力、确认状态和回复。",
        "source": "approved:runtime-capability-router",
        "task_group": "01 路由验证",
        "sequence": 100,
        "task_tier": "primary",
        "fields": [
            {
                "key": "message",
                "label": "消息",
                "input_type": "textarea",
                "required": True,
                "default": "现在系统状态如何？",
                "placeholder": "输入希望 AI 执行或查询的任务",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "entrypoint",
                "label": "入口",
                "input_type": "hidden",
                "required": True,
                "default": "tui",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "context",
                "label": "上下文",
                "input_type": "textarea",
                "required": False,
                "default": '{"answer_chain_enabled": true, "params": {}}',
                "placeholder": '{"params": {}}',
                "binding": "body",
                "value_type": "object",
            },
        ],
        "view_model": {
            "kind": "detail",
            "title_path": "selected_capability_key",
            "status_path": "decision",
        },
    },
    {
        "key": "capability-router.catalog-stats",
        "label": "能力目录统计",
        "endpoint": "/api/ai-capability/stats/",
        "method": "GET",
        "intent": "inspect_capability_catalog_stats",
        "risk": "read",
        "screen_key": "capability-router.gateway",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "查看能力目录总量、启用量、来源分布和路由组分布。",
        "source": "approved:runtime-capability-router",
        "task_group": "02 目录检查",
        "sequence": 110,
        "task_tier": "support",
        "view_model": {
            "kind": "detail",
            "title_path": "total",
            "status_path": "enabled",
        },
    },
    {
        "key": "capability-router.list-capabilities",
        "label": "能力列表",
        "endpoint": "/api/ai-capability/capabilities/",
        "method": "GET",
        "intent": "list_routable_capabilities",
        "risk": "read",
        "screen_key": "capability-router.gateway",
        "module_key": "capability-router",
        "view_type": "datagrid",
        "description": "按来源、分类或关键词查看当前进入能力目录的能力。",
        "source": "approved:runtime-capability-router",
        "task_group": "02 目录检查",
        "sequence": 120,
        "task_tier": "support",
        "fields": [
            {
                "key": "source_type",
                "label": "来源类型",
                "input_type": "select",
                "required": False,
                "default": "",
                "placeholder": "全部",
                "binding": "query",
                "value_type": "string",
                "options": ["", "builtin", "terminal_command", "mcp_tool", "api"],
            },
            {
                "key": "q",
                "label": "关键词",
                "input_type": "text",
                "required": False,
                "default": "",
                "placeholder": "搜索能力名称或说明",
                "binding": "query",
                "value_type": "string",
            },
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "",
        },
    },
    {
        "key": "capability-router.mcp-tools-stats",
        "label": "MCP 接入概览",
        "endpoint": "/api/ai-capability/mcp-tools/stats/",
        "method": "GET",
        "intent": "inspect_mcp_governance_stats",
        "risk": "admin",
        "screen_key": "capability-router.mcp-center",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "查看 MCP 目录同步、路由开关和终端开关的最新治理摘要。",
        "source": "approved:runtime-capability-router",
        "task_group": "03 MCP 治理",
        "sequence": 200,
        "task_tier": "primary",
        "view_model": {
            "kind": "detail",
            "title_path": "status",
            "status_path": "status",
        },
    },
    {
        "key": "capability-router.list-mcp-tools",
        "label": "MCP 工具目录",
        "endpoint": "/api/ai-capability/mcp-tools/",
        "method": "GET",
        "intent": "list_mcp_governance_tools",
        "risk": "admin",
        "screen_key": "capability-router.mcp-center",
        "module_key": "capability-router",
        "view_type": "datagrid",
        "description": "查看已同步到能力目录的 MCP 工具及其治理开关。",
        "source": "approved:runtime-capability-router",
        "task_group": "03 MCP 治理",
        "sequence": 210,
        "task_tier": "primary",
        "fields": [
            {
                "key": "q",
                "label": "关键词",
                "input_type": "text",
                "required": False,
                "default": "",
                "placeholder": "搜索 capability_key / name / summary",
                "binding": "query",
                "value_type": "string",
            },
            {
                "key": "module",
                "label": "模块前缀",
                "input_type": "text",
                "required": False,
                "default": "",
                "placeholder": "如 data_center / risk_center",
                "binding": "query",
                "value_type": "string",
            },
            {
                "key": "status",
                "label": "治理状态",
                "input_type": "select",
                "required": False,
                "default": "",
                "placeholder": "全部",
                "binding": "query",
                "value_type": "string",
                "options": ["", "routing_on", "routing_off", "terminal_on", "terminal_off"],
            },
            {
                "key": "limit",
                "label": "返回行数",
                "input_type": "hidden",
                "required": False,
                "default": "60",
                "binding": "query",
                "value_type": "integer",
            },
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "tools",
            "total_path": "total_count",
        },
    },
    {
        "key": "capability-router.list-mcp-routing-off",
        "label": "待放行 MCP 工具",
        "endpoint": "/api/ai-capability/mcp-tools/",
        "method": "GET",
        "intent": "list_mcp_routing_off_tools",
        "risk": "admin",
        "screen_key": "capability-router.mcp-center",
        "module_key": "capability-router",
        "view_type": "datagrid",
        "description": "快速查看尚未进入 AI Routing 候选集的 MCP 工具。",
        "source": "approved:runtime-capability-router",
        "task_group": "03 MCP 治理",
        "sequence": 220,
        "task_tier": "support",
        "fields": [
            {
                "key": "status",
                "label": "治理状态",
                "input_type": "hidden",
                "required": False,
                "default": "routing_off",
                "binding": "query",
                "value_type": "string",
            },
            {
                "key": "limit",
                "label": "返回行数",
                "input_type": "hidden",
                "required": False,
                "default": "20",
                "binding": "query",
                "value_type": "integer",
            },
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "tools",
            "total_path": "total_count",
        },
    },
    {
        "key": "capability-router.mcp-tool-detail",
        "label": "MCP 工具详情",
        "endpoint": "/api/ai-capability/capabilities/<str:capability_key>/",
        "method": "GET",
        "intent": "inspect_mcp_tool_detail",
        "risk": "admin",
        "screen_key": "capability-router.mcp-center",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "查看单个 MCP 工具的 schema、风险、可见性和治理状态。",
        "source": "approved:runtime-capability-router",
        "task_group": "03 MCP 治理",
        "sequence": 230,
        "task_tier": "support",
        "fields": [
            {
                "key": "capability_key",
                "label": "Capability Key",
                "input_type": "text",
                "required": True,
                "default": "",
                "placeholder": "mcp_tool.get_xxx",
                "binding": "path",
                "value_type": "string",
            }
        ],
    },
    {
        "key": "capability-router.sync-mcp-tools",
        "label": "重新同步 MCP 工具",
        "endpoint": "/api/ai-capability/mcp-tools/sync/",
        "method": "POST",
        "intent": "sync_mcp_governance_tools",
        "risk": "admin",
        "screen_key": "capability-router.mcp-center",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "重新同步 SDK 注册的 MCP 工具，并立即执行能力目录治理。",
        "source": "approved:runtime-capability-router",
        "task_group": "03 MCP 治理",
        "sequence": 240,
        "task_tier": "primary",
    },
    {
        "key": "capability-router.toggle-mcp-routing",
        "label": "切换 Routing 开关",
        "endpoint": "/api/ai-capability/mcp-tools/<str:capability_key>/toggle/enabled_for_routing/",
        "method": "POST",
        "intent": "toggle_mcp_routing_flag",
        "risk": "admin",
        "screen_key": "capability-router.mcp-center",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "切换单个 MCP 工具是否进入 AI Routing 候选集。",
        "source": "approved:runtime-capability-router",
        "task_group": "03 MCP 治理",
        "sequence": 250,
        "task_tier": "primary",
        "fields": [
            {
                "key": "capability_key",
                "label": "Capability Key",
                "input_type": "text",
                "required": True,
                "default": "",
                "placeholder": "mcp_tool.get_xxx",
                "binding": "path",
                "value_type": "string",
            }
        ],
    },
    {
        "key": "capability-router.toggle-mcp-terminal",
        "label": "切换 Terminal 开关",
        "endpoint": "/api/ai-capability/mcp-tools/<str:capability_key>/toggle/enabled_for_terminal/",
        "method": "POST",
        "intent": "toggle_mcp_terminal_flag",
        "risk": "admin",
        "screen_key": "capability-router.mcp-center",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "切换单个 MCP 工具是否允许在 Terminal/TUI 直接执行。",
        "source": "approved:runtime-capability-router",
        "task_group": "03 MCP 治理",
        "sequence": 260,
        "task_tier": "primary",
        "fields": [
            {
                "key": "capability_key",
                "label": "Capability Key",
                "input_type": "text",
                "required": True,
                "default": "",
                "placeholder": "mcp_tool.get_xxx",
                "binding": "path",
                "value_type": "string",
            }
        ],
    },
)
