"""Runtime TUI metadata for prompt template and chain management."""

from __future__ import annotations

from typing import Any

_CATEGORY_OPTIONS: list[dict[str, str]] = [
    {"value": "report", "label": "报告分析"},
    {"value": "signal", "label": "信号生成"},
    {"value": "analysis", "label": "数据分析"},
    {"value": "chat", "label": "对话"},
]

_TEMPLATE_FIELDS: list[dict[str, Any]] = [
    {
        "key": "name",
        "label": "模板名称",
        "input_type": "text",
        "required": True,
        "binding": "body",
        "value_type": "string",
    },
    {
        "key": "category",
        "label": "分类",
        "input_type": "select",
        "required": True,
        "binding": "body",
        "value_type": "string",
        "options": _CATEGORY_OPTIONS,
    },
    {
        "key": "version",
        "label": "版本",
        "input_type": "text",
        "required": False,
        "binding": "body",
        "value_type": "string",
        "default": "1.0",
    },
    {
        "key": "system_prompt",
        "label": "系统提示词",
        "input_type": "textarea",
        "required": False,
        "binding": "body",
        "value_type": "string",
        "presentation_semantic": "prompt_text",
    },
    {
        "key": "template_content",
        "label": "模板内容",
        "input_type": "textarea",
        "required": True,
        "binding": "body",
        "value_type": "string",
        "presentation_semantic": "prompt_text",
    },
    {
        "key": "placeholders",
        "label": "占位符定义",
        "input_type": "textarea",
        "required": False,
        "binding": "body",
        "value_type": "list",
        "default": [],
        "placeholder": '[{"name":"asset_code","type":"simple","required":true}]',
    },
    {
        "key": "temperature",
        "label": "温度",
        "input_type": "number",
        "required": False,
        "binding": "body",
        "value_type": "float",
        "default": 0.7,
        "min": 0,
        "max": 2,
    },
    {
        "key": "max_tokens",
        "label": "最大 Token",
        "input_type": "number",
        "required": False,
        "binding": "body",
        "value_type": "integer",
        "min": 1,
        "max": 200000,
    },
    {
        "key": "description",
        "label": "说明",
        "input_type": "textarea",
        "required": False,
        "binding": "body",
        "value_type": "string",
    },
    {
        "key": "is_active",
        "label": "启用",
        "input_type": "checkbox",
        "required": False,
        "binding": "body",
        "value_type": "boolean",
        "default": True,
    },
]

_CHAIN_FIELDS: list[dict[str, Any]] = [
    {
        "key": "name",
        "label": "链名称",
        "input_type": "text",
        "required": True,
        "binding": "body",
        "value_type": "string",
    },
    {
        "key": "category",
        "label": "分类",
        "input_type": "select",
        "required": True,
        "binding": "body",
        "value_type": "string",
        "options": _CATEGORY_OPTIONS,
    },
    {
        "key": "description",
        "label": "说明",
        "input_type": "textarea",
        "required": False,
        "binding": "body",
        "value_type": "string",
    },
    {
        "key": "steps",
        "label": "执行步骤",
        "input_type": "textarea",
        "required": True,
        "binding": "body",
        "value_type": "list",
        "placeholder": (
            '[{"step_id":"step-1","template_id":"1","step_name":"分析",'
            '"order":1,"input_mapping":{}}]'
        ),
    },
    {
        "key": "execution_mode",
        "label": "执行模式",
        "input_type": "select",
        "required": True,
        "binding": "body",
        "value_type": "string",
        "default": "serial",
        "options": [
            {"value": "serial", "label": "串行"},
            {"value": "parallel", "label": "并行"},
            {"value": "tool", "label": "工具调用"},
            {"value": "hybrid", "label": "混合"},
        ],
    },
    {
        "key": "aggregate_step",
        "label": "聚合步骤",
        "input_type": "textarea",
        "required": False,
        "binding": "body",
        "value_type": "object",
    },
    {
        "key": "is_active",
        "label": "启用",
        "input_type": "checkbox",
        "required": False,
        "binding": "body",
        "value_type": "boolean",
        "default": True,
    },
]


def _path_field(key: str, label: str) -> dict[str, Any]:
    """Build a required integer path selector."""

    return {
        "key": key,
        "label": label,
        "input_type": "number",
        "required": True,
        "binding": "path",
        "value_type": "integer",
        "presentation_semantic": "primary_selector",
    }


RUNTIME_PROMPT_SCREEN: dict[str, Any] = {
    "key": "prompt.workbench",
    "dashboard_layout": "task_flow",
    "workflow": {
        "name": "AI 工具配置流程",
        "label": "提示词模板与执行链",
        "role": "维护 AI 任务可复用的提示词与编排。",
        "previous": {"key": "ai-ops.providers", "label": "我的 AI 服务商"},
        "next": {"key": "ai-ops.terminal", "label": "AI 任务助手"},
    },
    "business_context": {
        "objective": "把模板、链、测试和执行记录放在同一任务上下文中。",
        "decision_output": "可用的提示词与执行链版本，以及一次可追溯的测试结果。",
        "checkpoints": [
            "先确认模板内容、占位符和版本，再执行测试。",
            "模板与链变更仅对管理员开放，删除和执行必须确认。",
            "执行后检查模型、Token、耗时、成本和错误信息。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "prompt-template-list",
            "title": "一、提示词模板",
            "kind": "datagrid",
            "action_key": "prompt-template.list",
            "max_rows": 10,
            "layout_area": "templates",
            "target_screen": "prompt.workbench",
            "columns": [
                {"key": "id", "label": "模板 ID"},
                {"key": "name", "label": "名称"},
                {"key": "category", "label": "分类"},
                {"key": "version", "label": "版本"},
                {"key": "is_active", "label": "启用"},
                {"key": "updated_at", "label": "更新时间"},
            ],
            "row_actions": [
                {
                    "action_key": "prompt-template.update",
                    "label_template": "编辑 {name}",
                    "param_map": {"template_id": "id"},
                    "result_panel_key": "prompt-operation-workspace",
                    "refresh_panel_key": "prompt-template-list",
                },
                {
                    "action_key": "prompt-template.execute",
                    "label_template": "测试 {name}",
                    "param_map": {"template_id": "id"},
                    "result_panel_key": "prompt-operation-workspace",
                },
                {
                    "action_key": "prompt-template.delete",
                    "label_template": "删除 {name}",
                    "param_map": {"template_id": "id"},
                    "result_panel_key": "prompt-operation-workspace",
                    "refresh_panel_key": "prompt-template-list",
                },
            ],
            "empty_message": "暂无可用提示词模板。",
            "user_priority": "p0",
            "presentation_semantic": "primary_list",
        },
        {
            "key": "prompt-chain-list",
            "title": "二、执行链",
            "kind": "datagrid",
            "action_key": "prompt-chain.list",
            "max_rows": 8,
            "layout_area": "chains",
            "target_screen": "prompt.workbench",
            "columns": [
                {"key": "id", "label": "执行链 ID"},
                {"key": "name", "label": "名称"},
                {"key": "category", "label": "分类"},
                {"key": "execution_mode", "label": "执行模式"},
                {"key": "is_active", "label": "启用"},
                {"key": "updated_at", "label": "更新时间"},
            ],
            "row_actions": [
                {
                    "action_key": "prompt-chain.update",
                    "label_template": "编辑 {name}",
                    "param_map": {"chain_id": "id"},
                    "result_panel_key": "prompt-operation-workspace",
                    "refresh_panel_key": "prompt-chain-list",
                },
                {
                    "action_key": "prompt-chain.delete",
                    "label_template": "删除 {name}",
                    "param_map": {"chain_id": "id"},
                    "result_panel_key": "prompt-operation-workspace",
                    "refresh_panel_key": "prompt-chain-list",
                },
            ],
            "empty_message": "暂无可用执行链。",
            "user_priority": "p1",
            "presentation_semantic": "supporting_list",
        },
        {
            "key": "prompt-recent-logs",
            "title": "三、最近执行记录",
            "kind": "datagrid",
            "action_key": "prompt-log.recent",
            "max_rows": 8,
            "layout_area": "logs",
            "target_screen": "prompt.workbench",
            "empty_message": "暂无执行记录。",
            "user_priority": "p1",
            "presentation_semantic": "supporting_list",
        },
        {
            "key": "prompt-operation-workspace",
            "title": "四、当前配置与操作回执",
            "kind": "detail",
            "max_rows": 12,
            "layout_area": "operation-workspace",
            "target_screen": "prompt.workbench",
            "empty_message": "从模板或执行链列表选择编辑、测试或删除操作。",
            "user_priority": "p1",
            "presentation_semantic": "supporting_detail",
        },
    ],
}

RUNTIME_PROMPT_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "prompt-template.list",
        "label": "提示词模板",
        "endpoint": "/api/prompt/templates/",
        "method": "GET",
        "intent": "list_prompt_templates",
        "risk": "read",
        "screen_key": "prompt.workbench",
        "module_key": "research-tools",
        "view_type": "datagrid",
        "description": "按名称或分类查看当前可用提示词模板。",
        "source": "approved:runtime-prompt-workbench",
        "task_group": "01 模板",
        "sequence": 100,
        "task_tier": "primary",
        "fields": [
            {
                "key": "name",
                "label": "模板名称",
                "input_type": "text",
                "required": False,
                "binding": "query",
                "value_type": "string",
            },
            {
                "key": "category",
                "label": "分类",
                "input_type": "select",
                "required": False,
                "binding": "query",
                "value_type": "string",
                "options": _CATEGORY_OPTIONS,
            },
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "results",
            "total_path": "count",
        },
        "result_semantics": [],
    },
    {
        "key": "prompt-chain.list",
        "label": "提示词执行链",
        "endpoint": "/api/prompt/chains/",
        "method": "GET",
        "intent": "list_prompt_chains",
        "risk": "read",
        "screen_key": "prompt.workbench",
        "module_key": "research-tools",
        "view_type": "datagrid",
        "description": "查看当前可用的提示词执行链。",
        "source": "approved:runtime-prompt-workbench",
        "task_group": "03 执行链",
        "sequence": 300,
        "task_tier": "support",
        "fields": [],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "results",
            "total_path": "count",
        },
        "result_semantics": [],
    },
    {
        "key": "prompt-log.recent",
        "label": "最近执行记录",
        "endpoint": "/api/prompt/logs/recent/",
        "method": "GET",
        "intent": "list_recent_prompt_execution_logs",
        "risk": "admin",
        "audience": "admin",
        "screen_key": "prompt.workbench",
        "module_key": "research-tools",
        "view_type": "datagrid",
        "description": "查看最近的提示词或执行链调用记录。",
        "source": "approved:runtime-prompt-workbench",
        "task_group": "04 记录",
        "sequence": 400,
        "task_tier": "support",
        "fields": [
            {
                "key": "limit",
                "label": "返回数量",
                "input_type": "number",
                "required": False,
                "binding": "query",
                "value_type": "integer",
                "default": 20,
                "min": 1,
                "max": 100,
            }
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "results",
            "total_path": "count",
        },
        "result_semantics": [],
    },
    {
        "key": "prompt-template.create",
        "label": "新建提示词模板",
        "endpoint": "/api/prompt/templates/",
        "method": "POST",
        "intent": "create_prompt_template",
        "risk": "admin",
        "audience": "admin",
        "effect": "create",
        "confirmation_required": True,
        "screen_key": "prompt.workbench",
        "module_key": "research-tools",
        "view_type": "detail",
        "description": "创建一份版本化提示词模板。",
        "source": "approved:runtime-prompt-workbench",
        "task_group": "01 模板",
        "sequence": 110,
        "task_tier": "operation",
        "fields": _TEMPLATE_FIELDS,
    },
    {
        "key": "prompt-template.update",
        "label": "更新提示词模板",
        "endpoint": "/api/prompt/templates/<int:template_id>/",
        "method": "PATCH",
        "intent": "update_prompt_template",
        "risk": "admin",
        "audience": "admin",
        "effect": "update",
        "confirmation_required": True,
        "screen_key": "prompt.workbench",
        "module_key": "research-tools",
        "view_type": "detail",
        "description": "更新指定提示词模板的显式字段。",
        "source": "approved:runtime-prompt-workbench",
        "task_group": "01 模板",
        "sequence": 120,
        "task_tier": "operation",
        "fields": [_path_field("template_id", "模板 ID"), *_TEMPLATE_FIELDS],
    },
    {
        "key": "prompt-template.delete",
        "label": "删除提示词模板",
        "endpoint": "/api/prompt/templates/<int:template_id>/",
        "method": "DELETE",
        "intent": "delete_prompt_template",
        "risk": "admin",
        "audience": "admin",
        "effect": "delete",
        "confirmation_required": True,
        "screen_key": "prompt.workbench",
        "module_key": "research-tools",
        "view_type": "status",
        "description": "删除指定提示词模板。",
        "source": "approved:runtime-prompt-workbench",
        "task_group": "01 模板",
        "sequence": 130,
        "task_tier": "advanced",
        "fields": [_path_field("template_id", "模板 ID")],
    },
    {
        "key": "prompt-template.execute",
        "label": "测试执行提示词",
        "endpoint": "/api/prompt/templates/<int:template_id>/execute/",
        "method": "POST",
        "intent": "execute_prompt_template",
        "risk": "ai",
        "effect": "create",
        "confirmation_required": True,
        "screen_key": "prompt.workbench",
        "module_key": "research-tools",
        "view_type": "detail",
        "description": "使用占位符和可选模型参数执行一次提示词测试。",
        "source": "approved:runtime-prompt-workbench",
        "task_group": "02 测试",
        "sequence": 210,
        "task_tier": "primary",
        "fields": [
            _path_field("template_id", "模板 ID"),
            {
                "key": "placeholder_values",
                "label": "占位符值",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "value_type": "object",
                "default": {},
            },
            {
                "key": "provider_ref",
                "label": "服务商引用",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "value_type": "object",
            },
            {
                "key": "provider_name",
                "label": "服务商",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "model",
                "label": "模型",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "temperature",
                "label": "温度",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "float",
                "min": 0,
                "max": 2,
            },
            {
                "key": "max_tokens",
                "label": "最大 Token",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "integer",
                "min": 1,
                "max": 200000,
            },
        ],
    },
    {
        "key": "prompt-chain.create",
        "label": "新建执行链",
        "endpoint": "/api/prompt/chains/",
        "method": "POST",
        "intent": "create_prompt_chain",
        "risk": "admin",
        "audience": "admin",
        "effect": "create",
        "confirmation_required": True,
        "screen_key": "prompt.workbench",
        "module_key": "research-tools",
        "view_type": "detail",
        "description": "创建一条提示词执行链。",
        "source": "approved:runtime-prompt-workbench",
        "task_group": "03 执行链",
        "sequence": 310,
        "task_tier": "operation",
        "fields": _CHAIN_FIELDS,
    },
    {
        "key": "prompt-chain.update",
        "label": "更新执行链",
        "endpoint": "/api/prompt/chains/<int:chain_id>/",
        "method": "PATCH",
        "intent": "update_prompt_chain",
        "risk": "admin",
        "audience": "admin",
        "effect": "update",
        "confirmation_required": True,
        "screen_key": "prompt.workbench",
        "module_key": "research-tools",
        "view_type": "detail",
        "description": "更新指定提示词执行链。",
        "source": "approved:runtime-prompt-workbench",
        "task_group": "03 执行链",
        "sequence": 320,
        "task_tier": "operation",
        "fields": [_path_field("chain_id", "执行链 ID"), *_CHAIN_FIELDS],
    },
    {
        "key": "prompt-chain.delete",
        "label": "删除执行链",
        "endpoint": "/api/prompt/chains/<int:chain_id>/",
        "method": "DELETE",
        "intent": "delete_prompt_chain",
        "risk": "admin",
        "audience": "admin",
        "effect": "delete",
        "confirmation_required": True,
        "screen_key": "prompt.workbench",
        "module_key": "research-tools",
        "view_type": "status",
        "description": "删除指定提示词执行链。",
        "source": "approved:runtime-prompt-workbench",
        "task_group": "03 执行链",
        "sequence": 330,
        "task_tier": "advanced",
        "fields": [_path_field("chain_id", "执行链 ID")],
    },
)
