"""Runtime screen patches for research-oriented TUI surfaces."""

from __future__ import annotations

from typing import Any

RUNTIME_SCREEN_PATCHES_RESEARCH: dict[str, dict[str, Any]] = {
    "research.signals": {
        "default_action_key": "dashboard.beta-market-summary",
        "user_experience": {
            "journey": "dashboard",
            "primary_task": "先确认 Beta 市场态势，再筛出今天最值得研究的 Alpha 股票。",
            "primary_outcome": "得到市场参与结论、Alpha 股票清单及每只股票的入选或阻断理由。",
            "empty_state_hint": "无候选时先看 Beta 数据可用性，再检查 Alpha 评分日、股票池和触发条件。",
            "next_step_hint": "仅对通过 Beta 与风控约束的股票进入账户和持仓检查。",
        },
        "business_context": {
            "objective": "把 Beta 市场态势与 Alpha 横截面选股收敛为一条可解释判断链。",
            "decision_output": "Beta 结论、Alpha 排名、建议仓位、入选理由和不行动理由。",
            "checkpoints": [
                "先看 Beta 市场结论，确认数据是否可用于决策。",
                "再看 Alpha 排名、约束结果和建议仓位。",
                "最后复核已触发候选和证伪条件。",
            ],
        },
        "dashboard_panels": [
            {
                "key": "beta-market-summary",
                "title": "一、Beta 市场结论",
                "kind": "datagrid",
                "action_key": "dashboard.beta-market-summary",
                "max_rows": 1,
                "layout_area": "beta_summary",
                "user_priority": "p0",
                "presentation_semantic": "primary_list",
                "note": "Beta 结论来自 Regime + Pulse 联合建议；A股情绪不是系统运行状态。",
                "empty_message": "暂无可用的 Beta 市场结论。",
                "error_message": "Beta 市场结论加载失败，请先检查环境与脉搏数据。",
                "stale_message": "Beta 数据已过期，Alpha 清单仅供研究。",
                "columns": [
                    {"key": "beta_conclusion", "label": "Beta 结论"},
                    {"key": "decision_status", "label": "决策可用性"},
                    {"key": "regime", "label": "市场环境"},
                    {"key": "market_sentiment", "label": "A股情绪"},
                    {"key": "sentiment_index", "label": "情绪指数（-3~+3）"},
                    {"key": "equity_weight_percent", "label": "权益建议（%）"},
                    {"key": "risk_budget_percent", "label": "风险预算（%）"},
                    {"key": "alpha_usage", "label": "Alpha 使用方式"},
                    {"key": "observed_at", "label": "观测日期"},
                ],
            },
            {
                "key": "alpha-stock-ranking",
                "title": "二、Alpha 选股清单",
                "kind": "datagrid",
                "action_key": "dashboard.alpha-ranking",
                "max_rows": 10,
                "layout_area": "alpha_ranking",
                "user_priority": "p0",
                "presentation_semantic": "primary_list",
                "note": "排名回答模型看好谁；约束结果与不行动理由回答今天能不能推进。",
                "empty_message": "当前没有可展示的 Alpha 股票；请检查评分日、股票池或数据可靠性。",
                "error_message": "Alpha 选股清单加载失败。",
                "stale_message": "Alpha 评分已过期，仅供研究。",
                "columns": [
                    {"key": "rank", "label": "排名"},
                    {"key": "code", "label": "证券代码"},
                    {"key": "name", "label": "名称"},
                    {"key": "alpha_score", "label": "Alpha"},
                    {"key": "confidence", "label": "置信度"},
                    {"key": "stage_label", "label": "阶段"},
                    {"key": "gate_status", "label": "约束结果"},
                    {"key": "suggested_position_pct", "label": "建议仓位（%）"},
                    {"key": "buy_reason_summary", "label": "入选理由"},
                    {"key": "no_buy_reason_summary", "label": "不行动理由"},
                    {"key": "asof_date", "label": "评分日"},
                ],
            },
            {
                "key": "actionable-candidates",
                "title": "三、已触发候选（执行前复核）",
                "kind": "datagrid",
                "action_key": "alpha-trigger.candidate-actionable",
                "max_rows": 8,
                "layout_area": "triggered_candidates",
                "user_priority": "p1",
                "presentation_semantic": "supporting_list",
                "note": "这里只显示已进入触发流程的候选，不等同于完整 Alpha 排名。",
                "empty_message": "当前没有已触发候选；仍可查看上方 Alpha 排名。",
                "columns": [
                    {"key": "candidate_id", "label": "候选 ID"},
                    {"key": "asset_code", "label": "标的代码"},
                    {"key": "direction", "label": "方向"},
                    {"key": "strength", "label": "强度"},
                    {"key": "confidence", "label": "置信度"},
                    {"key": "status", "label": "状态"},
                    {"key": "risk_level", "label": "风险等级"},
                    {"key": "is_executed", "label": "已执行"},
                ],
                "row_actions": [
                    {
                        "action_key": "alpha-trigger.candidate-detail",
                        "label_template": "查看 {asset_code}",
                        "param_map": {"candidate_id": "candidate_id"},
                    }
                ],
            },
            {
                "key": "active-signals",
                "title": "四、活跃信号与证伪条件",
                "kind": "datagrid",
                "action_key": "signal.active",
                "max_rows": 8,
                "layout_area": "active_signals",
                "user_priority": "p2",
                "presentation_semantic": "supporting_list",
                "empty_message": "当前没有活跃信号。",
                "columns": [
                    {"key": "id", "label": "信号 ID"},
                    {"key": "asset_code", "label": "标的代码"},
                    {"key": "direction", "label": "方向"},
                    {"key": "logic_desc", "label": "投资逻辑"},
                    {"key": "invalidation_logic", "label": "证伪逻辑"},
                    {"key": "target_regime", "label": "目标环境"},
                    {"key": "status", "label": "状态"},
                    {"key": "rejection_reason", "label": "处理理由"},
                ],
                "row_actions": [
                    {
                        "action_key": "signal.update",
                        "label_template": "编辑 {asset_code}",
                        "param_map": {"signal_id": "id"},
                        "refresh_panel_key": "active-signals",
                    },
                    {
                        "action_key": "signal.approve",
                        "label_template": "批准 {asset_code}",
                        "param_map": {"signal_id": "id"},
                        "refresh_panel_key": "active-signals",
                    },
                    {
                        "action_key": "signal.reject",
                        "label_template": "拒绝 {asset_code}",
                        "param_map": {"signal_id": "id", "reason": "rejection_reason"},
                        "refresh_panel_key": "active-signals",
                    },
                    {
                        "action_key": "signal.invalidate",
                        "label_template": "证伪 {asset_code}",
                        "param_map": {"signal_id": "id", "reason": "rejection_reason"},
                        "refresh_panel_key": "active-signals",
                    },
                    {
                        "action_key": "signal.delete",
                        "label_template": "删除 {asset_code}",
                        "param_map": {"signal_id": "id"},
                        "refresh_panel_key": "active-signals",
                    },
                ],
            },
            {
                "key": "signal-create",
                "title": "五、记录新的投资观点",
                "kind": "detail",
                "action_key": "signal.create",
                "layout_area": "signal_create",
                "user_priority": "p2",
                "presentation_semantic": "next_step",
                "note": "需要记录新观点时，填写标的、方向、逻辑和证伪条件。",
                "empty_message": "点击“记录新的投资观点”开始填写。",
            },
        ],
    },
    "research.asset-lab": {
        "view_type": "detail",
        "default_action_key": "auto.api.get.api.asset-analysis.pool-summary",
        "user_experience": {
            "journey": "dashboard",
            "primary_task": "先看资产池和当前权重结论，再决定是否继续调整权重配置。",
            "primary_outcome": "明确当前资产池结构、当前权重状态，以及权重配置是否需要继续复核。",
            "empty_state_hint": "先看资产池概览，再看当前资产权重和权重配置状态。",
            "next_step_hint": "若资产池或权重状态异常，继续进入基金、板块和筛选器研究补证据。",
        },
        "business_context": {
            "objective": "先读资产池和当前权重，再决定今天研究应围绕哪些资产和配置问题展开。",
            "decision_output": "资产研究结论：当前资产池结构、配置倾向，以及是否需要进一步复核权重规则。",
            "checkpoints": [
                "先看资产池概览，确认当前可研究对象和结构分布。",
                "再看当前资产权重，确认配置是否偏离预期。",
                "最后看权重配置状态，确认规则层是否需要调整或继续复核。",
            ],
        },
        "dashboard_panels": [
            {
                "key": "asset-pool-summary",
                "title": "一、资产池概览",
                "kind": "detail",
                "action_key": "auto.api.get.api.asset-analysis.pool-summary",
                "max_rows": 6,
                "layout_area": "pool_summary",
                "target_screen": "research.asset-lab",
                "user_priority": "p0",
                "presentation_semantic": "primary_status",
            },
            {
                "key": "asset-current-weight",
                "title": "二、当前资产权重",
                "kind": "detail",
                "action_key": "auto.api.get.api.asset-analysis.current-weight",
                "max_rows": 6,
                "layout_area": "current_weight",
                "target_screen": "research.asset-lab",
                "user_priority": "p1",
                "presentation_semantic": "supporting_detail",
            },
            {
                "key": "asset-weight-configs",
                "title": "三、权重配置状态",
                "kind": "detail",
                "action_key": "auto.api.get.api.asset-analysis.weight-configs",
                "max_rows": 6,
                "layout_area": "weight_configs",
                "target_screen": "research.asset-lab",
                "user_priority": "p2",
                "presentation_semantic": "supporting_detail",
            },
        ],
    },
    "research.alpha-triggers": {
        "default_action_key": "alpha-trigger.candidate-actionable",
        "user_experience": {
            "journey": "dashboard",
            "primary_task": "先筛出今天最值得推进的候选，再决定继续跟进活跃触发器还是观察列表。",
            "primary_outcome": "明确今天应优先推进的候选，以及哪些触发器仍在延续或需要继续观察。",
            "empty_state_hint": "先看可操作候选，再核对活跃触发器和观察列表。",
            "next_step_hint": "若存在高优先级候选，继续进入标的研究、绩效复核或执行前检查。",
        },
        "business_context": {
            "objective": "先看可操作候选，再核对活跃触发器和观察列表，判断今天应该推进哪些研究动作。",
            "decision_output": "Alpha 触发结论：立即跟进、继续观察、等待触发或复核绩效。",
            "checkpoints": [
                "先看可操作候选，确认今天最值得推进的标的。",
                "再看活跃触发器和观察列表，确认触发背景是否延续。",
                "需要复核历史效果时再看触发器绩效。",
            ],
        },
        "dashboard_panels": [
            {
                "key": "alpha-triggers-actionable",
                "title": "一、可操作候选",
                "kind": "datagrid",
                "action_key": "alpha-trigger.candidate-actionable",
                "max_rows": 8,
                "layout_area": "actionable",
                "target_screen": "research.alpha-triggers",
                "user_priority": "p0",
                "presentation_semantic": "primary_list",
            },
            {
                "key": "alpha-triggers-active",
                "title": "二、活跃触发器",
                "kind": "datagrid",
                "action_key": "alpha-trigger.trigger-active",
                "max_rows": 6,
                "layout_area": "triggers",
                "target_screen": "research.alpha-triggers",
                "user_priority": "p1",
                "presentation_semantic": "supporting_list",
            },
            {
                "key": "alpha-triggers-watch-list",
                "title": "三、观察列表",
                "kind": "datagrid",
                "action_key": "alpha-trigger.candidate-watch-list",
                "max_rows": 6,
                "layout_area": "watch_list",
                "target_screen": "research.alpha-triggers",
                "user_priority": "p2",
                "presentation_semantic": "supporting_list",
            },
        ],
    },
}

RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_RESEARCH: dict[str, set[str]] = {
    "research.alpha-triggers": {"auto.api.get.api.alpha-triggers"},
    "research.signals": {
        "auto.api.get.api.filter",
        "auto.api.get.api.filter.indicators",
        "auto.api.get.api.filter.health",
        "param.api.get.api.filter.config.indicator_code",
        "param.api.get.api.filter.config.str.indicator_code",
    },
}
