"""Runtime TUI metadata for administrator user-access governance."""

from __future__ import annotations

from typing import Any

RUNTIME_USER_ACCESS_GOVERNANCE_SCREEN: dict[str, Any] = {
    "key": "identity-access.user-governance",
    "label": "用户准入治理",
    "module_key": "system-governance",
    "group": "system",
    "summary": "管理员筛选待处理用户，并完成批准、拒绝、状态重置和角色调整。",
    "view_type": "datagrid",
    "audience": "admin",
    "dashboard_layout": "task_flow",
    "default_action_key": "identity-access.user-list",
    "user_experience": {
        "journey": "admin",
        "primary_task": "处理待审批用户并维护其系统角色。",
        "primary_outcome": "所有待处理用户都有明确准入结论，已准入用户拥有正确角色。",
        "empty_state_hint": "先查看全部用户；若没有待审批项，再按用户名或邮箱搜索目标用户。",
        "next_step_hint": "准入完成后进入 MCP 用户接入治理，按需发放或回收接入令牌。",
    },
    "workflow": {
        "name": "身份与接入治理",
        "label": "用户准入",
        "role": "先决定用户是否可以进入系统，再分配最小必要角色。",
        "previous": {},
        "next": {"key": "capability-router.admin-access", "label": "MCP 用户接入治理"},
    },
    "business_context": {
        "objective": "把用户审批和角色分配收敛为可复核的管理员任务。",
        "decision_output": "批准、拒绝、重置或角色调整的明确回执。",
        "checkpoints": [
            "优先筛选待审批用户，核对用户名、邮箱和注册时间。",
            "拒绝时填写可追溯原因；已拒绝用户需要重新处理时先重置。",
            "批准后按最小权限原则选择角色，再进入 MCP 接入治理。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "user-access-list",
            "title": "一、用户准入队列",
            "kind": "datagrid",
            "action_key": "identity-access.user-list",
            "max_rows": 12,
            "layout_area": "users",
            "target_screen": "identity-access.user-governance",
            "columns": [
                {"key": "user_id", "label": "用户 ID"},
                {"key": "username", "label": "用户名"},
                {"key": "display_name", "label": "显示名称"},
                {"key": "email", "label": "邮箱"},
                {"key": "approval_status", "label": "准入状态"},
                {"key": "rbac_role", "label": "角色"},
                {"key": "created_at", "label": "注册时间"},
            ],
            "row_actions": [
                {
                    "action_key": "identity-access.approve-user",
                    "label_template": "批准 {username}",
                    "param_map": {"user_id": "user_id"},
                    "result_panel_key": "user-access-receipt",
                    "refresh_panel_key": "user-access-list",
                },
                {
                    "action_key": "identity-access.reject-user",
                    "label_template": "拒绝 {username}",
                    "param_map": {"user_id": "user_id"},
                    "result_panel_key": "user-access-receipt",
                    "refresh_panel_key": "user-access-list",
                },
                {
                    "action_key": "identity-access.reset-user",
                    "label_template": "重置 {username} 的准入状态",
                    "param_map": {"user_id": "user_id"},
                    "result_panel_key": "user-access-receipt",
                    "refresh_panel_key": "user-access-list",
                },
            ],
            "empty_message": "当前筛选条件下没有用户。",
            "error_message": "用户准入队列加载失败，请稍后重试。",
            "stale_message": "用户状态可能已经变化，请刷新后再操作。",
            "user_priority": "p0",
            "presentation_semantic": "primary_list",
        },
        {
            "key": "user-access-receipt",
            "title": "二、治理回执",
            "kind": "detail",
            "max_rows": 8,
            "layout_area": "receipt",
            "note": "批准、拒绝、重置与角色调整的结果显示在这里；操作后上方列表会自动刷新。",
            "empty_message": "从用户列表选择一项治理操作。",
            "user_priority": "p1",
            "presentation_semantic": "primary_status",
        },
    ],
}


RUNTIME_USER_ACCESS_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "identity-access.user-list",
        "label": "读取用户准入队列",
        "endpoint": "/api/account/admin/users/",
        "method": "GET",
        "intent": "list_admin_user_access_governance",
        "risk": "admin",
        "screen_key": "identity-access.user-governance",
        "module_key": "system-governance",
        "view_type": "datagrid",
        "description": "按状态或关键词筛选用户准入与角色信息。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 用户准入",
        "sequence": 100,
        "task_tier": "primary",
        "fields": [
            {
                "key": "approval_status",
                "label": "准入状态",
                "input_type": "select",
                "required": False,
                "default": "",
                "binding": "query",
                "value_type": "string",
                "options": ["", "pending", "approved", "auto_approved", "rejected"],
            },
            {
                "key": "q",
                "label": "关键词",
                "input_type": "text",
                "required": False,
                "default": "",
                "placeholder": "用户名、邮箱或显示名称",
                "binding": "query",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "datagrid", "rows_path": "rows", "total_path": "total_count"},
        "result_semantics": ["primary_list"],
    },
    {
        "key": "identity-access.approve-user",
        "label": "批准用户",
        "endpoint": "/api/account/admin/users/<int:user_id>/approve/",
        "method": "POST",
        "intent": "approve_admin_managed_user",
        "risk": "admin",
        "effect": "update",
        "screen_key": "identity-access.user-governance",
        "module_key": "system-governance",
        "view_type": "detail",
        "description": "批准一个待审批用户并启用其系统访问。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 用户准入",
        "sequence": 110,
        "task_tier": "operation",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
                "presentation_semantic": "primary_selector",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message", "status_path": "success"},
        "result_semantics": ["primary_status"],
    },
    {
        "key": "identity-access.reject-user",
        "label": "拒绝用户",
        "endpoint": "/api/account/admin/users/<int:user_id>/reject/",
        "method": "POST",
        "intent": "reject_admin_managed_user",
        "risk": "admin",
        "effect": "update",
        "screen_key": "identity-access.user-governance",
        "module_key": "system-governance",
        "view_type": "detail",
        "description": "拒绝一个待审批用户并记录原因。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 用户准入",
        "sequence": 120,
        "task_tier": "operation",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
                "presentation_semantic": "primary_selector",
            },
            {
                "key": "rejection_reason",
                "label": "拒绝原因",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "detail", "title_path": "message", "status_path": "success"},
        "result_semantics": ["primary_status"],
    },
    {
        "key": "identity-access.reset-user",
        "label": "重置用户准入状态",
        "endpoint": "/api/account/admin/users/<int:user_id>/reset/",
        "method": "POST",
        "intent": "reset_admin_managed_user_approval",
        "risk": "admin",
        "effect": "update",
        "screen_key": "identity-access.user-governance",
        "module_key": "system-governance",
        "view_type": "detail",
        "description": "把用户重置为待审批并撤销其现有访问。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 用户准入",
        "sequence": 130,
        "task_tier": "operation",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
                "presentation_semantic": "primary_selector",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message", "status_path": "success"},
        "result_semantics": ["primary_status"],
    },
    {
        "key": "identity-access.set-user-role",
        "label": "设置用户角色",
        "endpoint": "/api/account/admin/users/<int:user_id>/role/",
        "method": "POST",
        "intent": "set_admin_managed_user_role",
        "risk": "admin",
        "effect": "update",
        "screen_key": "identity-access.user-governance",
        "module_key": "system-governance",
        "view_type": "detail",
        "description": "按最小权限原则设置一个用户的系统角色。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 用户准入",
        "sequence": 140,
        "task_tier": "operation",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
                "presentation_semantic": "primary_selector",
            },
            {
                "key": "rbac_role",
                "label": "角色",
                "input_type": "select",
                "required": True,
                "binding": "body",
                "value_type": "string",
                "options": [
                    "admin",
                    "owner",
                    "analyst",
                    "investment_manager",
                    "trader",
                    "risk",
                    "read_only",
                ],
                "presentation_semantic": "identifier",
            },
        ],
        "view_model": {"kind": "detail", "title_path": "message", "status_path": "success"},
        "result_semantics": ["primary_status"],
    },
)
