"""Runtime TUI metadata for hedge-pair, snapshot, and alert workflows."""

from __future__ import annotations

from typing import Any

from apps.hedge.domain.entities import HedgeMethod

_SCREEN = "macro-regime.strategy"
_MODULE = "macro-strategy"
_SOURCE = "approved:runtime-hedge"


def _path_id(key: str, label: str) -> dict[str, Any]:
    """Build one positive integer path identifier."""

    return {
        "key": key,
        "label": label,
        "binding": "path",
        "input_type": "number",
        "value_type": "integer",
        "required": True,
        "min": 1,
    }


def _number(
    key: str,
    label: str,
    *,
    required: bool,
    minimum: int | float | None = None,
    maximum: int | float | None = None,
    default: int | float | None = None,
    value_type: str = "float",
) -> dict[str, Any]:
    """Build one bounded hedge input."""

    field: dict[str, Any] = {
        "key": key,
        "label": label,
        "binding": "body",
        "input_type": "number",
        "value_type": value_type,
        "required": required,
    }
    if minimum is not None:
        field["min"] = minimum
    if maximum is not None:
        field["max"] = maximum
    if default is not None:
        field["default"] = default
    return field


def _pair_fields(*, required: bool) -> list[dict[str, Any]]:
    """Build the complete hedge-pair configuration form."""

    return [
        {
            "key": "name",
            "label": "对冲对名称",
            "binding": "body",
            "input_type": "text",
            "value_type": "string",
            "required": required,
            "max": 100,
        },
        {
            "key": "long_asset",
            "label": "多头资产代码",
            "binding": "body",
            "input_type": "text",
            "value_type": "string",
            "required": required,
            "max": 20,
        },
        {
            "key": "hedge_asset",
            "label": "对冲资产代码",
            "binding": "body",
            "input_type": "text",
            "value_type": "string",
            "required": required,
            "max": 20,
        },
        {
            "key": "hedge_method",
            "label": "对冲方法",
            "binding": "body",
            "input_type": "select",
            "value_type": "string",
            "required": required,
            "default": HedgeMethod.BETA.value,
            "options": [method.value for method in HedgeMethod],
        },
        _number(
            "target_long_weight",
            "目标多头权重",
            required=required,
            minimum=0,
            maximum=1,
            default=0.7,
        ),
        _number(
            "target_hedge_weight",
            "目标对冲权重",
            required=required,
            minimum=0,
            maximum=1,
            default=0.3,
        ),
        _number(
            "rebalance_trigger",
            "调仓触发阈值",
            required=required,
            minimum=0,
            maximum=1,
            default=0.05,
        ),
        _number(
            "correlation_window",
            "相关性窗口（天）",
            required=required,
            minimum=2,
            maximum=5000,
            default=60,
            value_type="integer",
        ),
        _number(
            "min_correlation",
            "最小相关性",
            required=required,
            minimum=-1,
            maximum=1,
            default=-0.3,
        ),
        _number(
            "max_correlation",
            "最大相关性",
            required=required,
            minimum=-1,
            maximum=1,
            default=-0.9,
        ),
        _number(
            "correlation_alert_threshold",
            "相关性告警阈值",
            required=required,
            minimum=0,
            maximum=2,
            default=0.2,
        ),
        _number(
            "max_hedge_cost",
            "最大对冲成本",
            required=required,
            minimum=0,
            maximum=1,
            default=0.05,
        ),
        _number(
            "beta_target",
            "目标 Beta",
            required=False,
            minimum=-10,
            maximum=10,
        ),
        {
            "key": "is_active",
            "label": "启用状态",
            "binding": "body",
            "input_type": "checkbox",
            "value_type": "boolean",
            "required": False,
            "default": True,
        },
    ]


def _mutation(
    *,
    key: str,
    label: str,
    endpoint: str,
    method: str,
    intent: str,
    sequence: int,
    fields: list[dict[str, Any]],
    audience: str,
    effect: str,
    description: str,
    view_type: str = "detail",
) -> dict[str, Any]:
    """Build one confirmed hedge operation."""

    return {
        "key": key,
        "label": label,
        "endpoint": endpoint,
        "method": method,
        "intent": intent,
        "risk": "admin" if audience == "admin" else "write",
        "audience": audience,
        "effect": effect,
        "confirmation_required": True,
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": view_type,
        "description": description,
        "source": _SOURCE,
        "task_group": "08 对冲治理",
        "sequence": sequence,
        "task_tier": "support",
        "fields": fields,
        "view_model": {
            "kind": view_type,
            "title_path": "name",
            "status_path": "status",
        },
    }


RUNTIME_HEDGE_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "hedge.pair-list",
        "label": "查看对冲对",
        "endpoint": "/api/hedge/pairs/",
        "method": "GET",
        "intent": "list_hedge_pairs",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "datagrid",
        "description": "按启用状态、对冲方法或关键字查看对冲配置。",
        "source": _SOURCE,
        "task_group": "08 对冲治理",
        "sequence": 880,
        "task_tier": "support",
        "fields": [
            {
                "key": "is_active",
                "label": "仅看启用状态",
                "binding": "query",
                "input_type": "checkbox",
                "value_type": "boolean",
                "required": False,
            },
            {
                "key": "hedge_method",
                "label": "对冲方法",
                "binding": "query",
                "input_type": "select",
                "value_type": "string",
                "required": False,
                "options": [method.value for method in HedgeMethod],
            },
            {
                "key": "search",
                "label": "搜索名称或资产代码",
                "binding": "query",
                "input_type": "text",
                "value_type": "string",
                "required": False,
            },
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "results",
            "columns": [
                {"key": "id", "label": "ID"},
                {"key": "name", "label": "对冲对"},
                {"key": "long_asset", "label": "多头资产"},
                {"key": "hedge_asset", "label": "对冲资产"},
                {"key": "hedge_method", "label": "方法"},
                {"key": "target_long_weight", "label": "多头权重"},
                {"key": "target_hedge_weight", "label": "对冲权重"},
                {"key": "is_active", "label": "已启用"},
            ],
        },
    },
    {
        "key": "hedge.pair-detail",
        "label": "查看对冲对详情",
        "endpoint": "/api/hedge/pairs/<int:pair_id>/",
        "method": "GET",
        "intent": "read_hedge_pair",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "查看完整对冲参数、相关性窗口和风险上限。",
        "source": _SOURCE,
        "task_group": "08 对冲治理",
        "sequence": 890,
        "task_tier": "support",
        "fields": [_path_id("pair_id", "对冲对 ID")],
        "view_model": {
            "kind": "detail",
            "title_path": "name",
            "status_path": "is_active",
        },
    },
    _mutation(
        key="hedge.pair-create",
        label="新建对冲对",
        endpoint="/api/hedge/pairs/",
        method="POST",
        intent="create_hedge_pair",
        sequence=900,
        fields=_pair_fields(required=True),
        audience="admin",
        effect="create",
        description="创建具有完整权重、相关性与成本约束的对冲配置。",
    ),
    _mutation(
        key="hedge.pair-update",
        label="更新对冲对",
        endpoint="/api/hedge/pairs/<int:pair_id>/",
        method="PATCH",
        intent="update_hedge_pair",
        sequence=910,
        fields=[_path_id("pair_id", "对冲对 ID"), *_pair_fields(required=False)],
        audience="admin",
        effect="update",
        description="按 ID 局部更新对冲配置。",
    ),
    _mutation(
        key="hedge.pair-activate",
        label="启用对冲对",
        endpoint="/api/hedge/pairs/<int:pair_id>/activate/",
        method="POST",
        intent="activate_hedge_pair",
        sequence=920,
        fields=[_path_id("pair_id", "对冲对 ID")],
        audience="admin",
        effect="update",
        description="启用指定对冲对。",
    ),
    _mutation(
        key="hedge.pair-deactivate",
        label="停用对冲对",
        endpoint="/api/hedge/pairs/<int:pair_id>/deactivate/",
        method="POST",
        intent="deactivate_hedge_pair",
        sequence=930,
        fields=[_path_id("pair_id", "对冲对 ID")],
        audience="admin",
        effect="update",
        description="停用指定对冲对。",
    ),
    _mutation(
        key="hedge.pair-effectiveness",
        label="检查对冲有效性",
        endpoint="/api/hedge/pairs/<int:pair_id>/check_effectiveness/",
        method="POST",
        intent="check_hedge_effectiveness",
        sequence=940,
        fields=[_path_id("pair_id", "对冲对 ID")],
        audience="authenticated",
        effect="execute",
        description="只读计算指定对冲对的风险降低和有效性。",
    ),
    _mutation(
        key="hedge.pair-delete",
        label="删除对冲对",
        endpoint="/api/hedge/pairs/<int:pair_id>/",
        method="DELETE",
        intent="delete_hedge_pair",
        sequence=950,
        fields=[_path_id("pair_id", "对冲对 ID")],
        audience="admin",
        effect="delete",
        description="永久删除指定对冲对。",
    ),
    {
        "key": "hedge.snapshot-list",
        "label": "查看对冲快照",
        "endpoint": "/api/hedge/snapshots/",
        "method": "GET",
        "intent": "list_hedge_snapshots",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "datagrid",
        "description": "按对冲对、交易日与再平衡状态查看组合快照。",
        "source": _SOURCE,
        "task_group": "08 对冲治理",
        "sequence": 960,
        "task_tier": "support",
        "fields": [
            {
                "key": "pair",
                "label": "对冲对 ID",
                "binding": "query",
                "input_type": "number",
                "value_type": "integer",
                "required": False,
                "min": 1,
            },
            {
                "key": "trade_date",
                "label": "交易日",
                "binding": "query",
                "input_type": "date",
                "value_type": "date",
                "required": False,
            },
            {
                "key": "rebalance_needed",
                "label": "仅看需再平衡",
                "binding": "query",
                "input_type": "checkbox",
                "value_type": "boolean",
                "required": False,
            },
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "results",
            "columns": [
                {"key": "trade_date", "label": "交易日"},
                {"key": "pair_name", "label": "对冲对"},
                {"key": "current_correlation", "label": "当前相关性"},
                {"key": "hedge_ratio", "label": "对冲比率"},
                {"key": "portfolio_beta", "label": "组合 Beta"},
                {"key": "portfolio_volatility", "label": "组合波动率"},
                {"key": "hedge_effectiveness", "label": "对冲有效性"},
                {"key": "rebalance_needed", "label": "需再平衡"},
            ],
        },
    },
    {
        "key": "hedge.snapshot-latest",
        "label": "查看各对冲对最新快照",
        "endpoint": "/api/hedge/snapshots/latest/",
        "method": "GET",
        "intent": "read_latest_hedge_snapshots",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "datagrid",
        "description": "查看每个对冲对的最新风险与有效性状态。",
        "source": _SOURCE,
        "task_group": "08 对冲治理",
        "sequence": 970,
        "task_tier": "support",
        "fields": [],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "",
            "columns": [
                {"key": "pair_name", "label": "对冲对"},
                {"key": "trade_date", "label": "交易日"},
                {"key": "hedge_effectiveness", "label": "对冲有效性"},
                {"key": "rebalance_needed", "label": "需再平衡"},
            ],
        },
    },
    _mutation(
        key="hedge.snapshot-update-all",
        label="更新全部对冲快照",
        endpoint="/api/hedge/snapshots/update_all/",
        method="POST",
        intent="update_all_hedge_snapshots",
        sequence=980,
        fields=[],
        audience="admin",
        effect="execute",
        description="按当前市场数据更新全部启用对冲对的组合快照。",
    ),
    {
        "key": "hedge.alert-list",
        "label": "查看对冲告警",
        "endpoint": "/api/hedge/alerts/",
        "method": "GET",
        "intent": "list_hedge_alerts",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "datagrid",
        "description": "按对冲对、日期、类型、严重度和解决状态查看告警。",
        "source": _SOURCE,
        "task_group": "08 对冲治理",
        "sequence": 990,
        "task_tier": "support",
        "fields": [
            {
                "key": "pair_name",
                "label": "对冲对名称",
                "binding": "query",
                "input_type": "text",
                "value_type": "string",
                "required": False,
            },
            {
                "key": "alert_date",
                "label": "告警日期",
                "binding": "query",
                "input_type": "date",
                "value_type": "date",
                "required": False,
            },
            {
                "key": "severity",
                "label": "严重度",
                "binding": "query",
                "input_type": "text",
                "value_type": "string",
                "required": False,
            },
            {
                "key": "is_resolved",
                "label": "仅看已解决",
                "binding": "query",
                "input_type": "checkbox",
                "value_type": "boolean",
                "required": False,
            },
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "results",
            "columns": [
                {"key": "alert_date", "label": "日期"},
                {"key": "pair_name", "label": "对冲对"},
                {"key": "alert_type", "label": "类型"},
                {"key": "severity", "label": "严重度"},
                {"key": "message", "label": "告警"},
                {"key": "current_value", "label": "当前值"},
                {"key": "threshold_value", "label": "阈值"},
                {"key": "is_resolved", "label": "已解决"},
            ],
        },
    },
    {
        "key": "hedge.alert-active",
        "label": "查看近期未解决告警",
        "endpoint": "/api/hedge/alerts/active/",
        "method": "GET",
        "intent": "read_active_hedge_alerts",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "datagrid",
        "description": "按回看天数查看近期未解决告警。",
        "source": _SOURCE,
        "task_group": "08 对冲治理",
        "sequence": 1000,
        "task_tier": "support",
        "fields": [
            {
                "key": "days",
                "label": "回看天数",
                "binding": "query",
                "input_type": "number",
                "value_type": "integer",
                "required": False,
                "default": 7,
                "min": 1,
                "max": 3650,
            }
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "",
            "columns": [
                {"key": "alert_date", "label": "日期"},
                {"key": "pair_name", "label": "对冲对"},
                {"key": "severity", "label": "严重度"},
                {"key": "message", "label": "告警"},
                {"key": "action_required", "label": "建议动作"},
                {"key": "action_priority", "label": "优先级"},
            ],
        },
    },
    _mutation(
        key="hedge.alert-monitor",
        label="运行对冲监控",
        endpoint="/api/hedge/alerts/monitor/",
        method="POST",
        intent="monitor_hedge_pairs",
        sequence=1010,
        fields=[],
        audience="admin",
        effect="execute",
        description="检查启用对冲对并生成新的风险告警。",
    ),
    _mutation(
        key="hedge.alert-resolve",
        label="解决对冲告警",
        endpoint="/api/hedge/alerts/<int:alert_id>/resolve/",
        method="POST",
        intent="resolve_hedge_alert",
        sequence=1020,
        fields=[_path_id("alert_id", "告警 ID")],
        audience="admin",
        effect="update",
        description="将指定告警标记为已解决。",
    ),
)
