"""Runtime TUI metadata for current-user account settings."""

from __future__ import annotations

from typing import Any

RUNTIME_ACCOUNT_SELF_SERVICE_SCREEN: dict[str, Any] = {
    "key": "account.self-service",
    "dashboard_layout": "task_flow",
    "workflow": {
        "name": "账户自助",
        "label": "个人资料与交易设置",
        "role": "先核对个人资料，再维护资金流水和交易成本。",
        "previous": {"key": "execution.accounts", "label": "账户与持仓"},
        "next": {},
    },
    "business_context": {
        "objective": "在 TUI 内完成本人账户设置，不依赖 Classic 表单。",
        "decision_output": "个人资料、资金流水与交易成本的最新状态和写入回执。",
        "checkpoints": [
            "核对显示名称、邮箱、风险偏好和角色。",
            "修改密码时必须再次输入当前密码，并使用符合策略的新密码。",
            "新增资金流水和费率配置前确认投资组合 ID 属于当前用户。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "account-profile",
            "title": "一、个人资料",
            "kind": "detail",
            "action_key": "account-settings.read-profile",
            "max_rows": 8,
            "layout_area": "profile",
            "target_screen": "account.self-service",
            "empty_message": "暂无个人资料。",
            "user_priority": "p0",
            "presentation_semantic": "primary_status",
        },
        {
            "key": "capital-flows",
            "title": "二、资金流水",
            "kind": "datagrid",
            "action_key": "account-settings.list-capital-flows",
            "max_rows": 10,
            "layout_area": "capital-flows",
            "target_screen": "account.self-service",
            "columns": [
                {"key": "id", "label": "流水 ID"},
                {"key": "portfolio_name", "label": "投资组合"},
                {"key": "flow_type", "label": "类型"},
                {"key": "amount", "label": "金额"},
                {"key": "flow_date", "label": "日期"},
                {"key": "notes", "label": "备注"},
            ],
            "row_actions": [
                {
                    "action_key": "account-settings.delete-capital-flow",
                    "label_template": "删除流水 {id}",
                    "param_map": {"pk": "id"},
                    "result_panel_key": "account-settings-receipt",
                    "refresh_panel_key": "capital-flows",
                }
            ],
            "empty_message": "当前没有资金流水。",
            "user_priority": "p1",
            "presentation_semantic": "supporting_list",
        },
        {
            "key": "trading-costs",
            "title": "三、交易成本",
            "kind": "datagrid",
            "action_key": "account-settings.list-trading-costs",
            "max_rows": 6,
            "layout_area": "trading-costs",
            "target_screen": "account.self-service",
            "empty_message": "当前没有交易成本配置。",
            "user_priority": "p1",
            "presentation_semantic": "supporting_list",
        },
        {
            "key": "account-settings-receipt",
            "title": "四、设置回执",
            "kind": "detail",
            "max_rows": 8,
            "layout_area": "receipt",
            "empty_message": "从任务区选择资料、密码、流水或费率操作。",
            "user_priority": "p2",
            "presentation_semantic": "primary_status",
        },
    ],
}


RUNTIME_ACCOUNT_SELF_SERVICE_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "account-settings.read-profile",
        "label": "读取我的资料",
        "endpoint": "/api/account/profile/",
        "method": "GET",
        "intent": "read_current_user_account_profile",
        "risk": "read",
        "screen_key": "account.self-service",
        "module_key": "research-tools",
        "view_type": "detail",
        "description": "读取当前用户的显示名称、邮箱、风险偏好和角色。",
        "source": "approved:runtime-account-self-service",
        "task_group": "01 个人资料",
        "sequence": 100,
        "task_tier": "primary",
        "fields": [],
        "view_model": {
            "kind": "detail",
            "title_path": "display_name",
            "status_path": "risk_tolerance",
        },
        "result_semantics": ["primary_status"],
    },
    {
        "key": "account-settings.update-profile",
        "label": "更新我的资料",
        "endpoint": "/api/account/profile/",
        "method": "PUT",
        "intent": "update_current_user_account_profile",
        "risk": "write",
        "effect": "update",
        "screen_key": "account.self-service",
        "module_key": "research-tools",
        "view_type": "detail",
        "description": "更新当前用户的显示名称、邮箱和风险偏好。",
        "source": "approved:runtime-account-self-service",
        "task_group": "01 个人资料",
        "sequence": 110,
        "task_tier": "operation",
        "fields": [
            {
                "key": "display_name",
                "label": "显示名称",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "email",
                "label": "邮箱",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "risk_tolerance",
                "label": "风险偏好",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "string",
                "options": [
                    {"value": "conservative", "label": "保守型"},
                    {"value": "moderate", "label": "稳健型"},
                    {"value": "aggressive", "label": "激进型"},
                ],
            },
        ],
        "view_model": {
            "kind": "detail",
            "title_path": "display_name",
            "status_path": "risk_tolerance",
        },
        "result_semantics": ["primary_status"],
    },
    {
        "key": "account-settings.change-password",
        "label": "修改我的密码",
        "endpoint": "/api/account/profile/password/",
        "method": "POST",
        "intent": "change_current_user_password",
        "risk": "write",
        "effect": "update",
        "confirmation_required": True,
        "screen_key": "account.self-service",
        "module_key": "research-tools",
        "view_type": "detail",
        "description": "再次验证当前密码后设置符合安全策略的新密码。",
        "source": "approved:runtime-account-self-service",
        "task_group": "01 个人资料",
        "sequence": 120,
        "task_tier": "operation",
        "fields": [
            {
                "key": "current_password",
                "label": "当前密码",
                "input_type": "password",
                "required": True,
                "binding": "body",
                "value_type": "string",
                "presentation_semantic": "api_token",
            },
            {
                "key": "new_password",
                "label": "新密码",
                "input_type": "password",
                "required": True,
                "binding": "body",
                "value_type": "string",
                "presentation_semantic": "api_token",
            },
        ],
        "view_model": {"kind": "detail", "title_path": "message", "status_path": "success"},
        "result_semantics": ["primary_status"],
    },
    {
        "key": "account-settings.list-capital-flows",
        "label": "读取资金流水",
        "endpoint": "/api/account/capital-flows/",
        "method": "GET",
        "intent": "list_current_user_capital_flows",
        "risk": "read",
        "screen_key": "account.self-service",
        "module_key": "research-tools",
        "view_type": "datagrid",
        "description": "读取当前用户投资组合的入金和出金记录。",
        "source": "approved:runtime-account-self-service",
        "task_group": "02 资金流水",
        "sequence": 200,
        "task_tier": "primary",
        "fields": [],
    },
    {
        "key": "account-settings.create-capital-flow",
        "label": "新增资金流水",
        "endpoint": "/api/account/capital-flows/",
        "method": "POST",
        "intent": "create_current_user_capital_flow",
        "risk": "write",
        "effect": "create",
        "screen_key": "account.self-service",
        "module_key": "research-tools",
        "view_type": "detail",
        "description": "为本人拥有的投资组合记录一笔入金或出金。",
        "source": "approved:runtime-account-self-service",
        "task_group": "02 资金流水",
        "sequence": 210,
        "task_tier": "operation",
        "fields": [
            {
                "key": "portfolio",
                "label": "投资组合 ID",
                "input_type": "number",
                "required": True,
                "binding": "body",
                "value_type": "integer",
                "presentation_semantic": "primary_selector",
            },
            {
                "key": "flow_type",
                "label": "流水类型",
                "input_type": "select",
                "required": True,
                "binding": "body",
                "value_type": "string",
                "options": [
                    {"value": "deposit", "label": "入金"},
                    {"value": "withdraw", "label": "出金"},
                ],
            },
            {
                "key": "amount",
                "label": "金额",
                "input_type": "number",
                "required": True,
                "binding": "body",
                "value_type": "decimal",
            },
            {
                "key": "flow_date",
                "label": "日期",
                "input_type": "date",
                "required": True,
                "binding": "body",
                "value_type": "date",
            },
            {
                "key": "notes",
                "label": "备注",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
        ],
    },
    {
        "key": "account-settings.delete-capital-flow",
        "label": "删除资金流水",
        "endpoint": "/api/account/capital-flows/<pk>/",
        "method": "DELETE",
        "intent": "delete_current_user_capital_flow",
        "risk": "write",
        "effect": "delete",
        "confirmation_required": True,
        "screen_key": "account.self-service",
        "module_key": "research-tools",
        "view_type": "detail",
        "description": "删除本人投资组合中的一笔资金流水。",
        "source": "approved:runtime-account-self-service",
        "task_group": "02 资金流水",
        "sequence": 220,
        "task_tier": "support",
        "fields": [
            {
                "key": "pk",
                "label": "流水 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
                "presentation_semantic": "primary_selector",
            }
        ],
    },
    {
        "key": "account-settings.list-trading-costs",
        "label": "读取交易成本",
        "endpoint": "/api/account/trading-cost-configs/",
        "method": "GET",
        "intent": "list_current_user_trading_cost_configs",
        "risk": "read",
        "screen_key": "account.self-service",
        "module_key": "research-tools",
        "view_type": "datagrid",
        "description": "读取本人投资组合的佣金、印花税和过户费配置。",
        "source": "approved:runtime-account-self-service",
        "task_group": "03 交易成本",
        "sequence": 300,
        "task_tier": "primary",
        "fields": [],
    },
    {
        "key": "account-settings.create-trading-cost",
        "label": "新增交易成本配置",
        "endpoint": "/api/account/trading-cost-configs/",
        "method": "POST",
        "intent": "create_current_user_trading_cost_config",
        "risk": "write",
        "effect": "create",
        "screen_key": "account.self-service",
        "module_key": "research-tools",
        "view_type": "detail",
        "description": "为本人拥有的投资组合创建交易成本配置。",
        "source": "approved:runtime-account-self-service",
        "task_group": "03 交易成本",
        "sequence": 310,
        "task_tier": "operation",
        "fields": [
            {
                "key": "portfolio",
                "label": "投资组合 ID",
                "input_type": "number",
                "required": True,
                "binding": "body",
                "value_type": "integer",
                "presentation_semantic": "primary_selector",
            },
            {
                "key": "commission_rate",
                "label": "佣金率",
                "input_type": "number",
                "required": True,
                "binding": "body",
                "value_type": "decimal",
            },
            {
                "key": "min_commission",
                "label": "最低佣金",
                "input_type": "number",
                "required": True,
                "binding": "body",
                "value_type": "decimal",
            },
            {
                "key": "stamp_duty_rate",
                "label": "印花税率",
                "input_type": "number",
                "required": True,
                "binding": "body",
                "value_type": "decimal",
            },
            {
                "key": "transfer_fee_rate",
                "label": "过户费率",
                "input_type": "number",
                "required": True,
                "binding": "body",
                "value_type": "decimal",
            },
            {
                "key": "is_active",
                "label": "立即启用",
                "input_type": "checkbox",
                "required": False,
                "default": True,
                "binding": "body",
                "value_type": "boolean",
            },
        ],
    },
)
