"""Runtime TUI metadata for the backtest task flow."""

from __future__ import annotations

from typing import Any

_BACKTEST_SCREEN = "research.asset-lab"
_BACKTEST_MODULE = "research-tools"
_SOURCE = "approved:runtime-backtest"

RUNTIME_BACKTEST_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "backtest.summary",
        "label": "查看回测统计",
        "endpoint": "/api/backtest/statistics/",
        "method": "GET",
        "intent": "read_backtest_statistics",
        "risk": "read",
        "screen_key": _BACKTEST_SCREEN,
        "module_key": _BACKTEST_MODULE,
        "view_type": "status",
        "description": "查看回测数量、状态分布和收益区间。",
        "source": _SOURCE,
        "task_group": "03 回测研究",
        "sequence": 320,
        "task_tier": "support",
        "fields": [],
        "view_model": {"kind": "detail"},
    },
    {
        "key": "backtest.list",
        "label": "查看回测列表",
        "endpoint": "/api/backtest/backtests/",
        "method": "GET",
        "intent": "browse_backtest_records",
        "risk": "read",
        "screen_key": _BACKTEST_SCREEN,
        "module_key": _BACKTEST_MODULE,
        "view_type": "datagrid",
        "description": "按状态查看近期回测任务和结果摘要。",
        "source": _SOURCE,
        "task_group": "03 回测研究",
        "sequence": 330,
        "task_tier": "support",
        "fields": [
            {
                "key": "status",
                "label": "状态",
                "input_type": "select",
                "required": False,
                "binding": "query",
                "value_type": "string",
                "options": ["", "pending", "running", "completed", "failed"],
            },
            {
                "key": "limit",
                "label": "返回数量",
                "input_type": "number",
                "required": False,
                "default": "20",
                "binding": "query",
                "value_type": "integer",
            },
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "backtests",
            "total_path": "total_count",
            "columns": [
                {"key": "id", "label": "ID"},
                {"key": "name", "label": "名称"},
                {"key": "status", "label": "状态"},
                {"key": "start_date", "label": "开始日期"},
                {"key": "end_date", "label": "结束日期"},
                {"key": "total_return", "label": "总收益"},
                {"key": "annualized_return", "label": "年化收益"},
                {"key": "created_at", "label": "创建时间"},
            ],
        },
    },
    {
        "key": "backtest.detail",
        "label": "查看回测详情",
        "endpoint": "/api/backtest/backtests/<pk>/",
        "method": "GET",
        "intent": "read_backtest_detail",
        "risk": "read",
        "screen_key": _BACKTEST_SCREEN,
        "module_key": _BACKTEST_MODULE,
        "view_type": "detail",
        "description": "查看一个回测的配置、状态、指标和结果。",
        "source": _SOURCE,
        "task_group": "03 回测研究",
        "sequence": 340,
        "task_tier": "support",
        "fields": [
            {
                "key": "pk",
                "label": "回测 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {
            "kind": "detail",
            "title_path": "name",
            "status_path": "status",
        },
    },
    {
        "key": "backtest.run",
        "label": "运行新回测",
        "endpoint": "/api/backtest/backtests/",
        "method": "POST",
        "intent": "run_backtest",
        "risk": "write",
        "effect": "execute",
        "confirmation_required": True,
        "screen_key": _BACKTEST_SCREEN,
        "module_key": _BACKTEST_MODULE,
        "view_type": "detail",
        "description": "按时间范围、资金和研究可信度配置运行回测。",
        "source": _SOURCE,
        "task_group": "03 回测研究",
        "sequence": 350,
        "task_tier": "support",
        "fields": [
            {
                "key": "name",
                "label": "回测名称",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "start_date",
                "label": "开始日期",
                "input_type": "date",
                "required": True,
                "binding": "body",
                "value_type": "date",
            },
            {
                "key": "end_date",
                "label": "结束日期",
                "input_type": "date",
                "required": True,
                "binding": "body",
                "value_type": "date",
            },
            {
                "key": "initial_capital",
                "label": "初始资金",
                "input_type": "number",
                "required": True,
                "default": "100000",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "rebalance_frequency",
                "label": "再平衡频率",
                "input_type": "select",
                "required": True,
                "default": "monthly",
                "binding": "body",
                "value_type": "string",
                "options": ["monthly", "quarterly", "yearly"],
            },
            {
                "key": "transaction_cost_bps",
                "label": "交易成本（bp）",
                "input_type": "number",
                "required": False,
                "default": "10",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "use_pit_data",
                "label": "使用 Point-in-Time 数据",
                "input_type": "checkbox",
                "required": False,
                "default": False,
                "binding": "body",
                "value_type": "boolean",
            },
            {
                "key": "trust_status",
                "label": "研究可信度",
                "input_type": "select",
                "required": False,
                "default": "exploratory",
                "binding": "body",
                "value_type": "string",
                "options": ["exploratory", "pit_verified"],
            },
            {
                "key": "data_manifest_id",
                "label": "数据清单 ID",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "config_hash",
                "label": "配置哈希",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "code_commit",
                "label": "代码提交",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "engine_version",
                "label": "引擎版本",
                "input_type": "text",
                "required": False,
                "default": "backtest-v1",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "research_trial_id",
                "label": "研究试验 ID",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "decision_snapshot_id",
                "label": "决策快照 ID",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "run_async",
                "label": "后台运行",
                "input_type": "checkbox",
                "required": False,
                "default": True,
                "binding": "body",
                "value_type": "boolean",
            },
        ],
        "view_model": {
            "kind": "detail",
            "title_path": "backtest_id",
            "status_path": "status",
        },
    },
    {
        "key": "backtest.rerun",
        "label": "重新运行回测",
        "endpoint": "/api/backtest/backtests/<pk>/rerun/",
        "method": "POST",
        "intent": "rerun_backtest",
        "risk": "write",
        "effect": "execute",
        "confirmation_required": True,
        "screen_key": _BACKTEST_SCREEN,
        "module_key": _BACKTEST_MODULE,
        "view_type": "detail",
        "description": "重新运行一个已存在的回测。",
        "source": _SOURCE,
        "task_group": "03 回测研究",
        "sequence": 360,
        "task_tier": "support",
        "fields": [
            {
                "key": "pk",
                "label": "回测 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "backtest.apply",
        "label": "应用回测结果到持仓",
        "endpoint": "/api/account/backtests/<backtest_id>/apply/",
        "method": "POST",
        "intent": "apply_backtest_to_portfolio",
        "risk": "write",
        "effect": "create",
        "confirmation_required": True,
        "screen_key": _BACKTEST_SCREEN,
        "module_key": _BACKTEST_MODULE,
        "view_type": "detail",
        "description": "按缩放因子把回测最终持仓应用到当前用户的持仓。",
        "source": _SOURCE,
        "task_group": "03 回测研究",
        "sequence": 370,
        "task_tier": "support",
        "fields": [
            {
                "key": "backtest_id",
                "label": "回测 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "scale_factor",
                "label": "仓位缩放因子",
                "input_type": "number",
                "required": False,
                "default": "1.0",
                "binding": "body",
                "value_type": "float",
            },
        ],
        "view_model": {
            "kind": "detail",
            "title_path": "message",
            "status_path": "success",
        },
    },
    {
        "key": "backtest.delete",
        "label": "删除回测",
        "endpoint": "/api/backtest/backtests/<pk>/",
        "method": "DELETE",
        "intent": "delete_backtest",
        "risk": "write",
        "effect": "delete",
        "confirmation_required": True,
        "screen_key": _BACKTEST_SCREEN,
        "module_key": _BACKTEST_MODULE,
        "view_type": "detail",
        "description": "永久删除一个回测记录。",
        "source": _SOURCE,
        "task_group": "03 回测研究",
        "sequence": 380,
        "task_tier": "support",
        "fields": [
            {
                "key": "pk",
                "label": "回测 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
)
