"""Runtime screen patches for macro, regime, and data-center TUI surfaces."""

from __future__ import annotations

from typing import Any

RUNTIME_SCREEN_PATCHES_MACRO_DATA: dict[str, dict[str, Any]] = {
    "macro-regime.beta-gate": {
        "default_action_key": "auto.api.get.api.beta-gate.decisions",
        "user_experience": {
            "journey": "dashboard",
            "primary_task": "先判断当前市场暴露是否被放行，再决定是否继续查看配置和标的池版本差异。",
            "primary_outcome": "明确最近放行结论、当前配置是否匹配风险画像，以及是否需要做版本复核。",
            "empty_state_hint": "先看最近闸门决策，再看配置版本和标的池快照。",
            "next_step_hint": "如果放行结论与预期不一致，继续比较配置版本并复核规则差异。",
        },
        "business_context": {
            "objective": "先看最近闸门决策，再核对配置、标的池和版本差异，判断当前市场暴露是否允许放行。",
            "decision_output": "Beta 闸门结论：放行、限制、禁止或需要版本复核。",
            "checkpoints": [
                "先看最近决策，确认哪些标的被放行、限制或拦截。",
                "再看配置和标的池，确认当前约束是否符合目标风险画像。",
                "需要核对规则变动时再进入版本对比，不直接执行。",
            ],
        },
        "dashboard_panels": [
            {
                "key": "beta-gate-decisions",
                "title": "一、最近闸门决策",
                "kind": "datagrid",
                "action_key": "auto.api.get.api.beta-gate.decisions",
                "max_rows": 8,
                "layout_area": "decisions",
                "target_screen": "macro-regime.beta-gate",
                "user_priority": "p0",
                "presentation_semantic": "primary_list",
                "columns": [
                    {"key": "asset_code", "label": "标的"},
                    {"key": "status", "label": "结论"},
                    {"key": "current_regime", "label": "环境"},
                    {"key": "policy_level", "label": "政策档位"},
                    {"key": "evaluated_at", "label": "评估时间"},
                ],
            },
            {
                "key": "beta-gate-configs",
                "title": "二、当前配置版本",
                "kind": "datagrid",
                "action_key": "auto.api.get.api.beta-gate.configs",
                "max_rows": 6,
                "layout_area": "configs",
                "target_screen": "macro-regime.beta-gate",
                "user_priority": "p1",
                "presentation_semantic": "supporting_list",
                "columns": [
                    {"key": "config_id", "label": "配置ID"},
                    {"key": "risk_profile", "label": "风险画像"},
                    {"key": "version", "label": "版本"},
                    {"key": "is_active", "label": "启用"},
                    {"key": "effective_date", "label": "生效日期"},
                ],
            },
            {
                "key": "beta-gate-universe",
                "title": "三、最近标的池快照",
                "kind": "datagrid",
                "action_key": "auto.api.get.api.beta-gate.universe",
                "max_rows": 6,
                "layout_area": "universe",
                "target_screen": "macro-regime.beta-gate",
                "user_priority": "p2",
                "presentation_semantic": "supporting_list",
                "columns": [
                    {"key": "snapshot_id", "label": "快照ID"},
                    {"key": "current_regime", "label": "环境"},
                    {"key": "policy_level", "label": "政策档位"},
                    {"key": "risk_profile", "label": "风险画像"},
                    {"key": "created_at", "label": "生成时间"},
                ],
            },
            {
                "key": "beta-gate-version-compare",
                "title": "四、最近配置版本",
                "kind": "datagrid",
                "action_key": "auto.api.get.api.beta-gate.version.compare",
                "max_rows": 6,
                "layout_area": "versions",
                "target_screen": "macro-regime.beta-gate",
                "user_priority": "p2",
                "presentation_semantic": "supporting_list",
                "columns": [
                    {"key": "config_id", "label": "配置ID"},
                    {"key": "risk_profile", "label": "风险画像"},
                    {"key": "version", "label": "版本"},
                    {"key": "is_active", "label": "启用"},
                    {"key": "created_at", "label": "创建时间"},
                ],
            },
        ],
    },
    "macro-regime.hedge": {
        "default_action_key": "auto.api.get.api.hedge.snapshots",
        "user_experience": {
            "journey": "dashboard",
            "primary_task": "先判断当前是否存在需要处理的对冲变化或主动预警，再决定是否继续看有效性。",
            "primary_outcome": "明确最新对冲快照、当前预警状态，以及是否需要继续复核对冲有效性。",
            "empty_state_hint": "先看最新对冲快照和当前预警，再查看对冲有效性。",
            "next_step_hint": "若快照或预警显示风险上升，继续进入有效性和相关性检查。",
        },
        "dashboard_panels": [
            {
                "key": "hedge-latest-snapshots",
                "title": "一、最新对冲快照",
                "kind": "datagrid",
                "action_key": "auto.api.get.api.hedge.snapshots.latest",
                "max_rows": 8,
                "layout_area": "snapshots",
                "target_screen": "macro-regime.hedge",
                "user_priority": "p0",
                "presentation_semantic": "primary_list",
            },
            {
                "key": "hedge-active-alerts",
                "title": "二、当前对冲预警",
                "kind": "datagrid",
                "action_key": "auto.api.get.api.hedge.alerts.active",
                "max_rows": 6,
                "layout_area": "alerts",
                "target_screen": "macro-regime.hedge",
                "user_priority": "p1",
                "presentation_semantic": "supporting_list",
            },
            {
                "key": "hedge-effectiveness",
                "title": "三、对冲有效性",
                "kind": "datagrid",
                "action_key": "auto.api.get.api.hedge.pairs.all_effectiveness",
                "max_rows": 6,
                "layout_area": "effectiveness",
                "target_screen": "macro-regime.hedge",
                "user_priority": "p2",
                "presentation_semantic": "supporting_list",
            },
        ],
    },
    "macro-regime.pulse": {
        "default_action_key": "pulse.current",
        "user_experience": {
            "journey": "dashboard",
            "primary_task": "先确认当前脉搏指标是否出现转折，再决定是否继续查看历史变化。",
            "primary_outcome": "明确当前脉搏状态、是否有异常变化，以及是否需要用历史数据复核趋势。",
            "empty_state_hint": "先看当前脉搏指标，再进入历史观察变化方向。",
            "next_step_hint": "如果当前脉搏出现异常或转折，继续查看历史并回到环境行动建议。",
        },
        "dashboard_panels": [
            {
                "key": "pulse-current",
                "title": "一、当前脉搏指标",
                "kind": "datagrid",
                "action_key": "pulse.current",
                "max_rows": 8,
                "layout_area": "current",
                "target_screen": "macro-regime.pulse",
                "user_priority": "p0",
                "presentation_semantic": "primary_list",
            },
            {
                "key": "pulse-history",
                "title": "二、脉搏趋势",
                "kind": "chart",
                "action_key": "pulse.history",
                "layout_area": "history",
                "target_screen": "macro-regime.pulse",
                "user_priority": "p2",
                "presentation_semantic": "supporting_detail",
            },
        ],
    },
}

RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_MACRO_DATA: dict[str, set[str]] = {
    "macro-regime.beta-gate": {
        "auto.api.get.api.beta-gate",
        "auto.api.get.api.beta-gate.health",
    },
}
