"""Compatibility exports for runtime TUI metadata constants."""

from __future__ import annotations

from .tui_metadata_runtime_action_patch_registry import RUNTIME_ACTION_PATCHES
from .tui_metadata_runtime_injections import (
    RUNTIME_ADVISOR_ACTION,
    RUNTIME_ADVISOR_FACTOR_BREAKDOWN_ACTION,
    RUNTIME_ADVISOR_SCREEN,
    RUNTIME_ADVISOR_SELECTOR_ACTION,
    RUNTIME_CAPABILITY_ROUTER_ACTIONS,
    RUNTIME_CAPABILITY_ROUTER_MODULE,
    RUNTIME_CAPABILITY_ROUTER_SCREEN,
    RUNTIME_CLI_CHAT_ACTION,
    RUNTIME_CLI_GROUP,
    RUNTIME_CLI_MODULE,
    RUNTIME_CLI_SCREEN,
    RUNTIME_CONFIG_CENTER_ACTIONS,
    RUNTIME_OPERATOR_ACTIONS,
    RUNTIME_RISK_CENTER_ACTIONS,
    RUNTIME_RISK_CENTER_MODULE,
    RUNTIME_RISK_CENTER_SCREEN,
)
from .tui_metadata_runtime_screen_patch_registry import (
    RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS,
    RUNTIME_SCREEN_PATCHES,
)

__all__ = [
    "RUNTIME_ACTION_PATCHES",
    "RUNTIME_ADVISOR_ACTION",
    "RUNTIME_ADVISOR_FACTOR_BREAKDOWN_ACTION",
    "RUNTIME_ADVISOR_SCREEN",
    "RUNTIME_ADVISOR_SELECTOR_ACTION",
    "RUNTIME_CAPABILITY_ROUTER_ACTIONS",
    "RUNTIME_CAPABILITY_ROUTER_MODULE",
    "RUNTIME_CAPABILITY_ROUTER_SCREEN",
    "RUNTIME_CLI_CHAT_ACTION",
    "RUNTIME_CLI_GROUP",
    "RUNTIME_CLI_MODULE",
    "RUNTIME_CLI_SCREEN",
    "RUNTIME_CONFIG_CENTER_ACTIONS",
    "RUNTIME_OPERATOR_ACTIONS",
    "RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS",
    "RUNTIME_RISK_CENTER_ACTIONS",
    "RUNTIME_RISK_CENTER_MODULE",
    "RUNTIME_RISK_CENTER_SCREEN",
    "RUNTIME_SCREEN_PATCHES",
]
