"""Runtime TUI metadata for decision quota management."""

from __future__ import annotations

from typing import Any

from apps.decision_rhythm.domain.entities import QuotaPeriod

_PERIOD_OPTIONS = ["", *[period.value for period in QuotaPeriod]]

RUNTIME_DECISION_RHYTHM_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "decision-rhythm.quota-list",
        "label": "查看决策配额",
        "endpoint": "/api/decision-rhythm/quotas/",
        "method": "GET",
        "intent": "list_decision_quotas",
        "risk": "read",
        "screen_key": "command-center.decision-flow",
        "module_key": "daily-decisions",
        "view_type": "datagrid",
        "description": "按账户和周期查看决策与执行配额使用情况。",
        "source": "approved:runtime-decision-rhythm",
        "task_group": "03 决策配额",
        "sequence": 280,
        "task_tier": "support",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "text",
                "required": False,
                "binding": "query",
                "value_type": "string",
            },
            {
                "key": "period",
                "label": "周期",
                "input_type": "select",
                "required": False,
                "binding": "query",
                "value_type": "string",
                "options": _PERIOD_OPTIONS,
            },
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "results",
            "columns": [
                {"key": "account_id", "label": "账户"},
                {"key": "period", "label": "周期"},
                {"key": "used_decisions", "label": "已用决策"},
                {"key": "max_decisions", "label": "决策上限"},
                {"key": "used_executions", "label": "已用执行"},
                {"key": "max_execution_count", "label": "执行上限"},
                {"key": "remaining_decisions", "label": "剩余决策"},
            ],
        },
    },
    {
        "key": "decision-rhythm.quota-trend",
        "label": "查看决策使用趋势",
        "endpoint": "/api/decision-rhythm/trend-data/",
        "method": "GET",
        "intent": "read_decision_quota_trend",
        "risk": "read",
        "screen_key": "command-center.decision-flow",
        "module_key": "daily-decisions",
        "view_type": "chart",
        "description": "查看近 7 天或 30 天的每日决策使用趋势。",
        "source": "approved:runtime-decision-rhythm",
        "task_group": "03 决策配额",
        "sequence": 290,
        "task_tier": "support",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "text",
                "required": False,
                "default": "default",
                "binding": "query",
                "value_type": "string",
            },
            {
                "key": "days",
                "label": "时间范围",
                "input_type": "select",
                "required": False,
                "default": "7",
                "binding": "query",
                "value_type": "integer",
                "options": ["7", "30"],
            },
        ],
        "view_model": {
            "kind": "chart",
            "rows_path": "data.daily_decisions",
            "columns": [
                {"key": "date", "label": "日期"},
                {"key": "value", "label": "每日决策"},
            ],
        },
    },
    {
        "key": "decision-rhythm.quota-update",
        "label": "更新决策配额",
        "endpoint": "/api/decision-rhythm/quota/update/",
        "method": "POST",
        "intent": "update_decision_quota",
        "risk": "admin",
        "audience": "admin",
        "effect": "update",
        "confirmation_required": True,
        "screen_key": "command-center.decision-flow",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "更新一个账户指定周期的决策与执行上限。",
        "source": "approved:runtime-decision-rhythm",
        "task_group": "03 决策配额",
        "sequence": 300,
        "task_tier": "support",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "text",
                "required": False,
                "default": "default",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "period",
                "label": "周期",
                "input_type": "select",
                "required": True,
                "binding": "body",
                "value_type": "string",
                "options": [period.value for period in QuotaPeriod],
            },
            {
                "key": "max_decisions",
                "label": "最大决策数",
                "input_type": "number",
                "required": True,
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "max_executions",
                "label": "最大执行数",
                "input_type": "number",
                "required": True,
                "binding": "body",
                "value_type": "integer",
            },
        ],
        "view_model": {
            "kind": "detail",
            "title_path": "period",
            "status_path": "success",
        },
    },
    {
        "key": "decision-rhythm.quota-reset",
        "label": "重置决策配额用量",
        "endpoint": "/api/decision-rhythm/reset-quota/",
        "method": "POST",
        "intent": "reset_decision_quota_usage",
        "risk": "admin",
        "audience": "admin",
        "effect": "update",
        "confirmation_required": True,
        "screen_key": "command-center.decision-flow",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "清零一个账户指定周期或全部周期的已用配额。",
        "source": "approved:runtime-decision-rhythm",
        "task_group": "03 决策配额",
        "sequence": 310,
        "task_tier": "support",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "period",
                "label": "周期（留空为全部）",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "string",
                "options": _PERIOD_OPTIONS,
            },
        ],
        "view_model": {
            "kind": "detail",
            "title_path": "message",
            "status_path": "success",
        },
    },
)
