"""Governance runtime TUI actions for risk-center surfaces."""

from __future__ import annotations

from typing import Any

RUNTIME_RISK_CENTER_GOVERNANCE_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "risk-center.create-exception",
        "label": "创建风控例外",
        "endpoint": "/api/risk-center/exceptions/",
        "method": "POST",
        "intent": "create_risk_exception",
        "risk": "write",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "经过确认后创建有理由和过期时间的管理员风控例外。",
        "source": "approved:runtime-risk-center",
        "task_group": "02 风控写入",
        "sequence": 220,
        "task_tier": "advanced",
        "fields": [
            {
                "key": "account_id",
                "label": "账户 ID",
                "input_type": "number",
                "required": False,
                "default": "",
                "placeholder": "可选",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "field_name",
                "label": "突破字段",
                "input_type": "select",
                "required": True,
                "default": "max_total_position_pct",
                "placeholder": "",
                "binding": "body",
                "value_type": "string",
                "options": ["max_total_position_pct", "max_single_position_pct", "min_cash_pct"],
            },
            {
                "key": "allowed_value",
                "label": "允许值",
                "input_type": "number",
                "required": True,
                "default": "",
                "placeholder": "0.9",
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "expires_at",
                "label": "过期时间",
                "input_type": "text",
                "required": True,
                "default": "",
                "placeholder": "2026-06-28T00:00:00Z",
                "binding": "body",
                "value_type": "datetime",
            },
            {
                "key": "reason",
                "label": "例外理由",
                "input_type": "textarea",
                "required": True,
                "default": "",
                "placeholder": "说明临时突破底线的业务原因",
                "binding": "body",
                "value_type": "string",
            },
        ],
    },
    {
        "key": "risk-center.active-scenario-set",
        "label": "当前生效情景集",
        "endpoint": "/api/risk-center/stress-scenario-sets/active/",
        "method": "GET",
        "intent": "read_active_scenario_set",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "查看当前生效情景、主情景概率、最近修改、证据时间和阻断状态。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "00 情景总览",
        "sequence": 10,
        "task_tier": "primary",
        "fields": [
            {
                "key": "environment",
                "label": "运行环境",
                "input_type": "select",
                "required": True,
                "default": "production",
                "binding": "query",
                "value_type": "string",
                "options": ["production", "shadow"],
            },
            {
                "key": "purpose",
                "label": "用途",
                "input_type": "select",
                "required": True,
                "default": "portfolio_stress",
                "binding": "query",
                "value_type": "string",
                "options": ["portfolio_stress", "strategy_research"],
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.status"},
    },
    {
        "key": "risk-center.scenario-list",
        "label": "情景版本目录",
        "endpoint": "/api/risk-center/stress-scenarios/",
        "method": "GET",
        "intent": "list_governed_stress_scenarios",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "datagrid",
        "description": "查看可见情景定义、当前版本、类型、状态和证据更新时间。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "00 情景总览",
        "sequence": 20,
        "task_tier": "primary",
        "view_model": {"kind": "datagrid", "rows_path": "data"},
    },
    {
        "key": "risk-center.market-state",
        "label": "五维市场状态",
        "endpoint": "/api/risk-center/research/market-state/",
        "method": "GET",
        "intent": "read_five_dimension_market_state",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "聚合宏观、产业、盈利、资金和估值证据，并保留缺失与冲突。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "00 情景总览",
        "sequence": 30,
        "task_tier": "primary",
        "view_model": {"kind": "detail", "status_path": "data.must_not_use_for_decision"},
    },
    {
        "key": "risk-center.scenario-impact-preview",
        "label": "预览组合情景影响",
        "endpoint": "/api/risk-center/stress-scenario-sets/impact-preview/",
        "method": "POST",
        "intent": "preview_scenario_portfolio_impact",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "基于不可变组合快照预览各情景和概率加权影响，不执行交易。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "01 情景预览",
        "sequence": 40,
        "task_tier": "primary",
        "fields": [
            {
                "key": "scenario_set_revision_id",
                "label": "情景集版本",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "portfolio_snapshot_id",
                "label": "组合快照",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "allocation_policy_version",
                "label": "配置政策版本",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {
            "kind": "detail",
            "status_path": "data.must_not_use_for_decision",
        },
    },
    {
        "key": "risk-center.scenario-revision-preview",
        "label": "预览情景修订",
        "endpoint": "/api/risk-center/stress-scenarios/preview-revision/",
        "method": "POST",
        "intent": "preview_stress_scenario_revision",
        "risk": "read",
        "audience": "admin",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "先校验修订并查看版本差异、数据依赖和组合影响，全程不改变生效状态。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "01 情景预览",
        "sequence": 50,
        "task_tier": "primary",
        "fields": [
            {
                "key": "scenario_key",
                "label": "情景标识",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "scenario_type",
                "label": "情景类型",
                "input_type": "select",
                "required": True,
                "default": "historical_window",
                "binding": "body",
                "value_type": "string",
                "options": [
                    "historical_window",
                    "rolling_extreme",
                    "parametric_shock",
                    "macro_path",
                ],
            },
            {
                "key": "based_on_version",
                "label": "基于版本",
                "input_type": "number",
                "required": False,
                "default": "",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "invalidation_logic",
                "label": "证伪条件",
                "input_type": "textarea",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "review_date",
                "label": "下次复核日期",
                "input_type": "date",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "date",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.status"},
    },
    {
        "key": "risk-center.scenario-propose",
        "label": "提交情景修订提案",
        "endpoint": "/api/risk-center/stress-scenarios/propose-revision/",
        "method": "POST",
        "intent": "propose_stress_scenario_revision",
        "risk": "write",
        "effect": "create",
        "confirmation_required": True,
        "audit_required": True,
        "audience": "admin",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "确认后只创建不可变修订提案，不会自动激活生产情景。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "02 情景治理",
        "sequence": 60,
        "task_tier": "primary",
        "fields": [
            {
                "key": "preview_id",
                "label": "预览凭据",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "change_reason",
                "label": "修订理由",
                "input_type": "textarea",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "idempotency_key",
                "label": "操作流水号",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.status"},
    },
    {
        "key": "risk-center.scenario-activate",
        "label": "激活已批准情景版本",
        "endpoint": "/api/risk-center/stress-scenario-sets/activate/",
        "method": "POST",
        "intent": "activate_approved_stress_scenario_revision",
        "risk": "admin",
        "effect": "update",
        "confirmation_required": True,
        "audit_required": True,
        "audience": "admin",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "仅人类管理员可在持久审批通过后激活；AI 提案人不能自批。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "02 情景治理",
        "sequence": 70,
        "task_tier": "advanced",
        "fields": [
            {
                "key": "proposal_id",
                "label": "已批准提案",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "scenario_set_revision_id",
                "label": "待激活情景集版本",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "environment",
                "label": "运行环境",
                "input_type": "select",
                "required": True,
                "default": "production",
                "binding": "body",
                "value_type": "string",
                "options": ["production", "shadow"],
            },
            {
                "key": "purpose",
                "label": "使用目的",
                "input_type": "text",
                "required": True,
                "default": "portfolio_stress",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "preview_id",
                "label": "预览凭据",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "expected_active_version",
                "label": "当前版本",
                "input_type": "number",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "expected_active_hash",
                "label": "当前内容校验值",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "change_reason",
                "label": "激活理由",
                "input_type": "textarea",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "correlation_id",
                "label": "操作流水号",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "idempotency_key",
                "label": "操作流水号",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.status"},
    },
    {
        "key": "risk-center.scenario-proposal-approve",
        "label": "人工复核情景提案",
        "endpoint": "/api/risk-center/stress-scenario-proposals/{proposal_id}/approve/",
        "method": "POST",
        "intent": "approve_stress_scenario_proposal",
        "risk": "admin",
        "effect": "update",
        "confirmation_required": True,
        "audit_required": True,
        "audience": "admin",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "由非提案人的人类管理员复核证据后批准；批准本身不会自动激活。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "02 情景治理",
        "sequence": 75,
        "task_tier": "advanced",
        "fields": [
            {
                "key": "proposal_id",
                "label": "待复核提案",
                "input_type": "number",
                "required": True,
                "default": "",
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "reason",
                "label": "复核意见",
                "input_type": "textarea",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "correlation_id",
                "label": "操作流水号",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.status"},
    },
    {
        "key": "risk-center.scenario-rollback",
        "label": "回滚到已验证版本",
        "endpoint": "/api/risk-center/stress-scenario-sets/rollback/",
        "method": "POST",
        "intent": "rollback_approved_stress_scenario_revision",
        "risk": "admin",
        "effect": "update",
        "confirmation_required": True,
        "audit_required": True,
        "audience": "admin",
        "screen_key": "risk-center.overview",
        "module_key": "risk-center",
        "view_type": "detail",
        "description": "复制旧内容为新版本并激活，历史版本保持不可变。",
        "source": "approved:runtime-risk-center-scenarios",
        "task_group": "02 情景治理",
        "sequence": 80,
        "task_tier": "advanced",
        "fields": [
            {
                "key": "proposal_id",
                "label": "已批准提案",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "target_version",
                "label": "目标历史版本",
                "input_type": "number",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "scenario_key",
                "label": "情景集标识",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "environment",
                "label": "运行环境",
                "input_type": "select",
                "required": True,
                "default": "production",
                "binding": "body",
                "value_type": "string",
                "options": ["production", "shadow"],
            },
            {
                "key": "purpose",
                "label": "使用目的",
                "input_type": "text",
                "required": True,
                "default": "portfolio_stress",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "preview_id",
                "label": "预览凭据",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "expected_active_version",
                "label": "当前版本",
                "input_type": "number",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "expected_active_hash",
                "label": "当前内容校验值",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "change_reason",
                "label": "回滚理由",
                "input_type": "textarea",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "correlation_id",
                "label": "操作流水号",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "idempotency_key",
                "label": "操作流水号",
                "input_type": "text",
                "required": True,
                "default": "",
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "data.status"},
    },
)
