"""Runtime action patches for Alpha and policy TUI actions."""

from __future__ import annotations

from typing import Any

RUNTIME_ACTION_PATCHES_ALPHA_POLICY: dict[str, dict[str, Any]] = {
    "alpha.scores": {
        "fields": [
            {
                "key": "universe",
                "label": "股票池",
                "input_type": "text",
                "value_type": "string",
                "binding": "query",
                "default": "csi300",
                "required": False,
                "placeholder": "csi300",
            },
            {
                "key": "trade_date",
                "label": "刷新日期",
                "input_type": "date",
                "value_type": "date",
                "binding": "query",
                "default": "",
                "required": False,
                "placeholder": "",
            },
            {
                "key": "top_n",
                "label": "候选数量",
                "input_type": "hidden",
                "value_type": "integer",
                "binding": "query",
                "default": 500,
                "required": False,
                "placeholder": "",
            },
            {
                "key": "limit",
                "label": "每页数量",
                "input_type": "hidden",
                "value_type": "integer",
                "binding": "query",
                "default": 30,
                "required": False,
                "placeholder": "",
            },
            {
                "key": "offset",
                "label": "偏移量",
                "input_type": "hidden",
                "value_type": "integer",
                "binding": "query",
                "default": 0,
                "required": False,
                "placeholder": "",
            },
        ],
        "pagination": {"mode": "offset", "offset_param": "offset", "limit_param": "limit"},
        "view_model": {"rows_path": "stocks", "total_path": "total", "page_size_path": "page_size"},
    },
    "policy.workbench_items": {
        "fields": [
            {
                "key": "search",
                "label": "标题或正文关键词",
                "input_type": "text",
                "value_type": "string",
                "binding": "query",
                "default": "",
                "required": False,
                "placeholder": "",
                "presentation_semantic": "primary_selector",
            },
            {
                "key": "tab",
                "label": "审核范围",
                "input_type": "select",
                "value_type": "string",
                "binding": "query",
                "default": "all",
                "required": False,
                "placeholder": "",
                "presentation_semantic": "primary_selector",
                "options": [
                    {"value": "all", "label": "全部"},
                    {"value": "pending", "label": "待审核"},
                    {"value": "effective", "label": "已生效"},
                ],
            },
            {
                "key": "start_date",
                "label": "开始日期",
                "input_type": "date",
                "value_type": "date",
                "binding": "query",
                "default": "",
                "required": False,
                "placeholder": "",
                "presentation_semantic": "primary_selector",
            },
            {
                "key": "end_date",
                "label": "结束日期",
                "input_type": "date",
                "value_type": "date",
                "binding": "query",
                "default": "",
                "required": False,
                "placeholder": "",
                "presentation_semantic": "primary_selector",
            },
            {
                "key": "limit",
                "label": "每页数量",
                "input_type": "hidden",
                "value_type": "integer",
                "binding": "query",
                "default": 50,
                "required": False,
                "placeholder": "",
            },
            {
                "key": "offset",
                "label": "偏移量",
                "input_type": "hidden",
                "value_type": "integer",
                "binding": "query",
                "default": 0,
                "required": False,
                "placeholder": "",
            },
        ],
        "pagination": {"mode": "offset", "offset_param": "offset", "limit_param": "limit"},
        "view_model": {
            "kind": "datagrid",
            "rows_path": "items",
            "total_path": "total",
            "columns": [
                {"key": "title", "label": "事件标题"},
                {"key": "audit_status", "label": "审核状态"},
                {"key": "gate_effective", "label": "闸门生效"},
                {"key": "event_date", "label": "事件日期"},
                {"key": "level", "label": "事件等级"},
                {"key": "gate_level", "label": "闸门等级"},
                {"key": "id", "label": "事件编号"},
                {"key": "review_notes", "label": "审核说明"},
                {"key": "rollback_reason", "label": "回滚原因"},
            ],
        },
    },
    "auto.api.get.api.dashboard.alpha.history": {
        "view_type": "datagrid",
        "view_model": {"rows_path": "data"},
    },
}
