"""Runtime screen patches for execution and risk-control TUI surfaces."""

from __future__ import annotations

from typing import Any


RUNTIME_SCREEN_PATCHES_EXECUTION: dict[str, dict[str, Any]] = {'execution.accounts': {'label': '账户清单与当前持仓',
                        'summary': '集中查看当前账户清单、组合、持仓和账户级绩效检查。',
                        'business_context': {'objective': '在执行前确认当前账户、现金、组合和持仓都支持今天的动作。',
                                             'decision_output': '账户与持仓检查结论：可执行、资金不足、持仓冲突或需调整账户。',
                                             'checkpoints': ['先看账户清单，确认账户名称、类型、现金和总资产。',
                                                             '再看当前持仓，确认资产代码、名称、数量、市值和浮动盈亏。',
                                                             '需要单账户明细时，用账户下拉选择后查看账户持仓和绩效。']}},
  'execution.account-settings': {'default_action_key': 'operator.governance.account_settings_summary',
                                 'workflow': {'name': '系统治理流程',
                                              'step': 5,
                                              'total': 6,
                                              'label': '执行参数',
                                              'role': '确认会阻断执行的参数异常，再进入分类、汇率和成本明细。',
                                              'previous': {'key': 'ai-ops.agent-runtime',
                                                           'label': 'Agent 运行时治理'},
                                              'next': {'key': 'api-library.config-center',
                                                       'label': '配置中心治理'}},
                                 'business_context': {'objective': '先看会阻断执行的参数异常，再决定是否进入分类、汇率、成本或观察授权明细。',
                                                      'decision_output': '执行参数结论：可执行、缺少分类/币种、没有组合或需要补配置。',
                                                      'checkpoints': ['先看治理摘要，确认是否存在会阻断执行的前置条件。',
                                                                      '再看宏观仓位、交易成本、分类和汇率等具体参数。',
                                                                      '参数修正后再回到执行或决策主线。']},
                                 'dashboard_panels': [{'key': 'account-settings-governance-summary',
                                                       'title': '一、执行阻断参数',
                                                       'kind': 'datagrid',
                                                       'action_key': 'operator.governance.account_settings_summary',
                                                       'max_rows': 8,
                                                       'layout_area': 'governance_summary',
                                                       'target_screen': 'execution.account-settings',
                                                       'columns': [{'key': 'severity', 'label': '级别'},
                                                                   {'key': 'title', 'label': '异常项'},
                                                                   {'key': 'status', 'label': '状态'},
                                                                   {'key': 'blocking_reason',
                                                                    'label': '原因'},
                                                                   {'key': 'next_action',
                                                                    'label': '下一步'}]},
                                                      {'key': 'account-settings-macro-sizing',
                                                       'title': '二、宏观仓位参数',
                                                       'kind': 'datagrid',
                                                       'action_key': 'auto.api.get.api.account.macro-sizing-config',
                                                       'max_rows': 6,
                                                       'layout_area': 'macro_sizing',
                                                       'target_screen': 'execution.account-settings'},
                                                      {'key': 'account-settings-trading-cost',
                                                       'title': '三、交易成本配置',
                                                       'kind': 'datagrid',
                                                       'action_key': 'auto.api.get.api.account.trading-cost-configs',
                                                       'max_rows': 6,
                                                       'layout_area': 'trading_cost',
                                                       'target_screen': 'execution.account-settings'}]},
  'execution.events': {'default_action_key': 'auto.api.get.api.events.query',
                       'business_context': {'objective': '先看最近事件，再核对事件指标和运行状态，判断事件总线是否支持当前执行链路。',
                                            'decision_output': '事件结论：正常、堆积、失败升高或需要排查订阅端。',
                                            'checkpoints': ['先看最近事件，确认是否持续产出和消费。',
                                                            '再看事件指标，确认失败数、成功率和处理耗时。',
                                                           '最后看运行状态，确认队列大小和订阅端数量。']},
                      'dashboard_panels': [{'key': 'events-query',
                                            'title': '一、最近事件',
                                            'kind': 'datagrid',
                                            'action_key': 'auto.api.get.api.events.query',
                                            'max_rows': 8,
                                            'layout_area': 'events',
                                            'target_screen': 'execution.events'},
                                           {'key': 'events-metrics',
                                            'title': '二、事件指标',
                                            'kind': 'detail',
                                            'action_key': 'auto.api.get.api.events.metrics',
                                            'layout_area': 'metrics',
                                            'target_screen': 'execution.events'},
                                           {'key': 'events-status',
                                            'title': '三、事件状态',
                                            'kind': 'detail',
                                            'action_key': 'auto.api.get.api.events.status',
                                            'layout_area': 'status',
                                            'target_screen': 'execution.events'}]},
 'execution.share': {'default_action_key': 'auto.api.get.api.share.links',
                     'business_context': {'objective': '先看分享链接，再沿着同屏详情、日志和快照动作检查分享链路是否可用。',
                                          'decision_output': '分享结论：链接正常、访问受限、快照缺失或需要重新生成公开入口。',
                                          'checkpoints': ['先看分享链接列表，确认短码、主题和所属账户。',
                                                          '再从选中行进入详情、日志、快照或统计。',
                                                          '公开访问需要短码和密码时，用专门的验证访问动作处理。']},
                     'dashboard_panels': [{'key': 'share-links',
                                           'title': '一、分享链接',
                                           'kind': 'datagrid',
                                           'action_key': 'auto.api.get.api.share.links',
                                           'max_rows': 8,
                                           'layout_area': 'links',
                                           'target_screen': 'execution.share'}]},
 'risk-center.overview': {'default_action_key': 'risk-center.effective-policy',
                          'dashboard_panels': [{'key': 'risk-center-floor',
                                                'title': '一、全局底线',
                                                'kind': 'detail',
                                                'action_key': 'risk-center.floor',
                                                'layout_area': 'floor',
                                                'target_screen': 'risk-center.overview'},
                                               {'key': 'risk-center-account-policies',
                                                'title': '二、账户策略',
                                                'kind': 'datagrid',
                                                'action_key': 'risk-center.account-policies',
                                                'max_rows': 8,
                                                'layout_area': 'policies',
                                                'target_screen': 'risk-center.overview'},
                                               {'key': 'risk-center-templates',
                                                'title': '三、风险模板',
                                                'kind': 'datagrid',
                                                'action_key': 'risk-center.templates',
                                                'max_rows': 6,
                                                'layout_area': 'templates',
                                                'target_screen': 'risk-center.overview'}]}}

RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_EXECUTION: dict[str, set[str]] = {'execution.events': {'auto.api.get.api.events'}, 'execution.share': {'auto.api.get.api.share'}}
