"""Runtime screen patches for command-center TUI surfaces."""

from __future__ import annotations

from typing import Any


RUNTIME_SCREEN_PATCHES_COMMAND_CENTER: dict[str, dict[str, Any]] = {'command-center.overview': {'chrome_mode': 'immersive',
                             'dashboard_panels': [{'key': 'today-queue',
                                                   'title': '零、今日待办',
                                                   'kind': 'datagrid',
                                                   'action_key': 'decision.workspace.today_queue',
                                                   'max_rows': 8,
                                                   'layout_area': 'queue',
                                                   'target_screen': 'command-center.decision-flow',
                                                   'columns': [{'key': 'priority', 'label': '优先级'},
                                                               {'key': 'status', 'label': '状态'},
                                                               {'key': 'type', 'label': '类型'},
                                                               {'key': 'title', 'label': '事项'},
                                                               {'key': 'next_action',
                                                                'label': '下一步'},
                                                               {'key': 'security_code',
                                                                'label': '标的'}]},
                                                  {'key': 'regime-status',
                                                   'title': '一、市场周期象限',
                                                   'kind': 'regime_quadrant',
                                                   'action_key': 'regime.current',
                                                   'max_rows': 6,
                                                   'layout_area': 'regime',
                                                   'target_screen': 'macro-regime.overview'},
                                                  {'key': 'pulse-alerts',
                                                   'title': '二、战术脉搏预警',
                                                   'kind': 'detail',
                                                   'action_key': 'pulse.current',
                                                   'layout_area': 'pulse',
                                                   'target_screen': 'macro-regime.pulse'},
                                                  {'key': 'account-list',
                                                   'title': '三、账户清单',
                                                   'kind': 'datagrid',
                                                   'action_key': 'auto.api.get.api.account.accounts',
                                                   'max_rows': 6,
                                                   'layout_area': 'account_list',
                                                   'target_screen': 'execution.accounts',
                                                   'columns': [{'key': 'account_name',
                                                                'label': '账户名称'},
                                                               {'key': 'account_type',
                                                                'label': '类型'},
                                                               {'key': 'total_value',
                                                                'label': '总资产'},
                                                               {'key': 'current_cash',
                                                                'label': '现金'},
                                                               {'key': 'total_return',
                                                                'label': '收益率'}]},
                                                  {'key': 'account-positions',
                                                   'title': '四、当前持仓',
                                                   'kind': 'datagrid',
                                                   'action_key': 'auto.api.get.api.account.positions',
                                                   'max_rows': 8,
                                                   'layout_area': 'positions',
                                                   'target_screen': 'execution.accounts',
                                                   'columns': [{'key': 'portfolio_name',
                                                                'label': '组合'},
                                                               {'key': 'asset_code', 'label': '代码'},
                                                               {'key': 'asset_name', 'label': '名称'},
                                                               {'key': 'shares', 'label': '数量'},
                                                               {'key': 'market_value',
                                                                'label': '市值'},
                                                               {'key': 'unrealized_pnl_pct',
                                                                'label': '盈亏率'}]},
                                                  {'key': 'alpha-ranking',
                                                   'title': '五、Alpha 排行',
                                                   'kind': 'datagrid',
                                                   'action_key': 'alpha.scores',
                                                   'max_rows': 10,
                                                   'layout_area': 'alpha',
                                                   'target_screen': 'research.alpha',
                                                   'columns': [{'key': 'code', 'label': '标的'},
                                                               {'key': 'score', 'label': 'Alpha'},
                                                               {'key': 'rank', 'label': '排名'},
                                                               {'key': 'source', 'label': '来源'},
                                                               {'key': 'confidence',
                                                                'label': '置信度'}]},
                                                  {'key': 'task-monitor',
                                                   'title': '六、任务监控',
                                                   'kind': 'detail',
                                                   'action_key': 'task_monitor.dashboard',
                                                   'layout_area': 'tasks',
                                                   'target_screen': 'execution.tasks'}]},
 'command-center.auto-advisor': {'default_action_key': 'advisor.today_sheet',
                                 'dashboard_panels': [{'key': 'advisor-account-selector',
                                                       'title': '一、账户选择',
                                                       'kind': 'datagrid',
                                                       'action_key': 'advisor.account_selector',
                                                       'max_rows': 8,
                                                       'layout_area': 'accounts',
                                                       'target_screen': 'command-center.auto-advisor'}]}}

RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_COMMAND_CENTER: dict[str, set[str]] = {}
