"""Staff-only TUI actions for preview-first controlled event replay."""

from __future__ import annotations

from typing import Any

_TARGET_OPTIONS = [
    "events.decision.approved",
    "events.decision.rejected",
    "events.decision.executed",
    "events.decision.execution_failed",
    "decision_rhythm.main",
    "decision_rhythm.quota",
    "decision_rhythm.cooldown",
    "alpha_trigger.main",
    "alpha_trigger.invalidation",
    "alpha_trigger.promotion",
]

_REPLAY_FIELDS: list[dict[str, Any]] = [
    {
        "key": "target_key",
        "label": "重放目标",
        "input_type": "select",
        "required": True,
        "default": "events.decision.approved",
        "placeholder": "",
        "binding": "body",
        "value_type": "string",
        "options": _TARGET_OPTIONS,
    },
    {
        "key": "event_type",
        "label": "事件类型",
        "input_type": "text",
        "required": True,
        "default": "decision_approved",
        "placeholder": "decision_approved",
        "binding": "body",
        "value_type": "string",
    },
    {
        "key": "start_at",
        "label": "开始时间",
        "input_type": "text",
        "required": False,
        "default": "",
        "placeholder": "可选，需包含时区",
        "binding": "body",
        "value_type": "datetime",
    },
    {
        "key": "end_at",
        "label": "结束时间",
        "input_type": "text",
        "required": False,
        "default": "",
        "placeholder": "可选，需包含时区",
        "binding": "body",
        "value_type": "datetime",
    },
    {
        "key": "limit",
        "label": "最多事件数",
        "input_type": "number",
        "required": False,
        "default": 100,
        "placeholder": "100",
        "binding": "body",
        "value_type": "integer",
        "min": 1,
        "max": 1000,
    },
]

RUNTIME_EVENT_REPLAY_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "execution.preview-event-replay",
        "label": "预览事件重放",
        "endpoint": "/api/events/replay/preview/",
        "method": "POST",
        "intent": "preview_controlled_event_replay",
        "risk": "admin",
        "screen_key": "execution.events",
        "module_key": "execution",
        "view_type": "detail",
        "description": "管理员先查看候选事件、目标能力和可能产生的业务影响。",
        "source": "approved:runtime-event-replay",
        "task_group": "90 管理员恢复",
        "task_tier": "advanced",
        "sequence": 900,
        "fields": [dict(field) for field in _REPLAY_FIELDS],
        "view_model": {"kind": "detail", "status_path": "success"},
    },
    {
        "key": "execution.commit-event-replay",
        "label": "确认事件重放",
        "endpoint": "/api/events/replay/commit/",
        "method": "POST",
        "intent": "commit_controlled_event_replay",
        "risk": "admin",
        "screen_key": "execution.events",
        "module_key": "execution",
        "view_type": "detail",
        "description": "仅在核对预览后，以唯一执行标识确认重放并查看逐项结果。",
        "source": "approved:runtime-event-replay",
        "task_group": "90 管理员恢复",
        "task_tier": "advanced",
        "sequence": 910,
        "confirmation_required": True,
        "audit_required": True,
        "sensitive_level": "high",
        "fields": [
            *[dict(field) for field in _REPLAY_FIELDS],
            {
                "key": "idempotency_key",
                "label": "唯一执行标识",
                "input_type": "text",
                "required": True,
                "default": "",
                "placeholder": "为本次重放填写唯一标识",
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "detail", "status_path": "outcome"},
    },
)
