"""Runtime TUI metadata for system AI provider administration."""

from __future__ import annotations

from typing import Any

RUNTIME_AI_SYSTEM_PROVIDERS_SCREEN: dict[str, Any] = {
    "key": "ai-ops.system-providers",
    "label": "系统 AI 服务商",
    "module_key": "ai-ops",
    "group": "ops",
    "summary": "管理员在 TUI 内管理系统级 AI 服务商、连通性与使用统计。",
    "view_type": "detail",
    "default_action_key": "ai-ops.system-provider-overall-stats",
    "user_experience": {
        "journey": "admin",
        "primary_task": "先判断系统级 AI 服务商是否可支撑当前业务，再决定是否新增、切换或测试连通性。",
        "primary_outcome": "明确系统服务商总体可用性、启用状态，以及是否需要调整默认路由。",
        "empty_state_hint": "先看系统服务商概览，再查看系统服务商列表。",
        "next_step_hint": "若可用性不足或默认路由异常，继续在本屏执行创建、切换和连通性测试。",
    },
    "workflow": {
        "name": "AI 管理流程",
        "step": 2,
        "total": 3,
        "label": "系统服务商",
        "role": "先看系统服务商总体可用性，再处理创建、切换和连通性测试。",
        "previous": {"key": "ai-ops.my-providers", "label": "我的 AI 服务商"},
        "next": {"key": "ai-ops.user-quotas", "label": "用户 AI 配额"},
    },
    "business_context": {
        "objective": "把系统服务商的 CRUD、启停和测试能力拉进 TUI。",
        "decision_output": "系统服务商总量、启用状态、最近用量以及是否需要切换默认路由。",
        "checkpoints": [
            "先看整体统计，确认系统可用服务商数量。",
            "新增或修改时保持 base_url、api_mode 与默认模型一致。",
            "变更后立即跑 test-connection，不把未验证配置直接交给业务流量。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "system-provider-overall-stats",
            "title": "一、系统服务商概览",
            "kind": "detail",
            "action_key": "ai-ops.system-provider-overall-stats",
            "layout_area": "summary",
            "target_screen": "ai-ops.system-providers",
            "user_priority": "p0",
            "presentation_semantic": "primary_status",
        },
        {
            "key": "system-provider-list",
            "title": "二、系统服务商列表",
            "kind": "datagrid",
            "action_key": "ai-ops.list-system-providers",
            "max_rows": 10,
            "layout_area": "providers",
            "target_screen": "ai-ops.system-providers",
            "columns": [
                {"key": "id", "label": "ID"},
                {"key": "name", "label": "名称"},
                {"key": "provider_type_label", "label": "类型"},
                {"key": "default_model", "label": "默认模型"},
                {"key": "is_active", "label": "启用"},
                {"key": "priority", "label": "优先级"},
            ],
            "row_actions": [
                {
                    "action_key": "ai-ops.system-provider-detail",
                    "label_template": "查看 {name}",
                    "param_map": {"provider_id": "id"},
                    "result_panel_key": "system-provider-workspace",
                },
                {
                    "action_key": "ai-ops.update-system-provider",
                    "label_template": "编辑 {name}",
                    "param_map": {"provider_id": "id"},
                    "result_panel_key": "system-provider-workspace",
                    "refresh_panel_key": "system-provider-list",
                },
                {
                    "action_key": "ai-ops.toggle-system-provider",
                    "label_template": "切换 {name} 的启用状态",
                    "param_map": {"provider_id": "id"},
                    "result_panel_key": "system-provider-workspace",
                    "refresh_panel_key": "system-provider-list",
                },
                {
                    "action_key": "ai-ops.test-system-provider",
                    "label_template": "测试 {name} 的连通性",
                    "param_map": {"provider_id": "id"},
                    "result_panel_key": "system-provider-workspace",
                    "refresh_panel_key": "system-provider-list",
                },
                {
                    "action_key": "ai-ops.system-provider-usage-stats",
                    "label_template": "查看 {name} 的用量",
                    "param_map": {"provider_id": "id"},
                    "result_panel_key": "system-provider-workspace",
                },
                {
                    "action_key": "ai-ops.delete-system-provider",
                    "label_template": "删除 {name}",
                    "param_map": {"provider_id": "id"},
                    "result_panel_key": "system-provider-workspace",
                    "refresh_panel_key": "system-provider-list",
                },
            ],
            "user_priority": "p1",
            "presentation_semantic": "supporting_list",
        },
        {
            "key": "system-provider-workspace",
            "title": "三、当前服务商与操作回执",
            "kind": "detail",
            "max_rows": 12,
            "layout_area": "provider-workspace",
            "empty_message": "从系统服务商列表选择查看、编辑、启停、测试、用量或删除操作。",
            "user_priority": "p1",
            "presentation_semantic": "supporting_detail",
        },
        {
            "key": "system-provider-logs",
            "title": "四、系统调用日志",
            "kind": "datagrid",
            "action_key": "ai-ops.system-ai-logs",
            "max_rows": 10,
            "layout_area": "logs",
            "target_screen": "ai-ops.system-providers",
            "columns": [
                {"key": "provider_name", "label": "服务商"},
                {"key": "username", "label": "用户"},
                {"key": "model", "label": "模型"},
                {"key": "provider_scope", "label": "命中范围"},
                {"key": "status", "label": "状态"},
                {"key": "estimated_cost", "label": "成本"},
                {"key": "created_at", "label": "时间"},
            ],
            "user_priority": "p2",
            "presentation_semantic": "supporting_list",
        },
    ],
}


RUNTIME_AI_SYSTEM_PROVIDER_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "ai-ops.system-provider-overall-stats",
        "label": "读取系统服务商概览",
        "endpoint": "/api/ai/providers/overall_stats/",
        "method": "GET",
        "intent": "read_admin_ai_provider_overall_stats",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取管理员视角下的系统服务商总体统计。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 400,
        "task_tier": "primary",
        "fields": [],
        "view_model": {"kind": "detail"},
    },
    {
        "key": "ai-ops.list-system-providers",
        "label": "读取系统服务商列表",
        "endpoint": "/api/ai/providers/",
        "method": "GET",
        "intent": "list_admin_ai_system_providers",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "datagrid",
        "description": "读取系统级 AI 服务商列表。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 410,
        "task_tier": "primary",
        "fields": [],
        "view_model": {"kind": "datagrid"},
    },
    {
        "key": "ai-ops.system-provider-detail",
        "label": "读取系统服务商详情",
        "endpoint": "/api/ai/providers/<int:provider_id>/",
        "method": "GET",
        "intent": "read_admin_ai_system_provider_detail",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取一个系统级 AI 服务商的配置详情。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 420,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.create-system-provider",
        "label": "创建系统服务商",
        "endpoint": "/api/ai/providers/",
        "method": "POST",
        "intent": "create_admin_ai_system_provider",
        "risk": "admin",
        "audience": "admin",
        "effect": "create",
        "confirmation_required": True,
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "创建一个系统级 AI 服务商。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 430,
        "task_tier": "operation",
        "fields": [
            {
                "key": "name",
                "label": "名称",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "provider_type",
                "label": "类型",
                "input_type": "select",
                "required": True,
                "default": "openai",
                "binding": "body",
                "value_type": "string",
                "options": ["openai", "deepseek", "qwen", "moonshot", "custom"],
            },
            {
                "key": "base_url",
                "label": "基础地址",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_key",
                "label": "API Key",
                "input_type": "password",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "default_model",
                "label": "默认模型",
                "input_type": "text",
                "required": False,
                "default": "gpt-3.5-turbo",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_mode",
                "label": "API 模式",
                "input_type": "select",
                "required": False,
                "default": "dual",
                "binding": "body",
                "value_type": "string",
                "options": ["dual", "responses_only", "chat_only"],
            },
            {
                "key": "priority",
                "label": "优先级",
                "input_type": "number",
                "required": False,
                "default": "10",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "select",
                "required": False,
                "default": "true",
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
            {
                "key": "fallback_enabled",
                "label": "允许故障切换",
                "input_type": "select",
                "required": False,
                "default": "true",
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
            {
                "key": "daily_budget_limit",
                "label": "每日预算（USD）",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "monthly_budget_limit",
                "label": "每月预算（USD）",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "description",
                "label": "说明",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "extra_config",
                "label": "扩展配置",
                "input_type": "textarea",
                "required": False,
                "default": {},
                "binding": "body",
                "value_type": "object",
            },
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.update-system-provider",
        "label": "更新系统服务商",
        "endpoint": "/api/ai/providers/<int:provider_id>/",
        "method": "PATCH",
        "intent": "update_admin_ai_system_provider",
        "risk": "admin",
        "audience": "admin",
        "effect": "update",
        "confirmation_required": True,
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "更新一个系统级 AI 服务商。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 440,
        "task_tier": "operation",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "name",
                "label": "名称",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "provider_type",
                "label": "类型",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "string",
                "options": ["openai", "deepseek", "qwen", "moonshot", "custom"],
            },
            {
                "key": "base_url",
                "label": "基础地址",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_key",
                "label": "API Key",
                "input_type": "password",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "default_model",
                "label": "默认模型",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_mode",
                "label": "API 模式",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "string",
                "options": ["dual", "responses_only", "chat_only"],
            },
            {
                "key": "priority",
                "label": "优先级",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
            {
                "key": "fallback_enabled",
                "label": "允许故障切换",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
            {
                "key": "daily_budget_limit",
                "label": "每日预算（USD）",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "monthly_budget_limit",
                "label": "每月预算（USD）",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "description",
                "label": "说明",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "extra_config",
                "label": "扩展配置",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "value_type": "object",
            },
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.toggle-system-provider",
        "label": "切换系统服务商启用",
        "endpoint": "/api/ai/providers/<int:provider_id>/toggle_active/",
        "method": "POST",
        "intent": "toggle_admin_ai_system_provider",
        "risk": "admin",
        "audience": "admin",
        "effect": "toggle",
        "confirmation_required": True,
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "切换系统级 AI 服务商的启用状态。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 450,
        "task_tier": "operation",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.test-system-provider",
        "label": "测试系统服务商连通性",
        "endpoint": "/api/ai/providers/<int:provider_id>/test-connection/",
        "method": "POST",
        "intent": "test_admin_ai_system_provider_connection",
        "risk": "admin",
        "audience": "admin",
        "effect": "execute",
        "confirmation_required": True,
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "测试一个系统级 AI 服务商的连通性。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 460,
        "task_tier": "operation",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail"},
    },
    {
        "key": "ai-ops.system-provider-usage-stats",
        "label": "读取系统服务商用量",
        "endpoint": "/api/ai/providers/<int:provider_id>/usage_stats/",
        "method": "GET",
        "intent": "read_admin_ai_system_provider_usage_stats",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取一个系统级 AI 服务商的今日、本月用量与预算状态。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 470,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "provider_name"},
    },
    {
        "key": "ai-ops.system-ai-logs",
        "label": "读取系统 AI 调用日志",
        "endpoint": "/api/ai/logs/",
        "method": "GET",
        "intent": "list_admin_ai_usage_logs",
        "risk": "admin",
        "audience": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "datagrid",
        "description": "按服务商、状态和命中范围读取系统 AI 调用日志。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 475,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider",
                "label": "服务商 ID",
                "input_type": "number",
                "required": False,
                "binding": "query",
                "value_type": "integer",
            },
            {
                "key": "status",
                "label": "状态",
                "input_type": "select",
                "required": False,
                "binding": "query",
                "value_type": "string",
                "options": ["", "success", "error", "timeout", "rate_limited"],
            },
            {
                "key": "provider_scope",
                "label": "命中范围",
                "input_type": "select",
                "required": False,
                "binding": "query",
                "value_type": "string",
                "options": ["", "system_global", "system_fallback", "personal"],
            },
            {
                "key": "limit",
                "label": "返回行数",
                "input_type": "hidden",
                "required": False,
                "default": "100",
                "binding": "query",
                "value_type": "integer",
            },
        ],
        "view_model": {"kind": "datagrid"},
    },
    {
        "key": "ai-ops.delete-system-provider",
        "label": "删除系统服务商",
        "endpoint": "/api/ai/providers/<int:provider_id>/",
        "method": "DELETE",
        "intent": "delete_admin_ai_system_provider",
        "risk": "admin",
        "audience": "admin",
        "effect": "delete",
        "confirmation_required": True,
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "message",
        "description": "删除一个系统级 AI 服务商。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 480,
        "task_tier": "operation",
        "fields": [
            {
                "key": "provider_id",
                "label": "服务商 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "message"},
    },
)
