"""Runtime screen patches for macro, regime, and data-center TUI surfaces."""

from __future__ import annotations

from typing import Any


RUNTIME_SCREEN_PATCHES_MACRO_DATA: dict[str, dict[str, Any]] = {'macro-regime.beta-gate': {'default_action_key': 'auto.api.get.api.beta-gate.decisions',
                            'business_context': {'objective': '先看最近闸门决策，再核对配置、标的池和版本差异，判断当前市场暴露是否允许放行。',
                                                 'decision_output': 'Beta 闸门结论：放行、限制、禁止或需要版本复核。',
                                                 'checkpoints': ['先看最近决策，确认哪些标的被放行、限制或拦截。',
                                                                 '再看配置和标的池，确认当前约束是否符合目标风险画像。',
                                                                 '需要核对规则变动时再进入版本对比，不直接执行。']},
                            'dashboard_panels': [{'key': 'beta-gate-decisions',
                                                  'title': '一、最近闸门决策',
                                                  'kind': 'datagrid',
                                                  'action_key': 'auto.api.get.api.beta-gate.decisions',
                                                  'max_rows': 8,
                                                  'layout_area': 'decisions',
                                                  'target_screen': 'macro-regime.beta-gate',
                                                  'columns': [{'key': 'asset_code', 'label': '标的'},
                                                              {'key': 'status', 'label': '结论'},
                                                              {'key': 'current_regime',
                                                               'label': '环境'},
                                                              {'key': 'policy_level',
                                                               'label': '政策档位'},
                                                              {'key': 'evaluated_at',
                                                               'label': '评估时间'}]},
                                                 {'key': 'beta-gate-configs',
                                                  'title': '二、当前配置版本',
                                                  'kind': 'datagrid',
                                                  'action_key': 'auto.api.get.api.beta-gate.configs',
                                                  'max_rows': 6,
                                                  'layout_area': 'configs',
                                                  'target_screen': 'macro-regime.beta-gate',
                                                  'columns': [{'key': 'config_id', 'label': '配置ID'},
                                                              {'key': 'risk_profile',
                                                               'label': '风险画像'},
                                                              {'key': 'version', 'label': '版本'},
                                                              {'key': 'is_active', 'label': '启用'},
                                                              {'key': 'effective_date',
                                                               'label': '生效日期'}]},
                                                 {'key': 'beta-gate-universe',
                                                  'title': '三、最近标的池快照',
                                                  'kind': 'datagrid',
                                                  'action_key': 'auto.api.get.api.beta-gate.universe',
                                                  'max_rows': 6,
                                                  'layout_area': 'universe',
                                                  'target_screen': 'macro-regime.beta-gate',
                                                  'columns': [{'key': 'snapshot_id',
                                                               'label': '快照ID'},
                                                              {'key': 'current_regime',
                                                               'label': '环境'},
                                                              {'key': 'policy_level',
                                                               'label': '政策档位'},
                                                              {'key': 'risk_profile',
                                                               'label': '风险画像'},
                                                              {'key': 'created_at',
                                                               'label': '生成时间'}]},
                                                 {'key': 'beta-gate-version-compare',
                                                  'title': '四、最近配置版本',
                                                  'kind': 'datagrid',
                                                  'action_key': 'auto.api.get.api.beta-gate.version.compare',
                                                  'max_rows': 6,
                                                  'layout_area': 'versions',
                                                  'target_screen': 'macro-regime.beta-gate',
                                                  'columns': [{'key': 'config_id', 'label': '配置ID'},
                                                              {'key': 'risk_profile',
                                                               'label': '风险画像'},
                                                              {'key': 'version', 'label': '版本'},
                                                              {'key': 'is_active', 'label': '启用'},
                                                              {'key': 'created_at',
                                                               'label': '创建时间'}]}]},
 'api-library.data-center': {'default_action_key': 'auto.api.get.api.data-center.indicators',
                             'business_context': {'objective': '先从指标目录进入，再用同屏目录和筛选任务完成数据源检查、指标查询和同步动作。',
                                                  'decision_output': '数据中心结论：指标可查、服务商异常、发布机构缺失或需要补同步。',
                                                  'checkpoints': ['先看指标目录，确认当前可用指标和代码。',
                                                                  '再看服务商列表与发布机构目录，确认来源是否可用。',
                                                                  '需要查宏观序列或补同步时，优先从当前目录行填参进入后续任务。']},
                             'dashboard_panels': [{'key': 'data-center-indicators',
                                                   'title': '一、指标目录',
                                                   'kind': 'datagrid',
                                                   'action_key': 'auto.api.get.api.data-center.indicators',
                                                   'max_rows': 8,
                                                   'layout_area': 'indicators',
                                                   'target_screen': 'api-library.data-center'},
                                                  {'key': 'data-center-providers',
                                                   'title': '二、服务商列表',
                                                   'kind': 'datagrid',
                                                   'action_key': 'auto.api.get.api.data-center.providers',
                                                   'max_rows': 6,
                                                   'layout_area': 'providers',
                                                   'target_screen': 'api-library.data-center'},
                                                  {'key': 'data-center-publishers',
                                                   'title': '三、发布机构目录',
                                                   'kind': 'datagrid',
                                                   'action_key': 'auto.api.get.api.data-center.publishers',
                                                   'max_rows': 6,
                                                   'layout_area': 'publishers',
                                                   'target_screen': 'api-library.data-center'}]},
 'macro-regime.hedge': {'dashboard_panels': [{'key': 'hedge-latest-snapshots',
                                              'title': '一、最新对冲快照',
                                              'kind': 'datagrid',
                                              'action_key': 'auto.api.get.api.hedge.snapshots.latest',
                                              'max_rows': 8,
                                              'layout_area': 'snapshots',
                                              'target_screen': 'macro-regime.hedge'},
                                             {'key': 'hedge-active-alerts',
                                              'title': '二、当前对冲预警',
                                              'kind': 'datagrid',
                                              'action_key': 'auto.api.get.api.hedge.alerts.active',
                                              'max_rows': 6,
                                              'layout_area': 'alerts',
                                              'target_screen': 'macro-regime.hedge'},
                                             {'key': 'hedge-effectiveness',
                                              'title': '三、对冲有效性',
                                              'kind': 'datagrid',
                                              'action_key': 'auto.api.get.api.hedge.pairs.all_effectiveness',
                                              'max_rows': 6,
                                              'layout_area': 'effectiveness',
                                              'target_screen': 'macro-regime.hedge'}]},
 'macro-regime.pulse': {'dashboard_panels': [{'key': 'pulse-current',
                                              'title': '一、当前脉搏指标',
                                              'kind': 'datagrid',
                                              'action_key': 'pulse.current',
                                              'max_rows': 8,
                                              'layout_area': 'current',
                                              'target_screen': 'macro-regime.pulse'},
                                             {'key': 'pulse-history',
                                              'title': '二、脉搏历史',
                                              'kind': 'datagrid',
                                              'action_key': 'pulse.history',
                                              'max_rows': 8,
                                              'layout_area': 'history',
                                              'target_screen': 'macro-regime.pulse'}]}}

RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_MACRO_DATA: dict[str, set[str]] = {'api-library.data-center': {'auto.api.get.api.data-center'},
 'macro-regime.beta-gate': {'auto.api.get.api.beta-gate', 'auto.api.get.api.beta-gate.health'}}
