"""Runtime screen patches for command-center TUI surfaces."""

from __future__ import annotations

from typing import Any


RUNTIME_SCREEN_PATCHES_COMMAND_CENTER: dict[str, dict[str, Any]] = {'command-center.overview': {'chrome_mode': 'immersive',
                             'default_action_key': 'operator.home.decision_queue',
                             'label': '统一操作者首页',
                             'summary': '同时查看今日投研判断、治理异常和最近工作区，再决定进入哪条主线。',
                             'business_context': {'objective': '先在一个首页看清今日判断和系统治理状态，再决定进入投研主线还是治理主线。',
                                                  'decision_output': '首页结论：今天要不要继续决策，系统哪里有阻断，下一步去哪个工作区。',
                                                  'checkpoints': ['先看今日待办和环境/脉搏，确认今天是否需要继续投研。',
                                                                  '再看系统异常、数据任务和 AI/配置异常，确认是否先做治理。',
                                                                  '需要继续处理时，优先从首页主动作恢复上次工作区或进入对应主线。']},
                             'dashboard_panels': [{'key': 'today-queue',
                                                   'title': '一、今日待办队列',
                                                   'kind': 'datagrid',
                                                   'action_key': 'operator.home.decision_queue',
                                                   'max_rows': 8,
                                                   'layout_area': 'decision_queue',
                                                   'target_screen': 'command-center.decision-flow',
                                                   'columns': [{'key': 'priority', 'label': '优先级'},
                                                               {'key': 'status', 'label': '状态'},
                                                               {'key': 'type', 'label': '类型'},
                                                               {'key': 'title', 'label': '事项'},
                                                               {'key': 'next_action', 'label': '下一步'},
                                                               {'key': 'security_code', 'label': '标的'}]},
                                                  {'key': 'market-context',
                                                   'title': '二、环境与脉搏摘要',
                                                   'kind': 'datagrid',
                                                   'action_key': 'operator.home.market_context',
                                                   'max_rows': 6,
                                                   'layout_area': 'market_context',
                                                   'target_screen': 'macro-regime.overview',
                                                   'columns': [{'key': 'area', 'label': '模块'},
                                                               {'key': 'status', 'label': '状态'},
                                                               {'key': 'summary', 'label': '摘要'},
                                                               {'key': 'observed_at', 'label': '观察时间'},
                                                               {'key': 'next_action', 'label': '下一步'}]},
                                                  {'key': 'account-signal-summary',
                                                   'title': '三、账户与信号摘要',
                                                   'kind': 'datagrid',
                                                   'action_key': 'operator.home.account_signal_summary',
                                                   'max_rows': 6,
                                                   'layout_area': 'account_signal_summary',
                                                   'target_screen': 'execution.accounts',
                                                   'columns': [{'key': 'area', 'label': '模块'},
                                                               {'key': 'status', 'label': '状态'},
                                                               {'key': 'value', 'label': '数量'},
                                                               {'key': 'summary', 'label': '摘要'},
                                                               {'key': 'next_action', 'label': '下一步'}]},
                                                  {'key': 'system-exception-summary',
                                                   'title': '四、系统异常总览',
                                                   'kind': 'datagrid',
                                                   'action_key': 'operator.home.system_exception_summary',
                                                   'max_rows': 6,
                                                   'layout_area': 'system_exception_summary',
                                                   'target_screen': 'api-library.runtime',
                                                   'columns': [{'key': 'severity', 'label': '级别'},
                                                               {'key': 'domain', 'label': '域'},
                                                               {'key': 'title', 'label': '异常项'},
                                                               {'key': 'status', 'label': '状态'},
                                                               {'key': 'next_action', 'label': '下一步'}]},
                                                  {'key': 'data-task-summary',
                                                   'title': '五、数据与任务异常',
                                                   'kind': 'datagrid',
                                                   'action_key': 'operator.home.data_task_summary',
                                                   'max_rows': 6,
                                                   'layout_area': 'data_task_summary',
                                                   'target_screen': 'api-library.data-center',
                                                   'columns': [{'key': 'severity', 'label': '级别'},
                                                               {'key': 'domain', 'label': '域'},
                                                               {'key': 'title', 'label': '异常项'},
                                                               {'key': 'status', 'label': '状态'},
                                                               {'key': 'next_action', 'label': '下一步'}]},
                                                  {'key': 'ai-config-summary',
                                                   'title': '六、AI / 配置异常',
                                                   'kind': 'datagrid',
                                                   'action_key': 'operator.home.ai_config_summary',
                                                   'max_rows': 6,
                                                   'layout_area': 'ai_config_summary',
                                                   'target_screen': 'ai-ops.providers',
                                                   'columns': [{'key': 'severity', 'label': '级别'},
                                                               {'key': 'domain', 'label': '域'},
                                                               {'key': 'title', 'label': '异常项'},
                                                               {'key': 'status', 'label': '状态'},
                                                               {'key': 'next_action', 'label': '下一步'}]}]},
 'command-center.auto-advisor': {'default_action_key': 'advisor.today_sheet',
                                 'dashboard_panels': [{'key': 'advisor-account-selector',
                                                       'title': '一、账户选择',
                                                       'kind': 'datagrid',
                                                       'action_key': 'advisor.account_selector',
                                                       'max_rows': 8,
                                                       'layout_area': 'accounts',
                                                       'target_screen': 'command-center.auto-advisor'}]}}

RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_COMMAND_CENTER: dict[str, set[str]] = {}
