"""Runtime TUI metadata injection constants for config-center actions."""

from __future__ import annotations

from typing import Any

RUNTIME_CONFIG_CENTER_SCREEN: dict[str, Any] = {
    "key": "system.qlib-center",
    "label": "Qlib 配置与训练",
    "module_key": "system-governance",
    "group": "system",
    "summary": "维护 Qlib 运行配置、模型 Universe、训练模板和训练任务。",
    "view_type": "detail",
    "audience": "admin",
    "dashboard_layout": "task_flow",
    "default_action_key": "config_center.qlib_runtime",
    "user_experience": {
        "journey": "admin",
        "primary_task": "确认 Qlib 运行条件并完成模型范围、训练模板和训练任务管理。",
        "primary_outcome": "Qlib 运行配置有效，训练范围明确，最近训练状态可追溯。",
        "empty_state_hint": "先读取运行配置；首次使用时再创建模型 Universe 或训练模板。",
        "next_step_hint": "配置完成后触发训练，并在运行记录中确认任务结果。",
    },
    "workflow": {
        "name": "系统治理流程",
        "label": "Qlib 配置与训练",
        "role": "维护模型训练和推理所需的运行条件。",
        "previous": {"key": "system.settings", "label": "系统设置"},
        "next": {"key": "api-library.data-center", "label": "数据与系统健康"},
    },
    "business_context": {
        "objective": "让 Qlib 配置、模型范围、训练模板和运行记录在一个任务界面内闭环。",
        "decision_output": "可用于训练或推理的 Qlib 配置，以及最近训练任务的明确状态。",
        "checkpoints": [
            "先核对运行配置、活跃模型和训练占用状态。",
            "模型 Universe 只用于 Alpha/Qlib；生产覆盖范围继续由数据中心维护。",
            "写操作需管理员权限，保存或触发训练前必须确认影响。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "qlib-runtime-status",
            "title": "一、Qlib 运行条件",
            "kind": "detail",
            "action_key": "config_center.qlib_runtime",
            "layout_area": "runtime",
            "target_screen": "system.qlib-center",
            "empty_message": "暂无 Qlib 运行配置。",
            "error_message": "Qlib 运行配置读取失败，请稍后重试。",
            "stale_message": "运行配置可能已经变化，请刷新后再操作。",
            "user_priority": "p0",
            "presentation_semantic": "primary_status",
        },
        {
            "key": "qlib-alpha-universes",
            "title": "二、模型 Universe",
            "kind": "datagrid",
            "action_key": "config_center.alpha_universes",
            "max_rows": 8,
            "layout_area": "universes",
            "target_screen": "system.qlib-center",
            "empty_message": "暂无自定义模型 Universe，可从任务区新建。",
            "user_priority": "p0",
            "presentation_semantic": "primary_list",
        },
        {
            "key": "qlib-training-runs",
            "title": "三、最近训练记录",
            "kind": "datagrid",
            "action_key": "config_center.training_runs",
            "max_rows": 8,
            "layout_area": "training_runs",
            "target_screen": "system.qlib-center",
            "empty_message": "暂无训练记录，可从任务区选择模板并触发训练。",
            "user_priority": "p1",
            "presentation_semantic": "supporting_list",
        },
    ],
}

RUNTIME_CONFIG_CENTER_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "config_center.alpha_universes",
        "label": "Alpha/Qlib 模型 Universe",
        "endpoint": "/api/system/config-center/qlib/alpha-universes/",
        "intent": "list_alpha_universes",
        "screen_key": "system.qlib-center",
        "module_key": "system-governance",
        "view_type": "datagrid",
        "risk": "admin",
        "view_model": {
            "kind": "datagrid",
            "rows_path": "data",
        },
        "description": "查看用于 Alpha 评分、Qlib 数据构建和训练的模型 Universe；不影响 Data Center 生产覆盖验收口径。",
        "source": "approved:runtime-config-center-alpha-universe",
        "task_group": "02 Alpha Universe",
        "sequence": 15,
        "task_tier": "operation",
    },
    {
        "key": "config_center.alpha_universe_members",
        "label": "Alpha/Qlib 模型 Universe 成员",
        "endpoint": "/api/system/config-center/qlib/alpha-universes/<str:universe_id>/members/",
        "intent": "read_alpha_universe_members",
        "screen_key": "system.qlib-center",
        "module_key": "system-governance",
        "view_type": "datagrid",
        "risk": "admin",
        "fields": [
            {
                "key": "universe_id",
                "label": "Universe ID",
                "input_type": "text",
                "required": True,
                "binding": "path",
                "default": "all_a_share",
                "placeholder": "all_a_share",
                "value_type": "string",
            },
            {
                "key": "limit",
                "label": "返回数量",
                "input_type": "number",
                "required": False,
                "binding": "query",
                "default": 100,
                "placeholder": "100",
                "value_type": "integer",
            },
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "data.members",
            "total_path": "data.member_count",
        },
        "description": "按模型 Universe ID 解析实际成分股，用于确认 Alpha/Qlib 选股范围；不用于 readiness 覆盖分母。",
        "source": "approved:runtime-config-center-alpha-universe",
        "task_group": "02 Alpha Universe",
        "sequence": 16,
        "task_tier": "operation",
    },
    {
        "key": "config_center.alpha_universe_save",
        "label": "保存 Alpha/Qlib 模型 Universe",
        "method": "POST",
        "endpoint": "/api/system/config-center/qlib/alpha-universes/",
        "intent": "save_alpha_universe",
        "screen_key": "system.qlib-center",
        "module_key": "system-governance",
        "view_type": "detail",
        "risk": "admin",
        "effect": "update",
        "confirmation_required": True,
        "fields": [
            {
                "key": "universe_id",
                "label": "Universe ID",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "default": "all_a_share",
                "placeholder": "all_a_share",
                "value_type": "string",
            },
            {
                "key": "name",
                "label": "名称",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "default": "全 A 股票池",
                "placeholder": "全 A 股票池",
                "value_type": "string",
            },
            {
                "key": "source_type",
                "label": "来源类型",
                "input_type": "select",
                "required": True,
                "binding": "body",
                "default": "data_center_filter",
                "placeholder": "",
                "value_type": "string",
                "options": ["manual", "csv", "data_center_filter"],
            },
            {
                "key": "stock_codes",
                "label": "股票代码",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "default": [],
                "placeholder": '["000001.SZ", "688001.SH"]',
                "value_type": "list",
            },
            {
                "key": "filters",
                "label": "过滤条件",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "default": {
                    "asset_type": "stock",
                    "exchanges": ["SSE", "SZSE", "BSE"],
                    "boards": [],
                    "include_inactive": False,
                },
                "placeholder": '{"asset_type":"stock","exchanges":["SSE","SZSE","BSE"]}',
                "value_type": "object",
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "checkbox",
                "required": False,
                "binding": "body",
                "default": True,
                "placeholder": "",
                "value_type": "boolean",
            },
            {
                "key": "description",
                "label": "说明",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "default": "",
                "placeholder": "",
                "value_type": "string",
            },
        ],
        "description": "创建或更新一个可供 Runtime 默认值、Alpha 评分和训练任务引用的模型 Universe；生产覆盖验收请使用 Data Center Universe。",
        "source": "approved:runtime-config-center-alpha-universe",
        "task_group": "00 管理操作",
        "sequence": 15,
        "task_tier": "operation",
    },
)
