"""Structured registries for runtime screen patches."""

from __future__ import annotations

from .tui_metadata_runtime_screen_patch_command_center import (
    RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_COMMAND_CENTER,
    RUNTIME_SCREEN_PATCHES_COMMAND_CENTER,
)
from .tui_metadata_runtime_screen_patch_execution import (
    RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_EXECUTION,
    RUNTIME_SCREEN_PATCHES_EXECUTION,
)
from .tui_metadata_runtime_screen_patch_macro_data import (
    RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_MACRO_DATA,
    RUNTIME_SCREEN_PATCHES_MACRO_DATA,
)
from .tui_metadata_runtime_screen_patch_ops import (
    RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_OPS,
    RUNTIME_SCREEN_PATCHES_OPS,
)
from .tui_metadata_runtime_screen_patch_research import (
    RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_RESEARCH,
    RUNTIME_SCREEN_PATCHES_RESEARCH,
)

RUNTIME_SCREEN_PATCHES = {
    **RUNTIME_SCREEN_PATCHES_COMMAND_CENTER,
    **RUNTIME_SCREEN_PATCHES_EXECUTION,
    **RUNTIME_SCREEN_PATCHES_MACRO_DATA,
    **RUNTIME_SCREEN_PATCHES_OPS,
    **RUNTIME_SCREEN_PATCHES_RESEARCH,
}

RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS = {
    **RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_COMMAND_CENTER,
    **RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_EXECUTION,
    **RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_MACRO_DATA,
    **RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_OPS,
    **RUNTIME_REDUNDANT_SCREEN_ACTION_KEYS_RESEARCH,
}
