"""Runtime TUI metadata injections for AI/MCP identity and access workflows."""

from __future__ import annotations

from typing import Any

RUNTIME_MCP_SELF_SERVICE_SCREEN: dict[str, Any] = {
    "key": "capability-router.self-service",
    "label": "我的 MCP 接入",
    "module_key": "capability-router",
    "group": "ops",
    "summary": "管理自己的 MCP Token、读写级别，以及一键复制给 AI Agent 的接入提示词。",
    "view_type": "detail",
    "default_action_key": "capability-router.mcp-self-status",
    "workflow": {
        "name": "能力接入流程",
        "step": 2,
        "total": 3,
        "label": "个人接入",
        "role": "先确认自己是否已开通 MCP，再生成 Token 并复制 Agent 接入提示词。",
        "previous": {"key": "capability-router.gateway", "label": "能力路由接入"},
        "next": {},
    },
    "business_context": {
        "objective": "在 TUI 内完成个人 MCP 接入，不再依赖网页表单。",
        "decision_output": "当前权限状态、可用 Token、推荐接入 Prompt，以及是否需要新建或撤销 Token。",
        "checkpoints": [
            "先读个人 MCP 状态，确认 mcp_enabled、默认账户和可复制 Prompt。",
            "需要新 Token 时明确读写级别，再执行创建。",
            "旧 Token 不再使用时立即撤销，避免凭证扩散。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "mcp-self-status",
            "title": "一、我的 MCP 状态",
            "kind": "detail",
            "action_key": "capability-router.mcp-self-status",
            "layout_area": "summary",
            "target_screen": "capability-router.self-service",
        },
        {
            "key": "mcp-self-tokens",
            "title": "二、我的 Token",
            "kind": "datagrid",
            "action_key": "capability-router.list-my-mcp-tokens",
            "max_rows": 8,
            "layout_area": "tokens",
            "target_screen": "capability-router.self-service",
            "columns": [
                {"key": "name", "label": "名称"},
                {"key": "preview", "label": "预览"},
                {"key": "access_level_label", "label": "级别"},
                {"key": "created_at", "label": "创建时间"},
                {"key": "last_used_at", "label": "最后使用"},
            ],
        },
    ],
}

RUNTIME_MCP_ADMIN_ACCESS_SCREEN: dict[str, Any] = {
    "key": "capability-router.admin-access",
    "label": "MCP 用户治理",
    "module_key": "capability-router",
    "group": "ops",
    "summary": "管理员在 TUI 内管理用户 MCP 开关、Token 发放与撤销。",
    "view_type": "detail",
    "default_action_key": "capability-router.mcp-admin-users",
    "workflow": {
        "name": "能力接入流程",
        "step": 3,
        "total": 3,
        "label": "管理员治理",
        "role": "先筛用户，再发 Token、控读写权限并回收凭证。",
        "previous": {"key": "capability-router.mcp-center", "label": "MCP 接入中心"},
        "next": {},
    },
    "business_context": {
        "objective": "让管理员在 TUI 内闭环管理普通用户与管理员自己的 MCP 凭证策略。",
        "decision_output": "哪些用户未开通 MCP、哪些 Token 仍在使用、哪些读写凭证需要收紧。",
        "checkpoints": [
            "先看用户列表和 without_token 过滤，定位待发放用户。",
            "发放 Token 时明确 access_level，不默认给读写。",
            "关闭用户 MCP 时同步回收其有效 Token。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "mcp-admin-users",
            "title": "一、用户与 Token 分布",
            "kind": "datagrid",
            "action_key": "capability-router.mcp-admin-users",
            "max_rows": 10,
            "layout_area": "users",
            "target_screen": "capability-router.admin-access",
            "columns": [
                {"key": "username", "label": "用户"},
                {"key": "rbac_role", "label": "角色"},
                {"key": "mcp_enabled", "label": "MCP"},
                {"key": "token_count", "label": "Token 数"},
                {"key": "read_only_token_count", "label": "只读数"},
            ],
        }
    ],
}

RUNTIME_AI_MY_PROVIDERS_SCREEN: dict[str, Any] = {
    "key": "ai-ops.my-providers",
    "label": "我的 AI 服务商",
    "module_key": "ai-ops",
    "group": "ops",
    "summary": "管理个人 AI Provider、查看自己的 fallback quota 和调用日志。",
    "view_type": "detail",
    "default_action_key": "ai-ops.list-my-providers",
    "workflow": {
        "name": "AI 管理流程",
        "step": 1,
        "total": 3,
        "label": "个人 Provider",
        "role": "先看个人 Provider 是否可用，再检查自己配额与最近调用日志。",
        "previous": {"key": "ai-ops.providers", "label": "AI 服务商与用量"},
        "next": {},
    },
    "business_context": {
        "objective": "普通用户在 TUI 内完成个人 AI 接入与自查。",
        "decision_output": "当前个人 Provider 列表、启用状态、剩余额度以及最近失败日志。",
        "checkpoints": [
            "先看个人 Provider 列表与启用状态。",
            "需要新增密钥时在 TUI 直接创建或更新个人 Provider。",
            "调用异常时对照 quota 与 logs 定位是否是额度或上游故障。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "my-provider-list",
            "title": "一、我的 Provider",
            "kind": "datagrid",
            "action_key": "ai-ops.list-my-providers",
            "max_rows": 8,
            "layout_area": "providers",
            "target_screen": "ai-ops.my-providers",
            "columns": [
                {"key": "name", "label": "名称"},
                {"key": "provider_type_label", "label": "类型"},
                {"key": "default_model", "label": "默认模型"},
                {"key": "is_active", "label": "启用"},
                {"key": "priority", "label": "优先级"},
            ],
        },
        {
            "key": "my-provider-quota",
            "title": "二、我的 Fallback Quota",
            "kind": "detail",
            "action_key": "ai-ops.my-quota-current",
            "layout_area": "quota",
            "target_screen": "ai-ops.my-providers",
        },
        {
            "key": "my-provider-logs",
            "title": "三、最近调用日志",
            "kind": "datagrid",
            "action_key": "ai-ops.my-ai-logs",
            "max_rows": 8,
            "layout_area": "logs",
            "target_screen": "ai-ops.my-providers",
            "columns": [
                {"key": "provider_name", "label": "Provider"},
                {"key": "model", "label": "模型"},
                {"key": "status", "label": "状态"},
                {"key": "estimated_cost", "label": "成本"},
                {"key": "created_at", "label": "时间"},
            ],
        },
    ],
}

RUNTIME_AI_SYSTEM_PROVIDERS_SCREEN: dict[str, Any] = {
    "key": "ai-ops.system-providers",
    "label": "系统 AI 服务商",
    "module_key": "ai-ops",
    "group": "ops",
    "summary": "管理员在 TUI 内管理系统级 AI Provider、连通性与使用统计。",
    "view_type": "detail",
    "default_action_key": "ai-ops.system-provider-overall-stats",
    "workflow": {
        "name": "AI 管理流程",
        "step": 2,
        "total": 3,
        "label": "系统 Provider",
        "role": "先看系统 Provider 总体可用性，再处理创建、切换和连通性测试。",
        "previous": {"key": "ai-ops.my-providers", "label": "我的 AI 服务商"},
        "next": {"key": "ai-ops.user-quotas", "label": "用户 AI 配额"},
    },
    "business_context": {
        "objective": "把系统 Provider 的 CRUD、启停和测试能力拉进 TUI。",
        "decision_output": "系统 Provider 总量、启用状态、最近用量以及是否需要切换默认路由。",
        "checkpoints": [
            "先看 overall stats，确认系统可用 Provider 数量。",
            "新增或修改时保持 base_url、api_mode 与默认模型一致。",
            "变更后立即跑 test-connection，不把未验证配置直接交给业务流量。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "system-provider-overall-stats",
            "title": "一、系统 Provider 概览",
            "kind": "detail",
            "action_key": "ai-ops.system-provider-overall-stats",
            "layout_area": "summary",
            "target_screen": "ai-ops.system-providers",
        },
        {
            "key": "system-provider-list",
            "title": "二、系统 Provider 列表",
            "kind": "datagrid",
            "action_key": "ai-ops.list-system-providers",
            "max_rows": 10,
            "layout_area": "providers",
            "target_screen": "ai-ops.system-providers",
            "columns": [
                {"key": "name", "label": "名称"},
                {"key": "provider_type_label", "label": "类型"},
                {"key": "default_model", "label": "默认模型"},
                {"key": "is_active", "label": "启用"},
                {"key": "priority", "label": "优先级"},
            ],
        },
    ],
}

RUNTIME_AI_USER_QUOTAS_SCREEN: dict[str, Any] = {
    "key": "ai-ops.user-quotas",
    "label": "用户 AI 配额",
    "module_key": "ai-ops",
    "group": "ops",
    "summary": "管理员在 TUI 内查看和调整用户 fallback quota。",
    "view_type": "detail",
    "default_action_key": "ai-ops.list-user-quotas",
    "workflow": {
        "name": "AI 管理流程",
        "step": 3,
        "total": 3,
        "label": "配额治理",
        "role": "先看用户配额列表，再做单用户修正或批量下发。",
        "previous": {"key": "ai-ops.system-providers", "label": "系统 AI 服务商"},
        "next": {},
    },
    "business_context": {
        "objective": "把管理员对普通用户 AI fallback quota 的治理能力拉进 TUI。",
        "decision_output": "哪些用户已超预算、哪些用户未配置、哪些批量策略需要更新。",
        "checkpoints": [
            "先看列表确认 daily/monthly spent 与 is_active。",
            "单用户修正优先用 PATCH，批量策略再用 batch apply。",
            "批量覆盖前确认 overwrite_existing，避免误伤已定制配额。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "user-quota-list",
            "title": "一、用户配额列表",
            "kind": "datagrid",
            "action_key": "ai-ops.list-user-quotas",
            "max_rows": 12,
            "layout_area": "quotas",
            "target_screen": "ai-ops.user-quotas",
            "columns": [
                {"key": "username", "label": "用户"},
                {"key": "daily_limit", "label": "日额度"},
                {"key": "monthly_limit", "label": "月额度"},
                {"key": "daily_spent", "label": "今日已用"},
                {"key": "monthly_spent", "label": "本月已用"},
                {"key": "is_active", "label": "启用"},
            ],
        }
    ],
}

RUNTIME_IDENTITY_ACCESS_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "capability-router.mcp-self-status",
        "label": "读取我的 MCP 状态",
        "endpoint": "/api/account/mcp/self/",
        "method": "GET",
        "intent": "read_current_user_mcp_self_service",
        "risk": "read",
        "screen_key": "capability-router.self-service",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "读取当前用户的 MCP 开通状态、默认账户、Token 与 Agent Prompt。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 100,
        "task_tier": "primary",
        "fields": [],
        "view_model": {"kind": "detail", "title_path": "username", "status_path": "mcp_enabled"},
    },
    {
        "key": "capability-router.list-my-mcp-tokens",
        "label": "读取我的 Token 列表",
        "endpoint": "/api/account/mcp/self/",
        "method": "GET",
        "intent": "list_current_user_mcp_tokens",
        "risk": "read",
        "screen_key": "capability-router.self-service",
        "module_key": "capability-router",
        "view_type": "datagrid",
        "description": "从个人 MCP 状态接口中提取自己的有效 Token 列表。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 110,
        "task_tier": "support",
        "fields": [],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "access_tokens",
            "total_path": "active_token_count",
        },
    },
    {
        "key": "capability-router.create-my-mcp-token",
        "label": "创建我的 MCP Token",
        "endpoint": "/api/account/mcp/tokens/",
        "method": "POST",
        "intent": "create_current_user_mcp_token",
        "risk": "write",
        "screen_key": "capability-router.self-service",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "为当前用户创建一个新的 MCP Token，并返回可直接粘贴给 Agent 的 Prompt。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 120,
        "task_tier": "primary",
        "fields": [
            {
                "key": "token_name",
                "label": "Token 名称",
                "input_type": "text",
                "required": False,
                "placeholder": "留空则自动生成",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "access_level",
                "label": "访问级别",
                "input_type": "select",
                "required": True,
                "default": "read_only",
                "binding": "body",
                "value_type": "string",
                "options": ["read_only", "read_write"],
            },
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "capability-router.revoke-my-mcp-token",
        "label": "撤销我的 MCP Token",
        "endpoint": "/api/account/mcp/tokens/<int:token_id>/revoke/",
        "method": "POST",
        "intent": "revoke_current_user_mcp_token",
        "risk": "write",
        "screen_key": "capability-router.self-service",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "撤销当前用户自己名下的一个有效 MCP Token。",
        "source": "approved:runtime-identity-access",
        "task_group": "01 个人 MCP",
        "sequence": 130,
        "task_tier": "support",
        "fields": [
            {
                "key": "token_id",
                "label": "Token ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "capability-router.mcp-admin-users",
        "label": "读取 MCP 用户列表",
        "endpoint": "/api/account/admin/mcp/users/",
        "method": "GET",
        "intent": "list_admin_mcp_user_governance_rows",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "datagrid",
        "description": "读取管理员视角下的 MCP 用户、Token 与开关分布。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 200,
        "task_tier": "primary",
        "fields": [
            {
                "key": "q",
                "label": "关键词",
                "input_type": "text",
                "required": False,
                "default": "",
                "placeholder": "搜索用户名或邮箱",
                "binding": "query",
                "value_type": "string",
            },
            {
                "key": "without_token",
                "label": "仅无 Token",
                "input_type": "select",
                "required": False,
                "default": "false",
                "binding": "query",
                "value_type": "boolean",
                "options": ["false", "true"],
            },
        ],
        "view_model": {"kind": "datagrid", "rows_path": "rows", "total_path": "total_users"},
    },
    {
        "key": "capability-router.mcp-admin-user-detail",
        "label": "读取用户 MCP 详情",
        "endpoint": "/api/account/admin/mcp/users/<int:user_id>/",
        "method": "GET",
        "intent": "read_admin_mcp_user_detail",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "查看单个用户的 MCP 状态、Token 以及可复制 Prompt。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 210,
        "task_tier": "support",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "username", "status_path": "mcp_enabled"},
    },
    {
        "key": "capability-router.admin-create-mcp-token",
        "label": "为用户创建 MCP Token",
        "endpoint": "/api/account/admin/mcp/users/<int:user_id>/tokens/",
        "method": "POST",
        "intent": "create_admin_managed_mcp_token",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "管理员为指定用户创建一个新 Token，并返回可转发给 Agent 的 Prompt。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 220,
        "task_tier": "primary",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "token_name",
                "label": "Token 名称",
                "input_type": "text",
                "required": False,
                "placeholder": "留空则自动生成",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "access_level",
                "label": "访问级别",
                "input_type": "select",
                "required": True,
                "default": "read_only",
                "binding": "body",
                "value_type": "string",
                "options": ["read_only", "read_write"],
            },
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "capability-router.admin-toggle-user-mcp",
        "label": "切换用户 MCP 开关",
        "endpoint": "/api/account/admin/mcp/users/<int:user_id>/toggle/",
        "method": "POST",
        "intent": "toggle_admin_managed_user_mcp",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "管理员直接开启或关闭用户 MCP 权限。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 230,
        "task_tier": "primary",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "capability-router.admin-revoke-user-mcp-tokens",
        "label": "撤销用户全部 Token",
        "endpoint": "/api/account/admin/mcp/users/<int:user_id>/tokens/revoke/",
        "method": "POST",
        "intent": "revoke_admin_managed_user_mcp_tokens",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "管理员一次性回收指定用户的全部 MCP Token。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 240,
        "task_tier": "support",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "capability-router.admin-revoke-mcp-token",
        "label": "撤销单个用户 Token",
        "endpoint": "/api/account/admin/mcp/tokens/<int:token_id>/revoke/",
        "method": "POST",
        "intent": "revoke_admin_managed_single_mcp_token",
        "risk": "admin",
        "screen_key": "capability-router.admin-access",
        "module_key": "capability-router",
        "view_type": "detail",
        "description": "管理员按 token_id 回收单个 MCP Token。",
        "source": "approved:runtime-identity-access",
        "task_group": "02 管理员 MCP",
        "sequence": 250,
        "task_tier": "support",
        "fields": [
            {
                "key": "token_id",
                "label": "Token ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "ai-ops.list-my-providers",
        "label": "读取我的 AI Provider",
        "endpoint": "/api/ai/me/providers/",
        "method": "GET",
        "intent": "list_current_user_ai_providers",
        "risk": "read",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "datagrid",
        "description": "读取当前用户自己的 AI Provider 列表。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 300,
        "task_tier": "primary",
        "fields": [],
        "view_model": {"kind": "datagrid"},
    },
    {
        "key": "ai-ops.my-provider-detail",
        "label": "读取我的 Provider 详情",
        "endpoint": "/api/ai/me/providers/<int:provider_id>/",
        "method": "GET",
        "intent": "read_current_user_ai_provider_detail",
        "risk": "read",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取一个个人 AI Provider 的配置详情。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 310,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "Provider ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.create-my-provider",
        "label": "创建我的 Provider",
        "endpoint": "/api/ai/me/providers/",
        "method": "POST",
        "intent": "create_current_user_ai_provider",
        "risk": "write",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "为当前用户创建一个新的个人 AI Provider。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 320,
        "task_tier": "primary",
        "fields": [
            {
                "key": "name",
                "label": "名称",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "provider_type",
                "label": "类型",
                "input_type": "select",
                "required": True,
                "default": "openai",
                "binding": "body",
                "value_type": "string",
                "options": ["openai", "deepseek", "qwen", "moonshot", "custom"],
            },
            {
                "key": "base_url",
                "label": "Base URL",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_key",
                "label": "API Key",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "default_model",
                "label": "默认模型",
                "input_type": "text",
                "required": False,
                "default": "gpt-3.5-turbo",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_mode",
                "label": "API 模式",
                "input_type": "select",
                "required": False,
                "default": "dual",
                "binding": "body",
                "value_type": "string",
                "options": ["dual", "responses_only", "chat_only"],
            },
            {
                "key": "priority",
                "label": "优先级",
                "input_type": "number",
                "required": False,
                "default": "10",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "select",
                "required": False,
                "default": "true",
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.update-my-provider",
        "label": "更新我的 Provider",
        "endpoint": "/api/ai/me/providers/<int:provider_id>/",
        "method": "PATCH",
        "intent": "update_current_user_ai_provider",
        "risk": "write",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "更新一个已有的个人 AI Provider。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 330,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "Provider ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "name",
                "label": "名称",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "provider_type",
                "label": "类型",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "string",
                "options": ["openai", "deepseek", "qwen", "moonshot", "custom"],
            },
            {
                "key": "base_url",
                "label": "Base URL",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_key",
                "label": "API Key",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "default_model",
                "label": "默认模型",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_mode",
                "label": "API 模式",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "string",
                "options": ["dual", "responses_only", "chat_only"],
            },
            {
                "key": "priority",
                "label": "优先级",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.toggle-my-provider",
        "label": "切换我的 Provider 启用",
        "endpoint": "/api/ai/me/providers/<int:provider_id>/toggle_active/",
        "method": "POST",
        "intent": "toggle_current_user_ai_provider",
        "risk": "write",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "切换个人 AI Provider 的启用状态。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 340,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "Provider ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.delete-my-provider",
        "label": "删除我的 Provider",
        "endpoint": "/api/ai/me/providers/<int:provider_id>/",
        "method": "DELETE",
        "intent": "delete_current_user_ai_provider",
        "risk": "write",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "message",
        "description": "删除一个个人 AI Provider。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 350,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "Provider ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "message"},
    },
    {
        "key": "ai-ops.my-quota-current",
        "label": "读取我的 Quota",
        "endpoint": "/api/ai/me/quota/current/",
        "method": "GET",
        "intent": "read_current_user_ai_quota",
        "risk": "read",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取当前用户自己的 fallback quota 使用状态。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 360,
        "task_tier": "support",
        "fields": [],
        "view_model": {"kind": "detail", "title_path": "username", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.my-ai-logs",
        "label": "读取我的 AI 日志",
        "endpoint": "/api/ai/me/logs/",
        "method": "GET",
        "intent": "list_current_user_ai_logs",
        "risk": "read",
        "screen_key": "ai-ops.my-providers",
        "module_key": "ai-ops",
        "view_type": "datagrid",
        "description": "读取当前用户自己的 AI 调用日志。",
        "source": "approved:runtime-identity-access",
        "task_group": "03 个人 AI",
        "sequence": 370,
        "task_tier": "support",
        "fields": [
            {
                "key": "status",
                "label": "状态",
                "input_type": "text",
                "required": False,
                "default": "",
                "binding": "query",
                "value_type": "string",
            },
            {
                "key": "provider_scope",
                "label": "Provider 范围",
                "input_type": "text",
                "required": False,
                "default": "",
                "binding": "query",
                "value_type": "string",
            },
            {
                "key": "limit",
                "label": "返回行数",
                "input_type": "hidden",
                "required": False,
                "default": "50",
                "binding": "query",
                "value_type": "integer",
            },
        ],
        "view_model": {"kind": "datagrid"},
    },
    {
        "key": "ai-ops.system-provider-overall-stats",
        "label": "读取系统 Provider 概览",
        "endpoint": "/api/ai/providers/overall_stats/",
        "method": "GET",
        "intent": "read_admin_ai_provider_overall_stats",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取管理员视角下的系统 Provider 总体统计。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 400,
        "task_tier": "primary",
        "fields": [],
        "view_model": {"kind": "detail"},
    },
    {
        "key": "ai-ops.list-system-providers",
        "label": "读取系统 Provider 列表",
        "endpoint": "/api/ai/providers/",
        "method": "GET",
        "intent": "list_admin_ai_system_providers",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "datagrid",
        "description": "读取系统级 AI Provider 列表。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 410,
        "task_tier": "primary",
        "fields": [],
        "view_model": {"kind": "datagrid"},
    },
    {
        "key": "ai-ops.system-provider-detail",
        "label": "读取系统 Provider 详情",
        "endpoint": "/api/ai/providers/<int:provider_id>/",
        "method": "GET",
        "intent": "read_admin_ai_system_provider_detail",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取一个系统级 AI Provider 的配置详情。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 420,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "Provider ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.create-system-provider",
        "label": "创建系统 Provider",
        "endpoint": "/api/ai/providers/",
        "method": "POST",
        "intent": "create_admin_ai_system_provider",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "创建一个系统级 AI Provider。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 430,
        "task_tier": "primary",
        "fields": [
            {
                "key": "name",
                "label": "名称",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "provider_type",
                "label": "类型",
                "input_type": "select",
                "required": True,
                "default": "openai",
                "binding": "body",
                "value_type": "string",
                "options": ["openai", "deepseek", "qwen", "moonshot", "custom"],
            },
            {
                "key": "base_url",
                "label": "Base URL",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_key",
                "label": "API Key",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "default_model",
                "label": "默认模型",
                "input_type": "text",
                "required": False,
                "default": "gpt-3.5-turbo",
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_mode",
                "label": "API 模式",
                "input_type": "select",
                "required": False,
                "default": "dual",
                "binding": "body",
                "value_type": "string",
                "options": ["dual", "responses_only", "chat_only"],
            },
            {
                "key": "priority",
                "label": "优先级",
                "input_type": "number",
                "required": False,
                "default": "10",
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "select",
                "required": False,
                "default": "true",
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.update-system-provider",
        "label": "更新系统 Provider",
        "endpoint": "/api/ai/providers/<int:provider_id>/",
        "method": "PATCH",
        "intent": "update_admin_ai_system_provider",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "更新一个系统级 AI Provider。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 440,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "Provider ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "name",
                "label": "名称",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "provider_type",
                "label": "类型",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "string",
                "options": ["openai", "deepseek", "qwen", "moonshot", "custom"],
            },
            {
                "key": "base_url",
                "label": "Base URL",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_key",
                "label": "API Key",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "default_model",
                "label": "默认模型",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "api_mode",
                "label": "API 模式",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "string",
                "options": ["dual", "responses_only", "chat_only"],
            },
            {
                "key": "priority",
                "label": "优先级",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "integer",
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.toggle-system-provider",
        "label": "切换系统 Provider 启用",
        "endpoint": "/api/ai/providers/<int:provider_id>/toggle_active/",
        "method": "POST",
        "intent": "toggle_admin_ai_system_provider",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "切换系统级 AI Provider 的启用状态。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 450,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "Provider ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "name", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.test-system-provider",
        "label": "测试系统 Provider 连通性",
        "endpoint": "/api/ai/providers/<int:provider_id>/test-connection/",
        "method": "POST",
        "intent": "test_admin_ai_system_provider_connection",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "测试一个系统级 AI Provider 的连通性。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 460,
        "task_tier": "primary",
        "fields": [
            {
                "key": "provider_id",
                "label": "Provider ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail"},
    },
    {
        "key": "ai-ops.system-provider-usage-stats",
        "label": "读取系统 Provider 用量",
        "endpoint": "/api/ai/providers/<int:provider_id>/usage_stats/",
        "method": "GET",
        "intent": "read_admin_ai_system_provider_usage_stats",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取一个系统级 AI Provider 的今日、本月用量与预算状态。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 470,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "Provider ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "provider_name"},
    },
    {
        "key": "ai-ops.delete-system-provider",
        "label": "删除系统 Provider",
        "endpoint": "/api/ai/providers/<int:provider_id>/",
        "method": "DELETE",
        "intent": "delete_admin_ai_system_provider",
        "risk": "admin",
        "screen_key": "ai-ops.system-providers",
        "module_key": "ai-ops",
        "view_type": "message",
        "description": "删除一个系统级 AI Provider。",
        "source": "approved:runtime-identity-access",
        "task_group": "04 管理员 AI",
        "sequence": 480,
        "task_tier": "support",
        "fields": [
            {
                "key": "provider_id",
                "label": "Provider ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "message"},
    },
    {
        "key": "ai-ops.list-user-quotas",
        "label": "读取用户 AI 配额",
        "endpoint": "/api/ai/admin/quotas/",
        "method": "GET",
        "intent": "list_admin_user_ai_quotas",
        "risk": "admin",
        "screen_key": "ai-ops.user-quotas",
        "module_key": "ai-ops",
        "view_type": "datagrid",
        "description": "读取所有用户的 fallback quota 列表。",
        "source": "approved:runtime-identity-access",
        "task_group": "05 配额治理",
        "sequence": 500,
        "task_tier": "primary",
        "fields": [],
        "view_model": {"kind": "datagrid"},
    },
    {
        "key": "ai-ops.user-quota-detail",
        "label": "读取用户 AI 配额详情",
        "endpoint": "/api/ai/admin/quotas/<int:user_id>/",
        "method": "GET",
        "intent": "read_admin_user_ai_quota_detail",
        "risk": "admin",
        "screen_key": "ai-ops.user-quotas",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "读取单个用户的 fallback quota 详情。",
        "source": "approved:runtime-identity-access",
        "task_group": "05 配额治理",
        "sequence": 510,
        "task_tier": "support",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            }
        ],
        "view_model": {"kind": "detail", "title_path": "username", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.update-user-quota",
        "label": "更新用户 AI 配额",
        "endpoint": "/api/ai/admin/quotas/<int:user_id>/",
        "method": "PATCH",
        "intent": "update_admin_user_ai_quota",
        "risk": "admin",
        "screen_key": "ai-ops.user-quotas",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "更新单个用户的 daily/monthly fallback quota。",
        "source": "approved:runtime-identity-access",
        "task_group": "05 配额治理",
        "sequence": 520,
        "task_tier": "primary",
        "fields": [
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "daily_limit",
                "label": "日额度",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "monthly_limit",
                "label": "月额度",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "select",
                "required": False,
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
            {
                "key": "admin_note",
                "label": "管理员备注",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "detail", "title_path": "username", "status_path": "is_active"},
    },
    {
        "key": "ai-ops.batch-apply-user-quotas",
        "label": "批量下发用户 AI 配额",
        "endpoint": "/api/ai/admin/quotas/batch_apply/",
        "method": "POST",
        "intent": "batch_apply_admin_user_ai_quota",
        "risk": "admin",
        "screen_key": "ai-ops.user-quotas",
        "module_key": "ai-ops",
        "view_type": "detail",
        "description": "批量下发一套 fallback quota 到用户集合。",
        "source": "approved:runtime-identity-access",
        "task_group": "05 配额治理",
        "sequence": 530,
        "task_tier": "primary",
        "fields": [
            {
                "key": "daily_limit",
                "label": "日额度",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "monthly_limit",
                "label": "月额度",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "float",
            },
            {
                "key": "overwrite_existing",
                "label": "覆盖既有配置",
                "input_type": "select",
                "required": False,
                "default": "false",
                "binding": "body",
                "value_type": "boolean",
                "options": ["false", "true"],
            },
            {
                "key": "is_active",
                "label": "启用",
                "input_type": "select",
                "required": False,
                "default": "true",
                "binding": "body",
                "value_type": "boolean",
                "options": ["true", "false"],
            },
            {
                "key": "admin_note",
                "label": "管理员备注",
                "input_type": "textarea",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
        ],
        "view_model": {"kind": "detail"},
    },
)
