"""Runtime TUI metadata for simulated-trading account records."""

from __future__ import annotations

from typing import Any

_SCREEN = "execution.accounts"
_MODULE = "daily-decisions"
_SOURCE = "approved:runtime-simulated-trading"


def _account_id() -> dict[str, Any]:
    """Build one owned-account path parameter."""

    return {
        "key": "account_id",
        "label": "账户 ID",
        "binding": "path",
        "input_type": "number",
        "value_type": "integer",
        "required": True,
        "min": 1,
    }


RUNTIME_SIMULATED_TRADING_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "simulated-trading.accounts",
        "label": "查看我的投资账户",
        "endpoint": "/api/simulated-trading/accounts/",
        "method": "GET",
        "intent": "read_owned_accounts",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "datagrid",
        "description": "查看本人名下实仓与模拟仓的资产、现金、收益和运行状态。",
        "source": _SOURCE,
        "task_group": "06 模拟交易记录",
        "sequence": 600,
        "task_tier": "operation",
        "fields": [
            {
                "key": "active_only",
                "label": "只看活跃账户",
                "binding": "query",
                "input_type": "checkbox",
                "value_type": "boolean",
                "required": False,
                "default": True,
            },
            {
                "key": "account_type",
                "label": "账户类型",
                "binding": "query",
                "input_type": "select",
                "value_type": "string",
                "required": False,
                "options": ["real", "simulated"],
            },
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "accounts",
            "columns": [
                {"key": "account_id", "label": "账户 ID"},
                {"key": "account_name", "label": "账户名称"},
                {"key": "account_type", "label": "类型"},
                {"key": "total_value", "label": "总资产"},
                {"key": "current_cash", "label": "现金"},
                {"key": "total_return", "label": "总收益率"},
                {"key": "is_active", "label": "活跃"},
                {"key": "auto_trading_enabled", "label": "自动交易"},
            ],
        },
    },
    {
        "key": "simulated-trading.account-detail",
        "label": "查看账户详情",
        "endpoint": "/api/simulated-trading/accounts/<int:account_id>/",
        "method": "GET",
        "intent": "read_owned_account_detail",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "查看本人账户的资产、收益、交易统计与风控参数。",
        "source": _SOURCE,
        "task_group": "06 模拟交易记录",
        "sequence": 610,
        "task_tier": "operation",
        "fields": [_account_id()],
        "view_model": {"kind": "detail", "title_path": "account.account_name"},
    },
    {
        "key": "simulated-trading.account-create",
        "label": "创建投资账户",
        "endpoint": "/api/simulated-trading/accounts/",
        "method": "POST",
        "intent": "create_owned_account",
        "risk": "write",
        "audience": "authenticated",
        "effect": "create",
        "confirmation_required": True,
        "audit_required": True,
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "创建本人名下的实仓或模拟仓账户。",
        "source": _SOURCE,
        "task_group": "06 模拟交易记录",
        "sequence": 620,
        "task_tier": "operation",
        "fields": [
            {
                "key": "account_name",
                "label": "账户名称",
                "binding": "body",
                "input_type": "text",
                "value_type": "string",
                "required": True,
                "max": 100,
            },
            {
                "key": "account_type",
                "label": "账户类型",
                "binding": "body",
                "input_type": "select",
                "value_type": "string",
                "required": True,
                "default": "simulated",
                "options": ["real", "simulated"],
            },
            {
                "key": "initial_capital",
                "label": "初始资金（元）",
                "binding": "body",
                "input_type": "number",
                "value_type": "float",
                "required": True,
                "min": 1000,
            },
            {
                "key": "max_position_pct",
                "label": "单资产持仓上限（%）",
                "binding": "body",
                "input_type": "number",
                "value_type": "float",
                "required": False,
                "default": 20,
                "min": 1,
                "max": 100,
            },
            {
                "key": "stop_loss_pct",
                "label": "止损比例（%）",
                "binding": "body",
                "input_type": "number",
                "value_type": "float",
                "required": False,
                "min": 0,
                "max": 50,
            },
            {
                "key": "commission_rate",
                "label": "手续费率",
                "binding": "body",
                "input_type": "number",
                "value_type": "float",
                "required": False,
                "default": 0.0003,
                "min": 0,
                "max": 0.01,
            },
            {
                "key": "slippage_rate",
                "label": "滑点率",
                "binding": "body",
                "input_type": "number",
                "value_type": "float",
                "required": False,
                "default": 0.001,
                "min": 0,
                "max": 0.01,
            },
        ],
        "view_model": {"kind": "detail", "title_path": "account.account_name"},
    },
    {
        "key": "simulated-trading.account-delete",
        "label": "删除投资账户",
        "endpoint": "/api/simulated-trading/accounts/<int:account_id>/",
        "method": "DELETE",
        "intent": "delete_owned_account",
        "risk": "write",
        "audience": "authenticated",
        "effect": "delete",
        "confirmation_required": True,
        "audit_required": True,
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "删除本人账户及其关联持仓、交易和巡检记录。",
        "source": _SOURCE,
        "task_group": "06 模拟交易记录",
        "sequence": 630,
        "task_tier": "operation",
        "fields": [_account_id()],
        "view_model": {"kind": "detail", "title_path": "account_name"},
    },
    {
        "key": "simulated-trading.account-batch-delete",
        "label": "批量删除投资账户",
        "endpoint": "/api/simulated-trading/accounts/batch-delete/",
        "method": "POST",
        "intent": "batch_delete_owned_accounts",
        "risk": "write",
        "audience": "authenticated",
        "effect": "delete",
        "confirmation_required": True,
        "audit_required": True,
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "按账户 ID 列表批量删除本人账户，并返回逐项失败原因。",
        "source": _SOURCE,
        "task_group": "06 模拟交易记录",
        "sequence": 640,
        "task_tier": "operation",
        "fields": [
            {
                "key": "account_ids",
                "label": "账户 ID 列表",
                "binding": "body",
                "input_type": "text",
                "value_type": "list",
                "required": True,
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "simulated-trading.performance",
        "label": "查看账户绩效",
        "endpoint": "/api/simulated-trading/accounts/<int:account_id>/performance/",
        "method": "GET",
        "intent": "read_owned_account_performance",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "查看本人账户的收益、回撤、夏普率、胜率和交易统计。",
        "source": _SOURCE,
        "task_group": "06 模拟交易记录",
        "sequence": 650,
        "task_tier": "operation",
        "fields": [_account_id()],
        "view_model": {"kind": "detail", "title_path": "account.account_name"},
    },
    {
        "key": "simulated-trading.equity-curve",
        "label": "查看账户净值曲线",
        "endpoint": "/api/simulated-trading/accounts/<int:account_id>/equity-curve/",
        "method": "GET",
        "intent": "read_owned_account_equity_curve",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "chart",
        "description": "按日期范围查看本人账户的净值变化。",
        "source": _SOURCE,
        "task_group": "06 模拟交易记录",
        "sequence": 660,
        "task_tier": "operation",
        "fields": [
            _account_id(),
            {
                "key": "start_date",
                "label": "开始日期",
                "binding": "query",
                "input_type": "date",
                "value_type": "date",
                "required": False,
            },
            {
                "key": "end_date",
                "label": "结束日期",
                "binding": "query",
                "input_type": "date",
                "value_type": "date",
                "required": False,
            },
        ],
        "view_model": {
            "kind": "chart",
            "chart_type": "line",
            "rows_path": "data_points",
            "columns": [
                {"key": "date", "label": "日期"},
                {"key": "net_value", "label": "账户净值"},
            ],
        },
    },
    {
        "key": "simulated-trading.strategy-options",
        "label": "查看可绑定策略",
        "endpoint": "/api/strategy/strategies/my_strategies/",
        "method": "GET",
        "intent": "read_owned_strategy_options",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "datagrid",
        "description": "查看本人创建、可绑定到投资账户的策略。",
        "source": _SOURCE,
        "task_group": "06 模拟交易记录",
        "sequence": 670,
        "task_tier": "operation",
        "fields": [],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "",
            "columns": [
                {"key": "id", "label": "策略 ID"},
                {"key": "name", "label": "策略名称"},
                {"key": "strategy_type", "label": "类型"},
                {"key": "version", "label": "版本"},
                {"key": "is_active", "label": "活跃"},
            ],
        },
    },
    {
        "key": "simulated-trading.strategy-bind",
        "label": "绑定账户策略",
        "endpoint": "/api/strategy/bind-strategy/",
        "method": "POST",
        "intent": "bind_owned_account_strategy",
        "risk": "write",
        "audience": "authenticated",
        "effect": "update",
        "confirmation_required": True,
        "audit_required": True,
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "把本人策略绑定到本人投资账户。",
        "source": _SOURCE,
        "task_group": "06 模拟交易记录",
        "sequence": 680,
        "task_tier": "operation",
        "fields": [
            {
                "key": "portfolio_id",
                "label": "账户 ID",
                "binding": "body",
                "input_type": "number",
                "value_type": "integer",
                "required": True,
                "min": 1,
            },
            {
                "key": "strategy_id",
                "label": "策略 ID",
                "binding": "body",
                "input_type": "number",
                "value_type": "integer",
                "required": True,
                "min": 1,
            },
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "simulated-trading.strategy-unbind",
        "label": "解绑账户策略",
        "endpoint": "/api/strategy/unbind-strategy/",
        "method": "POST",
        "intent": "unbind_owned_account_strategy",
        "risk": "write",
        "audience": "authenticated",
        "effect": "update",
        "confirmation_required": True,
        "audit_required": True,
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "解除本人投资账户的策略绑定。",
        "source": _SOURCE,
        "task_group": "06 模拟交易记录",
        "sequence": 690,
        "task_tier": "operation",
        "fields": [
            {
                "key": "portfolio_id",
                "label": "账户 ID",
                "binding": "body",
                "input_type": "number",
                "value_type": "integer",
                "required": True,
                "min": 1,
            }
        ],
        "view_model": {"kind": "detail", "title_path": "message"},
    },
    {
        "key": "simulated-trading.positions",
        "label": "查看账户持仓",
        "endpoint": "/api/simulated-trading/accounts/<int:account_id>/positions/",
        "method": "GET",
        "intent": "read_owned_account_positions",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "datagrid",
        "description": "查看本人账户的持仓、可用数量、成本、市值和未实现盈亏。",
        "source": _SOURCE,
        "task_group": "06 模拟交易记录",
        "sequence": 720,
        "task_tier": "operation",
        "fields": [_account_id()],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "positions",
            "columns": [
                {"key": "asset_code", "label": "资产代码"},
                {"key": "asset_name", "label": "资产名称"},
                {"key": "quantity", "label": "数量"},
                {"key": "avg_cost", "label": "成本价"},
                {"key": "current_price", "label": "现价"},
                {"key": "market_value", "label": "市值"},
                {"key": "unrealized_pnl", "label": "未实现盈亏"},
                {"key": "unrealized_pnl_pct", "label": "盈亏率"},
            ],
        },
    },
    {
        "key": "simulated-trading.trades",
        "label": "查看账户交易记录",
        "endpoint": "/api/simulated-trading/accounts/<int:account_id>/trades/",
        "method": "GET",
        "intent": "read_owned_account_trades",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "datagrid",
        "description": "按日期、资产与方向筛选本人账户的交易记录。",
        "source": _SOURCE,
        "task_group": "06 模拟交易记录",
        "sequence": 730,
        "task_tier": "operation",
        "fields": [
            _account_id(),
            {
                "key": "start_date",
                "label": "开始日期",
                "binding": "query",
                "input_type": "date",
                "value_type": "date",
                "required": False,
            },
            {
                "key": "end_date",
                "label": "结束日期",
                "binding": "query",
                "input_type": "date",
                "value_type": "date",
                "required": False,
            },
            {
                "key": "asset_code",
                "label": "资产代码",
                "binding": "query",
                "input_type": "text",
                "value_type": "string",
                "required": False,
                "max": 32,
            },
            {
                "key": "action",
                "label": "交易方向",
                "binding": "query",
                "input_type": "select",
                "value_type": "string",
                "required": False,
                "options": ["buy", "sell"],
            },
            {
                "key": "limit",
                "label": "最多返回",
                "binding": "query",
                "input_type": "number",
                "value_type": "integer",
                "required": False,
                "default": 100,
                "min": 1,
                "max": 500,
            },
        ],
        "view_model": {
            "kind": "datagrid",
            "rows_path": "trades",
            "columns": [
                {"key": "execution_date", "label": "交易日"},
                {"key": "asset_code", "label": "资产代码"},
                {"key": "action", "label": "方向"},
                {"key": "quantity", "label": "数量"},
                {"key": "price", "label": "价格"},
                {"key": "amount", "label": "金额"},
                {"key": "realized_pnl", "label": "已实现盈亏"},
                {"key": "reason", "label": "原因"},
            ],
        },
    },
    {
        "key": "simulated-trading.inspection-notification",
        "label": "查看巡检通知配置",
        "endpoint": (
            "/api/simulated-trading/accounts/" "<int:account_id>/inspection-notification/"
        ),
        "method": "GET",
        "intent": "read_owned_account_inspection_notification",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "查看本人账户的日更巡检邮件通知范围与收件人。",
        "source": _SOURCE,
        "task_group": "06 模拟交易记录",
        "sequence": 740,
        "task_tier": "operation",
        "fields": [_account_id()],
        "view_model": {"kind": "detail", "title_path": "account_name"},
    },
    {
        "key": "simulated-trading.inspection-notification-update",
        "label": "更新巡检通知配置",
        "endpoint": (
            "/api/simulated-trading/accounts/" "<int:account_id>/inspection-notification/"
        ),
        "method": "PATCH",
        "intent": "update_owned_account_inspection_notification",
        "risk": "write",
        "audience": "authenticated",
        "effect": "update",
        "confirmation_required": True,
        "audit_required": True,
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "更新本人账户的巡检邮件触发级别和收件人。",
        "source": _SOURCE,
        "task_group": "06 模拟交易记录",
        "sequence": 750,
        "task_tier": "operation",
        "fields": [
            _account_id(),
            {
                "key": "is_enabled",
                "label": "启用通知",
                "binding": "body",
                "input_type": "checkbox",
                "value_type": "boolean",
                "required": True,
                "default": True,
            },
            {
                "key": "notify_on",
                "label": "触发级别",
                "binding": "body",
                "input_type": "select",
                "value_type": "string",
                "required": True,
                "default": "warning_error",
                "options": ["warning_error", "all"],
            },
            {
                "key": "include_owner_email",
                "label": "包含账户所有者邮箱",
                "binding": "body",
                "input_type": "checkbox",
                "value_type": "boolean",
                "required": True,
                "default": True,
            },
            {
                "key": "recipient_emails",
                "label": "额外收件人",
                "binding": "body",
                "input_type": "text",
                "value_type": "list",
                "required": True,
            },
        ],
        "view_model": {"kind": "detail", "title_path": "account_name"},
    },
)
