"""Runtime TUI metadata for governed QMT live execution tasks."""

from __future__ import annotations

from typing import Any

from apps.terminal.infrastructure.tui_metadata_runtime_injection_broker_execution_helpers import (
    _admin_preview_commit_actions,
    _order_action,
)

RUNTIME_BROKER_EXECUTION_SCREENS: tuple[dict[str, Any], ...] = (
    {
        "key": "broker-execution.overview",
        "label": "实盘执行与账户",
        "module_key": "daily-decisions",
        "group": "daily",
        "summary": "判断今天能否安全实盘，并复核订单、连接和停止状态。",
        "view_type": "status",
        "default_action_key": "broker-execution.overview",
        "user_experience": {
            "journey": "dashboard",
            "primary_task": "先确认本地连接和实盘门禁，再处理待确认订单。",
            "primary_outcome": "得到可交易、需复核、已停止或离线的明确结论。",
            "empty_state_hint": "若本地连接为空，请先完成 Windows Agent 和账户绑定。",
            "next_step_hint": "连接正常后复核待确认订单；出现异常时先停止并对账。",
        },
        "dashboard_panels": [
            {
                "key": "broker-execution-readiness",
                "title": "实盘就绪结论",
                "kind": "detail",
                "action_key": "broker-execution.overview",
                "layout_area": "broker_readiness",
                "target_screen": "broker-execution.overview",
                "user_priority": "p0",
                "presentation_semantic": "primary_status",
            },
            {
                "key": "broker-execution-orders",
                "title": "待确认与执行中订单",
                "kind": "datagrid",
                "action_key": "broker-execution.order-list",
                "max_rows": 8,
                "layout_area": "broker_orders",
                "target_screen": "broker-execution.overview",
                "user_priority": "p0",
                "presentation_semantic": "primary_list",
            },
            {
                "key": "broker-execution-connections",
                "title": "本地连接",
                "kind": "datagrid",
                "action_key": "broker-execution.connection-status",
                "max_rows": 6,
                "layout_area": "broker_connections",
                "target_screen": "broker-execution.overview",
                "user_priority": "p1",
                "presentation_semantic": "supporting_list",
            },
        ],
    },
    {
        "key": "broker-execution.audit",
        "label": "实盘对账与审计",
        "module_key": "daily-decisions",
        "group": "daily",
        "summary": "处理委托、成交、资金和持仓差异，并核对实盘操作证据。",
        "view_type": "status",
        "default_action_key": "broker-execution.reconciliation-list",
        "user_experience": {
            "journey": "dashboard",
            "primary_task": "先处理未处置对账差异，再检查实盘操作审计。",
            "primary_outcome": "所有差异都有明确处置状态，关键操作可追溯。",
            "empty_state_hint": "尚无差异时继续查看最近实盘审计事件。",
            "next_step_hint": "未知订单不得补单，先接受券商事实或升级复核。",
        },
        "dashboard_panels": [
            {
                "key": "broker-execution-reconciliation",
                "title": "实盘对账差异",
                "kind": "datagrid",
                "action_key": "broker-execution.reconciliation-list",
                "max_rows": 8,
                "layout_area": "broker_reconciliation",
                "target_screen": "broker-execution.audit",
                "user_priority": "p0",
                "presentation_semantic": "primary_list",
            },
            {
                "key": "broker-execution-audit",
                "title": "实盘操作审计",
                "kind": "datagrid",
                "action_key": "broker-execution.audit-list",
                "max_rows": 8,
                "layout_area": "broker_audit",
                "target_screen": "broker-execution.audit",
                "user_priority": "p1",
                "presentation_semantic": "supporting_list",
            },
        ],
    },
    {
        "key": "broker-execution.qmt-setup",
        "label": "QMT 接入与设置",
        "module_key": "system-governance",
        "group": "system",
        "audience": "admin",
        "summary": "完成 Windows QMT Agent 接入、账户绑定、凭证、连接验证和执行门禁设置。",
        "view_type": "detail",
        "dashboard_layout": "task_flow",
        "default_action_key": "broker-execution.qmt-onboarding-guide",
        "user_experience": {
            "journey": "admin",
            "primary_task": "按安全顺序完成 QMT 本地执行端接入并核对当前门禁。",
            "primary_outcome": "Agent、账户和一次性凭证配置清楚，连接可验证，自动执行仍受控。",
            "empty_state_hint": "尚未接入时先阅读指引，再完成账户绑定和一次性凭证创建。",
            "next_step_hint": "连接成功后保持自动执行关闭，继续完成只读探针和仿真验收。",
        },
        "business_context": {
            "objective": "把 QMT 接入从隐藏管理动作收敛为可审计的管理员自助流程。",
            "decision_output": "接入状态、安装命令、连接证据、账户门禁和下一步。",
            "checkpoints": [
                "券商已开通外部 XtQuant 权限",
                "Agent 与系统账户已绑定",
                "一次性凭证已安全保存",
                "只读探针与仿真验收已通过",
            ],
        },
        "dashboard_panels": [
            {
                "key": "qmt-setup-guide",
                "title": "一、QMT 接入指引",
                "kind": "detail",
                "action_key": "broker-execution.qmt-onboarding-guide",
                "max_rows": 16,
                "layout_area": "qmt_guide",
                "target_screen": "broker-execution.qmt-setup",
                "note": "按顺序完成准备、绑定、门禁、凭证、安装、只读验收和分级启用。",
                "user_priority": "p0",
                "presentation_semantic": "setup_guide",
            },
            {
                "key": "qmt-connection-status",
                "title": "二、Agent 与 QMT 连接",
                "kind": "datagrid",
                "action_key": "broker-execution.qmt-onboarding-connections",
                "max_rows": 8,
                "layout_area": "qmt_connections",
                "target_screen": "broker-execution.qmt-setup",
                "columns": [
                    {"key": "agent_id", "label": "Agent"},
                    {"key": "display_name", "label": "名称"},
                    {"key": "status", "label": "状态"},
                    {"key": "qmt_connected", "label": "QMT 已连接"},
                    {"key": "binding_count", "label": "绑定账户"},
                    {"key": "last_heartbeat_at", "label": "最后心跳"},
                ],
                "empty_message": "尚未创建本地 Agent 绑定。",
                "user_priority": "p0",
                "presentation_semantic": "primary_list",
            },
            {
                "key": "qmt-current-settings",
                "title": "三、当前执行门禁",
                "kind": "datagrid",
                "action_key": "broker-execution.qmt-onboarding-settings",
                "max_rows": 8,
                "layout_area": "qmt_settings",
                "target_screen": "broker-execution.qmt-setup",
                "columns": [
                    {"key": "account_id", "label": "系统账户"},
                    {"key": "agent_id", "label": "Agent"},
                    {"key": "auto_execution_enabled", "label": "自动执行"},
                    {"key": "max_single_order_amount", "label": "单笔上限"},
                    {"key": "daily_order_amount_limit", "label": "单日上限"},
                    {"key": "max_position_count", "label": "持仓上限"},
                    {"key": "max_snapshot_age_seconds", "label": "快照时效（秒）"},
                    {"key": "enforce_trading_session", "label": "校验交易时段"},
                ],
                "empty_message": "尚无已绑定账户的执行门禁。",
                "user_priority": "p0",
                "presentation_semantic": "primary_list",
            },
            {
                "key": "qmt-bind-agent",
                "title": "四、绑定 Agent 与账户",
                "kind": "detail",
                "action_key": "broker-execution.agent-binding-preview",
                "layout_area": "qmt_binding",
                "target_screen": "broker-execution.qmt-setup",
                "note": "先预览绑定范围；系统账户 ID 不是券商资金账号。",
                "user_priority": "p1",
                "presentation_semantic": "next_step",
            },
            {
                "key": "qmt-create-credential",
                "title": "五、创建一次性凭证",
                "kind": "detail",
                "action_key": "broker-execution.credential-rotate-preview",
                "layout_area": "qmt_credential",
                "target_screen": "broker-execution.qmt-setup",
                "note": "确认后 Token 只显示一次；立即复制并在 Windows 使用 DPAPI 保存。",
                "user_priority": "p1",
                "presentation_semantic": "next_step",
            },
            {
                "key": "qmt-update-settings",
                "title": "六、更新执行门禁",
                "kind": "detail",
                "action_key": "broker-execution.settings-preview",
                "layout_area": "qmt_update_settings",
                "target_screen": "broker-execution.qmt-setup",
                "note": "先预览再确认；完成仿真前保持自动执行关闭。",
                "user_priority": "p1",
                "presentation_semantic": "next_step",
            },
        ],
    },
)


_ORDER_ID_FIELD = {
    "key": "client_order_id",
    "label": "订单编号",
    "input_type": "text",
    "required": True,
    "default": "",
    "placeholder": "从订单列表选择",
    "binding": "path",
    "value_type": "string",
}
_REASON_FIELD = {
    "key": "reason",
    "label": "操作原因",
    "input_type": "textarea",
    "required": True,
    "default": "",
    "placeholder": "说明复核结论或处置原因",
    "binding": "body",
    "value_type": "string",
}


_ACCOUNT_ID_FIELD = {
    "key": "account_id",
    "label": "实盘账户 ID",
    "input_type": "number",
    "required": True,
    "binding": "body",
    "value_type": "integer",
    "min": 1,
}
_AGENT_ID_FIELD = {
    "key": "agent_id",
    "label": "Agent ID",
    "input_type": "text",
    "required": True,
    "binding": "body",
    "value_type": "string",
    "max": 64,
}


RUNTIME_BROKER_EXECUTION_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "broker-execution.qmt-onboarding-guide",
        "label": "读取 QMT 接入指引",
        "endpoint": "/api/broker-execution/qmt-onboarding/",
        "method": "GET",
        "intent": "read_qmt_onboarding_guide",
        "risk": "read",
        "audience": "admin",
        "screen_key": "broker-execution.qmt-setup",
        "module_key": "system-governance",
        "view_type": "detail",
        "description": "读取 QMT 接入状态、分步指引和可复制的 Windows 安装验收命令。",
        "source": "approved:runtime-broker-execution",
        "task_group": "01 接入总览",
        "task_tier": "primary",
        "sequence": 10,
        "fields": [],
        "view_model": {
            "kind": "detail",
            "field_presentations": {
                "server_address": "copyable",
                "setup_guide": "multiline",
                "package_build_command": "multiline",
                "windows_install_command": "multiline",
                "token_setup_command": "multiline",
                "verification_command": "multiline",
            },
        },
        "result_semantics": ["primary_status", "setup_guide"],
    },
    {
        "key": "broker-execution.qmt-onboarding-connections",
        "label": "读取 QMT 接入连接",
        "endpoint": "/api/broker-execution/qmt-onboarding/",
        "method": "GET",
        "intent": "read_qmt_onboarding_connections",
        "risk": "read",
        "audience": "admin",
        "screen_key": "broker-execution.qmt-setup",
        "module_key": "system-governance",
        "view_type": "datagrid",
        "description": "读取已持久化的 Agent、QMT 连接和绑定数量。",
        "source": "approved:runtime-broker-execution",
        "task_group": "01 接入总览",
        "task_tier": "primary",
        "sequence": 20,
        "fields": [],
        "view_model": {"kind": "datagrid", "rows_path": "connections"},
        "result_semantics": ["primary_list"],
    },
    {
        "key": "broker-execution.qmt-onboarding-settings",
        "label": "读取 QMT 执行门禁",
        "endpoint": "/api/broker-execution/qmt-onboarding/",
        "method": "GET",
        "intent": "read_qmt_onboarding_settings",
        "risk": "read",
        "audience": "admin",
        "screen_key": "broker-execution.qmt-setup",
        "module_key": "system-governance",
        "view_type": "datagrid",
        "description": "读取每个已绑定账户的当前额度、白名单、交易时段和自动执行门禁。",
        "source": "approved:runtime-broker-execution",
        "task_group": "01 接入总览",
        "task_tier": "primary",
        "sequence": 30,
        "fields": [],
        "view_model": {"kind": "datagrid", "rows_path": "settings"},
        "result_semantics": ["primary_list"],
    },
    {
        "key": "broker-execution.overview",
        "label": "实盘就绪总览",
        "endpoint": "/api/broker-execution/",
        "method": "GET",
        "intent": "read_live_execution_readiness",
        "risk": "read",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "读取持久化的连接、停止开关、待确认订单和对账结论。",
        "source": "approved:runtime-broker-execution",
        "task_group": "01 实盘状态",
        "task_tier": "primary",
        "sequence": 100,
        "view_model": {"kind": "detail", "status_path": "data.today_readiness"},
    },
    {
        "key": "broker-execution.order-list",
        "label": "实盘订单",
        "endpoint": "/api/broker-execution/orders/",
        "method": "GET",
        "intent": "list_live_orders",
        "risk": "read",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "datagrid",
        "description": "列出当前身份有权查看的实盘订单。",
        "source": "approved:runtime-broker-execution",
        "task_group": "01 实盘状态",
        "task_tier": "primary",
        "sequence": 110,
        "view_model": {"kind": "datagrid", "rows_path": "data.orders"},
    },
    {
        "key": "broker-execution.order-detail",
        "label": "实盘订单详情",
        "endpoint": "/api/broker-execution/orders/<uuid:client_order_id>/",
        "method": "GET",
        "intent": "read_live_order_evidence",
        "risk": "read",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "查看订单风险快照、审批摘要、券商事件和成交。",
        "source": "approved:runtime-broker-execution",
        "task_group": "01 实盘状态",
        "task_tier": "primary",
        "sequence": 120,
        "fields": [dict(_ORDER_ID_FIELD)],
        "view_model": {
            "kind": "detail",
            "title_path": "data.asset_code",
            "status_path": "data.status",
        },
    },
    {
        "key": "broker-execution.connection-status",
        "label": "本地连接状态",
        "endpoint": "/api/broker-execution/connections/",
        "method": "GET",
        "intent": "read_qmt_connection_status",
        "risk": "read",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "datagrid",
        "description": "读取 Agent、QMT 和绑定账户最近一次持久化健康状态。",
        "source": "approved:runtime-broker-execution",
        "task_group": "01 实盘状态",
        "task_tier": "support",
        "sequence": 130,
        "view_model": {"kind": "datagrid", "rows_path": "data.connections"},
    },
    _order_action(
        "broker-execution.approval-preview", "批准订单", "approve", preview=True, sequence=200
    ),
    _order_action(
        "broker-execution.reject-preview", "拒绝订单", "reject", preview=True, sequence=220
    ),
    _order_action(
        "broker-execution.reject-order", "拒绝订单", "reject", preview=False, sequence=230
    ),
    _order_action(
        "broker-execution.cancel-preview", "请求撤单", "cancel", preview=True, sequence=240
    ),
    _order_action(
        "broker-execution.request-cancel", "请求撤单", "cancel", preview=False, sequence=250
    ),
    {
        "key": "broker-execution.reconciliation-list",
        "label": "实盘对账批次",
        "endpoint": "/api/broker-execution/reconciliations/",
        "method": "GET",
        "intent": "list_live_reconciliation_runs",
        "risk": "read",
        "screen_key": "broker-execution.audit",
        "module_key": "daily-decisions",
        "view_type": "datagrid",
        "description": "列出委托、成交、资金和持仓差异批次。",
        "source": "approved:runtime-broker-execution",
        "task_group": "03 对账与审计",
        "task_tier": "primary",
        "sequence": 300,
        "view_model": {"kind": "datagrid", "rows_path": "data.runs"},
    },
    {
        "key": "broker-execution.audit-list",
        "label": "实盘操作审计",
        "endpoint": "/api/broker-execution/audit/",
        "method": "GET",
        "intent": "list_live_execution_audit",
        "risk": "read",
        "screen_key": "broker-execution.audit",
        "module_key": "daily-decisions",
        "view_type": "datagrid",
        "description": "查看批准、撤单、启停、凭证和差异处置证据。",
        "source": "approved:runtime-broker-execution",
        "task_group": "03 对账与审计",
        "task_tier": "support",
        "sequence": 310,
        "view_model": {"kind": "datagrid", "rows_path": "data.events"},
    },
    {
        "key": "broker-execution.resolve-reconciliation-preview",
        "label": "预览对账处置",
        "endpoint": "/api/broker-execution/reconciliations/<int:run_id>/resolve/",
        "method": "POST",
        "intent": "preview_live_reconciliation_resolution",
        "risk": "read",
        "screen_key": "broker-execution.audit",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "预览委托、成交、资金和持仓差异的处置结果。",
        "source": "approved:runtime-broker-execution",
        "task_group": "03 对账与审计",
        "task_tier": "primary",
        "sequence": 320,
        "fields": [
            {
                "key": "run_id",
                "label": "对账批次",
                "input_type": "number",
                "required": True,
                "default": 0,
                "placeholder": "从对账列表选择",
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "resolution",
                "label": "处置方式",
                "input_type": "select",
                "required": True,
                "default": "verified_no_change",
                "binding": "body",
                "value_type": "string",
                "options": [
                    "accept_broker_fact",
                    "manual_adjustment",
                    "verified_no_change",
                    "escalate",
                ],
            },
            dict(_REASON_FIELD),
            {
                "key": "preview_only",
                "label": "仅预览",
                "input_type": "hidden",
                "required": True,
                "default": True,
                "binding": "body",
                "value_type": "boolean",
            },
        ],
    },
    {
        "key": "broker-execution.resolve-reconciliation",
        "label": "确认对账处置",
        "endpoint": "/api/broker-execution/reconciliations/<int:run_id>/resolve/",
        "method": "POST",
        "intent": "resolve_live_reconciliation",
        "risk": "write",
        "screen_key": "broker-execution.audit",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "确认差异处置并保留幂等、权限和审计证据。",
        "source": "approved:runtime-broker-execution",
        "task_group": "03 对账与审计",
        "task_tier": "primary",
        "sequence": 330,
        "confirmation_required": True,
        "audit_required": True,
        "fields": [
            {
                "key": "run_id",
                "label": "对账批次",
                "input_type": "number",
                "required": True,
                "default": 0,
                "placeholder": "从对账列表选择",
                "binding": "path",
                "value_type": "integer",
            },
            {
                "key": "resolution",
                "label": "处置方式",
                "input_type": "select",
                "required": True,
                "default": "verified_no_change",
                "binding": "body",
                "value_type": "string",
                "options": [
                    "accept_broker_fact",
                    "manual_adjustment",
                    "verified_no_change",
                    "escalate",
                ],
            },
            dict(_REASON_FIELD),
            {
                "key": "preview_only",
                "label": "仅预览",
                "input_type": "hidden",
                "required": True,
                "default": False,
                "binding": "body",
                "value_type": "boolean",
            },
            {
                "key": "idempotency_key",
                "label": "请求幂等键",
                "input_type": "text",
                "required": True,
                "default": "",
                "placeholder": "每次确认使用唯一值",
                "binding": "body",
                "value_type": "string",
            },
        ],
    },
    {
        "key": "broker-execution.kill-switch-preview",
        "label": "预览紧急停止",
        "endpoint": "/api/broker-execution/kill-switch/",
        "method": "POST",
        "intent": "preview_live_trading_stop",
        "risk": "read",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "预览停止范围和当前实盘状态，不产生状态变化。",
        "source": "approved:runtime-broker-execution",
        "task_group": "04 紧急控制",
        "task_tier": "primary",
        "sequence": 400,
        "fields": [
            {
                "key": "account_id",
                "label": "账户范围",
                "input_type": "number",
                "required": True,
                "default": 0,
                "placeholder": "0 表示全部可管理账户",
                "binding": "body",
                "value_type": "integer",
            },
            dict(_REASON_FIELD),
            {
                "key": "active",
                "label": "触发停止",
                "input_type": "hidden",
                "required": True,
                "default": True,
                "binding": "body",
                "value_type": "boolean",
            },
            {
                "key": "preview_only",
                "label": "仅预览",
                "input_type": "hidden",
                "required": True,
                "default": True,
                "binding": "body",
                "value_type": "boolean",
            },
        ],
    },
    {
        "key": "broker-execution.trigger-kill-switch",
        "label": "确认紧急停止",
        "endpoint": "/api/broker-execution/kill-switch/",
        "method": "POST",
        "intent": "trigger_live_trading_stop",
        "risk": "write",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "确认后停止新订单领取和提交，撤单与对账仍可继续。",
        "source": "approved:runtime-broker-execution",
        "task_group": "04 紧急控制",
        "task_tier": "primary",
        "sequence": 410,
        "confirmation_required": True,
        "audit_required": True,
        "fields": [
            {
                "key": "account_id",
                "label": "账户范围",
                "input_type": "number",
                "required": True,
                "default": 0,
                "placeholder": "0 表示全部可管理账户",
                "binding": "body",
                "value_type": "integer",
            },
            dict(_REASON_FIELD),
            {
                "key": "active",
                "label": "触发停止",
                "input_type": "hidden",
                "required": True,
                "default": True,
                "binding": "body",
                "value_type": "boolean",
            },
            {
                "key": "preview_only",
                "label": "仅预览",
                "input_type": "hidden",
                "required": True,
                "default": False,
                "binding": "body",
                "value_type": "boolean",
            },
            {
                "key": "idempotency_key",
                "label": "请求幂等键",
                "input_type": "text",
                "required": True,
                "default": "",
                "placeholder": "每次确认使用唯一值",
                "binding": "body",
                "value_type": "string",
            },
        ],
    },
    {
        "key": "broker-execution.resume-preview",
        "label": "预览恢复实盘",
        "endpoint": "/api/broker-execution/kill-switch/",
        "method": "POST",
        "intent": "preview_live_trading_resume",
        "risk": "read",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "复核连接、执行异常和对账差异是否允许恢复。",
        "source": "approved:runtime-broker-execution",
        "task_group": "04 紧急控制",
        "task_tier": "primary",
        "sequence": 420,
        "fields": [
            {
                "key": "account_id",
                "label": "账户范围",
                "input_type": "number",
                "required": True,
                "default": 0,
                "placeholder": "0 表示全部可管理账户",
                "binding": "body",
                "value_type": "integer",
            },
            dict(_REASON_FIELD),
            {
                "key": "active",
                "label": "恢复实盘",
                "input_type": "hidden",
                "required": True,
                "default": False,
                "binding": "body",
                "value_type": "boolean",
            },
            {
                "key": "preview_only",
                "label": "仅预览",
                "input_type": "hidden",
                "required": True,
                "default": True,
                "binding": "body",
                "value_type": "boolean",
            },
        ],
    },
    {
        "key": "broker-execution.resume-trading",
        "label": "确认恢复实盘",
        "endpoint": "/api/broker-execution/kill-switch/",
        "method": "POST",
        "intent": "resume_live_trading",
        "risk": "write",
        "screen_key": "broker-execution.overview",
        "module_key": "daily-decisions",
        "view_type": "detail",
        "description": "仅管理员在所有阻断项清除后确认恢复，并写入审计。",
        "source": "approved:runtime-broker-execution",
        "task_group": "04 紧急控制",
        "task_tier": "primary",
        "sequence": 430,
        "confirmation_required": True,
        "requires_password": True,
        "audit_required": True,
        "fields": [
            {
                "key": "account_id",
                "label": "账户范围",
                "input_type": "number",
                "required": True,
                "default": 0,
                "placeholder": "0 表示全部可管理账户",
                "binding": "body",
                "value_type": "integer",
            },
            dict(_REASON_FIELD),
            {
                "key": "active",
                "label": "恢复实盘",
                "input_type": "hidden",
                "required": True,
                "default": False,
                "binding": "body",
                "value_type": "boolean",
            },
            {
                "key": "preview_only",
                "label": "仅预览",
                "input_type": "hidden",
                "required": True,
                "default": False,
                "binding": "body",
                "value_type": "boolean",
            },
            {
                "key": "idempotency_key",
                "label": "请求幂等键",
                "input_type": "text",
                "required": True,
                "default": "",
                "placeholder": "每次确认使用唯一值",
                "binding": "body",
                "value_type": "string",
            },
        ],
    },
    *_admin_preview_commit_actions(
        key_prefix="broker-execution.advisor-draft",
        label="从投顾建议生成订单草稿",
        endpoint="/api/broker-execution/orders/from-advisor-sheet/",
        method="POST",
        intent="create_advisor_live_order_drafts",
        sequence=500,
        fields=[dict(_ACCOUNT_ID_FIELD)],
        commit_fields=[
            {
                "key": "expected_plan_digest",
                "label": "预览计划摘要",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "string",
            }
        ],
        effect="create",
        commit_enabled=False,
    ),
    *_admin_preview_commit_actions(
        key_prefix="broker-execution.agent-binding",
        label="Agent 与账户绑定",
        endpoint="/api/broker-execution/bindings/",
        method="POST",
        intent="manage_agent_binding",
        sequence=520,
        fields=[
            {
                "key": "user_id",
                "label": "用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "body",
                "value_type": "integer",
                "min": 1,
            },
            dict(_ACCOUNT_ID_FIELD),
            dict(_AGENT_ID_FIELD),
            {
                "key": "display_name",
                "label": "显示名称",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "broker_account_ref",
                "label": "券商账户引用",
                "input_type": "password",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "broker_account_mask",
                "label": "脱敏账户号",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "account_type",
                "label": "账户类型",
                "input_type": "select",
                "required": True,
                "default": "STOCK",
                "options": ["STOCK"],
                "binding": "body",
                "value_type": "string",
            },
            {
                "key": "is_active",
                "label": "启用绑定",
                "input_type": "checkbox",
                "required": False,
                "default": True,
                "binding": "body",
                "value_type": "boolean",
            },
            dict(_REASON_FIELD),
        ],
        screen_key="broker-execution.qmt-setup",
        task_group="02 账户绑定",
    ),
    {
        "key": "broker-execution.account-access-list",
        "label": "查看实盘账户授权",
        "endpoint": "/api/broker-execution/account-access/",
        "method": "GET",
        "intent": "list_broker_account_access",
        "risk": "read",
        "audience": "admin",
        "screen_key": "broker-execution.qmt-setup",
        "module_key": "daily-decisions",
        "view_type": "datagrid",
        "description": "查看用户对实盘账户的审批、交易与启用权限。",
        "source": "approved:runtime-broker-execution",
        "task_group": "06 账户授权",
        "task_tier": "support",
        "sequence": 540,
        "view_model": {"kind": "datagrid", "rows_path": "access_grants"},
    },
    *_admin_preview_commit_actions(
        key_prefix="broker-execution.account-access",
        label="实盘账户授权",
        endpoint="/api/broker-execution/account-access/",
        method="POST",
        intent="manage_broker_account_access",
        sequence=550,
        fields=[
            {
                "key": "user_id",
                "label": "被授权用户 ID",
                "input_type": "number",
                "required": True,
                "binding": "body",
                "value_type": "integer",
                "min": 1,
            },
            dict(_ACCOUNT_ID_FIELD),
            {
                "key": "can_approve",
                "label": "允许审批",
                "input_type": "checkbox",
                "required": False,
                "binding": "body",
                "value_type": "boolean",
            },
            {
                "key": "can_trade",
                "label": "允许交易",
                "input_type": "checkbox",
                "required": False,
                "binding": "body",
                "value_type": "boolean",
            },
            {
                "key": "is_active",
                "label": "授权有效",
                "input_type": "checkbox",
                "required": False,
                "default": True,
                "binding": "body",
                "value_type": "boolean",
            },
            dict(_REASON_FIELD),
        ],
        screen_key="broker-execution.qmt-setup",
        task_group="06 账户授权",
    ),
    *_admin_preview_commit_actions(
        key_prefix="broker-execution.credential-rotate",
        label="创建 Agent 一次性凭证",
        endpoint="/api/broker-execution/credentials/rotate/",
        method="POST",
        intent="rotate_agent_credential",
        sequence=570,
        fields=[
            dict(_AGENT_ID_FIELD),
            {
                "key": "account_ids",
                "label": "允许账户 ID（逗号分隔）",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "list",
            },
            {
                "key": "expires_at",
                "label": "有效期",
                "input_type": "text",
                "required": True,
                "binding": "body",
                "value_type": "datetime",
            },
            {
                "key": "scopes",
                "label": "固定 Agent 权限",
                "input_type": "hidden",
                "required": True,
                "binding": "body",
                "value_type": "list",
                "default": [
                    "agent.heartbeat.write",
                    "agent.orders.lease",
                    "agent.orders.submitting_ack",
                    "agent.events.write",
                    "agent.snapshots.write",
                    "agent.commands.lease",
                ],
            },
        ],
        effect="create",
        result_semantics=["copyable_secret"],
        screen_key="broker-execution.qmt-setup",
        task_group="03 凭证管理",
    ),
    *_admin_preview_commit_actions(
        key_prefix="broker-execution.credential-revoke",
        label="撤销 Agent 凭证",
        endpoint="/api/broker-execution/credentials/<uuid:credential_id>/revoke/",
        method="POST",
        intent="revoke_agent_credential",
        sequence=590,
        fields=[
            {
                "key": "credential_id",
                "label": "凭证 ID",
                "input_type": "text",
                "required": True,
                "binding": "path",
                "value_type": "string",
            },
            dict(_REASON_FIELD),
        ],
        effect="delete",
        screen_key="broker-execution.qmt-setup",
        task_group="03 凭证管理",
    ),
    *_admin_preview_commit_actions(
        key_prefix="broker-execution.connection-sync",
        label="下发 Agent 全量同步",
        endpoint="/api/broker-execution/connections/sync/",
        method="POST",
        intent="request_agent_full_sync",
        sequence=610,
        fields=[dict(_AGENT_ID_FIELD), dict(_REASON_FIELD)],
        effect="execute",
        screen_key="broker-execution.qmt-setup",
        task_group="04 连接验证",
    ),
    *_admin_preview_commit_actions(
        key_prefix="broker-execution.settings",
        label="更新账户执行门禁",
        endpoint="/api/broker-execution/settings/<int:account_id>/",
        method="PATCH",
        intent="update_broker_execution_settings",
        sequence=630,
        fields=[
            {
                **dict(_ACCOUNT_ID_FIELD),
                "binding": "path",
            },
            {
                "key": "auto_execution_enabled",
                "label": "自动执行",
                "input_type": "checkbox",
                "required": False,
                "binding": "body",
                "value_type": "boolean",
            },
            {
                "key": "max_single_order_amount",
                "label": "单笔金额上限",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "decimal",
                "min": 0,
            },
            {
                "key": "daily_order_amount_limit",
                "label": "单日金额上限",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "decimal",
                "min": 0,
            },
            {
                "key": "max_position_count",
                "label": "最大持仓数",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "integer",
                "min": 1,
                "max": 1000,
            },
            {
                "key": "max_snapshot_age_seconds",
                "label": "快照最大延迟（秒）",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "integer",
                "min": 10,
                "max": 3600,
            },
            {
                "key": "price_deviation_limit_pct",
                "label": "限价偏离上限",
                "input_type": "number",
                "required": False,
                "binding": "body",
                "value_type": "decimal",
                "min": 0,
                "max": 1,
            },
            {
                "key": "allowed_trading_windows",
                "label": "交易时段（逗号分隔）",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "list",
            },
            {
                "key": "allowed_symbols",
                "label": "标的白名单（逗号分隔）",
                "input_type": "text",
                "required": False,
                "binding": "body",
                "value_type": "list",
            },
            {
                "key": "enforce_trading_session",
                "label": "校验交易时段",
                "input_type": "checkbox",
                "required": False,
                "binding": "body",
                "value_type": "boolean",
            },
            dict(_REASON_FIELD),
        ],
        screen_key="broker-execution.qmt-setup",
        task_group="05 执行门禁",
    ),
)
