"""Runtime TUI metadata for administrator system settings."""

from __future__ import annotations

from typing import Any

RUNTIME_SYSTEM_SETTINGS_SCREEN: dict[str, Any] = {
    "key": "system.settings",
    "label": "系统设置",
    "module_key": "system-governance",
    "group": "system",
    "summary": "维护用户准入、MCP 默认值、市场视觉、协议与运行时映射。",
    "view_type": "detail",
    "audience": "admin",
    "dashboard_layout": "task_flow",
    "default_action_key": "system-settings.read",
    "user_experience": {
        "journey": "admin",
        "primary_task": "核对并更新影响全体用户和运行时语义的系统级设置。",
        "primary_outcome": "全局准入、凭证、视觉、协议与代码映射均处于明确且可审计的状态。",
        "empty_state_hint": "先读取当前设置；系统首次运行时会展示数据库默认值。",
        "next_step_hint": "保存后分别进入用户准入、MCP 接入和数据中心复核实际效果。",
    },
    "workflow": {
        "name": "系统治理流程",
        "label": "系统设置",
        "role": "维护全局默认值和用户可见约定。",
        "previous": {"key": "api-library.data-center", "label": "数据与系统健康"},
        "next": {"key": "identity-access.user-governance", "label": "用户准入治理"},
    },
    "business_context": {
        "objective": "让全局运行约定只有 config_center 一个写入真源。",
        "decision_output": "设置更新回执和最新全局配置。",
        "checkpoints": [
            "先确认用户审批和首个管理员策略，再调整准入默认值。",
            "Token 明文与 MCP 默认开关影响凭证安全，保存前复核影响范围。",
            "JSON 映射必须保持对象结构；宏观指标治理继续在数据中心完成。",
        ],
    },
    "dashboard_panels": [
        {
            "key": "system-settings-current",
            "title": "一、当前系统设置",
            "kind": "detail",
            "action_key": "system-settings.read",
            "max_rows": 14,
            "layout_area": "current",
            "target_screen": "system.settings",
            "empty_message": "暂无系统设置。",
            "error_message": "系统设置读取失败，请稍后重试。",
            "stale_message": "系统设置可能已经变化，请刷新后再编辑。",
            "user_priority": "p0",
            "presentation_semantic": "primary_status",
        },
        {
            "key": "system-settings-receipt",
            "title": "二、更新回执",
            "kind": "detail",
            "max_rows": 10,
            "layout_area": "receipt",
            "empty_message": "从任务区打开“更新系统设置”。",
            "user_priority": "p1",
            "presentation_semantic": "primary_status",
        },
    ],
}


_SYSTEM_SETTINGS_FIELDS: list[dict[str, Any]] = [
    {
        "key": "require_user_approval",
        "label": "新用户需要管理员审批",
        "input_type": "checkbox",
        "required": False,
        "binding": "body",
        "value_type": "boolean",
    },
    {
        "key": "auto_approve_first_admin",
        "label": "自动批准首个管理员",
        "input_type": "checkbox",
        "required": False,
        "binding": "body",
        "value_type": "boolean",
    },
    {
        "key": "default_mcp_enabled",
        "label": "新用户默认开启 MCP",
        "input_type": "checkbox",
        "required": False,
        "binding": "body",
        "value_type": "boolean",
    },
    {
        "key": "allow_token_plaintext_view",
        "label": "允许查看 Token 明文",
        "input_type": "checkbox",
        "required": False,
        "binding": "body",
        "value_type": "boolean",
    },
    {
        "key": "market_color_convention",
        "label": "市场颜色约定",
        "input_type": "select",
        "required": False,
        "binding": "body",
        "value_type": "string",
        "options": [
            {"value": "cn_a_share", "label": "A 股红涨绿跌"},
            {"value": "us_market", "label": "美股绿涨红跌"},
        ],
    },
    {
        "key": "alpha_pool_mode",
        "label": "Alpha 默认股票池",
        "input_type": "select",
        "required": False,
        "binding": "body",
        "value_type": "string",
        "options": [
            {"value": "strict_valuation", "label": "严格估值覆盖池"},
            {"value": "market", "label": "市场可交易池"},
            {"value": "price_covered", "label": "价格覆盖池"},
        ],
    },
    {
        "key": "user_agreement_content",
        "label": "用户服务协议",
        "input_type": "textarea",
        "required": False,
        "binding": "body",
        "value_type": "string",
    },
    {
        "key": "risk_warning_content",
        "label": "投资风险提示",
        "input_type": "textarea",
        "required": False,
        "binding": "body",
        "value_type": "string",
    },
    {
        "key": "notes",
        "label": "变更说明",
        "input_type": "textarea",
        "required": False,
        "binding": "body",
        "value_type": "string",
    },
    {
        "key": "benchmark_code_map",
        "label": "基准代码映射",
        "input_type": "textarea",
        "required": False,
        "binding": "body",
        "value_type": "object",
    },
    {
        "key": "asset_proxy_code_map",
        "label": "资产代理代码映射",
        "input_type": "textarea",
        "required": False,
        "binding": "body",
        "value_type": "object",
    },
]


RUNTIME_SYSTEM_SETTINGS_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "system-settings.read",
        "label": "读取系统设置",
        "endpoint": "/api/system/config-center/settings/",
        "method": "GET",
        "intent": "read_admin_system_governance_settings",
        "risk": "admin",
        "screen_key": "system.settings",
        "module_key": "system-governance",
        "view_type": "detail",
        "description": "读取用户准入、MCP 默认值、视觉、协议和运行时映射。",
        "source": "approved:runtime-system-settings",
        "task_group": "01 系统设置",
        "sequence": 100,
        "task_tier": "primary",
        "fields": [],
        "view_model": {
            "kind": "detail",
            "title_path": "market_color_label",
            "status_path": "updated_at",
        },
        "result_semantics": ["primary_status"],
    },
    {
        "key": "system-settings.update",
        "label": "更新系统设置",
        "endpoint": "/api/system/config-center/settings/",
        "method": "PUT",
        "intent": "update_admin_system_governance_settings",
        "risk": "admin",
        "effect": "update",
        "confirmation_required": True,
        "screen_key": "system.settings",
        "module_key": "system-governance",
        "view_type": "detail",
        "description": "更新全局设置的显式允许字段，并返回保存后的完整状态。",
        "source": "approved:runtime-system-settings",
        "task_group": "01 系统设置",
        "sequence": 110,
        "task_tier": "operation",
        "fields": _SYSTEM_SETTINGS_FIELDS,
        "view_model": {
            "kind": "detail",
            "title_path": "market_color_label",
            "status_path": "updated_at",
        },
        "result_semantics": ["primary_status"],
    },
)
