"""Runtime TUI metadata for authenticated sentiment analysis."""

from __future__ import annotations

from typing import Any

_SCREEN = "research.signals"
_MODULE = "daily-decisions"
_SOURCE = "approved:runtime-sentiment-analysis"

RUNTIME_SENTIMENT_ACTIONS: tuple[dict[str, Any], ...] = (
    {
        "key": "sentiment.dashboard-summary",
        "label": "舆情指数摘要",
        "endpoint": "/api/sentiment/tui/overview/",
        "method": "GET",
        "intent": "inspect_sentiment_index_summary",
        "risk": "read",
        "audience": "authenticated",
        "effect": "read",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "查看最新综合、新闻、政策情绪和数据充分性。",
        "source": _SOURCE,
        "task_group": "04 情绪分析",
        "sequence": 580,
        "task_tier": "support",
        "fields": [],
        "view_model": {
            "kind": "detail",
            "title_path": "summary.latest_level",
            "status_path": "summary.service_status",
        },
    },
    {
        "key": "sentiment.index-trend",
        "label": "舆情指数趋势",
        "endpoint": "/api/sentiment/tui/overview/",
        "method": "GET",
        "intent": "chart_sentiment_index_trend",
        "risk": "read",
        "audience": "authenticated",
        "effect": "read",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "chart",
        "description": "查看综合、新闻和政策情绪的近期多序列变化。",
        "source": _SOURCE,
        "task_group": "04 情绪分析",
        "sequence": 590,
        "task_tier": "support",
        "fields": [
            {
                "key": "days",
                "label": "最近天数",
                "binding": "query",
                "input_type": "number",
                "value_type": "integer",
                "required": False,
                "default": 30,
                "min": 1,
                "max": 365,
            }
        ],
        "view_model": {
            "kind": "chart",
            "chart_type": "line",
            "rows_path": "indices",
            "columns": [
                {"key": "date", "label": "日期"},
                {"key": "composite", "label": "综合指数"},
                {"key": "news", "label": "新闻情绪"},
                {"key": "policy", "label": "政策情绪"},
            ],
        },
    },
    {
        "key": "sentiment.analyze-text",
        "label": "分析文本情绪",
        "endpoint": "/api/sentiment/analyze/",
        "method": "POST",
        "intent": "analyze_sentiment_text",
        "risk": "write",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "分析新闻、评论或政策文本的情绪评分、置信度、分类和关键词。",
        "source": _SOURCE,
        "task_group": "04 情绪分析",
        "sequence": 600,
        "task_tier": "support",
        "fields": [
            {
                "key": "text",
                "label": "待分析文本",
                "binding": "body",
                "input_type": "textarea",
                "value_type": "string",
                "required": True,
                "max": 5000,
            },
            {
                "key": "use_cache",
                "label": "使用缓存",
                "binding": "body",
                "input_type": "checkbox",
                "value_type": "boolean",
                "required": False,
                "default": True,
            },
        ],
        "view_model": {
            "kind": "detail",
            "title_path": "category",
            "status_path": "sentiment_score",
        },
        "effect": "execute",
        "confirmation_required": True,
    },
    {
        "key": "sentiment.health",
        "label": "查看情绪服务健康",
        "endpoint": "/api/sentiment/health/",
        "method": "GET",
        "intent": "read_sentiment_health",
        "risk": "read",
        "audience": "authenticated",
        "screen_key": _SCREEN,
        "module_key": _MODULE,
        "view_type": "detail",
        "description": "查看 AI 服务、缓存数量和最新情绪指数日期。",
        "source": _SOURCE,
        "task_group": "04 情绪分析",
        "sequence": 610,
        "task_tier": "support",
        "fields": [],
        "view_model": {"kind": "detail", "status_path": "status"},
    },
)
