"""Append-only ORM ledgers for R1 forecast-baseline evidence."""

from __future__ import annotations

from collections.abc import Collection, Iterable
from datetime import timedelta
from typing import NoReturn, TypeVar

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.base import ModelBase
from django.utils import timezone

from shared.infrastructure.django_append_only import AppendOnlyManager, AppendOnlyQuerySet

_ModelT = TypeVar("_ModelT", bound=models.Model)


class ForecastBaselineAppendOnlyQuerySet(AppendOnlyQuerySet[_ModelT]):
    """Reject every bulk insertion path that can bypass evidence validation."""

    def bulk_create(
        self,
        objs: Iterable[_ModelT],
        batch_size: int | None = None,
        ignore_conflicts: bool = False,
        update_conflicts: bool = False,
        update_fields: Collection[str] | None = None,
        unique_fields: Collection[str] | None = None,
    ) -> NoReturn:
        """Reject bulk create, including silent-ignore and conflict-update variants."""

        raise ValidationError("Forecast baseline evidence must use exact append operations.")


class ForecastBaselineAppendOnlyManager(AppendOnlyManager[_ModelT]):
    """Expose the stronger ledger guard on default, base and related paths."""

    def get_queryset(self) -> ForecastBaselineAppendOnlyQuerySet[_ModelT]:
        """Return the forecast-baseline-specific guarded QuerySet."""

        return ForecastBaselineAppendOnlyQuerySet(self.model, using=self._db)

    def bulk_create(
        self,
        objs: Iterable[_ModelT],
        batch_size: int | None = None,
        ignore_conflicts: bool = False,
        update_conflicts: bool = False,
        update_fields: Collection[str] | None = None,
        unique_fields: Collection[str] | None = None,
    ) -> NoReturn:
        """Reject manager-level bulk insertion and conflict shortcuts."""

        raise ValidationError("Forecast baseline evidence must use exact append operations.")


class ForecastBaselineAppendOnlyModel(models.Model):
    """Reject every mutation or deletion of persisted R1 evidence."""

    objects = ForecastBaselineAppendOnlyManager()

    class Meta:
        abstract = True
        base_manager_name = "objects"
        default_manager_name = "objects"

    def save(
        self,
        *,
        force_insert: bool | tuple[ModelBase, ...] = False,
        force_update: bool = False,
        using: str | None = None,
        update_fields: Iterable[str] | None = None,
    ) -> None:
        """Insert a row while rejecting all persisted-instance updates."""

        if force_update or update_fields is not None:
            raise ValidationError("Forecast baseline evidence is append-only.")
        if self.pk is not None and type(self)._default_manager.filter(pk=self.pk).exists():
            raise ValidationError("Forecast baseline evidence is immutable.")
        super().save(force_insert=force_insert, using=using)

    def delete(
        self,
        using: object | None = None,
        keep_parents: bool = False,
    ) -> tuple[int, dict[str, int]]:
        """Reject destructive deletion of R1 evidence."""

        raise ValidationError("Forecast baseline evidence cannot be deleted.")


class ForecastBaselineApprovalEvidenceModel(ForecastBaselineAppendOnlyModel):
    """Canonical Equity-owned baseline approval evidence."""

    approval_id = models.CharField(max_length=192)
    approval_version = models.CharField(max_length=192)
    content_hash = models.CharField(max_length=64, unique=True)
    owner = models.CharField(max_length=32)
    status = models.CharField(max_length=32)
    forecast_origin_at = models.DateTimeField()
    approved_at = models.DateTimeField()
    valid_until = models.DateTimeField()
    payload_schema = models.CharField(max_length=64)
    canonical_payload = models.JSONField()
    research_only = models.BooleanField(default=True)
    must_not_use_for_decision = models.BooleanField(default=True)
    must_not_execute = models.BooleanField(default=True)
    recorded_at = models.DateTimeField(editable=False)

    def save(
        self,
        *,
        force_insert: bool | tuple[ModelBase, ...] = False,
        force_update: bool = False,
        using: str | None = None,
        update_fields: Iterable[str] | None = None,
    ) -> None:
        """Accept only an owner-repository receipt timestamp generated just now."""

        if self._state.adding:
            now = timezone.now()
            if (
                self.recorded_at is None
                or self.recorded_at > now
                or now - self.recorded_at > timedelta(seconds=5)
            ):
                raise ValidationError(
                    "Approval recorded_at must be generated by the Equity owner repository."
                )
        super().save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields,
        )

    class Meta:
        db_table = "equity_forecast_baseline_approval_evidence"
        base_manager_name = "objects"
        default_manager_name = "objects"
        constraints = [
            models.UniqueConstraint(
                fields=["approval_id", "approval_version"],
                name="eq_fb_approval_identity_uniq",
            ),
            models.CheckConstraint(
                condition=models.Q(owner="equity", status="approved"),
                name="eq_fb_approval_authority_ck",
            ),
            models.CheckConstraint(
                condition=(
                    models.Q(valid_until__gt=models.F("approved_at"))
                    & models.Q(recorded_at__gte=models.F("approved_at"))
                    & models.Q(recorded_at__lte=models.F("forecast_origin_at"))
                    & models.Q(forecast_origin_at__gte=models.F("approved_at"))
                    & models.Q(forecast_origin_at__lt=models.F("valid_until"))
                ),
                name="eq_fb_approval_time_ck",
            ),
            models.CheckConstraint(
                condition=(
                    models.Q(research_only=True)
                    & models.Q(must_not_use_for_decision=True)
                    & models.Q(must_not_execute=True)
                ),
                name="eq_fb_approval_research_ck",
            ),
            models.CheckConstraint(
                condition=models.Q(content_hash__regex=r"^[0-9a-f]{64}$"),
                name="eq_fb_approval_hash_ck",
            ),
            models.CheckConstraint(
                condition=~models.Q(canonical_payload={}),
                name="eq_fb_approval_payload_ck",
            ),
        ]
        indexes = [
            models.Index(
                fields=["status", "approved_at", "valid_until"],
                name="eq_fb_approval_active_ix",
            ),
            models.Index(
                fields=["forecast_origin_at"],
                name="eq_fb_approval_origin_ix",
            ),
        ]


class ForecastBaselineSpecModel(ForecastBaselineAppendOnlyModel):
    """Canonical immutable ForecastBaselineSpec payload."""

    approval = models.ForeignKey(
        ForecastBaselineApprovalEvidenceModel,
        on_delete=models.PROTECT,
        related_name="spec_records",
    )
    spec_id = models.CharField(max_length=192)
    spec_version = models.CharField(max_length=192)
    content_hash = models.CharField(max_length=64, unique=True)
    owner = models.CharField(max_length=32)
    approval_evidence_id = models.CharField(max_length=192)
    approval_evidence_version = models.CharField(max_length=192)
    approval_evidence_content_hash = models.CharField(max_length=64)
    approval_recorded_at = models.DateTimeField()
    forecast_origin_at = models.DateTimeField()
    approved_at = models.DateTimeField()
    valid_until = models.DateTimeField()
    payload_schema = models.CharField(max_length=64)
    canonical_payload = models.JSONField()
    research_only = models.BooleanField(default=True)
    must_not_use_for_decision = models.BooleanField(default=True)
    must_not_execute = models.BooleanField(default=True)
    recorded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "equity_forecast_baseline_spec"
        base_manager_name = "objects"
        default_manager_name = "objects"
        constraints = [
            models.UniqueConstraint(
                fields=["spec_id", "spec_version"],
                name="eq_fb_spec_identity_uniq",
            ),
            models.CheckConstraint(
                condition=models.Q(owner="equity"),
                name="eq_fb_spec_owner_ck",
            ),
            models.CheckConstraint(
                condition=(
                    models.Q(valid_until__gt=models.F("approved_at"))
                    & models.Q(approval_recorded_at__gte=models.F("approved_at"))
                    & models.Q(approval_recorded_at__lte=models.F("forecast_origin_at"))
                    & models.Q(forecast_origin_at__gte=models.F("approved_at"))
                    & models.Q(forecast_origin_at__lt=models.F("valid_until"))
                ),
                name="eq_fb_spec_time_ck",
            ),
            models.CheckConstraint(
                condition=(
                    models.Q(research_only=True)
                    & models.Q(must_not_use_for_decision=True)
                    & models.Q(must_not_execute=True)
                ),
                name="eq_fb_spec_research_ck",
            ),
            models.CheckConstraint(
                condition=models.Q(content_hash__regex=r"^[0-9a-f]{64}$"),
                name="eq_fb_spec_hash_ck",
            ),
            models.CheckConstraint(
                condition=~models.Q(canonical_payload={}),
                name="eq_fb_spec_payload_ck",
            ),
        ]
        indexes = [
            models.Index(
                fields=["approval_evidence_id", "approval_evidence_version"],
                name="eq_fb_spec_approval_ix",
            ),
            models.Index(
                fields=["forecast_origin_at"],
                name="eq_fb_spec_origin_ix",
            ),
        ]


class ForecastBaselineArtifactModel(ForecastBaselineAppendOnlyModel):
    """Canonical immutable ForecastBaselineArtifact payload."""

    spec = models.ForeignKey(
        ForecastBaselineSpecModel,
        on_delete=models.PROTECT,
        related_name="artifact_records",
    )
    artifact_id = models.CharField(max_length=192)
    artifact_version = models.CharField(max_length=192)
    content_hash = models.CharField(max_length=64, unique=True)
    owner = models.CharField(max_length=32)
    spec_evidence_id = models.CharField(max_length=192)
    spec_evidence_version = models.CharField(max_length=192)
    spec_evidence_content_hash = models.CharField(max_length=64)
    knowledge_as_of = models.DateTimeField()
    produced_at = models.DateTimeField()
    valid_until = models.DateTimeField()
    payload_schema = models.CharField(max_length=64)
    canonical_payload = models.JSONField()
    research_only = models.BooleanField(default=True)
    must_not_use_for_decision = models.BooleanField(default=True)
    must_not_execute = models.BooleanField(default=True)
    recorded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "equity_forecast_baseline_artifact"
        base_manager_name = "objects"
        default_manager_name = "objects"
        constraints = [
            models.UniqueConstraint(
                fields=["artifact_id", "artifact_version"],
                name="eq_fb_artifact_identity_uniq",
            ),
            models.CheckConstraint(
                condition=models.Q(owner="equity"),
                name="eq_fb_artifact_owner_ck",
            ),
            models.CheckConstraint(
                condition=(
                    models.Q(knowledge_as_of__lte=models.F("produced_at"))
                    & models.Q(produced_at__lt=models.F("valid_until"))
                ),
                name="eq_fb_artifact_time_ck",
            ),
            models.CheckConstraint(
                condition=(
                    models.Q(research_only=True)
                    & models.Q(must_not_use_for_decision=True)
                    & models.Q(must_not_execute=True)
                ),
                name="eq_fb_artifact_research_ck",
            ),
            models.CheckConstraint(
                condition=models.Q(content_hash__regex=r"^[0-9a-f]{64}$"),
                name="eq_fb_artifact_hash_ck",
            ),
            models.CheckConstraint(
                condition=~models.Q(canonical_payload={}),
                name="eq_fb_artifact_payload_ck",
            ),
        ]
        indexes = [
            models.Index(
                fields=["spec_evidence_id", "spec_evidence_version"],
                name="eq_fb_artifact_spec_ix",
            ),
            models.Index(
                fields=["knowledge_as_of"],
                name="eq_fb_artifact_asof_ix",
            ),
        ]


class ForecastBaselineTrialResultModel(ForecastBaselineAppendOnlyModel):
    """Canonical immutable ForecastBaselineTrialResult payload."""

    spec = models.ForeignKey(
        ForecastBaselineSpecModel,
        on_delete=models.PROTECT,
        related_name="trial_records",
    )
    artifact = models.ForeignKey(
        ForecastBaselineArtifactModel,
        on_delete=models.PROTECT,
        related_name="trial_records",
    )
    result_id = models.CharField(max_length=192)
    result_version = models.CharField(max_length=192)
    content_hash = models.CharField(max_length=64, unique=True)
    owner = models.CharField(max_length=32)
    spec_evidence_id = models.CharField(max_length=192)
    spec_evidence_version = models.CharField(max_length=192)
    spec_evidence_content_hash = models.CharField(max_length=64)
    artifact_evidence_id = models.CharField(max_length=192)
    artifact_evidence_version = models.CharField(max_length=192)
    artifact_evidence_content_hash = models.CharField(max_length=64)
    actual_manifest_id = models.CharField(max_length=192)
    actual_manifest_version = models.CharField(max_length=192)
    actual_manifest_content_hash = models.CharField(max_length=64)
    research_trial_id = models.CharField(max_length=192)
    research_trial_version = models.CharField(max_length=192)
    research_trial_content_hash = models.CharField(max_length=64)
    evaluated_at = models.DateTimeField()
    valid_until = models.DateTimeField()
    payload_schema = models.CharField(max_length=64)
    canonical_payload = models.JSONField()
    research_only = models.BooleanField(default=True)
    must_not_use_for_decision = models.BooleanField(default=True)
    must_not_execute = models.BooleanField(default=True)
    recorded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "equity_forecast_baseline_trial_result"
        base_manager_name = "objects"
        default_manager_name = "objects"
        constraints = [
            models.UniqueConstraint(
                fields=["result_id", "result_version"],
                name="eq_fb_trial_identity_uniq",
            ),
            models.CheckConstraint(
                condition=models.Q(owner="equity"),
                name="eq_fb_trial_owner_ck",
            ),
            models.CheckConstraint(
                condition=models.Q(valid_until__gt=models.F("evaluated_at")),
                name="eq_fb_trial_time_ck",
            ),
            models.CheckConstraint(
                condition=(
                    models.Q(research_only=True)
                    & models.Q(must_not_use_for_decision=True)
                    & models.Q(must_not_execute=True)
                ),
                name="eq_fb_trial_research_ck",
            ),
            models.CheckConstraint(
                condition=models.Q(content_hash__regex=r"^[0-9a-f]{64}$"),
                name="eq_fb_trial_hash_ck",
            ),
            models.CheckConstraint(
                condition=~models.Q(canonical_payload={}),
                name="eq_fb_trial_payload_ck",
            ),
        ]
        indexes = [
            models.Index(
                fields=["research_trial_id", "research_trial_version"],
                name="eq_fb_trial_research_ix",
            ),
            models.Index(
                fields=["actual_manifest_id", "actual_manifest_version"],
                name="eq_fb_trial_actual_ix",
            ),
            models.Index(
                fields=["evaluated_at"],
                name="eq_fb_trial_eval_ix",
            ),
        ]


__all__ = [
    "ForecastBaselineApprovalEvidenceModel",
    "ForecastBaselineArtifactModel",
    "ForecastBaselineSpecModel",
    "ForecastBaselineTrialResultModel",
]
