# Generated by Django 5.2.9 on 2026-01-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regimeeligibilityconfigmodel",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name="regimeeligibilityconfigmodel",
            unique_together={("asset_class", "regime")},
        ),
        migrations.AddIndex(
            model_name="regimeeligibilityconfigmodel",
            index=models.Index(
                fields=["asset_class", "regime"], name="regime_elig_asset_c_96db03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="regimeeligibilityconfigmodel",
            index=models.Index(fields=["is_active"], name="regime_elig_is_acti_551a9f_idx"),
        ),
    ]
