# Generated by Django 5.2.10 on 2026-03-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpha_trigger", "0002_add_decision_tracking_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alphatriggermodel",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("THRESHOLD_CROSS", "阈值穿越"),
                    ("MOMENTUM_SIGNAL", "动量信号"),
                    ("MEAN_REVERSION", "均值回归"),
                    ("BREAKOUT", "突破"),
                    ("REGIME_TRANSITION", "Regime 转换"),
                    ("POLICY_CHANGE", "Policy 变化"),
                    ("MANUAL_OVERRIDE", "手动覆盖"),
                    ("STRUCTURAL_MISALIGNMENT", "结构性错位"),
                    ("SUPPLY_SHOCK", "供给冲击"),
                    ("CREDIT_SPREAD", "信用利差"),
                    ("CUSTOM", "自定义"),
                ],
                db_index=True,
                default="MOMENTUM_SIGNAL",
                help_text="触发器类型",
                max_length=32,
            ),
        ),
    ]
