# Generated by Django 5.2.12 on 2026-07-28 07:31

from django.conf import settings
from django.db import migrations, models


def validate_existing_share_data(apps, schema_editor):
    """Fail before adding constraints without rewriting historical share records."""

    ShareAccessLog = apps.get_model("share", "ShareAccessLogModel")
    ShareDisclaimer = apps.get_model("share", "ShareDisclaimerConfigModel")
    ShareLink = apps.get_model("share", "ShareLinkModel")
    ShareSnapshot = apps.get_model("share", "ShareSnapshotModel")
    valid_result_statuses = [
        "success",
        "password_required",
        "password_invalid",
        "expired",
        "revoked",
        "max_count_exceeded",
        "not_found",
    ]
    violations = []
    if ShareLink.objects.filter(account_id__lt=1).exists():
        violations.append("non-positive account ID")
    if ShareLink.objects.filter(access_count__lt=0).exists():
        violations.append("negative access count")
    if ShareLink.objects.filter(max_access_count__lt=1).exists():
        violations.append("non-positive maximum access count")
    if ShareLink.objects.filter(
        max_access_count__isnull=False,
        access_count__gt=models.F("max_access_count"),
    ).exists():
        violations.append("access count above maximum")
    if ShareSnapshot.objects.filter(snapshot_version__lt=1).exists():
        violations.append("non-positive snapshot version")
    if ShareSnapshot.objects.filter(
        models.Q(source_range_start__isnull=True, source_range_end__isnull=False)
        | models.Q(source_range_start__isnull=False, source_range_end__isnull=True)
        | models.Q(source_range_end__lt=models.F("source_range_start"))
    ).exists():
        violations.append("invalid snapshot source range")
    if ShareAccessLog.objects.exclude(result_status__in=valid_result_statuses).exists():
        violations.append("unknown access log status")
    if ShareDisclaimer.objects.exclude(singleton_key="default").exists():
        violations.append("non-default disclaimer singleton key")
    if violations:
        raise RuntimeError("Cannot add Share constraints: " + ", ".join(violations))


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0004_update_disclaimer_title_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(validate_existing_share_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="shareaccesslogmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "result_status__in",
                        [
                            "success",
                            "password_required",
                            "password_invalid",
                            "expired",
                            "revoked",
                            "max_count_exceeded",
                            "not_found",
                        ],
                    )
                ),
                name="share_access_log_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharedisclaimerconfigmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("singleton_key", "default")),
                name="share_disclaimer_default_singleton",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharelinkmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("account_id__gte", 1)), name="share_link_account_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="sharelinkmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("access_count__gte", 0)), name="share_link_access_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="sharelinkmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_access_count__isnull", True),
                    ("max_access_count__gte", 1),
                    _connector="OR",
                ),
                name="share_link_max_access_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharelinkmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_access_count__isnull", True),
                    ("access_count__lte", models.F("max_access_count")),
                    _connector="OR",
                ),
                name="share_link_access_within_limit",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharesnapshotmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("snapshot_version__gte", 1)),
                name="share_snapshot_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharesnapshotmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_range_start__isnull", True), ("source_range_end__isnull", True)
                    ),
                    models.Q(
                        ("source_range_start__isnull", False),
                        ("source_range_end__isnull", False),
                        ("source_range_end__gte", models.F("source_range_start")),
                    ),
                    _connector="OR",
                ),
                name="share_snapshot_source_range_valid",
            ),
        ),
    ]
