"""Shared constants for TUI workbench operator-facing view models."""

from __future__ import annotations

import re

HTML_TAG_PATTERN = re.compile(r"</?\s*[a-zA-Z][a-zA-Z0-9:-]*(?:\s+[^<>]*)?>")
ESCAPED_HTML_TAG_PATTERN = re.compile(r"&lt;/?\s*[a-zA-Z][a-zA-Z0-9:-]*")
ASSET_CODE_PATTERN = re.compile(
    r"^(?:\d{6}(?:\.(?:SH|SZ|BJ|OF))?|(?:SH|SZ|BJ)\d{6})$",
    re.IGNORECASE,
)
ASSET_CODE_FIELDS = {"asset_code", "stock_code", "code", "symbol", "fund_code"}
ASSET_NAME_FIELDS = ("asset_name", "stock_name", "fund_name", "name")
ROW_IDENTIFIER_FIELDS = {
    "id",
    "pk",
    "account_id",
    "portfolio_id",
    "asset_code",
    "fund_code",
    "code",
    "symbol",
    "capability_key",
    "strategy_id",
    "strategy",
    "event_id",
    "summary_id",
    "report_id",
    "validation_id",
    "log_id",
    "request_id",
    "task_id",
    "provider_id",
    "snapshot_id",
    "run_id",
    "plan_id",
    "short_code",
    "task_name",
    "period",
    "sector_code",
}

FIELD_LABELS = {
    "account": "账户",
    "account_id": "账户ID",
    "account_name": "账户名称",
    "account_type": "账户类型",
    "action": "动作",
    "action_required": "需要行动",
    "actionable": "可操作",
    "ai_provider_available": "AI服务可用",
    "allocation_effect": "配置效应",
    "annual_return": "年化收益",
    "annualized_return": "年化收益",
    "answer_chain_visibility": "回答链可见性",
    "active": "启用",
    "aggregate_step": "聚合步骤",
    "amount": "金额",
    "asof_date": "日期",
    "asset": "资产",
    "attribution_method": "归因方法",
    "auto_approve_threshold": "自动通过阈值",
    "asset_code": "标的代码",
    "asset_name": "标的名称",
    "available_cash": "可用现金",
    "balance": "余额",
    "band": "区间",
    "base_currency": "基准币种",
    "benchmark_name": "基准名称",
    "benchmark_return": "基准收益",
    "backend_reachable": "后端可达",
    "backtest_id": "回测ID",
    "blocked_reason": "阻塞原因",
    "broker_reachable": "Broker可达",
    "buy_condition_expr": "买入条件",
    "buy_price_expr": "买入价格表达式",
    "cash": "现金",
    "cash_balance": "现金余额",
    "causation_id": "因果ID",
    "category": "分类",
    "checked_at": "检查时间",
    "client_id": "客户端ID",
    "code": "代码",
    "commission_rate": "佣金率",
    "commission_rate_buy": "买入佣金率",
    "commission_rate_sell": "卖出佣金率",
    "commission_rate_wan": "万分佣金率",
    "component": "组件",
    "config": "配置",
    "config_id": "配置ID",
    "children_count": "子项数量",
    "condition_json": "条件",
    "confirmation_required": "需要确认",
    "current_step": "当前步骤",
    "rbac_role": "角色",
    "correlation_id": "关联ID",
    "confidence": "置信度",
    "created_by": "创建人",
    "count": "数量",
    "created_at": "创建时间",
    "currency": "币种",
    "current_regime": "当前环境",
    "daily_quota_limit": "每日配额上限",
    "data_freshness": "数据时效",
    "date": "日期",
    "calculated_at": "计算时间",
    "cache_count": "缓存数量",
    "change_20d": "20日变化",
    "change_5d": "5日变化",
    "default_model": "默认模型",
    "decision_id": "决策ID",
    "description": "说明",
    "detail": "详情",
    "dimension": "维度",
    "direction": "方向",
    "display_label": "显示标签",
    "display_name": "显示名称",
    "drawdown_pct": "回撤率",
    "effective_date": "生效日期",
    "enabled": "启用",
    "error": "错误",
    "env": "环境",
    "event_id": "事件ID",
    "evidence_url": "证据链接",
    "execution_mode": "执行模式",
    "expected_volatility": "预期波动",
    "fallback_used": "已使用降级",
    "external_id": "外部ID",
    "extract_content": "提取正文",
    "fetch_interval_hours": "抓取间隔小时",
    "fetched_at": "抓取时间",
    "filters_available": "可用滤波器",
    "finished_at": "完成时间",
    "from_currency": "源币种",
    "fund_name": "基金名称",
    "full_path": "完整路径",
    "human_readable_invalidation": "证伪条件",
    "id": "ID",
    "generated_at": "生成时间",
    "growth_momentum_z": "增长动量Z值",
    "hedge_recommendation": "对冲建议",
    "initial_capital": "初始资金",
    "invested_ratio": "已投资比例",
    "invested_value": "已投资市值",
    "ip_address": "IP地址",
    "is_active": "是否启用",
    "has_ai_config": "已配置 AI",
    "has_script_config": "已配置脚本",
    "invalidated": "已失效",
    "is_base": "是否基准",
    "is_healthy": "是否健康",
    "is_stale": "是否过期",
    "inflation_momentum_z": "通胀动量Z值",
    "interaction_effect": "交互效应",
    "key": "键",
    "label": "标签",
    "last_check": "最近检查",
    "last_error": "最近错误",
    "latest_index_date": "最近指数日期",
    "last_snapshot_at": "最近快照时间",
    "last_used_at": "最近使用时间",
    "level": "等级",
    "logic_desc": "逻辑说明",
    "lesson_learned": "复盘经验",
    "message": "消息",
    "max_drawdown": "最大回撤",
    "max_pe": "最大PE",
    "max_tokens": "最大Token数",
    "max_turnover": "最大换手",
    "name": "名称",
    "market_value": "市值",
    "metadata": "元数据",
    "mcp_client_id": "MCP客户端ID",
    "min_commission": "最低佣金",
    "min_drawdown": "最小回撤",
    "min_pe": "最小PE",
    "model_artifact_hash": "模型产物哈希",
    "model_id": "模型ID",
    "module": "模块",
    "observed_at": "观测时间",
    "occurred_at": "发生时间",
    "owner_id": "所有者ID",
    "password": "访问密码",
    "parent": "上级",
    "path": "路径",
    "pending_tasks_count": "待处理任务",
    "next": "下一页",
    "normal_sla_hours": "普通SLA小时",
    "override": "覆盖值",
    "p23_sla_hours": "P2/P3 SLA小时",
    "period_days": "周期天数",
    "page": "页码",
    "page_size": "每页行数",
    "previous": "上一页",
    "precision": "精度",
    "priority": "优先级",
    "profit_loss": "盈亏",
    "portfolio": "组合",
    "portfolio_id": "组合ID",
    "portfolio_type": "组合类型",
    "portfolio_return": "组合收益",
    "position_size_expr": "仓位规模表达式",
    "position_limit_pct": "持仓上限率",
    "price": "价格",
    "performance": "绩效",
    "provider_type": "服务商类型",
    "prompt_template": "Prompt模板",
    "pulse_contribution": "脉搏贡献",
    "published_at": "发布时间",
    "provider_id": "数据源ID",
    "pk": "记录ID",
    "queue": "队列",
    "rank": "排名",
    "rate": "汇率",
    "rebalance_frequency": "再平衡频率",
    "ratio": "比例",
    "records_count": "记录数量",
    "recommended_sectors": "推荐板块",
    "regime_accuracy": "环境准确率",
    "regime_contribution": "环境贡献",
    "regime_context": "环境上下文",
    "regime_name": "环境名称",
    "reasoning": "原因说明",
    "report_id": "报告ID",
    "regime": "环境",
    "request_id": "请求ID",
    "requires_password": "需要密码",
    "requires_mcp": "需要MCP",
    "requires_confirmation": "需要确认",
    "result": "结果",
    "return_7d": "7日收益",
    "return_30d": "30日收益",
    "regime_fit_score": "环境匹配评分",
    "risk_level": "风险等级",
    "risk_score": "风险评分",
    "risk_tolerance": "风险承受度",
    "rule_name": "规则名称",
    "rule_type": "规则类型",
    "runtime_seconds": "运行秒数",
    "schema_version": "结构版本",
    "scope_label": "范围",
    "score": "评分",
    "selection_effect": "选股效应",
    "sell_condition_expr": "卖出条件",
    "sell_price_expr": "卖出价格表达式",
    "share_level": "分享等级",
    "share_link": "分享链接",
    "sharpe_ratio": "夏普比率",
    "service": "服务",
    "signal": "信号",
    "slippage_rate": "滑点率",
    "sort_order": "排序",
    "source": "来源",
    "source_range_end": "来源区间结束",
    "source_range_start": "来源区间开始",
    "scale_score": "规模评分",
    "start_date": "开始日期",
    "stamp_duty_rate": "印花税率",
    "stamp_duty_rate_qian": "千分印花税率",
    "started_at": "开始时间",
    "status": "状态",
    "status_display": "状态文本",
    "stop_loss_expr": "止损表达式",
    "stop_loss_pct": "止损率",
    "success": "成功",
    "successful_accesses": "成功访问次数",
    "short_code": "短码",
    "snapshot": "快照",
    "subtitle": "副标题",
    "summary": "说明",
    "setup_state": "接入状态",
    "server_address": "服务地址",
    "setup_guide": "接入步骤",
    "package_build_command": "安装包构建命令",
    "windows_install_command": "Windows 安装命令",
    "token_setup_command": "Token 保存命令",
    "verification_command": "只读验收命令",
    "safety_notice": "安全提示",
    "connected_agent_count": "已连接 Agent",
    "bound_account_count": "已绑定账户",
    "symbol": "符号",
    "system_prompt": "系统提示词",
    "task": "任务",
    "task_domain": "任务域",
    "task_domain_display": "任务域标签",
    "temperature": "温度",
    "template_content": "模板内容",
    "theme": "主题",
    "timestamp": "时间",
    "title": "标题",
    "to_currency": "目标币种",
    "total_accesses": "总访问次数",
    "total_capital_inflow": "累计资金流入",
    "total_capital_outflow": "累计资金流出",
    "total_cost": "总成本",
    "total_pnl": "总盈亏",
    "total_pnl_pct": "总盈亏率",
    "total_trades": "总交易次数",
    "top_n": "候选数量",
    "total": "合计",
    "total_assets": "总资产",
    "total_score": "总评分",
    "total_return": "总收益",
    "total_return_pct": "总收益率",
    "transfer_fee_rate": "过户费率",
    "type": "类型",
    "underlying_index": "跟踪指数",
    "unit": "单位",
    "unique_visitors": "独立访问者",
    "universe": "标的范围",
    "updated_at": "更新时间",
    "url": "链接",
    "user": "用户",
    "username": "用户名",
    "auto_trading_enabled": "自动交易启用",
    "capability_key": "能力标识",
    "version": "版本",
    "fund_code": "基金代码",
    "inception_date": "起始日期",
    "last_trade_date": "最近交易日期",
    "net_capital_flow": "净资金流",
    "net_value": "净值",
    "input_payload": "输入参数",
    "rules_count": "规则数量",
    "steps_count": "步骤数量",
    "proposals_count": "提案数量",
    "artifacts_count": "产物数量",
    "timeline_events_count": "时间线事件数量",
    "triggered": "已触发",
    "watch": "观察",
    "watch_indicators": "观察指标",
    "candidate": "候选",
    "by_type": "按类型",
    "by_status": "按状态",
    "by_direction": "按方向",
    "investable": "可投资",
    "performance_score": "绩效评分",
    "prohibited": "禁投",
    "take_profit_expr": "止盈表达式",
    "value": "值",
    "winning_trades": "盈利交易次数",
    "win_rate": "胜率",
    "weight": "权重",
    "weights": "权重",
    "visibility": "可见性",
    "worker": "执行节点",
}

FIELD_TOKEN_LABELS = {
    "account": "账户",
    "accounts": "账户",
    "action": "动作",
    "aggregate": "聚合",
    "active": "启用",
    "alpha": "Alpha",
    "amount": "金额",
    "answer": "回答",
    "artifact": "产物",
    "asset": "资产",
    "assets": "资产",
    "accuracy": "准确率",
    "audit": "审计",
    "auto": "自动",
    "base": "基准",
    "balance": "余额",
    "band": "区间",
    "backend": "后端",
    "benchmark": "基准",
    "benefiting": "受益",
    "blocked": "阻塞",
    "bond": "债券",
    "broker": "Broker",
    "builtin": "内置",
    "buy": "买入",
    "capability": "能力",
    "capital": "资金",
    "cash": "现金",
    "category": "分类",
    "causation": "因果",
    "checked": "检查",
    "client": "客户端",
    "code": "代码",
    "commission": "佣金",
    "component": "组件",
    "composite": "综合",
    "condition": "条件",
    "config": "配置",
    "confirmation": "确认",
    "commodity": "商品",
    "contribution": "贡献",
    "content": "内容",
    "context": "上下文",
    "correlation": "关联",
    "confidence": "置信度",
    "count": "数量",
    "created": "创建",
    "currency": "币种",
    "current": "当前",
    "data": "数据",
    "daily": "每日",
    "date": "日期",
    "default": "默认",
    "decision": "决策",
    "decisions": "决策",
    "description": "说明",
    "dimension": "维度",
    "direction": "方向",
    "distribution": "分布",
    "display": "显示",
    "disabled": "停用",
    "enabled": "启用",
    "error": "错误",
    "event": "事件",
    "evidence": "证据",
    "effective": "生效",
    "equity": "权益",
    "execution": "执行",
    "expr": "表达式",
    "expected": "预期",
    "extreme": "极端",
    "external": "外部",
    "extract": "提取",
    "factor": "因子",
    "fallback": "降级",
    "fetch": "抓取",
    "fetched": "抓取",
    "finished": "完成",
    "from": "源",
    "fund": "基金",
    "full": "完整",
    "freshness": "时效",
    "generated": "生成",
    "gate": "闸门",
    "growth": "增长",
    "group": "组",
    "has": "已配置",
    "health": "健康",
    "healthy": "健康",
    "human": "可读",
    "id": "ID",
    "indicator": "指标",
    "initial": "初始",
    "investable": "可投资",
    "invested": "已投资",
    "invalidation": "证伪",
    "inflation": "通胀",
    "interaction": "交互",
    "is": "是否",
    "key": "键",
    "label": "标签",
    "learned": "经验",
    "level": "等级",
    "lesson": "复盘",
    "liquidity": "流动性",
    "limit": "上限",
    "logic": "逻辑",
    "links": "链接",
    "message": "消息",
    "market": "市场",
    "max": "最大",
    "mcp": "MCP",
    "metadata": "元数据",
    "min": "最小",
    "model": "模型",
    "module": "模块",
    "momentum": "动量",
    "movement": "变化",
    "name": "名称",
    "observed": "观测",
    "occurred": "发生",
    "operator": "运算符",
    "order": "顺序",
    "owner": "所有者",
    "outside": "外部",
    "only": "仅",
    "parent": "上级",
    "path": "路径",
    "pending": "待处理",
    "params": "参数",
    "portfolio": "组合",
    "position": "持仓",
    "positions": "持仓",
    "probability": "概率",
    "pct": "率",
    "percent": "比例",
    "precision": "精度",
    "priority": "优先级",
    "prompt": "提示词",
    "published": "发布",
    "price": "价格",
    "profit": "盈利",
    "performance": "绩效",
    "policy": "政策",
    "prohibited": "禁投",
    "queue": "队列",
    "quotas": "配额",
    "rank": "排名",
    "ranked": "排名",
    "rate": "率",
    "readable": "可读",
    "reachable": "可达",
    "rebalance": "再平衡",
    "records": "记录",
    "required": "需要",
    "requires": "需要",
    "role": "角色",
    "regime": "环境",
    "recommended": "推荐",
    "report": "报告",
    "request": "请求",
    "requested": "请求",
    "requests": "请求",
    "return": "收益",
    "route": "路由",
    "loss": "亏损",
    "runtime": "运行",
    "seconds": "秒数",
    "sell": "卖出",
    "score": "评分",
    "scope": "范围",
    "sentiment": "情绪",
    "signal": "信号",
    "sort": "排序",
    "source": "来源",
    "sources": "来源",
    "stable": "稳定",
    "stamp": "印花",
    "status": "状态",
    "stocks": "股票",
    "short": "短",
    "snapshot": "快照",
    "started": "开始",
    "strategy": "策略",
    "styles": "风格",
    "subtitle": "副标题",
    "system": "系统",
    "task": "任务",
    "tasks": "任务",
    "template": "模板",
    "threshold": "阈值",
    "theme": "主题",
    "time": "时间",
    "timestamp": "时间",
    "title": "标题",
    "to": "目标",
    "tokens": "令牌",
    "top": "前列",
    "trends": "趋势",
    "transition": "切换",
    "transitioning": "切换中",
    "transfer": "过户",
    "transaction": "交易",
    "transactions": "交易",
    "turnover": "换手",
    "total": "合计",
    "type": "类型",
    "underlying": "跟踪",
    "unsafe": "受限",
    "unit": "单位",
    "updated": "更新",
    "url": "链接",
    "user": "用户",
    "username": "用户名",
    "value": "值",
    "version": "版本",
    "domain": "域",
    "visibility": "可见性",
    "volatility": "波动",
    "visitor": "访问者",
    "visitors": "访问者",
    "warning": "预警",
    "warnings": "预警",
    "winning": "盈利",
    "weight": "权重",
    "weights": "权重",
    "worker": "执行节点",
    "workflow": "流程",
}

STATUS_LABELS = {
    "OK": "正常",
    "EMPTY": "暂无数据",
    "REDIRECT": "跳转",
    "ERROR": "错误",
}

VALUE_LABELS = {
    "active": "启用",
    "degraded": "降级",
    "disabled": "禁用",
    "draft": "草稿",
    "enabled": "启用",
    "error": "错误",
    "expired": "已过期",
    "failed": "失败",
    "fresh": "最新",
    "healthy": "健康",
    "high": "高",
    "inactive": "停用",
    "low": "低",
    "market": "市场",
    "medium": "中",
    "moderate": "中等",
    "ok": "正常",
    "overheat": "过热",
    "pending": "待处理",
    "password_invalid": "密码错误",
    "password_required": "需要密码",
    "ready": "就绪",
    "recession": "衰退",
    "recovery": "复苏",
    "regime": "环境引擎",
    "revoked": "已撤销",
    "running": "运行中",
    "safe": "安全",
    "stagflation": "滞胀",
    "stable": "稳定",
    "success": "成功",
    "system": "系统",
    "warning": "预警",
    "filter api": "筛选服务",
    "buy": "买入",
}

EMBEDDED_VALUE_LABELS = {
    "overheat": "过热",
    "recession": "衰退",
    "recovery": "复苏",
    "stagflation": "滞胀",
}

FIELD_VALUE_LABELS = {
    "account_type": {
        "real": "实盘",
        "simulated": "模拟",
    },
    "portfolio_type": {
        "real": "实盘",
        "simulated": "模拟",
    },
    "rbac_role": {
        "admin": "管理员",
        "observer": "观察者",
        "owner": "所有者",
        "viewer": "查看者",
    },
    "risk_tolerance": {
        "aggressive": "激进",
        "conservative": "保守",
        "moderate": "中等",
    },
    "share_level": {
        "snapshot": "快照",
    },
    "task_domain": {
        "research": "研究",
    },
    "task_domain_display": {
        "research": "研究",
    },
    "visibility": {
        "private": "私密",
        "public": "公开",
    },
}
