# Generated by Django 5.2.9 on 2025-12-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("macro", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="macroindicator",
            new_name="macro_indic_code_108657_idx",
            old_name="macro_in_code_obs_idx",
        ),
        migrations.AlterUniqueTogether(
            name="macroindicator",
            unique_together={("code", "observed_at", "revision_number")},
        ),
    ]
