# Generated by Django 5.2.9 on 2025-12-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("macro", "0004_alter_macroindicator_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="macroindicator",
            name="period_type",
            field=models.CharField(
                default="D",
                help_text="期间类型（D=日,W=周,M=月,Q=季,H=半,Y=年,3M=3月期,10Y=10年期等）",
                max_length=10,
            ),
        ),
    ]
