# Generated by Django 5.2.9 on 2026-01-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("macro", "0005_extend_period_type_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="macroindicator",
            name="unit",
            field=models.CharField(
                default="", help_text="单位（如 %、指数、点、元、元/g、元/吨等）", max_length=50
            ),
        ),
    ]
