# Generated by Django 5.2.9 on 2026-01-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("macro", "0007_macroindicator_original_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="macroindicator",
            name="value",
            field=models.FloatField(help_text="指标值"),
        ),
    ]
