# Generated by Codex on 2026-03-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("macro", "0011_alter_exchangeratemodel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasourceconfig",
            name="http_url",
            field=models.URLField(
                blank=True,
                help_text="自定义 HTTP URL（Tushare 可用于第三方代理源）",
            ),
        ),
    ]
