# Generated by Django 5.2.12 on 2026-04-16 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpha", "0003_add_user_to_alpha_score_cache"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alphascorecachemodel",
            name="scope_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="账户驱动股票池 scope hash",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="alphascorecachemodel",
            name="scope_label",
            field=models.CharField(
                blank=True, help_text="账户驱动股票池展示名称", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="alphascorecachemodel",
            name="scope_metadata",
            field=models.JSONField(blank=True, help_text="账户驱动股票池元数据", null=True),
        ),
        migrations.AddIndex(
            model_name="alphascorecachemodel",
            index=models.Index(
                fields=["scope_hash", "intended_trade_date"], name="alpha_score_scope_h_5d2cea_idx"
            ),
        ),
    ]
