# Generated by Django 5.2.10 on 2026-03-08 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpha", "0002_alphaalertmodel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="alphascorecachemodel",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="alphascorecachemodel",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alpha_score_caches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="上传用户（None=系统级）",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alphascorecachemodel",
            unique_together={
                (
                    "user",
                    "universe_id",
                    "intended_trade_date",
                    "provider_source",
                    "model_artifact_hash",
                )
            },
        ),
    ]
