"""Idempotent bootstrap of the Config Center runtime definition registry."""

from __future__ import annotations

from apps.config_center.application.runtime_config import (
    RuntimeConfigDefinitionRepositoryPort,
)
from apps.config_center.domain.runtime_config import (
    RuntimeConfigCriticality,
    RuntimeConfigDefinition,
    RuntimeConfigReloadMode,
    RuntimeValueType,
)

DEFAULT_RUNTIME_DEFINITIONS: tuple[RuntimeConfigDefinition, ...] = (
    RuntimeConfigDefinition(
        key="data_center.provider.failover_tolerance",
        namespace="data_center",
        owner_app="data_center",
        value_type=RuntimeValueType.DECIMAL,
        constraints={"minimum": 0.0, "maximum": 1.0},
        criticality=RuntimeConfigCriticality.CRITICAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Cross-provider consistency tolerance for macro failover.",
        user_impact="Controls when provider responses are considered inconsistent.",
    ),
    RuntimeConfigDefinition(
        key="data_center.provider.enable_failover",
        namespace="data_center",
        owner_app="data_center",
        value_type=RuntimeValueType.BOOL,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Whether the macro provider adapter may fail over to a backup source.",
        user_impact="Disabling failover leaves only the configured primary provider.",
    ),
    RuntimeConfigDefinition(
        key="data_center.provider.default_source",
        namespace="data_center",
        owner_app="data_center",
        value_type=RuntimeValueType.ENUM,
        constraints={"choices": ["akshare", "tushare", "failover"]},
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Primary macro data provider selected for the next data task.",
        user_impact="Controls whether macro tasks start with AKShare, Tushare, or the failover chain.",
    ),
    RuntimeConfigDefinition(
        key="task_monitor.retention_days",
        namespace="task_monitor",
        owner_app="task_monitor",
        value_type=RuntimeValueType.INT,
        constraints={"minimum": 1, "maximum": 3650},
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Number of days to retain local database backup artifacts.",
        user_impact="Controls bounded backup cleanup; missing typed policy blocks automatic backup.",
    ),
    RuntimeConfigDefinition(
        key="backup.enabled",
        namespace="backup",
        owner_app="account",
        value_type=RuntimeValueType.BOOL,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="Whether scheduled database-backup delivery is enabled.",
        user_impact="Controls whether the backup email task may issue a download link.",
    ),
    RuntimeConfigDefinition(
        key="backup.recipient_email",
        namespace="backup",
        owner_app="account",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="Mailbox receiving scheduled database-backup links.",
        user_impact="Controls the destination of backup delivery notifications.",
    ),
    RuntimeConfigDefinition(
        key="backup.app_base_url",
        namespace="backup",
        owner_app="account",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="Absolute application URL used in backup download links.",
        user_impact="Controls the host embedded in emailed download links.",
    ),
    RuntimeConfigDefinition(
        key="backup.mail_from_email",
        namespace="backup",
        owner_app="account",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="Optional sender address for backup delivery emails.",
        user_impact="Controls the visible sender of backup notifications.",
    ),
    RuntimeConfigDefinition(
        key="backup.smtp_host",
        namespace="backup",
        owner_app="account",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="SMTP host used for backup delivery.",
        user_impact="Controls which mail relay sends backup notifications.",
    ),
    RuntimeConfigDefinition(
        key="backup.smtp_port",
        namespace="backup",
        owner_app="account",
        value_type=RuntimeValueType.INT,
        constraints={"minimum": 1, "maximum": 65535},
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="SMTP port used for backup delivery.",
        user_impact="Controls the network port used by the backup mail relay.",
    ),
    RuntimeConfigDefinition(
        key="backup.smtp_username",
        namespace="backup",
        owner_app="account",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="SMTP username used for backup delivery.",
        user_impact="Controls the account presented to the backup mail relay.",
    ),
    RuntimeConfigDefinition(
        key="backup.smtp_use_tls",
        namespace="backup",
        owner_app="account",
        value_type=RuntimeValueType.BOOL,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="Whether the backup SMTP connection uses STARTTLS.",
        user_impact="Controls transport encryption for the backup mail connection.",
    ),
    RuntimeConfigDefinition(
        key="backup.smtp_use_ssl",
        namespace="backup",
        owner_app="account",
        value_type=RuntimeValueType.BOOL,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="Whether the backup SMTP connection uses implicit TLS.",
        user_impact="Controls implicit TLS for the backup mail connection.",
    ),
    RuntimeConfigDefinition(
        key="backup.interval_days",
        namespace="backup",
        owner_app="account",
        value_type=RuntimeValueType.INT,
        constraints={"minimum": 1, "maximum": 3650},
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Minimum interval between scheduled backup delivery emails.",
        user_impact="Controls how often the backup task may send a new link.",
    ),
    RuntimeConfigDefinition(
        key="backup.link_ttl_days",
        namespace="backup",
        owner_app="account",
        value_type=RuntimeValueType.INT,
        constraints={"minimum": 1, "maximum": 3650},
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="Lifetime of an emailed database-backup download link.",
        user_impact="Controls how long a backup link remains usable.",
    ),
    RuntimeConfigDefinition(
        key="backup.password_hint",
        namespace="backup",
        owner_app="account",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="Non-secret operator hint for the backup archive password.",
        user_impact="Provides a safe reminder without exposing the backup password.",
    ),
    RuntimeConfigDefinition(
        key="backup.archive_password",
        namespace="backup",
        owner_app="account",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        secret=True,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="Secret reference for the encrypted backup archive password.",
        user_impact="Controls the password used to encrypt generated backup artifacts.",
    ),
    RuntimeConfigDefinition(
        key="backup.smtp_password",
        namespace="backup",
        owner_app="account",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        secret=True,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="Secret reference for the backup SMTP password.",
        user_impact="Controls authentication to the backup mail relay.",
    ),
    RuntimeConfigDefinition(
        key="account.require_user_approval",
        namespace="account",
        owner_app="account",
        value_type=RuntimeValueType.BOOL,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="Whether newly registered users require administrator approval.",
        user_impact="Controls whether an unreviewed registration may become active.",
    ),
    RuntimeConfigDefinition(
        key="account.auto_approve_first_admin",
        namespace="account",
        owner_app="account",
        value_type=RuntimeValueType.BOOL,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="Whether the first administrator registration may be auto-approved.",
        user_impact="Controls bootstrap administrator creation when no administrator exists.",
    ),
    RuntimeConfigDefinition(
        key="account.default_mcp_enabled",
        namespace="account",
        owner_app="account",
        value_type=RuntimeValueType.BOOL,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="Default MCP/SDK access state for newly provisioned accounts.",
        user_impact="Controls whether new accounts start with MCP access enabled.",
    ),
    RuntimeConfigDefinition(
        key="account.allow_token_plaintext_view",
        namespace="account",
        owner_app="account",
        value_type=RuntimeValueType.BOOL,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="Whether newly generated access tokens may be shown in plaintext.",
        user_impact="Controls whether a secret is returned to an administrator after creation.",
    ),
    RuntimeConfigDefinition(
        key="account.user_agreement_content",
        namespace="account",
        owner_app="account",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="User agreement content shown during account registration.",
        user_impact="Controls the agreement text that a registrant must accept.",
    ),
    RuntimeConfigDefinition(
        key="account.risk_warning_content",
        namespace="account",
        owner_app="account",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="Risk warning content shown during account registration.",
        user_impact="Controls the risk disclosure text that a registrant must acknowledge.",
    ),
    RuntimeConfigDefinition(
        key="account.notes",
        namespace="account",
        owner_app="account",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Administrator note attached to the account governance profile.",
        user_impact="Stores operator context without changing account access decisions.",
    ),
    RuntimeConfigDefinition(
        key="alpha.qlib.enabled",
        namespace="alpha",
        owner_app="alpha",
        value_type=RuntimeValueType.BOOL,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Whether Qlib-backed alpha inference is enabled.",
        user_impact="Controls whether the Qlib alpha provider may participate in inference.",
    ),
    RuntimeConfigDefinition(
        key="alpha.qlib.provider_uri",
        namespace="alpha",
        owner_app="alpha",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.RESTART_REQUIRED,
        description="Qlib data provider URI used by alpha inference and calendar checks.",
        user_impact="Changing the URI changes the local Qlib data source used by alpha jobs.",
    ),
    RuntimeConfigDefinition(
        key="alpha.qlib.region",
        namespace="alpha",
        owner_app="alpha",
        value_type=RuntimeValueType.STRING,
        constraints={"choices": ["CN", "US"]},
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Qlib market region used when initializing the alpha runtime.",
        user_impact="Controls the market-specific Qlib calendar and instrument conventions.",
    ),
    RuntimeConfigDefinition(
        key="alpha.qlib.model_path",
        namespace="alpha",
        owner_app="alpha",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.RESTART_REQUIRED,
        description="Filesystem path containing Qlib model artifacts.",
        user_impact="Changing the path changes which model artifacts can be loaded.",
    ),
    RuntimeConfigDefinition(
        key="alpha.qlib.default_universe",
        namespace="alpha",
        owner_app="alpha",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Default Qlib instrument universe for alpha jobs.",
        user_impact="Controls the universe used when a job does not specify one explicitly.",
    ),
    RuntimeConfigDefinition(
        key="alpha.qlib.default_feature_set_id",
        namespace="alpha",
        owner_app="alpha",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Default feature-set identifier for Qlib training and inference.",
        user_impact="Controls the feature contract used when a job omits a feature-set ID.",
    ),
    RuntimeConfigDefinition(
        key="alpha.qlib.default_label_id",
        namespace="alpha",
        owner_app="alpha",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Default label identifier for Qlib training.",
        user_impact="Controls the prediction target when a training job omits a label ID.",
    ),
    RuntimeConfigDefinition(
        key="alpha.qlib.train_queue_name",
        namespace="alpha",
        owner_app="alpha",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Celery queue used for Qlib training tasks.",
        user_impact="Changing the queue changes where training work is dispatched.",
    ),
    RuntimeConfigDefinition(
        key="alpha.qlib.infer_queue_name",
        namespace="alpha",
        owner_app="alpha",
        value_type=RuntimeValueType.STRING,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Celery queue used for Qlib inference tasks.",
        user_impact="Changing the queue changes where inference work is dispatched.",
    ),
    RuntimeConfigDefinition(
        key="alpha.qlib.allow_auto_activate",
        namespace="alpha",
        owner_app="alpha",
        value_type=RuntimeValueType.BOOL,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Whether Qlib training may automatically activate a produced model.",
        user_impact="Controls whether successful training can change the active model without manual review.",
    ),
    RuntimeConfigDefinition(
        key="alpha.runtime.fixed_provider",
        namespace="alpha",
        owner_app="alpha",
        value_type=RuntimeValueType.ENUM,
        constraints={"choices": ["", "qlib", "cache", "simple", "etf"]},
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Optional fixed Alpha provider; empty means controlled failover.",
        user_impact="Pins Alpha provider selection when explicitly configured.",
    ),
    RuntimeConfigDefinition(
        key="alpha.runtime.pool_mode",
        namespace="alpha",
        owner_app="alpha",
        value_type=RuntimeValueType.ENUM,
        constraints={"choices": ["strict_valuation", "market", "price_covered"]},
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Default Alpha candidate-pool mode.",
        user_impact="Controls which evidence-qualified candidate universe Alpha may use.",
    ),
    RuntimeConfigDefinition(
        key="config_center.market.color_convention",
        namespace="config_center",
        owner_app="config_center",
        value_type=RuntimeValueType.ENUM,
        constraints={"choices": ["cn_a_share", "us_market"]},
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.IMMEDIATE,
        description="Market visual convention used by client projections.",
        user_impact="Controls the display semantics of rising and falling values.",
    ),
    RuntimeConfigDefinition(
        key="config_center.market.benchmark_code_map",
        namespace="config_center",
        owner_app="config_center",
        value_type=RuntimeValueType.TYPED_JSON,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Named benchmark codes used by business Application facades.",
        user_impact="Controls benchmark instruments used in comparisons and attribution.",
    ),
    RuntimeConfigDefinition(
        key="config_center.market.asset_proxy_code_map",
        namespace="config_center",
        owner_app="config_center",
        value_type=RuntimeValueType.TYPED_JSON,
        criticality=RuntimeConfigCriticality.NORMAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Asset-class to canonical proxy code mapping.",
        user_impact="Controls proxy instruments used when an asset class has no direct quote.",
    ),
    RuntimeConfigDefinition(
        key="audit.system_event.mode",
        namespace="audit",
        owner_app="audit",
        value_type=RuntimeValueType.ENUM,
        constraints={"choices": ["off", "shadow", "required"]},
        criticality=RuntimeConfigCriticality.CRITICAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="System audit event emission mode.",
        user_impact="Controls governed audit emission.",
    ),
    RuntimeConfigDefinition(
        key="audit.system_event.outbox_enabled",
        namespace="audit",
        owner_app="audit",
        value_type=RuntimeValueType.BOOL,
        criticality=RuntimeConfigCriticality.CRITICAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Enable system audit outbox delivery.",
        user_impact="Controls durable audit delivery.",
    ),
    RuntimeConfigDefinition(
        key="audit.system_event.authority_selector",
        namespace="audit",
        owner_app="audit",
        value_type=RuntimeValueType.TYPED_JSON,
        criticality=RuntimeConfigCriticality.CRITICAL,
        reload_mode=RuntimeConfigReloadMode.NEXT_TASK,
        description="Server-issued audit authority selector.",
        user_impact="Binds audit reads to immutable authority sources.",
    ),
)


def reconcile_runtime_definitions(
    repository: RuntimeConfigDefinitionRepositoryPort,
    definitions: tuple[RuntimeConfigDefinition, ...] = DEFAULT_RUNTIME_DEFINITIONS,
) -> tuple[RuntimeConfigDefinition, ...]:
    """Upsert the owned definition catalog and return persisted definitions.

    The infrastructure repository performs an update-or-create by stable key,
    so running this operation repeatedly is safe and does not create duplicate
    definitions.
    """

    persisted: list[RuntimeConfigDefinition] = []
    for definition in definitions:
        persisted.append(repository.save(definition))
    return tuple(persisted)


__all__ = ["DEFAULT_RUNTIME_DEFINITIONS", "reconcile_runtime_definitions"]
