"""SDK contract actions for strategy APIs."""

from rest_framework import status
from rest_framework.decorators import action
from rest_framework.response import Response

from apps.strategy.application.interface_services import (
    execute_strategy_for_assignments,
    get_strategy_performance_payload,
    list_strategy_position_payloads,
    list_strategy_signal_payloads,
    list_strategy_trade_payloads,
)

from .serializers import (
    StrategyEmptyQuerySerializer,
    StrategyExecuteRequestSerializer,
    StrategyHistoryQuerySerializer,
    StrategyPerformanceQuerySerializer,
    StrategySignalQuerySerializer,
)


class StrategySDKContractActionsMixin:
    """Expose strategy operations required by the public SDK contract."""

    @action(detail=True, methods=["post"])
    def execute(self, request, pk=None):
        """Execute the strategy for one or all active portfolio assignments."""

        strategy = self.get_object()
        serializer = StrategyExecuteRequestSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        try:
            payload = execute_strategy_for_assignments(
                strategy_id=strategy.id,
                portfolio_id=serializer.validated_data.get("portfolio_id"),
                as_of_date=serializer.validated_data.get("as_of_date"),
            )
        except ValueError as exc:
            return Response(
                {"success": False, "error": str(exc)},
                status=status.HTTP_400_BAD_REQUEST,
            )
        return Response(payload)

    @action(detail=True, methods=["get"])
    def signals(self, request, pk=None):
        """Return persisted signals generated by this strategy."""

        strategy = self.get_object()
        serializer = StrategySignalQuerySerializer(data=request.query_params)
        serializer.is_valid(raise_exception=True)
        results = list_strategy_signal_payloads(
            strategy_id=strategy.id,
            status=serializer.validated_data.get("status"),
            limit=serializer.validated_data["limit"],
        )
        return Response({"results": results, "count": len(results)})

    @action(detail=True, methods=["get"])
    def performance(self, request, pk=None):
        """Return truthful execution performance for this strategy."""

        strategy = self.get_object()
        serializer = StrategyPerformanceQuerySerializer(data=request.query_params)
        serializer.is_valid(raise_exception=True)
        return Response(
            get_strategy_performance_payload(
                strategy_id=strategy.id,
                start_date=serializer.validated_data.get("start_date"),
                end_date=serializer.validated_data.get("end_date"),
            )
        )

    @action(detail=True, methods=["get"])
    def positions(self, request, pk=None):
        """Return positions in portfolios currently assigned to this strategy."""

        strategy = self.get_object()
        serializer = StrategyEmptyQuerySerializer(data=request.query_params)
        serializer.is_valid(raise_exception=True)
        results = list_strategy_position_payloads(strategy_id=strategy.id)
        return Response({"results": results, "count": len(results)})

    @action(detail=True, methods=["get"])
    def trades(self, request, pk=None):
        """Return ledger trades in portfolios currently assigned to this strategy."""

        strategy = self.get_object()
        serializer = StrategyHistoryQuerySerializer(data=request.query_params)
        serializer.is_valid(raise_exception=True)
        results = list_strategy_trade_payloads(
            strategy_id=strategy.id,
            start_date=serializer.validated_data.get("start_date"),
            end_date=serializer.validated_data.get("end_date"),
            limit=serializer.validated_data["limit"],
        )
        return Response({"results": results, "count": len(results)})
