"""SDK contract actions for strategy APIs."""

from collections.abc import Callable
from typing import Any, Protocol, TypeVar, cast

from rest_framework import status
from rest_framework.decorators import action
from rest_framework.request import Request
from rest_framework.response import Response

from apps.strategy.application.interface_services import (
    execute_strategy_for_assignments,
    get_strategy_performance_payload,
    list_strategy_position_payloads,
    list_strategy_signal_payloads,
    list_strategy_trade_payloads,
)

from .serializers import (
    StrategyEmptyQuerySerializer,
    StrategyExecuteRequestSerializer,
    StrategyHistoryQuerySerializer,
    StrategyPerformanceQuerySerializer,
    StrategySignalQuerySerializer,
)

ViewMethod = TypeVar("ViewMethod", bound=Callable[..., Any])


class StrategyObject(Protocol):
    """Minimum strategy shape consumed by SDK actions."""

    id: int


class StrategyViewSetPort(Protocol):
    """ViewSet operation supplied by the concrete DRF class."""

    def get_object(self) -> StrategyObject:
        """Return the owner-scoped strategy object."""


def typed_action(*args: Any, **kwargs: Any) -> Callable[[ViewMethod], ViewMethod]:
    """Expose DRF's action decorator without erasing method annotations."""

    return cast(Callable[[ViewMethod], ViewMethod], action(*args, **kwargs))


class StrategySDKContractActionsMixin:
    """Expose strategy operations required by the public SDK contract."""

    @typed_action(detail=True, methods=["post"])
    def execute(self, request: Request, pk: str | None = None) -> Response:
        """Execute the strategy for one or all active portfolio assignments."""

        strategy = cast(StrategyViewSetPort, self).get_object()
        serializer = StrategyExecuteRequestSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        try:
            payload = execute_strategy_for_assignments(
                strategy_id=strategy.id,
                portfolio_id=serializer.validated_data.get("portfolio_id"),
                as_of_date=serializer.validated_data.get("as_of_date"),
            )
        except ValueError as exc:
            return Response(
                {"success": False, "error": str(exc)},
                status=status.HTTP_400_BAD_REQUEST,
            )
        return Response(payload)

    @typed_action(detail=True, methods=["get"])
    def signals(self, request: Request, pk: str | None = None) -> Response:
        """Return persisted signals generated by this strategy."""

        strategy = cast(StrategyViewSetPort, self).get_object()
        serializer = StrategySignalQuerySerializer(data=request.query_params)
        serializer.is_valid(raise_exception=True)
        results = list_strategy_signal_payloads(
            strategy_id=strategy.id,
            status=serializer.validated_data.get("status"),
            limit=serializer.validated_data["limit"],
        )
        return Response({"results": results, "count": len(results)})

    @typed_action(detail=True, methods=["get"])
    def performance(self, request: Request, pk: str | None = None) -> Response:
        """Return truthful execution performance for this strategy."""

        strategy = cast(StrategyViewSetPort, self).get_object()
        serializer = StrategyPerformanceQuerySerializer(data=request.query_params)
        serializer.is_valid(raise_exception=True)
        return Response(
            get_strategy_performance_payload(
                strategy_id=strategy.id,
                start_date=serializer.validated_data.get("start_date"),
                end_date=serializer.validated_data.get("end_date"),
            )
        )

    @typed_action(detail=True, methods=["get"])
    def positions(self, request: Request, pk: str | None = None) -> Response:
        """Return positions in portfolios currently assigned to this strategy."""

        strategy = cast(StrategyViewSetPort, self).get_object()
        serializer = StrategyEmptyQuerySerializer(data=request.query_params)
        serializer.is_valid(raise_exception=True)
        results = list_strategy_position_payloads(strategy_id=strategy.id)
        return Response({"results": results, "count": len(results)})

    @typed_action(detail=True, methods=["get"])
    def trades(self, request: Request, pk: str | None = None) -> Response:
        """Return ledger trades in portfolios currently assigned to this strategy."""

        strategy = cast(StrategyViewSetPort, self).get_object()
        serializer = StrategyHistoryQuerySerializer(data=request.query_params)
        serializer.is_valid(raise_exception=True)
        results = list_strategy_trade_payloads(
            strategy_id=strategy.id,
            start_date=serializer.validated_data.get("start_date"),
            end_date=serializer.validated_data.get("end_date"),
            limit=serializer.validated_data["limit"],
        )
        return Response({"results": results, "count": len(results)})
