# Generated by Django 5.2.12 on 2026-07-21 17:45

import decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.broker_execution.infrastructure.models


class Migration(migrations.Migration):

    dependencies = [
        ("broker_execution", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="brokeraccountbindingmodel",
            name="allowed_trading_windows",
            field=models.JSONField(
                blank=True,
                default=apps.broker_execution.infrastructure.models.default_trading_windows,
            ),
        ),
        migrations.AddField(
            model_name="brokeraccountbindingmodel",
            name="enforce_trading_session",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="brokeraccountbindingmodel",
            name="max_position_count",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="brokeraccountbindingmodel",
            name="max_snapshot_age_seconds",
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name="brokeraccountbindingmodel",
            name="price_deviation_limit_pct",
            field=models.DecimalField(
                decimal_places=4, default=decimal.Decimal("0.03"), max_digits=7
            ),
        ),
        migrations.AddField(
            model_name="reconciliationrunmodel",
            name="run_key",
            field=models.CharField(blank=True, max_length=96, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="BrokerExecutionAlertModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("account_id", models.PositiveIntegerField(db_index=True)),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("severity", models.CharField(db_index=True, max_length=8)),
                ("status", models.CharField(db_index=True, default="open", max_length=16)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("auto_stop_applied", models.BooleanField(default=False)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "broker_execution_alert",
                "ordering": ["-last_seen_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "account_id", "status", "severity"],
                        name="broker_exec_user_id_50d284_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BrokerExecutionDailyReportModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("account_id", models.PositiveIntegerField(db_index=True)),
                ("report_date", models.DateField(db_index=True)),
                ("status", models.CharField(db_index=True, default="ok", max_length=16)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "broker_execution_daily_report",
                "ordering": ["-report_date", "-generated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "account_id", "report_date"),
                        name="uq_broker_exec_daily_report",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReconciliationDifferenceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("order", "委托"),
                            ("fill", "成交"),
                            ("cash", "资金"),
                            ("position", "持仓"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("difference_key", models.CharField(max_length=160)),
                ("severity", models.CharField(db_index=True, default="P1", max_length=8)),
                ("expected", models.JSONField(blank=True, default=dict)),
                ("actual", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField()),
                ("status", models.CharField(db_index=True, default="open", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="differences",
                        to="broker_execution.reconciliationrunmodel",
                    ),
                ),
            ],
            options={
                "db_table": "broker_execution_reconciliation_difference",
                "indexes": [
                    models.Index(
                        fields=["run", "dimension", "status"], name="broker_exec_run_id_283748_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "dimension", "difference_key"),
                        name="uq_broker_exec_recon_difference",
                    )
                ],
            },
        ),
    ]
