# Generated by Django 5.2.12 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create an empty Broker-owned R8 reconciliation receipt registry."""

    dependencies = [("broker_execution", "0006_nullable_audit_owner")]

    operations = [
        migrations.CreateModel(
            name="R8BrokerMonitoringPeriodReceiptModel",
            fields=[
                (
                    "receipt_id",
                    models.CharField(max_length=96, primary_key=True, serialize=False),
                ),
                ("receipt_version", models.CharField(max_length=96)),
                ("definition_id", models.CharField(max_length=96)),
                ("definition_version", models.CharField(max_length=96)),
                ("definition_hash", models.CharField(max_length=64)),
                ("definition_payload", models.JSONField()),
                ("source_receipt_id", models.CharField(max_length=128)),
                ("source_receipt_version", models.CharField(max_length=96)),
                ("source_receipt_hash", models.CharField(max_length=64)),
                ("source_receipt_payload", models.JSONField()),
                ("result_id", models.CharField(max_length=192)),
                ("result_hash", models.CharField(max_length=64)),
                ("portfolio_receipt_id", models.CharField(max_length=192)),
                ("portfolio_receipt_version", models.CharField(max_length=128)),
                ("portfolio_receipt_hash", models.CharField(max_length=64)),
                ("calendar_id", models.CharField(max_length=192)),
                ("calendar_version", models.CharField(max_length=128)),
                ("calendar_hash", models.CharField(max_length=64)),
                ("period_id", models.CharField(max_length=192)),
                ("period_start_at", models.DateTimeField()),
                ("period_end_at", models.DateTimeField()),
                ("planning_reference_id", models.CharField(max_length=192)),
                ("planning_reference_version", models.CharField(max_length=128)),
                ("planning_reference_hash", models.CharField(max_length=64)),
                ("reconciliation_manifest_id", models.CharField(max_length=192)),
                ("reconciliation_manifest_version", models.CharField(max_length=128)),
                ("reconciliation_manifest_hash", models.CharField(max_length=64)),
                ("source_observed_at", models.DateTimeField()),
                ("source_available_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                (
                    "total_cost_amount",
                    models.DecimalField(decimal_places=12, max_digits=38),
                ),
                (
                    "total_cost_notional",
                    models.DecimalField(decimal_places=12, max_digits=38),
                ),
                (
                    "adverse_slippage_amount",
                    models.DecimalField(decimal_places=12, max_digits=38),
                ),
                (
                    "adverse_slippage_notional",
                    models.DecimalField(decimal_places=12, max_digits=38),
                ),
                ("reconciliation_break_count", models.PositiveBigIntegerField()),
                ("reconciliation_comparison_count", models.PositiveBigIntegerField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "broker_execution_r8_monitoring_period_receipt",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=[
                            "result_id",
                            "calendar_id",
                            "period_id",
                            "recorded_at",
                        ],
                        name="be_r8_mon_target_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("definition_id", "definition_version"),
                        name="be_r8_mon_definition_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("source_receipt_id", "source_receipt_version"),
                        name="be_r8_mon_source_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("result_id", "calendar_id", "period_id"),
                        name="be_r8_mon_period_uq",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(period_start_at__lt=models.F("period_end_at"))
                            & models.Q(source_observed_at__gte=models.F("period_start_at"))
                            & models.Q(source_observed_at__lte=models.F("period_end_at"))
                            & models.Q(source_available_at__gte=models.F("source_observed_at"))
                            & models.Q(recorded_at__gte=models.F("source_available_at"))
                            & models.Q(valid_until__gt=models.F("recorded_at"))
                        ),
                        name="be_r8_mon_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(total_cost_amount__gte=0)
                            & models.Q(total_cost_notional__gt=0)
                            & models.Q(total_cost_amount__lte=models.F("total_cost_notional"))
                            & models.Q(adverse_slippage_amount__gte=0)
                            & models.Q(adverse_slippage_notional__gt=0)
                            & models.Q(
                                adverse_slippage_amount__lte=models.F("adverse_slippage_notional")
                            )
                            & models.Q(reconciliation_comparison_count__gt=0)
                            & models.Q(
                                reconciliation_break_count__lte=models.F(
                                    "reconciliation_comparison_count"
                                )
                            )
                        ),
                        name="be_r8_mon_ratio_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            receipt_version=("broker-r8-monitoring-period-receipt.v1"),
                            definition_version=("broker-r8-reconciliation-definition.v1"),
                            source_receipt_version=("broker-r8-reconciliation-source.v1"),
                            research_only=True,
                            must_not_use_for_decision=True,
                            must_not_publish_current=True,
                            must_not_execute=True,
                        ),
                        name="be_r8_mon_safe_ck",
                    ),
                ],
            },
        )
    ]
