# Generated by Django 5.2.10 on 2026-03-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_provider", "0002_aiproviderconfig_api_mode_fallback_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiproviderconfig",
            name="api_key_encrypted",
            field=models.TextField(blank=True, help_text="API Key (encrypted at rest)"),
        ),
        migrations.AlterField(
            model_name="aiproviderconfig",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="API Key (plaintext, deprecated - use api_key_encrypted)",
                max_length=500,
            ),
        ),
    ]
