# Generated by Django 5.2.12 on 2026-07-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0031_seed_etf_flow_atomic_indicators"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionCoverageUniverseConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "universe_id",
                    models.CharField(
                        default="active_a_share",
                        help_text="Logical universe identifier used by readiness diagnostics",
                        max_length=50,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        default="stock",
                        help_text="AssetMaster asset_type included in coverage diagnostics",
                        max_length=20,
                    ),
                ),
                (
                    "exchanges",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Included MarketExchange codes, e.g. SSE/SZSE/BSE",
                    ),
                ),
                (
                    "include_inactive",
                    models.BooleanField(
                        default=False,
                        help_text="Include inactive/delisted assets in the coverage denominator",
                    ),
                ),
                ("min_active_asset_count", models.PositiveIntegerField(default=4000)),
                ("min_star_market_count", models.PositiveIntegerField(default=200)),
                ("min_chinext_count", models.PositiveIntegerField(default=0)),
                ("min_bse_count", models.PositiveIntegerField(default=50)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Production Coverage Universe Config",
                "verbose_name_plural": "Production Coverage Universe Config",
                "db_table": "data_center_production_coverage_universe_config",
            },
        ),
    ]
