# Generated by Django 5.2.12 on 2026-07-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0039_pit_fact_versions_and_manifests"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="fundnavfactmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("nav__gt", 0),
                    models.Q(("fund_code", ""), _negated=True),
                    models.Q(("source", ""), _negated=True),
                ),
                name="dc_fund_nav_executable_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricebarmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("close__gt", 0),
                    models.Q(("asset_code", ""), _negated=True),
                    models.Q(("source", ""), _negated=True),
                ),
                name="dc_price_bar_executable_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotesnapshotmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("current_price__gt", 0),
                    models.Q(("asset_code", ""), _negated=True),
                    models.Q(("source", ""), _negated=True),
                ),
                name="dc_quote_executable_price",
            ),
        ),
    ]
