# Generated by Django 5.2.12 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_center", "0048_seed_a_share_behavior_indicators"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotesnapshotmodel",
            name="fetched_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
