# Generated by Django 5.2.12 on 2026-08-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0053_archivemanifestmodel_retentionpolicymodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataOwnerRegistrationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dataset_key", models.CharField(max_length=160, unique=True)),
                ("data_platform_owner", models.CharField(max_length=100)),
                ("business_owner", models.CharField(max_length=100)),
                ("acceptance_owner", models.CharField(max_length=100)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_center_data_owner_registration",
                "ordering": ["dataset_key"],
                "indexes": [
                    models.Index(
                        fields=["business_owner", "active"], name="data_center_busines_440828_idx"
                    ),
                    models.Index(
                        fields=["acceptance_owner", "active"], name="data_center_accepta_d66271_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DatasetContractModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dataset_key", models.CharField(db_index=True, max_length=160)),
                ("contract_version", models.CharField(max_length=40)),
                ("schema_version", models.CharField(max_length=40)),
                ("owner", models.CharField(db_index=True, max_length=100)),
                ("frequency", models.CharField(max_length=40)),
                ("decision_critical", models.BooleanField(db_index=True, default=False)),
                ("fields", models.JSONField(default=list)),
                ("freshness_seconds", models.PositiveBigIntegerField(blank=True, null=True)),
                ("comparable_group", models.CharField(blank=True, max_length=120)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_center_dataset_contract",
                "ordering": ["dataset_key", "contract_version", "schema_version"],
                "indexes": [
                    models.Index(
                        fields=["dataset_key", "active"], name="data_center_dataset_ebd8a2_idx"
                    ),
                    models.Index(
                        fields=["owner", "decision_critical"], name="data_center_owner_a56837_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset_key", "contract_version", "schema_version"),
                        name="dc_dataset_contract_version_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DatasetProviderBindingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dataset_key", models.CharField(db_index=True, max_length=160)),
                ("contract_version", models.CharField(max_length=40)),
                ("schema_version", models.CharField(max_length=40)),
                ("provider", models.CharField(db_index=True, max_length=100)),
                ("capability", models.CharField(max_length=80)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("freshness_seconds", models.PositiveBigIntegerField(blank=True, null=True)),
                ("validator_key", models.CharField(max_length=160)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_center_dataset_provider_binding",
                "ordering": ["dataset_key", "priority", "provider"],
                "indexes": [
                    models.Index(
                        fields=["dataset_key", "enabled", "priority"],
                        name="data_center_dataset_a8a70c_idx",
                    ),
                    models.Index(
                        fields=["provider", "capability", "enabled"],
                        name="data_center_provide_18d247_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "dataset_key",
                            "contract_version",
                            "schema_version",
                            "provider",
                            "capability",
                        ),
                        name="dc_dataset_binding_version_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DatasetPublicationPolicyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dataset_key", models.CharField(db_index=True, max_length=160)),
                ("contract_version", models.CharField(max_length=40)),
                ("schema_version", models.CharField(max_length=40)),
                ("minimum_coverage_ratio", models.FloatField()),
                ("allow_partial", models.BooleanField(default=False)),
                ("conflict_action", models.CharField(max_length=40)),
                ("required_evidence", models.JSONField(default=list)),
                ("retention_days", models.PositiveIntegerField()),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_center_dataset_publication_policy",
                "ordering": ["dataset_key", "contract_version", "schema_version"],
                "indexes": [
                    models.Index(
                        fields=["dataset_key", "active"], name="data_center_dataset_bc01d4_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset_key", "contract_version", "schema_version"),
                        name="dc_dataset_policy_version_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("minimum_coverage_ratio__gte", 0.0),
                            ("minimum_coverage_ratio__lte", 1.0),
                        ),
                        name="dc_dataset_policy_coverage_ratio_valid",
                    ),
                ],
            },
        ),
    ]
