# Generated by Django 5.2.12 on 2026-08-02 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0054_dataownerregistrationmodel_datasetcontractmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationEvidenceModel",
            fields=[
                (
                    "evidence_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("dataset_key", models.CharField(db_index=True, max_length=160)),
                ("legacy_snapshot_hash", models.CharField(db_index=True, max_length=128)),
                ("canonical_snapshot_hash", models.CharField(db_index=True, max_length=128)),
                ("classification_counts", models.JSONField(default=dict)),
                ("is_clean", models.BooleanField(db_index=True, default=False)),
                ("observed_at", models.DateTimeField(db_index=True)),
                ("rows", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "data_center_reconciliation_evidence",
                "ordering": ["-observed_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dataset_key", "observed_at"], name="data_center_dataset_3b5977_idx"
                    ),
                    models.Index(
                        fields=["dataset_key", "is_clean", "observed_at"],
                        name="data_center_dataset_b43199_idx",
                    ),
                ],
            },
        ),
    ]
