# Generated by Django 5.2.12 on 2026-08-02 21:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0055_reconciliationevidencemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionRunModel",
            fields=[
                (
                    "run_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("dataset_key", models.CharField(db_index=True, max_length=160)),
                ("policy_version", models.PositiveIntegerField(blank=True, null=True)),
                ("dry_run", models.BooleanField(default=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "success"),
                            ("partial", "partial"),
                            ("noop", "noop"),
                            ("blocked", "blocked"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("requested", models.PositiveIntegerField(default=0)),
                ("candidates", models.PositiveIntegerField(default=0)),
                ("planned", models.PositiveIntegerField(default=0)),
                ("deleted", models.PositiveIntegerField(default=0)),
                ("held", models.PositiveIntegerField(default=0)),
                ("blocked", models.PositiveIntegerField(default=0)),
                ("bytes_planned", models.PositiveBigIntegerField(default=0)),
                ("bytes_deleted", models.PositiveBigIntegerField(default=0)),
                ("cutoff", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(db_index=True)),
                ("finished_at", models.DateTimeField()),
                ("reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "data_center_retention_run",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["dataset_key", "started_at"], name="data_center_dataset_144018_idx"
                    ),
                    models.Index(
                        fields=["outcome", "started_at"], name="data_center_outcome_d66373_idx"
                    ),
                ],
            },
        ),
    ]
