# Generated by Django 5.2.12 on 2026-08-04 00:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0056_retentionrunmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalpublicationmodel",
            name="reinstated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PublicationRollbackModel",
            fields=[
                (
                    "rollback_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_publication_id", models.UUIDField(db_index=True)),
                ("previous_publication_id", models.UUIDField(db_index=True)),
                ("dataset_key", models.CharField(db_index=True, max_length=160)),
                ("publication_key", models.CharField(max_length=300)),
                ("reason", models.TextField()),
                ("operator", models.CharField(max_length=150)),
                ("observed_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "data_center_publication_rollback",
                "ordering": ["-observed_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dataset_key", "publication_key", "observed_at"],
                        name="data_center_dataset_da9510_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_publication_id", "observed_at"),
                        name="dc_publication_rollback_target_time_unique",
                    ),
                ],
            },
        ),
    ]
