# Generated by Django 5.2.12 on 2026-08-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0057_publicationrollbackmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetGroupRevisionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_code", models.CharField(db_index=True, max_length=64)),
                ("revision", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=160)),
                ("source", models.CharField(db_index=True, max_length=100)),
                ("effective_at", models.DateTimeField(db_index=True)),
                (
                    "effective_to",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_center_asset_group_revision",
                "ordering": ["group_code", "revision"],
                "indexes": [
                    models.Index(
                        fields=["group_code", "is_active", "revision"],
                        name="dc_asset_group_active_idx",
                    ),
                    models.Index(
                        fields=["source", "is_active"],
                        name="dc_asset_group_source_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group_code", "revision"),
                        name="dc_asset_group_revision_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_at")),
                            _connector="OR",
                        ),
                        name="dc_asset_group_interval_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvestorFlowDefinitionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flow_code", models.CharField(db_index=True, max_length=64)),
                ("definition_version", models.PositiveIntegerField()),
                ("actor_code", models.CharField(db_index=True, max_length=64)),
                ("actor_name", models.CharField(max_length=160)),
                (
                    "measure_kind",
                    models.CharField(
                        choices=[
                            ("capital_balance", "capital_balance"),
                            ("holding_change", "holding_change"),
                            ("transaction_net_flow", "transaction_net_flow"),
                        ],
                        max_length=40,
                    ),
                ),
                ("canonical_unit", models.CharField(max_length=40)),
                ("frequency", models.CharField(max_length=40)),
                ("source", models.CharField(db_index=True, max_length=100)),
                ("effective_at", models.DateTimeField(db_index=True)),
                (
                    "effective_to",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_proxy", models.BooleanField(db_index=True, default=False)),
                ("proxy_target_actor_code", models.CharField(blank=True, max_length=64)),
                ("proxy_methodology_ref", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_center_investor_flow_definition",
                "ordering": ["flow_code", "definition_version"],
                "indexes": [
                    models.Index(
                        fields=["actor_code", "measure_kind", "is_active"],
                        name="dc_flow_actor_measure_idx",
                    ),
                    models.Index(
                        fields=["source", "is_proxy", "is_active"],
                        name="dc_flow_source_proxy_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("flow_code", "definition_version"),
                        name="dc_investor_flow_version_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_at")),
                            _connector="OR",
                        ),
                        name="dc_investor_flow_interval_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("is_proxy", True),
                                models.Q(("proxy_target_actor_code", ""), _negated=True),
                                models.Q(("proxy_methodology_ref", ""), _negated=True),
                            ),
                            models.Q(
                                ("is_proxy", False),
                                ("proxy_target_actor_code", ""),
                                ("proxy_methodology_ref", ""),
                            ),
                            _connector="OR",
                        ),
                        name="dc_investor_flow_proxy_metadata_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OperatingMetricDefinitionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_code", models.CharField(db_index=True, max_length=64)),
                ("definition_version", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=160)),
                ("canonical_unit", models.CharField(max_length=40)),
                ("frequency", models.CharField(max_length=40)),
                ("source", models.CharField(db_index=True, max_length=100)),
                ("effective_at", models.DateTimeField(db_index=True)),
                (
                    "effective_to",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_center_operating_metric_definition",
                "ordering": ["metric_code", "definition_version"],
                "indexes": [
                    models.Index(
                        fields=["metric_code", "is_active", "definition_version"],
                        name="dc_oper_metric_active_idx",
                    ),
                    models.Index(
                        fields=["source", "is_active"],
                        name="dc_oper_metric_source_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("metric_code", "definition_version"),
                        name="dc_operating_metric_version_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_at")),
                            _connector="OR",
                        ),
                        name="dc_operating_metric_interval_valid",
                    ),
                ],
            },
        ),
    ]
