# Generated by Django 5.2.12 on 2026-08-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0058_assetgrouprevisionmodel_investorflowdefinitionmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investorflowdefinitionmodel",
            name="measure_kind",
            field=models.CharField(
                choices=[
                    ("fund_flow", "fund_flow"),
                    ("capital_balance", "capital_balance"),
                    ("holding_change", "holding_change"),
                    ("transaction_net_flow", "transaction_net_flow"),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="InvestorActorDefinitionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("taxonomy_code", models.CharField(db_index=True, max_length=64)),
                ("taxonomy_version", models.PositiveIntegerField()),
                ("actor_code", models.CharField(db_index=True, max_length=64)),
                ("actor_name", models.CharField(max_length=160)),
                ("parent_actor_code", models.CharField(blank=True, max_length=64)),
                ("source", models.CharField(db_index=True, max_length=100)),
                ("revision_policy_ref", models.CharField(max_length=300)),
                ("effective_at", models.DateTimeField(db_index=True)),
                ("effective_to", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("definition_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "data_center_investor_actor_definition",
                "ordering": ["taxonomy_code", "taxonomy_version", "actor_code"],
                "indexes": [
                    models.Index(
                        fields=["taxonomy_code", "taxonomy_version", "is_active"],
                        name="dc_ms_actor_tax_idx",
                    ),
                    models.Index(fields=["actor_code", "is_active"], name="dc_ms_actor_code_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("taxonomy_code", "taxonomy_version", "actor_code"),
                        name="dc_ms_actor_version_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_at")),
                            _connector="OR",
                        ),
                        name="dc_ms_actor_interval_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketStructureResearchEvidenceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("evidence_key", models.CharField(db_index=True, max_length=128)),
                ("evidence_version", models.PositiveIntegerField()),
                ("as_of_time", models.DateTimeField(db_index=True)),
                ("group_code", models.CharField(db_index=True, max_length=64)),
                ("group_revision", models.PositiveIntegerField()),
                ("method_version", models.CharField(db_index=True, max_length=64)),
                ("policy_code", models.CharField(db_index=True, max_length=64)),
                ("policy_version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "available"), ("blocked", "blocked")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("input_hash", models.CharField(db_index=True, max_length=64)),
                ("output_hash", models.CharField(max_length=64)),
                ("evidence_hash", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField()),
                ("source_evidence", models.JSONField(blank=True, default=list)),
                ("research_only", models.BooleanField(default=True, editable=False)),
                ("must_not_use_for_decision", models.BooleanField(default=True, editable=False)),
                ("must_not_execute", models.BooleanField(default=True, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "data_center_market_structure_evidence",
                "ordering": ["evidence_key", "evidence_version"],
                "indexes": [
                    models.Index(
                        fields=["group_code", "group_revision", "-as_of_time"],
                        name="dc_ms_evidence_group_idx",
                    ),
                    models.Index(
                        fields=["method_version", "status"], name="dc_ms_evidence_method_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("evidence_key", "evidence_version"),
                        name="dc_ms_evidence_version_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("research_only", True)),
                        name="dc_ms_evidence_research_only",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("must_not_use_for_decision", True)),
                        name="dc_ms_evidence_no_decision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("must_not_execute", True)),
                        name="dc_ms_evidence_no_execute",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketStructureSeriesDefinitionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("series_code", models.CharField(db_index=True, max_length=64)),
                ("series_version", models.PositiveIntegerField()),
                ("flow_code", models.CharField(db_index=True, max_length=64)),
                ("flow_definition_version", models.PositiveIntegerField()),
                ("taxonomy_code", models.CharField(db_index=True, max_length=64)),
                ("taxonomy_version", models.PositiveIntegerField()),
                ("actor_code", models.CharField(db_index=True, max_length=64)),
                (
                    "measure_concept",
                    models.CharField(
                        choices=[
                            ("flow", "flow"),
                            ("holding", "holding"),
                            ("stock", "stock"),
                            ("transaction", "transaction"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "measure_kind",
                    models.CharField(
                        choices=[
                            ("fund_flow", "fund_flow"),
                            ("capital_balance", "capital_balance"),
                            ("holding_change", "holding_change"),
                            ("transaction_net_flow", "transaction_net_flow"),
                        ],
                        max_length=40,
                    ),
                ),
                ("canonical_unit", models.CharField(max_length=40)),
                ("frequency", models.CharField(max_length=40)),
                ("source", models.CharField(db_index=True, max_length=100)),
                ("revision_policy_ref", models.CharField(max_length=300)),
                ("effective_at", models.DateTimeField(db_index=True)),
                ("effective_to", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_proxy", models.BooleanField(db_index=True, default=False)),
                ("proxy_target_actor_code", models.CharField(blank=True, max_length=64)),
                ("proxy_methodology_ref", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("definition_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "data_center_market_structure_series",
                "ordering": ["series_code", "series_version"],
                "indexes": [
                    models.Index(
                        fields=["actor_code", "measure_concept", "is_active"],
                        name="dc_ms_series_actor_idx",
                    ),
                    models.Index(
                        fields=["flow_code", "flow_definition_version"],
                        name="dc_ms_series_flow_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("series_code", "series_version"), name="dc_ms_series_version_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gt", models.F("effective_at")),
                            _connector="OR",
                        ),
                        name="dc_ms_series_interval_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("is_proxy", True),
                                models.Q(("proxy_target_actor_code", ""), _negated=True),
                                models.Q(("proxy_methodology_ref", ""), _negated=True),
                            ),
                            models.Q(
                                ("is_proxy", False),
                                ("proxy_target_actor_code", ""),
                                ("proxy_methodology_ref", ""),
                            ),
                            _connector="OR",
                        ),
                        name="dc_ms_series_proxy_valid",
                    ),
                ],
            },
        ),
    ]
