# Generated by Django 5.2.8 on 2026-08-05

import hashlib
import json
from datetime import UTC

from django.db import migrations, models
from django.db.models import F


def backfill_available_at(apps, schema_editor):
    """Use the prior effective clock and reseal legacy definition payloads."""

    for model_name in (
        "InvestorActorDefinitionModel",
        "MarketStructureSeriesDefinitionModel",
    ):
        model = apps.get_model("data_center", model_name)
        model._default_manager.filter(available_at__isnull=True).update(
            available_at=F("effective_at")
        )
    actor_model = apps.get_model("data_center", "InvestorActorDefinitionModel")
    for row in actor_model._default_manager.all().iterator():
        payload = {
            "actor_code": row.actor_code,
            "actor_name": row.actor_name,
            "available_at": row.available_at.astimezone(UTC).isoformat(),
            "description": row.description,
            "effective_at": row.effective_at.astimezone(UTC).isoformat(),
            "effective_to": (
                row.effective_to.astimezone(UTC).isoformat()
                if row.effective_to is not None
                else None
            ),
            "expires_at": (
                row.expires_at.astimezone(UTC).isoformat() if row.expires_at is not None else None
            ),
            "is_active": row.is_active,
            "parent_actor_code": row.parent_actor_code,
            "revision_policy_ref": row.revision_policy_ref,
            "source": row.source,
            "taxonomy_code": row.taxonomy_code,
            "taxonomy_version": row.taxonomy_version,
        }
        digest = hashlib.sha256(
            json.dumps(payload, separators=(",", ":"), sort_keys=True).encode("utf-8")
        ).hexdigest()
        actor_model._default_manager.filter(pk=row.pk).update(definition_hash=digest)

    series_model = apps.get_model("data_center", "MarketStructureSeriesDefinitionModel")
    for row in series_model._default_manager.all().iterator():
        payload = {
            "actor_code": row.actor_code,
            "available_at": row.available_at.astimezone(UTC).isoformat(),
            "canonical_unit": row.canonical_unit,
            "description": row.description,
            "effective_at": row.effective_at.astimezone(UTC).isoformat(),
            "effective_to": (
                row.effective_to.astimezone(UTC).isoformat()
                if row.effective_to is not None
                else None
            ),
            "expires_at": (
                row.expires_at.astimezone(UTC).isoformat() if row.expires_at is not None else None
            ),
            "flow_code": row.flow_code,
            "flow_definition_version": row.flow_definition_version,
            "frequency": row.frequency,
            "is_active": row.is_active,
            "is_proxy": row.is_proxy,
            "measure_concept": row.measure_concept,
            "measure_kind": row.measure_kind,
            "proxy_methodology_ref": row.proxy_methodology_ref,
            "proxy_target_actor_code": row.proxy_target_actor_code,
            "revision_policy_ref": row.revision_policy_ref,
            "series_code": row.series_code,
            "series_version": row.series_version,
            "source": row.source,
            "taxonomy_code": row.taxonomy_code,
            "taxonomy_version": row.taxonomy_version,
        }
        digest = hashlib.sha256(
            json.dumps(payload, separators=(",", ":"), sort_keys=True).encode("utf-8")
        ).hexdigest()
        series_model._default_manager.filter(pk=row.pk).update(definition_hash=digest)


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0059_market_structure_research_slice"),
    ]

    operations = [
        migrations.AddField(
            model_name="investoractordefinitionmodel",
            name="available_at",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="investoractordefinitionmodel",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="marketstructureseriesdefinitionmodel",
            name="available_at",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="marketstructureseriesdefinitionmodel",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_available_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="investoractordefinitionmodel",
            name="available_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name="investoractordefinitionmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("available_at__gte", F("effective_at"))),
                name="dc_ms_actor_available_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="investoractordefinitionmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__isnull", True))
                | models.Q(("expires_at__gt", F("available_at"))),
                name="dc_ms_actor_expiry_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketstructureseriesdefinitionmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("available_at__gte", F("effective_at"))),
                name="dc_ms_series_available_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketstructureseriesdefinitionmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__isnull", True))
                | models.Q(("expires_at__gt", F("available_at"))),
                name="dc_ms_series_expiry_valid",
            ),
        ),
        migrations.AlterField(
            model_name="marketstructureseriesdefinitionmodel",
            name="available_at",
            field=models.DateTimeField(db_index=True),
        ),
    ]
