# Generated by Django 5.2.12 on 2026-08-06 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0061_market_structure_period_calendar"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderCredentialModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("credential_ref", models.CharField(max_length=300, unique=True)),
                ("api_key_encrypted", models.TextField(blank=True)),
                ("api_secret_encrypted", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential_record",
                        to="data_center.providerconfigmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provider Credential",
                "verbose_name_plural": "Provider Credentials",
                "db_table": "data_center_provider_credential",
            },
        ),
    ]
