# Generated by Django 5.2.12 on 2026-08-07 05:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0063_archivemanifest_archive_restore_evidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionPlanModel",
            fields=[
                (
                    "plan_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("operation_id", models.CharField(max_length=160, unique=True)),
                ("dataset_key", models.CharField(db_index=True, max_length=160)),
                ("policy_id", models.UUIDField()),
                ("policy_version", models.PositiveIntegerField()),
                ("requested", models.PositiveIntegerField()),
                ("candidates", models.PositiveIntegerField(default=0)),
                ("planned", models.PositiveIntegerField(default=0)),
                ("held", models.PositiveIntegerField(default=0)),
                ("blocked", models.PositiveIntegerField(default=0)),
                ("bytes_planned", models.PositiveBigIntegerField(default=0)),
                ("cutoff", models.DateTimeField()),
                ("created_at", models.DateTimeField(db_index=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("snapshot_digest", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "ready"),
                            ("empty", "empty"),
                            ("blocked", "blocked"),
                            ("enforcing", "enforcing"),
                            ("completed", "completed"),
                            ("partial", "partial"),
                            ("failed", "failed"),
                            ("expired", "expired"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "enforce_operation_id",
                    models.CharField(blank=True, max_length=160, null=True, unique=True),
                ),
                ("outcome", models.CharField(blank=True, max_length=16)),
                ("deleted", models.PositiveIntegerField(default=0)),
                ("execution_blocked", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("bytes_deleted", models.PositiveBigIntegerField(default=0)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
            ],
            options={
                "db_table": "data_center_retention_plan",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dataset_key", "status", "expires_at"],
                        name="data_center_dataset_7f140b_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("requested__gte", 1), ("requested__lte", 10000)),
                        name="dc_retention_plan_requested_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("created_at"))),
                        name="dc_retention_plan_expiry_after_create",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RetentionPlanMemberModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ordinal", models.PositiveIntegerField()),
                ("payload_id", models.UUIDField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("record_digest", models.CharField(max_length=64)),
                ("schema_fingerprint", models.CharField(max_length=128)),
                ("fetched_at", models.DateTimeField()),
                ("retention_until", models.DateTimeField(blank=True, null=True)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("eligible", "eligible"),
                            ("held", "held"),
                            ("retention_blocked", "retention_blocked"),
                            ("archive_blocked", "archive_blocked"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "execution",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("skipped", "skipped"),
                            ("deleted", "deleted"),
                            ("blocked", "blocked"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("execution_reason", models.TextField(blank=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archive",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retention_plan_members",
                        to="data_center.archivemanifestmodel",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="data_center.retentionplanmodel",
                    ),
                ),
            ],
            options={
                "db_table": "data_center_retention_plan_member",
                "ordering": ["plan_id", "ordinal"],
                "indexes": [
                    models.Index(
                        fields=["plan", "execution", "ordinal"],
                        name="data_center_plan_id_85aa17_idx",
                    ),
                    models.Index(
                        fields=["payload_id", "record_digest"],
                        name="data_center_payload_77c1e8_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plan", "payload_id"), name="dc_ret_plan_member_payload_uniq"
                    ),
                    models.UniqueConstraint(
                        fields=("plan", "ordinal"), name="dc_ret_plan_member_ordinal_uniq"
                    ),
                ],
            },
        ),
    ]
