# Generated by Django 5.2.16 on 2026-09-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0076_publication_policy_versions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canonicalpublicationmodel",
            name="policy_version",
            field=models.CharField(max_length=128),
        ),
    ]
