# Generated by Django 5.2.16 on 2026-09-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0077_publication_evidence_identity_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationmembermodel",
            name="available_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicationmembermodel",
            name="fact_content_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="publicationmembermodel",
            name="fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicationmembermodel",
            name="raw_payload_scope",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="publicationmembermodel",
            name="source_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
