# Generated by Django 5.2.12 on 2026-09-21 06:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0078_frozen_publication_member_evidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncItemAttemptModel",
            fields=[
                (
                    "attempt_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("run_id", models.UUIDField(db_index=True)),
                ("batch_id", models.UUIDField(db_index=True)),
                ("dataset_key", models.CharField(db_index=True, max_length=160)),
                ("asset_code", models.CharField(db_index=True, max_length=20)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("quote", "quote"),
                            ("valuation", "valuation"),
                            ("price", "price"),
                            ("financial", "financial"),
                            ("publication", "publication"),
                        ],
                        max_length=24,
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("running", "running"),
                            ("succeeded", "succeeded"),
                            ("failed", "failed"),
                            ("blocked", "blocked"),
                            ("interrupted", "interrupted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("execution_token", models.CharField(max_length=100)),
                ("started_at", models.DateTimeField(db_index=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("stored_count", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.TextField(blank=True)),
                ("universe_hash", models.CharField(max_length=64)),
                ("authority_content_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_center_sync_item_attempt",
                "ordering": ["batch_id", "asset_code", "phase", "attempt_number"],
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["batch_id", "asset_code", "phase", "attempt_number"],
                        name="dc_item_attempt_identity_idx",
                    ),
                    models.Index(fields=["batch_id", "state"], name="dc_item_attempt_state_idx"),
                    models.Index(
                        fields=["run_id", "batch_id", "phase", "state"],
                        name="dc_item_attempt_run_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch_id", "asset_code", "phase", "attempt_number"),
                        name="dc_sync_item_attempt_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempt_number__gte", 1)),
                        name="dc_sync_item_attempt_number_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("finished_at__isnull", True), ("state", "running")),
                            models.Q(
                                models.Q(("state", "running"), _negated=True),
                                ("finished_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="dc_sync_item_attempt_terminal_time",
                    ),
                ],
            },
        ),
    ]
