# Generated by Django 5.2.8 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0079_sync_item_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncitemattemptmodel",
            name="evidence_hash",
            field=models.CharField(blank=True, default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="syncitemattemptmodel",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(
                        ("phase", "publication"),
                        ("state", "succeeded"),
                    )
                    | ~models.Q(("evidence_hash", ""))
                ),
                name="dc_item_pub_evidence",
            ),
        ),
    ]
