# Generated by Django 5.2.12 on 2026-10-01 22:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0088_publication_member_manifest_seal"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateRawAuditManifestModel",
            fields=[
                (
                    "manifest_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("manifest_version", models.CharField(max_length=16)),
                ("publication_hash", models.CharField(max_length=64)),
                ("run_id", models.UUIDField(db_index=True)),
                ("dataset_key", models.CharField(db_index=True, max_length=160)),
                ("publication_key", models.CharField(max_length=300)),
                ("task_attempt_id", models.CharField(db_index=True, max_length=160)),
                ("raw_audit_count", models.PositiveIntegerField()),
                ("raw_audit_hash", models.CharField(max_length=64)),
                ("manifest_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publication",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_raw_audit_manifest",
                        to="data_center.canonicalpublicationmodel",
                    ),
                ),
            ],
            options={
                "db_table": "data_center_candidate_raw_audit_manifest",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="CandidateRawAuditManifestMemberModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ordinal", models.PositiveIntegerField()),
                ("raw_audit_version", models.CharField(max_length=16)),
                ("raw_audit_content_hash", models.CharField(max_length=64)),
                ("provider_name", models.CharField(max_length=50)),
                ("capability", models.CharField(max_length=30)),
                ("run_id", models.UUIDField(db_index=True)),
                ("ingested_run_id", models.UUIDField(db_index=True)),
                (
                    "raw_audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidate_manifest_memberships",
                        to="data_center.rawauditmodel",
                    ),
                ),
                (
                    "manifest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="data_center.candidaterawauditmanifestmodel",
                    ),
                ),
            ],
            options={
                "db_table": "data_center_candidate_raw_audit_manifest_member",
                "ordering": ["manifest_id", "ordinal"],
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AddIndex(
            model_name="candidaterawauditmanifestmodel",
            index=models.Index(
                fields=["dataset_key", "publication_key"], name="dc_raw_manifest_scope_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidaterawauditmanifestmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("manifest_version", "1"), ("raw_audit_count__gte", 1)),
                name="dc_raw_manifest_header_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="candidaterawauditmanifestmembermodel",
            index=models.Index(
                fields=["manifest", "ordinal"], name="dc_raw_manifest_member_ord_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidaterawauditmanifestmembermodel",
            constraint=models.UniqueConstraint(
                fields=("manifest", "ordinal"), name="dc_raw_manifest_member_ord_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidaterawauditmanifestmembermodel",
            constraint=models.UniqueConstraint(
                fields=("manifest", "raw_audit"), name="dc_raw_manifest_member_audit_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidaterawauditmanifestmembermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("raw_audit_version", "1")), name="dc_raw_manifest_member_ver_ck"
            ),
        ),
    ]
