# Generated by Django 5.2.12 on 2026-10-08 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0092_financial_capacity_owner_approval_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialPublicationCapacityEvidenceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ordinal", models.PositiveIntegerField()),
                ("evidence", models.JSONField()),
                ("evidence_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slice_evidence",
                        to="data_center.financialpublicationcapacityworkflowmodel",
                    ),
                ),
            ],
            options={
                "db_table": "data_center_financial_capacity_slice_evidence",
                "ordering": ["ordinal"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workflow", "ordinal"), name="dc_cap_evidence_workflow_ordinal_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FinancialPublicationCapacityManifestItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ordinal", models.PositiveIntegerField()),
                ("asset_code", models.CharField(max_length=20)),
                ("announcement_date", models.DateField()),
                ("item_sha256", models.CharField(max_length=64)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manifest_items",
                        to="data_center.financialpublicationcapacityworkflowmodel",
                    ),
                ),
            ],
            options={
                "db_table": "data_center_financial_capacity_manifest_item",
                "ordering": ["ordinal"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workflow", "ordinal"), name="dc_cap_manifest_workflow_ordinal_uniq"
                    ),
                    models.UniqueConstraint(
                        fields=("workflow", "asset_code", "announcement_date"),
                        name="dc_cap_manifest_slice_uniq",
                    ),
                ],
            },
        ),
    ]
