# Generated by Django 5.2.12 on 2026-10-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0094_financial_scope_discovery_governance_stages"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialScopeManifestCurrentPointerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("isolated", "Isolated capacity rehearsal"),
                            ("production", "Production"),
                        ],
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("report_payload", models.JSONField()),
                ("report_sha256", models.CharField(max_length=64)),
                ("owner_approval_id", models.CharField(max_length=300)),
                ("owner_event_id", models.CharField(max_length=300)),
                ("reviewer_approval_id", models.CharField(max_length=300)),
                ("reviewer_event_id", models.CharField(max_length=300)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("updated_by", models.CharField(max_length=150)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "data_center_financial_scope_manifest_current_pointer",
            },
        ),
    ]
