# Generated by Django 5.2.12 on 2026-10-09 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_center", "0096_financial_scope_capacity_import_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialScopeCapacityImportConsumptionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workflow_id", models.CharField(max_length=300, unique=True)),
                ("record_sha256", models.CharField(max_length=64)),
                ("event_payload", models.JSONField()),
                ("event_sha256", models.CharField(max_length=64, unique=True)),
                ("consumed_at", models.DateTimeField()),
                (
                    "scope_import",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="formal_consumption",
                        to="data_center.financialscopecapacityimportmodel",
                    ),
                ),
            ],
            options={
                "db_table": "data_center_financial_scope_capacity_consumption",
            },
        ),
    ]
