# Generated by Django 5.2.10 on 2026-03-03 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decision_rhythm", "0004_add_unified_recommendation_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executionapprovalrequestmodel",
            name="recommendation",
            field=models.ForeignKey(
                blank=True,
                help_text="关联的投资建议（legacy，unified 路径可为空）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_requests",
                to="decision_rhythm.investmentrecommendationmodel",
            ),
        ),
    ]
