# Generated by Django 5.2.10 on 2026-03-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decision_rhythm", "0005_make_recommendation_optional_in_approval"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="unifiedrecommendationmodel",
            index=models.Index(
                fields=["account_id", "status", "-composite_score"],
                name="idx_urec_acc_status_score",
            ),
        ),
    ]
