# Generated by Django 5.2.10 on 2026-03-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decision_rhythm", "0006_add_composite_index_for_recommendations"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionquotamodel",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, help_text="是否激活"),
        ),
    ]
