# Generated by Django 5.2.10 on 2026-03-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decision_rhythm", "0007_add_is_active_to_quota"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decisionquotamodel",
            name="is_active",
        ),
    ]
