# Generated by Django 5.2.10 on 2026-03-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decision_rhythm", "0008_remove_decisionquotamodel_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="decisionquotamodel",
            options={
                "ordering": ["account_id", "period"],
                "verbose_name": "决策配额",
                "verbose_name_plural": "决策配额",
            },
        ),
        migrations.RemoveIndex(
            model_name="decisionquotamodel",
            name="decision_qu_period_730e18_idx",
        ),
        migrations.AddField(
            model_name="decisionquotamodel",
            name="account_id",
            field=models.CharField(
                db_index=True,
                default="default",
                help_text="关联账户 ID，不同账户独立配额",
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="decisionquotamodel",
            index=models.Index(
                fields=["account_id", "period"], name="decision_qu_account_06614d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="decisionquotamodel",
            constraint=models.UniqueConstraint(
                fields=("account_id", "period"), name="uq_quota_account_period"
            ),
        ),
    ]
