# Generated by Django 5.2.10 on 2026-03-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decision_rhythm", "0009_add_account_id_to_quota"),
    ]

    operations = [
        migrations.AddField(
            model_name="unifiedrecommendationmodel",
            name="user_action",
            field=models.CharField(
                choices=[
                    ("PENDING", "待决策"),
                    ("WATCHING", "观察中"),
                    ("ADOPTED", "已采纳"),
                    ("IGNORED", "已忽略"),
                ],
                db_index=True,
                default="PENDING",
                help_text="用户决策动作",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="unifiedrecommendationmodel",
            name="user_action_at",
            field=models.DateTimeField(blank=True, help_text="用户动作时间", null=True),
        ),
        migrations.AddField(
            model_name="unifiedrecommendationmodel",
            name="user_action_note",
            field=models.TextField(blank=True, help_text="用户决策备注"),
        ),
        migrations.AddIndex(
            model_name="unifiedrecommendationmodel",
            index=models.Index(
                fields=["account_id", "user_action", "-created_at"],
                name="idx_urec_acc_uaction_time",
            ),
        ),
    ]
