# Generated by Django 5.2.9 on 2025-12-31 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_currencymodel_assetcategorymodel_exchangeratemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliomodel",
            name="base_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portfolios",
                to="account.currencymodel",
                verbose_name="基准货币",
            ),
        ),
        migrations.AddField(
            model_name="positionmodel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to="account.assetcategorymodel",
                verbose_name="资产分类",
            ),
        ),
        migrations.AddField(
            model_name="positionmodel",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="positions",
                to="account.currencymodel",
                verbose_name="币种",
            ),
        ),
    ]
