# Generated by Django 5.2.9 on 2026-01-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_stoplossconfigmodel_stoplosstriggermodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofilemodel",
            name="max_volatility_reduction",
            field=models.FloatField(
                default=0.5,
                help_text="波动率超标时最大降仓比例，如0.5表示最多降50%",
                verbose_name="最大降仓幅度",
            ),
        ),
        migrations.AddField(
            model_name="accountprofilemodel",
            name="target_volatility",
            field=models.FloatField(
                default=0.15, help_text="年化波动率目标，如0.15表示15%", verbose_name="目标波动率"
            ),
        ),
        migrations.AddField(
            model_name="accountprofilemodel",
            name="volatility_tolerance",
            field=models.FloatField(
                default=0.2,
                help_text="超过目标波动率多少比例触发降仓，如0.2表示20%",
                verbose_name="波动率容忍度",
            ),
        ),
    ]
