# Generated by Django 5.2.9 on 2026-01-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_accountprofilemodel_max_volatility_reduction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionmodel",
            name="cost_variance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="实际成本 - 预估成本",
                max_digits=10,
                null=True,
                verbose_name="成本差异",
            ),
        ),
        migrations.AddField(
            model_name="transactionmodel",
            name="cost_variance_pct",
            field=models.FloatField(blank=True, null=True, verbose_name="成本差异百分比"),
        ),
        migrations.AddField(
            model_name="transactionmodel",
            name="estimated_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="预估成本"
            ),
        ),
        migrations.AddField(
            model_name="transactionmodel",
            name="estimated_cost_ratio",
            field=models.FloatField(blank=True, null=True, verbose_name="预估成本比例"),
        ),
        migrations.AddField(
            model_name="transactionmodel",
            name="slippage",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="滑点成本"
            ),
        ),
        migrations.AddField(
            model_name="transactionmodel",
            name="stamp_duty",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="印花税"
            ),
        ),
        migrations.AddField(
            model_name="transactionmodel",
            name="transfer_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="过户费"
            ),
        ),
    ]
