# Generated by Django 5.2.9 on 2026-01-04 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_transactionmodel_cost_variance_and_more"),
        (
            "simulated_trading",
            "0002_rename_fee_config_asset_idx_simulated_f_asset_t_e1e211_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofilemodel",
            name="real_account",
            field=models.ForeignKey(
                blank=True,
                help_text="用户的实仓账户",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="real_profile_users",
                to="simulated_trading.simulatedaccountmodel",
                verbose_name="关联实仓",
            ),
        ),
        migrations.AddField(
            model_name="accountprofilemodel",
            name="simulated_account",
            field=models.ForeignKey(
                blank=True,
                help_text="用户的模拟仓账户",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="simulated_profile_users",
                to="simulated_trading.simulatedaccountmodel",
                verbose_name="关联模拟仓",
            ),
        ),
    ]
