# Generated by Django 5.2.9 on 2026-01-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_systemsettingsmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentrulemodel",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("regime_policy_combo", "Regime+Policy组合"),
                    ("match_position_combo", "匹配度+仓位组合"),
                    ("regime_position_combo", "Regime+仓位组合"),
                    ("regime_advice", "Regime环境建议"),
                    ("policy_advice", "Policy档位建议"),
                    ("position_advice", "仓位建议"),
                    ("match_advice", "Regime匹配度建议"),
                    ("signal_advice", "投资信号建议"),
                    ("risk_alert", "风险提示"),
                    ("static_advice", "静态建议"),
                ],
                max_length=30,
                verbose_name="规则类型",
            ),
        ),
    ]
