# Generated by Django 5.2.10 on 2026-03-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_add_trading_cost_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettingsmodel",
            name="qlib_enabled",
            field=models.BooleanField(
                default=False,
                help_text="开启后系统将使用 Qlib 进行量化分析",
                verbose_name="启用 Qlib",
            ),
        ),
        migrations.AddField(
            model_name="systemsettingsmodel",
            name="qlib_model_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Qlib 模型存储路径，留空使用默认路径",
                max_length=500,
                verbose_name="Qlib 模型目录",
            ),
        ),
        migrations.AddField(
            model_name="systemsettingsmodel",
            name="qlib_provider_uri",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Qlib 数据存储路径，如 D:/qlib_data/cn_data 或 /var/lib/qlib/cn_data",
                max_length=500,
                verbose_name="Qlib 数据目录",
            ),
        ),
        migrations.AddField(
            model_name="systemsettingsmodel",
            name="qlib_region",
            field=models.CharField(
                default="CN",
                help_text="市场区域，如 CN（中国）、US（美国）",
                max_length=10,
                verbose_name="Qlib 区域",
            ),
        ),
    ]
