# Generated by Django 5.2.10 on 2026-03-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_add_qlib_config_to_system_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettingsmodel",
            name="alpha_fixed_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "自动降级（默认）"),
                    ("qlib", "仅使用 Qlib"),
                    ("cache", "仅使用缓存"),
                    ("simple", "仅使用 Simple"),
                    ("etf", "仅使用 ETF"),
                ],
                default="",
                help_text="强制使用指定的 Provider（禁用自动降级），留空则启用自动降级",
                max_length=20,
                verbose_name="固定 Alpha Provider",
            ),
        ),
    ]
