# Generated by Django 5.2.12 on 2026-04-29 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0026_transactioncostconfigmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettingsmodel",
            name="macro_index_catalog",
        ),
    ]
