# Generated by Django 5.2.12 on 2026-07-24 17:49

from django.db import migrations, models


def ensure_transaction_cost_config_table(apps, schema_editor):
    """Create the repatriated cost-config table when legacy migrations removed it."""

    table_name = "transaction_cost_config"
    existing_tables = schema_editor.connection.introspection.table_names()
    if table_name in existing_tables:
        return

    model = apps.get_model("account", "TransactionCostConfigModel")
    schema_editor.create_model(model)


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0032_align_stop_loss_positive_pct_help_text"),
        ("shared", "0004_delete_assetconfigmodel_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="tradingcostconfigmodel",
                    name="min_commission",
                    field=models.FloatField(
                        help_text="单笔佣金不足此金额按此收取",
                        verbose_name="最低佣金（元）",
                    ),
                ),
                migrations.AlterField(
                    model_name="transactioncostconfigmodel",
                    name="min_commission",
                    field=models.DecimalField(
                        decimal_places=2,
                        help_text="单笔交易最低佣金（元）",
                        max_digits=10,
                        verbose_name="最低佣金",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            ensure_transaction_cost_config_table,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
