# Generated by Django 5.2.16 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("account", "0037_account_identity_snapshot_ledger")]

    operations = [
        migrations.CreateModel(
            name="AccountIdentityRawSourceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("source_id", models.CharField(max_length=192)),
                ("source_version", models.CharField(max_length=192)),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                ("underlying_unified_account_namespace", models.CharField(max_length=192)),
                ("underlying_unified_account_id", models.PositiveBigIntegerField()),
                ("owner_user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("assignment_state", models.CharField(max_length=32)),
                (
                    "assignment_evidence_owner",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "assignment_evidence_artifact_type",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("assignment_evidence_id", models.CharField(blank=True, max_length=192, null=True)),
                (
                    "assignment_evidence_version",
                    models.CharField(blank=True, max_length=192, null=True),
                ),
                (
                    "assignment_evidence_content_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("row_source_owner", models.CharField(max_length=32)),
                ("row_source_artifact_type", models.CharField(max_length=64)),
                ("row_source_id", models.CharField(max_length=192)),
                ("row_source_version", models.CharField(max_length=192)),
                ("row_source_content_hash", models.CharField(max_length=64)),
                ("observed_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("row_source_valid_until", models.DateTimeField()),
                ("ttl_valid_until", models.DateTimeField()),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("account_type", models.CharField(max_length=16)),
                ("is_active", models.BooleanField()),
                (
                    "supersedes_content_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "root_claim_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("blocker_codes", models.JSONField()),
                ("captured_actor_id", models.CharField(max_length=192)),
                ("captured_actor_user_id", models.PositiveBigIntegerField()),
                ("captured_actor_role", models.CharField(max_length=192)),
                ("captured_actor_kind", models.CharField(max_length=16)),
                ("captured_actor_is_staff", models.BooleanField()),
                ("canonical_payload", models.JSONField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("actor_binding_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "account_identity_raw_source_ledger",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["account_namespace", "account_id", "recorded_at"],
                        name="acct_raw_src_chain_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_id", "source_version"), name="acct_raw_src_identity_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("account_type", "real"),
                            ("artifact_type", "account_identity_raw_source"),
                            ("captured_actor_is_staff", True),
                            ("captured_actor_kind", "human"),
                            ("owner", "account"),
                            ("permission", "source_evidence_only"),
                            ("schema", "account-identity-raw-source.v1"),
                            ("status", "inactive"),
                        ),
                        name="acct_raw_src_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("observed_at__lte", models.F("recorded_at")),
                            ("persisted_at", models.F("recorded_at")),
                            ("recorded_at__lt", models.F("valid_until")),
                            ("valid_until__lte", models.F("row_source_valid_until")),
                            ("valid_until__lte", models.F("ttl_valid_until")),
                        ),
                        name="acct_raw_src_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("root_claim_hash__isnull", False),
                                ("supersedes_content_hash__isnull", True),
                            ),
                            models.Q(
                                ("root_claim_hash__isnull", True),
                                ("supersedes_content_hash__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="acct_raw_src_link_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "assignment_evidence_artifact_type",
                                    "account_owner_assignment_evidence",
                                ),
                                ("assignment_evidence_content_hash__isnull", False),
                                ("assignment_evidence_id__isnull", False),
                                ("assignment_evidence_owner", "account"),
                                ("assignment_evidence_version__isnull", False),
                                ("assignment_state", "authoritative"),
                                ("owner_user_id__isnull", False),
                            ),
                            models.Q(
                                (
                                    "assignment_evidence_artifact_type",
                                    "account_legacy_default_assignment_evidence",
                                ),
                                ("assignment_evidence_content_hash__isnull", False),
                                ("assignment_evidence_id__isnull", False),
                                ("assignment_evidence_owner", "account"),
                                ("assignment_evidence_version__isnull", False),
                                ("assignment_state", "legacy_default"),
                                ("owner_user_id__isnull", True),
                            ),
                            models.Q(
                                ("assignment_evidence_artifact_type__isnull", True),
                                ("assignment_evidence_content_hash__isnull", True),
                                ("assignment_evidence_id__isnull", True),
                                ("assignment_evidence_owner__isnull", True),
                                ("assignment_evidence_version__isnull", True),
                                ("assignment_state", "unknown"),
                                ("owner_user_id__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="acct_raw_src_assign_ck",
                    ),
                ],
            },
        )
    ]
