# Generated by Django 5.2.12 on 2026-08-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0039_account_owner_assignment_evidence_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysicalAccountRowObservationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("observation_id", models.CharField(max_length=192)),
                ("observation_version", models.CharField(max_length=192)),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                ("underlying_unified_account_namespace", models.CharField(max_length=192)),
                ("underlying_unified_account_id", models.PositiveBigIntegerField()),
                ("raw_source_owner", models.CharField(max_length=32)),
                ("raw_source_artifact_type", models.CharField(max_length=64)),
                ("raw_source_id", models.CharField(max_length=192)),
                ("raw_source_version", models.CharField(max_length=192)),
                ("raw_source_content_hash", models.CharField(max_length=64)),
                ("row_user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("account_type", models.CharField(max_length=192)),
                ("is_active", models.BooleanField()),
                ("row_created_at", models.DateTimeField()),
                ("row_updated_at", models.DateTimeField()),
                ("observed_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("raw_source_valid_until", models.DateTimeField()),
                ("ttl_valid_until", models.DateTimeField()),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("owner_assignment_state", models.CharField(max_length=32)),
                ("supersedes_content_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("root_claim_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("blocker_codes", models.JSONField()),
                ("captured_actor_id", models.CharField(max_length=192)),
                ("captured_actor_user_id", models.PositiveBigIntegerField()),
                ("captured_actor_role", models.CharField(max_length=192)),
                ("captured_actor_kind", models.CharField(max_length=16)),
                ("captured_actor_is_staff", models.BooleanField()),
                ("canonical_payload", models.JSONField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("raw_row_hash", models.CharField(max_length=64)),
                ("raw_source_binding_hash", models.CharField(max_length=64, unique=True)),
                ("actor_binding_hash", models.CharField(max_length=64, unique=True)),
                ("record_header_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "account_physical_row_observation_ledger",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["account_namespace", "account_id", "raw_source_id", "recorded_at"],
                        name="acct_phys_row_chain_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("observation_id", "observation_version"),
                        name="acct_phys_row_obs_id_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("raw_source_id", "raw_source_version"),
                        name="acct_phys_row_src_id_uq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("root_claim_hash__isnull", False)),
                        fields=("root_claim_hash",),
                        name="acct_phys_row_root_uq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("supersedes_content_hash__isnull", False)),
                        fields=("supersedes_content_hash",),
                        name="acct_phys_row_next_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("artifact_type", "physical_account_row_observation"),
                            ("captured_actor_is_staff", True),
                            ("captured_actor_kind", "human"),
                            ("owner", "account"),
                            ("owner_assignment_state", "unknown"),
                            ("permission", "evidence_only"),
                            ("raw_source_artifact_type", "simulated_account_row"),
                            ("raw_source_owner", "simulated_trading"),
                            ("schema", "physical-account-row-observation.v1"),
                            ("status", "inactive"),
                        ),
                        name="acct_phys_row_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("observed_at__lte", models.F("recorded_at")),
                            ("persisted_at", models.F("recorded_at")),
                            ("recorded_at__lt", models.F("valid_until")),
                            ("row_created_at__lte", models.F("row_updated_at")),
                            ("row_updated_at__lte", models.F("observed_at")),
                            ("valid_until__lte", models.F("raw_source_valid_until")),
                            ("valid_until__lte", models.F("ttl_valid_until")),
                        ),
                        name="acct_phys_row_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("root_claim_hash__isnull", False),
                                ("supersedes_content_hash__isnull", True),
                            ),
                            models.Q(
                                ("root_claim_hash__isnull", True),
                                ("supersedes_content_hash__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="acct_phys_row_link_ck",
                    ),
                ],
            },
        ),
    ]
