# Generated by Django 5.2.16 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0040_physical_account_row_observation_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountOwnerAssignmentProvenanceReceiptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("receipt_id", models.CharField(max_length=192)),
                ("receipt_version", models.CharField(max_length=192)),
                ("provenance_kind", models.CharField(max_length=32)),
                ("assignment_state", models.CharField(max_length=32)),
                (
                    "assigned_owner_user_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                (
                    "underlying_unified_account_namespace",
                    models.CharField(max_length=192),
                ),
                ("underlying_unified_account_id", models.PositiveBigIntegerField()),
                ("row_observation_owner", models.CharField(max_length=32)),
                ("row_observation_artifact_type", models.CharField(max_length=64)),
                ("row_observation_id", models.CharField(max_length=192)),
                ("row_observation_version", models.CharField(max_length=192)),
                ("row_observation_identity_hash", models.CharField(max_length=64)),
                ("row_observation_content_hash", models.CharField(max_length=64)),
                ("row_observation_valid_until", models.DateTimeField()),
                ("claimant_actor_id", models.CharField(max_length=192)),
                ("claimant_user_id", models.PositiveBigIntegerField()),
                ("claimant_role", models.CharField(max_length=192)),
                ("claimant_kind", models.CharField(max_length=16)),
                ("claimant_is_staff", models.BooleanField()),
                ("issued_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                (
                    "supersedes_content_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "root_claim_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("blocker_codes", models.JSONField()),
                ("issuer_actor_id", models.CharField(max_length=192)),
                ("issuer_user_id", models.PositiveBigIntegerField()),
                ("issuer_role", models.CharField(max_length=192)),
                ("issuer_kind", models.CharField(max_length=16)),
                ("issuer_is_staff", models.BooleanField()),
                ("canonical_payload", models.JSONField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("row_binding_hash", models.CharField(max_length=64)),
                ("issuer_binding_hash", models.CharField(max_length=64, unique=True)),
                ("record_header_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "account_owner_assignment_provenance_receipt_ledger",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["receipt_id", "recorded_at"],
                        name="acct_prov_receipt_chain_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("receipt_id", "receipt_version"),
                        name="acct_prov_receipt_id_uq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("root_claim_hash__isnull", False)),
                        fields=("root_claim_hash",),
                        name="acct_prov_receipt_root_uq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("supersedes_content_hash__isnull", False)),
                        fields=("supersedes_content_hash",),
                        name="acct_prov_receipt_next_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("claimant_kind", "human"),
                            ("issuer_kind", "human"),
                            ("owner", "account"),
                            ("permission", "evidence_only"),
                            (
                                "schema",
                                "account-owner-assignment-provenance-receipt.v1",
                            ),
                            ("status", "inactive"),
                        ),
                        name="acct_prov_receipt_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("issued_at__lte", models.F("recorded_at")),
                            ("persisted_at", models.F("recorded_at")),
                            ("recorded_at__lt", models.F("valid_until")),
                            (
                                "valid_until__lte",
                                models.F("row_observation_valid_until"),
                            ),
                        ),
                        name="acct_prov_receipt_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("root_claim_hash__isnull", False),
                                ("supersedes_content_hash__isnull", True),
                            ),
                            models.Q(
                                ("root_claim_hash__isnull", True),
                                ("supersedes_content_hash__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="acct_prov_receipt_link_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("claimant_actor_id", models.F("issuer_actor_id")),
                            ("claimant_is_staff", models.F("issuer_is_staff")),
                            ("claimant_kind", models.F("issuer_kind")),
                            ("claimant_role", models.F("issuer_role")),
                            ("claimant_user_id", models.F("issuer_user_id")),
                        ),
                        name="acct_prov_receipt_actor_ck",
                    ),
                ],
            },
        )
    ]
