# Generated by Django 5.2.16 on 2026-08-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0041_account_owner_assignment_provenance_receipt_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysicalAccountRowObservationV2Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("observation_id", models.CharField(max_length=192)),
                ("observation_version", models.CharField(max_length=192)),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                ("underlying_unified_account_namespace", models.CharField(max_length=192)),
                ("underlying_unified_account_id", models.PositiveBigIntegerField()),
                ("row_user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("raw_account_type", models.CharField(max_length=192)),
                ("is_active", models.BooleanField()),
                ("row_created_at", models.DateTimeField()),
                ("row_updated_at", models.DateTimeField()),
                ("is_present", models.BooleanField()),
                ("is_tombstone", models.BooleanField()),
                ("source_owner", models.CharField(max_length=32)),
                ("source_artifact_type", models.CharField(max_length=64)),
                ("source_schema", models.CharField(max_length=64)),
                ("source_id", models.CharField(max_length=192)),
                ("source_version", models.CharField(max_length=192)),
                ("source_identity_hash", models.CharField(max_length=64)),
                ("source_content_hash", models.CharField(max_length=64)),
                (
                    "source_supersedes_content_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("source_observed_at", models.DateTimeField()),
                ("source_recorded_at", models.DateTimeField()),
                ("source_valid_until", models.DateTimeField()),
                ("source_ttl_valid_until", models.DateTimeField()),
                ("source_effective_valid_until", models.DateTimeField()),
                ("raw_observation_owner", models.CharField(max_length=32)),
                ("raw_observation_artifact_type", models.CharField(max_length=64)),
                ("raw_observation_schema", models.CharField(max_length=64)),
                ("raw_observation_id", models.CharField(max_length=192)),
                ("raw_observation_version", models.CharField(max_length=192)),
                ("raw_observation_identity_hash", models.CharField(max_length=64)),
                ("raw_observation_content_hash", models.CharField(max_length=64)),
                (
                    "raw_observation_supersedes_content_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("raw_observation_observed_at", models.DateTimeField()),
                ("raw_observation_valid_until", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("ttl_valid_until", models.DateTimeField()),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("owner_assignment_state", models.CharField(max_length=32)),
                ("supersedes_content_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("root_claim_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("captured_actor_id", models.CharField(max_length=192)),
                ("captured_actor_user_id", models.PositiveBigIntegerField()),
                ("captured_actor_role", models.CharField(max_length=192)),
                ("captured_actor_kind", models.CharField(max_length=16)),
                ("captured_actor_is_staff", models.BooleanField()),
                ("canonical_payload", models.JSONField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("raw_binding_seal", models.CharField(max_length=64)),
                ("source_binding_seal", models.CharField(max_length=64)),
                ("row_seal", models.CharField(max_length=64)),
                ("clock_seal", models.CharField(max_length=64)),
                ("actor_binding_seal", models.CharField(max_length=64)),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "account_physical_row_observation_v2_ledger",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["account_namespace", "account_id", "source_id", "recorded_at"],
                        name="acct_phys_v2_chain_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("observation_id", "observation_version"), name="acct_phys_v2_obs_uq"
                    ),
                    models.UniqueConstraint(
                        fields=("source_id", "source_version"), name="acct_phys_v2_src_uq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("root_claim_hash__isnull", False)),
                        fields=("root_claim_hash",),
                        name="acct_phys_v2_root_uq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("supersedes_content_hash__isnull", False)),
                        fields=("supersedes_content_hash",),
                        name="acct_phys_v2_next_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("artifact_type", "physical_account_row_observation_v2"),
                            ("captured_actor_is_staff", True),
                            ("captured_actor_kind", "human"),
                            ("owner", "account"),
                            ("owner_assignment_state", "unknown"),
                            ("permission", "evidence_only"),
                            ("raw_observation_artifact_type", "simulated_account_raw_observation"),
                            ("raw_observation_owner", "simulated_trading"),
                            ("raw_observation_schema", "simulated-account-raw-observation.v1"),
                            ("schema", "physical-account-row-observation.v2"),
                            ("source_artifact_type", "simulated_account_row_v2"),
                            ("source_owner", "simulated_trading"),
                            ("source_schema", "simulated-account-row.v2"),
                            ("status", "inactive"),
                        ),
                        name="acct_phys_v2_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("persisted_at", models.F("recorded_at")),
                            ("recorded_at__lt", models.F("valid_until")),
                            ("row_created_at__lte", models.F("row_updated_at")),
                            ("row_updated_at__lte", models.F("source_observed_at")),
                            ("source_observed_at", models.F("raw_observation_observed_at")),
                            ("source_recorded_at__lte", models.F("recorded_at")),
                            ("source_valid_until", models.F("raw_observation_valid_until")),
                            ("valid_until__lte", models.F("source_effective_valid_until")),
                            ("valid_until__lte", models.F("ttl_valid_until")),
                        ),
                        name="acct_phys_v2_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_id", models.F("raw_observation_id")),
                            ("source_version", models.F("raw_observation_version")),
                        ),
                        name="acct_phys_v2_raw_id_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("is_present", True), ("is_tombstone", False)),
                            models.Q(("is_present", False), ("is_tombstone", True)),
                            _connector="OR",
                        ),
                        name="acct_phys_v2_presence_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("raw_observation_supersedes_content_hash__isnull", True),
                                ("root_claim_hash__isnull", False),
                                ("source_supersedes_content_hash__isnull", True),
                                ("supersedes_content_hash__isnull", True),
                            ),
                            models.Q(
                                ("raw_observation_supersedes_content_hash__isnull", False),
                                ("root_claim_hash__isnull", True),
                                ("source_supersedes_content_hash__isnull", False),
                                ("supersedes_content_hash__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="acct_phys_v2_link_ck",
                    ),
                ],
            },
        ),
    ]
