# Generated by Django 5.2.16 on 2026-08-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("account", "0043_account_owner_assignment_provenance_receipt_v2_ledger")]

    operations = [
        migrations.CreateModel(
            name="AccountOwnerAssignmentSubjectV2Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("subject_id", models.CharField(max_length=192)),
                ("subject_version", models.CharField(max_length=192)),
                ("physical_observation_id", models.CharField(max_length=192)),
                ("physical_observation_version", models.CharField(max_length=192)),
                ("physical_identity_hash", models.CharField(max_length=64)),
                ("physical_content_hash", models.CharField(max_length=64)),
                ("receipt_id", models.CharField(max_length=192)),
                ("receipt_version", models.CharField(max_length=192)),
                ("receipt_identity_hash", models.CharField(max_length=64)),
                ("receipt_content_hash", models.CharField(max_length=64)),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                ("underlying_unified_account_namespace", models.CharField(max_length=192)),
                ("underlying_unified_account_id", models.PositiveBigIntegerField()),
                ("requested_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("canonical_payload", models.JSONField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("upstream_binding_seal", models.CharField(max_length=64)),
                ("fixed_authority_seal", models.CharField(max_length=64)),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "account_owner_assignment_subject_v2_ledger",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["subject_id", "requested_at"], name="acct_own_v2_sub_chain_ix"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subject_id", "subject_version"), name="acct_own_v2_sub_id_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("artifact_type", "account_owner_assignment_subject_v2"),
                            ("owner", "account"),
                            ("permission", "evidence_only"),
                            ("schema", "account-owner-assignment-subject.v2"),
                            ("status", "inactive"),
                        ),
                        name="acct_own_v2_sub_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("persisted_at", models.F("requested_at")),
                            ("requested_at__lt", models.F("valid_until")),
                        ),
                        name="acct_own_v2_sub_clock_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccountOwnerAssignmentEvidenceV2Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("subject_content_hash", models.CharField(max_length=64, unique=True)),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("evidence_id", models.CharField(max_length=192)),
                ("evidence_version", models.CharField(max_length=192)),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                ("underlying_unified_account_namespace", models.CharField(max_length=192)),
                ("underlying_unified_account_id", models.PositiveBigIntegerField()),
                ("assignment_state", models.CharField(max_length=32)),
                ("assigned_owner_user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("approved_actor_id", models.CharField(max_length=192)),
                ("approved_user_id", models.PositiveBigIntegerField()),
                ("approved_role", models.CharField(max_length=192)),
                ("approved_kind", models.CharField(max_length=16)),
                ("approved_is_staff", models.BooleanField()),
                ("approved_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("approval_valid_until", models.DateTimeField()),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("supersedes_content_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("account_root_claim_hash", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "underlying_root_claim_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("blocker_codes", models.JSONField()),
                ("canonical_payload", models.JSONField()),
                ("subject_binding_seal", models.CharField(max_length=64)),
                ("approver_binding_seal", models.CharField(max_length=64)),
                ("mapping_binding_seal", models.CharField(max_length=64)),
                ("fixed_authority_seal", models.CharField(max_length=64)),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField()),
                (
                    "subject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_evidence",
                        to="account.accountownerassignmentsubjectv2model",
                    ),
                ),
            ],
            options={
                "db_table": "account_owner_assignment_evidence_v2_ledger",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["evidence_id", "recorded_at"], name="acct_own_v2_ev_chain_ix"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("evidence_id", "evidence_version"), name="acct_own_v2_ev_id_uq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("account_root_claim_hash__isnull", False)),
                        fields=("account_root_claim_hash",),
                        name="acct_own_v2_acct_root_uq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("underlying_root_claim_hash__isnull", False)),
                        fields=("underlying_root_claim_hash",),
                        name="acct_own_v2_under_root_uq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("supersedes_content_hash__isnull", False)),
                        fields=("supersedes_content_hash",),
                        name="acct_own_v2_next_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("approved_is_staff", True),
                            ("approved_kind", "human"),
                            ("approved_role", "account_owner_assignment_approver"),
                            ("artifact_type", "account_owner_assignment_evidence_v2"),
                            ("owner", "account"),
                            ("permission", "evidence_only"),
                            ("schema", "account-owner-assignment-evidence.v2"),
                            ("status", "inactive"),
                        ),
                        name="acct_own_v2_ev_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("approved_at__lte", models.F("recorded_at")),
                            ("persisted_at", models.F("recorded_at")),
                            ("recorded_at__lt", models.F("approval_valid_until")),
                            ("valid_until__lte", models.F("approval_valid_until")),
                        ),
                        name="acct_own_v2_ev_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("account_root_claim_hash__isnull", False),
                                ("supersedes_content_hash__isnull", True),
                                ("underlying_root_claim_hash__isnull", False),
                            ),
                            models.Q(
                                ("account_root_claim_hash__isnull", True),
                                ("supersedes_content_hash__isnull", False),
                                ("underlying_root_claim_hash__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="acct_own_v2_link_ck",
                    ),
                ],
            },
        ),
    ]
