# Generated by Django 5.2.16 on 2026-08-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("account", "0045_canonical_account_creation_ledger")]

    operations = [
        migrations.CreateModel(
            name="AllocatedPhysicalAccountRowObservationV3Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("observation_id", models.CharField(max_length=192)),
                ("observation_version", models.CharField(max_length=192)),
                ("allocation_id", models.CharField(max_length=192)),
                ("allocation_version", models.CharField(max_length=192)),
                (
                    "allocation_identity_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "allocation_content_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                (
                    "underlying_unified_account_namespace",
                    models.CharField(max_length=192),
                ),
                (
                    "underlying_unified_account_id",
                    models.PositiveBigIntegerField(),
                ),
                ("physical_observation_id", models.CharField(max_length=192)),
                (
                    "physical_observation_version",
                    models.CharField(max_length=192),
                ),
                (
                    "physical_identity_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "physical_content_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("ttl_valid_until", models.DateTimeField()),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("identity_anchor_kind", models.CharField(max_length=32)),
                ("owner_assignment_state", models.CharField(max_length=32)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("recorded_by_service_id", models.CharField(max_length=192)),
                ("recorded_by_role", models.CharField(max_length=192)),
                ("recorded_by_kind", models.CharField(max_length=16)),
                ("recorded_by_is_automated", models.BooleanField()),
                ("canonical_payload", models.JSONField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                (
                    "identity_claim_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "allocation_claim_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "account_claim_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "underlying_claim_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "physical_claim_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                ("root_claim_hash", models.CharField(max_length=64, unique=True)),
                ("allocation_binding_seal", models.CharField(max_length=64)),
                ("physical_binding_seal", models.CharField(max_length=64)),
                ("projector_binding_seal", models.CharField(max_length=64)),
                ("fixed_authority_seal", models.CharField(max_length=64)),
                ("clock_seal", models.CharField(max_length=64)),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "account_allocated_physical_row_observation_v3_ledger",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=[
                            "allocation_content_hash",
                            "account_namespace",
                            "account_id",
                            "recorded_at",
                        ],
                        name="acct_apv3_head_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("observation_id", "observation_version"),
                        name="acct_apv3_obs_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("allocation_id", "allocation_version"),
                        name="acct_apv3_alloc_id_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("account_namespace", "account_id"),
                        name="acct_apv3_account_uq",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "underlying_unified_account_namespace",
                            "underlying_unified_account_id",
                        ),
                        name="acct_apv3_under_uq",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "physical_observation_id",
                            "physical_observation_version",
                        ),
                        name="acct_apv3_phys_id_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            owner="account",
                            artifact_type=("allocated_physical_account_row_observation_v3"),
                            schema=("allocated-physical-account-row-observation.v3"),
                            account_namespace="account",
                            identity_anchor_kind="creation_allocation",
                            owner_assignment_state="unknown",
                            permission="evidence_only",
                            status="inactive",
                            recorded_by_role=("allocated_physical_creation_projector"),
                            recorded_by_kind="service",
                            recorded_by_is_automated=True,
                        ),
                        name="acct_apv3_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(recorded_at__lt=models.F("ttl_valid_until"))
                            & models.Q(recorded_at__lt=models.F("valid_until"))
                            & models.Q(valid_until__lte=models.F("ttl_valid_until"))
                            & models.Q(persisted_at=models.F("recorded_at"))
                        ),
                        name="acct_apv3_clock_ck",
                    ),
                ],
            },
        )
    ]
