# Generated by Django 5.2.10 on 2026-08-13 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0046_allocated_physical_account_row_observation_v3_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalAccountCreationConsumptionClaimModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("claim_id", models.CharField(max_length=192)),
                ("claim_version", models.CharField(max_length=192)),
                (
                    "allocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creation_consumption_claim",
                        to="account.canonicalaccountcreationallocationmodel",
                    ),
                ),
                (
                    "allocation_identity_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "allocation_content_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                ("consumer_generation", models.CharField(max_length=16)),
                ("consumer_owner", models.CharField(max_length=32)),
                ("consumer_artifact_type", models.CharField(max_length=64)),
                ("consumer_schema", models.CharField(max_length=64)),
                ("consumer_id", models.CharField(max_length=192)),
                ("consumer_version", models.CharField(max_length=192)),
                (
                    "consumer_identity_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "consumer_content_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                (
                    "underlying_unified_account_namespace",
                    models.CharField(max_length=192),
                ),
                ("underlying_unified_account_id", models.PositiveBigIntegerField()),
                (
                    "physical_v2_content_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "physical_v3_root_content_hash",
                    models.CharField(max_length=64, null=True),
                ),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("canonical_payload", models.JSONField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("allocation_binding_seal", models.CharField(max_length=64)),
                ("consumer_binding_seal", models.CharField(max_length=64)),
                ("fixed_authority_seal", models.CharField(max_length=64)),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "canonical_account_creation_consumption_claim_ledger",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("claim_id", "claim_version"),
                        name="acct_create_cons_claim_uq",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "consumer_owner",
                            "consumer_artifact_type",
                            "consumer_id",
                            "consumer_version",
                        ),
                        name="acct_create_cons_ref_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("account_namespace", "account_id"),
                        name="acct_create_cons_acct_uq",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "underlying_unified_account_namespace",
                            "underlying_unified_account_id",
                        ),
                        name="acct_create_cons_under_uq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("physical_v3_root_content_hash__isnull", False)),
                        fields=("physical_v3_root_content_hash",),
                        name="acct_create_cons_root_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("account_namespace", "account"),
                            ("artifact_type", "canonical_account_creation_consumption_claim"),
                            ("consumer_owner", "account"),
                            ("owner", "account"),
                            ("permission", "evidence_only"),
                            ("schema", "canonical-account-creation-consumption-claim.v1"),
                            ("status", "inactive"),
                            (
                                "underlying_unified_account_namespace",
                                "simulated-account-row",
                            ),
                        ),
                        name="acct_create_cons_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                (
                                    "consumer_artifact_type",
                                    "canonical_account_creation_binding",
                                ),
                                ("consumer_generation", "v1"),
                                (
                                    "consumer_schema",
                                    "canonical-account-creation-binding.v1",
                                ),
                                ("physical_v3_root_content_hash__isnull", True),
                            ),
                            models.Q(
                                (
                                    "consumer_artifact_type",
                                    "canonical_account_creation_binding_v2",
                                ),
                                ("consumer_generation", "v2"),
                                (
                                    "consumer_schema",
                                    "canonical-account-creation-binding.v2",
                                ),
                                ("physical_v3_root_content_hash__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="acct_create_cons_branch_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("persisted_at", models.F("recorded_at"))),
                        name="acct_create_cons_clock_ck",
                    ),
                ],
                "indexes": [],
            },
        ),
        migrations.CreateModel(
            name="CanonicalAccountCreationBindingV2Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consumption_claim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creation_binding_v2",
                        to="account.canonicalaccountcreationconsumptionclaimmodel",
                    ),
                ),
                (
                    "consumption_claim_content_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creation_bindings_v2",
                        to="account.canonicalaccountcreationallocationmodel",
                    ),
                ),
                (
                    "allocation_identity_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "allocation_content_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "creation_root",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creation_binding_v2",
                        to="account.allocatedphysicalaccountrowobservationv3model",
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("binding_id", models.CharField(max_length=192)),
                ("binding_version", models.CharField(max_length=192)),
                ("creation_root_observation_id", models.CharField(max_length=192)),
                (
                    "creation_root_observation_version",
                    models.CharField(max_length=192),
                ),
                (
                    "creation_root_identity_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "creation_root_content_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "physical_observation_content_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "physical_source_content_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "physical_raw_observation_content_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                ("account_namespace_claim", models.CharField(max_length=192)),
                ("account_id_claim", models.CharField(max_length=192)),
                (
                    "underlying_unified_account_namespace_claim",
                    models.CharField(max_length=192),
                ),
                (
                    "underlying_unified_account_id_claim",
                    models.PositiveBigIntegerField(),
                ),
                ("recorded_service_id", models.CharField(max_length=192)),
                ("recorded_role", models.CharField(max_length=192)),
                ("recorded_kind", models.CharField(max_length=16)),
                ("recorded_is_automated", models.BooleanField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("account_claim_hash", models.CharField(max_length=64, unique=True)),
                (
                    "underlying_claim_hash",
                    models.CharField(max_length=64, unique=True),
                ),
                ("permission", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=16)),
                ("binding_state", models.CharField(max_length=32)),
                ("owner_assignment_state", models.CharField(max_length=32)),
                ("canonical_payload", models.JSONField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("consumption_claim_binding_seal", models.CharField(max_length=64)),
                ("allocation_binding_seal", models.CharField(max_length=64)),
                ("creation_root_binding_seal", models.CharField(max_length=64)),
                ("physical_binding_seal", models.CharField(max_length=64)),
                ("recorder_binding_seal", models.CharField(max_length=64)),
                ("fixed_authority_seal", models.CharField(max_length=64)),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "canonical_account_creation_binding_v2_ledger",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("binding_id", "binding_version"),
                        name="acct_create_bind_v2_id_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("account_namespace_claim", "account_id_claim"),
                        name="acct_create_bind_v2_acct_uq",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "underlying_unified_account_namespace_claim",
                            "underlying_unified_account_id_claim",
                        ),
                        name="acct_create_bind_v2_under_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("account_namespace_claim", "account"),
                            (
                                "artifact_type",
                                "canonical_account_creation_binding_v2",
                            ),
                            ("binding_state", "bound_pending_owner_approval"),
                            ("owner", "account"),
                            ("owner_assignment_state", "unknown"),
                            ("permission", "identity_binding_evidence_only"),
                            ("recorded_is_automated", True),
                            ("recorded_kind", "service"),
                            ("recorded_role", "canonical_account_creation_binder"),
                            ("schema", "canonical-account-creation-binding.v2"),
                            ("status", "inactive"),
                            (
                                "underlying_unified_account_namespace_claim",
                                "simulated-account-row",
                            ),
                        ),
                        name="acct_create_bind_v2_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("persisted_at", models.F("recorded_at"))),
                        name="acct_create_bind_v2_clock_ck",
                    ),
                ],
                "indexes": [],
            },
        ),
        migrations.AddField(
            model_name="canonicalaccountcreationbindingmodel",
            name="consumption_claim",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="creation_binding_v1",
                to="account.canonicalaccountcreationconsumptionclaimmodel",
            ),
        ),
    ]
