# Generated by Django 5.2.10 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0047_canonical_account_creation_consumption_expand"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalaccountcreationconsumptionclaimmodel",
            name="knowledge_at",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
