# Generated by Django 5.2.16 on 2026-08-13 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0048_canonical_account_creation_consumption_knowledge_clock_expand"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountOwnerAssignmentProvenanceReceiptV3Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("provenance_kind", models.CharField(max_length=32)),
                ("assignment_state", models.CharField(max_length=32)),
                ("assigned_owner_user_id", models.PositiveBigIntegerField()),
                ("receipt_id", models.CharField(max_length=192)),
                ("receipt_version", models.CharField(max_length=192)),
                ("binding_ref_id", models.CharField(max_length=192)),
                ("binding_ref_version", models.CharField(max_length=192)),
                ("binding_identity_hash", models.CharField(max_length=64)),
                ("binding_content_hash", models.CharField(max_length=64)),
                ("binding_recorded_at", models.DateTimeField()),
                ("allocation_identity_hash", models.CharField(max_length=64)),
                ("creation_root_content_hash", models.CharField(max_length=64)),
                ("creation_root_identity_hash", models.CharField(max_length=64)),
                ("creation_root_recorded_at", models.DateTimeField()),
                ("creation_root_valid_until", models.DateTimeField()),
                ("allocation_content_hash", models.CharField(max_length=64)),
                ("account_claim_hash", models.CharField(max_length=64)),
                ("underlying_claim_hash", models.CharField(max_length=64)),
                ("physical_observation_content_hash", models.CharField(max_length=64)),
                ("physical_source_content_hash", models.CharField(max_length=64)),
                ("physical_raw_observation_content_hash", models.CharField(max_length=64)),
                ("physical_row_user_id", models.PositiveBigIntegerField()),
                ("claimant_user_id", models.PositiveBigIntegerField()),
                ("claimant_actor_id", models.CharField(max_length=192)),
                ("claimant_role", models.CharField(max_length=192)),
                ("claimant_kind", models.CharField(max_length=16)),
                ("claimant_is_staff", models.BooleanField()),
                ("issuer_actor_id", models.CharField(max_length=192)),
                ("issuer_user_id", models.PositiveBigIntegerField()),
                ("issuer_role", models.CharField(max_length=192)),
                ("issuer_kind", models.CharField(max_length=16)),
                ("issuer_is_staff", models.BooleanField()),
                ("issued_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField()),
                ("supersedes_content_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("blocker_codes", models.JSONField()),
                ("canonical_payload", models.JSONField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("binding_seal", models.CharField(max_length=64)),
                ("claimant_seal", models.CharField(max_length=64)),
                ("actor_binding_seal", models.CharField(max_length=64)),
                ("chain_seal", models.CharField(max_length=64)),
                ("fixed_authority_seal", models.CharField(max_length=64)),
                ("header_seal", models.CharField(max_length=64)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                (
                    "root_claim_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("persisted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "account_owner_assignment_provenance_receipt_v3_ledger",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AddField(
            model_name="accountownerassignmentprovenancereceiptv3model",
            name="binding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner_claim_receipts_v3",
                to="account.canonicalaccountcreationbindingv2model",
            ),
        ),
        migrations.AddField(
            model_name="accountownerassignmentprovenancereceiptv3model",
            name="predecessor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="successor",
                to="account.accountownerassignmentprovenancereceiptv3model",
            ),
        ),
        migrations.AddIndex(
            model_name="accountownerassignmentprovenancereceiptv3model",
            index=models.Index(fields=["receipt_id", "recorded_at"], name="acct_prov_v3_chain_ix"),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentprovenancereceiptv3model",
            constraint=models.UniqueConstraint(
                fields=("receipt_id", "receipt_version"), name="acct_prov_v3_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentprovenancereceiptv3model",
            constraint=models.UniqueConstraint(
                condition=models.Q(("predecessor__isnull", True)),
                fields=("receipt_id",),
                name="acct_prov_v3_root_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentprovenancereceiptv3model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("artifact_type", "account_owner_assignment_provenance_receipt_v3"),
                    ("assignment_state", "claimed_owner"),
                    ("claimant_is_staff", False),
                    ("claimant_kind", "human"),
                    ("issuer_is_staff", False),
                    ("issuer_kind", "human"),
                    ("owner", "account"),
                    ("permission", "claim_evidence_only"),
                    ("provenance_kind", "creation"),
                    ("schema", "account-owner-assignment-provenance-receipt.v3"),
                    ("status", "inactive"),
                ),
                name="acct_prov_v3_fixed_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentprovenancereceiptv3model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("binding_recorded_at__lte", models.F("issued_at")),
                    ("creation_root_recorded_at__lte", models.F("binding_recorded_at")),
                    ("issued_at__lte", models.F("recorded_at")),
                    ("persisted_at", models.F("recorded_at")),
                    ("recorded_at__lt", models.F("valid_until")),
                    ("valid_until__lte", models.F("creation_root_valid_until")),
                ),
                name="acct_prov_v3_clock_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentprovenancereceiptv3model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("assigned_owner_user_id", models.F("claimant_user_id")),
                    ("claimant_user_id", models.F("physical_row_user_id")),
                    ("claimant_actor_id", models.F("issuer_actor_id")),
                    ("claimant_user_id", models.F("issuer_user_id")),
                    ("claimant_role", models.F("issuer_role")),
                    ("claimant_kind", models.F("issuer_kind")),
                    ("claimant_is_staff", models.F("issuer_is_staff")),
                ),
                name="acct_prov_v3_actor_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentprovenancereceiptv3model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("predecessor__isnull", True),
                        ("root_claim_hash__isnull", False),
                        ("supersedes_content_hash__isnull", True),
                    ),
                    models.Q(
                        ("predecessor__isnull", False),
                        ("root_claim_hash__isnull", True),
                        ("supersedes_content_hash__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="acct_prov_v3_link_ck",
            ),
        ),
    ]
