# Generated by Django 5.2.16 on 2026-08-13 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0049_account_owner_assignment_provenance_receipt_v3_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountOwnerAssignmentEvidenceV3Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("subject_content_hash", models.CharField(max_length=64, unique=True)),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("evidence_id", models.CharField(max_length=192)),
                ("evidence_version", models.CharField(max_length=192)),
                ("assignment_state", models.CharField(max_length=32)),
                ("assigned_owner_user_id", models.PositiveBigIntegerField()),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                ("underlying_unified_account_namespace", models.CharField(max_length=192)),
                ("underlying_unified_account_id", models.PositiveBigIntegerField()),
                ("claimant_actor_id", models.CharField(max_length=192)),
                ("claimant_user_id", models.PositiveBigIntegerField()),
                ("approved_actor_id", models.CharField(max_length=192)),
                ("approved_user_id", models.PositiveBigIntegerField()),
                ("approved_role", models.CharField(max_length=192)),
                ("approved_kind", models.CharField(max_length=16)),
                ("approved_is_staff", models.BooleanField()),
                ("subject_requested_at", models.DateTimeField()),
                ("subject_valid_until", models.DateTimeField()),
                ("approved_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("approval_valid_until", models.DateTimeField()),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("account_root_claim_hash", models.CharField(max_length=64, unique=True)),
                ("underlying_root_claim_hash", models.CharField(max_length=64, unique=True)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("blocker_codes", models.JSONField()),
                ("canonical_payload", models.JSONField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("subject_binding_seal", models.CharField(max_length=64)),
                ("approver_binding_seal", models.CharField(max_length=64)),
                ("mapping_binding_seal", models.CharField(max_length=64)),
                ("fixed_authority_seal", models.CharField(max_length=64)),
                ("header_seal", models.CharField(max_length=64)),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "account_owner_assignment_evidence_v3_ledger",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="AccountOwnerAssignmentSubjectV3Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("subject_id", models.CharField(max_length=192)),
                ("subject_version", models.CharField(max_length=192)),
                ("receipt_ref_id", models.CharField(max_length=192)),
                ("receipt_ref_version", models.CharField(max_length=192)),
                ("binding_ref_id", models.CharField(max_length=192)),
                ("binding_ref_version", models.CharField(max_length=192)),
                ("creation_root_ref_id", models.CharField(max_length=192)),
                ("creation_root_ref_version", models.CharField(max_length=192)),
                ("receipt_identity_hash", models.CharField(max_length=64)),
                ("receipt_content_hash", models.CharField(max_length=64)),
                ("binding_identity_hash", models.CharField(max_length=64)),
                ("binding_content_hash", models.CharField(max_length=64)),
                ("creation_root_identity_hash", models.CharField(max_length=64)),
                ("creation_root_content_hash", models.CharField(max_length=64)),
                ("binding_account_claim_hash", models.CharField(max_length=64)),
                ("binding_underlying_claim_hash", models.CharField(max_length=64)),
                ("physical_observation_content_hash", models.CharField(max_length=64)),
                ("physical_source_content_hash", models.CharField(max_length=64)),
                ("physical_raw_observation_content_hash", models.CharField(max_length=64)),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                ("underlying_unified_account_namespace", models.CharField(max_length=192)),
                ("underlying_unified_account_id", models.PositiveBigIntegerField()),
                ("assigned_owner_user_id", models.PositiveBigIntegerField()),
                ("physical_row_user_id", models.PositiveBigIntegerField()),
                ("claimant_actor_id", models.CharField(max_length=192)),
                ("claimant_user_id", models.PositiveBigIntegerField()),
                ("claimant_role", models.CharField(max_length=192)),
                ("claimant_kind", models.CharField(max_length=16)),
                ("claimant_is_staff", models.BooleanField()),
                ("receipt_recorded_at", models.DateTimeField()),
                ("receipt_valid_until", models.DateTimeField()),
                ("creation_root_recorded_at", models.DateTimeField()),
                ("creation_root_valid_until", models.DateTimeField()),
                ("requested_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("blocker_codes", models.JSONField()),
                ("canonical_payload", models.JSONField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("upstream_binding_seal", models.CharField(max_length=64)),
                ("claimant_binding_seal", models.CharField(max_length=64)),
                ("fixed_authority_seal", models.CharField(max_length=64)),
                ("header_seal", models.CharField(max_length=64)),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "account_owner_assignment_subject_v3_ledger",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AddField(
            model_name="accountownerassignmentsubjectv3model",
            name="binding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner_assignment_subjects_v3",
                to="account.canonicalaccountcreationbindingv2model",
            ),
        ),
        migrations.AddField(
            model_name="accountownerassignmentsubjectv3model",
            name="creation_root",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner_assignment_subjects_v3",
                to="account.allocatedphysicalaccountrowobservationv3model",
            ),
        ),
        migrations.AddField(
            model_name="accountownerassignmentsubjectv3model",
            name="receipt",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner_assignment_subject_v3",
                to="account.accountownerassignmentprovenancereceiptv3model",
            ),
        ),
        migrations.AddField(
            model_name="accountownerassignmentevidencev3model",
            name="subject",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_evidence_v3",
                to="account.accountownerassignmentsubjectv3model",
            ),
        ),
        migrations.AddIndex(
            model_name="accountownerassignmentsubjectv3model",
            index=models.Index(fields=["subject_id", "requested_at"], name="acct_own_v3_sub_ix"),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentsubjectv3model",
            constraint=models.UniqueConstraint(
                fields=("subject_id", "subject_version"), name="acct_own_v3_sub_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentsubjectv3model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("artifact_type", "account_owner_assignment_subject_v3"),
                    ("claimant_is_staff", False),
                    ("claimant_kind", "human"),
                    ("claimant_role", "account_owner_claimant"),
                    ("owner", "account"),
                    ("permission", "evidence_only"),
                    ("schema", "account-owner-assignment-subject.v3"),
                    ("status", "inactive"),
                ),
                name="acct_own_v3_sub_fixed_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentsubjectv3model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("assigned_owner_user_id", models.F("claimant_user_id")),
                    ("claimant_user_id", models.F("physical_row_user_id")),
                ),
                name="acct_own_v3_sub_actor_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentsubjectv3model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("receipt_recorded_at__lte", models.F("requested_at")),
                    ("requested_at__lt", models.F("valid_until")),
                    ("valid_until__lte", models.F("receipt_valid_until")),
                    ("valid_until__lte", models.F("creation_root_valid_until")),
                    models.Q(
                        ("valid_until", models.F("receipt_valid_until")),
                        ("valid_until", models.F("creation_root_valid_until")),
                        _connector="OR",
                    ),
                    ("persisted_at", models.F("requested_at")),
                ),
                name="acct_own_v3_sub_clock_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="accountownerassignmentevidencev3model",
            index=models.Index(fields=["evidence_id", "recorded_at"], name="acct_own_v3_ev_ix"),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentevidencev3model",
            constraint=models.UniqueConstraint(
                fields=("evidence_id", "evidence_version"), name="acct_own_v3_ev_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentevidencev3model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_is_staff", True),
                    ("approved_kind", "human"),
                    ("approved_role", "account_owner_assignment_approver"),
                    ("artifact_type", "account_owner_assignment_evidence_v3"),
                    ("assignment_state", "authoritative"),
                    ("owner", "account"),
                    ("permission", "evidence_only"),
                    ("schema", "account-owner-assignment-evidence.v3"),
                    ("status", "inactive"),
                ),
                name="acct_own_v3_ev_fixed_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentevidencev3model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("assigned_owner_user_id", models.F("claimant_user_id")),
                    models.Q(("approved_actor_id", models.F("claimant_actor_id")), _negated=True),
                    models.Q(("approved_user_id", models.F("claimant_user_id")), _negated=True),
                ),
                name="acct_own_v3_ev_actor_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentevidencev3model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subject_requested_at__lte", models.F("approved_at")),
                    ("approved_at__lte", models.F("recorded_at")),
                    ("recorded_at__lt", models.F("valid_until")),
                    ("valid_until__lte", models.F("subject_valid_until")),
                    ("valid_until__lte", models.F("approval_valid_until")),
                    models.Q(
                        ("valid_until", models.F("subject_valid_until")),
                        ("valid_until", models.F("approval_valid_until")),
                        _connector="OR",
                    ),
                    ("persisted_at", models.F("recorded_at")),
                ),
                name="acct_own_v3_ev_clock_ck",
            ),
        ),
    ]
