# Generated by Django 5.2.16 on 2026-08-14 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0050_account_owner_assignment_evidence_v3_ledgers"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountOwnerAssignmentActorAuthoritySourceV3RootLockModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_id", models.CharField(max_length=192, unique=True)),
                ("root_claim_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "account_actor_authority_source_v3_root_lock",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="AccountOwnerAssignmentActorAuthoritySourceV3Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=96)),
                ("schema", models.CharField(max_length=96)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("must_not_execute", models.BooleanField()),
                ("execution_allowed", models.BooleanField()),
                ("source_id", models.CharField(max_length=192)),
                ("source_version", models.CharField(max_length=192)),
                ("principal_id", models.CharField(max_length=192)),
                ("user_id", models.PositiveBigIntegerField()),
                ("authentication_context_id", models.CharField(max_length=192)),
                ("authentication_context_version", models.CharField(max_length=192)),
                ("authentication_context_identity_hash", models.CharField(max_length=64)),
                ("authentication_context_content_hash", models.CharField(max_length=64)),
                ("user_source_id", models.CharField(max_length=192)),
                ("user_source_version", models.CharField(max_length=192)),
                ("user_source_content_hash", models.CharField(max_length=64)),
                ("rbac_source_id", models.CharField(max_length=192)),
                ("rbac_source_version", models.CharField(max_length=192)),
                ("rbac_source_content_hash", models.CharField(max_length=64)),
                ("actor_id", models.CharField(max_length=192)),
                ("is_authenticated", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("is_staff", models.BooleanField()),
                ("is_superuser", models.BooleanField()),
                ("rbac_role", models.CharField(max_length=192)),
                ("authority_state", models.CharField(max_length=16)),
                ("principal_authenticated_at", models.DateTimeField()),
                ("principal_valid_until", models.DateTimeField()),
                ("source_recorded_at", models.DateTimeField()),
                ("source_valid_until", models.DateTimeField()),
                ("issued_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("ttl_valid_until", models.DateTimeField()),
                ("valid_until", models.DateTimeField(db_index=True)),
                (
                    "root_claim_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "supersedes_content_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("principal_seal", models.CharField(max_length=64)),
                ("authentication_context_seal", models.CharField(max_length=64)),
                ("user_seal", models.CharField(max_length=64)),
                ("rbac_seal", models.CharField(max_length=64)),
                ("facts_seal", models.CharField(max_length=64)),
                ("clock_seal", models.CharField(max_length=64)),
                ("chain_seal", models.CharField(max_length=64)),
                ("fixed_authority_seal", models.CharField(max_length=64)),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("recorded_by_service_id", models.CharField(max_length=192)),
                ("recorded_by_role", models.CharField(max_length=192)),
                ("recorded_by_kind", models.CharField(max_length=16)),
                ("recorded_by_is_automated", models.BooleanField()),
                ("recorder_binding_seal", models.CharField(max_length=64)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                ("persisted_at", models.DateTimeField()),
                (
                    "predecessor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor",
                        to="account.accountownerassignmentactorauthoritysourcev3model",
                    ),
                ),
                (
                    "root_lock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="account.accountownerassignmentactorauthoritysourcev3rootlockmodel",
                    ),
                ),
            ],
            options={
                "db_table": "account_actor_authority_source_v3_ledger",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(fields=["source_id", "recorded_at"], name="acct_aav3_chain_ix")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_id", "source_version"), name="acct_aav3_source_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("artifact_type", "account_owner_assignment_actor_authority_source_v3"),
                            ("execution_allowed", False),
                            ("must_not_execute", True),
                            ("owner", "account"),
                            ("permission", "attestation_only"),
                            ("recorded_by_is_automated", True),
                            ("recorded_by_kind", "service"),
                            ("recorded_by_role", "account_actor_authority_attestor"),
                            ("schema", "account.owner_assignment_actor_authority_source.v3"),
                            ("status", "inactive"),
                        ),
                        name="acct_aav3_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(authority_state__in=("current", "revoked", "deactivated"))
                            & (
                                ~models.Q(authority_state="current")
                                | models.Q(is_authenticated=True, is_active=True)
                            )
                        ),
                        name="acct_aav3_state_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("predecessor__isnull", True),
                                ("root_claim_hash__isnull", False),
                                ("supersedes_content_hash__isnull", True),
                            ),
                            models.Q(
                                ("predecessor__isnull", False),
                                ("root_claim_hash__isnull", True),
                                ("supersedes_content_hash__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="acct_aav3_root_xor_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("principal_authenticated_at__lte", models.F("source_recorded_at")),
                            ("source_recorded_at__lte", models.F("issued_at")),
                            ("issued_at__lte", models.F("recorded_at")),
                            ("recorded_at__lt", models.F("valid_until")),
                            ("valid_until__lte", models.F("principal_valid_until")),
                            ("valid_until__lte", models.F("source_valid_until")),
                            ("valid_until__lte", models.F("ttl_valid_until")),
                            ("persisted_at", models.F("recorded_at")),
                        ),
                        name="acct_aav3_clock_ck",
                    ),
                ],
            },
        ),
    ]
