# Generated by Django 5.2.8 on 2026-08-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("account", "0054_normalize_physical_v2_fixed_constraint")]

    operations = [
        migrations.CreateModel(
            name="OwnerTenantAuthorityV1Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("authority_id", models.CharField(max_length=192)),
                ("authority_version", models.CharField(max_length=192)),
                ("tenant_id", models.CharField(max_length=192)),
                ("owner_id", models.CharField(max_length=192)),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                ("actor_id", models.CharField(max_length=192)),
                ("actor_user_id", models.PositiveBigIntegerField()),
                ("assignment_evidence_id", models.CharField(max_length=192)),
                ("assignment_evidence_version", models.CharField(max_length=192)),
                ("assignment_evidence_content_hash", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=16)),
                ("approved_actor_id", models.CharField(max_length=192)),
                ("approved_user_id", models.PositiveBigIntegerField()),
                ("approved_role", models.CharField(max_length=192)),
                ("approved_kind", models.CharField(max_length=16)),
                ("approved_is_staff", models.BooleanField()),
                ("approved_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("supersedes_content_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("authority_owner", models.CharField(max_length=32)),
                ("authority_artifact_type", models.CharField(max_length=64)),
                ("authority_schema", models.CharField(max_length=64)),
                ("permission", models.CharField(max_length=32)),
                ("canonical_payload", models.JSONField()),
                ("persisted_at", models.DateTimeField()),
                (
                    "predecessor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor",
                        to="account.ownertenantauthorityv1model",
                    ),
                ),
            ],
            options={
                "db_table": "account_owner_tenant_authority_v1",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["authority_id", "recorded_at"], name="acct_own_ten_auth_pit_ix"
                    ),
                    models.Index(
                        fields=["actor_user_id", "account_id", "recorded_at"],
                        name="acct_own_ten_actor_ix",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("authority_id", "authority_version"), name="acct_own_ten_auth_id_uq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("predecessor__isnull", True)),
                        fields=("authority_id",),
                        name="acct_own_ten_auth_root_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("supersedes_content_hash",), name="acct_own_ten_auth_pred_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ("active", "revoked"))),
                        name="acct_own_ten_auth_status_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("authority_owner", "account"),
                            ("authority_artifact_type", "owner_tenant_authority_v1"),
                            ("authority_schema", "account.owner_tenant_authority.v1"),
                            ("permission", "evidence_read"),
                            ("approved_role", "owner_tenant_authority_approver"),
                            ("approved_kind", "human"),
                            ("approved_is_staff", True),
                        ),
                        name="acct_own_ten_auth_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("actor_id", models.F("approved_actor_id")), _negated=True
                        )
                        & models.Q(("actor_user_id", models.F("approved_user_id")), _negated=True),
                        name="acct_own_ten_auth_actor_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("approved_at__lte", models.F("recorded_at")),
                            ("recorded_at__lt", models.F("valid_until")),
                            ("persisted_at", models.F("recorded_at")),
                        ),
                        name="acct_own_ten_auth_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("supersedes_content_hash__isnull", True),
                                ("predecessor__isnull", True),
                            )
                            | models.Q(
                                ("supersedes_content_hash__isnull", False),
                                ("predecessor__isnull", False),
                            )
                        ),
                        name="acct_own_ten_auth_chain_ck",
                    ),
                ],
            },
        )
    ]
