# Generated by Django 5.2.16 on 2026-09-10 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0056_single_owner_authority_policy_v1"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountOwnerAssignmentProvenanceReceiptV4Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("receipt_id", models.CharField(max_length=192)),
                ("receipt_version", models.CharField(max_length=192)),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("issued_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField()),
                ("persisted_at", models.DateTimeField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                (
                    "supersedes_content_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("canonical_payload", models.JSONField()),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                (
                    "actor_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_claim_receipts_v4",
                        to="account.accountownerassignmentactorauthoritysourcev3model",
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_claim_receipts_v4",
                        to="account.canonicalaccountcreationbindingv2model",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_claim_receipts_v4",
                        to="account.singleownerauthoritypolicyv1model",
                    ),
                ),
                (
                    "predecessor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor",
                        to="account.accountownerassignmentprovenancereceiptv4model",
                    ),
                ),
            ],
            options={
                "db_table": "account_owner_assignment_provenance_receipt_v4_ledger",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(fields=["receipt_id", "recorded_at"], name="acct_prov_v4_chain_ix")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("receipt_id", "receipt_version"), name="acct_prov_v4_id_uq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("predecessor__isnull", True)),
                        fields=("receipt_id",),
                        name="acct_prov_v4_root_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("artifact_type", "account_owner_assignment_provenance_receipt_v4"),
                            ("owner", "account"),
                            ("permission", "claim_evidence_only"),
                            ("schema", "account-owner-assignment-provenance-receipt.v4"),
                            ("status", "inactive"),
                        ),
                        name="acct_prov_v4_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("issued_at__lte", models.F("recorded_at")),
                            ("persisted_at", models.F("recorded_at")),
                            ("recorded_at__lt", models.F("valid_until")),
                        ),
                        name="acct_prov_v4_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("predecessor__isnull", True),
                                ("supersedes_content_hash__isnull", True),
                            ),
                            models.Q(
                                ("predecessor__isnull", False),
                                ("supersedes_content_hash__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="acct_prov_v4_link_ck",
                    ),
                ],
            },
        ),
    ]
