# Generated by Django 5.2.16 on 2026-09-10 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0057_account_owner_assignment_provenance_receipt_v4"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountOwnerAssignmentSubjectV4Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("valid_until", models.DateTimeField()),
                ("persisted_at", models.DateTimeField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("subject_id", models.CharField(max_length=192)),
                ("subject_version", models.CharField(max_length=192)),
                ("requested_at", models.DateTimeField(db_index=True)),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_subject_v4",
                        to="account.accountownerassignmentprovenancereceiptv4model",
                    ),
                ),
            ],
            options={
                "db_table": "account_owner_assignment_subject_v4_ledger",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="AccountOwnerAssignmentEvidenceV4Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("valid_until", models.DateTimeField()),
                ("persisted_at", models.DateTimeField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("evidence_id", models.CharField(max_length=192)),
                ("evidence_version", models.CharField(max_length=192)),
                ("assignment_state", models.CharField(max_length=32)),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                ("underlying_unified_account_namespace", models.CharField(max_length=192)),
                ("underlying_unified_account_id", models.PositiveBigIntegerField()),
                ("account_claim_hash", models.CharField(max_length=64, unique=True)),
                ("underlying_claim_hash", models.CharField(max_length=64, unique=True)),
                ("approved_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("approval_valid_until", models.DateTimeField()),
                (
                    "actor_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_approvals_v4",
                        to="account.accountownerassignmentactorauthoritysourcev3model",
                    ),
                ),
                (
                    "subject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_v4",
                        to="account.accountownerassignmentsubjectv4model",
                    ),
                ),
            ],
            options={
                "db_table": "account_owner_assignment_evidence_v4_ledger",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentsubjectv4model",
            constraint=models.UniqueConstraint(
                fields=("subject_id", "subject_version"), name="acct_asg_v4_sub_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentsubjectv4model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("artifact_type", "account_owner_assignment_subject_v4"),
                    ("owner", "account"),
                    ("permission", "evidence_only"),
                    ("schema", "account-owner-assignment-subject.v4"),
                    ("status", "inactive"),
                ),
                name="acct_asg_v4_sub_fixed_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentsubjectv4model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("persisted_at", models.F("requested_at")),
                    ("requested_at__lt", models.F("valid_until")),
                ),
                name="acct_asg_v4_sub_clock_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentevidencev4model",
            constraint=models.UniqueConstraint(
                fields=("evidence_id", "evidence_version"), name="acct_asg_v4_ev_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentevidencev4model",
            constraint=models.UniqueConstraint(
                fields=("account_namespace", "account_id"), name="acct_asg_v4_account_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentevidencev4model",
            constraint=models.UniqueConstraint(
                fields=("underlying_unified_account_namespace", "underlying_unified_account_id"),
                name="acct_asg_v4_underlying_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentevidencev4model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("artifact_type", "account_owner_assignment_evidence_v4"),
                    ("assignment_state", "authoritative"),
                    ("owner", "account"),
                    ("permission", "evidence_only"),
                    ("schema", "account-owner-assignment-evidence.v4"),
                    ("status", "inactive"),
                ),
                name="acct_asg_v4_ev_fixed_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentevidencev4model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_at__lte", models.F("recorded_at")),
                    ("persisted_at", models.F("recorded_at")),
                    ("recorded_at__lt", models.F("valid_until")),
                    ("valid_until__lte", models.F("approval_valid_until")),
                ),
                name="acct_asg_v4_ev_clock_ck",
            ),
        ),
    ]
