# Generated by Django 5.2.16 on 2026-09-11 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0059_owner_tenant_authority_v2"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalAccountOwnershipReobservationV1Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=96)),
                ("schema", models.CharField(max_length=96)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("observation_id", models.CharField(max_length=192)),
                ("observation_version", models.CharField(max_length=192)),
                ("binding_identity_hash", models.CharField(max_length=64)),
                ("binding_content_hash", models.CharField(max_length=64)),
                ("current_physical_identity_hash", models.CharField(max_length=64)),
                ("current_physical_content_hash", models.CharField(max_length=64)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("persisted_at", models.DateTimeField()),
                ("canonical_payload", models.JSONField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ownership_reobservations_v1",
                        to="account.canonicalaccountcreationbindingv2model",
                    ),
                ),
                (
                    "current_physical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ownership_reobservations_v1",
                        to="account.physicalaccountrowobservationv2model",
                    ),
                ),
            ],
            options={
                "db_table": "canonical_account_ownership_reobservation_v1_ledger",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["binding", "recorded_at"], name="acct_reobs_v1_binding_time_ix"
                    ),
                    models.Index(
                        fields=["current_physical", "recorded_at"],
                        name="acct_reobs_v1_phys_time_ix",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("observation_id", "observation_version"),
                        name="acct_reobs_v1_obs_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("artifact_type", "canonical_account_ownership_reobservation_v1"),
                            ("owner", "account"),
                            ("permission", "evidence_only"),
                            ("schema", "canonical-account-ownership-reobservation.v1"),
                            ("status", "inactive"),
                        ),
                        name="acct_reobs_v1_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("recorded_at__lt", models.F("valid_until")),
                            ("persisted_at", models.F("recorded_at")),
                        ),
                        name="acct_reobs_v1_clock_ck",
                    ),
                ],
            },
        ),
    ]
