# Generated by Django 5.2.16 on 2026-09-11 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0060_canonical_account_ownership_reobservation_v1"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountOwnerAssignmentProvenanceReceiptV5Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("valid_until", models.DateTimeField()),
                ("persisted_at", models.DateTimeField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("receipt_id", models.CharField(max_length=192)),
                ("receipt_version", models.CharField(max_length=192)),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                ("underlying_unified_account_namespace", models.CharField(max_length=192)),
                ("underlying_unified_account_id", models.PositiveBigIntegerField()),
                ("assigned_owner_user_id", models.PositiveBigIntegerField()),
                ("issued_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                (
                    "supersedes_content_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_claim_receipts_v5",
                        to="account.canonicalaccountcreationbindingv2model",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_claim_receipts_v5",
                        to="account.singleownerauthoritypolicyv1model",
                    ),
                ),
                (
                    "predecessor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor",
                        to="account.accountownerassignmentprovenancereceiptv5model",
                    ),
                ),
                (
                    "reobservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_claim_receipts_v5",
                        to="account.canonicalaccountownershipreobservationv1model",
                    ),
                ),
            ],
            options={
                "db_table": "account_owner_assignment_provenance_receipt_v5_ledger",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="AccountOwnerAssignmentSubjectV5Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("valid_until", models.DateTimeField()),
                ("persisted_at", models.DateTimeField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("subject_id", models.CharField(max_length=192)),
                ("subject_version", models.CharField(max_length=192)),
                ("requested_at", models.DateTimeField(db_index=True)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_assignment_subjects_v5",
                        to="account.canonicalaccountcreationbindingv2model",
                    ),
                ),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_subject_v5",
                        to="account.accountownerassignmentprovenancereceiptv5model",
                    ),
                ),
                (
                    "reobservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_assignment_subjects_v5",
                        to="account.canonicalaccountownershipreobservationv1model",
                    ),
                ),
            ],
            options={
                "db_table": "account_owner_assignment_subject_v5_ledger",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AddIndex(
            model_name="accountownerassignmentprovenancereceiptv5model",
            index=models.Index(fields=["receipt_id", "recorded_at"], name="acct_prov_v5_chain_ix"),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentprovenancereceiptv5model",
            constraint=models.UniqueConstraint(
                fields=("receipt_id", "receipt_version"), name="acct_prov_v5_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentprovenancereceiptv5model",
            constraint=models.UniqueConstraint(
                condition=models.Q(("predecessor__isnull", True)),
                fields=("receipt_id",),
                name="acct_prov_v5_root_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentprovenancereceiptv5model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("artifact_type", "account_owner_assignment_provenance_receipt_v5"),
                    ("owner", "account"),
                    ("permission", "claim_evidence_only"),
                    ("schema", "account-owner-assignment-provenance-receipt.v5"),
                    ("status", "inactive"),
                ),
                name="acct_prov_v5_fixed_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentprovenancereceiptv5model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("issued_at__lte", models.F("recorded_at")),
                    ("persisted_at", models.F("recorded_at")),
                    ("recorded_at__lt", models.F("valid_until")),
                ),
                name="acct_prov_v5_clock_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentprovenancereceiptv5model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("predecessor__isnull", True), ("supersedes_content_hash__isnull", True)
                    ),
                    models.Q(
                        ("predecessor__isnull", False), ("supersedes_content_hash__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="acct_prov_v5_link_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentsubjectv5model",
            constraint=models.UniqueConstraint(
                fields=("subject_id", "subject_version"), name="acct_asg_v5_sub_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentsubjectv5model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("artifact_type", "account_owner_assignment_subject_v5"),
                    ("owner", "account"),
                    ("permission", "evidence_only"),
                    ("schema", "account-owner-assignment-subject.v5"),
                    ("status", "inactive"),
                ),
                name="acct_asg_v5_sub_fixed_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentsubjectv5model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("persisted_at", models.F("requested_at")),
                    ("requested_at__lt", models.F("valid_until")),
                ),
                name="acct_asg_v5_sub_clock_ck",
            ),
        ),
    ]
