# Generated by Django 5.2.16 on 2026-09-11 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0061_account_owner_assignment_v5"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountOwnerAssignmentEvidenceV5Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("valid_until", models.DateTimeField()),
                ("persisted_at", models.DateTimeField()),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("evidence_id", models.CharField(max_length=192)),
                ("evidence_version", models.CharField(max_length=192)),
                ("assignment_state", models.CharField(max_length=32)),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                ("underlying_unified_account_namespace", models.CharField(max_length=192)),
                ("underlying_unified_account_id", models.PositiveBigIntegerField()),
                ("account_claim_hash", models.CharField(max_length=64, unique=True)),
                ("underlying_claim_hash", models.CharField(max_length=64, unique=True)),
                ("approved_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("approval_valid_until", models.DateTimeField()),
                (
                    "actor_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_approvals_v5",
                        to="account.accountownerassignmentactorauthoritysourcev3model",
                    ),
                ),
                (
                    "subject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_v5",
                        to="account.accountownerassignmentsubjectv5model",
                    ),
                ),
            ],
            options={
                "db_table": "account_owner_assignment_evidence_v5_ledger",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("evidence_id", "evidence_version"), name="acct_asg_v5_ev_id_uq"
                    ),
                    models.UniqueConstraint(
                        fields=("account_namespace", "account_id"), name="acct_asg_v5_account_uq"
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "underlying_unified_account_namespace",
                            "underlying_unified_account_id",
                        ),
                        name="acct_asg_v5_underlying_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("artifact_type", "account_owner_assignment_evidence_v5"),
                            ("assignment_state", "authoritative"),
                            ("owner", "account"),
                            ("permission", "evidence_only"),
                            ("schema", "account-owner-assignment-evidence.v5"),
                            ("status", "inactive"),
                        ),
                        name="acct_asg_v5_ev_fixed_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("approved_at__lte", models.F("recorded_at")),
                            ("persisted_at", models.F("recorded_at")),
                            ("recorded_at__lt", models.F("valid_until")),
                            ("valid_until__lte", models.F("approval_valid_until")),
                        ),
                        name="acct_asg_v5_ev_clock_ck",
                    ),
                ],
            },
        ),
    ]
