# Generated by Django 5.2.12 on 2026-09-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0062_account_owner_assignment_evidence_v5"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerTenantAuthorityV3Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=96)),
                ("schema", models.CharField(max_length=96)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("authority_id", models.CharField(max_length=192)),
                ("authority_version", models.CharField(max_length=192)),
                ("assignment_evidence_id", models.CharField(max_length=192)),
                ("assignment_evidence_version", models.CharField(max_length=192)),
                ("assignment_evidence_content_hash", models.CharField(max_length=64)),
                ("policy_identifier", models.CharField(max_length=192)),
                ("policy_version", models.CharField(max_length=192)),
                ("policy_content_hash", models.CharField(max_length=64)),
                ("tenant_id", models.CharField(max_length=192)),
                ("owner_id", models.CharField(max_length=192)),
                ("account_namespace", models.CharField(max_length=192)),
                ("account_id", models.CharField(max_length=192)),
                ("actor_id", models.CharField(max_length=192)),
                ("actor_user_id", models.PositiveBigIntegerField()),
                ("approved_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("supersedes_content_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("persisted_at", models.DateTimeField()),
                (
                    "actor_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_tenant_authority_v3_approvals",
                        to="account.accountownerassignmentactorauthoritysourcev3model",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_tenant_authority_v3_roots",
                        to="account.accountownerassignmentevidencev5model",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_tenant_authority_v3_roots",
                        to="account.singleownerauthoritypolicyv1model",
                    ),
                ),
                (
                    "predecessor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor",
                        to="account.ownertenantauthorityv3model",
                    ),
                ),
            ],
            options={
                "db_table": "account_owner_tenant_authority_v3_ledger",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="OwnerTenantAuthorityV3RevocationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("artifact_type", models.CharField(max_length=96)),
                ("schema", models.CharField(max_length=96)),
                ("permission", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=16)),
                ("identity_hash", models.CharField(max_length=64, unique=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                ("record_seal", models.CharField(max_length=64, unique=True)),
                ("ledger_seal", models.CharField(max_length=64, unique=True)),
                ("authority_content_hash", models.CharField(max_length=64, unique=True)),
                ("policy_content_hash", models.CharField(max_length=64)),
                ("revoked_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("persisted_at", models.DateTimeField()),
                ("reason", models.CharField(max_length=192)),
                (
                    "actor_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_tenant_authority_v3_revocations",
                        to="account.accountownerassignmentactorauthoritysourcev3model",
                    ),
                ),
                (
                    "authority",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_tenant_authority_v3_revocation",
                        to="account.ownertenantauthorityv3model",
                    ),
                ),
            ],
            options={
                "db_table": "account_owner_tenant_authority_v3_revocation_ledger",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AddIndex(
            model_name="ownertenantauthorityv3model",
            index=models.Index(
                fields=["authority_id", "recorded_at"], name="acct_otav3_authority_time_ix"
            ),
        ),
        migrations.AddIndex(
            model_name="ownertenantauthorityv3model",
            index=models.Index(
                fields=["assignment_evidence_content_hash", "recorded_at"],
                name="acct_otav3_assignment_time_ix",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownertenantauthorityv3model",
            constraint=models.UniqueConstraint(
                fields=("authority_id", "authority_version"), name="acct_otav3_authority_id_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="ownertenantauthorityv3model",
            constraint=models.UniqueConstraint(
                condition=models.Q(("predecessor__isnull", True)),
                fields=("authority_id",),
                name="acct_otav3_authority_root_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownertenantauthorityv3model",
            constraint=models.UniqueConstraint(
                fields=("supersedes_content_hash",), name="acct_otav3_authority_pred_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="ownertenantauthorityv3model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("artifact_type", "owner_tenant_authority_v3"),
                    ("owner", "account"),
                    ("permission", "evidence_read"),
                    ("schema", "account.owner_tenant_authority.v3"),
                    ("status", "active"),
                ),
                name="acct_otav3_fixed_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownertenantauthorityv3model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_at__lte", models.F("recorded_at")),
                    ("recorded_at__lt", models.F("valid_until")),
                    ("persisted_at", models.F("recorded_at")),
                ),
                name="acct_otav3_clock_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownertenantauthorityv3model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("supersedes_content_hash__isnull", True), ("predecessor__isnull", True)
                    ),
                    models.Q(
                        ("supersedes_content_hash__isnull", False), ("predecessor__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="acct_otav3_authority_chain_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="ownertenantauthorityv3revocationmodel",
            index=models.Index(
                fields=["authority_content_hash", "recorded_at"], name="acct_otav3_revoke_time_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="ownertenantauthorityv3revocationmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("artifact_type", "owner_tenant_authority_v3_revocation"),
                    ("owner", "account"),
                    ("permission", "evidence_read"),
                    ("schema", "account.owner_tenant_authority.v3.revocation"),
                    ("status", "revoked"),
                ),
                name="acct_otav3_revoke_fixed_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownertenantauthorityv3revocationmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("revoked_at__lte", models.F("recorded_at")),
                    ("persisted_at", models.F("recorded_at")),
                ),
                name="acct_otav3_revoke_clock_ck",
            ),
        ),
    ]
