# Generated by Django 5.2.12 on 2026-09-23 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0063_owner_tenant_authority_v3"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accountownerassignmentevidencev5model",
            name="acct_asg_v5_account_uq",
        ),
        migrations.RemoveConstraint(
            model_name="accountownerassignmentevidencev5model",
            name="acct_asg_v5_underlying_uq",
        ),
        migrations.AddField(
            model_name="accountownerassignmentevidencev5model",
            name="predecessor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="successor",
                to="account.accountownerassignmentevidencev5model",
            ),
        ),
        migrations.AddField(
            model_name="accountownerassignmentevidencev5model",
            name="supersedes_content_hash",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="accountownerassignmentevidencev5model",
            name="account_claim_hash",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="accountownerassignmentevidencev5model",
            name="underlying_claim_hash",
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentevidencev5model",
            constraint=models.UniqueConstraint(
                condition=models.Q(("predecessor__isnull", True)),
                fields=("account_namespace", "account_id"),
                name="acct_asg_v5_account_root_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentevidencev5model",
            constraint=models.UniqueConstraint(
                condition=models.Q(("predecessor__isnull", True)),
                fields=("underlying_unified_account_namespace", "underlying_unified_account_id"),
                name="acct_asg_v5_underlying_root_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentevidencev5model",
            constraint=models.UniqueConstraint(
                condition=models.Q(("predecessor__isnull", True)),
                fields=("account_claim_hash",),
                name="acct_asg_v5_account_claim_root_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentevidencev5model",
            constraint=models.UniqueConstraint(
                condition=models.Q(("predecessor__isnull", True)),
                fields=("underlying_claim_hash",),
                name="acct_asg_v5_under_claim_root_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountownerassignmentevidencev5model",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("predecessor__isnull", True), ("supersedes_content_hash__isnull", True)
                    ),
                    models.Q(
                        ("predecessor__isnull", False), ("supersedes_content_hash__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="acct_asg_v5_ev_link_ck",
            ),
        ),
    ]
