# Generated by Django 5.2.10 on 2026-03-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SetupStateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_completed", models.BooleanField(default=False, help_text="是否已完成初始化")),
                (
                    "admin_username",
                    models.CharField(blank=True, help_text="创建的管理员用户名", max_length=150),
                ),
                (
                    "admin_email",
                    models.EmailField(blank=True, help_text="管理员邮箱", max_length=254),
                ),
                (
                    "ai_provider_configured",
                    models.BooleanField(default=False, help_text="是否已配置 AI Provider"),
                ),
                (
                    "data_source_configured",
                    models.BooleanField(default=False, help_text="是否已配置数据源"),
                ),
                (
                    "current_step",
                    models.CharField(default="welcome", help_text="当前步骤", max_length=50),
                ),
                (
                    "completed_steps",
                    models.JSONField(blank=True, default=list, help_text="已完成的步骤列表"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, help_text="完成时间", null=True)),
            ],
            options={
                "verbose_name": "安装向导状态",
                "verbose_name_plural": "安装向导状态",
                "db_table": "setup_wizard_state",
            },
        ),
    ]
