# Generated by Django 5.2.12 on 2026-07-28 07:00

from django.db import migrations, models


def validate_existing_fund_data(apps, schema_editor):
    """Fail before adding constraints without silently rewriting investment facts."""

    FundHolding = apps.get_model("fund", "FundHoldingModel")
    FundInfo = apps.get_model("fund", "FundInfoModel")
    FundManager = apps.get_model("fund", "FundManagerModel")
    FundNetValue = apps.get_model("fund", "FundNetValueModel")
    FundPerformance = apps.get_model("fund", "FundPerformanceModel")
    FundSector = apps.get_model("fund", "FundSectorAllocationModel")
    violations = []
    if FundInfo.objects.filter(fund_scale__lt=0).exists():
        violations.append("negative fund scale")
    if FundManager.objects.filter(tenure_end__lt=models.F("tenure_start")).exists():
        violations.append("reversed manager tenure")
    if FundManager.objects.filter(total_tenure_days__lt=0).exists():
        violations.append("negative manager tenure days")
    if FundNetValue.objects.filter(models.Q(unit_nav__lte=0) | models.Q(accum_nav__lte=0)).exists():
        violations.append("non-positive fund NAV")
    if FundHolding.objects.filter(
        models.Q(holding_amount__lt=0)
        | models.Q(holding_value__lt=0)
        | models.Q(holding_ratio__lt=0)
        | models.Q(holding_ratio__gt=100)
    ).exists():
        violations.append("invalid fund holding")
    if FundSector.objects.filter(
        models.Q(allocation_ratio__lt=0) | models.Q(allocation_ratio__gt=100)
    ).exists():
        violations.append("invalid fund sector allocation")
    if FundPerformance.objects.filter(end_date__lt=models.F("start_date")).exists():
        violations.append("reversed performance window")
    if FundPerformance.objects.filter(volatility__lt=0).exists():
        violations.append("negative fund volatility")
    if violations:
        raise RuntimeError("Cannot add Fund constraints: " + ", ".join(violations))


class Migration(migrations.Migration):

    dependencies = [
        ("fund", "0002_fundtypepreferenceconfigmodel"),
    ]

    operations = [
        migrations.RunPython(validate_existing_fund_data, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="fundholdingmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("holding_amount__isnull", True), ("holding_amount__gte", 0), _connector="OR"
                ),
                name="fund_holding_amount_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundholdingmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("holding_value__isnull", True), ("holding_value__gte", 0), _connector="OR"
                ),
                name="fund_holding_value_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundholdingmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("holding_ratio__isnull", True),
                    models.Q(("holding_ratio__gte", 0), ("holding_ratio__lte", 100)),
                    _connector="OR",
                ),
                name="fund_holding_ratio_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundinfomodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fund_scale__isnull", True), ("fund_scale__gte", 0), _connector="OR"
                ),
                name="fund_info_scale_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundmanagermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tenure_end__isnull", True),
                    ("tenure_end__gte", models.F("tenure_start")),
                    _connector="OR",
                ),
                name="fund_manager_tenure_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundmanagermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("total_tenure_days__isnull", True),
                    ("total_tenure_days__gte", 0),
                    _connector="OR",
                ),
                name="fund_manager_tenure_days_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundnetvaluemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_nav__gt", 0)), name="fund_nav_unit_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="fundnetvaluemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("accum_nav__gt", 0)), name="fund_nav_accum_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="fundperformancemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="fund_performance_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundperformancemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("volatility__isnull", True), ("volatility__gte", 0), _connector="OR"
                ),
                name="fund_performance_volatility_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundsectorallocationmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("allocation_ratio__gte", 0), ("allocation_ratio__lte", 100)),
                name="fund_sector_ratio_0_100",
            ),
        ),
    ]
