# Generated by Django 5.2.12 on 2026-07-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config_center", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlphaUniverseConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "universe_id",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="Universe ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="名称")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "手工代码清单"),
                            ("csv", "CSV 导入代码清单"),
                            ("data_center_filter", "Data Center 条件生成"),
                        ],
                        default="manual",
                        max_length=32,
                        verbose_name="来源类型",
                    ),
                ),
                (
                    "stock_codes",
                    models.JSONField(blank=True, default=list, verbose_name="股票代码清单"),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="Data Center 过滤条件"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Alpha Universe 配置",
                "verbose_name_plural": "Alpha Universe 配置",
                "db_table": "config_center_alpha_universe_config",
                "ordering": ["universe_id"],
            },
        ),
        migrations.AlterField(
            model_name="systemsettingsmodel",
            name="qlib_default_universe",
            field=models.CharField(default="csi300", max_length=64, verbose_name="Qlib 默认股票池"),
        ),
    ]
