# Generated by Django 5.2.12 on 2026-08-02 19:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config_center", "0006_runtimeconfigdefinitionmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageCapacityObservationModel",
            fields=[
                (
                    "observation_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("environment", models.CharField(db_index=True, max_length=80)),
                ("observed_at", models.DateTimeField(db_index=True)),
                ("filesystem_total_bytes", models.PositiveBigIntegerField()),
                ("filesystem_used_bytes", models.PositiveBigIntegerField()),
                ("filesystem_free_bytes", models.PositiveBigIntegerField()),
                ("database_size_bytes", models.PositiveBigIntegerField()),
                ("relation_sizes", models.JSONField(default=dict)),
                ("policy_key", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "configured_capacity_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("effective_capacity_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("usage_ratio", models.FloatField(blank=True, null=True)),
                ("pressure_state", models.CharField(blank=True, db_index=True, max_length=20)),
                ("source", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "config_center_storage_capacity_observation",
                "ordering": ["-observed_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["environment", "observed_at"], name="config_cent_environ_ef3131_idx"
                    ),
                    models.Index(
                        fields=["environment", "pressure_state", "observed_at"],
                        name="config_cent_environ_6e7241_idx",
                    ),
                ],
            },
        ),
    ]
