# Generated by Django 5.2.9 on 2025-12-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("total_pnl", models.FloatField()),
                ("regime_timing_pnl", models.FloatField()),
                ("asset_selection_pnl", models.FloatField()),
                ("interaction_pnl", models.FloatField()),
                ("regime_predicted", models.CharField(max_length=20)),
                ("regime_actual", models.CharField(max_length=20)),
                ("lesson_learned", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_report",
                "ordering": ["-period_end"],
            },
        ),
    ]
