# Generated by Django 5.2.10 on 2026-02-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_add_confidence_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributionreport",
            name="attribution_method",
            field=models.CharField(
                choices=[
                    ("heuristic", "启发式方法（30%/50%规则）"),
                    ("brinson", "标准Brinson模型"),
                ],
                default="heuristic",
                help_text="使用的归因分析方法",
                max_length=20,
                verbose_name="归因方法",
            ),
        ),
    ]
