# Generated by Django 5.2.12 on 2026-08-14 15:13

import django.core.serializers.json
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0010_alter_attribution_regime_actual"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemAuditEventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_id", models.CharField(max_length=128)),
                ("event_version", models.CharField(max_length=64)),
                ("schema_version", models.CharField(max_length=64)),
                ("category", models.CharField(max_length=64)),
                ("event_type", models.CharField(max_length=128)),
                ("owner", models.CharField(max_length=64)),
                ("write_policy", models.CharField(max_length=32)),
                ("outcome", models.CharField(max_length=32)),
                ("severity", models.CharField(max_length=16)),
                (
                    "reason_codes",
                    models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("actor_type", models.CharField(max_length=64)),
                ("actor_id", models.CharField(max_length=256)),
                ("actor_display", models.CharField(blank=True, max_length=256, null=True)),
                ("source_app", models.CharField(max_length=128)),
                ("source_component", models.CharField(max_length=128)),
                ("source_surface", models.CharField(max_length=64)),
                (
                    "correlations",
                    models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("resource_type", models.CharField(blank=True, max_length=128, null=True)),
                ("resource_id", models.CharField(blank=True, max_length=256, null=True)),
                ("resource_version", models.CharField(blank=True, max_length=128, null=True)),
                ("dataset_key", models.CharField(blank=True, max_length=256, null=True)),
                ("provider_key", models.CharField(blank=True, max_length=256, null=True)),
                ("capability", models.CharField(blank=True, max_length=256, null=True)),
                ("publication_id", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "evidence_refs",
                    models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("detail_schema", models.CharField(max_length=128)),
                (
                    "detail",
                    models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                (
                    "canonical_payload",
                    models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("stream_id", models.CharField(db_index=True, max_length=256)),
                ("sequence_no", models.PositiveBigIntegerField()),
                ("predecessor_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("idempotency_key", models.CharField(max_length=256)),
                ("identity_hash", models.CharField(max_length=64)),
                ("content_hash", models.CharField(max_length=64)),
                ("persisted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "audit_system_event",
                "ordering": ["stream_id", "sequence_no"],
                "default_manager_name": "objects",
                "base_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["event_type", "recorded_at"], name="audit_event_type_recorded_idx"
                    ),
                    models.Index(
                        fields=["category", "outcome", "recorded_at"],
                        name="audit_event_cat_outcome_idx",
                    ),
                    models.Index(
                        fields=["actor_id", "recorded_at"], name="audit_event_actor_recorded_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_id", "event_version"), name="audit_event_identity_unique"
                    ),
                    models.UniqueConstraint(
                        fields=("identity_hash",), name="audit_event_identity_hash_unique"
                    ),
                    models.UniqueConstraint(
                        fields=("content_hash",), name="audit_event_content_hash_unique"
                    ),
                    models.UniqueConstraint(
                        fields=("stream_id", "sequence_no"),
                        name="audit_event_stream_sequence_unique",
                    ),
                    models.UniqueConstraint(
                        fields=("stream_id", "idempotency_key"),
                        name="audit_event_stream_idempotency_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence_no__gte", 1)),
                        name="audit_event_sequence_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("recorded_at__gte", models.F("occurred_at"))),
                        name="audit_event_recorded_after_occurred",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("observed_at__isnull", True),
                            ("recorded_at__gte", models.F("observed_at")),
                            _connector="OR",
                        ),
                        name="audit_event_recorded_after_observed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("predecessor_hash__isnull", True), ("sequence_no", 1)),
                            models.Q(("predecessor_hash__isnull", False), ("sequence_no__gt", 1)),
                            _connector="OR",
                        ),
                        name="audit_event_root_successor_predecessor",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemAuditOutboxModel",
            fields=[
                (
                    "outbox_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.CharField(max_length=128, unique=True)),
                ("idempotency_key", models.CharField(max_length=256, unique=True)),
                (
                    "payload",
                    models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("payload_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("claimed", "claimed"),
                            ("delivered", "delivered"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("available_at", models.DateTimeField(db_index=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_by", models.CharField(blank=True, max_length=128, null=True)),
                ("claim_token", models.CharField(blank=True, max_length=128, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=128, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "audit_system_outbox",
                "ordering": ["available_at", "created_at"],
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["status", "available_at"], name="audit_outbox_claim_idx"
                    ),
                    models.Index(
                        fields=["claimed_by", "claimed_at"], name="audit_outbox_owner_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ("pending", "claimed", "delivered", "failed"))
                        ),
                        name="audit_outbox_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempt_count__gte", 0)),
                        name="audit_outbox_attempt_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("claimed_at__isnull", True), ("claimed_by__isnull", True)),
                            models.Q(
                                ("claimed_at__isnull", False), ("claimed_by__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="audit_outbox_claim_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("updated_at__gte", models.F("created_at"))),
                        name="audit_outbox_clock_order",
                    ),
                ],
            },
        ),
    ]
