# Generated by Django 5.2.12 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0011_systemauditeventmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemauditeventmodel",
            name="scope_owner_id",
            field=models.CharField(blank=True, max_length=192, null=True),
        ),
        migrations.AddField(
            model_name="systemauditeventmodel",
            name="scope_tenant_id",
            field=models.CharField(blank=True, max_length=192, null=True),
        ),
        migrations.AddConstraint(
            model_name="systemauditeventmodel",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(scope_tenant_id__isnull=True, scope_owner_id__isnull=True)
                    | models.Q(scope_tenant_id__isnull=False, scope_owner_id__isnull=False)
                ),
                name="audit_event_scope_pair",
            ),
        ),
        migrations.AddIndex(
            model_name="systemauditeventmodel",
            index=models.Index(
                fields=["scope_tenant_id", "scope_owner_id", "recorded_at"],
                name="audit_event_scope_recorded_idx",
            ),
        ),
    ]
