# Generated by Django 5.2 for governed stress scenarios.

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

REVISION_STATUS_CHOICES = [
    ("candidate", "Candidate"),
    ("draft", "Draft"),
    ("proposed", "Proposed"),
    ("approved", "Approved"),
    ("active", "Active"),
    ("superseded", "Superseded"),
    ("rejected", "Rejected"),
]


class Migration(migrations.Migration):
    dependencies = [("risk_center", "0002_riskdailyreportmodel")]

    operations = [
        migrations.CreateModel(
            name="ScenarioSetModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("set_key", models.CharField(db_index=True, max_length=120, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("purpose", models.CharField(db_index=True, max_length=80)),
                ("owner", models.CharField(default="risk_center", max_length=80)),
                ("applicable_asset_scope", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "risk_center_scenario_set",
                "ordering": ["purpose", "set_key"],
            },
        ),
        migrations.CreateModel(
            name="StressScenarioDefinitionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scenario_key", models.CharField(db_index=True, max_length=120, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("category", models.CharField(db_index=True, max_length=80)),
                ("owner", models.CharField(default="risk_center", max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("legacy_aliases", models.JSONField(blank=True, default=list)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "risk_center_stress_scenario_definition",
                "ordering": ["category", "scenario_key"],
                "indexes": [
                    models.Index(fields=["status", "category"], name="risk_scn_def_status_cat")
                ],
            },
        ),
        migrations.CreateModel(
            name="ScenarioSetRevisionModel",
            fields=[
                (
                    "revision_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(choices=REVISION_STATUS_CHOICES, db_index=True, max_length=16),
                ),
                ("driver_axes", models.JSONField(blank=True, default=list)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("created_by", models.CharField(max_length=150)),
                ("change_reason", models.TextField()),
                ("effective_from", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "scenario_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="risk_center.scenariosetmodel",
                    ),
                ),
            ],
            options={
                "db_table": "risk_center_scenario_set_revision",
                "ordering": ["scenario_set_id", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scenario_set", "version"),
                        name="risk_scn_set_revision_ver_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(version__gt=0),
                        name="risk_scn_set_revision_ver_pos",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(effective_to__isnull=True)
                        | models.Q(effective_from__isnull=True)
                        | models.Q(effective_to__gt=models.F("effective_from")),
                        name="risk_scn_set_effective_order",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StressScenarioRevisionModel",
            fields=[
                (
                    "revision_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("based_on_version", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(choices=REVISION_STATUS_CHOICES, db_index=True, max_length=16),
                ),
                (
                    "scenario_type",
                    models.CharField(
                        choices=[
                            ("historical_window", "Historical window"),
                            ("rolling_extreme", "Rolling extreme"),
                            ("parametric_shock", "Parametric shock"),
                            ("macro_path", "Macro path"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("assumptions", models.JSONField(blank=True, default=list)),
                ("source_evidence", models.JSONField(blank=True, default=list)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("human", "Human"),
                            ("ai_mcp", "AI MCP"),
                            ("seed", "Seed"),
                            ("detector", "Detector"),
                            ("legacy_code_migration", "Legacy code migration"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("created_by", models.CharField(max_length=150)),
                ("change_reason", models.TextField()),
                ("effective_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="risk_center.stressscenariodefinitionmodel",
                    ),
                ),
            ],
            options={
                "db_table": "risk_center_stress_scenario_revision",
                "ordering": ["definition_id", "-version"],
                "indexes": [
                    models.Index(
                        fields=["definition", "status", "-version"],
                        name="risk_scn_rev_def_status",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("definition", "version"),
                        name="risk_scn_revision_version_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(version__gt=0),
                        name="risk_scn_revision_ver_pos",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(based_on_version__isnull=True)
                        | models.Q(based_on_version__lt=models.F("version")),
                        name="risk_scn_revision_base_lt",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScenarioSetMemberModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "probability",
                    models.DecimalField(
                        decimal_places=12,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "probability_source",
                    models.CharField(
                        choices=[
                            ("subjective", "Subjective"),
                            ("model_inferred", "Model inferred"),
                        ],
                        max_length=24,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "scenario_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="set_memberships",
                        to="risk_center.stressscenariorevisionmodel",
                    ),
                ),
                (
                    "scenario_set_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="risk_center.scenariosetrevisionmodel",
                    ),
                ),
            ],
            options={
                "db_table": "risk_center_scenario_set_member",
                "ordering": ["sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scenario_set_revision", "scenario_revision"),
                        name="risk_scn_set_member_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(probability__gte=0, probability__lte=1),
                        name="risk_scn_member_prob_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScenarioActivationModel",
            fields=[
                (
                    "activation_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("environment", models.CharField(db_index=True, max_length=40)),
                ("purpose", models.CharField(db_index=True, max_length=80)),
                ("activated_by", models.CharField(max_length=150)),
                ("reason", models.TextField()),
                ("correlation_id", models.CharField(blank=True, default="", max_length=120)),
                (
                    "activated_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "previous_activation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement_activations",
                        to="risk_center.scenarioactivationmodel",
                    ),
                ),
                (
                    "scenario_set_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activations",
                        to="risk_center.scenariosetrevisionmodel",
                    ),
                ),
            ],
            options={
                "db_table": "risk_center_scenario_activation",
                "ordering": ["-activated_at"],
                "indexes": [
                    models.Index(
                        fields=["environment", "purpose", "-activated_at"],
                        name="risk_scn_activation_scope",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(is_active=True),
                        fields=("environment", "purpose"),
                        name="risk_scn_one_active_scope",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScenarioRunEvidenceModel",
            fields=[
                (
                    "run_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("portfolio_snapshot_id", models.CharField(db_index=True, max_length=120)),
                ("portfolio_snapshot_hash", models.CharField(max_length=64)),
                ("as_of_time", models.DateTimeField(db_index=True)),
                ("data_evidence_ids", models.JSONField(default=list)),
                (
                    "result_hash",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("allocation_policy_version", models.CharField(max_length=120)),
                ("code_version", models.CharField(max_length=120)),
                ("must_not_use_for_decision", models.BooleanField(db_index=True, default=False)),
                ("blocked_reason", models.CharField(blank=True, default="", max_length=160)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "scenario_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="run_evidence",
                        to="risk_center.stressscenariorevisionmodel",
                    ),
                ),
                (
                    "scenario_set_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="run_evidence",
                        to="risk_center.scenariosetrevisionmodel",
                    ),
                ),
            ],
            options={
                "db_table": "risk_center_scenario_run_evidence",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scenario_revision", "-created_at"],
                        name="risk_scn_run_revision",
                    ),
                    models.Index(
                        fields=["portfolio_snapshot_id", "-created_at"],
                        name="risk_scn_run_portfolio",
                    ),
                ],
            },
        ),
    ]
