# Generated by Django 5.2.16 on 2026-08-13 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Schema-only, zero-seed Broker execution-risk policy ledgers."""

    dependencies = [
        ("risk_center", "0008_broker_order_risk_authorizations"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerOrderExecutionPolicySourceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_snapshot_id", models.CharField(max_length=192)),
                ("source_snapshot_version", models.CharField(max_length=192)),
                ("source_identity_hash", models.CharField(max_length=64, unique=True)),
                ("account_id", models.PositiveBigIntegerField()),
                ("source_recorded_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField()),
            ],
            options={
                "db_table": "risk_center_broker_execution_policy_source",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["account_id", "recorded_at"], name="risk_br_pol_src_pit_ix"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_snapshot_id", "source_snapshot_version"),
                        name="risk_br_pol_src_id_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_recorded_at__lte", models.F("recorded_at")),
                            ("recorded_at__lt", models.F("valid_until")),
                            ("persisted_at", models.F("recorded_at")),
                        ),
                        name="risk_br_pol_src_clock_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BrokerOrderExecutionPolicyActivationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("owner", models.CharField(max_length=32)),
                ("capability", models.CharField(max_length=64)),
                ("schema", models.CharField(max_length=64)),
                ("permission_cap", models.CharField(max_length=32)),
                ("policy_id", models.CharField(max_length=192)),
                ("policy_version", models.CharField(max_length=192)),
                ("policy_identity_hash", models.CharField(max_length=64, unique=True)),
                ("account_id", models.PositiveBigIntegerField()),
                ("source_snapshot_id", models.CharField(max_length=192)),
                ("source_snapshot_version", models.CharField(max_length=192)),
                ("source_snapshot_hash", models.CharField(max_length=64)),
                ("supersedes_policy_hash", models.CharField(max_length=64, null=True)),
                ("activated_actor_id", models.CharField(max_length=192)),
                ("activated_actor_user_id", models.PositiveBigIntegerField()),
                ("activated_actor_kind", models.CharField(max_length=16)),
                ("activated_actor_is_staff", models.BooleanField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("activated_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("canonical_policy", models.JSONField()),
                ("canonical_activation", models.JSONField()),
                ("policy_content_hash", models.CharField(max_length=64, unique=True)),
                ("activation_content_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policy_activations",
                        to="risk_center.brokerorderexecutionpolicysourcemodel",
                    ),
                ),
            ],
            options={
                "db_table": "risk_center_broker_execution_policy_activation",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["account_id", "recorded_at"], name="risk_br_pol_act_pit_ix"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy_id", "policy_version"), name="risk_br_pol_act_id_uq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("supersedes_policy_hash__isnull", False)),
                        fields=("supersedes_policy_hash",),
                        name="risk_br_pol_act_next_uq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("supersedes_policy_hash__isnull", True)),
                        fields=("account_id",),
                        name="risk_br_pol_act_root_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("owner", "risk_center"),
                            ("capability", "broker_order_execution_risk_policy"),
                            ("permission_cap", "execution_eligible"),
                        ),
                        name="risk_br_pol_act_owner_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("recorded_at", models.F("activated_at")),
                            ("activated_at__lt", models.F("valid_until")),
                            ("persisted_at", models.F("recorded_at")),
                        ),
                        name="risk_br_pol_act_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("activated_actor_is_staff", True), ("activated_actor_kind", "human")
                        ),
                        name="risk_br_pol_act_actor_ck",
                    ),
                ],
            },
        ),
    ]
