# Generated by Django 5.2.12 on 2026-08-05 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_canonical_portfolio_snapshot_and_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernedOptimizationResearchResultModel",
            fields=[
                ("result_id", models.CharField(max_length=80, primary_key=True, serialize=False)),
                ("result_version", models.CharField(max_length=128)),
                ("run_key", models.CharField(max_length=160)),
                ("run_version", models.CharField(max_length=128)),
                ("assembly_hash", models.CharField(max_length=64)),
                ("problem_id", models.CharField(db_index=True, max_length=192)),
                ("problem_hash", models.CharField(max_length=64)),
                ("input_set_id", models.CharField(db_index=True, max_length=192)),
                ("input_set_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("blocked", "Blocked"), ("completed", "Completed")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("selected_candidate", models.CharField(blank=True, default="", max_length=32)),
                ("candidates", models.JSONField(blank=True, default=list)),
                ("problem_blockers", models.JSONField(blank=True, default=list)),
                ("evaluated_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "portfolio_governed_optimization_result",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["status", "-evaluated_at"], name="pf_opt_result_status_eval_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_key", "run_version"), name="pf_opt_result_run_ver_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("valid_until__gt", models.F("evaluated_at"))),
                        name="pf_opt_result_valid_eval_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="pf_opt_result_research_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OptimizationResearchLifecycleEventModel",
            fields=[
                ("event_id", models.CharField(max_length=80, primary_key=True, serialize=False)),
                ("result_hash", models.CharField(max_length=64)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("recorded", "Recorded"),
                            ("promotion_attested", "Promotion attested"),
                            ("retired", "Retired"),
                            ("rolled_back", "Rolled back"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("recorded_at", models.DateTimeField()),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("previous_event_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("promotion_attestation", models.JSONField(blank=True, null=True)),
                ("owner_attestation", models.JSONField(blank=True, null=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_events",
                        to="portfolio.governedoptimizationresearchresultmodel",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_optimization_lifecycle_event",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(fields=["result", "sequence"], name="pf_opt_lc_result_seq_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("result", "sequence"), name="pf_opt_lc_result_seq_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)), name="pf_opt_lc_seq_pos_ck"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("recorded_at__gte", models.F("occurred_at"))),
                        name="pf_opt_lc_record_time_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("event_type", "recorded"),
                                ("owner_attestation__isnull", True),
                                ("previous_event_hash__isnull", True),
                                ("promotion_attestation__isnull", True),
                                ("sequence", 1),
                            ),
                            models.Q(
                                ("event_type", "promotion_attested"),
                                ("owner_attestation__isnull", True),
                                ("previous_event_hash__isnull", False),
                                ("promotion_attestation__isnull", False),
                                ("sequence__gt", 1),
                            ),
                            models.Q(
                                ("event_type__in", ["retired", "rolled_back"]),
                                ("owner_attestation__isnull", False),
                                ("previous_event_hash__isnull", False),
                                ("promotion_attestation__isnull", True),
                                ("sequence__gt", 1),
                            ),
                            _connector="OR",
                        ),
                        name="pf_opt_lc_shape_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="pf_opt_lc_research_ck",
                    ),
                ],
            },
        ),
    ]
