# Generated by Django 5.2.12 on 2026-08-06 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_governed_optimization_research_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="R4RollingResearchReceiptModel",
            fields=[
                (
                    "receipt_id",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("record_version", models.CharField(max_length=80)),
                ("study_id", models.CharField(max_length=200)),
                ("study_version", models.CharField(max_length=128)),
                ("study_content_hash", models.CharField(max_length=64)),
                ("r3_promotion_attestation_hash", models.CharField(max_length=64)),
                ("split_contract_hash", models.CharField(max_length=64)),
                ("evaluated_at", models.DateTimeField(db_index=True)),
                ("owner", models.CharField(default="portfolio", max_length=32)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("producer_code_version", models.CharField(max_length=200)),
                ("dependency_lock_hash", models.CharField(max_length=64)),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("study_payload", models.JSONField()),
                ("promotion_attestation_payload", models.JSONField()),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "portfolio_r4_rolling_research_receipt",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["study_id", "-evaluated_at"],
                        name="pf_r4_receipt_study_eval_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "study_id",
                            "study_version",
                            "evaluated_at",
                            "producer_code_version",
                            "dependency_lock_hash",
                        ),
                        name="pf_r4_receipt_identity_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("recorded_at__gte", models.F("evaluated_at"))),
                        name="pf_r4_receipt_eval_record_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("valid_until__gt", models.F("recorded_at"))),
                        name="pf_r4_receipt_record_valid_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("owner", "portfolio")),
                        name="pf_r4_receipt_owner_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R4RollingResearchResultModel",
            fields=[
                (
                    "record_id",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("artifact_hash", models.CharField(db_index=True, max_length=64)),
                ("evidence_complete", models.BooleanField()),
                ("eligible_for_research_comparison", models.BooleanField()),
                ("subhashes", models.JSONField(default=list)),
                ("artifact_payload", models.JSONField()),
                ("record_hash", models.CharField(max_length=64, unique=True)),
                (
                    "usage_scope",
                    models.CharField(default="research_only", max_length=32),
                ),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="portfolio.r4rollingresearchreceiptmodel",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_r4_rolling_research_result",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("receipt",),
                        name="pf_r4_result_receipt_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("eligible_for_research_comparison", False),
                            ("evidence_complete", True),
                            _connector="OR",
                        ),
                        name="pf_r4_result_eligible_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_use_for_decision", True),
                            ("usage_scope", "research_only"),
                        ),
                        name="pf_r4_result_research_ck",
                    ),
                ],
            },
        ),
    ]
