# Generated by Django 5.2.12 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_r4_rolling_research_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioR5RelativeValueOutcomeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("outcome_id", models.CharField(max_length=192)),
                ("outcome_version", models.CharField(max_length=96)),
                ("owner", models.CharField(default="portfolio", max_length=32)),
                ("owner_record_id", models.CharField(max_length=300)),
                ("owner_record_version", models.CharField(max_length=300)),
                ("owner_record_hash", models.CharField(max_length=64)),
                ("observation_id", models.CharField(max_length=300)),
                ("fixed_income_result_id", models.CharField(max_length=192)),
                ("fixed_income_result_version", models.CharField(max_length=96)),
                ("fixed_income_result_record_hash", models.CharField(max_length=64)),
                ("fixed_income_owner_seal_hash", models.CharField(max_length=64)),
                ("selection_as_of", models.DateTimeField(db_index=True)),
                ("outcome_observed_at", models.DateTimeField(db_index=True)),
                ("outcome_available_at", models.DateTimeField(db_index=True)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                (
                    "target_gross_return",
                    models.DecimalField(decimal_places=18, max_digits=38),
                ),
                ("target_cost", models.DecimalField(decimal_places=18, max_digits=38)),
                (
                    "benchmark_gross_return",
                    models.DecimalField(decimal_places=18, max_digits=38),
                ),
                (
                    "benchmark_cost",
                    models.DecimalField(decimal_places=18, max_digits=38),
                ),
                (
                    "target_maximum_drawdown",
                    models.DecimalField(decimal_places=18, max_digits=38),
                ),
                (
                    "benchmark_maximum_drawdown",
                    models.DecimalField(decimal_places=18, max_digits=38),
                ),
                (
                    "capacity_utilization",
                    models.DecimalField(decimal_places=18, max_digits=38),
                ),
                ("liquidity_breached", models.BooleanField()),
                (
                    "realized_credit_loss",
                    models.DecimalField(decimal_places=18, max_digits=38),
                ),
                ("command_hash", models.CharField(max_length=64)),
                ("draft_hash", models.CharField(max_length=64)),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "portfolio_r5_relative_value_outcome",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["owner_record_id", "owner_record_version"],
                        name="pf_r5_outcome_owner_idx",
                    ),
                    models.Index(
                        fields=["fixed_income_result_id", "fixed_income_result_version"],
                        name="pf_r5_outcome_fi_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("outcome_id", "outcome_version"),
                        name="pf_r5_outcome_identity_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("owner_record_id", "owner_record_version"),
                        name="pf_r5_outcome_owner_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("observation_id",),
                        name="pf_r5_outcome_observation_uq",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(("outcome_observed_at__gt", models.F("selection_as_of")))
                            & models.Q(
                                ("outcome_available_at__gte", models.F("outcome_observed_at"))
                            )
                            & models.Q(("recorded_at__gte", models.F("outcome_available_at")))
                            & models.Q(("valid_until__gt", models.F("recorded_at")))
                        ),
                        name="pf_r5_outcome_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_use_for_decision", True),
                            ("owner", "portfolio"),
                            ("research_only", True),
                        ),
                        name="pf_r5_outcome_safety_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(("target_cost__gte", 0))
                            & models.Q(("benchmark_cost__gte", 0))
                            & models.Q(("capacity_utilization__gte", 0))
                            & models.Q(("realized_credit_loss__gte", 0))
                        ),
                        name="pf_r5_outcome_nonneg_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(("target_maximum_drawdown__gte", 0))
                            & models.Q(("target_maximum_drawdown__lte", 1))
                            & models.Q(("benchmark_maximum_drawdown__gte", 0))
                            & models.Q(("benchmark_maximum_drawdown__lte", 1))
                        ),
                        name="pf_r5_outcome_drawdown_ck",
                    ),
                ],
            },
        ),
    ]
