# Generated by Django 5.2.12 on 2026-08-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_r5_relative_value_outcome_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernedOptimizationInputReceiptModel",
            fields=[
                (
                    "receipt_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("receipt_version", models.CharField(max_length=80)),
                ("owner", models.CharField(default="portfolio", max_length=32)),
                ("input_set_id", models.CharField(max_length=192, unique=True)),
                ("input_set_version", models.CharField(max_length=128)),
                ("contract_version", models.CharField(max_length=128)),
                ("input_set_hash", models.CharField(max_length=64, unique=True)),
                ("portfolio_snapshot_id", models.CharField(max_length=192)),
                ("portfolio_snapshot_hash", models.CharField(max_length=64)),
                ("universe_hash", models.CharField(max_length=64)),
                ("evidence_graph_hash", models.CharField(max_length=64)),
                ("pit_manifest_set_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("payload_count", models.PositiveSmallIntegerField()),
                ("owner_binding_count", models.PositiveSmallIntegerField()),
                ("promotion_count", models.PositiveSmallIntegerField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "portfolio_governed_optimization_input_receipt",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["input_set_id", "recorded_at", "valid_until"],
                        name="pf_opt_receipt_pit_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(("recorded_at__gte", models.F("created_at")))
                            & models.Q(("valid_until__gt", models.F("recorded_at")))
                        ),
                        name="pf_opt_receipt_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_use_for_decision", True),
                            ("owner", "portfolio"),
                            ("owner_binding_count", 13),
                            ("payload_count", 13),
                            ("promotion_count", 3),
                            ("research_only", True),
                        ),
                        name="pf_opt_receipt_safety_ck",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="governedoptimizationresearchresultmodel",
            name="input_receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="research_results",
                to="portfolio.governedoptimizationinputreceiptmodel",
            ),
        ),
    ]
