# Generated by Django 5.2.12 on 2026-08-09

from typing import Any

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError

CANONICAL_RESULT_VERSION = "governed-optimization-result.v2"


def _lock_receipt_evidence_tables(
    Receipt: Any,
    Result: Any,
    schema_editor: Any,
) -> None:
    """Block concurrent writes until the reverse migration transaction ends."""

    connection = schema_editor.connection
    quote_name = schema_editor.quote_name
    receipt_table = quote_name(Receipt._meta.db_table)
    result_table = quote_name(Result._meta.db_table)
    with connection.cursor() as cursor:
        if connection.vendor == "postgresql":
            # Parent-before-child matches the runtime insert order and avoids a
            # receipt/result lock-order deadlock with an in-flight writer.
            cursor.execute(f"LOCK TABLE {receipt_table} IN ACCESS EXCLUSIVE MODE")
            cursor.execute(f"LOCK TABLE {result_table} IN ACCESS EXCLUSIVE MODE")
        elif connection.vendor == "sqlite":
            # SQLite has a database-level writer reservation. A zero-row UPDATE
            # acquires it inside Django's existing atomic migration transaction;
            # issuing BEGIN IMMEDIATE here would be illegal inside that atomic block.
            receipt_pk = quote_name(Receipt._meta.pk.column)
            cursor.execute(f"UPDATE {receipt_table} SET {receipt_pk} = {receipt_pk} WHERE 0")
        else:
            raise IrreversibleError(
                "Safe reversal of portfolio.0009 is supported only on PostgreSQL " "and SQLite."
            )


def refuse_receipt_evidence_loss(apps: Any, schema_editor: Any) -> None:
    """Refuse reversal before the independent receipt ledger would be dropped."""

    Receipt = apps.get_model("portfolio", "GovernedOptimizationInputReceiptModel")
    Result = apps.get_model("portfolio", "GovernedOptimizationResearchResultModel")
    _lock_receipt_evidence_tables(Receipt, Result, schema_editor)
    using = schema_editor.connection.alias
    has_receipts = Receipt.objects.using(using).exists()
    has_receipt_bound_results = (
        Result.objects.using(using)
        .filter(
            models.Q(result_version=CANONICAL_RESULT_VERSION)
            | models.Q(input_receipt_id__isnull=False)
        )
        .exists()
    )
    if has_receipts or has_receipt_bound_results:
        raise IrreversibleError(
            "Cannot reverse portfolio.0009 while governed optimization receipt "
            "evidence exists. Preserve or explicitly retire that evidence first."
        )


class Migration(migrations.Migration):

    atomic = True

    dependencies = [
        ("portfolio", "0008_r5_relative_value_outcome_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernedOptimizationInputReceiptModel",
            fields=[
                (
                    "receipt_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("receipt_version", models.CharField(max_length=80)),
                ("owner", models.CharField(default="portfolio", max_length=32)),
                ("input_set_id", models.CharField(max_length=192, unique=True)),
                ("input_set_version", models.CharField(max_length=128)),
                ("contract_version", models.CharField(max_length=128)),
                ("input_set_hash", models.CharField(max_length=64, unique=True)),
                ("portfolio_snapshot_id", models.CharField(max_length=192)),
                ("portfolio_snapshot_hash", models.CharField(max_length=64)),
                ("universe_hash", models.CharField(max_length=64)),
                ("evidence_graph_hash", models.CharField(max_length=64)),
                ("pit_manifest_set_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("payload_count", models.PositiveSmallIntegerField()),
                ("owner_binding_count", models.PositiveSmallIntegerField()),
                ("promotion_count", models.PositiveSmallIntegerField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "portfolio_governed_optimization_input_receipt",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["input_set_id", "recorded_at", "valid_until"],
                        name="pf_opt_receipt_pit_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(("recorded_at__gte", models.F("created_at")))
                            & models.Q(("valid_until__gt", models.F("recorded_at")))
                        ),
                        name="pf_opt_receipt_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_use_for_decision", True),
                            ("owner", "portfolio"),
                            ("owner_binding_count", 13),
                            ("payload_count", 13),
                            ("promotion_count", 3),
                            ("research_only", True),
                        ),
                        name="pf_opt_receipt_safety_ck",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="governedoptimizationresearchresultmodel",
            name="input_receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="research_results",
                to="portfolio.governedoptimizationinputreceiptmodel",
            ),
        ),
        migrations.RunPython(
            code=migrations.RunPython.noop,
            reverse_code=refuse_receipt_evidence_loss,
        ),
    ]
