# Generated by Django 5.2.12 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_governed_optimization_input_receipt"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="governedoptimizationresearchresultmodel",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("input_receipt__isnull", False),
                        ("result_version", "governed-optimization-result.v2"),
                    )
                    | models.Q(
                        ("input_receipt__isnull", True),
                        ("result_version", "governed-optimization-result.v1"),
                    )
                ),
                name="pf_opt_result_receipt_ver_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="governedoptimizationinputreceiptmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("receipt_version", "governed-optimization-input-receipt.v1")),
                name="pf_opt_receipt_version_ck",
            ),
        ),
    ]
