# Generated by Django 5.2.12 on 2026-08-10 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_governed_optimization_receipt_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernedOptimizationMonitoringAuditSnapshotModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_id", models.CharField(max_length=192)),
                ("snapshot_version", models.CharField(max_length=192)),
                ("as_of", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("entry_count", models.PositiveIntegerField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64)),
                ("internal_audit_only", models.BooleanField(default=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "portfolio_governed_optimization_monitoring_audit_snapshot",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["as_of", "created_at"],
                        name="pf_opt_mon_snap_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot_id", "snapshot_version"),
                        name="pf_opt_mon_snap_ident_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("as_of__lte", models.F("created_at"))),
                        name="pf_opt_mon_snap_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("internal_audit_only", True),
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="pf_opt_mon_snap_safe_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GovernedOptimizationMonitoringAssessmentModel",
            fields=[
                (
                    "assessment_id",
                    models.CharField(
                        max_length=192,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assessment_version", models.CharField(max_length=192)),
                ("result_hash", models.CharField(max_length=64)),
                ("receipt_hash", models.CharField(max_length=64)),
                ("promotion_event_id", models.CharField(max_length=192)),
                ("promotion_event_hash", models.CharField(max_length=64)),
                ("requested_policy_id", models.CharField(max_length=192)),
                ("requested_policy_version", models.CharField(max_length=192)),
                ("expected_policy_hash", models.CharField(max_length=64)),
                ("calendar_id", models.CharField(max_length=192)),
                ("calendar_version", models.CharField(max_length=192)),
                ("calendar_hash", models.CharField(max_length=64)),
                ("evaluated_at", models.DateTimeField()),
                ("latest_owner_available_at", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("ledger_header_hash", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=48)),
                ("observation_count", models.PositiveIntegerField()),
                ("observation_hashes", models.JSONField()),
                ("upstream_promotions_payload", models.JSONField()),
                ("policy_payload", models.JSONField()),
                ("calendar_payload", models.JSONField()),
                ("assessment_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("automatic_retirement", models.BooleanField(default=False)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "input_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitoring_assessment_ledgers",
                        to="portfolio.governedoptimizationinputreceiptmodel",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitoring_assessment_ledgers",
                        to="portfolio.governedoptimizationresearchresultmodel",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_governed_optimization_monitoring_assessment",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["result", "expected_policy_hash", "ledger_recorded_at"],
                        name="pf_opt_mon_asmt_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "requested_policy_id",
                            "requested_policy_version",
                            "expected_policy_hash",
                            "evaluated_at",
                        ),
                        name="pf_opt_mon_asmt_cmd_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "latest_owner_available_at__lte",
                                models.F("evaluated_at"),
                            ),
                            ("evaluated_at__lte", models.F("ledger_recorded_at")),
                        ),
                        name="pf_opt_mon_asmt_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                (
                                    "healthy",
                                    "breached",
                                    "retirement_review_required",
                                    "blocked",
                                ),
                            )
                        ),
                        name="pf_opt_mon_asmt_status_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("automatic_retirement", False),
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="pf_opt_mon_asmt_safe_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GovernedOptimizationMonitoringObservationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_id", models.CharField(max_length=192)),
                ("observation_id", models.CharField(max_length=192)),
                ("observation_version", models.CharField(max_length=192)),
                ("result_hash", models.CharField(max_length=64)),
                ("receipt_hash", models.CharField(max_length=64)),
                ("policy_id", models.CharField(max_length=192)),
                ("policy_version", models.CharField(max_length=192)),
                ("policy_hash", models.CharField(max_length=64)),
                ("calendar_id", models.CharField(max_length=192)),
                ("calendar_version", models.CharField(max_length=192)),
                ("calendar_hash", models.CharField(max_length=64)),
                ("period_id", models.CharField(max_length=192)),
                ("period_start_at", models.DateTimeField()),
                ("period_end_at", models.DateTimeField()),
                ("latest_owner_available_at", models.DateTimeField()),
                ("portfolio_evidence_payload", models.JSONField()),
                ("broker_evidence_payload", models.JSONField()),
                ("canonical_payload", models.JSONField()),
                ("domain_observation_hash", models.CharField(max_length=64)),
                ("content_hash", models.CharField(max_length=64)),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("ledger_header_hash", models.CharField(max_length=64)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "input_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitoring_observation_ledgers",
                        to="portfolio.governedoptimizationinputreceiptmodel",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitoring_observation_ledgers",
                        to="portfolio.governedoptimizationresearchresultmodel",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_governed_optimization_monitoring_observation",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["result", "policy_hash", "ledger_recorded_at"],
                        name="pf_opt_mon_obs_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assessment_id", "period_id"),
                        name="pf_opt_mon_obs_period_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_start_at__lt", models.F("period_end_at")),
                            (
                                "period_end_at__lte",
                                models.F("latest_owner_available_at"),
                            ),
                            (
                                "latest_owner_available_at__lte",
                                models.F("ledger_recorded_at"),
                            ),
                        ),
                        name="pf_opt_mon_obs_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="pf_opt_mon_obs_safe_ck",
                    ),
                ],
            },
        ),
    ]
