# Generated by Django 5.2.12 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_governed_optimization_monitoring_ledgers"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioR4MonitoringRawFactReceiptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observation_id", models.CharField(max_length=192)),
                ("observation_version", models.CharField(max_length=192)),
                ("active_decision_id", models.CharField(max_length=192)),
                ("active_decision_version", models.CharField(max_length=192)),
                ("active_decision_hash", models.CharField(max_length=64)),
                ("policy_id", models.CharField(max_length=192)),
                ("policy_version", models.CharField(max_length=192)),
                ("policy_hash", models.CharField(max_length=64)),
                ("calendar_id", models.CharField(max_length=192)),
                ("calendar_version", models.CharField(max_length=192)),
                ("calendar_hash", models.CharField(max_length=64)),
                ("period_id", models.CharField(max_length=64)),
                ("source_owner", models.CharField(default="portfolio", max_length=192)),
                ("definition_hash", models.CharField(max_length=64)),
                ("source_receipt_id", models.CharField(max_length=192)),
                ("source_receipt_version", models.CharField(max_length=192)),
                ("source_receipt_hash", models.CharField(max_length=64)),
                ("source_receipt_payload", models.JSONField()),
                ("observed_at", models.DateTimeField()),
                ("available_at", models.DateTimeField()),
                ("owner_recorded_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "portfolio_r4_monitoring_raw_fact_receipt",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["policy_id", "calendar_id", "owner_recorded_at"],
                        name="pf_r4_mon_fact_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("observation_id", "observation_version"),
                        name="pf_r4_mon_fact_ident_uq",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "active_decision_id",
                            "active_decision_version",
                            "policy_id",
                            "policy_version",
                            "calendar_id",
                            "calendar_version",
                            "period_id",
                        ),
                        name="pf_r4_mon_fact_period_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("available_at__lte", models.F("owner_recorded_at")),
                            ("observed_at__lte", models.F("available_at")),
                            ("owner_recorded_at__lt", models.F("valid_until")),
                        ),
                        name="pf_r4_mon_fact_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                            ("source_owner", "portfolio"),
                        ),
                        name="pf_r4_mon_fact_safe_ck",
                    ),
                ],
            },
        ),
    ]
