# Generated by Django 5.2.12 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the empty Portfolio R8 raw monitoring feedback registry."""

    dependencies = [("portfolio", "0014_r5_monitoring_raw_fact_registry")]

    operations = [
        migrations.CreateModel(
            name="PortfolioR8MonitoringFeedbackReceiptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback_id", models.CharField(max_length=192)),
                ("feedback_version", models.CharField(max_length=128)),
                ("feedback_hash", models.CharField(max_length=64, unique=True)),
                ("definition_version", models.CharField(max_length=128)),
                ("definition_hash", models.CharField(max_length=64, unique=True)),
                ("source_receipt_id", models.CharField(max_length=192)),
                ("source_receipt_version", models.CharField(max_length=128)),
                ("source_receipt_hash", models.CharField(max_length=64, unique=True)),
                ("source_owner", models.CharField(max_length=32)),
                ("result_id", models.CharField(max_length=192)),
                ("result_version", models.CharField(max_length=128)),
                ("result_hash", models.CharField(max_length=64)),
                ("receipt_id", models.CharField(max_length=192)),
                ("receipt_version", models.CharField(max_length=128)),
                ("receipt_hash", models.CharField(max_length=64)),
                ("calendar_id", models.CharField(max_length=192)),
                ("calendar_version", models.CharField(max_length=128)),
                ("calendar_hash", models.CharField(max_length=64)),
                ("period_id", models.CharField(max_length=192)),
                ("period_start_at", models.DateTimeField()),
                ("period_end_at", models.DateTimeField()),
                ("source_observed_at", models.DateTimeField()),
                ("source_available_at", models.DateTimeField()),
                ("source_valid_until", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                (
                    "net_realized_pnl_after_flows",
                    models.DecimalField(decimal_places=12, max_digits=38),
                ),
                (
                    "opening_portfolio_value",
                    models.DecimalField(decimal_places=12, max_digits=38),
                ),
                (
                    "maximum_peak_to_trough_loss",
                    models.DecimalField(decimal_places=12, max_digits=38),
                ),
                (
                    "peak_portfolio_value",
                    models.DecimalField(decimal_places=12, max_digits=38),
                ),
                (
                    "absolute_traded_notional",
                    models.DecimalField(decimal_places=12, max_digits=38),
                ),
                (
                    "average_portfolio_value",
                    models.DecimalField(decimal_places=12, max_digits=38),
                ),
                (
                    "liquidity_consumed_notional",
                    models.DecimalField(decimal_places=12, max_digits=38),
                ),
                (
                    "liquidity_budget_notional",
                    models.DecimalField(decimal_places=12, max_digits=38),
                ),
                (
                    "position_exposure_notional",
                    models.DecimalField(decimal_places=12, max_digits=38),
                ),
                (
                    "capacity_limit_notional",
                    models.DecimalField(decimal_places=12, max_digits=38),
                ),
                ("constraint_breach_count", models.PositiveBigIntegerField()),
                ("constraint_evaluation_count", models.PositiveBigIntegerField()),
                ("changed_label_count", models.PositiveBigIntegerField()),
                ("comparable_label_count", models.PositiveBigIntegerField()),
                (
                    "aggregate_drift_distance",
                    models.DecimalField(decimal_places=12, max_digits=38),
                ),
                (
                    "drift_normalization_bound",
                    models.DecimalField(decimal_places=12, max_digits=38),
                ),
                ("member_manifest_hash", models.CharField(max_length=64)),
                ("raw_fact_manifest_hash", models.CharField(max_length=64)),
                ("definition_payload", models.JSONField()),
                ("source_payload", models.JSONField()),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "portfolio_r8_monitoring_feedback_receipt",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=[
                            "result_id",
                            "calendar_id",
                            "period_id",
                            "ledger_recorded_at",
                        ],
                        name="port_r8_feed_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feedback_id", "feedback_version"),
                        name="port_r8_feed_id_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("source_receipt_id", "source_receipt_version"),
                        name="port_r8_feed_source_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("result_id", "calendar_id", "period_id"),
                        name="port_r8_feed_period_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_start_at__lt", models.F("period_end_at")),
                            ("source_observed_at__gte", models.F("period_start_at")),
                            ("source_observed_at__lte", models.F("period_end_at")),
                            ("source_available_at__gte", models.F("source_observed_at")),
                            ("source_available_at__lte", models.F("ledger_recorded_at")),
                            ("ledger_recorded_at__lt", models.F("source_valid_until")),
                        ),
                        name="port_r8_feed_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("opening_portfolio_value__gt", 0),
                            (
                                "net_realized_pnl_after_flows__gte",
                                models.F("opening_portfolio_value") * -1,
                            ),
                            ("maximum_peak_to_trough_loss__gte", 0),
                            ("peak_portfolio_value__gt", 0),
                            (
                                "maximum_peak_to_trough_loss__lte",
                                models.F("peak_portfolio_value"),
                            ),
                            ("absolute_traded_notional__gte", 0),
                            ("average_portfolio_value__gt", 0),
                            ("liquidity_consumed_notional__gte", 0),
                            ("liquidity_budget_notional__gt", 0),
                            ("position_exposure_notional__gte", 0),
                            ("capacity_limit_notional__gt", 0),
                            ("constraint_evaluation_count__gt", 0),
                            (
                                "constraint_breach_count__lte",
                                models.F("constraint_evaluation_count"),
                            ),
                            ("comparable_label_count__gt", 0),
                            (
                                "changed_label_count__lte",
                                models.F("comparable_label_count"),
                            ),
                            ("aggregate_drift_distance__gte", 0),
                            ("drift_normalization_bound__gt", 0),
                            (
                                "aggregate_drift_distance__lte",
                                models.F("drift_normalization_bound"),
                            ),
                        ),
                        name="port_r8_feed_raw_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "definition_version",
                                "portfolio-r8-monitoring-feedback-definition.v1",
                            ),
                            ("feedback_version", "portfolio-r8-monitoring-feedback.v1"),
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                            ("source_owner", "portfolio"),
                            (
                                "source_receipt_version",
                                "portfolio-r8-monitoring-feedback-source.v1",
                            ),
                        ),
                        name="port_r8_feed_safe_ck",
                    ),
                ],
            },
        )
    ]
