# Generated by Django 5.2.16 on 2026-08-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0023_policy_benchmark_fx_fixing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transitionplaninactiveapprovalreceiptmodel",
            name="persisted_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="transitionplaninactiveapprovalsubjectmodel",
            name="persisted_at",
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name="transitionplaninactiveapprovalreceiptmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("persisted_at", models.F("recorded_at"))),
                name="portfolio_tr_ap_rcpt_persist_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="transitionplaninactiveapprovalsubjectmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("persisted_at", models.F("recorded_at"))),
                name="portfolio_tr_ap_subj_persist_ck",
            ),
        ),
    ]
