# Generated by Django 5.2.9 on 2025-12-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("initial_capital", models.DecimalField(decimal_places=2, max_digits=20)),
                ("final_capital", models.DecimalField(decimal_places=2, max_digits=20)),
                ("total_return", models.FloatField()),
                ("annualized_return", models.FloatField()),
                ("max_drawdown", models.FloatField()),
                ("sharpe_ratio", models.FloatField()),
                ("regime_accuracy", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "backtest_result",
                "ordering": ["-created_at"],
            },
        ),
    ]
