# Generated by Django 5.2.9 on 2025-12-31 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtest", "0002_backtestresultmodel_backtesttrademodel_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestresultmodel",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="NULL表示系统/测试数据",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backtests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建用户",
            ),
        ),
    ]
