# Generated by Django 5.2.9 on 2026-01-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtest", "0003_backtestresultmodel_user"),
        ("signal", "0004_investmentsignalmodel_avg_backtest_return_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestresultmodel",
            name="signal_configs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="记录每个信号的配置参数，如权重、准入条件等",
                verbose_name="信号配置",
            ),
        ),
        migrations.AddField(
            model_name="backtestresultmodel",
            name="used_signals",
            field=models.ManyToManyField(
                blank=True,
                help_text="记录回测使用了哪些投资信号",
                related_name="backtests",
                to="signal.investmentsignalmodel",
                verbose_name="使用的信号",
            ),
        ),
    ]
