# Generated by Django 5.2.10 on 2026-02-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoringWeightConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="配置名称")),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, verbose_name="配置描述"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("growth_weight", models.FloatField(default=0.4, verbose_name="成长性评分权重")),
                (
                    "profitability_weight",
                    models.FloatField(default=0.4, verbose_name="盈利能力评分权重"),
                ),
                ("valuation_weight", models.FloatField(default=0.2, verbose_name="估值评分权重")),
                (
                    "revenue_growth_weight",
                    models.FloatField(default=0.5, verbose_name="营收增长率权重"),
                ),
                (
                    "profit_growth_weight",
                    models.FloatField(default=0.5, verbose_name="净利润增长率权重"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "股票评分权重配置",
                "verbose_name_plural": "股票评分权重配置",
                "db_table": "equity_scoring_weight_config",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
    ]
