# Generated by Django 5.2.10 on 2026-03-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equity", "0004_valuation_repair_tracking"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="valuationrepairtrackingmodel",
            new_name="equity_valu_source__ea3d60_idx",
            old_name="equity_valu_source_u_idx",
        ),
        migrations.RenameIndex(
            model_name="valuationrepairtrackingmodel",
            new_name="equity_valu_source__940c19_idx",
            old_name="equity_valu_source_s_idx",
        ),
        migrations.RenameIndex(
            model_name="valuationrepairtrackingmodel",
            new_name="equity_valu_as_of_d_d1bd40_idx",
            old_name="equity_valu_as_of_d_idx",
        ),
        migrations.AlterUniqueTogether(
            name="valuationrepairtrackingmodel",
            unique_together={("stock_code", "source_universe")},
        ),
    ]
