# Generated by Django 5.2.8 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equity", "0010_operating_forecast_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatingforecastassumptionmodel",
            name="observed_metric_role",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="operatingforecastevaluationmodel",
            name="subject_code",
            field=models.CharField(default="", max_length=80),
            preserve_default=False,
        ),
    ]
