# Generated by Django 5.2.12 on 2026-08-05 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equity", "0012_industry_template_forecast_bridge"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastBaselineApprovalEvidenceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("approval_id", models.CharField(max_length=192)),
                ("approval_version", models.CharField(max_length=192)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("owner", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=32)),
                ("forecast_origin_at", models.DateTimeField()),
                ("approved_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("payload_schema", models.CharField(max_length=64)),
                ("canonical_payload", models.JSONField()),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("recorded_at", models.DateTimeField(editable=False)),
            ],
            options={
                "db_table": "equity_forecast_baseline_approval_evidence",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["status", "approved_at", "valid_until"],
                        name="eq_fb_approval_active_ix",
                    ),
                    models.Index(fields=["forecast_origin_at"], name="eq_fb_approval_origin_ix"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("approval_id", "approval_version"),
                        name="eq_fb_approval_identity_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("owner", "equity"), ("status", "approved")),
                        name="eq_fb_approval_authority_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__gt", models.F("approved_at")),
                            ("recorded_at__gte", models.F("approved_at")),
                            ("recorded_at__lte", models.F("forecast_origin_at")),
                            ("forecast_origin_at__gte", models.F("approved_at")),
                            ("forecast_origin_at__lt", models.F("valid_until")),
                        ),
                        name="eq_fb_approval_time_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("research_only", True),
                            ("must_not_use_for_decision", True),
                            ("must_not_execute", True),
                        ),
                        name="eq_fb_approval_research_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("content_hash__regex", "^[0-9a-f]{64}$")),
                        name="eq_fb_approval_hash_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("canonical_payload", {}), _negated=True),
                        name="eq_fb_approval_payload_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ForecastBaselineSpecModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("spec_id", models.CharField(max_length=192)),
                ("spec_version", models.CharField(max_length=192)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("owner", models.CharField(max_length=32)),
                ("approval_evidence_id", models.CharField(max_length=192)),
                ("approval_evidence_version", models.CharField(max_length=192)),
                ("approval_evidence_content_hash", models.CharField(max_length=64)),
                ("approval_recorded_at", models.DateTimeField()),
                ("forecast_origin_at", models.DateTimeField()),
                ("approved_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("payload_schema", models.CharField(max_length=64)),
                ("canonical_payload", models.JSONField()),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spec_records",
                        to="equity.forecastbaselineapprovalevidencemodel",
                    ),
                ),
            ],
            options={
                "db_table": "equity_forecast_baseline_spec",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="ForecastBaselineArtifactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("artifact_id", models.CharField(max_length=192)),
                ("artifact_version", models.CharField(max_length=192)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("owner", models.CharField(max_length=32)),
                ("spec_evidence_id", models.CharField(max_length=192)),
                ("spec_evidence_version", models.CharField(max_length=192)),
                ("spec_evidence_content_hash", models.CharField(max_length=64)),
                ("knowledge_as_of", models.DateTimeField()),
                ("produced_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("payload_schema", models.CharField(max_length=64)),
                ("canonical_payload", models.JSONField()),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifact_records",
                        to="equity.forecastbaselinespecmodel",
                    ),
                ),
            ],
            options={
                "db_table": "equity_forecast_baseline_artifact",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="ForecastBaselineTrialResultModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("result_id", models.CharField(max_length=192)),
                ("result_version", models.CharField(max_length=192)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("owner", models.CharField(max_length=32)),
                ("spec_evidence_id", models.CharField(max_length=192)),
                ("spec_evidence_version", models.CharField(max_length=192)),
                ("spec_evidence_content_hash", models.CharField(max_length=64)),
                ("artifact_evidence_id", models.CharField(max_length=192)),
                ("artifact_evidence_version", models.CharField(max_length=192)),
                ("artifact_evidence_content_hash", models.CharField(max_length=64)),
                ("actual_manifest_id", models.CharField(max_length=192)),
                ("actual_manifest_version", models.CharField(max_length=192)),
                ("actual_manifest_content_hash", models.CharField(max_length=64)),
                ("research_trial_id", models.CharField(max_length=192)),
                ("research_trial_version", models.CharField(max_length=192)),
                ("research_trial_content_hash", models.CharField(max_length=64)),
                ("evaluated_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("payload_schema", models.CharField(max_length=64)),
                ("canonical_payload", models.JSONField()),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trial_records",
                        to="equity.forecastbaselineartifactmodel",
                    ),
                ),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trial_records",
                        to="equity.forecastbaselinespecmodel",
                    ),
                ),
            ],
            options={
                "db_table": "equity_forecast_baseline_trial_result",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AddIndex(
            model_name="forecastbaselinespecmodel",
            index=models.Index(
                fields=["approval_evidence_id", "approval_evidence_version"],
                name="eq_fb_spec_approval_ix",
            ),
        ),
        migrations.AddIndex(
            model_name="forecastbaselinespecmodel",
            index=models.Index(fields=["forecast_origin_at"], name="eq_fb_spec_origin_ix"),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselinespecmodel",
            constraint=models.UniqueConstraint(
                fields=("spec_id", "spec_version"), name="eq_fb_spec_identity_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselinespecmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("owner", "equity")), name="eq_fb_spec_owner_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselinespecmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__gt", models.F("approved_at")),
                    ("approval_recorded_at__gte", models.F("approved_at")),
                    ("approval_recorded_at__lte", models.F("forecast_origin_at")),
                    ("forecast_origin_at__gte", models.F("approved_at")),
                    ("forecast_origin_at__lt", models.F("valid_until")),
                ),
                name="eq_fb_spec_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselinespecmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("research_only", True),
                    ("must_not_use_for_decision", True),
                    ("must_not_execute", True),
                ),
                name="eq_fb_spec_research_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselinespecmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[0-9a-f]{64}$")),
                name="eq_fb_spec_hash_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselinespecmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical_payload", {}), _negated=True),
                name="eq_fb_spec_payload_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="forecastbaselineartifactmodel",
            index=models.Index(
                fields=["spec_evidence_id", "spec_evidence_version"], name="eq_fb_artifact_spec_ix"
            ),
        ),
        migrations.AddIndex(
            model_name="forecastbaselineartifactmodel",
            index=models.Index(fields=["knowledge_as_of"], name="eq_fb_artifact_asof_ix"),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselineartifactmodel",
            constraint=models.UniqueConstraint(
                fields=("artifact_id", "artifact_version"), name="eq_fb_artifact_identity_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselineartifactmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("owner", "equity")), name="eq_fb_artifact_owner_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselineartifactmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("knowledge_as_of__lte", models.F("produced_at")),
                    ("produced_at__lt", models.F("valid_until")),
                ),
                name="eq_fb_artifact_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselineartifactmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("research_only", True),
                    ("must_not_use_for_decision", True),
                    ("must_not_execute", True),
                ),
                name="eq_fb_artifact_research_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselineartifactmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[0-9a-f]{64}$")),
                name="eq_fb_artifact_hash_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselineartifactmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical_payload", {}), _negated=True),
                name="eq_fb_artifact_payload_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="forecastbaselinetrialresultmodel",
            index=models.Index(
                fields=["research_trial_id", "research_trial_version"],
                name="eq_fb_trial_research_ix",
            ),
        ),
        migrations.AddIndex(
            model_name="forecastbaselinetrialresultmodel",
            index=models.Index(
                fields=["actual_manifest_id", "actual_manifest_version"],
                name="eq_fb_trial_actual_ix",
            ),
        ),
        migrations.AddIndex(
            model_name="forecastbaselinetrialresultmodel",
            index=models.Index(fields=["evaluated_at"], name="eq_fb_trial_eval_ix"),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselinetrialresultmodel",
            constraint=models.UniqueConstraint(
                fields=("result_id", "result_version"), name="eq_fb_trial_identity_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselinetrialresultmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("owner", "equity")), name="eq_fb_trial_owner_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselinetrialresultmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("valid_until__gt", models.F("evaluated_at"))),
                name="eq_fb_trial_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselinetrialresultmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("research_only", True),
                    ("must_not_use_for_decision", True),
                    ("must_not_execute", True),
                ),
                name="eq_fb_trial_research_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselinetrialresultmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("content_hash__regex", "^[0-9a-f]{64}$")),
                name="eq_fb_trial_hash_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastbaselinetrialresultmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("canonical_payload", {}), _negated=True),
                name="eq_fb_trial_payload_ck",
            ),
        ),
    ]
