# Generated by Django 5.2.9 on 2026-01-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_systemsettingsmodel_and_more"),
        ("simulated_trading", "0004_simulatedaccountmodel_active_strategy_and_more"),
        ("strategy", "0002_fix_ai_provider_reference"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="portfoliostrategyassignmentmodel",
            index=models.Index(
                fields=["portfolio", "is_active"], name="portfolio_s_portfol_55e41a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfoliostrategyassignmentmodel",
            index=models.Index(
                fields=["strategy", "is_active"], name="portfolio_s_strateg_95157f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ruleconditionmodel",
            index=models.Index(
                fields=["strategy", "-priority"], name="rule_condit_strateg_a5a77e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ruleconditionmodel",
            index=models.Index(
                fields=["rule_type", "is_enabled"], name="rule_condit_rule_ty_f5fbad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="strategyexecutionlogmodel",
            index=models.Index(
                fields=["strategy", "-execution_time"], name="strategy_ex_strateg_d8ac67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="strategyexecutionlogmodel",
            index=models.Index(
                fields=["portfolio", "-execution_time"], name="strategy_ex_portfol_a15c5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="strategyexecutionlogmodel",
            index=models.Index(
                fields=["is_success", "-execution_time"], name="strategy_ex_is_succ_a50ee7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="strategymodel",
            index=models.Index(
                fields=["strategy_type", "is_active"], name="strategy_strateg_5e640e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="strategymodel",
            index=models.Index(
                fields=["created_by", "-created_at"], name="strategy_created_f3b40d_idx"
            ),
        ),
    ]
