# Generated by Django 5.2.10 on 2026-03-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0006_orderintentmodel"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="orderintentmodel",
            new_name="order_inten_portfol_c5915a_idx",
            old_name="order_inten_portfol_aeab65_idx",
        ),
        migrations.RenameIndex(
            model_name="orderintentmodel",
            new_name="order_inten_strateg_ba47e5_idx",
            old_name="order_inten_strateg_2ae2f2_idx",
        ),
        migrations.RenameIndex(
            model_name="orderintentmodel",
            new_name="order_inten_symbol_1cccbc_idx",
            old_name="order_inten_symbol_0872b3_idx",
        ),
    ]
