# Generated by Django 5.2.12 on 2026-07-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0033_require_explicit_minimum_commission"),
        ("ai_provider", "0004_aiuserfallbackquota_aiproviderconfig_owner_user_and_more"),
        ("prompt", "0002_prompt_evaluation_gate"),
        ("simulated_trading", "0020_enforce_fee_config_invariants"),
        ("strategy", "0010_transfer_order_intent_state"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="aistrategyconfigmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("temperature__gte", 0),
                    ("temperature__lte", 2),
                    ("max_tokens__gte", 1),
                    ("confidence_threshold__gte", 0),
                    ("confidence_threshold__lte", 1),
                ),
                name="ai_strategy_numeric_ranges",
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliostrategyassignmentmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("override_max_position_pct__isnull", True),
                        models.Q(
                            ("override_max_position_pct__gte", 0),
                            ("override_max_position_pct__lte", 100),
                        ),
                        _connector="OR",
                    ),
                    models.Q(
                        ("override_stop_loss_pct__isnull", True),
                        models.Q(
                            ("override_stop_loss_pct__gte", 0), ("override_stop_loss_pct__lte", 100)
                        ),
                        _connector="OR",
                    ),
                ),
                name="portfolio_strategy_pct_ranges",
            ),
        ),
        migrations.AddConstraint(
            model_name="positionmanagementrulemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_precision__lte", 8)),
                name="position_rule_precision_lte_8",
            ),
        ),
        migrations.AddConstraint(
            model_name="ruleconditionmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("weight__isnull", True),
                    models.Q(("weight__gte", 0), ("weight__lte", 1)),
                    _connector="OR",
                ),
                name="rule_condition_weight_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="strategyexecutionlogmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("execution_duration_ms__gte", 0)),
                name="strategy_execution_duration_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="strategymodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_position_pct__gte", 0),
                    ("max_position_pct__lte", 100),
                    ("max_total_position_pct__gte", 0),
                    ("max_total_position_pct__lte", 100),
                    models.Q(
                        ("stop_loss_pct__isnull", True),
                        models.Q(("stop_loss_pct__gte", 0), ("stop_loss_pct__lte", 100)),
                        _connector="OR",
                    ),
                ),
                name="strategy_risk_pct_ranges",
            ),
        ),
    ]
