# Generated by Django 5.2.12 on 2026-08-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0036_assetcategorymodel_account_asset_category_level_positive_and_more",
        ),
        ("strategy", "0011_enforce_strategy_numeric_invariants"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationPolicyVersionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_key",
                    models.CharField(db_index=True, max_length=96, verbose_name="配置标识"),
                ),
                ("version", models.PositiveIntegerField(verbose_name="版本号")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "已激活"),
                            ("superseded", "已替代"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(db_index=True, max_length=64, verbose_name="内容哈希"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("legacy_code_migration", "旧代码迁移"),
                            ("human", "人工配置"),
                            ("approved_research", "已批准研究"),
                            ("rollback", "回滚副本"),
                        ],
                        max_length=32,
                        verbose_name="来源类型",
                    ),
                ),
                (
                    "source_metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="来源元数据"),
                ),
                ("change_reason", models.TextField(verbose_name="变更原因")),
                (
                    "based_on_version",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="基于版本"),
                ),
                (
                    "effective_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="生效时间"),
                ),
                (
                    "activated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="激活时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activated_allocation_policy_versions",
                        to="account.accountprofilemodel",
                        verbose_name="激活者",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_allocation_policy_versions",
                        to="account.accountprofilemodel",
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产配置策略版本",
                "verbose_name_plural": "资产配置策略版本",
                "db_table": "strategy_allocation_policy_version",
                "ordering": ["policy_key", "-version"],
            },
        ),
        migrations.CreateModel(
            name="AllocationPolicyEntryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regime", models.CharField(max_length=24, verbose_name="Regime")),
                (
                    "risk_profile",
                    models.CharField(max_length=24, verbose_name="风险偏好"),
                ),
                (
                    "equity",
                    models.DecimalField(decimal_places=6, max_digits=9, verbose_name="权益权重"),
                ),
                (
                    "fixed_income",
                    models.DecimalField(decimal_places=6, max_digits=9, verbose_name="固收权重"),
                ),
                (
                    "commodity",
                    models.DecimalField(decimal_places=6, max_digits=9, verbose_name="商品权重"),
                ),
                (
                    "cash",
                    models.DecimalField(decimal_places=6, max_digits=9, verbose_name="现金权重"),
                ),
                ("reasoning", models.TextField(verbose_name="配置理由")),
                (
                    "expected_return",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=12,
                        null=True,
                        verbose_name="预期年化收益",
                    ),
                ),
                (
                    "expected_volatility",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=12,
                        null=True,
                        verbose_name="预期波动率",
                    ),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=12,
                        null=True,
                        verbose_name="夏普比率",
                    ),
                ),
                (
                    "statistics_status",
                    models.CharField(
                        choices=[
                            ("legacy_unverified", "旧值未验证"),
                            ("human_assumption", "人工假设"),
                            ("approved_research", "已批准研究"),
                            ("not_provided", "未提供"),
                        ],
                        default="not_provided",
                        max_length=32,
                        verbose_name="统计假设状态",
                    ),
                ),
                (
                    "research_evidence_id",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="研究证据 ID",
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="strategy.allocationpolicyversionmodel",
                        verbose_name="策略版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产配置策略矩阵项",
                "verbose_name_plural": "资产配置策略矩阵项",
                "db_table": "strategy_allocation_policy_entry",
                "ordering": ["regime", "risk_profile"],
            },
        ),
        migrations.CreateModel(
            name="AllocationPolicyAdjustmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_level",
                    models.CharField(max_length=8, verbose_name="Policy 档位"),
                ),
                (
                    "equity_multiplier",
                    models.DecimalField(decimal_places=6, max_digits=9, verbose_name="权益乘数"),
                ),
                (
                    "expected_return_multiplier",
                    models.DecimalField(
                        decimal_places=6,
                        default=1,
                        max_digits=9,
                        verbose_name="预期收益乘数",
                    ),
                ),
                (
                    "expected_volatility_multiplier",
                    models.DecimalField(
                        decimal_places=6,
                        default=1,
                        max_digits=9,
                        verbose_name="预期波动乘数",
                    ),
                ),
                (
                    "sharpe_multiplier",
                    models.DecimalField(
                        decimal_places=6,
                        default=1,
                        max_digits=9,
                        verbose_name="Sharpe 乘数",
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="strategy.allocationpolicyversionmodel",
                        verbose_name="策略版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产配置 Policy 调整",
                "verbose_name_plural": "资产配置 Policy 调整",
                "db_table": "strategy_allocation_policy_adjustment",
                "ordering": ["policy_level"],
            },
        ),
        migrations.AddIndex(
            model_name="allocationpolicyversionmodel",
            index=models.Index(
                fields=["policy_key", "status"], name="strategy_al_policy__6a7273_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="allocationpolicyversionmodel",
            index=models.Index(
                fields=["policy_key", "-version"], name="strategy_al_policy__3dfd78_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationpolicyversionmodel",
            constraint=models.UniqueConstraint(
                fields=("policy_key", "version"),
                name="strategy_alloc_policy_key_version_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationpolicyversionmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("policy_key",),
                name="strategy_alloc_policy_single_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationpolicyversionmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gt", 0)),
                name="strategy_alloc_policy_version_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationpolicyentrymodel",
            constraint=models.UniqueConstraint(
                fields=("policy_version", "regime", "risk_profile"),
                name="strategy_alloc_policy_entry_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationpolicyentrymodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("equity__gte", 0),
                    ("equity__lte", 1),
                    ("fixed_income__gte", 0),
                    ("fixed_income__lte", 1),
                    ("commodity__gte", 0),
                    ("commodity__lte", 1),
                    ("cash__gte", 0),
                    ("cash__lte", 1),
                ),
                name="strategy_alloc_policy_weight_ranges",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationpolicyentrymodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expected_volatility__isnull", True),
                    ("expected_volatility__gte", 0),
                    _connector="OR",
                ),
                name="strategy_alloc_policy_volatility_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationpolicyadjustmentmodel",
            constraint=models.UniqueConstraint(
                fields=("policy_version", "policy_level"),
                name="strategy_alloc_policy_adjustment_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationpolicyadjustmentmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("equity_multiplier__gte", 0),
                    ("equity_multiplier__lte", 1),
                    ("expected_return_multiplier__gte", 0),
                    ("expected_volatility_multiplier__gte", 0),
                    ("sharpe_multiplier__gte", 0),
                ),
                name="strategy_alloc_policy_multiplier_ranges",
            ),
        ),
    ]
