# ruff: noqa: F403, F405
"""Split tests from test_core_registry.py: foundation."""

from .core_registry_support import *


def test_core_registry_loader_loads_seed_manifests():
    loader = CapabilityRegistryLoader()

    registry = loader.build_registry()

    assert "system.read.regime.current" in registry
    assert "regime.read.history" in registry
    assert "system.read.policy.status" in registry
    assert "policy.read.events" in registry
    assert "policy.read.workbench.bootstrap" in registry
    assert "policy.read.workbench.summary" in registry
    assert "policy.read.workbench.event_detail" in registry
    assert "policy.read.workbench.items" in registry
    assert "policy.read.sentiment_gate.state" in registry
    assert "system.read.task_monitor.statistics" in registry
    assert "task_monitor.read.task_status" in registry
    assert "task_monitor.read.task_list" in registry
    assert "data_center.read.provider_status" in registry
    assert "data_center.read.provider_catalog" in registry
    assert "data_center.read.macro_series" in registry
    assert "data_center.read.indicator_catalog" in registry
    assert "pulse.read.current" in registry
    assert "pulse.read.history" in registry
    assert "regime.read.navigator" in registry
    assert "regime.read.distribution" in registry
    assert "regime.compute.calculate" in registry
    assert "ai_provider.read.provider_catalog" in registry
    assert "ai_provider.read.provider_detail" in registry
    assert "ai_provider.read.usage_logs" in registry
    assert "filter.read.indicator_catalog" in registry
    assert "filter.read.config_detail" in registry
    assert "prompt.read.template_catalog" in registry
    assert "prompt.read.chain_catalog" in registry
    assert "dashboard.read.alpha_history" in registry
    assert "dashboard.read.alpha_history_detail" in registry
    assert "risk_center.read.floor" in registry
    assert "risk_center.read.template_catalog" in registry
    assert "risk_center.read.effective_policy" in registry
    assert "risk_center.read.account_policy" in registry
    assert "risk_center.read.exception_list" in registry
    assert "risk_center.read.pre_trade_check" in registry
    assert "risk_center.read.post_investment_check" in registry
    assert "risk_center.read.daily_report" in registry
    assert "risk_center.read.daily_report_history" in registry
    assert "task_monitor.read.dashboard" in registry
    assert "task_monitor.read.celery_health" in registry
    assert "signal.read.list" in registry
    assert "signal.read.detail" in registry
    assert "signal.check.eligibility" in registry
    assert "realtime.read.price" in registry
    assert "realtime.read.price_batch" in registry
    assert "data_center.read.price_history" in registry
    assert "realtime.read.market_summary" in registry
    assert "data_center.read.latest_quote" in registry
    assert "data_center.read.news" in registry
    assert "data_center.read.capital_flows" in registry
    assert "data_center.read.publisher_detail" in registry
    assert "data_center.read.publisher_catalog" in registry
    assert "data_center.read.indicator_detail" in registry
    assert "data_center.read.indicator_unit_rules" in registry
    assert "data_center.read.indicator_unit_rule_detail" in registry
    assert "account.read.macro_sizing_config" in registry
    assert "account.read.positions" in registry
    assert "account.read.portfolio_catalog" in registry
    assert "account.read.portfolio_detail" in registry
    assert "account.read.position_records" in registry
    assert "account.read.transaction_records" in registry
    assert "account.read.capital_flow_records" in registry
    assert "account.read.portfolio_statistics" in registry
    assert "account.read.trading_cost_configs" in registry
    assert "account.calculate.trading_cost" in registry
    assert "account.read.account_list" in registry
    assert "account.read.account_detail" in registry
    assert "account.read.account_positions" in registry
    assert "account.read.account_performance" in registry
    assert "simulated_trading.read.daily_inspection_list" in registry
    assert "hedge.compute.correlation_matrix" in registry
    assert "hedge.read.pair_catalog" in registry
    assert "hedge.read.pair_detail" in registry
    assert "hedge.read.alert_list" in registry
    assert "hedge.read.portfolio_state" in registry
    assert "asset_analysis.read.weight_config_catalog" in registry
    assert "asset_analysis.read.current_weight" in registry
    assert "asset_analysis.read.pool_summary" in registry
    assert "equity.read.pool_catalog" in registry
    assert "equity.read.valuation_analysis" in registry
    assert "equity.read.valuation_repair_list" in registry
    assert "equity.read.valuation_freshness" in registry
    assert "equity.read.valuation_quality_latest" in registry
    assert "decision.read.advisor_sheet" in registry
    assert "dashboard.read.auto_advisor_console" in registry
    assert "dashboard.query.auto_advisor" in registry
    assert "dashboard.read.auto_advisor_weekly_report" in registry
    assert "dashboard.read.auto_advisor_weekly_report_history" in registry
    assert "dashboard.read.auto_advisor_notifications" in registry
    assert "agent_proposal.read.proposal_detail" in registry
    assert "beta_gate.read.config_catalog" in registry
    assert "beta_gate.compute.batch_evaluation" in registry
    assert "filter.read.health" in registry
    assert "sentiment.read.index" in registry
    assert "sentiment.read.recent" in registry
    assert "sentiment.read.health" in registry
    assert "events.read.query" in registry
    assert "events.read.metrics" in registry
    assert "events.read.status" in registry
    assert "audit.read.summary" in registry
    assert "audit.read.execution_links" in registry
    assert "factor.compute.top_stocks" in registry
    assert "factor.compute.stock_explanation" in registry
    assert "factor.read.definition_catalog" in registry
    assert "factor.read.config_catalog" in registry
    assert "strategy.read.catalog" in registry
    assert "strategy.read.detail" in registry
    assert "strategy.read.ai_config_catalog" in registry
    assert "strategy.read.ai_config_detail" in registry
    assert "strategy.read.position_rule_catalog" in registry
    assert "strategy.read.position_rule_detail" in registry
    assert "fund.read.ranking" in registry
    assert "fund.compute.screen" in registry
    assert "fund.read.detail" in registry
    assert "fund.read.nav_history" in registry
    assert "fund.read.holdings" in registry
    assert "backtest.read.detail" in registry
    assert "backtest.read.list" in registry
    assert "alpha.read.provider_status" in registry
    assert "alpha.read.universe_catalog" in registry
    assert "alpha.read.health" in registry
    assert "alpha.read.inference_ops_overview" in registry
    assert "alpha.read.qlib_data_ops_overview" in registry
    assert "alpha_trigger.read.trigger_list" in registry
    assert "alpha_trigger.read.candidate_list" in registry
    assert "alpha_trigger.read.candidate_detail" in registry
    assert "alpha_trigger.read.performance" in registry
    assert "decision_rhythm.read.quota_list" in registry
    assert "decision_rhythm.read.request_list" in registry
    assert "decision_rhythm.read.request_detail" in registry
    assert "decision_rhythm.read.summary" in registry
    assert "decision.read.recommendation_list" in registry
    assert "decision.read.transition_plan_detail" in registry
    assert "config_center.read.capability_catalog" in registry
    assert "config_center.read.qlib_runtime" in registry
    assert "config_center.read.qlib_training_profiles" in registry
    assert "config_center.read.alpha_universe_catalog" in registry
    assert "config_center.read.alpha_universe_members" in registry
    assert "config_center.read.qlib_training_runs" in registry
    assert "config_center.read.qlib_training_run_detail" in registry
    assert "rotation.read.regime_catalog" in registry
    assert "rotation.read.template_catalog" in registry
    assert "rotation.read.config_detail" in registry
    assert "rotation.read.account_config_list" in registry
    assert "rotation.read.account_config_detail" in registry
    assert "rotation.read.asset_catalog" in registry
    assert "rotation.read.asset_detail" in registry
    assert "rotation.read.latest_signal_list" in registry
    assert "rotation.compute.asset_comparison" in registry
    assert "decision.create.execution_request" in registry
    assert "decision.submit.request_batch" in registry
    assert "account.import.positions" in registry
    assert "account.import.transactions" in registry
    assert "account.import.capital_flows" in registry
    assert "account.import.broker_trades" in registry
    assert "beta_gate.create.config" in registry
    assert "beta_gate.compute.config_comparison" in registry
    assert "beta_gate.rollback.config" in registry
    assert "agent_proposal.create.proposal" in registry
    assert "decision.submit.request" in registry
    assert "decision.execute.request" in registry
    assert "decision.cancel.request" in registry
    assert "decision.reset.quota" in registry
    assert "policy.create.event" in registry
    assert "events.publish.event" in registry
    assert "prompt.create.template" in registry
    assert "trading.submit.simulated_order" in registry
    assert "trading.close.simulated_position" in registry
    assert "trading.reset.simulated_account" in registry
    assert "trading.delete.simulated_account" in registry
    assert "trading.delete.simulated_account_batch" in registry
    assert "trading.create.simulated_account" in registry
    assert "trading.start.simulated_auto_trading" in registry
    assert "trading.run.simulated_daily_inspection" in registry
    assert "strategy.execute.run" in registry
    assert "strategy.bind.portfolio" in registry
    assert "strategy.unbind.portfolio" in registry
    assert "rotation.create.account_config" in registry
    assert "rotation.delete.account_config" in registry
    assert "rotation.update.account_config" in registry
    assert "rotation.apply_template.account_config" in registry
    assert "strategy.create.position_rule" in registry
    assert "strategy.update.position_rule" in registry
    assert "strategy.create.ai_config" in registry
    assert "strategy.create.strategy" in registry
    assert "strategy.update.ai_config" in registry
    assert "account.create.trading_cost_config" in registry
    assert "account.update.trading_cost_config" in registry
    assert "account.update.macro_sizing_config" in registry
    assert "config_center.update.runtime_setting" in registry
    assert "config_center.create.data_center_provider" in registry
    assert "config_center.update.data_center_provider" in registry
    assert "data_center.create.publisher" in registry
    assert "data_center.delete.publisher" in registry
    assert "data_center.create.indicator" in registry
    assert "data_center.delete.indicator" in registry
    assert "data_center.create.indicator_unit_rule" in registry
    assert "data_center.delete.indicator_unit_rule" in registry
    assert "data_center.update.indicator_unit_rule" in registry
    assert "data_center.start.sync_job" in registry
    assert "data_center.update.publisher" in registry
    assert "data_center.update.indicator" in registry
    assert "filter.create.filter" in registry
    assert "ai_provider.create.provider" in registry
    assert "ai_provider.update.provider" in registry
    assert "ai_provider.toggle.provider" in registry
    assert "alpha_trigger.update.candidate_status" in registry
    assert "filter.update.filter" in registry
    assert "filter.delete.filter" in registry
    assert "policy.approve.workbench_event" in registry
    assert "policy.reject.workbench_event" in registry
    assert "policy.rollback.workbench_event" in registry
    assert "policy.override.workbench_event" in registry
    assert "agent_proposal.execute.proposal" in registry
    assert "agent_proposal.approve.proposal" in registry
    assert "agent_proposal.reject.proposal" in registry
    assert "signal.create.signal" in registry
    assert "signal.approve.signal" in registry
    assert "signal.reject.signal" in registry
    assert "signal.invalidate.signal" in registry


def test_server_registers_core_tools_by_default(core_only_mcp_server):
    tools = asyncio.run(core_only_mcp_server.list_tools())
    names = {tool.name for tool in tools}

    assert names == set(CORE_TOOL_NAMES)
    for tool_name in CORE_TOOL_NAMES:
        assert tool_name in names
