# Generated by Django 5.2.12 on 2026-08-05 11:22

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioReviewReminderModel",
            fields=[
                ("reminder_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("reminder_version", models.CharField(max_length=128)),
                ("intent_id", models.CharField(max_length=64, unique=True)),
                ("intent_version", models.CharField(max_length=128)),
                ("intent_content_hash", models.CharField(max_length=64)),
                ("forecast_entry_id", models.CharField(db_index=True, max_length=64)),
                ("forecast_group_id", models.CharField(max_length=128)),
                ("forecast_observation_hash", models.CharField(max_length=64)),
                ("probability_policy_version", models.CharField(max_length=128)),
                ("probability_policy_hash", models.CharField(max_length=64)),
                ("scenario_revision_id", models.UUIDField(db_index=True)),
                (
                    "scenario_set_revision_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("invalidation_evidence_hash", models.CharField(max_length=64)),
                ("intent_reason_code", models.CharField(max_length=128)),
                ("schedule_version", models.CharField(max_length=128)),
                ("schedule_policy_hash", models.CharField(max_length=64)),
                ("expiry_delay", models.DurationField()),
                ("escalation_delay", models.DurationField()),
                ("maximum_escalation_level", models.PositiveSmallIntegerField()),
                ("path_horizon_periods", models.PositiveSmallIntegerField()),
                ("owner_evidence_hash", models.CharField(max_length=64)),
                ("escalation_policy_version", models.CharField(max_length=128)),
                ("escalation_policy_hash", models.CharField(max_length=64)),
                ("path_evidence_hash", models.CharField(max_length=64)),
                ("period_bindings", models.JSONField()),
                ("created_at", models.DateTimeField()),
                ("due_at", models.DateTimeField(db_index=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("delivery_scope", models.CharField(default="internal_review", max_length=32)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("external_dispatch_requested", models.BooleanField(default=False)),
                ("auto_approval_requested", models.BooleanField(default=False)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_scenario_review_reminder",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(fields=["due_at", "expires_at"], name="research_srr_due_exp_idx"),
                    models.Index(
                        fields=["scenario_revision_id", "created_at"],
                        name="research_srr_rev_created_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("due_at__gte", models.F("created_at"))),
                        name="research_srr_due_after_created_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("due_at"))),
                        name="research_srr_exp_after_due_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("maximum_escalation_level__gte", 1)),
                        name="research_srr_max_level_positive_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("path_horizon_periods__gte", 1)),
                        name="research_srr_path_horizon_positive_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expiry_delay__gt", datetime.timedelta(0))),
                        name="research_srr_expiry_delay_positive_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("escalation_delay__gt", datetime.timedelta(0))),
                        name="research_srr_escalation_delay_positive_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("auto_approval_requested", False),
                            ("delivery_scope", "internal_review"),
                            ("external_dispatch_requested", False),
                            ("must_not_execute", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="research_srr_internal_only_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScenarioReviewReminderEventModel",
            fields=[
                ("event_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("event_version", models.CharField(max_length=128)),
                ("event_type", models.CharField(db_index=True, max_length=24)),
                ("sequence", models.PositiveIntegerField()),
                ("escalation_level", models.PositiveSmallIntegerField(default=0)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("recorded_at", models.DateTimeField()),
                ("actor_evidence_hash", models.CharField(max_length=64)),
                ("reason_code", models.CharField(max_length=128)),
                ("idempotency_key", models.CharField(db_index=True, max_length=255)),
                ("previous_event_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("delivery_scope", models.CharField(default="internal_review", max_length=32)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("external_dispatch_requested", models.BooleanField(default=False)),
                ("auto_approval_requested", models.BooleanField(default=False)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("record_hash", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="research.scenarioreviewremindermodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_scenario_review_reminder_event",
                "ordering": ["reminder_id", "sequence"],
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["reminder", "occurred_at"], name="research_srr_event_time_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reminder", "sequence"), name="research_srr_event_sequence_uniq"
                    ),
                    models.UniqueConstraint(
                        fields=("reminder", "idempotency_key"),
                        name="research_srr_event_idempotency_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("event_type", "scheduled"),
                                ("previous_event_hash__isnull", True),
                                ("sequence", 1),
                            ),
                            models.Q(
                                ("previous_event_hash__isnull", False),
                                ("sequence__gt", 1),
                                models.Q(("event_type", "scheduled"), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="research_srr_event_root_chain_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("auto_approval_requested", False),
                            ("delivery_scope", "internal_review"),
                            ("external_dispatch_requested", False),
                            ("must_not_execute", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="research_srr_event_internal_only_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("recorded_at__gte", models.F("occurred_at"))),
                        name="research_srr_event_recorded_after_ck",
                    ),
                ],
            },
        ),
    ]
