# Generated by Django 5.2.12 on 2026-08-05 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equity", "0013_forecast_baseline_ledgers"),
        ("research", "0002_scenario_review_reminder_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="R1ForecastPromotionPolicyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("policy_id", models.CharField(max_length=192)),
                ("policy_version", models.CharField(max_length=192)),
                ("owner", models.CharField(max_length=32)),
                ("capability", models.CharField(max_length=32)),
                ("purpose", models.CharField(max_length=32)),
                ("status", models.CharField(max_length=32)),
                ("scope_id", models.CharField(db_index=True, max_length=192)),
                ("scope_content_hash", models.CharField(max_length=64)),
                ("subject_code", models.CharField(max_length=192)),
                ("industry_code", models.CharField(max_length=192)),
                ("candidate_scenario", models.CharField(max_length=32)),
                ("horizon_quarters", models.PositiveSmallIntegerField()),
                ("calendar_schedule_hash", models.CharField(max_length=64)),
                ("metric_codes", models.JSONField()),
                ("approved_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField()),
                ("active_from", models.DateTimeField(db_index=True)),
                ("active_until", models.DateTimeField(db_index=True)),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_r1_promotion_policy",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy_id", "policy_version"), name="res_r1_pol_identity_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("capability", "r1"), ("owner", "research"), ("purpose", "valuation")
                        ),
                        name="res_r1_pol_authority_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("approved_at__lte", models.F("recorded_at")),
                            ("recorded_at__lte", models.F("active_from")),
                            ("active_from__lt", models.F("active_until")),
                        ),
                        name="res_r1_pol_time_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="res_r1_pol_research_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R1PromotionDecisionReceiptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("receipt_id", models.CharField(max_length=192)),
                ("receipt_version", models.CharField(max_length=192)),
                ("decision_id", models.CharField(max_length=192)),
                ("decision_version", models.CharField(max_length=192)),
                ("policy_content_hash", models.CharField(max_length=64)),
                ("result_content_hash", models.CharField(max_length=64)),
                ("equity_result_recorded_at", models.DateTimeField()),
                ("equity_result_record_hash", models.CharField(max_length=64)),
                ("owner", models.CharField(max_length=32)),
                ("capability", models.CharField(max_length=32)),
                ("purpose", models.CharField(max_length=32)),
                ("decided_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField()),
                ("decision_valid_until", models.DateTimeField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equity_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="research_r1_promotion_receipts",
                        to="equity.forecastbaselinetrialresultmodel",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision_receipts",
                        to="research.r1forecastpromotionpolicymodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r1_promotion_decision_receipt",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="R1ForecastPromotionDecisionBundleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("decision_id", models.CharField(max_length=192)),
                ("decision_version", models.CharField(max_length=192)),
                ("owner", models.CharField(max_length=32)),
                ("capability", models.CharField(max_length=32)),
                ("purpose", models.CharField(max_length=32)),
                ("scope_id", models.CharField(db_index=True, max_length=192)),
                ("scope_content_hash", models.CharField(max_length=64)),
                ("outcome", models.CharField(max_length=32)),
                ("decided_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("canonical_payload", models.JSONField()),
                ("decision_content_hash", models.CharField(max_length=64, unique=True)),
                ("bundle_content_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equity_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="research_r1_promotion_decisions",
                        to="equity.forecastbaselinetrialresultmodel",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision_bundles",
                        to="research.r1forecastpromotionpolicymodel",
                    ),
                ),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision_bundle",
                        to="research.r1promotiondecisionreceiptmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r1_promotion_decision_bundle",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="R1PromotionLifecycleReceiptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("authorization_id", models.CharField(max_length=192)),
                ("authorization_version", models.CharField(max_length=192)),
                ("event_id", models.CharField(max_length=192)),
                ("event_version", models.CharField(max_length=192)),
                ("owner", models.CharField(max_length=32)),
                ("capability", models.CharField(max_length=32)),
                ("purpose", models.CharField(max_length=32)),
                ("scope_id", models.CharField(db_index=True, max_length=192)),
                ("scope_content_hash", models.CharField(max_length=64)),
                ("event_type", models.CharField(max_length=32)),
                ("reason_codes", models.JSONField()),
                ("reason_hash", models.CharField(max_length=64)),
                ("authorization_issued_at", models.DateTimeField()),
                ("authorization_recorded_at", models.DateTimeField()),
                ("authorization_valid_until", models.DateTimeField()),
                ("occurred_at", models.DateTimeField()),
                ("event_recorded_at", models.DateTimeField()),
                ("authorization_content_hash", models.CharField(max_length=64, unique=True)),
                ("evidence_content_hash", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_receipts",
                        to="research.r1forecastpromotiondecisionbundlemodel",
                    ),
                ),
                (
                    "rollback_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rollback_target_receipts",
                        to="research.r1forecastpromotiondecisionbundlemodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r1_promotion_lifecycle_receipt",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="R1PromotionLifecycleEventBundleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_id", models.CharField(max_length=192)),
                ("event_version", models.CharField(max_length=192)),
                ("scope_id", models.CharField(db_index=True, max_length=192)),
                ("scope_content_hash", models.CharField(max_length=64)),
                ("stream_id", models.CharField(max_length=255)),
                ("event_type", models.CharField(max_length=32)),
                ("sequence", models.PositiveIntegerField()),
                ("reason_codes", models.JSONField()),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("previous_event_hash", models.CharField(blank=True, default="", max_length=64)),
                ("event_content_hash", models.CharField(max_length=64, unique=True)),
                ("bundle_content_hash", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_event_bundles",
                        to="research.r1forecastpromotiondecisionbundlemodel",
                    ),
                ),
                (
                    "previous_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="next_events",
                        to="research.r1promotionlifecycleeventbundlemodel",
                    ),
                ),
                (
                    "rollback_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rollback_target_event_bundles",
                        to="research.r1forecastpromotiondecisionbundlemodel",
                    ),
                ),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_bundle",
                        to="research.r1promotionlifecyclereceiptmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r1_promotion_lifecycle_bundle",
                "ordering": ["stream_id", "sequence"],
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AddConstraint(
            model_name="r1promotiondecisionreceiptmodel",
            constraint=models.UniqueConstraint(
                fields=("receipt_id", "receipt_version"), name="res_r1_dr_identity_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r1promotiondecisionreceiptmodel",
            constraint=models.UniqueConstraint(
                fields=("decision_id", "decision_version"), name="res_r1_dr_decision_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r1promotiondecisionreceiptmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capability", "r1"), ("owner", "research"), ("purpose", "valuation")
                ),
                name="res_r1_dr_authority_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r1promotiondecisionreceiptmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("equity_result_recorded_at__lte", models.F("decided_at")),
                    ("decided_at__lte", models.F("recorded_at")),
                    ("recorded_at__lt", models.F("decision_valid_until")),
                ),
                name="res_r1_dr_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r1forecastpromotiondecisionbundlemodel",
            constraint=models.UniqueConstraint(
                fields=("decision_id", "decision_version"), name="res_r1_db_identity_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r1forecastpromotiondecisionbundlemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capability", "r1"), ("owner", "research"), ("purpose", "valuation")
                ),
                name="res_r1_db_authority_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r1forecastpromotiondecisionbundlemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("decided_at__lte", models.F("recorded_at")),
                    ("recorded_at__lt", models.F("valid_until")),
                ),
                name="res_r1_db_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r1forecastpromotiondecisionbundlemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("must_not_execute", True),
                    ("must_not_use_for_decision", True),
                    ("research_only", True),
                ),
                name="res_r1_db_research_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r1promotionlifecyclereceiptmodel",
            constraint=models.UniqueConstraint(
                fields=("authorization_id", "authorization_version"),
                name="res_r1_lr_auth_identity_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="r1promotionlifecyclereceiptmodel",
            constraint=models.UniqueConstraint(
                fields=("event_id", "event_version"), name="res_r1_lr_event_identity_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r1promotionlifecyclereceiptmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capability", "r1"), ("owner", "research"), ("purpose", "valuation")
                ),
                name="res_r1_lr_authority_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r1promotionlifecyclereceiptmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("authorization_issued_at__lte", models.F("authorization_recorded_at")),
                    ("authorization_recorded_at__lte", models.F("occurred_at")),
                    ("occurred_at__lte", models.F("event_recorded_at")),
                    ("occurred_at__lt", models.F("authorization_valid_until")),
                ),
                name="res_r1_lr_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r1promotionlifecyclereceiptmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event_type", "rolled_back"), ("rollback_target__isnull", False)),
                    models.Q(
                        models.Q(("event_type", "rolled_back"), _negated=True),
                        ("rollback_target__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="res_r1_lr_target_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="r1promotionlifecycleeventbundlemodel",
            index=models.Index(fields=["stream_id", "recorded_at"], name="res_r1_lb_stream_rec_ix"),
        ),
        migrations.AddConstraint(
            model_name="r1promotionlifecycleeventbundlemodel",
            constraint=models.UniqueConstraint(
                fields=("event_id", "event_version"), name="res_r1_lb_identity_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r1promotionlifecycleeventbundlemodel",
            constraint=models.UniqueConstraint(
                fields=("stream_id", "sequence"), name="res_r1_lb_stream_seq_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r1promotionlifecycleeventbundlemodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("previous_event__isnull", False)),
                fields=("stream_id", "previous_event"),
                name="res_r1_lb_previous_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="r1promotionlifecycleeventbundlemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("recorded_at__gte", models.F("occurred_at"))),
                name="res_r1_lb_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r1promotionlifecycleeventbundlemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("event_type", "promoted"),
                        ("previous_event__isnull", True),
                        ("previous_event_hash", ""),
                        ("sequence", 1),
                    ),
                    models.Q(
                        ("previous_event__isnull", False),
                        ("sequence__gt", 1),
                        models.Q(("previous_event_hash", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="res_r1_lb_root_chain_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r1promotionlifecycleeventbundlemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("must_not_execute", True),
                    ("must_not_use_for_decision", True),
                    ("research_only", True),
                ),
                name="res_r1_lb_research_ck",
            ),
        ),
    ]
