# Generated by Django 5.2.12 on 2026-08-06 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0003_r1_forecast_promotion_ledgers"),
    ]

    operations = [
        migrations.CreateModel(
            name="R4PromotionDecisionReceiptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("receipt_id", models.CharField(max_length=192)),
                ("receipt_version", models.CharField(max_length=192)),
                ("decision_id", models.CharField(max_length=192)),
                ("decision_version", models.CharField(max_length=192)),
                ("trial_id", models.CharField(max_length=192)),
                ("trial_version", models.CharField(max_length=192)),
                ("policy_content_hash", models.CharField(max_length=64)),
                ("portfolio_record_id", models.CharField(max_length=192)),
                ("portfolio_record_hash", models.CharField(max_length=64)),
                ("portfolio_owner_record_key", models.CharField(max_length=192)),
                ("portfolio_recorded_at", models.DateTimeField()),
                ("current_r3_content_hash", models.CharField(max_length=64)),
                ("owner", models.CharField(max_length=32)),
                ("capability", models.CharField(max_length=32)),
                ("purpose", models.CharField(max_length=64)),
                ("decided_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField()),
                ("decision_valid_until", models.DateTimeField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_r4_promotion_decision_receipt",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="R4PromotionDecisionBundleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("decision_id", models.CharField(max_length=192)),
                ("decision_version", models.CharField(max_length=192)),
                ("trial_id", models.CharField(max_length=192)),
                ("trial_version", models.CharField(max_length=192)),
                ("trial_content_hash", models.CharField(max_length=64)),
                ("policy_content_hash", models.CharField(max_length=64)),
                ("portfolio_record_id", models.CharField(max_length=192)),
                ("portfolio_record_hash", models.CharField(max_length=64)),
                ("portfolio_owner_record_key", models.CharField(max_length=192)),
                ("current_r3_content_hash", models.CharField(max_length=64)),
                ("owner", models.CharField(max_length=32)),
                ("capability", models.CharField(max_length=32)),
                ("purpose", models.CharField(max_length=64)),
                ("scope_id", models.CharField(db_index=True, max_length=192)),
                ("scope_content_hash", models.CharField(max_length=64)),
                ("outcome", models.CharField(max_length=32)),
                ("decided_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("canonical_payload", models.JSONField()),
                ("decision_content_hash", models.CharField(max_length=64, unique=True)),
                ("bundle_content_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision_bundle",
                        to="research.r4promotiondecisionreceiptmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r4_promotion_decision_bundle",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="R4PromotionLifecycleAuthorizationReceiptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("authorization_id", models.CharField(max_length=192)),
                ("authorization_version", models.CharField(max_length=192)),
                ("event_id", models.CharField(max_length=192)),
                ("event_version", models.CharField(max_length=192)),
                ("decision_content_hash", models.CharField(max_length=64)),
                (
                    "rollback_target_content_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("owner", models.CharField(max_length=32)),
                ("capability", models.CharField(max_length=32)),
                ("purpose", models.CharField(max_length=64)),
                ("scope_id", models.CharField(db_index=True, max_length=192)),
                ("scope_content_hash", models.CharField(max_length=64)),
                ("event_type", models.CharField(max_length=32)),
                ("reason_codes", models.JSONField()),
                ("reason_hash", models.CharField(max_length=64)),
                ("authorization_issued_at", models.DateTimeField()),
                ("authorization_recorded_at", models.DateTimeField()),
                ("authorization_valid_until", models.DateTimeField()),
                ("occurred_at", models.DateTimeField()),
                ("event_recorded_at", models.DateTimeField()),
                ("authorization_content_hash", models.CharField(max_length=64, unique=True)),
                ("evidence_content_hash", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_authorization_receipts",
                        to="research.r4promotiondecisionbundlemodel",
                    ),
                ),
                (
                    "rollback_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rollback_target_authorization_receipts",
                        to="research.r4promotiondecisionbundlemodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r4_promotion_lifecycle_auth_receipt",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="R4PromotionLifecycleEventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("decision_content_hash", models.CharField(max_length=64)),
                (
                    "rollback_target_content_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("event_id", models.CharField(max_length=192)),
                ("event_version", models.CharField(max_length=192)),
                ("scope_id", models.CharField(db_index=True, max_length=192)),
                ("scope_content_hash", models.CharField(max_length=64)),
                ("stream_id", models.CharField(max_length=255)),
                ("event_type", models.CharField(max_length=32)),
                ("sequence", models.PositiveIntegerField()),
                ("reason_codes", models.JSONField()),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("previous_event_hash", models.CharField(blank=True, default="", max_length=64)),
                ("event_content_hash", models.CharField(max_length=64, unique=True)),
                ("bundle_content_hash", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_events",
                        to="research.r4promotiondecisionbundlemodel",
                    ),
                ),
                (
                    "previous_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="next_events",
                        to="research.r4promotionlifecycleeventmodel",
                    ),
                ),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_event",
                        to="research.r4promotionlifecycleauthorizationreceiptmodel",
                    ),
                ),
                (
                    "rollback_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rollback_target_lifecycle_events",
                        to="research.r4promotiondecisionbundlemodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r4_promotion_lifecycle_event",
                "ordering": ["stream_id", "sequence"],
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="R4PromotionPolicyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("policy_id", models.CharField(max_length=192)),
                ("policy_version", models.CharField(max_length=192)),
                ("owner", models.CharField(max_length=32)),
                ("capability", models.CharField(max_length=32)),
                ("purpose", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=32)),
                ("scope_id", models.CharField(db_index=True, max_length=192)),
                ("scope_content_hash", models.CharField(max_length=64)),
                ("study_family_id", models.CharField(max_length=192)),
                ("target_method", models.CharField(max_length=64)),
                ("universe_policy_id", models.CharField(max_length=192)),
                ("factor_policy_id", models.CharField(max_length=192)),
                ("split_policy_id", models.CharField(max_length=192)),
                ("cost_semantics_id", models.CharField(max_length=192)),
                ("approved_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField()),
                ("active_from", models.DateTimeField(db_index=True)),
                ("active_until", models.DateTimeField(db_index=True)),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_r4_promotion_policy",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy_id", "policy_version"), name="res_r4_pol_identity_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("capability", "r4"),
                            ("owner", "research"),
                            ("purpose", "macro_risk_method_research"),
                        ),
                        name="res_r4_pol_authority_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("approved_at__lte", models.F("recorded_at")),
                            ("recorded_at__lte", models.F("active_from")),
                            ("active_from__lt", models.F("active_until")),
                        ),
                        name="res_r4_pol_time_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="res_r4_pol_research_ck",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="r4promotiondecisionreceiptmodel",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decision_receipts",
                to="research.r4promotionpolicymodel",
            ),
        ),
        migrations.AddField(
            model_name="r4promotiondecisionbundlemodel",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decision_bundles",
                to="research.r4promotionpolicymodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotionlifecycleauthorizationreceiptmodel",
            constraint=models.UniqueConstraint(
                fields=("authorization_id", "authorization_version"),
                name="res_r4_lr_auth_identity_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotionlifecycleauthorizationreceiptmodel",
            constraint=models.UniqueConstraint(
                fields=("event_id", "event_version"), name="res_r4_lr_event_identity_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotionlifecycleauthorizationreceiptmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capability", "r4"),
                    ("owner", "research"),
                    ("purpose", "macro_risk_method_research"),
                ),
                name="res_r4_lr_authority_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotionlifecycleauthorizationreceiptmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("authorization_issued_at__lte", models.F("authorization_recorded_at")),
                    ("authorization_recorded_at__lte", models.F("occurred_at")),
                    ("occurred_at__lte", models.F("event_recorded_at")),
                    ("occurred_at__lt", models.F("authorization_valid_until")),
                ),
                name="res_r4_lr_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotionlifecycleauthorizationreceiptmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event_type", "rolled_back"), ("rollback_target__isnull", False)),
                    models.Q(
                        models.Q(("event_type", "rolled_back"), _negated=True),
                        ("rollback_target__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="res_r4_lr_target_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="r4promotionlifecycleeventmodel",
            index=models.Index(fields=["stream_id", "recorded_at"], name="res_r4_le_stream_rec_ix"),
        ),
        migrations.AddConstraint(
            model_name="r4promotionlifecycleeventmodel",
            constraint=models.UniqueConstraint(
                fields=("event_id", "event_version"), name="res_r4_le_identity_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotionlifecycleeventmodel",
            constraint=models.UniqueConstraint(
                fields=("stream_id", "sequence"), name="res_r4_le_stream_seq_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotionlifecycleeventmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("previous_event__isnull", False)),
                fields=("stream_id", "previous_event"),
                name="res_r4_le_previous_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotionlifecycleeventmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("recorded_at__gte", models.F("occurred_at"))),
                name="res_r4_le_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotionlifecycleeventmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("event_type", "promoted"),
                        ("previous_event__isnull", True),
                        ("previous_event_hash", ""),
                        ("sequence", 1),
                    ),
                    models.Q(
                        ("previous_event__isnull", False),
                        ("sequence__gt", 1),
                        models.Q(("previous_event_hash", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="res_r4_le_link_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotionlifecycleeventmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event_type", "rolled_back"), ("rollback_target__isnull", False)),
                    models.Q(
                        models.Q(("event_type", "rolled_back"), _negated=True),
                        ("rollback_target__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="res_r4_le_target_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotionlifecycleeventmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("must_not_execute", True),
                    ("must_not_use_for_decision", True),
                    ("research_only", True),
                ),
                name="res_r4_le_research_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotiondecisionreceiptmodel",
            constraint=models.UniqueConstraint(
                fields=("receipt_id", "receipt_version"), name="res_r4_dr_identity_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotiondecisionreceiptmodel",
            constraint=models.UniqueConstraint(
                fields=("decision_id", "decision_version"), name="res_r4_dr_decision_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotiondecisionreceiptmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capability", "r4"),
                    ("owner", "research"),
                    ("purpose", "macro_risk_method_research"),
                ),
                name="res_r4_dr_authority_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotiondecisionreceiptmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("portfolio_recorded_at__lte", models.F("decided_at")),
                    ("decided_at__lte", models.F("recorded_at")),
                    ("recorded_at__lt", models.F("decision_valid_until")),
                ),
                name="res_r4_dr_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotiondecisionbundlemodel",
            constraint=models.UniqueConstraint(
                fields=("decision_id", "decision_version"), name="res_r4_db_identity_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotiondecisionbundlemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capability", "r4"),
                    ("owner", "research"),
                    ("purpose", "macro_risk_method_research"),
                ),
                name="res_r4_db_authority_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotiondecisionbundlemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("decided_at__lte", models.F("recorded_at")),
                    ("recorded_at__lt", models.F("valid_until")),
                ),
                name="res_r4_db_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r4promotiondecisionbundlemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("must_not_execute", True),
                    ("must_not_use_for_decision", True),
                    ("research_only", True),
                ),
                name="res_r4_db_research_ck",
            ),
        ),
    ]
