# Generated by Django 5.2.12 on 2026-08-07 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0005_r7_sample_policy_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="R5PromotionArtifactModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("artifact_kind", models.CharField(max_length=16)),
                ("stable_id", models.CharField(max_length=300)),
                ("version", models.CharField(max_length=300)),
                ("owner", models.CharField(max_length=32)),
                ("capability", models.CharField(max_length=32)),
                ("purpose", models.CharField(max_length=96)),
                ("scope_id", models.CharField(db_index=True, max_length=300)),
                ("scope_content_hash", models.CharField(max_length=64)),
                ("semantic_recorded_at", models.DateTimeField(db_index=True)),
                ("active_from", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("ledger_receipt_hash", models.CharField(max_length=64, unique=True)),
                ("command_hash", models.CharField(max_length=64)),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "research_r5_promotion_artifact",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("artifact_kind", "stable_id", "version"),
                        name="res_r5_art_identity_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("artifact_kind__in", ["policy", "trial"])),
                        name="res_r5_art_kind_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("capability", "r5"),
                            ("owner", "research"),
                            ("purpose", "fixed_income_relative_value_research"),
                        ),
                        name="res_r5_art_authority_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("semantic_recorded_at__lte", models.F("active_from")),
                            ("active_from__lt", models.F("valid_until")),
                        ),
                        name="res_r5_art_time_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="res_r5_art_research_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R5PromotionDecisionAuthorizationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("authorization_id", models.CharField(max_length=300)),
                ("authorization_version", models.CharField(max_length=300)),
                ("owner", models.CharField(max_length=32)),
                ("capability", models.CharField(max_length=32)),
                ("purpose", models.CharField(max_length=96)),
                ("scope_id", models.CharField(db_index=True, max_length=300)),
                ("scope_content_hash", models.CharField(max_length=64)),
                ("issued_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField()),
                ("decision_recorded_at", models.DateTimeField()),
                ("decision_valid_until", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("ledger_receipt_hash", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="r5_decision_policy_authorizations",
                        to="research.r5promotionartifactmodel",
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="r5_decision_trial_authorizations",
                        to="research.r5promotionartifactmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r5_promotion_decision_auth",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="R5PromotionDecisionBundleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("decision_id", models.CharField(max_length=300)),
                ("decision_version", models.CharField(max_length=300)),
                ("owner", models.CharField(max_length=32)),
                ("capability", models.CharField(max_length=32)),
                ("purpose", models.CharField(max_length=96)),
                ("scope_id", models.CharField(db_index=True, max_length=300)),
                ("scope_content_hash", models.CharField(max_length=64)),
                ("outcome", models.CharField(max_length=32)),
                ("decided_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("ledger_receipt_hash", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                ("decision_content_hash", models.CharField(max_length=64, unique=True)),
                ("bundle_content_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                (
                    "authorization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision_bundle",
                        to="research.r5promotiondecisionauthorizationmodel",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="r5_policy_decision_bundles",
                        to="research.r5promotionartifactmodel",
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="r5_trial_decision_bundles",
                        to="research.r5promotionartifactmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r5_promotion_decision_bundle",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="R5PromotionLifecycleAuthorizationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("evidence_id", models.CharField(max_length=300)),
                ("evidence_version", models.CharField(max_length=300)),
                ("authorization_id", models.CharField(max_length=300)),
                ("authorization_version", models.CharField(max_length=300)),
                ("scope_id", models.CharField(db_index=True, max_length=300)),
                ("scope_content_hash", models.CharField(max_length=64)),
                ("event_id", models.CharField(max_length=300)),
                ("event_version", models.CharField(max_length=300)),
                ("event_type", models.CharField(max_length=32)),
                ("reason_codes", models.JSONField()),
                ("reason_hash", models.CharField(max_length=64)),
                ("authorization_issued_at", models.DateTimeField()),
                ("authorization_recorded_at", models.DateTimeField()),
                ("authorization_valid_until", models.DateTimeField()),
                ("receipt_recorded_at", models.DateTimeField()),
                ("occurred_at", models.DateTimeField()),
                ("event_recorded_at", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("ledger_receipt_hash", models.CharField(max_length=64, unique=True)),
                ("authorization_content_hash", models.CharField(max_length=64, unique=True)),
                ("evidence_content_hash", models.CharField(max_length=64, unique=True)),
                ("event_content_hash", models.CharField(max_length=64, unique=True)),
                ("canonical_payload", models.JSONField()),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="r5_lifecycle_authorizations",
                        to="research.r5promotiondecisionbundlemodel",
                    ),
                ),
                (
                    "rollback_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="r5_rollback_target_authorizations",
                        to="research.r5promotiondecisionbundlemodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r5_promotion_lifecycle_auth",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="R5PromotionLifecycleEventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_id", models.CharField(max_length=300)),
                ("event_version", models.CharField(max_length=300)),
                ("scope_id", models.CharField(db_index=True, max_length=300)),
                ("scope_content_hash", models.CharField(max_length=64)),
                ("stream_id", models.CharField(max_length=384)),
                ("event_type", models.CharField(max_length=32)),
                ("sequence", models.PositiveIntegerField()),
                ("reason_codes", models.JSONField()),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("ledger_receipt_hash", models.CharField(max_length=64, unique=True)),
                ("previous_event_hash", models.CharField(blank=True, default="", max_length=64)),
                ("canonical_payload", models.JSONField()),
                ("event_content_hash", models.CharField(max_length=64, unique=True)),
                ("bundle_content_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                (
                    "authorization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_event",
                        to="research.r5promotionlifecycleauthorizationmodel",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="r5_lifecycle_events",
                        to="research.r5promotiondecisionbundlemodel",
                    ),
                ),
                (
                    "previous_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="next_events",
                        to="research.r5promotionlifecycleeventmodel",
                    ),
                ),
                (
                    "rollback_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="r5_rollback_target_events",
                        to="research.r5promotiondecisionbundlemodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r5_promotion_lifecycle_event",
                "ordering": ["stream_id", "sequence"],
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AddConstraint(
            model_name="r5promotiondecisionauthorizationmodel",
            constraint=models.UniqueConstraint(
                fields=("authorization_id", "authorization_version"), name="res_r5_da_identity_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotiondecisionauthorizationmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capability", "r5"),
                    ("owner", "research"),
                    ("purpose", "fixed_income_relative_value_research"),
                ),
                name="res_r5_da_authority_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotiondecisionauthorizationmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("issued_at__lte", models.F("recorded_at")),
                    ("recorded_at__lte", models.F("decided_at")),
                    ("decided_at__lte", models.F("decision_recorded_at")),
                    ("decision_recorded_at__lt", models.F("decision_valid_until")),
                    ("decision_valid_until__lte", models.F("valid_until")),
                ),
                name="res_r5_da_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotiondecisionbundlemodel",
            constraint=models.UniqueConstraint(
                fields=("decision_id", "decision_version"), name="res_r5_db_identity_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotiondecisionbundlemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capability", "r5"),
                    ("owner", "research"),
                    ("purpose", "fixed_income_relative_value_research"),
                ),
                name="res_r5_db_authority_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotiondecisionbundlemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("decided_at__lte", models.F("recorded_at")),
                    ("recorded_at__lt", models.F("valid_until")),
                ),
                name="res_r5_db_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotiondecisionbundlemodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("must_not_execute", True),
                    ("must_not_use_for_decision", True),
                    ("research_only", True),
                ),
                name="res_r5_db_research_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotionlifecycleauthorizationmodel",
            constraint=models.UniqueConstraint(
                fields=("evidence_id", "evidence_version"), name="res_r5_la_evidence_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotionlifecycleauthorizationmodel",
            constraint=models.UniqueConstraint(
                fields=("authorization_id", "authorization_version"), name="res_r5_la_auth_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotionlifecycleauthorizationmodel",
            constraint=models.UniqueConstraint(
                fields=("event_id", "event_version"), name="res_r5_la_event_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotionlifecycleauthorizationmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event_type", "rolled_back"), ("rollback_target__isnull", False)),
                    models.Q(
                        models.Q(("event_type", "rolled_back"), _negated=True),
                        ("rollback_target__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="res_r5_la_target_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotionlifecycleauthorizationmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("authorization_issued_at__lte", models.F("authorization_recorded_at")),
                    ("authorization_recorded_at__lte", models.F("receipt_recorded_at")),
                    ("receipt_recorded_at__lte", models.F("occurred_at")),
                    ("occurred_at__lte", models.F("event_recorded_at")),
                    ("occurred_at__lt", models.F("authorization_valid_until")),
                ),
                name="res_r5_la_time_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="r5promotionlifecycleeventmodel",
            index=models.Index(fields=["stream_id", "recorded_at"], name="res_r5_le_stream_rec_ix"),
        ),
        migrations.AddConstraint(
            model_name="r5promotionlifecycleeventmodel",
            constraint=models.UniqueConstraint(
                fields=("event_id", "event_version"), name="res_r5_le_identity_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotionlifecycleeventmodel",
            constraint=models.UniqueConstraint(
                fields=("stream_id", "sequence"), name="res_r5_le_stream_seq_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotionlifecycleeventmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("previous_event__isnull", False)),
                fields=("stream_id", "previous_event"),
                name="res_r5_le_previous_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotionlifecycleeventmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("recorded_at__gte", models.F("occurred_at"))),
                name="res_r5_le_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotionlifecycleeventmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("event_type", "promoted"),
                        ("previous_event__isnull", True),
                        ("previous_event_hash", ""),
                        ("sequence", 1),
                    ),
                    models.Q(
                        ("previous_event__isnull", False),
                        ("sequence__gt", 1),
                        models.Q(("previous_event_hash", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="res_r5_le_link_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotionlifecycleeventmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event_type", "rolled_back"), ("rollback_target__isnull", False)),
                    models.Q(
                        models.Q(("event_type", "rolled_back"), _negated=True),
                        ("rollback_target__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="res_r5_le_target_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r5promotionlifecycleeventmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("must_not_execute", True),
                    ("must_not_use_for_decision", True),
                    ("research_only", True),
                ),
                name="res_r5_le_research_ck",
            ),
        ),
    ]
