# Generated by Django 5.2.12 on 2026-08-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0007_r7_research_result_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="R6QualificationAssessmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_id", models.CharField(max_length=192, unique=True)),
                ("study_id", models.CharField(db_index=True, max_length=192)),
                ("assessed_at", models.DateTimeField(db_index=True)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("status", models.CharField(max_length=32)),
                ("candidate_id", models.CharField(max_length=192, null=True)),
                ("candidate_version", models.CharField(max_length=192, null=True)),
                ("study_hash", models.CharField(max_length=64, null=True)),
                ("preregistration_hash", models.CharField(max_length=64, null=True)),
                (
                    "baseline_shortfall_report_hash",
                    models.CharField(max_length=64, null=True),
                ),
                ("candidate_evidence_hash", models.CharField(max_length=64, null=True)),
                ("advanced_assessment_hash", models.CharField(max_length=64, null=True)),
                (
                    "pit_manifest_canonical_hash",
                    models.CharField(max_length=64, null=True),
                ),
                ("artifact_attestation_hash", models.CharField(max_length=64, null=True)),
                ("advanced_threshold_hash", models.CharField(max_length=64, null=True)),
                ("derived_metric_bundle_hash", models.CharField(max_length=64, null=True)),
                ("policy_hash", models.CharField(max_length=64, null=True)),
                ("metric_result_count", models.PositiveIntegerField()),
                ("blockers", models.JSONField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("may_request_promotion_review", models.BooleanField()),
                ("promotion_decision_present", models.BooleanField(default=False)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_replace_regime", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_r6_qualification_assessment",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="R6QualificationLifecycleAuthorizationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authorization_id", models.CharField(max_length=192)),
                ("authorization_version", models.CharField(max_length=192)),
                ("event_id", models.CharField(max_length=192)),
                ("event_version", models.CharField(max_length=192)),
                ("action", models.CharField(max_length=16)),
                ("expected_sequence", models.PositiveIntegerField()),
                ("owner", models.CharField(max_length=32)),
                ("issued_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("valid_until", models.DateTimeField()),
                ("reason_codes", models.JSONField()),
                ("evidence_ref", models.CharField(max_length=300)),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_replace_regime", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_authorizations",
                        to="research.r6qualificationassessmentmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r6_qualification_lifecycle_auth",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="R6QualificationLifecycleEventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=192)),
                ("event_version", models.CharField(max_length=192)),
                ("action", models.CharField(max_length=16)),
                ("sequence", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("previous_event_hash", models.CharField(max_length=64, null=True)),
                ("reason_codes", models.JSONField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_replace_regime", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_events",
                        to="research.r6qualificationassessmentmodel",
                    ),
                ),
                (
                    "authorization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_event",
                        to="research.r6qualificationlifecycleauthorizationmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r6_qualification_lifecycle_event",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AddIndex(
            model_name="r6qualificationassessmentmodel",
            index=models.Index(
                fields=["study_id", "recorded_at"],
                name="res_r6_qual_pit_ix",
            ),
        ),
        migrations.AddConstraint(
            model_name="r6qualificationassessmentmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(assessed_at__lte=models.F("recorded_at")),
                name="res_r6_qual_clock_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r6qualificationassessmentmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    promotion_decision_present=False,
                    research_only=True,
                    must_not_use_for_decision=True,
                    must_not_replace_regime=True,
                ),
                name="res_r6_qual_safety_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r6qualificationlifecycleauthorizationmodel",
            constraint=models.UniqueConstraint(
                fields=("authorization_id", "authorization_version"),
                name="res_r6_qual_auth_identity_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="r6qualificationlifecycleauthorizationmodel",
            constraint=models.UniqueConstraint(
                fields=("event_id", "event_version"),
                name="res_r6_qual_auth_event_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="r6qualificationlifecycleauthorizationmodel",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(issued_at__lte=models.F("recorded_at"))
                    & models.Q(recorded_at__lt=models.F("valid_until"))
                ),
                name="res_r6_qual_auth_clock_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r6qualificationlifecycleauthorizationmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    owner="research",
                    research_only=True,
                    must_not_use_for_decision=True,
                    must_not_replace_regime=True,
                ),
                name="res_r6_qual_auth_safety_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r6qualificationlifecycleeventmodel",
            constraint=models.UniqueConstraint(
                fields=("event_id", "event_version"),
                name="res_r6_qual_event_identity_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="r6qualificationlifecycleeventmodel",
            constraint=models.UniqueConstraint(
                fields=("assessment", "sequence"),
                name="res_r6_qual_event_sequence_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="r6qualificationlifecycleeventmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(occurred_at__lte=models.F("recorded_at")),
                name="res_r6_qual_event_clock_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r6qualificationlifecycleeventmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    research_only=True,
                    must_not_use_for_decision=True,
                    must_not_replace_regime=True,
                ),
                name="res_r6_qual_event_safety_ck",
            ),
        ),
    ]
