# Generated by Django 5.2.12 on 2026-08-09 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the schema-only R6 monitoring observation and assessment ledgers."""

    dependencies = [
        ("research", "0010_r7_result_promotion_lifecycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="R6MonitoringAssessmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_id", models.CharField(max_length=192, unique=True)),
                ("qualification_assessment_id", models.CharField(max_length=192)),
                ("qualification_assessment_hash", models.CharField(max_length=64)),
                ("requested_policy_id", models.CharField(max_length=192)),
                ("requested_policy_version", models.CharField(max_length=192)),
                ("expected_policy_hash", models.CharField(max_length=64)),
                ("policy_hash", models.CharField(max_length=64)),
                ("period_calendar_id", models.CharField(max_length=192)),
                ("period_calendar_version", models.CharField(max_length=192)),
                ("period_calendar_hash", models.CharField(max_length=64)),
                ("evaluated_at", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("ledger_header_hash", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=40)),
                ("observation_count", models.PositiveIntegerField()),
                ("metric_result_count", models.PositiveIntegerField()),
                ("observation_hashes", models.JSONField()),
                ("blockers", models.JSONField()),
                ("policy_payload", models.JSONField()),
                ("period_calendar_payload", models.JSONField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("label_drift_detected", models.BooleanField()),
                ("retirement_review_required", models.BooleanField()),
                ("automatic_retirement", models.BooleanField(default=False)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_replace_regime", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitoring_assessments",
                        to="research.r6qualificationassessmentmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r6_monitoring_assessment",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=[
                            "qualification",
                            "expected_policy_hash",
                            "ledger_recorded_at",
                        ],
                        name="res_r6_mon_asmt_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "qualification",
                            "expected_policy_hash",
                            "evaluated_at",
                        ),
                        name="res_r6_mon_asmt_cmd_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("evaluated_at__lte", models.F("ledger_recorded_at"))),
                        name="res_r6_mon_asmt_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("automatic_retirement", False),
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_replace_regime", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="res_r6_mon_asmt_safe_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R6MonitoringObservationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observation_id", models.CharField(max_length=192)),
                ("observation_version", models.CharField(max_length=192)),
                ("qualification_assessment_id", models.CharField(max_length=192)),
                ("qualification_assessment_hash", models.CharField(max_length=64)),
                ("policy_id", models.CharField(max_length=192)),
                ("policy_version", models.CharField(max_length=192)),
                ("policy_hash", models.CharField(max_length=64)),
                ("period_calendar_id", models.CharField(max_length=192)),
                ("period_calendar_version", models.CharField(max_length=192)),
                ("period_calendar_hash", models.CharField(max_length=64)),
                ("observation_period_id", models.CharField(max_length=64)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("source_owner", models.CharField(max_length=192)),
                ("observed_at", models.DateTimeField()),
                ("available_at", models.DateTimeField()),
                ("owner_recorded_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("pit_manifest_id", models.CharField(max_length=192)),
                ("pit_manifest_hash", models.CharField(max_length=64)),
                ("evidence_ref", models.CharField(max_length=300)),
                ("label_protocol_version", models.CharField(max_length=192)),
                ("observed_label_set_hash", models.CharField(max_length=64)),
                ("metric_count", models.PositiveIntegerField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("ledger_header_hash", models.CharField(max_length=64)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_replace_regime", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitoring_observations",
                        to="research.r6qualificationassessmentmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r6_monitoring_observation",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["qualification", "policy_hash", "ledger_recorded_at"],
                        name="res_r6_mon_obs_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("observation_id", "observation_version"),
                        name="res_r6_mon_obs_ident_uq",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "qualification",
                            "policy_hash",
                            "observation_period_id",
                        ),
                        name="res_r6_mon_obs_period_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("observed_at__lte", models.F("available_at")),
                            ("available_at__lte", models.F("owner_recorded_at")),
                            ("owner_recorded_at__lt", models.F("valid_until")),
                            ("owner_recorded_at__lte", models.F("ledger_recorded_at")),
                        ),
                        name="res_r6_mon_obs_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_start__lt", models.F("period_end")),
                            ("period_start__lte", models.F("observed_at")),
                            ("observed_at__lt", models.F("period_end")),
                        ),
                        name="res_r6_mon_obs_window_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_replace_regime", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="res_r6_mon_obs_safe_ck",
                    ),
                ],
            },
        ),
    ]
