# Generated by Django 5.2 on 2026-08-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create schema-only R6 activation ledgers and stream-commit anchors."""

    dependencies = [
        ("research", "0011_r6_monitoring_ledgers"),
    ]

    operations = [
        migrations.CreateModel(
            name="R6ActivationAuthorizationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authorization_id", models.CharField(max_length=192)),
                ("authorization_version", models.CharField(max_length=192)),
                ("event_id", models.CharField(max_length=192)),
                ("event_version", models.CharField(max_length=192)),
                ("scope_id", models.CharField(max_length=192)),
                ("scope_version", models.CharField(max_length=192)),
                ("scope_hash", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=16)),
                ("subject_approval_id", models.CharField(max_length=192)),
                ("subject_approval_version", models.CharField(max_length=192)),
                ("subject_approval_hash", models.CharField(max_length=64)),
                ("rollback_approval_id", models.CharField(max_length=192, null=True)),
                ("rollback_approval_version", models.CharField(max_length=192, null=True)),
                ("rollback_approval_hash", models.CharField(max_length=64, null=True)),
                ("expected_sequence", models.PositiveIntegerField()),
                ("expected_previous_event_hash", models.CharField(max_length=64, null=True)),
                ("owner", models.CharField(max_length=192)),
                ("issued_at", models.DateTimeField()),
                ("owner_recorded_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("reason_codes", models.JSONField()),
                ("evidence_ref", models.CharField(max_length=300)),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("ledger_header_hash", models.CharField(max_length=64)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_replace_regime", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_r6_activation_authorization",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=("scope_id", "scope_version", "scope_hash", "ledger_recorded_at"),
                        name="res_r6_act_auth_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("authorization_id", "authorization_version"),
                        name="res_r6_act_auth_ident_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("event_id", "event_version"),
                        name="res_r6_act_auth_event_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            action__in=("activate", "retire", "rollback"), owner="research"
                        ),
                        name="res_r6_act_auth_type_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(issued_at__lte=models.F("owner_recorded_at"))
                            & models.Q(owner_recorded_at__lt=models.F("valid_until"))
                            & models.Q(owner_recorded_at__lte=models.F("ledger_recorded_at"))
                        ),
                        name="res_r6_act_auth_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                expected_sequence=1,
                                expected_previous_event_hash__isnull=True,
                            )
                            | models.Q(
                                expected_sequence__gt=1,
                                expected_previous_event_hash__isnull=False,
                            )
                        ),
                        name="res_r6_act_auth_head_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                action="rollback",
                                rollback_approval_id__isnull=False,
                                rollback_approval_version__isnull=False,
                                rollback_approval_hash__isnull=False,
                            )
                            | (
                                ~models.Q(action="rollback")
                                & models.Q(
                                    rollback_approval_id__isnull=True,
                                    rollback_approval_version__isnull=True,
                                    rollback_approval_hash__isnull=True,
                                )
                            )
                        ),
                        name="res_r6_act_auth_roll_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            research_only=True,
                            must_not_use_for_decision=True,
                            must_not_replace_regime=True,
                            must_not_publish_current=True,
                            must_not_execute=True,
                        ),
                        name="res_r6_act_auth_safe_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R6ActivationEventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=192)),
                ("event_version", models.CharField(max_length=192)),
                ("scope_id", models.CharField(max_length=192)),
                ("scope_version", models.CharField(max_length=192)),
                ("scope_hash", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=16)),
                ("subject_approval_id", models.CharField(max_length=192)),
                ("subject_approval_version", models.CharField(max_length=192)),
                ("subject_approval_hash", models.CharField(max_length=64)),
                ("rollback_approval_id", models.CharField(max_length=192, null=True)),
                ("rollback_approval_version", models.CharField(max_length=192, null=True)),
                ("rollback_approval_hash", models.CharField(max_length=64, null=True)),
                ("authorization_id", models.CharField(max_length=192)),
                ("authorization_version", models.CharField(max_length=192)),
                ("authorization_hash", models.CharField(max_length=64)),
                ("sequence", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField()),
                ("previous_event_hash", models.CharField(max_length=64, null=True)),
                ("reason_codes", models.JSONField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("ledger_header_hash", models.CharField(max_length=64)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_replace_regime", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authorization_row",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activation_event",
                        to="research.r6activationauthorizationmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r6_activation_event",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=("scope_id", "scope_version", "scope_hash", "ledger_recorded_at"),
                        name="res_r6_act_evt_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_id", "event_version"),
                        name="res_r6_act_evt_ident_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("scope_id", "scope_version", "sequence"),
                        name="res_r6_act_evt_sid_seq_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("scope_hash", "sequence"),
                        name="res_r6_act_evt_hash_seq_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(action__in=("activate", "retire", "rollback")),
                        name="res_r6_act_evt_type_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(occurred_at__lte=models.F("recorded_at"))
                            & models.Q(recorded_at__lte=models.F("ledger_recorded_at"))
                        ),
                        name="res_r6_act_evt_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(sequence=1, previous_event_hash__isnull=True)
                            | models.Q(sequence__gt=1, previous_event_hash__isnull=False)
                        ),
                        name="res_r6_act_evt_head_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                action="rollback",
                                rollback_approval_id__isnull=False,
                                rollback_approval_version__isnull=False,
                                rollback_approval_hash__isnull=False,
                            )
                            | (
                                ~models.Q(action="rollback")
                                & models.Q(
                                    rollback_approval_id__isnull=True,
                                    rollback_approval_version__isnull=True,
                                    rollback_approval_hash__isnull=True,
                                )
                            )
                        ),
                        name="res_r6_act_evt_roll_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            research_only=True,
                            must_not_use_for_decision=True,
                            must_not_replace_regime=True,
                            must_not_publish_current=True,
                            must_not_execute=True,
                        ),
                        name="res_r6_act_evt_safe_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R6ActivationStreamCommitModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authorization_id", models.CharField(max_length=192)),
                ("authorization_version", models.CharField(max_length=192)),
                ("authorization_hash", models.CharField(max_length=64)),
                ("event_id", models.CharField(max_length=192)),
                ("event_version", models.CharField(max_length=192)),
                ("event_hash", models.CharField(max_length=64)),
                ("scope_id", models.CharField(max_length=192)),
                ("scope_version", models.CharField(max_length=192)),
                ("scope_hash", models.CharField(max_length=64)),
                ("sequence", models.PositiveIntegerField()),
                ("previous_event_hash", models.CharField(max_length=64, null=True)),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_replace_regime", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authorization_row",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activation_stream_commit",
                        to="research.r6activationauthorizationmodel",
                    ),
                ),
                (
                    "event_row",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activation_stream_commit",
                        to="research.r6activationeventmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r6_activation_stream_commit",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=(
                            "scope_id",
                            "scope_version",
                            "scope_hash",
                            "ledger_recorded_at",
                        ),
                        name="res_r6_act_cmt_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("authorization_id", "authorization_version"),
                        name="res_r6_act_cmt_auth_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("event_id", "event_version"),
                        name="res_r6_act_cmt_event_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("scope_id", "scope_version", "sequence"),
                        name="res_r6_act_cmt_sid_seq_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("scope_hash", "sequence"),
                        name="res_r6_act_cmt_hash_seq_uq",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(sequence=1, previous_event_hash__isnull=True)
                            | models.Q(sequence__gt=1, previous_event_hash__isnull=False)
                        ),
                        name="res_r6_act_cmt_head_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            research_only=True,
                            must_not_use_for_decision=True,
                            must_not_replace_regime=True,
                            must_not_publish_current=True,
                            must_not_execute=True,
                        ),
                        name="res_r6_act_cmt_safe_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R6ActivationAuditSnapshotModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_id", models.CharField(max_length=192)),
                ("snapshot_version", models.CharField(max_length=192)),
                ("as_of", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("entry_count", models.PositiveIntegerField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("internal_audit_only", models.BooleanField(default=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_replace_regime", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_r6_activation_audit_snapshot",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=("as_of", "created_at"),
                        name="res_r6_act_snap_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot_id", "snapshot_version"),
                        name="res_r6_act_snap_ident_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(as_of__lte=models.F("created_at")),
                        name="res_r6_act_snap_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            internal_audit_only=True,
                            research_only=True,
                            must_not_use_for_decision=True,
                            must_not_replace_regime=True,
                            must_not_publish_current=True,
                            must_not_execute=True,
                        ),
                        name="res_r6_act_snap_safe_ck",
                    ),
                ],
            },
        ),
    ]
