# Generated by Django 5.2.12 on 2026-08-10 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0013_r4_monitoring_ledgers"),
    ]

    operations = [
        migrations.CreateModel(
            name="R5MonitoringAssessmentLedgerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_id", models.CharField(max_length=192, unique=True)),
                ("assessment_version", models.CharField(max_length=192)),
                ("scope_id", models.CharField(max_length=300)),
                ("scope_hash", models.CharField(max_length=64)),
                ("active_decision_stable_id", models.CharField(max_length=300)),
                ("active_decision_version", models.CharField(max_length=300)),
                ("active_decision_hash", models.CharField(max_length=64)),
                ("active_lifecycle_hash", models.CharField(max_length=64)),
                ("fixed_income_result_id", models.CharField(max_length=300)),
                ("fixed_income_result_version", models.CharField(max_length=300)),
                ("fixed_income_result_hash", models.CharField(max_length=64)),
                ("fixed_income_owner_seal_hash", models.CharField(max_length=64)),
                ("requested_policy_id", models.CharField(max_length=192)),
                ("requested_policy_version", models.CharField(max_length=192)),
                ("expected_policy_hash", models.CharField(max_length=64)),
                ("calendar_id", models.CharField(max_length=192)),
                ("calendar_version", models.CharField(max_length=192)),
                ("calendar_hash", models.CharField(max_length=64)),
                ("evaluated_at", models.DateTimeField()),
                ("active_owner_recorded_at", models.DateTimeField()),
                ("fixed_income_owner_recorded_at", models.DateTimeField()),
                ("policy_owner_recorded_at", models.DateTimeField()),
                ("calendar_owner_recorded_at", models.DateTimeField()),
                ("latest_fact_owner_recorded_at", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("ledger_header_hash", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=48)),
                ("fact_count", models.PositiveIntegerField()),
                ("fact_hashes", models.JSONField()),
                ("active_lifecycle_payload", models.JSONField()),
                ("fixed_income_payload", models.JSONField()),
                ("policy_payload", models.JSONField()),
                ("calendar_payload", models.JSONField()),
                ("assessment_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("automatic_retirement", models.BooleanField(default=False)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "active_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="r5_monitoring_assessments",
                        to="research.r5promotiondecisionbundlemodel",
                    ),
                ),
                (
                    "lifecycle_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="r5_monitoring_assessments",
                        to="research.r5promotionlifecycleeventmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r5_monitoring_assessment",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="R5MonitoringAuditSnapshotModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("snapshot_id", models.CharField(max_length=192)),
                ("snapshot_version", models.CharField(max_length=192)),
                ("as_of", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("entry_count", models.PositiveIntegerField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64)),
                ("internal_audit_only", models.BooleanField(default=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_r5_monitoring_audit_snapshot",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(fields=["as_of", "created_at"], name="res_r5_mon_snap_pit_ix")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot_id", "snapshot_version"), name="res_r5_mon_snap_ident_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("as_of__lte", models.F("created_at"))),
                        name="res_r5_mon_snap_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("internal_audit_only", True),
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="res_r5_mon_snap_safe_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R5MonitoringObservationLedgerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fact_id", models.CharField(max_length=192)),
                ("fact_version", models.CharField(max_length=192)),
                ("domain_fact_hash", models.CharField(max_length=64)),
                ("policy_id", models.CharField(max_length=192)),
                ("policy_version", models.CharField(max_length=192)),
                ("policy_hash", models.CharField(max_length=64)),
                ("target_hash", models.CharField(max_length=64)),
                ("calendar_id", models.CharField(max_length=192)),
                ("calendar_version", models.CharField(max_length=192)),
                ("calendar_hash", models.CharField(max_length=64)),
                ("period_id", models.CharField(max_length=64)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("source_owner", models.CharField(max_length=192)),
                ("source_owner_id", models.CharField(max_length=192)),
                ("source_owner_version", models.CharField(max_length=192)),
                ("source_owner_hash", models.CharField(max_length=64)),
                ("source_observed_at", models.DateTimeField()),
                ("observed_at", models.DateTimeField()),
                ("available_at", models.DateTimeField()),
                ("owner_recorded_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("observed_label_hash", models.CharField(max_length=64)),
                ("observed_data_schema_hash", models.CharField(max_length=64)),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64)),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("ledger_header_hash", models.CharField(max_length=64)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "active_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="r5_monitoring_observations",
                        to="research.r5promotiondecisionbundlemodel",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="research.r5monitoringassessmentledgermodel",
                    ),
                ),
                (
                    "lifecycle_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="r5_monitoring_observations",
                        to="research.r5promotionlifecycleeventmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r5_monitoring_observation",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AddIndex(
            model_name="r5monitoringassessmentledgermodel",
            index=models.Index(
                fields=["active_decision", "expected_policy_hash", "ledger_recorded_at"],
                name="res_r5_mon_asmt_pit_ix",
            ),
        ),
        migrations.AddConstraint(
            model_name="r5monitoringassessmentledgermodel",
            constraint=models.UniqueConstraint(
                fields=(
                    "requested_policy_id",
                    "requested_policy_version",
                    "expected_policy_hash",
                    "evaluated_at",
                ),
                name="res_r5_mon_asmt_cmd_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="r5monitoringassessmentledgermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("active_owner_recorded_at__lte", models.F("evaluated_at")),
                    ("fixed_income_owner_recorded_at__lte", models.F("evaluated_at")),
                    ("policy_owner_recorded_at__lte", models.F("evaluated_at")),
                    ("calendar_owner_recorded_at__lte", models.F("evaluated_at")),
                    ("latest_fact_owner_recorded_at__lte", models.F("evaluated_at")),
                    ("evaluated_at__lte", models.F("ledger_recorded_at")),
                ),
                name="res_r5_mon_asmt_clock_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r5monitoringassessmentledgermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("healthy", "breached", "retirement_review_required", "blocked"))
                ),
                name="res_r5_mon_asmt_status_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r5monitoringassessmentledgermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("automatic_retirement", False),
                    ("must_not_execute", True),
                    ("must_not_publish_current", True),
                    ("must_not_use_for_decision", True),
                    ("research_only", True),
                ),
                name="res_r5_mon_asmt_safe_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="r5monitoringobservationledgermodel",
            index=models.Index(
                fields=["active_decision", "policy_hash", "ledger_recorded_at"],
                name="res_r5_mon_obs_pit_ix",
            ),
        ),
        migrations.AddConstraint(
            model_name="r5monitoringobservationledgermodel",
            constraint=models.UniqueConstraint(
                fields=("assessment", "period_id"), name="res_r5_mon_obs_period_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r5monitoringobservationledgermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("period_start__lt", models.F("period_end")),
                    ("period_end__lte", models.F("observed_at")),
                    ("source_observed_at__lte", models.F("observed_at")),
                    ("observed_at__lte", models.F("available_at")),
                    ("available_at__lte", models.F("owner_recorded_at")),
                    ("owner_recorded_at__lt", models.F("valid_until")),
                    ("owner_recorded_at__lte", models.F("ledger_recorded_at")),
                ),
                name="res_r5_mon_obs_clock_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r5monitoringobservationledgermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("must_not_execute", True),
                    ("must_not_publish_current", True),
                    ("must_not_use_for_decision", True),
                    ("research_only", True),
                ),
                name="res_r5_mon_obs_safe_ck",
            ),
        ),
    ]
