# Generated by Django 5.2.12 on 2026-08-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0015_r3_macro_factor_runner_spec_ledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="R2ExplanatoryTrialAssessmentLedgerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_id", models.CharField(max_length=192)),
                ("assessment_version", models.CharField(max_length=64)),
                ("policy_id", models.CharField(db_index=True, max_length=192)),
                ("policy_version", models.CharField(max_length=192)),
                ("policy_hash", models.CharField(max_length=64)),
                ("taxonomy_publication_id", models.CharField(max_length=192)),
                ("taxonomy_publication_version", models.CharField(max_length=192)),
                ("taxonomy_publication_hash", models.CharField(max_length=64)),
                ("calendar_publication_id", models.CharField(max_length=192)),
                ("calendar_publication_version", models.CharField(max_length=192)),
                ("calendar_publication_hash", models.CharField(max_length=64)),
                ("cycle_one_hash", models.CharField(max_length=64)),
                ("cycle_two_hash", models.CharField(max_length=64)),
                ("audit_outcome_id", models.CharField(max_length=192)),
                ("audit_outcome_version", models.CharField(max_length=192)),
                ("audit_outcome_hash", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=32)),
                ("assessed_at", models.DateTimeField(db_index=True)),
                ("owner_valid_until", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_as_predictive_signal", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("is_attested_ready", models.BooleanField(default=False)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_r2_explanatory_trial_assessment",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["policy_id", "policy_version", "assessed_at"],
                        name="res_r2_tm_trial_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assessment_id", "assessment_version"),
                        name="res_r2_tm_trial_ident_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ("passed", "breached", "blocked"))),
                        name="res_r2_tm_trial_status_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("assessed_at__lte", models.F("ledger_recorded_at")),
                            ("ledger_recorded_at__lt", models.F("owner_valid_until")),
                        ),
                        name="res_r2_tm_trial_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_attested_ready", False),
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_as_predictive_signal", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="res_r2_tm_trial_safe_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R2MonitoringAssessmentLedgerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_id", models.CharField(max_length=192)),
                ("assessment_version", models.CharField(max_length=64)),
                ("policy_id", models.CharField(db_index=True, max_length=192)),
                ("policy_version", models.CharField(max_length=192)),
                ("policy_hash", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=40)),
                ("assessed_at", models.DateTimeField(db_index=True)),
                ("owner_valid_until", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("fact_count", models.PositiveIntegerField()),
                ("fact_manifest_hash", models.CharField(max_length=64)),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("retirement_review_required", models.BooleanField(default=False)),
                ("automatic_retirement", models.BooleanField(default=False)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_as_predictive_signal", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trial_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitoring_assessments",
                        to="research.r2explanatorytrialassessmentledgermodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r2_monitoring_assessment",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="R2MonitoringAuditSnapshotModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_id", models.CharField(max_length=192)),
                ("snapshot_version", models.CharField(max_length=64)),
                ("as_of", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("entry_count", models.PositiveIntegerField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("internal_audit_only", models.BooleanField(default=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_r2_monitoring_audit_snapshot",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["as_of", "created_at"],
                        name="res_r2_tm_snap_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot_id", "snapshot_version"),
                        name="res_r2_tm_snap_ident_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("as_of__lte", models.F("created_at"))),
                        name="res_r2_tm_snap_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("internal_audit_only", True),
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="res_r2_tm_snap_safe_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R2MonitoringObservationLedgerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fact_id", models.CharField(max_length=192)),
                ("fact_version", models.CharField(max_length=192)),
                ("fact_content_hash", models.CharField(max_length=64)),
                ("policy_id", models.CharField(db_index=True, max_length=192)),
                ("policy_version", models.CharField(max_length=192)),
                ("policy_hash", models.CharField(max_length=64)),
                ("period_id", models.CharField(db_index=True, max_length=192)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("source_owner", models.CharField(max_length=192)),
                ("owner_observed_at", models.DateTimeField()),
                ("owner_available_at", models.DateTimeField()),
                ("owner_recorded_at", models.DateTimeField()),
                ("owner_valid_until", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("canonical_payload", models.JSONField()),
                ("row_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_as_predictive_signal", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "monitoring_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="research.r2monitoringassessmentledgermodel",
                    ),
                ),
                (
                    "trial_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monitoring_observations",
                        to="research.r2explanatorytrialassessmentledgermodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r2_monitoring_observation",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AddIndex(
            model_name="r2monitoringassessmentledgermodel",
            index=models.Index(
                fields=["policy_id", "policy_version", "assessed_at"],
                name="res_r2_tm_asmt_pit_ix",
            ),
        ),
        migrations.AddConstraint(
            model_name="r2monitoringassessmentledgermodel",
            constraint=models.UniqueConstraint(
                fields=("assessment_id", "assessment_version"),
                name="res_r2_tm_asmt_ident_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="r2monitoringassessmentledgermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        (
                            "healthy",
                            "breached",
                            "retirement_review_required",
                            "blocked",
                        ),
                    )
                ),
                name="res_r2_tm_asmt_status_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r2monitoringassessmentledgermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fact_count__gt", 0),
                    ("assessed_at__lte", models.F("ledger_recorded_at")),
                    ("ledger_recorded_at__lt", models.F("owner_valid_until")),
                ),
                name="res_r2_tm_asmt_clock_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r2monitoringassessmentledgermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("automatic_retirement", False),
                    ("must_not_execute", True),
                    ("must_not_publish_current", True),
                    ("must_not_use_as_predictive_signal", True),
                    ("must_not_use_for_decision", True),
                    ("research_only", True),
                ),
                name="res_r2_tm_asmt_safe_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="r2monitoringobservationledgermodel",
            index=models.Index(
                fields=["policy_id", "period_end", "ledger_recorded_at"],
                name="res_r2_tm_obs_pit_ix",
            ),
        ),
        migrations.AddConstraint(
            model_name="r2monitoringobservationledgermodel",
            constraint=models.UniqueConstraint(
                fields=("monitoring_assessment", "fact_id", "fact_version"),
                name="res_r2_tm_obs_scope_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="r2monitoringobservationledgermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("period_start__lt", models.F("period_end")),
                    ("owner_observed_at__lte", models.F("owner_available_at")),
                    ("owner_available_at__lte", models.F("owner_recorded_at")),
                    ("owner_recorded_at__lte", models.F("ledger_recorded_at")),
                    ("ledger_recorded_at__lt", models.F("owner_valid_until")),
                ),
                name="res_r2_tm_obs_clock_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r2monitoringobservationledgermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("must_not_execute", True),
                    ("must_not_publish_current", True),
                    ("must_not_use_as_predictive_signal", True),
                    ("must_not_use_for_decision", True),
                    ("research_only", True),
                ),
                name="res_r2_tm_obs_safe_ck",
            ),
        ),
    ]
