# Generated by Django 5.2.12 on 2026-08-10 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0016_r2_trial_monitoring_ledgers"),
    ]

    operations = [
        migrations.CreateModel(
            name="R7MonitoringAssessmentLedgerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("assessment_id", models.CharField(max_length=192, unique=True)),
                ("assessment_version", models.CharField(max_length=192)),
                ("policy_id", models.CharField(max_length=192)),
                ("policy_version", models.CharField(max_length=192)),
                ("policy_hash", models.CharField(max_length=64)),
                ("result_stable_id", models.CharField(max_length=192)),
                ("result_version", models.CharField(max_length=192)),
                ("result_hash", models.CharField(max_length=64)),
                ("lifecycle_attestation_id", models.CharField(max_length=192)),
                ("lifecycle_attestation_version", models.CharField(max_length=192)),
                ("lifecycle_attestation_hash", models.CharField(max_length=64)),
                ("lifecycle_head_hash", models.CharField(max_length=64)),
                ("calendar_id", models.CharField(max_length=192)),
                ("calendar_version", models.CharField(max_length=192)),
                ("calendar_hash", models.CharField(max_length=64)),
                ("period_id", models.CharField(max_length=192)),
                ("period_version", models.CharField(max_length=192)),
                ("period_hash", models.CharField(max_length=64)),
                ("realization_owner_id", models.CharField(max_length=300)),
                ("realization_owner_version", models.CharField(max_length=192)),
                ("realization_owner_hash", models.CharField(max_length=64)),
                ("evaluated_at", models.DateTimeField()),
                ("policy_recorded_at", models.DateTimeField()),
                ("result_recorded_at", models.DateTimeField()),
                ("lifecycle_recorded_at", models.DateTimeField()),
                ("calendar_recorded_at", models.DateTimeField()),
                ("realization_recorded_at", models.DateTimeField()),
                ("owner_valid_until", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("observation_count", models.PositiveIntegerField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("status", models.CharField(max_length=48)),
                ("automatic_retirement", models.BooleanField(default=False)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lifecycle_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="r7_monitoring_assessments",
                        to="research.r7resultlifecycleeventmodel",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="r7_monitoring_assessments",
                        to="research.r7researchresultmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r7_monitoring_assessment",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="R7MonitoringAuditSnapshotModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("snapshot_id", models.CharField(max_length=192)),
                ("snapshot_version", models.CharField(max_length=192)),
                ("as_of", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("entry_count", models.PositiveIntegerField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("internal_audit_only", models.BooleanField(default=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_r7_monitoring_audit_snapshot",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(fields=["as_of", "created_at"], name="res_r7_mon_snap_pit_ix")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot_id", "snapshot_version"), name="res_r7_mon_snap_ident_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("as_of__lte", models.F("created_at"))),
                        name="res_r7_mon_snap_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("internal_audit_only", True),
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="res_r7_mon_snap_safe_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R7MonitoringObservationLedgerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observation_index", models.PositiveIntegerField()),
                ("observation_id", models.CharField(max_length=300)),
                ("observation_version", models.CharField(max_length=192)),
                ("observation_hash", models.CharField(max_length=64)),
                ("prediction_hash", models.CharField(max_length=64)),
                ("member_hash", models.CharField(max_length=64)),
                ("period_id", models.CharField(max_length=192)),
                ("period_hash", models.CharField(max_length=64)),
                ("published_at", models.DateTimeField()),
                ("horizon_end", models.DateTimeField()),
                ("available_at", models.DateTimeField()),
                ("owner_recorded_at", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="research.r7monitoringassessmentledgermodel",
                    ),
                ),
                (
                    "lifecycle_head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="r7_monitoring_observations",
                        to="research.r7resultlifecycleeventmodel",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="r7_monitoring_observations",
                        to="research.r7researchresultmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r7_monitoring_observation",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AddIndex(
            model_name="r7monitoringassessmentledgermodel",
            index=models.Index(
                fields=["result", "policy_hash", "ledger_recorded_at"],
                name="res_r7_mon_asmt_pit_ix",
            ),
        ),
        migrations.AddConstraint(
            model_name="r7monitoringassessmentledgermodel",
            constraint=models.UniqueConstraint(
                fields=("policy_id", "policy_version", "policy_hash", "evaluated_at"),
                name="res_r7_mon_asmt_cmd_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="r7monitoringassessmentledgermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("policy_recorded_at__lte", models.F("evaluated_at")),
                    ("result_recorded_at__lte", models.F("evaluated_at")),
                    ("lifecycle_recorded_at__lte", models.F("evaluated_at")),
                    ("calendar_recorded_at__lte", models.F("evaluated_at")),
                    ("realization_recorded_at__lte", models.F("evaluated_at")),
                    ("evaluated_at__lte", models.F("ledger_recorded_at")),
                    ("ledger_recorded_at__lt", models.F("owner_valid_until")),
                ),
                name="res_r7_mon_asmt_clock_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r7monitoringassessmentledgermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("healthy", "breached", "retirement_review_required", "blocked"))
                ),
                name="res_r7_mon_asmt_status_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r7monitoringassessmentledgermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("automatic_retirement", False),
                    ("must_not_execute", True),
                    ("must_not_publish_current", True),
                    ("must_not_use_for_decision", True),
                    ("research_only", True),
                ),
                name="res_r7_mon_asmt_safe_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="r7monitoringobservationledgermodel",
            index=models.Index(
                fields=["result", "period_id", "ledger_recorded_at"], name="res_r7_mon_obs_pit_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="r7monitoringobservationledgermodel",
            constraint=models.UniqueConstraint(
                fields=("assessment", "observation_index"), name="res_r7_mon_obs_index_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="r7monitoringobservationledgermodel",
            constraint=models.UniqueConstraint(
                fields=("assessment", "observation_id", "observation_version"),
                name="res_r7_mon_obs_ident_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="r7monitoringobservationledgermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("published_at__lt", models.F("horizon_end")),
                    ("horizon_end__lte", models.F("available_at")),
                    ("available_at__lte", models.F("owner_recorded_at")),
                    ("owner_recorded_at__lte", models.F("ledger_recorded_at")),
                ),
                name="res_r7_mon_obs_clock_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="r7monitoringobservationledgermodel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("must_not_execute", True),
                    ("must_not_publish_current", True),
                    ("must_not_use_for_decision", True),
                    ("research_only", True),
                ),
                name="res_r7_mon_obs_safe_ck",
            ),
        ),
    ]
