# Generated by Django 5.2.12 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0018_r7_result_family_lifecycle_ledgers"),
    ]

    operations = [
        migrations.CreateModel(
            name="R4MonitoringCalendarLedgerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_owner", models.CharField(max_length=192)),
                ("calendar_id", models.CharField(max_length=192)),
                ("calendar_version", models.CharField(max_length=192)),
                ("definition_hash", models.CharField(max_length=64)),
                ("source_receipt_id", models.CharField(max_length=192)),
                ("source_receipt_version", models.CharField(max_length=192)),
                ("source_receipt_hash", models.CharField(max_length=64)),
                ("source_receipt_payload", models.JSONField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("entry_count", models.PositiveIntegerField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_r4_monitoring_period_calendar",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["calendar_id", "calendar_version", "recorded_at"],
                        name="res_r4_mon_cal_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_owner", "calendar_id", "calendar_version"),
                        name="res_r4_mon_cal_ident_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("recorded_at__lte", models.F("valid_from")),
                            ("valid_from__lt", models.F("valid_until")),
                        ),
                        name="res_r4_mon_cal_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="res_r4_mon_cal_safe_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R4MonitoringPolicyLedgerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_id", models.CharField(max_length=192)),
                ("policy_version", models.CharField(max_length=192)),
                ("active_decision_id", models.CharField(max_length=192)),
                ("active_decision_version", models.CharField(max_length=192)),
                ("active_decision_hash", models.CharField(max_length=64)),
                ("definition_hash", models.CharField(max_length=64)),
                ("source_receipt_id", models.CharField(max_length=192)),
                ("source_receipt_version", models.CharField(max_length=192)),
                ("source_receipt_hash", models.CharField(max_length=64)),
                ("source_receipt_payload", models.JSONField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("active_from", models.DateTimeField()),
                ("active_until", models.DateTimeField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("ledger_header_hash", models.CharField(max_length=64)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_r4_monitoring_policy",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["policy_id", "policy_version", "recorded_at"],
                        name="res_r4_mon_pol_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy_id", "policy_version"),
                        name="res_r4_mon_pol_ident_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("active_from__lt", models.F("active_until")),
                            ("recorded_at__lte", models.F("active_from")),
                        ),
                        name="res_r4_mon_pol_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="res_r4_mon_pol_safe_ck",
                    ),
                ],
            },
        ),
    ]
