# Generated by Django 5.2.12 on 2026-08-11

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0019_r4_monitoring_owner_registry"),
    ]

    operations = [
        migrations.CreateModel(
            name="R1ForecastTrialEvidenceLedgerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evidence_id", models.CharField(max_length=192)),
                ("evidence_version", models.CharField(max_length=192)),
                ("definition_id", models.CharField(max_length=192)),
                ("definition_version", models.CharField(max_length=192)),
                ("definition_content_hash", models.CharField(max_length=64)),
                ("baseline_spec_id", models.CharField(max_length=192)),
                ("baseline_spec_version", models.CharField(max_length=192)),
                ("baseline_spec_content_hash", models.CharField(max_length=64)),
                ("baseline_artifact_id", models.CharField(max_length=192)),
                ("baseline_artifact_version", models.CharField(max_length=192)),
                ("baseline_artifact_content_hash", models.CharField(max_length=64)),
                ("baseline_spec_approved_at", models.DateTimeField()),
                ("activated_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("forecast_origin_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("canonical_payload", models.JSONField()),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_r1_forecast_trial_evidence",
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["evidence_id", "evidence_version", "recorded_at"],
                        name="res_r1_trial_ev_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("evidence_id", "evidence_version"),
                        name="res_r1_trial_ev_ident_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("definition_id", "definition_version"),
                        name="res_r1_trial_def_ident_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            baseline_spec_approved_at__lte=models.F("activated_at"),
                            activated_at__lte=models.F("recorded_at"),
                            recorded_at__lte=models.F("forecast_origin_at"),
                            forecast_origin_at__lt=models.F("valid_until"),
                        ),
                        name="res_r1_trial_ev_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            research_only=True,
                            must_not_use_for_decision=True,
                            must_not_execute=True,
                        ),
                        name="res_r1_trial_ev_safe_ck",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
