# Generated by Django 5.2.12 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0020_r1_forecast_trial_evidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="R2MarketStructureTrialPolicyLedgerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_id", models.CharField(max_length=192)),
                ("policy_version", models.CharField(max_length=192)),
                ("taxonomy_publication_id", models.CharField(max_length=192)),
                ("taxonomy_publication_version", models.CharField(max_length=192)),
                ("taxonomy_publication_hash", models.CharField(max_length=64)),
                ("taxonomy_artifact_hash", models.CharField(max_length=64)),
                ("calendar_publication_id", models.CharField(max_length=192)),
                ("calendar_publication_version", models.CharField(max_length=192)),
                ("calendar_publication_hash", models.CharField(max_length=64)),
                ("calendar_artifact_hash", models.CharField(max_length=64)),
                ("policy_registered_at", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("selection_as_of", models.DateTimeField()),
                ("active_from", models.DateTimeField()),
                ("active_until", models.DateTimeField()),
                ("canonical_payload", models.JSONField()),
                ("policy_content_hash", models.CharField(max_length=64, unique=True)),
                ("record_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                ("persisted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_r2_trial_policy_registry",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["policy_id", "policy_version", "ledger_recorded_at"],
                        name="res_r2_pol_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy_id", "policy_version"),
                        name="res_r2_pol_ident_uq",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(policy_registered_at__lte=models.F("ledger_recorded_at"))
                            & models.Q(ledger_recorded_at__lt=models.F("selection_as_of"))
                            & models.Q(active_from__lte=models.F("selection_as_of"))
                            & models.Q(selection_as_of__lt=models.F("active_until"))
                        ),
                        name="res_r2_pol_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            must_not_execute=True,
                            must_not_publish_current=True,
                            must_not_use_for_decision=True,
                            research_only=True,
                        ),
                        name="res_r2_pol_safe_ck",
                    ),
                ],
            },
        ),
    ]
