# Generated by Django 5.2.12 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the empty independent Research R8 monitoring policy registry."""

    dependencies = [("research", "0022_r5_monitoring_owner_registry")]

    operations = [
        migrations.CreateModel(
            name="R8MonitoringPolicyRegistryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_id", models.CharField(max_length=192)),
                ("policy_version", models.CharField(max_length=128)),
                ("policy_hash", models.CharField(max_length=64, unique=True)),
                ("definition_version", models.CharField(max_length=128)),
                ("definition_hash", models.CharField(max_length=64, unique=True)),
                ("source_receipt_id", models.CharField(max_length=192)),
                ("source_receipt_version", models.CharField(max_length=128)),
                ("source_receipt_hash", models.CharField(max_length=64, unique=True)),
                ("target_result_id", models.CharField(max_length=192)),
                ("target_result_hash", models.CharField(max_length=64)),
                ("target_receipt_id", models.CharField(max_length=192)),
                ("target_receipt_hash", models.CharField(max_length=64)),
                ("calendar_id", models.CharField(max_length=192)),
                ("calendar_version", models.CharField(max_length=128)),
                ("calendar_hash", models.CharField(max_length=64)),
                ("source_available_at", models.DateTimeField()),
                ("source_valid_until", models.DateTimeField()),
                ("policy_recorded_at", models.DateTimeField()),
                ("policy_valid_until", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("definition_payload", models.JSONField()),
                ("source_payload", models.JSONField()),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "research_r8_monitoring_policy_registry",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["policy_id", "policy_version", "ledger_recorded_at"],
                        name="res_r8_policy_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy_id", "policy_version"),
                        name="res_r8_policy_id_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("source_receipt_id", "source_receipt_version"),
                        name="res_r8_policy_source_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source_available_at__lte", models.F("ledger_recorded_at")),
                            ("policy_recorded_at__lte", models.F("ledger_recorded_at")),
                            ("ledger_recorded_at__lt", models.F("source_valid_until")),
                            ("ledger_recorded_at__lt", models.F("policy_valid_until")),
                        ),
                        name="res_r8_policy_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("definition_version", "research-r8-monitoring-policy-definition.v1"),
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                            (
                                "source_receipt_version",
                                "research-r8-monitoring-policy-source.v1",
                            ),
                        ),
                        name="res_r8_policy_safe_ck",
                    ),
                ],
            },
        )
    ]
