# Generated by Django 5.2.12 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the empty canonical R6 scope-to-qualification owner registry."""

    dependencies = [("research", "0023_r8_monitoring_policy_registry")]

    operations = [
        migrations.CreateModel(
            name="R6ScopeQualificationRegistryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("binding_id", models.CharField(max_length=300)),
                ("binding_version", models.CharField(max_length=128)),
                ("definition_version", models.CharField(max_length=128)),
                ("definition_hash", models.CharField(max_length=64, unique=True)),
                ("scope_id", models.CharField(db_index=True, max_length=300)),
                ("scope_version", models.CharField(max_length=128)),
                ("scope_hash", models.CharField(max_length=64, unique=True)),
                ("qualification_id", models.CharField(db_index=True, max_length=300)),
                ("qualification_hash", models.CharField(max_length=64)),
                ("source_receipt_id", models.CharField(max_length=300)),
                ("source_receipt_version", models.CharField(max_length=128)),
                ("source_receipt_hash", models.CharField(max_length=64, unique=True)),
                ("effective_at", models.DateTimeField()),
                ("definition_valid_until", models.DateTimeField()),
                ("source_available_at", models.DateTimeField()),
                ("source_valid_until", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("definition_payload", models.JSONField()),
                ("source_payload", models.JSONField()),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_replace_regime", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "research_r6_scope_qualification_registry",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["scope_id", "ledger_recorded_at"],
                        name="res_r6_scope_bind_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("binding_id", "binding_version"),
                        name="res_r6_scope_bind_id_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("scope_id", "scope_version"),
                        name="res_r6_scope_bind_scope_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("source_receipt_id", "source_receipt_version"),
                        name="res_r6_scope_bind_src_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_at__lte", models.F("ledger_recorded_at")),
                            ("source_available_at__lte", models.F("ledger_recorded_at")),
                            (
                                "ledger_recorded_at__lt",
                                models.F("definition_valid_until"),
                            ),
                            ("ledger_recorded_at__lt", models.F("source_valid_until")),
                        ),
                        name="res_r6_scope_bind_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "definition_version",
                                "research-r6-scope-qualification-definition.v1",
                            ),
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_replace_regime", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                            (
                                "source_receipt_version",
                                "research-r6-scope-qualification-source.v1",
                            ),
                        ),
                        name="res_r6_scope_bind_safe_ck",
                    ),
                ],
            },
        )
    ]
