# Generated by Django 5.2.12 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create empty Research-owned R7 analogy and path registries."""

    dependencies = [("research", "0024_r6_scope_qualification_registry")]

    operations = [
        migrations.CreateModel(
            name="R7HistoricalAnalogyDefinitionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("definition_id", models.CharField(max_length=300)),
                ("definition_version", models.CharField(max_length=128)),
                ("definition_hash", models.CharField(max_length=64, unique=True)),
                ("scope_hash", models.CharField(db_index=True, max_length=64)),
                ("study_version", models.CharField(max_length=128)),
                ("feature_definition_version", models.CharField(max_length=128)),
                ("similarity_method_version", models.CharField(max_length=128)),
                ("activated_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("definition_payload", models.JSONField()),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "research_r7_analogy_definition",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["scope_hash", "ledger_recorded_at"],
                        name="res_r7_an_def_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("definition_id", "definition_version"),
                        name="res_r7_an_def_id_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("activated_at__lte", models.F("ledger_recorded_at")),
                            ("ledger_recorded_at__lt", models.F("valid_until")),
                        ),
                        name="res_r7_an_def_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="res_r7_an_def_safe_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R7HistoricalAnalogyReceiptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_id", models.CharField(max_length=300)),
                ("receipt_version", models.CharField(max_length=128)),
                ("receipt_hash", models.CharField(max_length=64, unique=True)),
                ("scope_hash", models.CharField(db_index=True, max_length=64)),
                ("query_manifest_id", models.CharField(max_length=300)),
                ("query_manifest_version", models.CharField(max_length=128)),
                ("query_manifest_hash", models.CharField(max_length=64)),
                ("query_manifest_reference_hash", models.CharField(max_length=64)),
                ("query_as_of", models.DateTimeField()),
                ("source_available_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("definition_valid_until", models.DateTimeField()),
                ("receipt_payload", models.JSONField()),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="research.r7historicalanalogydefinitionmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r7_analogy_receipt",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["scope_hash", "query_as_of", "recorded_at"],
                        name="res_r7_an_rcpt_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("receipt_id", "receipt_version"),
                        name="res_r7_an_rcpt_id_uq",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(query_as_of__lte=models.F("source_available_at"))
                            & models.Q(source_available_at__lte=models.F("recorded_at"))
                            & models.Q(recorded_at__lt=models.F("definition_valid_until"))
                        ),
                        name="res_r7_an_rcpt_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("receipt_version", "r7-analogy-receipt.v1"),
                            ("research_only", True),
                        ),
                        name="res_r7_an_rcpt_safe_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R7HistoricalAnalogyCandidateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_id", models.CharField(max_length=300)),
                ("candidate_version", models.CharField(max_length=128)),
                ("candidate_hash", models.CharField(max_length=64)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("decision_cutoff", models.DateTimeField()),
                ("manifest_id", models.CharField(max_length=300)),
                ("manifest_version", models.CharField(max_length=128)),
                ("manifest_hash", models.CharField(max_length=64)),
                ("manifest_reference_hash", models.CharField(max_length=64)),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("candidate_payload", models.JSONField()),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="research.r7historicalanalogyreceiptmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r7_analogy_candidate",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["candidate_id", "decision_cutoff"],
                        name="res_r7_an_cand_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("receipt", "candidate_id", "candidate_version"),
                        name="res_r7_an_cand_id_uq",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(window_start__lt=models.F("window_end"))
                            & models.Q(window_end__lte=models.F("decision_cutoff"))
                            & models.Q(decision_cutoff__lte=models.F("ledger_recorded_at"))
                        ),
                        name="res_r7_an_cand_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="res_r7_an_cand_safe_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R7ScenarioPathDefinitionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("definition_id", models.CharField(max_length=300)),
                ("definition_version", models.CharField(max_length=128)),
                ("definition_hash", models.CharField(max_length=64, unique=True)),
                ("scope_hash", models.CharField(db_index=True, max_length=64)),
                ("study_version", models.CharField(max_length=128)),
                ("source_version", models.CharField(max_length=128)),
                ("sample_definition_version", models.CharField(max_length=128)),
                ("activated_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("definition_payload", models.JSONField()),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "research_r7_path_definition",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["scope_hash", "ledger_recorded_at"],
                        name="res_r7_path_def_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("definition_id", "definition_version"),
                        name="res_r7_path_def_id_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("activated_at__lte", models.F("ledger_recorded_at")),
                            ("ledger_recorded_at__lt", models.F("valid_until")),
                        ),
                        name="res_r7_path_def_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="res_r7_path_def_safe_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R7ScenarioPathReceiptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_id", models.CharField(max_length=300)),
                ("receipt_version", models.CharField(max_length=128)),
                ("receipt_hash", models.CharField(max_length=64, unique=True)),
                ("scope_hash", models.CharField(db_index=True, max_length=64)),
                ("pit_manifest_id", models.CharField(max_length=300)),
                ("pit_manifest_version", models.CharField(max_length=128)),
                ("pit_manifest_hash", models.CharField(max_length=64)),
                ("pit_manifest_reference_hash", models.CharField(max_length=64)),
                ("pit_as_of", models.DateTimeField()),
                ("source_available_at", models.DateTimeField()),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("definition_valid_until", models.DateTimeField()),
                ("receipt_payload", models.JSONField()),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="research.r7scenariopathdefinitionmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r7_path_receipt",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["scope_hash", "pit_as_of", "recorded_at"],
                        name="res_r7_path_rcpt_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("receipt_id", "receipt_version"),
                        name="res_r7_path_rcpt_id_uq",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(pit_as_of__lte=models.F("source_available_at"))
                            & models.Q(source_available_at__lte=models.F("recorded_at"))
                            & models.Q(recorded_at__lt=models.F("definition_valid_until"))
                        ),
                        name="res_r7_path_rcpt_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("receipt_version", "r7-path-receipt.v1"),
                            ("research_only", True),
                        ),
                        name="res_r7_path_rcpt_safe_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="R7ScenarioPathMemberModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_kind", models.CharField(max_length=16)),
                ("member_key", models.CharField(max_length=420)),
                ("member_version", models.CharField(max_length=128)),
                ("member_hash", models.CharField(max_length=64)),
                ("period_index", models.PositiveIntegerField()),
                ("resolution", models.CharField(blank=True, max_length=16)),
                ("from_scenario_revision_id", models.UUIDField(blank=True, null=True)),
                ("to_scenario_revision_id", models.UUIDField(blank=True, null=True)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("source_available_at", models.DateTimeField()),
                ("ledger_recorded_at", models.DateTimeField(db_index=True)),
                ("member_payload", models.JSONField()),
                ("ledger_header_hash", models.CharField(max_length=64, unique=True)),
                ("research_only", models.BooleanField(default=True)),
                ("must_not_publish_current", models.BooleanField(default=True)),
                ("must_not_use_for_decision", models.BooleanField(default=True)),
                ("must_not_execute", models.BooleanField(default=True)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="research.r7scenariopathreceiptmodel",
                    ),
                ),
            ],
            options={
                "db_table": "research_r7_path_member",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["member_kind", "period_index", "ledger_recorded_at"],
                        name="res_r7_path_mem_pit_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("receipt", "member_kind", "member_key"),
                        name="res_r7_path_mem_id_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("member_kind__in", ("sample", "shock"))),
                        name="res_r7_path_mem_kind_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(source_available_at__lte=models.F("ledger_recorded_at"))
                        & (
                            models.Q(observed_at__isnull=True)
                            | models.Q(observed_at__lte=models.F("source_available_at"))
                        ),
                        name="res_r7_path_mem_clock_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("member_kind", "sample"),
                                ("observed_at__isnull", False),
                                ("resolution", "resolved"),
                                ("to_scenario_revision_id__isnull", False),
                            ),
                            models.Q(
                                ("member_kind", "sample"),
                                ("observed_at__isnull", True),
                                (
                                    "resolution__in",
                                    ("unresolved", "censored", "invalidated"),
                                ),
                                ("to_scenario_revision_id__isnull", True),
                            ),
                            models.Q(
                                ("from_scenario_revision_id__isnull", True),
                                ("member_kind", "shock"),
                                ("observed_at__isnull", True),
                                ("resolution", ""),
                                ("to_scenario_revision_id__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="res_r7_path_mem_state_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("must_not_execute", True),
                            ("must_not_publish_current", True),
                            ("must_not_use_for_decision", True),
                            ("research_only", True),
                        ),
                        name="res_r7_path_mem_safe_ck",
                    ),
                ],
            },
        ),
    ]
