# Generated by Django 5.2.9 on 2025-12-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_at", models.DateField(db_index=True, unique=True)),
                ("growth_momentum_z", models.FloatField()),
                ("inflation_momentum_z", models.FloatField()),
                ("distribution", models.JSONField()),
                ("dominant_regime", models.CharField(max_length=20)),
                ("confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "regime_log",
                "ordering": ["-observed_at"],
            },
        ),
    ]
