# Generated by Django 5.2.10 on 2026-03-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regime", "0003_alter_regimeindicatorthreshold_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionRecommendationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_at", models.DateField(db_index=True, verbose_name="观测日期")),
                ("regime_name", models.CharField(max_length=20, verbose_name="当期 Regime")),
                ("pulse_strength", models.CharField(max_length=20, verbose_name="Pulse 强弱")),
                ("asset_weights", models.JSONField(default=dict, verbose_name="资产权重")),
                ("risk_budget_pct", models.FloatField(verbose_name="风险预算 %")),
                ("recommended_sectors", models.JSONField(default=list, verbose_name="推荐板块")),
                ("benefiting_styles", models.JSONField(default=list, verbose_name="受益风格")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "action_recommendation_log",
                "ordering": ["-observed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="regimelog",
            index=models.Index(fields=["dominant_regime"], name="regime_log_dominan_2f7ba2_idx"),
        ),
        migrations.AddIndex(
            model_name="regimelog",
            index=models.Index(fields=["observed_at"], name="regime_log_observe_6d74bb_idx"),
        ),
    ]
