# Generated by Django 5.2.12 on 2026-04-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regime", "0005_cleanup_active_thresholds_and_add_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionrecommendationlog",
            name="blocked_reason",
            field=models.TextField(blank=True, default="", verbose_name="阻断原因"),
        ),
        migrations.AddField(
            model_name="actionrecommendationlog",
            name="must_not_use_for_decision",
            field=models.BooleanField(default=False, verbose_name="禁止用于决策"),
        ),
    ]
