# Generated by Django 5.2.10 on 2026-02-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regime", "0002_regime_threshold_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="regimeindicatorthreshold",
            options={
                "ordering": ["indicator_code"],
                "verbose_name": "指标阈值",
                "verbose_name_plural": "指标阈值",
            },
        ),
        migrations.AlterModelOptions(
            name="regimetrendindicator",
            options={
                "ordering": ["indicator_code"],
                "verbose_name": "趋势指标",
                "verbose_name_plural": "趋势指标",
            },
        ),
        migrations.AlterField(
            model_name="regimeindicatorthreshold",
            name="level_high",
            field=models.FloatField(
                blank=True,
                help_text="高水平阈值（如 PMI > 50 为扩张）",
                null=True,
                verbose_name="高水平阈值",
            ),
        ),
        migrations.AlterField(
            model_name="regimeindicatorthreshold",
            name="level_low",
            field=models.FloatField(
                blank=True,
                help_text="低水平阈值（如 PMI < 50 为收缩）",
                null=True,
                verbose_name="低水平阈值",
            ),
        ),
        migrations.AlterField(
            model_name="regimethresholdconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="regimethresholdconfig",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="是否激活"),
        ),
        migrations.AlterModelTable(
            name="regimeindicatorthreshold",
            table="regime_regimeindicatorthreshold",
        ),
        migrations.AlterModelTable(
            name="regimethresholdconfig",
            table="regime_regimethresholdconfig",
        ),
        migrations.AlterModelTable(
            name="regimetrendindicator",
            table="regime_regimetrendindicator",
        ),
    ]
